import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s), canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x142e2b);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x17332e,.026);
const camera=new THREE.OrthographicCamera(-12,12,8,-8,.1,100);camera.position.set(15,20,23);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0x8cc6b0,0x26301d,2.1));const sun=new THREE.DirectionalLight(0xffe6af,3.2);sun.position.set(-8,18,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15});sun.shadow.bias=-.001;scene.add(sun);const moon=new THREE.DirectionalLight(0x6aaba7,2);moon.position.set(10,9,-12);scene.add(moon);
const materials={};function mat(color,extra={}){const key=color+JSON.stringify(extra);return materials[key]??=new THREE.MeshStandardMaterial({color,roughness:.9,...extra})}function mesh(geo,color,x=0,y=0,z=0,parent=scene,extra={}){const m=new THREE.Mesh(geo,mat(color,extra));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}const box=(w,h,d,c,x,y,z,p)=>mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p);const cyl=(rt,rb,h,n,c,x,y,z,p)=>mesh(new THREE.CylinderGeometry(rt,rb,h,n),c,x,y,z,p);const ico=(r,c,x,y,z,p,detail=0)=>mesh(new THREE.IcosahedronGeometry(r,detail),c,x,y,z,p);
let seed=37;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const environment=new THREE.Group();scene.add(environment);
// A layered, irregular floating diorama.
cyl(9,8.5,1.5,11,0x273f32,0,-1,0,environment);cyl(8.65,9,.45,11,0x466246,0,-.12,0,environment);cyl(8.38,8.6,.18,11,0x587447,0,.12,0,environment);
for(let i=0;i<42;i++){const a=i/42*Math.PI*2,r=8.45+rand()*.45;const rock=ico(.5+rand()*.65,0x334b3c,Math.cos(a)*r,-.55,Math.sin(a)*r,environment);rock.scale.set(1,1+rand(),.8)}
const floor=mesh(new THREE.PlaneGeometry(200,200),0x142d28,0,-2.1,0);floor.rotation.x=-Math.PI/2;
function tree(x,z,scale=1,type=0){const g=new THREE.Group();g.position.set(x,.2,z);g.scale.setScalar(scale);environment.add(g);cyl(.12,.24,2.4,6,0x5d5140,0,1,0,g);if(type){for(let k=0;k<3;k++){const m=cyl(0,1.35-k*.25,2.2,6,[0x274b38,0x365b3d,0x476747][k],0,2+k*.7,0,g);m.rotation.y=k*.45}}else{ico(1.25,0x486544,0,2.8,0,g);ico(.95,0x537649,.7,2.6,0,g);ico(1.05,0x35583e,-.6,2.5,.25,g)}return g}
for(let i=0;i<40;i++){const a=i/40*Math.PI*2,r=7.2+rand()*.65;const x=Math.cos(a)*r,z=Math.sin(a)*r;if(z>2.5&&x>-6&&x<7)continue;tree(x,z,.72+rand()*.52,i%3!==0)}
for(let i=0;i<28;i++){let x=(rand()-.5)*14,z=(rand()-.5)*14;if(Math.hypot(x,z)>7.3||Math.hypot(x,z)<5.3)continue;ico(.27+rand()*.35,0x536b50,x,.3,z,environment)}
// Curved stepping stone trail and tiny wildflowers.
for(let i=0;i<24;i++){let x=-5.7+i*.49,z=1.9+Math.sin(i*.24)*.85;const s=cyl(.23+rand()*.16,.3,.055,6,0x8c9575,x,.235,z,environment);s.rotation.y=rand()*6;s.scale.z=.7}
for(let i=0;i<160;i++){const x=(rand()-.5)*15,z=(rand()-.5)*14;if(Math.hypot(x,z)>8)continue;const g=new THREE.Group();g.position.set(x,.22,z);environment.add(g);for(let j=0;j<3;j++){const blade=mesh(new THREE.ConeGeometry(.035,.18+rand()*.15,3),i%6===0?0xa6b97a:0x718450,(rand()-.5)*.2,.13,(rand()-.5)*.2,g);blade.rotation.z=(rand()-.5)*.7}if(i%8===0)ico(.045,0xf0d38b,0,.32,0,g)}
// Mossy arch, the sleeping forest sanctuary.
const arch=new THREE.Group();arch.position.set(3,.2,-3.8);environment.add(arch);for(const x of [-.95,.95]){box(.48,1.5,.6,0x7f8a6b,x,.75,0,arch);box(.65,.2,.75,0x9a9d7b,x,1.45,0,arch);ico(.3,0x617947,x,1.62,0,arch)}box(2.5,.38,.7,0x8c9273,0,1.8,0,arch);box(2.8,.18,.82,0x64784d,0,2.05,0,arch);const archRune=mesh(new THREE.OctahedronGeometry(.24),0xcfb97a,0,1.83,.39,arch,{emissive:0x5d461c,emissiveIntensity:.8});
// Little fox: geometry only, no external assets.
const fox=new THREE.Group();scene.add(fox);const foxVisual=new THREE.Group();foxVisual.scale.setScalar(1.2);fox.add(foxVisual);const body=box(.48,.45,.78,0xd57a36,0,.52,0,foxVisual);const chest=box(.36,.32,.25,0xffe5bc,0,.47,.36,foxVisual);const head=box(.49,.43,.46,0xe99042,0,.87,.37,foxVisual);const muzzle=mesh(new THREE.ConeGeometry(.21,.38,4),0xffe1b3,0,.77,.68,foxVisual);muzzle.rotation.x=Math.PI/2;muzzle.rotation.z=Math.PI/4;box(.13,.1,.08,0x302c24,0,.8,.88,foxVisual);for(const x of [-.19,.19]){const ear=mesh(new THREE.ConeGeometry(.15,.35,3),0xd87934,x,1.2,.31,foxVisual);ear.rotation.z=x>.0?-.17:.17;const inner=mesh(new THREE.ConeGeometry(.085,.22,3),0x593d30,x,1.22,.37,foxVisual);box(.055,.085,.035,0x222a22,x*.88,.92,.607,foxVisual)}const legs=[];for(const x of [-.17,.17])for(const z of [-.24,.25]){const leg=box(.12,.3,.13,0x673f2a,x,.23,z,foxVisual);legs.push(leg)}const tail=new THREE.Group();tail.position.set(0,.53,-.37);tail.rotation.x=-.52;foxVisual.add(tail);const t=mesh(new THREE.ConeGeometry(.25,.8,5),0xde8238,0,.15,-.25,tail);t.rotation.x=-Math.PI/2;const tip=mesh(new THREE.ConeGeometry(.19,.32,5),0xffe4ba,0,.15,-.7,tail);tip.rotation.x=-Math.PI/2;
const foxRing=mesh(new THREE.RingGeometry(.36,.39,40),0xeed391,0,.255,0,fox,{transparent:true,opacity:.55,side:THREE.DoubleSide});foxRing.rotation.x=-Math.PI/2;
const levels=[{name:'初光林地',source:[-5,0],mirrors:[[-2,0,3],[-2,3,0],[3,3,1]],goals:[[-2,1.5],[.5,3],[3,-2]],solution:[1,1,3],names:['点亮苔石上的光之芽','连接林间的琥珀水晶','唤醒沉睡的森林圣坛']},{name:'月影回廊',source:[-5,-2],mirrors:[[-3,-2,0],[-3,2,2],[1,2,0],[1,-2,1]],goals:[[-3,0],[-1,2],[4,-2]],solution:[1,1,3,3],names:['让光穿过月影石','唤醒回廊的双生水晶','将微光送往东侧圣坛']},{name:'星河归途',source:[-5,-3],mirrors:[[-2,-3,2],[-2,2,0],[3,2,1],[3,-1,0],[0,-1,2]],goals:[[-2,0],[3,.5],[0,4]],solution:[1,1,3,1,3],names:['照亮古树的记忆','穿过最后的星河水晶','点燃森林之心']}];
let levelIndex=0,selected=-1,elapsed=0,paused=false,won=false,moves=0,collected=0,sound=false,audio=null,foxTarget=null,toastTimeout;let mirrorData=[],goalData=[],stars=[],segments=[],lightStates=[];const puzzle=new THREE.Group();scene.add(puzzle);let beams=new THREE.Group();scene.add(beams);const keys={};const savedKey='foxlight-journey-v1';let best=0;try{best=Number(localStorage.getItem(savedKey)||0)}catch{}
const fireflyPositions=new Float32Array(100*3);for(let i=0;i<100;i++){fireflyPositions[i*3]=(rand()-.5)*20;fireflyPositions[i*3+1]=.4+rand()*4;fireflyPositions[i*3+2]=(rand()-.5)*17}const fg=new THREE.BufferGeometry();fg.setAttribute('position',new THREE.BufferAttribute(fireflyPositions,3));const fireflies=new THREE.Points(fg,new THREE.PointsMaterial({color:0xe5d9a0,size:.055,transparent:true,opacity:.8}));scene.add(fireflies);
function disposeGroup(group){group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.userData.uniqueMaterial)o.material.dispose()});group.clear()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),4200)}
function chime(freq=440){if(!sound)return;audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.6);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.6)}
function buildLevel(index){levelIndex=index;const l=levels[index];disposeGroup(puzzle);disposeGroup(beams);mirrorData=[];goalData=[];stars=[];selected=-1;elapsed=0;moves=0;collected=0;won=false;paused=false;foxTarget=null;lightStates=[];fox.position.set(-4,.05,3.6);fox.rotation.y=.4;$('#chapter-name').innerHTML=`0${index+1} <i>/</i> ${l.name}`;$('#objectives').innerHTML=l.names.map(t=>`<div class="objective"><span class="circle"></span><span>${t}</span></div>`).join('');document.querySelectorAll('.right-rail>span').forEach((s,i)=>s.classList.toggle('active',i===index));$('#continue-journey').hidden=true;$('#dust-count').textContent=0;$('#journal-count').textContent=Math.max(best,index);$('#mirror-panel').classList.remove('visible');
const [sx,sz]=l.source;cyl(.55,.66,.25,8,0x737d5c,sx,.34,sz,puzzle);cyl(.2,.3,.9,6,0x8a9268,sx,.85,sz,puzzle);const source=mesh(new THREE.OctahedronGeometry(.32),0xffe7a2,sx,1.48,sz,puzzle,{emissive:0xffd66c,emissiveIntensity:3});source.rotation.z=Math.PI/2;const lamp=new THREE.PointLight(0xffd784,8,5);lamp.position.set(sx,1.6,sz);puzzle.add(lamp);const halo=mesh(new THREE.TorusGeometry(.46,.025,6,40),0xd4b574,sx,1.48,sz,puzzle);halo.rotation.y=Math.PI/2;
l.mirrors.forEach(([x,z,a],i)=>{const group=new THREE.Group();group.position.set(x,.2,z);puzzle.add(group);cyl(.46,.53,.18,8,0x949578,0,.13,0,group);cyl(.33,.4,.13,8,0x667456,0,.27,0,group);box(.13,.68,.13,0xb5a077,0,.64,0,group);const pivot=new THREE.Group();pivot.position.y=1.24;group.add(pivot);box(1.03,1.07,.11,0xbfae7e,0,0,0,pivot);const surface=mesh(new THREE.BoxGeometry(.85,.89,.13),0xa4d5cb,0,0,0,pivot,{metalness:.75,roughness:.15,emissive:0x326458,emissiveIntensity:.3});for(const dx of [-.49,.49]){ico(.075,0xdbc58c,dx,.52,0,pivot);ico(.075,0xdbc58c,dx,-.52,0,pivot)}const ring=mesh(new THREE.RingGeometry(.57,.6,48),0xf2d790,0,.305,0,group,{side:THREE.DoubleSide,transparent:true,opacity:0});ring.rotation.x=-Math.PI/2;ring.material=ring.material.clone();ring.userData.uniqueMaterial=true;const hitbox=mesh(new THREE.BoxGeometry(1.3,1.8,1.3),0xffffff,0,.9,0,group,{visible:false});hitbox.userData.mirror=i;mirrorData.push({x,z,a,pivot,ring,hitbox});pivot.rotation.y=-a*Math.PI/4});
l.goals.forEach(([x,z],i)=>{const group=new THREE.Group();group.position.set(x,.2,z);puzzle.add(group);cyl(.47,.57,.18,6,0x8a9370,0,.12,0,group);cyl(.25,.35,.5,5,0x657453,0,.44,0,group);const crystal=mesh(new THREE.OctahedronGeometry(i===2?.4:.24),0x83aba0,0,1.2,0,group,{emissive:0xffd17b,emissiveIntensity:0,metalness:.25,roughness:.25});crystal.material=crystal.material.clone();crystal.userData.uniqueMaterial=true;crystal.scale.y=1.4;const glow=new THREE.PointLight(0xffd879,0,3);glow.position.y=1.3;group.add(glow);const ring=mesh(new THREE.TorusGeometry(.36,.016,5,32),0xc8b77e,0,.88,0,group);ring.rotation.x=Math.PI/2;goalData.push({x,z,crystal,glow,lit:false})});
const coords=[[-4,2],[-.5,4.2],[4.6,1.2],[1.5,-3.8],[-4.7,-3.7]];coords.forEach(([x,z],i)=>{const star=mesh(new THREE.OctahedronGeometry(.12),0xffe6a7,x,.75,z,puzzle,{emissive:0xf8c86b,emissiveIntensity:2});stars.push({x,z,mesh:star,taken:false,phase:i})});traceLight();}
function cross(ax,az,bx,bz){return ax*bz-az*bx}
function traceLight(){disposeGroup(beams);segments=[];const l=levels[levelIndex];let p=new THREE.Vector2(...l.source),d=new THREE.Vector2(1,0),previous=-1;for(let bounce=0;bounce<16;bounce++){let distance=17,target=-1;mirrorData.forEach((m,i)=>{if(i===previous)return;const a=m.a*Math.PI/4,v=new THREE.Vector2(Math.cos(a),Math.sin(a)),ax=m.x-v.x*.6,az=m.z-v.y*.6;const denom=cross(d.x,d.y,v.x,v.y);if(Math.abs(denom)<.00001)return;const t=cross(ax-p.x,az-p.y,v.x,v.y)/denom,u=cross(ax-p.x,az-p.y,d.x,d.y)/denom;if(t>.01&&u>=0&&u<=1.2&&t<distance){distance=t;target=i}});let end=p.clone().addScaledVector(d,distance);if(target===-1){for(let t=.05;t<distance;t+=.05){if(p.clone().addScaledVector(d,t).length()>8){distance=t;end=p.clone().addScaledVector(d,t);break}}}segments.push({start:p.clone(),end:end.clone()});drawBeam(p,end);if(target===-1)break;const m=mirrorData[target],a=m.a*Math.PI/4,v=new THREE.Vector2(Math.cos(a),Math.sin(a));d=v.multiplyScalar(2*d.dot(v)).sub(d).normalize();p=end;previous=target}
let total=0;goalData.forEach((g,i)=>{const pt=new THREE.Vector2(g.x,g.z);g.lit=segments.some(s=>{const v=s.end.clone().sub(s.start),t=THREE.MathUtils.clamp(pt.clone().sub(s.start).dot(v)/v.lengthSq(),0,1);return pt.distanceTo(s.start.clone().addScaledVector(v,t))<.33});if(g.lit)total++;g.crystal.material.emissiveIntensity=g.lit?2.5:0;g.crystal.material.color.setHex(g.lit?0xffe6a2:0x83aba0);g.glow.intensity=g.lit?5:0;const el=document.querySelectorAll('.objective')[i];el.classList.toggle('done',g.lit);el.querySelector('.circle').textContent=g.lit?'✓':'';if(g.lit&&!lightStates[i])chime(523+i*130);lightStates[i]=g.lit});$('#progress').textContent=`${total}/3`;archRune.material.emissiveIntensity=total===3?4:.4;if(total===3&&!won){won=true;$('#continue-journey').hidden=false;best=Math.max(best,levelIndex+1);try{localStorage.setItem(savedKey,String(best))}catch{}$('#journal-count').textContent=best;const completedIndex=levelIndex;setTimeout(()=>{if(won&&levelIndex===completedIndex)showWin()},900)}}
function drawBeam(a,b){const start=new THREE.Vector3(a.x,1.44,a.y),end=new THREE.Vector3(b.x,1.44,b.y),delta=end.clone().sub(start),length=delta.length();for(const [radius,opacity] of [[.018,1],[.045,.18],[.105,.035]]){const material=new THREE.MeshBasicMaterial({color:0xffd178,transparent:true,opacity,depthWrite:false,toneMapped:false});const ray=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,length,6),material);ray.userData.uniqueMaterial=true;ray.position.copy(start).add(end).multiplyScalar(.5);ray.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());beams.add(ray)}}
function selectMirror(i){selected=i;mirrorData.forEach((m,k)=>m.ring.material.opacity=k===i?.8:0);$('#mirror-panel').classList.add('visible');$('#mirror-name').textContent=`林间镜 · 0${i+1}`;$('#angle').textContent=`${mirrorData[i].a*45}°`;chime(330)}
function rotate(dir){if(paused||won)return;if(selected<0){let near=0,dist=Infinity;mirrorData.forEach((m,i)=>{const d=Math.hypot(fox.position.x-m.x,fox.position.z-m.z);if(d<dist){near=i;dist=d}});selectMirror(near)}const m=mirrorData[selected];m.a=(m.a+dir+4)%4;m.pivot.rotation.y=-m.a*Math.PI/4;moves++;$('#angle').textContent=`${m.a*45}°`;traceLight();chime(280+40*m.a)}
function showModal(html){paused=true;keys.w=keys.a=keys.s=keys.d=false;$('#modal-content').innerHTML=html;$('#modal-backdrop').hidden=false}function closeModal(){paused=false;$('#modal-backdrop').hidden=true;$('#pause').textContent='Ⅱ'}function showWin(){chime(880);showModal(`<div class="modal-icon">✺</div><span class="tiny">A LITTLE LIGHT GOES A LONG WAY</span><h2>${levelIndex===2?'森林，重新亮起来了。':'一束微光，一次新生。'}</h2><p>${levelIndex===2?'你带着小狐狸穿过了三片林地。古老的镜子重新连接了星光，森林会记得你。':'沉睡的水晶已被唤醒。前方的林地里，还有更多迷失的光，等着与你相遇。'}</p><div class="stat">◷ ${formatTime(elapsed)}</div><div class="stat">◇ ${moves} 次旋转</div><div class="stat">✦ ${collected}/5 星屑</div><br><button class="primary" id="next-level">${levelIndex===2?'再走一次光的旅程':'前往下一片森林 →'}</button><button class="text-button" id="keep-exploring">留在这里，继续收集星屑</button>`);$('#next-level').onclick=()=>{closeModal();buildLevel((levelIndex+1)%3);toast('新的光线谜题已经出现。点击镜子，继续你的旅程。')};$('#keep-exploring').onclick=closeModal}
function hint(){if(paused)return;const l=levels[levelIndex];let i=mirrorData.findIndex((m,j)=>m.a!==l.solution[j]);if(i<0){toast('光已归位！去收集散落的星屑吧。');return}selectMirror(i);toast(`森林低语：第 ${i+1} 面镜子的光，需要沿 ${l.solution[i]*45}° 的镜面转弯。`)}
$('#continue-journey').onclick=showWin;$('#rotate-left').onclick=()=>rotate(-1);$('#rotate-right').onclick=()=>rotate(1);$('#deselect').onclick=()=>{selected=-1;mirrorData.forEach(m=>m.ring.material.opacity=0);$('#mirror-panel').classList.remove('visible')};$('#hint').onclick=hint;$('#modal-close').onclick=closeModal;$('#modal-backdrop').onclick=e=>{if(e.target===$('#modal-backdrop'))closeModal()};$('#help').onclick=()=>showModal('<div class="modal-icon">✧</div><span class="tiny">HOW TO PLAY</span><h2>跟着光，慢慢走。</h2><p><b>W A S D / 方向键</b> 移动小狐狸，也可以点击地面前往。<br><b>点击镜子</b> 选中，再用 <b>Q / E</b> 或下方按钮旋转 45°。<br>让金色光束依次经过三枚水晶，即可唤醒森林。<br><b>靠近星屑</b> 自动收集，全部找到会得到特别的祝福。<br><b>空格</b> 获得提示 · <b>R</b> 重置当前关卡 · <b>Esc</b> 暂停。</p><p>这里没有倒计时，也不必着急。森林会等你。</p>');$('#pause').onclick=()=>{if(paused){closeModal();return}showModal('<div class="modal-icon">☾</div><span class="tiny">TAKE A LITTLE BREATH</span><h2>森林也在休息。</h2><p>旅程已暂停。关闭窗口，即可继续追寻微光。</p>');$('#pause').textContent='▷'};$('#sound').onclick=()=>{sound=!sound;$('#sound').style.color=sound?'#f1ce88':'';$('#sound').textContent=sound?'♫':'♪';toast(sound?'林间音效已开启':'林间音效已关闭');chime(660)};$('#journal').onclick=()=>showModal(`<div class="modal-icon">▧</div><span class="tiny">THE FOREST JOURNAL</span><h2>写给追光的你。</h2><p>「很久以前，森林的光被留在了一面面镜子里。只有愿意停下脚步的小小旅人，才能让它们再次相遇。」</p><p>${best>=1?'✦ 初光林地：光会沿着镜面，以相同的角度离开。':'○ 初光林地：唤醒圣坛，解锁第一段记忆。'}<br>${best>=2?'✦ 月影回廊：有时，回头也是前往终点的路。':'○ 月影回廊：尚未找回的记忆。'}<br>${best>=3?'✦ 星河归途：你寻找的光，也在寻找你。':'○ 星河归途：尚未找回的记忆。'}</p><p>已找回 ${best}/3 段森林记忆 · 本关星屑 ${collected}/5</p>`);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),-.25);canvas.addEventListener('pointerdown',e=>{if(paused)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(mirrorData.map(m=>m.hitbox));if(hit.length){selectMirror(hit[0].object.userData.mirror);return}const target=new THREE.Vector3();if(raycaster.ray.intersectPlane(ground,target)&&Math.hypot(target.x,target.z)<7.4)foxTarget=target});canvas.addEventListener('pointermove',e=>{pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);canvas.style.cursor=raycaster.intersectObjects(mirrorData.map(m=>m.hitbox)).length?'pointer':'default'});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(e.repeat)return;if(k==='escape'){$('#modal-backdrop').hidden?$('#pause').click():closeModal();return}if(paused)return;if(k==='q')rotate(-1);if(k==='e')rotate(1);if(k===' ')hint();if(k==='r'){buildLevel(levelIndex);toast('光回到了最初的地方。再试一次吧。')}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false)});document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys[b.dataset.move]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.move]=false});
function formatTime(s){return`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`}
function resize(){renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight,h=innerWidth<600?9/aspect:9;camera.left=-h*aspect;camera.right=h*aspect;camera.top=h;camera.bottom=-h;camera.setViewOffset(innerWidth,innerHeight,innerWidth<600?-innerWidth*.02:-innerWidth*.12,innerWidth<600?-innerHeight*.12:0,innerWidth,innerHeight);camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();buildLevel(0);
let last=performance.now(),time=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.04);last=now;if(!paused){time+=dt;if(!won)elapsed+=dt;$('#timer').textContent=formatTime(elapsed);let mx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),mz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let movement=new THREE.Vector3(mx*.84+mz*.54,0,-mx*.54+mz*.84);if(mx||mz)foxTarget=null;else if(foxTarget){movement.copy(foxTarget).sub(fox.position);movement.y=0;if(movement.length()<.15){foxTarget=null;movement.set(0,0,0)}}const moving=movement.length()>.01;if(moving){movement.normalize();const next=fox.position.clone().addScaledVector(movement,dt*2.8);if(Math.hypot(next.x,next.z)<7.5)fox.position.copy(next);const desired=Math.atan2(movement.x,movement.z);fox.rotation.y+=Math.atan2(Math.sin(desired-fox.rotation.y),Math.cos(desired-fox.rotation.y))*Math.min(1,dt*13);foxVisual.position.y=Math.sin(time*15)*.035;legs.forEach((leg,i)=>leg.rotation.x=Math.sin(time*15+i%2*Math.PI)*.38)}else{foxVisual.position.y=Math.sin(time*2)*.018;legs.forEach(l=>l.rotation.x=0)}tail.rotation.y=Math.sin(time*4)*.12;stars.forEach(st=>{if(st.taken)return;st.mesh.position.y=.8+Math.sin(time*2+st.phase)*.13;st.mesh.rotation.y=time;if(Math.hypot(fox.position.x-st.x,fox.position.z-st.z)<.55){st.taken=true;st.mesh.visible=false;collected++;$('#dust-count').textContent=collected;chime(800+collected*90);toast(collected===5?'✦ 星屑已集齐！你得到了森林的祝福。':`✦ 拾起一枚森林星屑 · ${collected}/5`)}});goalData.forEach((g,i)=>{g.crystal.rotation.y=time*.35;g.crystal.position.y=1.2+Math.sin(time*1.5+i)*.035});fireflies.rotation.y=Math.sin(time*.06)*.1;fireflies.position.y=Math.sin(time*.4)*.1;mirrorData.forEach((m,i)=>{if(i===selected)m.ring.material.opacity=.5+Math.sin(time*3)*.25})}renderer.render(scene,camera)}requestAnimationFrame(animate);setTimeout(()=>{$('#loading').style.opacity=0;setTimeout(()=>$('#loading').remove(),650)},600);
// Small debug surface for deterministic gameplay checks.
window.foxlight={get state(){return{level:levelIndex,mirrors:mirrorData.map(m=>m.a),lit:goalData.map(g=>g.lit),won,collected,segments:segments.length}},solve(){levels[levelIndex].solution.forEach((a,i)=>{mirrorData[i].a=a;mirrorData[i].pivot.rotation.y=-a*Math.PI/4});traceLight()},level:buildLevel};
