export const DIRS = [[0,-1],[0,1],[-1,0],[1,0]];
export const LEVELS = [
 {name:'早餐准备时间',difficulty:'初次见面',description:'把木箱推到餐垫上，早餐就准备好啦。',tip:'木箱只能推，不能拉。绕到它的另一边试试。',map:['#########','#.......#','#..g.g..#','#..b.b..#','#.......#','#...p...#','#.......#','#########'],seeds:[[2,5],[6,4],[4,1]],par:12},
 {name:'曲奇小径',difficulty:'绕个小弯',description:'绕过面粉袋，找到通往餐垫的小路。',tip:'先观察木箱周围，给自己留一条退路。',map:['#########','#...g...#','#.#...#.#','#..b.b..#','#...#...#','#.p...g.#','#.......#','#########'],seeds:[[1,1],[7,5],[4,2]],par:24},
 {name:'双份甜蜜',difficulty:'默契配合',description:'三份早餐，考验一点点整理的智慧。',tip:'别把木箱推到没有餐垫的角落哦。',map:['#########','#.g.g.g.#','#.......#','#.b.b.b.#','#..#.#..#','#...p...#','#.......#','#########'],seeds:[[1,4],[7,4],[4,1]],par:30},
 {name:'冰镇柠檬汽水',difficulty:'滑行时刻',description:'冰块好滑！木箱会滑到冰面的尽头。',tip:'蓝色冰面会让木箱持续滑行，直到离开冰面。',map:['#########','#.......#','#.giib..#','#.......#','#..biig.#','#...p...#','#.......#','#########'],seeds:[[1,2],[7,5],[4,1]],par:25},
 {name:'秘密储藏间',difficulty:'机关巧思',description:'站上薄荷按钮，或用木箱压住它，打开栅栏。',tip:'你和木箱都能压住按钮；松开时，栅栏会关闭。',map:['#########','#...#...#','#..sDs..#','#.b.#...#','#...#.g.#','#pb.#.g.#','#...#...#','#########'],seeds:[[1,1],[6,1],[7,6]],par:48},
 {name:'栗栗的早餐派对',difficulty:'厨房高手',description:'冰面、机关和三只木箱，最后的早餐挑战！',tip:'先安排最远处的箱子，再准备大家的早餐。',map:['#########','#...#.g.#','#.bsDs..#','#...#ii.#','#.b.#.g.#','#.b.#.i.#','#p..#.g.#','#########'],seeds:[[1,1],[7,1],[7,6]],par:65}
];
export const key = (x,y)=>`${x},${y}`;
export function createState(level){let boxes=[], player, goals=[],ice=[],switches=[],gates=[];level.map.forEach((r,y)=>[...r].forEach((c,x)=>{if(c==='b')boxes.push([x,y]);if(c==='p')player=[x,y];if(c==='g')goals.push([x,y]);if(c==='i')ice.push([x,y]);if(c==='s')switches.push([x,y]);if(c==='D')gates.push([x,y]);}));return {player,boxes,goals,ice,switches,gates,collected:[],moves:0,pushes:0};}
const has=(list,x,y)=>list.some(p=>p[0]===x&&p[1]===y);
export function gateOpen(s){return s.switches.some(([x,y])=>has(s.boxes,x,y)||(s.player[0]===x&&s.player[1]===y));}
export function move(level,s,d){const [dx,dy]=DIRS[d], [x,y]=s.player, nx=x+dx,ny=y+dy;const open=gateOpen(s);const blocked=(a,b)=>!level.map[b]||!level.map[b][a]||level.map[b][a]==='#'||(has(s.gates,a,b)&&!open);if(blocked(nx,ny))return null;const next={...s,player:[nx,ny],boxes:s.boxes.map(p=>[...p]),collected:[...s.collected],moves:s.moves+1};const bi=s.boxes.findIndex(p=>p[0]===nx&&p[1]===ny);if(bi>=0){let bx=nx+dx,by=ny+dy;if(blocked(bx,by)||has(s.boxes,bx,by))return null;while(has(s.ice,bx,by)&&!blocked(bx+dx,by+dy)&&!has(s.boxes,bx+dx,by+dy)){bx+=dx;by+=dy;}next.boxes[bi]=[bx,by];next.pushes=s.pushes+1;}const seed=level.seeds.findIndex(p=>p[0]===nx&&p[1]===ny);if(seed>=0&&!next.collected.includes(seed))next.collected.push(seed);return next;}
export const filled=s=>s.boxes.filter(([x,y])=>has(s.goals,x,y)).length;
export const won=s=>filled(s)===s.goals.length;
export function solve(level,start,max=150000){const encode=s=>key(...s.player)+'|'+s.boxes.map(p=>key(...p)).sort().join(';');let q=[{s:start,parent:-1,d:-1}],seen=new Set([encode(start)]),i=0;while(i<q.length&&q.length<max){let n=q[i];if(won(n.s)){let path=[];while(n.parent>=0){path.push(n.d);n=q[n.parent];}return path.reverse();}for(let d=0;d<4;d++){const s=move(level,n.s,d);if(!s)continue;const k=encode(s);if(seen.has(k))continue;const dead=s.boxes.some(([x,y])=>{if(has(s.goals,x,y))return false;const wall=(a,b)=>!level.map[b]||level.map[b][a]==='#';return (wall(x-1,y)||wall(x+1,y))&&(wall(x,y-1)||wall(x,y+1));});if(dead)continue;seen.add(k);q.push({s,parent:i,d});}i++;}return null;}
