import {createKitchen} from './scene.js';
import {LEVELS,createState,move,filled,won,solve} from './engine.js';
const $=id=>document.getElementById(id);let saved={level:0,completed:{},sound:true};try{saved={...saved,...JSON.parse(localStorage.getItem('hamster-kitchen-v1')||'{}')};}catch{}if(!Number.isInteger(saved.level)||saved.level<0||saved.level>=LEVELS.length)saved.level=0;if(!saved.completed||typeof saved.completed!=='object')saved.completed={};
let index=saved.level,state,history=[],elapsed=0,started=false,complete=false,lastMove=0,timerId,winTimeout,toastTimeout,hintWorker,hintBusy=false;const kitchen=createKitchen($('scene'));let audio;
function persist(){try{localStorage.setItem('hamster-kitchen-v1',JSON.stringify(saved));}catch{}}
function tone(freq=440,duration=.1,volume=.04){if(!saved.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.7,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function toast(text){clearTimeout(toastTimeout);$('toast').textContent=text;$('toast').classList.add('visible');toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
function updateUI(){const n=filled(state);$('goals').innerHTML=`${n} <em>/ ${state.goals.length}</em>`;$('goal-progress').style.width=`${n/state.goals.length*100}%`;$('moves').textContent=String(state.moves).padStart(2,'0');$('seeds').innerHTML=`${state.collected.length} <em>/ ${LEVELS[index].seeds.length}</em>`;$('undo').disabled=!history.length;updateTime();}
function updateTime(){$('timer').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;}
function load(i){clearTimeout(winTimeout);clearTimeout(toastTimeout);$('toast').classList.remove('visible');hintWorker?.terminate();hintWorker=null;hintBusy=false;$('hint').disabled=false;index=i;saved.level=i;persist();state=createState(LEVELS[i]);history=[];elapsed=0;started=false;complete=false;const l=LEVELS[i];$('level-number').textContent=`LEVEL ${String(i+1).padStart(2,'0')} / 06`;$('level-title').textContent=l.name;$('level-description').textContent=l.description;$('difficulty').textContent=l.difficulty;$('tip').textContent=l.tip;kitchen.build(l,state);updateUI();if($('modal').open)$('modal').close();}
function step(d){if(complete||$('modal').open||hintBusy)return;const now=performance.now();if(now-lastMove<125)return;lastMove=now;const next=move(LEVELS[index],state,d);if(!next){tone(150,.06,.015);return;}history.push(state);const wasFilled=filled(state),seeds=state.collected.length,push=next.pushes>state.pushes;state=next;started=true;kitchen.update(state);updateUI();tone(push?190:340,.075,.018);if(state.collected.length>seeds){tone(1000,.2);toast('✦ 收到一颗葵花籽，栗栗超开心！');}if(filled(state)>wasFilled)tone(700,.22);if(won(state)){complete=true;const stars=1+(state.collected.length===LEVELS[index].seeds.length?1:0)+(state.moves<=LEVELS[index].par?1:0);const old=saved.completed[index];saved.completed[index]={stars:Math.max(old?.stars||0,stars),moves:Math.min(old?.moves||Infinity,state.moves)};persist();kitchen.celebrate();[660,830,990].forEach((f,i)=>setTimeout(()=>tone(f,.25),i*130));winTimeout=setTimeout(()=>showWin(stars),850);}}
function undo(){if(!history.length||hintBusy)return;clearTimeout(winTimeout);complete=false;state=history.pop();kitchen.update(state);updateUI();tone(260,.1);}
function modal(content){$('modal-content').innerHTML=content;if(!$('modal').open)$('modal').showModal();}
function showLevels(){modal(`<div class="modal-label">THE LITTLE ADVENTURE</div><h2>栗栗的厨房地图</h2><p>六段小小的冒险，随时选择你想去的地方。</p><div class="level-grid">${LEVELS.map((l,i)=>`<button class="level-option ${i===index?'current':''}" data-level="${i}"><span>0${i+1} ${saved.completed[i]?'★'.repeat(saved.completed[i].stars):'◇'}</span><b>${l.name}</b><small>${l.difficulty}${saved.completed[i]?' · 最佳 '+saved.completed[i].moves+' 步':''}</small></button>`).join('')}</div>`);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>load(Number(b.dataset.level)));}
function showJournal(){modal(`<div class="modal-label">A HAMSTER'S FIELD GUIDE</div><h2>小爪爪冒险手册</h2><p>我是栗栗，一只对厨房充满好奇的仓鼠。今天的任务，是把早餐箱送到橙色餐垫！</p><div class="instructions"><span>⌨</span><span><b>移动与推箱</b>WASD / 方向键移动，走向木箱即可推动。触屏可用屏幕方向按钮。</span><span>🌻</span><span><b>收集小幸福</b>走过悬浮的葵花籽即可收集。全部收集会多获得一颗星。</span><span>🧊</span><span><b>留心冰面</b>木箱在蓝色冰面上会持续滑行，直到离开冰面或遇到障碍。</span><span>◉</span><span><b>薄荷色机关</b>栗栗或木箱压住圆形按钮时，绿色栅栏打开。离开按钮，栅栏关闭。</span><span>↶</span><span><b>安心尝试</b>Z 撤销、R 重开、H 获取下一步提示、C 旋转视角。提示来自当前局面的自动求解。</span><span>★</span><span><b>三颗星的约定</b>完成关卡、收集全部葵花籽、在目标步数内完成，各得一星。当前关目标：${LEVELS[index].par} 步。</span></div><button class="primary" id="play">好啦，开动小爪爪！</button>`);$('play').onclick=()=>$('modal').close();}
function showWin(stars){modal(`<div class="win-icon">🐹</div><div class="win-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><h2 class="win-title">${index===5?'早餐派对，开场啦！':'早餐已就位！'}</h2><p class="win-title">${index===5?'栗栗的厨房之旅完成了。谢谢你陪它度过这个甜甜的早晨。':'每个小小的努力，都值得一顿丰盛的早餐。'}</p><div class="win-stats"><div><b>${state.moves}</b>移动步数</div><div><b>${state.collected.length} / 3</b>葵花籽</div><div><b>${$('timer').textContent}</b>完成用时</div></div><button class="primary" id="next">${index===5?'查看厨房地图':'下一段小冒险 →'}</button><button class="secondary" id="replay">再玩一次 · 挑战 ${LEVELS[index].par} 步</button>`);$('next').onclick=()=>index===5?showLevels():load(index+1);$('replay').onclick=()=>load(index);}
function hint(){if(complete||hintBusy)return;hintBusy=true;$('hint').disabled=true;toast('栗栗正在想办法…');hintWorker=new Worker(new URL('./solver-worker.js',import.meta.url),{type:'module'});hintWorker.onmessage=e=>{hintBusy=false;$('hint').disabled=false;const path=e.data;if(path?.length){const dirs=['上 ↑','下 ↓','左 ←','右 →'];toast(`试试向${dirs[path[0]]}走。当前局面还需要约 ${path.length} 步。`);}else toast('这个局面暂时找不到路线。试试撤销几步，或重新开始。');hintWorker.terminate();hintWorker=null;};hintWorker.onerror=()=>{hintBusy=false;$('hint').disabled=false;hintWorker?.terminate();toast('提示计算遇到了问题，请重试。');};hintWorker.postMessage({level:LEVELS[index],state});}
$('levels').onclick=showLevels;$('adventure').onclick=showLevels;$('journal').onclick=showJournal;$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();}});$('undo').onclick=undo;$('restart').onclick=()=>{load(index);toast('全新的早餐时间，开始吧。');};$('hint').onclick=hint;$('camera').onclick=()=>{kitchen.rotate();toast('视角已切换；方向键仍对应棋盘方向。');};$('zoom').onclick=()=>kitchen.zoom();function soundUI(){$('sound').textContent=saved.sound?'♫':'♪';$('sound').style.opacity=saved.sound?'1':'.45';$('sound').setAttribute('aria-label',saved.sound?'关闭音效':'开启音效');}$('sound').onclick=()=>{saved.sound=!saved.sound;persist();soundUI();if(saved.sound)tone(600,.12);toast(saved.sound?'厨房音效已开启':'静静享受这段小时光。');};soundUI();
const keys={ArrowUp:0,ArrowDown:1,ArrowLeft:2,ArrowRight:3,w:0,s:1,a:2,d:3};window.addEventListener('keydown',e=>{if($('modal').open||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(keys[k]!==undefined){e.preventDefault();step(keys[k]);}else if(k==='z'){e.preventDefault();undo();}else if(k==='r')$('restart').click();else if(k==='h')hint();else if(k==='c')$('camera').click();});document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();step(Number(b.dataset.dir));}));let touchStart; kitchen.canvas.addEventListener('pointerdown',e=>{touchStart=[e.clientX,e.clientY];});kitchen.canvas.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart[0],dy=e.clientY-touchStart[1];if(Math.hypot(dx,dy)>25)step(Math.abs(dx)>Math.abs(dy)?(dx>0?3:2):(dy>0?1:0));touchStart=null;});setInterval(()=>{if(started&&!complete&&!document.hidden&&!$('modal').open){elapsed++;updateTime();}},1000);load(index);
// Compact read-only state exposure for smoke testing and debugging.
window.__hamster={getState:()=>({index,state:structuredClone(state),complete}),load,step,undo};
