import * as THREE from './three.module.js';
const $=id=>document.getElementById(id), clamp=THREE.MathUtils.clamp;
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('error').classList.remove('hidden');throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color('#063145');scene.fog=new THREE.FogExp2('#063145',.018);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,200);
scene.add(new THREE.HemisphereLight(0x9fe5ee,0x102d42,2.2));const sun=new THREE.DirectionalLight(0x9bffff,2.8);sun.position.set(-20,60,15);scene.add(sun);
const rand=(a,b)=>a+Math.random()*(b-a), mat=(c,opts={})=>new THREE.MeshStandardMaterial({color:c,roughness:.6,...opts});
const groundMat=mat(0x164654);const floorGeo=new THREE.PlaneGeometry(190,190,65,65);floorGeo.rotateX(-Math.PI/2);const pa=floorGeo.attributes.position;for(let i=0;i<pa.count;i++){const x=pa.getX(i),z=pa.getZ(i);pa.setY(i,Math.sin(x*.13)*1.2+Math.cos(z*.16)*.9+Math.sin(x*.35+z*.2)*.3);}floorGeo.computeVertexNormals();scene.add(new THREE.Mesh(floorGeo,groundMat));
const rocks=[],grass=[],foods=[],predators=[],particles=[],pearls=[];const grassZones=[[-15,10],[18,-12],[-26,-24],[26,25],[0,30]];
const rockMat=mat(0x235364);for(let i=0;i<65;i++){const m=new THREE.Mesh(new THREE.DodecahedronGeometry(rand(1,4),0),rockMat);m.position.set(rand(-80,80),rand(-1,1),rand(-80,80));m.scale.set(rand(.8,1.6),rand(.4,1.4),rand(.7,1.4));m.rotation.set(rand(0,3),rand(0,3),rand(0,3));scene.add(m);rocks.push(m);}
function tube(points,r,color,emissive=0){return new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),16,r,5,false),mat(color,{emissive,emissiveIntensity:.65}));}
// Sea gardens are actual 3D geometry; no image or external texture is required.
for(let i=0;i<140;i++){let x,z;if(i<70){const c=grassZones[i%5];x=c[0]+rand(-4,4);z=c[1]+rand(-4,4);}else{x=rand(-65,65);z=rand(-65,65);}const h=rand(2,6),g=new THREE.Group();g.position.set(x,0,z);for(let j=0;j<3;j++){const a=rand(0,6.28);g.add(tube([new THREE.Vector3(0,0,0),new THREE.Vector3(Math.cos(a)*.4,h*.4,0),new THREE.Vector3(Math.sin(a)*.8,h*.8,.3),new THREE.Vector3(Math.cos(a)*1.1,h,0)],.09,[0x287a72,0x379783,0x366a84][j]));}scene.add(g);grass.push(g);}
for(let i=0;i<43;i++){const group=new THREE.Group();group.position.set(rand(-65,65),0,rand(-65,65));const c=[0xce8e9e,0x547fac,0x6f62a5,0xa47492][i%4];for(let j=0;j<6;j++){const a=j/6*Math.PI*2,h=rand(.8,3);group.add(tube([new THREE.Vector3(),new THREE.Vector3(Math.cos(a)*.5,h*.45,Math.sin(a)*.5),new THREE.Vector3(Math.cos(a),h,Math.sin(a))],.13,c,c));}scene.add(group);}
// Light shafts and suspended plankton.
const rayMat=new THREE.MeshBasicMaterial({color:0x75cddb,transparent:true,opacity:.024,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});for(let i=0;i<8;i++){const ray=new THREE.Mesh(new THREE.CylinderGeometry(.6,5,85,12,1,true),rayMat);ray.position.set(-30+i*13,31,-20+Math.sin(i)*20);ray.rotation.z=-.24;scene.add(ray);}
const dustPositions=new Float32Array(1000*3);for(let i=0;i<dustPositions.length;i+=3){dustPositions[i]=rand(-90,90);dustPositions[i+1]=rand(1,60);dustPositions[i+2]=rand(-90,90);}const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0x9cdbdb,size:.11,transparent:true,opacity:.45}));scene.add(dust);
function makeJelly(color=0xb6c3ff,scale=1){const g=new THREE.Group();const shell=new THREE.Mesh(new THREE.SphereGeometry(1.6,40,24,0,Math.PI*2,0,Math.PI*.56),mat(color,{transparent:true,opacity:.69,emissive:color,emissiveIntensity:.38,roughness:.16,metalness:.05,side:THREE.DoubleSide,depthWrite:false}));shell.scale.y=.68;g.add(shell);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.56,.055,8,60),mat(0xe2cfff,{emissive:0xc3a4ff,emissiveIntensity:1.3}));ring.rotation.x=Math.PI/2;ring.position.y=-.17;g.add(ring);const inner=new THREE.Mesh(new THREE.SphereGeometry(.65,20,16),mat(0xf2bce2,{emissive:0xf3ade3,emissiveIntensity:.9,transparent:true,opacity:.7}));inner.scale.set(1,.4,1);inner.position.y=.3;g.add(inner);
const tentacles=[];for(let j=0;j<16;j++){const a=j/16*Math.PI*2,r=j%2?.55:1.22,len=rand(2.3,4.4);const pts=[];for(let k=0;k<9;k++)pts.push(new THREE.Vector3(Math.cos(a)*r+Math.sin(k*.9+j)*.14,-.17-k*len/8,Math.sin(a)*r+Math.cos(k+j)*.12));const t=tube(pts,j%2?.065:.026,j%2?0xc9a3e6:0x9eafe9,0x7d79cd);g.add(t);tentacles.push(t);}g.userData={shell,ring,inner,tentacles};g.scale.setScalar(scale);return g;}
const jelly=makeJelly();jelly.position.set(0,9,0);scene.add(jelly);const jellyLight=new THREE.PointLight(0xbdcaff,16,13,2);jelly.add(jellyLight);
const ambientJellies=[];for(let i=0;i<10;i++){const j=makeJelly(0x69bac5,rand(.17,.38));j.position.set(rand(-50,50),rand(7,30),rand(-50,-15));scene.add(j);ambientJellies.push(j);}
const foodMat=mat(0xa8f7d3,{emissive:0x6cffbb,emissiveIntensity:2});const foodGeo=new THREE.IcosahedronGeometry(.23,1);
function spawnFood(){const f=new THREE.Mesh(foodGeo,foodMat);f.position.set(rand(-44,44),rand(3.3,17),rand(-44,44));f.userData.phase=rand(0,7);scene.add(f);foods.push(f);}for(let i=0;i<100;i++)spawnFood();
// Three increasingly distant ocean hearts are the expedition's objective.
const heartSpots=[new THREE.Vector3(-20,5,-18),new THREE.Vector3(27,12,-30),new THREE.Vector3(22,5,32)];heartSpots.forEach((pos,i)=>{const g=new THREE.Group();const core=new THREE.Mesh(new THREE.OctahedronGeometry(.7),mat(0xffdda0,{emissive:0xffbe64,emissiveIntensity:1.8}));g.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15,.025,6,48),mat(0xffeac2,{emissive:0xffd38d,emissiveIntensity:1}));ring.rotation.x=Math.PI/2;g.add(ring);g.position.copy(pos);g.userData={index:i,core};scene.add(g);pearls.push(g);});
const home=new THREE.Group();home.position.set(0,3,0);const homeRing=new THREE.Mesh(new THREE.TorusGeometry(3,.07,8,70),mat(0xa4f9e8,{emissive:0x70eecf,emissiveIntensity:2}));homeRing.rotation.x=Math.PI/2;home.add(homeRing);home.visible=false;scene.add(home);
function makePredator(type,index){const g=new THREE.Group(),isShark=type==='shark';const bodyMat=mat(isShark?0x547684:0x607a62),body=new THREE.Mesh(new THREE.SphereGeometry(1,18,12),bodyMat);body.scale.set(isShark?.85:1.15,isShark?.65:.45,isShark?2.5:1.4);g.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.9,1.5,3),bodyMat);tail.rotation.x=Math.PI/2;tail.position.z=2.5;g.add(tail);const fin=new THREE.Mesh(new THREE.ConeGeometry(.7,1.35,3),bodyMat);fin.position.set(0,.7,.1);g.add(fin);for(let side of [-1,1]){const f=new THREE.Mesh(new THREE.ConeGeometry(.6,1.4,3),bodyMat);f.rotation.z=side*1.25;f.position.set(side*.8,0,.2);g.add(f);const eye=new THREE.Mesh(new THREE.SphereGeometry(.1,8,8),mat(0xffca94,{emissive:0xff6c3b,emissiveIntensity:.5}));eye.position.set(side*.43,.17,-1.7);g.add(eye);}g.position.set(Math.sin(index*2)*35,rand(5,14),Math.cos(index*2)*35);g.userData={type,index,stun:0,alert:false,target:new THREE.Vector3(rand(-40,40),rand(4,15),rand(-40,40)),tail};scene.add(g);predators.push(g);}for(let i=0;i<7;i++)makePredator(i%3?'shark':'turtle',i);
const schools=[];for(let i=0;i<70;i++){const f=new THREE.Mesh(new THREE.ConeGeometry(.10,.55,4),mat([0x759fab,0xa9bca3,0x5191aa][i%3]));f.rotation.x=Math.PI/2;f.position.set(rand(-55,55),rand(4,24),rand(-55,55));scene.add(f);schools.push(f);}
const shock=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshBasicMaterial({color:0x9cefff,wireframe:true,transparent:true,opacity:.4}));shock.visible=false;scene.add(shock);
let state='intro',elapsed=0,hp=100,energy=100,food=0,level=1,score=0,heartCount=0,dashTime=0,cloakTime=0,cloakCD=0,pulseCD=0,invincible=0,shockTime=0,boost=1,magnet=2.1,armor=1,currentTime=0,yaw=.38,zoom=19,toastTimer=0,muted=true,audioCtx,runBest=0;
try{runBest=Number(localStorage.getItem('jelly-best')||0);}catch{}
const keys=new Set(),velocity=new THREE.Vector3();let dragging=false,lastX=0;
function playTone(f=440,d=.2){if(muted)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(f,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(f*.7,audioCtx.currentTime+d);gain.gain.setValueAtTime(.055,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+d);}catch{}}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;toastTimer=3.2;}
function burst(pos,color,count=14){for(let i=0;i<count;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.055,5,5),new THREE.MeshBasicMaterial({color,transparent:true}));p.position.copy(pos);p.userData={v:new THREE.Vector3(rand(-2,2),rand(-1,2),rand(-2,2)),life:1};scene.add(p);particles.push(p);}}
function start(){state='playing';document.body.classList.add('playing');$('modal').classList.add('hidden');jelly.position.set(0,8,0);toast('追随绿色微光 · 收集浮游生物来成长');playTone(520,.4);}
function ability(name){if(state!=='playing')return false;if(name==='dash'&&energy>=24&&dashTime<=0){energy-=24;dashTime=.7;playTone(190,.25);return true;}if(name==='cloak'&&cloakCD<=0&&energy>=35){energy-=35;cloakTime=4;cloakCD=14;toast('透明伪装 · 暂时脱离捕食者视线');playTone(680,.6);return true;}if(name==='pulse'&&pulseCD<=0&&energy>=40){energy-=40;pulseCD=12;shockTime=.8;shock.position.copy(jelly.position);predators.forEach(p=>{if(p.position.distanceTo(jelly.position)<13)p.userData.stun=5;});playTone(100,.7);toast('电光脉冲 · 附近捕食者已被击退');return true;}toast('能量不足或技能正在冷却');return false;}
$('start').onclick=start;['dash','cloak','pulse'].forEach(n=>$(n).onclick=()=>ability(n));
function showModal(title,body,actions,eyebrow='TAKE A BREATH'){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalActions').replaceChildren();$('modalEyebrow').textContent=eyebrow;for(const [label,fn,cls] of actions){const b=document.createElement('button');b.className=cls||'primary';b.textContent=label;b.onclick=fn;$('modalActions').append(b);}$('modal').classList.remove('hidden');}
function resume(){state='playing';$('modal').classList.add('hidden');}
function pause(){if(state==='playing'){state='paused';keys.clear();showModal('海洋会等你',`<p>远行 ${formatTime(elapsed)} · 微光 ${score}<br>休息一下，再去探索深蓝。</p>`,[['继续远行',resume],['重新开始',()=>location.reload(),'secondary']]);}else if(state==='paused')resume();}
$('pause').onclick=pause;$('help').onclick=()=>{const previous=state;if(state==='playing')state='help';showModal('小水母生存指南','<p>W A S D / 方向键：沿镜头方向游动<br>R / F：上浮与下潜 · 拖动画面：旋转视角<br>空格：冲刺 · Q：透明伪装 · E：电光脉冲<br>Esc：暂停 · 手机可使用屏幕方向键</p><p>收集绿色浮游生物恢复生命并进化。进入海草附近、下潜到 6 米高度以内可以隐藏。金色菱形是海洋之心：集齐 3 颗后，回到起点的光环。雷达绿色代表食物，红色代表捕食者，金色代表海洋之心。</p>',[['明白了',()=>{state=previous;$('modal').classList.add('hidden');}]],'HOW TO SURVIVE');};
$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'♫':'♪';$('sound').title=muted?'开启声音':'关闭声音';$('sound').setAttribute('aria-label',$('sound').title);playTone(440,.4);};
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.key.toLowerCase());if(e.code==='Space')ability('dash');if(e.key.toLowerCase()==='q')ability('cloak');if(e.key.toLowerCase()==='e')ability('pulse');if(e.key==='Escape')pause();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});
$('world').addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(dragging){yaw-=(e.clientX-lastX)*.006;lastX=e.clientX;}});$('world').addEventListener('pointerup',()=>dragging=false);$('world').addEventListener('pointercancel',()=>dragging=false);$('world').addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom+e.deltaY*.02,11,32);},{passive:false});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
function formatTime(t){return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;}
function evolve(){level++;state='upgrade';keys.clear();playTone(880,.5);showModal('微光，正在长大',`<p>已进化至 Lv.${level}，生命与能量全部恢复。选择这次远行的进化方向：</p>`,[
['轻盈伞体 · 游动速度 +20%',()=>{boost+=.2;finishUpgrade();},'upgrade'],['微光触手 · 食物吸引范围 +45%',()=>{magnet*=1.45;finishUpgrade();},'upgrade'],['柔韧外膜 · 受到伤害减少 20%',()=>{armor*=.8;finishUpgrade();},'upgrade']],'EVOLUTION');}
function finishUpgrade(){hp=100;energy=100;resume();toast('进化完成 · 继续寻找海洋之心');}
function finish(won){state=won?'won':'lost';runBest=Math.max(runBest,score);try{localStorage.setItem('jelly-best',String(runBest));}catch{}showModal(won?'你点亮了这片海。':'微光未熄，下次再见。',`<p>${won?'你带回了三颗海洋之心，完成这次海底远行。':'捕食者结束了这次冒险。试试利用海草、伪装和脉冲脱身。'}</p><p>远行时间 ${formatTime(elapsed)} · 进化 Lv.${level}<br>本次微光 ${score} · 最高微光 ${runBest}<br>海洋之心 ${heartCount} / 3</p>`,[['再来一次',()=>location.reload()]],won?'OCEAN RESTORED':'THE OCEAN REMEMBERS');}
function updateUI(hidden){$('hp').style.width=hp+'%';$('hpLabel').textContent=Math.ceil(hp)+'%';$('energy').style.width=energy+'%';$('energyLabel').textContent=Math.floor(energy)+' / 100';$('level').textContent=`${level===1?'幼年水母':level<4?'月光水母':'深海精灵'} · Lv.${level}`;const thresholds=[0,6,16,30,50,75],prev=thresholds[Math.min(level-1,5)],next=thresholds[Math.min(level,5)];$('foodCount').textContent=level<6?`${food-prev} / ${next-prev}`:'已完全进化';$('xp').style.width=(level<6?(food-prev)/(next-prev)*100:100)+'%';$('time').textContent=formatTime(elapsed);$('score').textContent='微光 '+String(score).padStart(4,'0');$('depth').textContent=`深度 ${Math.round(40-jelly.position.y)} m`;$('zone').textContent=hidden?'海草庇护所':jelly.position.y>14?'微光水层':jelly.position.z<-15?'远古珊瑚礁':'珊瑚浅海';$('pearls').textContent=Array.from({length:3},(_,i)=>i<heartCount?'◆':'◇').join(' ');$('cloakInfo').textContent=cloakCD>0?`${Math.ceil(cloakCD)} 秒冷却`:'35 能量 · 4 秒';$('pulseInfo').textContent=pulseCD>0?`${Math.ceil(pulseCD)} 秒冷却`:'40 能量 · 击退';$('dashInfo').textContent=dashTime>0?'喷射中…':'消耗 24 能量';$('cloak').classList.toggle('cooldown',cloakCD>0||energy<35);$('pulse').classList.toggle('cooldown',pulseCD>0||energy<40);$('dash').classList.toggle('cooldown',energy<24);if(level>1){$('questTitle').textContent=heartCount===3?'把微光带回家':'寻找海洋之心';$('questText').textContent=heartCount===3?'回到雷达中心，在海床光环中完成远行。':'寻找雷达上的金色菱形。靠近它们，收集三颗海洋之心。';}}
const map=$('map').getContext('2d');function drawMap(){map.clearRect(0,0,140,140);map.strokeStyle='#8dc8ce33';map.lineWidth=1;for(const r of [24,45,64]){map.beginPath();map.arc(70,70,r,0,7);map.stroke();}map.beginPath();map.moveTo(6,70);map.lineTo(134,70);map.moveTo(70,6);map.lineTo(70,134);map.stroke();const point=(v,c,r)=>{map.fillStyle=c;map.beginPath();map.arc(70+v.x*.8,70+v.z*.8,r,0,7);map.fill();};grassZones.forEach(c=>point({x:c[0],z:c[1]},'#478e7777',4));foods.forEach(f=>point(f.position,'#83d7a777',1));predators.forEach(p=>point(p.position,p.userData.alert?'#ff9e78':'#b77f75',2.5));pearls.filter(p=>p.visible).forEach(p=>point(p.position,'#ffdc92',3));if(home.visible)point(home.position,'#d4fff6',4);point(jelly.position,'#e4dcff',3.5);}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;currentTime+=dt;const t=currentTime;
// Gentle motion continues behind start and pause screens.
jelly.userData.shell.scale.set(1+Math.sin(t*2.7)*.045,.68+Math.sin(t*2.7)*.045,1+Math.sin(t*2.7)*.045);jelly.userData.ring.scale.setScalar(1+Math.sin(t*2.7)*.035);jelly.userData.tentacles.forEach((a,i)=>{a.rotation.z=Math.sin(t*2+i*.6)*.07;a.rotation.x=Math.cos(t*1.6+i)*.06;});grass.forEach((g,i)=>{g.rotation.z=Math.sin(t*.6+i)*.06;});ambientJellies.forEach((j,i)=>{j.position.y+=Math.sin(t+i)*dt*.22;j.rotation.z=Math.sin(t*.5+i)*.1;});schools.forEach((f,i)=>{f.position.x+=dt*.6;if(f.position.x>60)f.position.x=-60;f.position.y+=Math.sin(t*2+i)*dt*.06;});foods.forEach(f=>{f.rotation.y+=dt;});pearls.forEach(p=>{p.userData.core.rotation.y+=dt;p.rotation.y+=dt*.3;});dust.rotation.y=t*.002;
if(state==='playing'){
elapsed+=dt;energy=Math.min(100,energy+dt*(cloakTime>0?0:6));dashTime=Math.max(0,dashTime-dt);cloakTime=Math.max(0,cloakTime-dt);cloakCD=Math.max(0,cloakCD-dt);pulseCD=Math.max(0,pulseCD-dt);invincible=Math.max(0,invincible-dt);
const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),move=new THREE.Vector3();if(keys.has('w')||keys.has('arrowup'))move.add(forward);if(keys.has('s')||keys.has('arrowdown'))move.sub(forward);if(keys.has('d')||keys.has('arrowright'))move.add(right);if(keys.has('a')||keys.has('arrowleft'))move.sub(right);if(keys.has('r'))move.y++;if(keys.has('f'))move.y--;if(move.lengthSq()>0)move.normalize();if(dashTime>0&&move.lengthSq()===0)move.copy(forward);move.multiplyScalar((dashTime>0?17:5.5)*boost);velocity.lerp(move,1-Math.exp(-dt*5));jelly.position.addScaledVector(velocity,dt);jelly.position.x=clamp(jelly.position.x,-55,55);jelly.position.z=clamp(jelly.position.z,-55,55);jelly.position.y=clamp(jelly.position.y,3,24);jelly.rotation.z=-velocity.x*.025;jelly.rotation.x=velocity.z*.025;
const hidden=jelly.position.y<6&&grassZones.some(c=>Math.hypot(jelly.position.x-c[0],jelly.position.z-c[1])<5);jelly.userData.shell.material.opacity=cloakTime>0?.18:.69;const size=1+(level-1)*.09;jelly.scale.lerp(new THREE.Vector3(size,size,size),.02);
let danger=false;for(const p of predators){const u=p.userData,d=p.position.distanceTo(jelly.position);u.stun=Math.max(0,u.stun-dt);u.alert=d<(u.type==='shark'?16:12)&&cloakTime<=0&&!hidden&&u.stun===0;danger ||=u.alert;if(u.alert)u.target.copy(jelly.position);else if(p.position.distanceTo(u.target)<3||Math.random()<dt*.1)u.target.set(rand(-43,43),rand(4,18),rand(-43,43));const dir=u.target.clone().sub(p.position).normalize();const speed=u.stun>0?-2:u.alert?(u.type==='shark'?5.4:4.1)+Math.min(elapsed/150,1.8):2;p.position.addScaledVector(dir,dt*speed);const look=p.position.clone().add(dir);p.lookAt(look);p.rotateY(Math.PI);u.tail.rotation.y=Math.sin(t*7+u.index)*.25;if(d<2.5&&invincible===0&&u.stun===0&&cloakTime<=0){hp=Math.max(0,hp-24*armor);invincible=2;burst(jelly.position,0xffacb2,20);playTone(80,.4);toast('受伤了！冲刺拉开距离，或释放电光脉冲');if(hp<=0){finish(false);break;}}}
$('danger').classList.toggle('hidden',!danger);jelly.visible=invincible>0?Math.floor(invincible*8)%2===0:true;
for(const f of foods){const d=f.position.distanceTo(jelly.position);if(d<magnet+2)f.position.lerp(jelly.position,dt*2);if(d<magnet*.55){burst(f.position,0x98ffcf,7);f.position.set(rand(-44,44),rand(3.3,17),rand(-44,44));food++;score+=20;hp=Math.min(100,hp+3);energy=Math.min(100,energy+4);playTone(600+food%5*100,.15);if([6,16,30,50,75].includes(food)&&state==='playing')evolve();}}
for(const p of pearls){if(p.visible&&p.position.distanceTo(jelly.position)<2.5){p.visible=false;heartCount++;score+=300;burst(p.position,0xffdf9e,35);playTone(1046,.7);toast(`收集海洋之心 ${heartCount} / 3${heartCount===3?' · 回到起点的光环！':''}`);if(heartCount===3)home.visible=true;}}
if(home.visible&&jelly.position.distanceTo(home.position)<3.5){score+=Math.max(100,Math.floor(1500-elapsed*2));finish(true);}if(dashTime>0&&Math.random()<.7)burst(jelly.position,0xaeeeff,1);updateUI(hidden);
}
if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').style.opacity=0;}if(shockTime>0){shockTime-=dt;shock.visible=true;shock.scale.setScalar((.8-shockTime)*17);shock.material.opacity=shockTime*.45;}else shock.visible=false;
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.userData.life-=dt;p.position.addScaledVector(p.userData.v,dt);p.material.opacity=p.userData.life;if(p.userData.life<=0){scene.remove(p);p.geometry.dispose();p.material.dispose();particles.splice(i,1);}}
homeRing.rotation.z=t*.2;
if(state==='intro'){jelly.position.y=10+Math.sin(t*.75)*.25;const target=new THREE.Vector3(-7,9,0);const pos=new THREE.Vector3(7,15,23);camera.position.lerp(pos,.025);camera.lookAt(target);}else{const target=jelly.position.clone().add(new THREE.Vector3(0,-1,0));const pos=target.clone().add(new THREE.Vector3(Math.sin(yaw)*zoom,zoom*.47,Math.cos(yaw)*zoom));camera.position.lerp(pos,1-Math.exp(-dt*3));camera.lookAt(target);}drawMap();renderer.render(scene,camera);}
camera.position.set(7,15,23);requestAnimationFrame(frame);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// Shared game actions for browser agents, when the host supports WebMCP.
const gameState=()=>({state,health:Math.round(hp),energy:Math.round(energy),level,food,score,hearts:heartCount,time:Math.floor(elapsed)});
if(document.modelContext?.registerTool){for(const tool of [{name:'read_jellyfish_game',description:'Read the current jellyfish expedition state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameState()},{name:'start_jellyfish_game',description:'Start the expedition from its welcome screen.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state!=='intro')throw Error('Expedition already started');start();return gameState();}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
