import {parts,slotInfo,svg,loadProfile,statsFor,defaultLoadout,opponents} from './data.js';
import {IronEngine} from './engine.js';
const $=id=>document.getElementById(id);let profile=loadProfile(),selectedSlot='weapon',mode='league',engine,round=0,wave=1,bonusHp=0,bonusDamage=0,roundReward='repair',resultState=null,toastTimer,messageTimer,lastHud=0;
const save=()=>{try{localStorage.setItem('iron-circuit-v1',JSON.stringify(profile))}catch{toast('当前浏览器无法保存进度，请保持页面开启。')}};
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function closeModal(){if(engine?.mode==='battle'&&!engine.ended&&engine.paused){resume();return}$('modal').hidden=true}
function showModal(html){$('modal-content').innerHTML=html;$('modal').hidden=false;const first=$('modal-content').querySelector('button');first?.focus()}
const closeButton='<button class="modal-close" data-close aria-label="关闭">×</button>';
function render(){
 const s=statsFor(profile.loadout);$('credits').textContent=profile.credits.toLocaleString();$('pilot-rank').textContent=profile.championships?'铁环认证冠军':profile.wins>2?'精英机甲技师':'独立机甲技师';
 $('slot-list').innerHTML=Object.entries(slotInfo).map(([k,v],i)=>`<button class="slot ${selectedSlot===k?'active':''}" data-slot="${k}" aria-pressed="${selectedSlot===k}"><span class="slot-icon">${svg(k)}</span><span class="slot-text"><small>${v.label} / ${v.en}</small><strong>${s.selected[k].name}</strong></span><span class="slot-index">0${i+1}</span></button>`).join('');
 $('parts-title').textContent=slotInfo[selectedSlot].title;$('parts-count').textContent=`0${parts[selectedSlot].length} 个部件`;$('parts-description').textContent=slotInfo[selectedSlot].desc;
 $('part-list').innerHTML=parts[selectedSlot].map(p=>{const unlocked=profile.unlocked.includes(p.id),active=profile.loadout[selectedSlot]===p.id;return`<button class="part-card ${active?'active':''}" data-part="${p.id}" aria-pressed="${active}"><span class="part-icon">${svg(selectedSlot==='weapon'?p.id:selectedSlot)}</span><span><span class="part-name">${p.name}</span><span class="part-meta"><span class="tag">${p.tag}</span> / ${unlocked?p.sub:'研发解锁'}</span></span>${!unlocked?`<span class="lock-price">◈ ${p.cost}</span>`:''}</button>`}).join('');
 $('selected-detail').innerHTML=`<p><strong>${s.selected[selectedSlot].tag}特性</strong>${s.selected[selectedSlot].desc}</p>`;
 $('paint-colors').innerHTML=['#c6cfc9','#ad5945','#6e929c','#aaa176'].map(c=>`<button class="paint ${c===profile.color?'selected':''}" style="--paint:${c}" data-paint="${c}" aria-label="${({'#c6cfc9':'霜白','#ad5945':'锈红','#6e929c':'冰蓝','#aaa176':'沙金'})[c]}涂装" aria-pressed="${c===profile.color}"></button>`).join('');
 $('weight').textContent=`${s.weight>66?'重型':s.weight<43?'轻型':'中型'} / ${s.weight} T`;
 $('stat-grid').innerHTML=[['结构耐久',s.hp,'HP',s.hp/280],['近战伤害',s.damage,'ATK',s.damage/44],['机动速度',s.speed.toFixed(1),'M/S',s.speed/7],['核心容量',s.energy,'EN',s.energy/140]].map(([name,v,unit,ratio])=>`<div class="stat"><div class="stat-top"><span>${name}</span><strong>${v}<small>${unit}</small></strong></div><div class="stat-track"><i style="width:${Math.min(100,ratio*100)}%"></i></div></div>`).join('');
 $('passive-text').textContent=s.selected.module.desc;$('build-summary').textContent=`${s.selected.chassis.tag}框架 · ${s.selected.weapon.tag}近战武装`;
 document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',(b.dataset.preset==='balanced'&&profile.loadout.weapon==='blade'&&profile.loadout.chassis==='ronin')||(b.dataset.preset==='agile'&&profile.loadout.weapon==='claws'&&profile.loadout.chassis==='spectre')||(b.dataset.preset==='tank'&&profile.loadout.weapon==='hammer'&&profile.loadout.chassis==='titan')));
 updateModeUI();
}
function updateModeUI(){const texts={league:['铁环冠军联赛','三轮淘汰赛 · 废弃铸造厂','+600'],survival:['无尽生存挑战','逐波强化 · 争夺最高纪录','+250'],training:['机师训练场','无限时间 · 自由测试配装','练习']};const t=texts[mode];$('event-name').textContent=t[0];$('event-description').textContent=t[1];$('event-reward').textContent=t[2]}
function rebuild(){render();engine?.setBuild(profile.loadout,profile.color);save()}
function choosePart(id){const p=parts[selectedSlot].find(p=>p.id===id);if(!p)return;if(!profile.unlocked.includes(id)){showModal(`${closeButton}<div class="eyebrow">R&D / 部件研发</div><h2>${p.name}</h2><p>${p.desc}</p><div class="mission-line"><span>◈</span><div><strong>研发所需：${p.cost} 零件点</strong><p>当前拥有 ${profile.credits.toLocaleString()} 零件点 · 解锁后永久可用</p></div></div><div class="modal-actions"><button data-close>暂时返回</button><button class="primary" data-buy="${id}" ${profile.credits<p.cost?'disabled':''}>${profile.credits<p.cost?'零件点不足':'解锁并装配'}</button></div>`);return}profile.loadout[selectedSlot]=id;rebuild()}
function preset(type){let next={...defaultLoadout};if(type==='agile')next={...next,chassis:'spectre',weapon:'claws',legs:profile.unlocked.includes('reverse')?'reverse':'biped'};if(type==='tank')next={...next,chassis:profile.unlocked.includes('titan')?'titan':'ronin',weapon:'hammer',legs:profile.unlocked.includes('heavy')?'heavy':'biped',module:profile.unlocked.includes('plating')?'plating':'capacitor'};profile.loadout=next;rebuild();toast(type==='tank'&&!profile.unlocked.includes('titan')?'已搭载破城锤；研发泰坦框架可完成重装配置。':'已应用'+({balanced:'均衡型',agile:'突击型',tank:'重装型'})[type]+'配置')}
function guide(){showModal(`${closeButton}<div class="eyebrow">FIELD MANUAL / 作战手册</div><h2>先读懂对手，再出手。</h2><p>机甲自动面向最近的对手。控制走位和出招节奏，才是擂台的制胜关键。</p><div class="guide-grid">${[['W A S D','移动 / 方向键也可','根据镜头方向移动，保持在你的武器有效距离内。'],['J','三段连击','连续点按形成三段连招；最后一击伤害更高。'],['K','蓄力重击','消耗 24 能量。击破防御与架势，出招时会露出破绽。'],['SPACE','推进闪避','短暂无敌，躲开红色预警。移动中沿移动方向闪避。'],['SHIFT / L','格挡与弹反','按住防御。抬盾后 0.22 秒内接住轻击，可反震敌人。'],['Q','核心爆发','战斗积累充能，满 100% 后释放你的核心专属技能。']].map(([key,title,desc])=>`<div class="guide-item"><kbd>${key}</kbd>${title}<p>${desc}</p></div>`).join('')}</div><div class="tip-box">橙色地面圈表示对手正在蓄力。重击适合闪避，轻击可以弹反。外环每 20 秒会出现高温脉冲，看到警告请靠近中心。<br>手机可使用屏幕方向键和技能按钮。按 Esc / P 暂停。</div><div class="modal-actions"><button data-close>返回机库</button><button class="primary" data-start-training>进入训练场</button></div>`)}
function modes(){showModal(`${closeButton}<div class="eyebrow">SELECT OPERATION / 赛事选择</div><h2>选择你的战场</h2>${[['league','♜','铁环冠军联赛','连战三位风格不同的精英机师，轮间选择整备奖励，夺取冠军。','每场胜利 +600 · 夺冠额外 +1,200'],['survival','∞','无尽生存挑战','逐波增强的对手与双机夹击。保留残余耐久，每轮获得整备选择。',`每波 +250 · 最高纪录 ${profile.bestWave} 波`],['training','◇','机师训练场','不会反击的训练机体，自由练习连击、闪避和核心爆发。','不限时间 · 不计入战绩']].map(([id,icon,title,desc,reward])=>`<button class="mode-card ${mode===id?'selected':''}" data-mode="${id}"><span>${icon}</span><div><strong>${title}</strong><p>${desc}</p><small>${reward}</small></div></button>`).join('')}`)}
function arenaOverview(){showModal(`${closeButton}<div class="eyebrow">IRON CIRCUIT / SEASON 01</div><h2>铁环冠军联赛</h2><p>从铸造厂的新人挑战者，到铁环的卫冕冠军。每场结束后可整备机体、选择战术增益。</p><div class="opponent-preview">${opponents.map((e,i)=>`<div><span>0${i+1}</span><strong>${e.name}</strong><small>${e.title}<br>${e.en}</small></div>`).join('')}</div><div class="tip-box">${opponents[0].description}<br>胜利奖励 600 零件点；夺冠额外奖励 1,200。耐久在联赛轮间完全恢复。</div><div class="modal-actions"><button data-open-modes>其他赛事</button><button class="primary" data-start-league>开始冠军联赛</button></div>`)}
function records(){showModal(`${closeButton}<div class="eyebrow">PILOT ARCHIVE / 技师档案</div><h2>每一次交锋，都留下记录。</h2><div class="result-grid"><div class="result-stat"><strong>${profile.wins}</strong><span>胜利场次</span></div><div class="result-stat"><strong>${profile.championships}</strong><span>联赛冠军</span></div><div class="result-stat"><strong>${profile.bestWave}</strong><span>生存最高波数</span></div></div><div class="record-list"><div class="record-row"><span>击败机体</span><b>${profile.totalKills}</b></div><div class="record-row"><span>失败场次</span><b>${profile.losses}</b></div><div class="record-row"><span>已解锁部件</span><b>${profile.unlocked.length} / ${Object.values(parts).flat().length}</b></div><div class="record-row"><span>研发余额</span><b>◈ ${profile.credits.toLocaleString()}</b></div><div class="record-row"><span>档案存储</span><b>当前设备 · 自动保存</b></div></div><div class="modal-actions"><button class="primary" data-close>继续整备</button></div>`)}
function battleMessage(main,sub){$('combat-message').innerHTML=`${main}<small>${sub||''}</small>`;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('combat-message').innerHTML='',1400)}
function damageFloat(f,text,type){if(!engine)return;const pos=engine.project(f),el=document.createElement('div');el.className='floating-damage '+(type==='player'?'player-damage':type==='parry'?'parry-damage':'');el.textContent=text;el.style.left=pos.x+'px';el.style.top=pos.y+'px';if(type==='miss'){el.style.fontSize='13px';el.style.color='#9aabb5'}$('battle-view').append(el);setTimeout(()=>el.remove(),800)}
function updateHud(s){if(performance.now()-lastHud<45)return;lastHud=performance.now();$('player-hp-label').textContent=`${Math.ceil(s.playerHp)} / ${s.playerMax}`;$('player-health').style.width=(s.playerHp/s.playerMax*100)+'%';$('player-energy').style.width=(s.energy/s.maxEnergy*100)+'%';$('energy-label').textContent=Math.floor(s.energy);$('enemy-hp-label').textContent=`${Math.ceil(s.enemyHp)} / ${s.enemyMax}`;$('enemy-health').style.width=(s.enemyHp/s.enemyMax*100)+'%';$('enemy-name').textContent=`${s.enemyName} / ${s.enemyEn}`;$('enemy-stagger').style.width=s.stagger/75*100+'%';$('enemy-intent').textContent=s.enemyIntent;$('battle-timer').textContent=s.training?'∞':`${Math.floor(s.time/60).toString().padStart(2,'0')}:${Math.floor(s.time%60).toString().padStart(2,'0')}`;$('ultimate-label').textContent=s.rage>0?`狂热 ${s.rage.toFixed(1)}s`:s.ult>=100?'已就绪 · 释放核心':`${Math.floor(s.ult)}% 充能`;$('ultimate-fill').style.width=s.ult+'%';$('dash-status').textContent=s.dashCd>0?s.dashCd.toFixed(1)+'s 冷却':'已就绪';$('dash-cooldown').style.width=(1-s.dashCd/1.05)*100+'%';document.querySelector('.ultimate-button').classList.toggle('ready',s.ult>=100)}
function startBattle(reset=true,startHp){if(!engine){toast('3D 引擎仍在准备，请稍候');return}if(reset){round=0;wave=1;bonusHp=0;bonusDamage=0}resultState=null;$('modal').hidden=true;$('hangar-view').hidden=true;$('battle-view').hidden=false;document.body.classList.add('in-battle');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view==='arena'));$('combo-display').innerHTML='';engine.unlockAudio();
 const enemy=mode==='survival'?{...opponents[(wave-1)%3],hp:Math.round(130*(1+(wave-1)*.16)),damage:13*(1+(wave-1)*.09),speed:Math.min(5,3.5+wave*.12)}:opponents[round];
 engine.start($('battle-scene-host'),{mode,enemy,training:mode==='training',extraEnemy:mode==='survival'&&wave>=3&&wave%3===0,bonusHp,bonusDamage,startHp});
 $('round-label').textContent=mode==='training'?'训练模式':mode==='survival'?`生存挑战 · 第 ${wave} 波`:`冠军联赛 · 第 ${round+1} / 3 轮`;$('battle-tip').textContent=mode==='training'?'练习 J 连击、K 重击和 Q 核心。按 Esc 返回机库。':enemy.description||'保留耐久，利用闪避和格挡迎接下一波。';updateHud(engine.snapshot());
}
function backToHangar(){clearTimeout(messageTimer);$('combat-message').innerHTML='';$('modal').hidden=true;$('battle-view').hidden=true;$('hangar-view').hidden=false;document.body.classList.remove('in-battle');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view==='hangar'));engine.showHangar($('scene-host'));render()}
function pause(){if(engine.mode!=='battle'||engine.ended||!$('modal').hidden)return;engine.paused=true;engine.keys.clear();engine.player.block=false;engine.player.blockHeld=false;showModal(`<div class="eyebrow">SYSTEM PAUSED / 战术暂停</div><h2>喘口气，调整策略。</h2><p>战斗已暂停。返回机库将结束当前挑战，已获得的零件点会保留。</p><div class="settings-row"><span>战斗音效</span><button data-audio>${engine.soundOn?'已开启':'已关闭'}</button></div><div class="tip-box">J 连击 · K 重击 · Space 闪避 · Shift 格挡 · Q 核心爆发<br>面对重锤应优先闪避；对手收招时是最佳进攻时机。</div><div class="modal-actions"><button data-hangar>返回机库</button><button class="primary" data-resume>继续战斗</button></div>`)}
function resume(){if(engine?.mode==='battle'){engine.paused=false;engine.keys.clear();engine.player.block=false}$('modal').hidden=true}
function onEnd(r){if(resultState)return;resultState=r;profile.totalKills+=r.kills;let earned=0;if(r.win){profile.wins++;earned=mode==='survival'?250:600;if(mode==='survival')profile.bestWave=Math.max(profile.bestWave,wave);if(mode==='league'&&round===2){profile.championships++;earned+=1200}}else{profile.losses++;earned=100}profile.credits+=earned;save();$('credits').textContent=profile.credits.toLocaleString();const complete=mode==='league'&&round===2&&r.win,canContinue=r.win&&!complete;roundReward='repair';
 showModal(`<div class="eyebrow">${complete?'LEAGUE CHAMPION / 铁环认证':r.win?'COMBAT REPORT / 战斗结算':'SYSTEM OFFLINE / 战斗结算'}</div><div class="result-heading">${complete?'CHAMPION.':r.win?'VICTORY.':'REBUILD. RETRY.'}</div><h2>${complete?'你就是新的铁环冠军。':r.win?(mode==='survival'?`第 ${wave} 波已肃清。`:`击败了${opponents[round].name}。`):'机体倒下，技师不会。'}</h2><p>${complete?'你的配装与操作经受住了最后的考验。更长的战斗，等待你在生存挑战中续写。':r.win?'回收可用部件，调整系统，为下一次交锋做好准备。':'试试更灵活的走位，或更厚重的装甲。每一次失败，都让下一次出击更有把握。'}</p><div class="result-grid"><div class="result-stat"><strong>${r.damage}</strong><span>有效伤害</span></div><div class="result-stat"><strong>${r.parries}</strong><span>完美弹反</span></div><div class="result-stat"><strong>+${earned}</strong><span>回收零件点</span></div></div>${canContinue?`<div class="section-label">轮间整备 <span>选择一项奖励 · 当前挑战有效</span></div><div class="reward-options"><button class="selected" data-reward="repair"><b>${mode==='league'?'装甲强化':'紧急修复'}</b>${mode==='league'?'耐久上限 +25':'恢复 55 耐久'}</button><button data-reward="damage"><b>武器超频</b>近战伤害 +10%</button><button data-reward="scrap"><b>资源回收</b>额外 +200 零件点</button></div><div class="tip-box">${mode==='league'?`下一个对手：${opponents[round+1].name}。${opponents[round+1].description} 联赛轮间耐久回满。`:'下一波保留剩余耐久并恢复 25 点。每三波出现双机夹击。'}</div>`:''}<div class="modal-actions"><button data-hangar>返回机库</button><button class="primary" ${canContinue?'data-next-round':complete?'data-champion-survival':'data-retry'}>${canContinue?'完成整备 · 下一场':complete?'挑战无尽生存':'再次挑战'}</button></div>`)
}
function nextRound(){if(!resultState?.win)return;let hp=resultState.hp+25;if(roundReward==='damage')bonusDamage+=.1;if(roundReward==='scrap'){profile.credits+=200;save()}if(roundReward==='repair'){if(mode==='league')bonusHp+=25;else hp+=55}if(mode==='league')round++;else wave++;startBattle(false,mode==='survival'?hp:undefined)}
function toggleSound(){engine.unlockAudio();engine.soundOn=!engine.soundOn;$('sound-toggle').style.color=engine.soundOn?'#ff743d':'';$('sound-toggle').title=engine.soundOn?'关闭声音':'开启声音';$('sound-toggle').setAttribute('aria-label',$('sound-toggle').title);engine.beep(440,.16,.04);toast(engine.soundOn?'战斗音效已开启':'战斗音效已关闭')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))closeModal();if(b.dataset.slot){selectedSlot=b.dataset.slot;render()}if(b.dataset.part)choosePart(b.dataset.part);if(b.dataset.preset)preset(b.dataset.preset);if(b.dataset.paint){profile.color=b.dataset.paint;rebuild()}if(b.dataset.buy){const p=parts[selectedSlot].find(p=>p.id===b.dataset.buy);if(p&&!profile.unlocked.includes(p.id)&&profile.credits>=p.cost){profile.credits-=p.cost;profile.unlocked.push(p.id);profile.loadout[selectedSlot]=p.id;$('modal').hidden=true;rebuild();toast(p.name+'已解锁并装配')}}if(b.dataset.view&&engine.mode==='battle')return;if(b.dataset.view==='guide')guide();if(b.dataset.view==='arena')arenaOverview();if(b.dataset.view==='hangar'&&engine.mode==='hangar')$('modal').hidden=true;if(b.dataset.mode){mode=b.dataset.mode;updateModeUI();$('modal').hidden=true;toast('已选择'+$('event-name').textContent)}if(b.hasAttribute('data-start-training')){mode='training';startBattle()}if(b.hasAttribute('data-start-league')){mode='league';startBattle()}if(b.hasAttribute('data-open-modes'))modes();if(b.hasAttribute('data-hangar'))backToHangar();if(b.hasAttribute('data-resume'))resume();if(b.hasAttribute('data-audio')){toggleSound();b.textContent=engine.soundOn?'已开启':'已关闭'}if(b.dataset.reward){roundReward=b.dataset.reward;document.querySelectorAll('[data-reward]').forEach(x=>x.classList.toggle('selected',x===b))}if(b.hasAttribute('data-next-round'))nextRound();if(b.hasAttribute('data-retry'))startBattle();if(b.hasAttribute('data-champion-survival')){mode='survival';startBattle()}});
$('help-button').onclick=guide;$('mode-button').onclick=modes;$('records-button').onclick=records;$('deploy-button').onclick=()=>startBattle();$('pause-button').onclick=pause;$('sound-toggle').onclick=()=>engine&&toggleSound();$('rotate-toggle').onclick=()=>{engine.autoRotate=!engine.autoRotate;toast(engine.autoRotate?'自动旋转已开启':'自动旋转已暂停')};$('modal').addEventListener('click',e=>{if(e.target===$('modal')&&!resultState)closeModal()});document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(engine?.mode==='hangar')$('modal').hidden=true});
window.addEventListener('keydown',e=>{if(e.code==='Escape'){if(engine?.mode==='hangar')$('modal').hidden=true}});
for(const b of document.querySelectorAll('[data-action]')){b.addEventListener('pointerdown',e=>{e.preventDefault();engine.unlockAudio();b.setPointerCapture(e.pointerId);engine.action(b.dataset.action,true)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(b.dataset.action==='block')engine.action('block',false)})}
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);engine.setMove(b.dataset.move,true)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>engine.setMove(b.dataset.move,false))}
render();
try{engine=new IronEngine($('scene-host'),{message:battleMessage,float:damageFloat,update:updateHud,end:onEnd,pause:()=>{if(engine?.paused)resume();else pause()},notice:toast,combo:n=>{$('combo-display').innerHTML=n>1?`${String(n).padStart(2,'0')} HITS<small>${n>=8?'超载连击':n>=4?'持续压制':'连击命中'}</small>`:''},hazard:text=>$('hazard-label').textContent=text});engine.setBuild(profile.loadout,profile.color);$('loading-scene').hidden=true;window.__IRON__={getSnapshot:()=>({mode:engine.mode,paused:engine.paused,profile:structuredClone(profile),battle:engine.mode==='battle'?engine.snapshot():null}),getRendererInfo:()=>({calls:engine.renderer.info.render.calls,triangles:engine.renderer.info.render.triangles})};}catch(error){console.error(error);$('loading-scene').innerHTML='<p style="padding:30px;text-align:center;line-height:2">无法启动 3D 引擎。<br>请开启浏览器硬件加速，使用支持 WebGL 的浏览器重新打开。</p>';$('deploy-button').disabled=true}

document.addEventListener('keydown',e=>{if(e.key!=='Tab'||$('modal').hidden)return;const buttons=[...$('modal-content').querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
