import fs from 'node:fs';
import * as RealThree from '../dist/vendor/three.module.js';
import * as Cannon from '../dist/vendor/cannon-es.js';
class Element {constructor(){this.style={};this.classList={add(){},remove(){},toggle(){}};this.clientWidth=900;this.clientHeight=650;this.open=false;}addEventListener(){}appendChild(){}querySelector(){return new Element();}setAttribute(){}close(){this.open=false;}showModal(){this.open=true;}setPointerCapture(){}}
const elements={};const document={getElementById(id){return elements[id]??=new Element();},querySelector(){return null;},querySelectorAll(){return [];},addEventListener(){}};
const window={addEventListener(){},scrollTo(){}};const store=new Map();const localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};
class Renderer {constructor(){this.domElement=new Element();this.shadowMap={};}setPixelRatio(){}setSize(){}render(){}}
const THREE={...RealThree,WebGLRenderer:Renderer};const code=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
const api=new Function('THREE','CANNON','document','window','localStorage','devicePixelRatio','innerWidth','innerHeight','ResizeObserver','requestAnimationFrame',code+`\nreturn {state:gameState,startGame,drop,rotate,steady,slow,togglePause,update,reset,setMode(m){mode=m;},align(){moveTime=Math.PI;aimOffset=0;update(0);},miss(){moveTime=Math.PI/2;aimOffset=1.3;update(0);},topple(){const b=blocks.find(b=>!b.seed);b.body.position.set(5,2,0);b.body.wakeUp();},details(){return blocks.map(b=>({type:b.type,y:b.body.position.y,accepted:b.accepted,contact:b.contact,v:b.body.velocity.length(),a:b.body.angularVelocity.length(),up:b.body.quaternion.y}));}};`)(THREE,Cannon,document,window,localStorage,1,1280,800,class {observe(){}},()=>{});
function advance(seconds){for(let i=0;i<seconds*90;i++)api.update(1/90);}
function assert(v,m){if(!v)throw Error(m);}
const report=[];
for(const mode of ['classic','cozy','storm']){api.setMode(mode);api.startGame();let landed=0;for(let i=0;i<(mode==='classic'?20:4);i++){api.align();if(i===1)api.rotate();api.drop();api.drop();for(let f=0;f<900&&api.state().phase==='falling';f++)api.update(1/90);if(api.state().layers!==i+1){console.log(JSON.stringify({failure:mode,at:i+1,state:api.state(),bodies:api.details()},null,2));throw Error('Could not land centered block');}landed++;if(i===1){api.steady();assert(api.state().remainingTools.steady===(mode==='cozy'?3:1),'steady charge');api.slow();assert(api.state().remainingTools.slow===(mode==='cozy'?3:1),'slow charge');}if(api.state().phase==='ended')break;}report.push({mode,layers:landed,score:api.state().score,status:api.state().phase});}
api.setMode('classic');api.startGame();api.togglePause();const before=api.state();advance(1);assert(api.state().layers===before.layers&&api.state().paused,'pause');api.togglePause();api.miss();api.drop();advance(4);assert(api.state().phase==='ended','miss should end');report.push({miss:'ended correctly'});
api.setMode('cozy');api.startGame();api.miss();api.drop();advance(4);assert(api.state().phase==='aiming'&&api.state().layers===0,'cozy rescue');report.push({cozyMiss:'rescued correctly'});
api.setMode('classic');api.startGame();api.align();api.drop();advance(3);assert(api.state().layers===1,'setup for collapse');api.topple();advance(3);assert(api.state().phase==='ended','accepted tower ground contact should end game');report.push({towerCollapse:'detected correctly'});
api.startGame();assert(api.state().score===0&&api.state().layers===0,'restart');console.log(JSON.stringify({passed:true,checks:report},null,2));
