import test from 'node:test';
import assert from 'node:assert/strict';
import {MISSIONS,generate,rotate,normalize,key,worldCells,validation,solve,volume} from '../src/game.js';
import {GameSession} from '../src/session.js';
const canon=c=>c.map(key).sort().join('|');
for(const m of MISSIONS){test(`${m.name}: generated exact cover, rotations, solver, complete session`,()=>{const pieces=generate(m),placements=[];assert.equal(pieces.length,m.pieces);for(const p of pieces){assert.equal(validation(p.solution,p.pos,m.dims,placements),'');placements.push({id:p.id,cells:p.solution,pos:p.pos});for(const axis of ['x','y','z']){let cells=p.cells;for(let n=0;n<4;n++)cells=rotate(cells,axis);assert.equal(canon(cells),canon(normalize(p.cells)));}}assert.equal(new Set(placements.flatMap(p=>worldCells(p).map(key))).size,volume(m.dims));const s=new GameSession(m.id);assert.equal(s.finish(),null);const solution=solve(s.remaining,m.dims,s.placements).solution;assert.ok(solution);for(const p of solution){s.select(p.id);s.cells=p.cells;s.pos=p.pos;assert.equal(s.place().ok,true);}assert.equal(s.full,true);assert.equal(s.finish().stars,3);assert.equal(s.place().ok,false);});}
test('illegal placement and invalid staging do not corrupt state',()=>{const s=new GameSession(0),before=structuredClone(s.placements);s.pos=[3,1,2];s.cells=[[0,0,0],[1,0,0]];assert.equal(s.place().ok,false);assert.deepEqual(s.placements,before);assert.throws(()=>s.stage(s.selected,[NaN,0,0]));assert.throws(()=>s.stage(s.selected,[0,0,0],['bad']));assert.deepEqual(s.placements,before);});
test('place, unload and undo conserve cargo without duplicates',()=>{const s=new GameSession(0);const start=structuredClone(s.placements);const p=s.remaining[0];s.selected=p.id;s.cells=p.solution;s.pos=p.pos;assert.equal(s.place().ok,true);assert.equal(s.remove(p.id),true);assert.equal(s.undo(),true);assert.equal(s.placements.some(q=>q.id===p.id),true);assert.equal(s.undo(),true);assert.deepEqual(s.placements,start);assert.equal(s.undo(),false);assert.equal(s.remove(start[0].id),false);});
test('daily puzzle is deterministic by date and different next day',()=>{const a=new GameSession(1,'daily',new Date(2026,9,4));const b=new GameSession(1,'daily',new Date(2026,9,4));const c=new GameSession(1,'daily',new Date(2026,9,5));assert.deepEqual(a.pieces,b.pieces);assert.notDeepEqual(a.pieces,c.pieces);});
test('hints are previews, limited to three, and recovery is undoable',()=>{const s=new GameSession(0);const p=s.remaining[0],o={id:p.id,cells:p.solution,pos:p.pos};const used=s.used;assert.equal(s.hintPlacement(o),true);assert.equal(s.used,used);assert.equal(s.place().ok,true);const old=structuredClone(s.placements);assert.equal(s.resetToReference(),true);assert.equal(s.hints,2);assert.equal(s.undo(),true);assert.deepEqual(s.placements,old);const q=s.remaining[0];assert.equal(s.hintPlacement({id:q.id,cells:q.solution,pos:q.pos}),true);assert.equal(s.hints,3);assert.equal(s.resetToReference(),false);});
test('collision boundaries distinguish adjacency from overlap',()=>{const p=[{id:1,cells:[[0,0,0]],pos:[1,1,1]}];assert.equal(validation([[0,0,0]],[2,1,1],[3,3,3],p),'');assert.match(validation([[0,0,0]],[1,1,1],[3,3,3],p),/重叠/);for(const pos of [[-1,0,0],[3,0,0],[0,-1,0],[0,3,0],[0,0,-1],[0,0,3]])assert.match(validation([[0,0,0]],pos,[3,3,3],[]),/边界/);});
