import * as THREE from './vendor/three.module.js';
import {LEVELS, FORMS} from './levels.js';
const $ = (q) => document.querySelector(q);
const TILE=1.6, STORAGE='morph-lab-progress-v1';
let save={completed:[],best:{},sound:false};try{save={...save,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(save))}catch{}}
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x16251d,.014);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch(e){$('#loading').innerHTML='<p>当前浏览器无法启动 3D 画面，请开启硬件加速后重新打开。</p>';throw e;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#scene').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-14,14,9,-9,.1,150);
scene.add(new THREE.HemisphereLight(0xdceccc,0x274235,2.0));
const sun=new THREE.DirectionalLight(0xfff1bf,3.4);sun.position.set(-8,18,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;sun.shadow.bias=-.0004;sun.shadow.normalBias=.03;scene.add(sun);
const rim=new THREE.DirectionalLight(0x8bbbac,2.1);rim.position.set(8,10,-12);scene.add(rim);
const ambientGlow=new THREE.PointLight(0xbaff7b,5,18);ambientGlow.position.set(0,4,0);scene.add(ambientGlow);
const world=new THREE.Group();scene.add(world);
const effects=new THREE.Group();scene.add(effects);
const mats={floor:new THREE.MeshStandardMaterial({color:0x647757,roughness:.89}),floor2:new THREE.MeshStandardMaterial({color:0x596d4f,roughness:.92}),edge:new THREE.MeshStandardMaterial({color:0x344638,roughness:1}),wall:new THREE.MeshStandardMaterial({color:0x516d50,roughness:.85}),wallTop:new THREE.MeshStandardMaterial({color:0x7e9767,roughness:.85}),dark:new THREE.MeshStandardMaterial({color:0x21392d,roughness:.8}),gold:new THREE.MeshStandardMaterial({color:0xdeb166,emissive:0xd89b30,emissiveIntensity:.22,metalness:.45,roughness:.32}),lime:new THREE.MeshStandardMaterial({color:0xb6ef73,emissive:0x85d936,emissiveIntensity:.45,roughness:.4}),purple:new THREE.MeshStandardMaterial({color:0xb49ae6,emissive:0x7753b5,emissiveIntensity:.5,metalness:.35,roughness:.3}),water:new THREE.MeshPhysicalMaterial({color:0x5cabac,transparent:true,opacity:.78,roughness:.14,metalness:.35}),laser:new THREE.MeshStandardMaterial({color:0xff856b,emissive:0xff4428,emissiveIntensity:2,transparent:true,opacity:.85})};
function mesh(geometry,material,x=0,y=0,z=0,parent=world){const o=new THREE.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,mat,x,y,z,parent){return mesh(new THREE.BoxGeometry(w,h,d),mat,x,y,z,parent)}
function cyl(r,h,mat,x,y,z,parent,n=12){return mesh(new THREE.CylinderGeometry(r,r,h,n),mat,x,y,z,parent)}
function torus(r,t,mat,x,y,z,parent){return mesh(new THREE.TorusGeometry(r,t,9,48),mat,x,y,z,parent)}
function at(col,row){return {x:(col-(cols-1)/2)*TILE,z:(row-(rows-1)/2)*TILE};}
let levelIndex=0,level,cols,rows,cubes=[],plates=[],gates=[],crystals=[],lasers=[],waters=[],switches=[],decor=[],portal,portalGlow;
let player={x:0,z:0,form:0,carry:null,dir:new THREE.Vector2(0,1),jump:0,stability:100};
let victoryTimer=null;
let elapsed=0,deaths=0,transforms=0,started=false,paused=false,won=false,hintIndex=0,touchedPassages=new Set(),laserDisabled=false;
let angle=.35,zoom=1,keys={},lastTime=performance.now(),time=0,toastTimer,interactNear=null,hazardCooldown=0,lastCheckpoint={x:0,z:0},cubeId=0;
const slimeRoot=new THREE.Group();scene.add(slimeRoot);
const slimeMat=new THREE.MeshPhysicalMaterial({color:0xadf451,emissive:0x639d27,emissiveIntensity:.27,roughness:.14,metalness:.04,transparent:true,opacity:.86,clearcoat:1,clearcoatRoughness:.1,side:THREE.DoubleSide});
const slime=mesh(new THREE.SphereGeometry(1,40,28),slimeMat,0,0,0,slimeRoot);slime.castShadow=true;
const core=mesh(new THREE.SphereGeometry(.33,16,12),new THREE.MeshStandardMaterial({color:0xd1ff80,emissive:0xa8e95a,emissiveIntensity:.6,transparent:true,opacity:.38}),0,0,0,slime);
const eyes=new THREE.Group();slimeRoot.add(eyes);const eyeMat=new THREE.MeshBasicMaterial({color:0x20391b}),shine=new THREE.MeshBasicMaterial({color:0xf9ffe5});
for(const x of [-.15,.15]){const eye=mesh(new THREE.SphereGeometry(.065,12,12),eyeMat,x,.6,.5,eyes);eye.scale.y=1.3;mesh(new THREE.SphereGeometry(.018,8,8),shine,x-.017,.63,.553,eyes)}
const mouth=torus(.065,.012,eyeMat,0,.47,.52,eyes);mouth.scale.set(1,.65,.3);mouth.rotation.x=.5;
const highlight=mesh(new THREE.SphereGeometry(.13,12,12),new THREE.MeshBasicMaterial({color:0xe9ffbd,transparent:true,opacity:.55}),-.23,.32,.63,slime);highlight.scale.set(.65,1,.16);
const groundRing=torus(.65,.017,new THREE.MeshBasicMaterial({color:0xbbf986,transparent:true,opacity:.5}),0,.07,0,slimeRoot);groundRing.rotation.x=Math.PI/2;
const dustGeometry=new THREE.BufferGeometry();const dustArray=new Float32Array(160*3);for(let i=0;i<160;i++){dustArray[i*3]=(Math.random()-.5)*35;dustArray[i*3+1]=Math.random()*9-2;dustArray[i*3+2]=(Math.random()-.5)*27}dustGeometry.setAttribute('position',new THREE.BufferAttribute(dustArray,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({size:.055,color:0xd4e7a1,transparent:true,opacity:.45}));scene.add(dust);
const motes=[];
function particles(x,z,color=0xbcef78,count=16){for(let i=0;i<count;i++){const p=mesh(new THREE.SphereGeometry(.045,5,4),new THREE.MeshBasicMaterial({color,transparent:true}),x,.4,z,effects);motes.push({mesh:p,v:new THREE.Vector3((Math.random()-.5)*2.8,Math.random()*3+.5,(Math.random()-.5)*2.8),life:1})}}
let audio;
function tone(freq=420,duration=.1,type='sine',gain=.07){if(!save.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.72,audio.currentTime+duration);g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function gridPosition(x,z){return{col:Math.round(x/TILE+(cols-1)/2),row:Math.round(z/TILE+(rows-1)/2)}}
function cell(x,z){const {col,row}=gridPosition(x,z);return level.map[row]?.[col]||'#'}
function makeWall(x,z,h=1.28){box(TILE-.025,h,TILE-.025,mats.wall,x,h/2+.02,z);box(TILE+.02,.09,TILE+.02,mats.wallTop,x,h+.035,z);if(Math.abs(z)>rows*TILE/2-TILE&&Math.random()>.4){box(.35,.13,.24,mats.floor2,x+.3,h+.13,z-.3)}}
function horizontalSlit(x,z){const {col,row}=gridPosition(x,z);return level.map[row]?.[col-1]!=='#'&&level.map[row]?.[col+1]!=='#'}
function makePass(x,z,kind){if(kind==='F'){box(TILE,.67,TILE-.06,mats.wall,x,.93,z);box(TILE+.04,.09,TILE,mats.wallTop,x,1.3,z);for(const d of [-1,1])box(.07,.045,TILE,mats.lime,x+d*.6,.075,z);for(let i=0;i<3;i++)box(.12,.07,.015,mats.lime,x+(i-1)*.24,.86,z+TILE/2)}else{const g=new THREE.Group();g.position.set(x,0,z);world.add(g);if(horizontalSlit(x,z))g.rotation.y=Math.PI/2;for(const d of [-1,1]){box(.47,1.8,TILE-.05,mats.wall,d*.56,.9,0,g);box(.06,1.45,.035,mats.lime,d*.335,.85,TILE/2,g)}box(TILE,.16,TILE,mats.wallTop,0,1.82,0,g)} }
function addPlant(x,z,seed){const g=new THREE.Group();g.position.set(x,.08,z);world.add(g);for(let i=0;i<4;i++){const a=i*2.2+seed;const leaf=mesh(new THREE.ConeGeometry(.09,.42+Math.sin(seed+i)*.1,4),new THREE.MeshStandardMaterial({color:i%2?0x9cb965:0x597c49}),Math.cos(a)*.13,.18,Math.sin(a)*.13,g);leaf.rotation.z=Math.cos(a)*.5;leaf.rotation.x=Math.sin(a)*.5}decor.push(g)}
function makeCube(x,z,channel){const g=new THREE.Group();world.add(g);g.position.set(x,.45,z);const mat=channel==='b'?mats.purple:mats.gold;box(.63,.63,.63,mats.dark,0,0,0,g);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(.66,.66,.66)),new THREE.LineBasicMaterial({color:channel==='b'?0xcab6fa:0xfcd17f}));g.add(edges);for(const [dx,dz]of[[0,.328],[0,-.328],[.328,0],[-.328,0]]){const gem=box(.18,.18,.025,mat,dx,0,dz,g);if(dx)gem.rotation.y=Math.PI/2;gem.rotation.z=Math.PI/4}cubes.push({id:++cubeId,x,z,home:{x,z},channel,mesh:g,onPlate:false})}
function makePlate(x,z,channel){const mat=channel==='b'?mats.purple:mats.gold;box(1,.11,1,mats.dark,x,.09,z);const ring=torus(.38,.035,mat,x,.16,z);ring.rotation.x=Math.PI/2;const light=new THREE.PointLight(channel==='b'?0xb899ff:0xffc162,0,3);light.position.set(x,.5,z);world.add(light);plates.push({x,z,channel,active:false,light,ring});for(const d of [-1,1])box(.1,.06,.1,mat,x+d*.45,.18,z+d*.45)}
function makeGate(x,z,channel){const mat=channel==='b'?mats.purple:mats.gold;const g=new THREE.Group();g.position.set(x,0,z);world.add(g);for(const d of [-1,1]){box(.2,1.7,.3,mats.dark,x+d*.7,.85,z);box(.05,1.45,.05,mat,x+d*.7,.85,z+.17)}for(let i=0;i<5;i++)box(.075,1.5,.09,mat,(i-2)*.26,.85,0,g);box(1.4,.08,.12,mat,0,1.62,0,g);gates.push({x,z,channel,open:false,mesh:g})}
function buildLevel(index){
 clearTimeout(victoryTimer);victoryTimer=null;
 levelIndex=index;level=LEVELS[index];rows=level.map.length;cols=level.map[0].length;
 world.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material&&!Object.values(mats).includes(o.material))o.material.dispose()});world.clear();for(const p of motes){p.mesh.geometry.dispose();p.mesh.material.dispose()}effects.clear();motes.length=0;
 cubes=[];plates=[];gates=[];crystals=[];lasers=[];waters=[];switches=[];decor=[];cubeId=0;
 elapsed=0;deaths=0;transforms=0;started=false;won=false;paused=false;hintIndex=0;touchedPassages.clear();laserDisabled=false;hazardCooldown=0;keys={};player.carry=null;player.form=0;player.stability=100;player.jump=0;
 const bw=cols*TILE,bh=rows*TILE;
 box(bw+.26,.58,bh+.26,mats.edge,0,-.34,0);box(bw+.4,.1,bh+.4,mats.dark,0,-.05,0);box(bw-.4,.7,bh-.4,new THREE.MeshStandardMaterial({color:0x263c30,roughness:1}),0,-.94,0);
 for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){
  const ch=level.map[row][col],{x,z}=at(col,row);box(TILE-.045,.13,TILE-.045,(row+col)%3===0?mats.floor2:mats.floor,x,-.005,z);
  if(ch==='#')makeWall(x,z,(row===rows-1)? .42 : 1.16+((row*17+col*3)%3)*.07);
  else if(ch==='F'||ch==='T')makePass(x,z,ch);
  else if(ch==='S'){player.x=x;player.z=z;lastCheckpoint={x,z};const ring=torus(.43,.025,mats.lime,x,.085,z);ring.rotation.x=Math.PI/2;}
  else if(ch==='c'||ch==='d')makeCube(x,z,ch==='d'?'b':'a');
  else if(ch==='a'||ch==='b')makePlate(x,z,ch);
  else if(ch==='A'||ch==='B')makeGate(x,z,ch.toLowerCase());
  else if(ch==='*'){const g=new THREE.Group();g.position.set(x,.65,z);world.add(g);const gem=mesh(new THREE.OctahedronGeometry(.3),mats.gold,0,0,0,g);gem.scale.y=1.5;const r=torus(.31,.016,new THREE.MeshBasicMaterial({color:0xe3bd6e,transparent:true,opacity:.5}),0,-.51,0,g);r.rotation.x=Math.PI/2;crystals.push({x,z,mesh:g,collected:false,offset:row+col})}
  else if(ch==='~'){const water=box(TILE-.03,.08,TILE-.03,mats.water,x,.08,z);waters.push(water);for(let i=0;i<2;i++){const r=torus(.25+i*.2,.012,new THREE.MeshBasicMaterial({color:0xb2edef,transparent:true,opacity:.4}),x,.135,z);r.rotation.x=Math.PI/2;waters.push(r)}}
  else if(ch==='!'){const beams=new THREE.Group();world.add(beams);beams.position.set(x,0,z);for(const d of [-1,1]){cyl(.12,.7,mats.dark,x,.35,z+d*.7);cyl(.07,.08,mats.laser,x,.74,z+d*.7)}for(let i=0;i<3;i++)box(.035,.035,1.4,mats.laser,0,.25+i*.22,0,beams);lasers.push({x,z,mesh:beams,active:true})}
  else if(ch==='s'){box(.2,1.65,.2,mats.dark,x,.82,z);const b=box(.34,.32,.16,mats.gold,x,1.55,z+.14);switches.push({x,z,mesh:b,active:false})}
  else if(ch==='X'){const g=new THREE.Group();g.position.set(x,0,z);world.add(g);cyl(.72,.18,mats.dark,0,.12,0,g,32);const baseRing=torus(.62,.05,mats.gold,0,.24,0,g);baseRing.rotation.x=Math.PI/2;const r=torus(.68,.09,mats.gold,0,1.02,0,g);const r2=torus(.55,.025,mats.gold,0,1.02,.02,g);portalGlow=mesh(new THREE.CircleGeometry(.56,40),new THREE.MeshBasicMaterial({color:0xf0d6a1,transparent:true,opacity:.13,side:THREE.DoubleSide}),0,1.02,.01,g);portal={x,z,mesh:g,ring:r,inner:r2,active:false};const l=new THREE.PointLight(0xffce73,3,4);l.position.set(0,1,0);g.add(l);}
  else if(ch==='.'&&((col*13+row*7)%23===0))addPlant(x+.5,z-.5,col+row);
 }
 // Small vegetation and stones along the floating island's shoulders.
 for(let i=0;i<cols;i+=2){const p=at(i,0);addPlant(p.x+.2,p.z-.1,i);}
 for(let i=0;i<8;i++){const x=(i%2?1:-1)*(bw/2+.4+Math.sin(i)*.25),z=((i*3)%rows-rows/2)*TILE;const rock=mesh(new THREE.DodecahedronGeometry(.22+i%3*.06,0),mats.edge,x,-.6,z);rock.rotation.set(i,i*.7,i*.3)}
 // Color-coded traces connect each plate to its matching gate.
 for(const p of plates){const gate=gates.find(g=>g.channel===p.channel);if(gate){const color=p.channel==='b'?0xa186c5:0xc7a260;const points=[new THREE.Vector3(p.x,.081,p.z),new THREE.Vector3(gate.x,.081,p.z),new THREE.Vector3(gate.x,.081,gate.z)];world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity:.55})))}}
 updateUI();resetCamera();$('#loading').classList.add('hidden');slimeRoot.position.set(player.x,0,player.z);tone(430,.16);}
function updateUI(){
 $('#chapter-no').textContent=`实验 ${String(levelIndex+1).padStart(2,'0')}`;$('#chapter-theme').textContent=level.theme;$('#level-title').textContent=level.title;$('#level-description').textContent=level.description;$('#world-caption').textContent=level.place;$('#island-no').textContent=String(levelIndex+1).padStart(2,'0');
 $('#hint-text').textContent=level.hints[0];$('#objectives').innerHTML=level.objectives.map((t,i)=>`<li data-objective="${i}"><span class="objective-check"></span><span>${t}</span></li>`).join('');
 $('#level-buttons').innerHTML=LEVELS.map((l,i)=>`<button class="level-button ${i===levelIndex?'active':''} ${save.completed.includes(i)?'completed':''}" data-level="${i}" title="${l.name}${save.best[i]?' · 最快 '+formatTime(save.best[i]):''}"><span class="level-number">${save.completed.includes(i)?'✓':String(i+1).padStart(2,'0')}</span><div>${l.name}<small>${i===levelIndex?'EXPLORING':save.completed.includes(i)?'COMPLETED':'EXPLORE'}</small></div></button>`).join('');
 document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{closeModal();buildLevel(Number(b.dataset.level))});$('#total-completed').textContent=save.completed.length;updateForms();updateStats();}
function objective(i,done){const li=$(`[data-objective="${i}"]`);li.classList.toggle('done',done);li.querySelector('.objective-check').textContent=done?'✓':''}
function updateStats(){const count=crystals.filter(c=>c.collected).length;$('#crystal-count').innerHTML=`${count} <em>/ ${crystals.length}</em>`;$('#timer').textContent=formatTime(elapsed);objective(0,plates.length?plates.every(p=>p.active):levelIndex===0?touchedPassages.has('F'):touchedPassages.has('F')&&touchedPassages.has('T'));objective(1,count===crystals.length);objective(2,won);$('#stability-fill').style.width=`${player.stability}%`;$('#stability').textContent=`${Math.round(player.stability)}%`;}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function updateForms(){document.querySelectorAll('.form-card').forEach((b,i)=>{b.classList.toggle('active',i===player.form);b.setAttribute('aria-pressed',String(i===player.form))});$('#current-form-name').textContent=FORMS[player.form].name;$('#current-form-desc').textContent=FORMS[player.form].description;$('#carry-label').textContent=player.carry?'放下方块':'包裹 / 放下';}
function blocked(x,z,form=player.form,ignoreCube=null){const r=FORMS[form].radius;for(const [ox,oz]of[[0,0],[-r,-r],[r,-r],[-r,r],[r,r]]){const ch=cell(x+ox,z+oz);if(ch==='T'&&form===2){const gp=gridPosition(x+ox,z+oz);const center=at(gp.col,gp.row);if(Math.abs(horizontalSlit(center.x,center.z)?z+oz-center.z:x+ox-center.x)>.32)return true}if(ch==='#'||(ch==='F'&&form!==1)||(ch==='T'&&form!==2))return true;if(ch==='A'||ch==='B'){const g=gates.find(g=>g.channel===ch.toLowerCase());if(g&&!g.open)return true}}for(const c of cubes){if(c===player.carry||c===ignoreCube)continue;if(Math.abs(x-c.x)<.33+r&&Math.abs(z-c.z)<.33+r)return true;}return false;}
function setForm(form){if(paused||won)return false;if(form===player.form)return true;if(player.carry){toast('先按 E 放下方块，再改变形态。');tone(160,.1);return false}if(blocked(player.x,player.z,form)){toast('这里太窄，先走出通道再变形。');return false}if(cell(player.x,player.z)==='~'&&form!==1){toast('水面上请保持扁平，漂到岸边再变形。');return false}player.form=form;transforms++;started=true;particles(player.x,player.z,0xbcef78,10);tone(260+form*160,.15);updateForms();return true;}
function updateCircuits(){for(const p of plates){const active=cubes.some(c=>c!==player.carry&&c.channel===p.channel&&Math.hypot(c.x-p.x,c.z-p.z)<.6);if(active&&!p.active){particles(p.x,p.z,p.channel==='b'?0xbdaaed:0xf8cb76,22);tone(650,.25);toast(p.channel==='b'?'紫色回路已接通。':'琥珀回路已接通，屏障开启。')}p.active=active;p.light.intensity=active?3:0;p.ring.scale.setScalar(active?1.05:1)}for(const g of gates){const wantsOpen=plates.filter(p=>p.channel===g.channel).every(p=>p.active);g.open=wantsOpen||(g.open&&Math.hypot(player.x-g.x,player.z-g.z)<1.1);}}
function interact(){if(paused||won)return;started=true;if(player.carry){const c=player.carry;const p=plates.find(p=>p.channel===c.channel&&Math.hypot(player.x-p.x,player.z-p.z)<1.65&&!cubes.some(other=>other!==c&&Math.hypot(other.x-p.x,other.z-p.z)<.6));let target=p?{x:p.x,z:p.z}:null;if(!target){for(const d of [player.dir,new THREE.Vector2(0,1),new THREE.Vector2(1,0),new THREE.Vector2(-1,0),new THREE.Vector2(0,-1)]){const point={x:player.x+d.x*1.18,z:player.z+d.y*1.18};if(!blocked(point.x,point.z,0,c)&&!['~','F','T','!','A','B'].includes(cell(point.x,point.z))){target=point;break}}}if(!target){toast('找一块空地再放下方块。');return}if(Math.abs(player.x-target.x)<.8&&Math.abs(player.z-target.z)<.8){const spots=[[0,1],[1,0],[0,-1],[-1,0]].map(([dx,dz])=>({x:target.x+dx*1.1,z:target.z+dz*1.1})).filter(p=>!blocked(p.x,p.z,0,c)&&!['~','F','T','!'].includes(cell(p.x,p.z))).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z));if(!spots.length){toast('退后一点，给方块留出空间。');return}player.x=spots[0].x;player.z=spots[0].z}c.x=target.x;c.z=target.z;c.mesh.position.set(c.x,.45,c.z);player.carry=null;particles(c.x,c.z,0xe4c079,10);tone(220,.18);updateCircuits();updateForms();return;}
 const sw=switches.find(s=>Math.hypot(player.x-s.x,player.z-s.z)<1.45);if(sw){if(player.form!==2){toast('这个开关太高了，按 3 伸长身体。');return}sw.active=!sw.active;laserDisabled=sw.active;toast(sw.active?'安全模式已开启，激光停止。':'激光重新启动。');tone(760,.15);return}
 const c=cubes.filter(c=>Math.hypot(player.x-c.x,player.z-c.z)<1.55).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];if(!c){toast('靠近发光方块，再按 E 包裹。');return}if(player.form!==0){toast('按 1 回到原生形态，才能包裹方块。');return}player.carry=c;particles(player.x,player.z,0xb9f080,18);tone(370,.18);updateCircuits();updateForms();}
function respawn(message){if(hazardCooldown>0)return;deaths++;hazardCooldown=1.5;player.stability=Math.max(0,player.stability-24);particles(player.x,player.z,0xf5b07a,22);player.x=lastCheckpoint.x;player.z=lastCheckpoint.z;if(player.carry){player.carry.x=player.carry.home.x;player.carry.z=player.carry.home.z;player.carry.mesh.position.set(player.carry.x,.45,player.carry.z);player.carry=null;updateForms();updateCircuits()}toast(message);tone(130,.3);}
function win(){if(won)return;won=true;keys={};if(!save.completed.includes(levelIndex))save.completed.push(levelIndex);save.best[levelIndex]=Math.min(save.best[levelIndex]??Infinity,Math.ceil(elapsed));persist();updateStats();particles(player.x,player.z,0xffd484,50);tone(880,.6);victoryTimer=setTimeout(()=>{const stars=deaths===0&&elapsed<=level.par?3:deaths<=2?2:1;showModal(`<div class="modal-eyebrow">EXPERIMENT ${String(levelIndex+1).padStart(2,'0')} / COMPLETE</div><div class="result-symbol">${'✦'.repeat(stars)}<span style="opacity:.2">${'✦'.repeat(3-stars)}</span></div><h2 class="modal-title">${levelIndex===4?'柔软的你，无所不能。':'这一次，你找到了可能。'}</h2><p class="modal-copy">${levelIndex===4?'五座实验岛都已点亮。你掌握了身体的每一种形态，也为自己打开了每一扇门。':'实验完成。带着新的灵感，去下一座岛看看吧。'}</p><div class="result-stats"><div><b>${formatTime(elapsed)}</b><span>完成用时</span></div><div><b>${transforms}</b><span>形态变化</span></div><div><b>${deaths}</b><span>失误次数</span></div></div><p class="modal-copy" style="font-size:12px">三星挑战：${level.par} 秒内、零失误通关 · 本机最佳 ${formatTime(save.best[levelIndex])}</p><div class="modal-actions"><button class="primary-button" id="next-level">${levelIndex<4?'探索下一座岛':'再来一次实验'}</button><button class="secondary-button" id="replay-level">重玩本关</button></div>`);$('#next-level').onclick=()=>{closeModal();buildLevel((levelIndex+1)%5)};$('#replay-level').onclick=()=>{closeModal();buildLevel(levelIndex)};},750)}
function showModal(html){keys={};paused=true;$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();paused=false;keys={}}
function help(){showModal('<div class="modal-eyebrow">A LITTLE FIELD GUIDE</div><h2 class="modal-title">你的柔软使用说明。</h2><p class="modal-copy">收集每座岛上的琥珀晶体，点亮传送门。遇到走不通的路，试着换一种形状。</p><div class="help-grid"><div><strong>WASD / 方向键</strong>相对当前镜头移动<br>空格：向前弹跃加速</div><div><strong>1 · 原生形态</strong>靠近方块按 E 包裹<br>搬到底座后按 E 放下</div><div><strong>2 · 扁平形态</strong>穿过绿色横缝<br>漂浮通过蓝色水池</div><div><strong>3 · 细长形态</strong>穿过绿色竖缝<br>按 E 触发高处开关</div><div><strong>机关与危险</strong>底座与方块需颜色对应<br>红色激光变暗后可穿过</div><div><strong>更多操作</strong>H 分步提示 · R 重玩<br>ESC 暂停 · 拖动画面旋转</div></div><p class="modal-copy" style="font-size:12px">所有实验可自由选择。每关零失误且在目标时间内完成，即可获得三星。</p><button id="help-done" class="primary-button">明白了，开始探索</button>');$('#help-done').onclick=closeModal}
function togglePause(){if($('#modal').open){closeModal();return}showModal('<div class="modal-eyebrow">TAKE A LITTLE BREATH</div><h2 class="modal-title">歇一会儿，也没关系。</h2><p class="modal-copy">实验已暂停。小史莱姆会在这里等你。</p><div class="modal-actions"><button id="resume" class="primary-button">继续实验</button><button id="restart" class="secondary-button">重新开始</button></div>');$('#resume').onclick=closeModal;$('#restart').onclick=()=>{closeModal();buildLevel(levelIndex)}}
function giveHint(){if(won)return;const text=level.hints[hintIndex++%level.hints.length];$('#hint-text').textContent=text;toast(text)}
function resetCamera(){angle=.35;zoom=1;resize()}
function resize(){const r=$('#scene').getBoundingClientRect();renderer.setSize(r.width,r.height);const aspect=r.width/r.height;const height=Math.max(rows*TILE*.67,cols*TILE*.58/aspect)*(r.width<780?1.38:1.1)/zoom;camera.left=-height*aspect;camera.right=height*aspect;camera.top=height;camera.bottom=-height;camera.updateProjectionMatrix();updateCamera()}
function updateCamera(){camera.position.set(Math.sin(angle)*28,25,Math.cos(angle)*28);camera.lookAt(0,-.7,0)}
const pointer={down:false,x:0,start:0};renderer.domElement.addEventListener('pointerdown',e=>{pointer.down=true;pointer.x=e.clientX;pointer.start=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(pointer.down){angle-=(e.clientX-pointer.x)*.006;pointer.x=e.clientX;updateCamera()}});renderer.domElement.addEventListener('pointerup',()=>pointer.down=false);renderer.domElement.addEventListener('pointercancel',()=>pointer.down=false);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom-e.deltaY*.001, .72,1.6);resize()},{passive:false});
window.addEventListener('resize',resize);window.addEventListener('blur',()=>{keys={};pointer.down=false});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};if(started&&!won&&!paused)togglePause()}});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){e.preventDefault();togglePause();return}if($('#modal').open||e.repeat)return;keys[e.code]=true;if(['Digit1','Digit2','Digit3'].includes(e.code))setForm(Number(e.code.slice(-1))-1);if(e.code==='KeyE')interact();if(e.code==='KeyR')buildLevel(levelIndex);if(e.code==='KeyH')giveHint();if(e.code==='Space')jump()});window.addEventListener('keyup',e=>keys[e.code]=false);
function jump(){if(paused||won||player.jump>0)return;started=true;player.jump=.5;tone(280,.15);particles(player.x,player.z,0xc5ec99,7)}
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='Space')jump()});b.addEventListener('pointerup',()=>keys[b.dataset.key]=false);b.addEventListener('pointercancel',()=>keys[b.dataset.key]=false)}
$('#help-btn').onclick=help;$('#pause-btn').onclick=togglePause;$('#interact-btn').onclick=interact;$('#hint-btn').onclick=giveHint;$('#camera-btn').onclick=resetCamera;$('#modal-close').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal()});document.querySelectorAll('[data-form]').forEach(b=>b.onclick=()=>setForm(Number(b.dataset.form)));
function updateSoundButton(){$('#sound-btn').ariaLabel=save.sound?'关闭音效':'开启音效';$('#sound-btn').title=$('#sound-btn').ariaLabel;$('#sound-btn').innerHTML=save.sound?'<svg viewBox="0 0 24 24"><path d="M11 5 6 9H3v6h3l5 4zM15 8q5 4 0 8m3-11q8 7 0 14"/></svg>':'<svg viewBox="0 0 24 24"><path d="M11 5 6 9H3v6h3l5 4zM16 9l5 6m0-6-5 6"/></svg>'}
$('#sound-btn').onclick=()=>{save.sound=!save.sound;persist();updateSoundButton();tone(600,.12)};updateSoundButton();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-lastTime)/1000,.045);lastTime=now;time+=dt;
 if(!paused&&!won){if(started)elapsed+=dt;hazardCooldown=Math.max(0,hazardCooldown-dt);player.stability=Math.min(100,player.stability+dt*3.5);player.jump=Math.max(0,player.jump-dt);
 let ix=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),iz=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);let moving=ix||iz;
 if(moving){started=true;const len=Math.hypot(ix,iz);ix/=len;iz/=len;const dx=ix*Math.cos(angle)+iz*Math.sin(angle),dz=-ix*Math.sin(angle)+iz*Math.cos(angle);player.dir.set(dx,dz);let speed=FORMS[player.form].speed*(player.carry?.78:1)*(player.jump>0?1.7:1);const nx=player.x+dx*speed*dt,nz=player.z+dz*speed*dt;if(!blocked(nx,player.z))player.x=nx;if(!blocked(player.x,nz))player.z=nz;}
 for(const g of gates){const powered=plates.filter(p=>p.channel===g.channel).every(p=>p.active);g.open=powered||(g.open&&Math.hypot(player.x-g.x,player.z-g.z)<1.1)}
 const here=cell(player.x,player.z);if(here==='F'||here==='T')touchedPassages.add(here);if(here==='~'&&player.form!==1)respawn('咕噜…水上需要扁平形态。按 2 再试试。');
 for(const l of lasers){l.active=!laserDisabled&&(elapsed%4<2.3);if(l.active&&Math.abs(player.x-l.x)<.3&&Math.abs(player.z-l.z)<.7)respawn('等激光变暗再通过，也可以寻找安全开关。')}
 for(const c of crystals){if(!c.collected&&Math.hypot(player.x-c.x,player.z-c.z)<.65){c.collected=true;c.mesh.visible=false;particles(c.x,c.z,0xffd88d,18);tone(620+crystals.filter(c=>c.collected).length*110,.17);lastCheckpoint={x:player.x,z:player.z}}}
 portal.active=crystals.every(c=>c.collected);if(portal.active&&Math.hypot(player.x-portal.x,player.z-portal.z)<.58)win();
 if(!portal.active&&Math.hypot(player.x-portal.x,player.z-portal.z)<.7&&!$('#toast').classList.contains('show'))toast(`还差 ${crystals.filter(c=>!c.collected).length} 枚晶体，传送门才能启动。`);
 if(!moving&&here==='.'&&hazardCooldown===0&&!blocked(player.x,player.z,0)&&!player.carry){lastCheckpoint={x:player.x,z:player.z}}
 const nearCube=cubes.find(c=>Math.hypot(player.x-c.x,player.z-c.z)<1.55);const nearSwitch=switches.find(c=>Math.hypot(player.x-c.x,player.z-c.z)<1.45);const msg=player.carry?'放下能量方块':nearSwitch?'触发高处开关':nearCube?'包裹能量方块':null;$('#interaction').classList.toggle('hidden',!msg);if(msg)$('#interaction span').textContent=msg;
 updateStats();
 }
 const moving=(keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight)&&!paused&&!won;
 const target=FORMS[player.form].scale;const wobble=moving?Math.sin(time*16)*.055:Math.sin(time*2.3)*.018;const carrying=player.carry?1.36:1;
 slime.scale.lerp(new THREE.Vector3(target[0]*(1+wobble)*carrying,target[1]*(1-wobble)*carrying,target[2]*(1+wobble)*carrying),Math.min(1,dt*12));slime.position.y=slime.scale.y+.06;core.visible=!player.carry;
 const jumpHeight=player.jump>0?Math.sin(player.jump/.5*Math.PI)*.55:0;slimeRoot.position.set(player.x,jumpHeight,player.z);slimeRoot.rotation.y=THREE.MathUtils.lerp(slimeRoot.rotation.y,Math.atan2(player.dir.x,player.dir.y),dt*10);
 eyes.position.y=slime.scale.y*.95-.58;eyes.position.z=slime.scale.z-.52;eyes.scale.set(player.form===2?.6:1,player.form===1?.67:1,1);eyes.visible=!(time%5.8>5.65&&time%5.8<5.78);groundRing.position.y=.08-jumpHeight;groundRing.scale.setScalar(player.carry?1.23:1);groundRing.material.opacity=hazardCooldown>0?.8:.26;
 if(player.carry){player.carry.mesh.position.set(player.x,.56+jumpHeight,player.z);player.carry.mesh.rotation.y+=dt*.5}
 for(const c of cubes){if(c!==player.carry)c.mesh.rotation.y=THREE.MathUtils.lerp(c.mesh.rotation.y,0,dt*8)}
 for(const c of crystals){if(!c.collected){c.mesh.position.y=.7+Math.sin(time*2.5+c.offset)*.1;c.mesh.children[0].rotation.y=time*.7}}
 for(const g of gates)g.mesh.position.y=THREE.MathUtils.lerp(g.mesh.position.y,g.open?-1.8:0,dt*5);
 for(const l of lasers){l.mesh.visible=l.active;l.mesh.children.forEach(b=>b.scale.y=.75+Math.sin(time*18)*.2)}
 for(const w of waters){if(w.geometry.type==='TorusGeometry')w.scale.setScalar(1+Math.sin(time*1.5+w.position.x)*.15)}
 portalGlow.material.opacity=portal.active?.3+Math.sin(time*3)*.12:.09;portal.inner.rotation.z=time*(portal.active?1:.2);portal.ring.rotation.z=-time*.15;
 dust.rotation.y=time*.009;
 for(let i=motes.length-1;i>=0;i--){const p=motes[i];p.life-=dt;p.v.y-=dt*4;p.mesh.position.addScaledVector(p.v,dt);p.mesh.material.opacity=p.life;if(p.life<=0){effects.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();motes.splice(i,1)}}
 renderer.render(scene,camera);
}
buildLevel(0);requestAnimationFrame(frame);
// Optional browser agent interface; the game remains fully usable without it.
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const result=()=>({level:levelIndex+1,name:level.name,form:FORMS[player.form].name,crystals:crystals.filter(c=>c.collected).length,total:crystals.length,completed:won,paused});const specs=[{name:'read_slime_experiment',description:'Read the currently visible slime puzzle progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>result()},{name:'select_slime_experiment',description:'Start or restart one of the five slime experiments, matching the level buttons.',inputSchema:{type:'object',properties:{level:{type:'integer',minimum:1,maximum:5}},required:['level'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input.level)||input.level<1||input.level>5)throw Error('Level must be 1 through 5');closeModal();buildLevel(input.level-1);return result()}}];for(const tool of specs){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
