export const ROOMS=[{id:'hub',name:'中央大厅',en:'ASSEMBLY',x:0,z:0,w:11,d:8,color:0x74b9b8},{id:'bridge',name:'驾驶舱',en:'NAVIGATION',x:0,z:-11,w:9,d:7,color:0x76b8d1},{id:'reactor',name:'反应堆',en:'REACTOR',x:-11,z:-8,w:8,d:8,color:0x9accac},{id:'medbay',name:'医疗舱',en:'MEDICAL',x:11,z:-8,w:8,d:8,color:0x8abdd1},{id:'electrical',name:'配电室',en:'ELECTRICAL',x:-11,z:7,w:8,d:7,color:0xd0b883},{id:'comms',name:'通讯室',en:'COMMUNICATIONS',x:0,z:11,w:9,d:7,color:0xa09fd3},{id:'cargo',name:'货运舱',en:'CARGO BAY',x:11,z:7,w:8,d:7,color:0xadbb9a}];
export const TASKS=[{id:'wires',name:'恢复电路连接',room:'electrical',icon:'ϟ',kind:'wires'},{id:'scan',name:'校准生物扫描',room:'medbay',icon:'⊕',kind:'scanner'},{id:'nav',name:'校验航行记录',room:'bridge',icon:'⌁',kind:'memory'},{id:'fuel',name:'稳定反应核心',room:'reactor',icon:'◈',kind:'tuning'},{id:'signal',name:'恢复通讯信号',room:'comms',icon:'⌘',kind:'memory'},{id:'cargo',name:'清点货舱物资',room:'cargo',icon:'▦',kind:'cargo'}];
const NAMES=['你','诺瓦','阿特拉斯','米拉','凯','奥利安','露娜','芬恩'];const COLORS=['#f7ba58','#89b9ef','#dc97b6','#95cbb5','#b19ee0','#e7957b','#d5dae0','#d5c476'];const JOBS=['调查员','领航员','工程师','医疗官','通讯员','维修员','研究员','货运员'];
export const roomById=id=>ROOMS.find(r=>r.id===id);export const fmt=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
const rand=a=>a[Math.floor(Math.random()*a.length)];
export class Game{
 constructor(){this.listeners=new Set();this.reset();}
 reset(difficulty='normal'){this.phase='ready';this.elapsed=0;this.difficulty=difficulty;this.round=1;this.oxygen=100;this.sabotage=null;this.nextSabotage=70;this.nextKill=difficulty==='hard'?70:105;this.nextVent=34;this.tasks=TASKS.map(t=>({...t,done:false}));this.npcTasks=0;this.evidence=[];this.events=[];this.feed=[];this.bodies=[];this.meetingsLeft=2;this.cooldown=0;this.meeting=null;this.result=null;this.suspects=new Set();this.impostor=1+Math.floor(Math.random()*7);this.crew=NAMES.map((name,id)=>({id,name,color:COLORS[id],job:JOBS[id],alive:true,impostor:id===this.impostor,x:(id%4-1.5)*1.35,z:(Math.floor(id/4)-.5)*2,room:'hub',targetRoom:'hub',path:[],history:[{time:0,room:'hub'}],wait:3+id*2,lastTask:0,seen:[],angle:0}));this.addFeed('奥德赛号已抵达开普勒星域');this.emit();}
 on(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}emit(){this.listeners.forEach(fn=>fn(this));}
 start(difficulty){this.reset(difficulty);this.phase='explore';this.addFeed('全体船员开始执行任务');this.addEvidence({id:'brief',title:'登舰简报',text:'生命信号发现一名外星伪装者。任务行为可以伪装，需比对门禁、目击与生物残留。',room:'hub',weight:0});this.emit();}
 addFeed(text){this.feed.unshift({time:this.elapsed,text});this.feed=this.feed.slice(0,18);}
 record(type,actor,room,extra={}){const ev={id:this.events.length,type,actor,room,time:this.elapsed,...extra};this.events.push(ev);return ev;}
 addEvidence(e){if(this.evidence.some(x=>x.id===e.id))return false;this.evidence.unshift({time:this.elapsed,...e});this.emit();return true;}
 enterRoom(c,r){if(c.room===r.id)return;c.room=r.id;c.history.push({room:r.id,time:this.elapsed});this.record('enter',c.id,r.id);if(c.id===0)this.emit();}
 tick(dt){if(this.phase!=='explore')return;this.elapsed+=dt;this.cooldown=Math.max(0,this.cooldown-dt);for(const c of this.crew){if(!c.alive||c.id===0)continue;if(c.path.length)continue;c.wait-=dt;if(c.wait<=0){if(!c.impostor&&c.room!=='hub'&&this.elapsed-c.lastTask>45&&this.npcTasks<4){this.npcTasks++;c.lastTask=this.elapsed;this.record('task',c.id,c.room);this.addFeed(`${c.name} 完成了一项船内维护`);this.emit();}c.targetRoom=rand(ROOMS.filter(r=>r.id!==c.room)).id;c.wait=15+Math.random()*18;}}
 if(this.elapsed>this.nextVent){this.vent();this.nextVent=this.elapsed+65+Math.random()*20;}
 if(!this.sabotage&&this.elapsed>this.nextSabotage)this.triggerSabotage();
 if(this.sabotage){this.oxygen=Math.max(0,this.oxygen-dt*(this.difficulty==='hard'?.8:.58));if(this.oxygen===0)this.finish(false,'供氧系统耗尽，外星伪装者夺取了飞船。');}
 if(this.elapsed>this.nextKill){this.attemptKill();this.nextKill=this.elapsed+(this.difficulty==='hard'?45:65);}
 this.checkWin();}
 vent(){const imp=this.crew[this.impostor];if(!imp.alive)return;const from=imp.room;const r=rand(ROOMS.filter(r=>r.id!=='hub'&&r.id!==from));const witnesses=this.crew.filter(c=>c.alive&&!c.impostor&&c.room===from).map(c=>c.id);this.record('vent',imp.id,from,{to:r.id,witnesses});witnesses.forEach(id=>this.crew[id].seen.push({type:'vent',actor:imp.id,room:from,time:this.elapsed}));imp.x=r.x;imp.z=r.z;imp.room=r.id;imp.targetRoom=r.id;imp.path=[];imp.wait=12;imp.history.push({time:this.elapsed,room:r.id});if(witnesses.includes(0))this.addEvidence({id:`vent-${this.events.length}`,title:'亲眼目击：通风管异常',text:`${fmt(this.elapsed)}，你看到 ${imp.name} 从 ${roomById(from).name} 钻入通风管。普通船员没有管道通行权限。`,room:from,suspect:imp.id,weight:5});this.addFeed('通风系统捕捉到不明压力波动');}
 triggerSabotage(){const imp=this.crew[this.impostor];if(!imp.alive)return;const room=rand(['reactor','electrical']);this.sabotage={room,time:this.elapsed};this.record('sabotage',imp.id,imp.room,{target:room});this.nextSabotage=this.elapsed+110;this.addFeed(`${roomById(room).name} 故障！氧气正在流失`);this.emit();}
 repair(){if(this.phase!=='explore'||!this.sabotage)return false;if(this.crew[0].room!==this.sabotage.room)return false;this.addFeed('紧急故障已排除，供氧系统恢复');const imp=this.crew[this.impostor];this.addEvidence({id:`residue-${this.sabotage.time}`,title:'故障调查：生物残留',text:`破坏接口发现非人类蛋白质，与 ${imp.name} 的手套样本吻合。物证需要与行动记录交叉验证。`,room:this.sabotage.room,suspect:imp.id,weight:3});this.sabotage=null;this.oxygen=100;this.nextSabotage=this.elapsed+100;this.emit();return true;}
 attemptKill(){const imp=this.crew[this.impostor];if(!imp.alive)return;const candidates=this.crew.filter(c=>c.alive&&!c.impostor&&c.id!==0&&c.room===imp.room&&c.room!=='hub');if(!candidates.length){this.nextKill=this.elapsed-45;return;}const victim=rand(candidates);victim.alive=false;victim.path=[];this.bodies.push({id:victim.id,x:victim.x,z:victim.z,room:victim.room,time:this.elapsed,reported:false});const witnesses=this.crew.filter(c=>c.alive&&!c.impostor&&c.room===imp.room).map(c=>c.id);this.record('kill',imp.id,imp.room,{victim:victim.id,witnesses});witnesses.forEach(id=>this.crew[id].seen.push({type:'kill',actor:imp.id,room:imp.room,time:this.elapsed}));if(witnesses.includes(0))this.addEvidence({id:`kill-${victim.id}`,title:'直接目击：袭击事件',text:`你在 ${roomById(imp.room).name} 目击 ${imp.name} 袭击了 ${victim.name}。`,suspect:imp.id,room:imp.room,weight:7});this.addFeed(`${victim.name} 的生命信号丢失`);this.emit();}
 completeTask(id){if(this.phase!=='explore')return false;const t=this.tasks.find(t=>t.id===id);if(!t||t.done||this.crew[0].room!==t.room)return false;t.done=true;this.record('task',0,t.room);this.addFeed(`你完成了 ${t.name}`);if(id==='nav'||id==='signal')this.collectLogs();else if(id==='scan'){this.addEvidence({id:'scan-analysis',title:'扫描结果：异常生物签名',text:`扫描仪检测到 ${this.crew[this.impostor].name} 身上存在异常蛋白质标记。仪器误差仍需其他证据排除。`,suspect:this.impostor,weight:2,room:t.room});}else this.addEvidence({id:`task-${id}`,title:`任务记录：${t.name}`,text:`${fmt(this.elapsed)}，你在 ${roomById(t.room).name} 完成真实维护。系统已记录这份不在场证明。`,room:t.room,weight:0});this.checkWin();this.emit();return true;}
 collectLogs(){const vent=this.events.find(e=>e.type==='vent');if(vent){this.addEvidence({id:'camera-'+vent.id,title:'监控记录：不可能的位移',text:`${fmt(vent.time)}，${this.crew[vent.actor].name} 在同一秒出现在 ${roomById(vent.room).name} 与 ${roomById(vent.to).name}。正常通道无法做到，只有通风管可以。`,suspect:vent.actor,weight:4,room:'bridge',time:vent.time});}else{this.addEvidence({id:'door-early',title:'早期门禁记录',text:'所有人从中央大厅出发。暂未发现异常；完成通讯任务或稍后在驾驶舱再次调取监控可获取新记录。',weight:0,room:'bridge'});}const recent=this.events.filter(e=>e.type==='enter').slice(-5);for(const ev of recent)this.addEvidence({id:'door-'+ev.id,title:'门禁记录',text:`${fmt(ev.time)}，${this.crew[ev.actor].name} 进入了 ${roomById(ev.room).name}。`,room:ev.room,weight:0,time:ev.time});}
 question(id,kind){const c=this.crew[id];if(!c||!c.alive)return '对方已无法回应。';if(kind==='route'){const h=c.history.slice(-3);if(c.impostor&&this.events.some(e=>e.type==='vent')){const lie='我一直在中央大厅检查设备，没有用过通风管。';this.addEvidence({id:`statement-${id}`,title:`${c.name} 的口供`,text:lie+' 可以与门禁或监控记录核对。',room:c.room,weight:0,suspect:id});return lie;}return `最近的路线是：${h.map(e=>`${fmt(e.time)} ${roomById(e.room).name}`).join(' → ')}。你可以核对门禁记录。`;}
 if(kind==='witness'){const saw=c.seen.at(-1);if(saw){this.addEvidence({id:`witness-${id}-${saw.time}`,title:`${c.name} 的目击证词`,text:`${fmt(saw.time)}，${c.name} 在 ${roomById(saw.room).name} 看到 ${this.crew[saw.actor].name} ${saw.type==='vent'?'进入通风管':'袭击了另一位船员'}。`,suspect:saw.actor,weight:saw.type==='kill'?5:3,room:saw.room});return `我确实看到了，${this.crew[saw.actor].name} ${saw.type==='vent'?'从通风管离开了':'袭击了船员'}！时间是 ${fmt(saw.time)}，就在 ${roomById(saw.room).name}。`;}return '我暂时没有看见能确认身份的异常行为。别只凭直觉投票，先找监控或扫描线索。';}
 return c.lastTask?`我在 ${fmt(c.lastTask)} 完成了维护。任务进度会留下系统记录。`:'我正在检查船内设备，还没有完成的任务记录。暂时没完成任务并不代表身份有问题。';}
 beginMeeting(report=false){if(this.phase!=='explore'||(!report&&(this.meetingsLeft<=0||this.cooldown>0)))return false;if(report){const p=this.crew[0];const body=this.bodies.find(b=>!b.reported&&Math.hypot(b.x-p.x,b.z-p.z)<4);if(!body)return false;body.reported=true;this.addEvidence({id:`body-${body.id}`,title:'发现失联船员',text:`${this.crew[body.id].name} 在 ${roomById(body.room).name} 遇袭。最后生命信号时间：${fmt(body.time)}。`,room:body.room,weight:0});}else this.meetingsLeft--;this.phase='meeting';this.meeting={shared:[],messages:[],votes:null};this.crew.filter(c=>c.alive&&c.id!==0).forEach(c=>this.meeting.messages.push({actor:c.id,text:c.seen.length?this.question(c.id,'witness'):c.impostor?'别急着下结论。我们需要可信的线索。':`${roomById(c.room).name} 是我目前的位置。${c.lastTask?'我有已完成的维护记录。':'如果证据不足，我会选择弃票。'}`}));this.emit();return true;}
 shareEvidence(id){if(this.phase!=='meeting')return false;const e=this.evidence.find(e=>e.id===id);if(!e||this.meeting.shared.includes(id))return false;this.meeting.shared.push(id);this.meeting.messages.push({actor:0,text:`【出示证据】${e.title}：${e.text}`});this.emit();return true;}
 vote(target){if(this.phase!=='meeting'||this.meeting.votes)return null;if(target!==null&&!this.crew.some(c=>c.id===target&&c.alive))return null;const votes=[{from:0,to:target}];const alive=this.crew.filter(c=>c.alive);for(const c of alive.filter(c=>c.id!==0)){const scores=new Map();this.evidence.filter(e=>this.meeting.shared.includes(e.id)&&e.suspect!==undefined).forEach(e=>scores.set(e.suspect,(scores.get(e.suspect)||0)+e.weight));c.seen.forEach(e=>scores.set(e.actor,(scores.get(e.actor)||0)+(e.type==='kill'?7:5)));let to=null;if(c.impostor)to=target!==c.id?target:rand(alive.filter(a=>a.id!==c.id)).id;else{const ranked=[...scores].filter(([id])=>id!==c.id&&this.crew[id]?.alive).sort((a,b)=>b[1]-a[1]);if(ranked[0]?.[1]>=3)to=ranked[0][0];}votes.push({from:c.id,to});}const count={skip:0};votes.forEach(v=>{const key=v.to===null?'skip':v.to;count[key]=(count[key]||0)+1;});const ranked=Object.entries(count).sort((a,b)=>b[1]-a[1]);const expelled=ranked[0][0]!=='skip'&&ranked[0][1]>(ranked[1]?.[1]??0)?Number(ranked[0][0]):null;this.meeting.votes={votes,count,expelled};if(expelled!==null){this.crew[expelled].alive=false;this.crew[expelled].path=[];this.record('eject',expelled,'hub');}this.phase='verdict';this.emit();return this.meeting.votes;}
 resumeAfterVote(){if(this.phase!=='verdict')return;this.round++;this.phase='explore';this.cooldown=35;this.crew.forEach(c=>{if(c.alive){c.x=(c.id%4-1.5)*1.35;c.z=(Math.floor(c.id/4)-.5)*2;c.room='hub';c.targetRoom='hub';c.path=[];c.wait=5+c.id;}});if(!this.crew[0].alive)this.finish(false,'你被投出了气闸。外星伪装者仍在船上。');this.checkWin();this.emit();}
 checkWin(){if(this.result)return;if(!this.crew[this.impostor].alive)this.finish(true,'外星伪装者已被驱逐，奥德赛号恢复安全。');else if(this.tasks.filter(t=>t.done).length+this.npcTasks>=10)this.finish(true,'全船维护完成，生命检测系统锁定并隔离了伪装者。');else if(this.crew.filter(c=>c.alive&&!c.impostor).length<=1)this.finish(false,'船员人数不足，外星伪装者控制了飞船。');}
 finish(win,reason){if(this.result)return;this.result={win,reason};this.phase='ended';this.emit();}
}
