import * as THREE from 'three';
const $=s=>document.querySelector(s),canvas=$('#world');
const scene=new THREE.Scene();scene.background=new THREE.Color('#070e18');scene.fog=new THREE.FogExp2('#080f1c',.009);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,240);let azimuth=.69,elevation=.66,distance=64;
const target=new THREE.Vector3(0,0,0),clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0x91cadd,0x17182c,2.4));const key=new THREE.DirectionalLight(0xc3ddeb,3);key.position.set(-8,25,14);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-28,right:28,top:28,bottom:-28});scene.add(key);const rim=new THREE.DirectionalLight(0x67bac9,2);rim.position.set(10,10,-24);scene.add(rim);
const mats={floor:new THREE.MeshStandardMaterial({color:0x283847,roughness:.77,metalness:.7}),wall:new THREE.MeshStandardMaterial({color:0x293746,roughness:.7,metalness:.65}),edge:new THREE.MeshStandardMaterial({color:0x4e6573,metalness:.75,roughness:.45}),dark:new THREE.MeshStandardMaterial({color:0x111c29,metalness:.6,roughness:.6}),white:new THREE.MeshStandardMaterial({color:0xdde8e9,roughness:.56,metalness:.25}),orange:new THREE.MeshStandardMaterial({color:0xc78144,roughness:.56,metalness:.5}),cyan:new THREE.MeshStandardMaterial({color:0x7ff3e0,emissive:0x41e3d6,emissiveIntensity:2}),red:new THREE.MeshStandardMaterial({color:0xff9a60,emissive:0xee5c31,emissiveIntensity:2}),glass:new THREE.MeshStandardMaterial({color:0x112f3c,metalness:.9,roughness:.16}),core:new THREE.MeshStandardMaterial({color:0x99ffe4,emissive:0x48eecb,emissiveIntensity:2.5})};
function box(w,h,d,x,y,z,mat=mats.floor,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cylinder(r,h,x,y,z,mat,parent=scene){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,12),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}
function light(color,intensity,x,y,z,range=10){const l=new THREE.PointLight(color,intensity,range,2);l.position.set(x,y,z);scene.add(l);return l}
function label(text,x,y,z,size=1.4,color='#91c5c9'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.font='500 62px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,81);const m=new THREE.Mesh(new THREE.PlaneGeometry(size*4,size),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),transparent:true,side:THREE.DoubleSide,depthWrite:false}));m.position.set(x,y,z);scene.add(m);return m}
// A cutaway spacecraft: four physical gravity surfaces, with the front wall omitted for visibility.
for(let z=-21;z<=21;z+=3){for(let x=-9;x<=9;x+=3){box(2.91,.28,2.91,x,-5.8,z);if((x+z)%3===0){box(.055,.012,2.5,x-1.2,-5.65,z,mats.edge)}}box(.1,.05,2.8,-10.25,-5.62,z,mats.cyan);box(.1,.05,2.8,10.25,-5.62,z,mats.cyan)}
box(22,.65,45,0,-6.25,0,mats.dark);box(.5,11.5,45,-11,-.3,0,mats.wall);box(.3,1.2,45,11,-5.1,0,mats.wall);box(.3,.3,45,11,5.6,0,mats.edge);box(22,11.5,.6,0,-.3,-22.5,mats.wall);box(22,1.7,.7,0,-5,22.5,mats.wall);
for(let z=-21;z<=21;z+=6){box(.8,12,.7,-10.7,0,z,mats.edge);box(22,.45,.7,0,5.8,z,mats.dark);box(.35,1.5,.7,10.8,5,z,mats.edge);box(.08,7,.12,-10.2,-.1,z,mats.cyan);box(.14,.08,4.7,10.35,5.85,z+2,mats.cyan);box(1.7,.2,.55,-9.4,-4.8,z,mats.dark);for(let k=0;k<3;k++)box(.14,.07,.5,8.8+k*.4,-5.63,z,mats.orange)}
for(let z=-18;z<=18;z+=6){box(.1,3.1,4,-10.69,.3,z,mats.dark);box(.12,.07,3.6,-10.6,-1,z,mats.edge);box(.12,.07,3.6,-10.6,1.6,z,mats.edge);for(let j=0;j<3;j++)box(.14,.15,.6,-10.49,.6-j*.42,z+1,mats.cyan)}
// Structural upper walkways keep the interior readable while providing a ceiling landing surface.
box(2,.25,44,-9.4,5.75,0,mats.wall);box(2,.25,44,9.4,5.75,0,mats.wall);for(let z of [-16,-4,8,20])box(20,.2,2,0,5.75,z,mats.floor);
const obstacles=[];function crate(x,z,w=2,h=2){const b=box(w,h,w,x,-5.6+h/2,z,mats.wall);obstacles.push({x,z,w:w/2,h});box(w+.06,.12,w+.06,x,-5.6+h-.22,z,mats.edge);box(w+.06,.14,w+.06,x,-5.6+.18,z,mats.dark);box(.38,h,.035,x-.5,-5.6+h/2,z+w/2+.02,mats.orange);box(.38,h,.035,x+.5,-5.6+h/2,z+w/2+.02,mats.orange);box(w*.45,h*.3,.04,x,-5.6+h/2,z+w/2+.05,mats.dark);return b}
crate(-6,15,2.4,2.1);crate(-3.5,15,2,1.8);crate(-6,12,2,1.6);crate(5,5,2.6,2.7);crate(7.5,5,1.8,1.6);crate(-6,-7,2.3,2.2);crate(-6,-10,1.8,1.5);crate(5,-16,2.5,2);
const escape=new THREE.Group();scene.add(escape);escape.position.set(0,-3.15,-21.8);box(5.2,5.5,.8,0,0,0,mats.dark,escape);box(4,4.4,1,0,-.2,.15,mats.wall,escape);box(.13,4.7,.2,-2.22,0,.7,mats.cyan,escape);box(.13,4.7,.2,2.22,0,.7,mats.cyan,escape);box(4.5,.12,.2,0,2.35,.7,mats.cyan,escape);box(.06,3.8,.04,0,-.2,.68,mats.edge,escape);box(.7,.4,.06,.7,-.2,.7,mats.orange,escape);label('ESCAPE POD',0,.5,-21.3,.68);label('07',6.9,1.5,-22.1,1.5,'#4d697a');
// Conduits, tanks, maintenance terminals and exposed cables.
for(let z of [-16,-10,2,14]){const p=cylinder(.24,10,-10,4.7,z,mats.edge);p.rotation.x=Math.PI/2;}for(let i=0;i<3;i++){cylinder(.6,2.5,-8+i*1.4,-4.3,-18,mats.edge);cylinder(.65,.2,-8+i*1.4,-3.4,-18,mats.dark)}
const terminal=box(1.7,1.1,1,-8,-3.7,3,mats.dark);const screen=box(1.3,.64,.04,-8,-3.52,3.52,mats.cyan);screen.rotation.x=-.15;box(.6,1.8,.6,-8,-4.7,3,mats.edge);
const hazardZ=[8,-2,-12];const hazards=[];hazardZ.forEach((z,i)=>{box(17,.08,.8,0,-5.59,z,mats.dark);for(let x=-8;x<=8;x+=.8){const stripe=box(.35,.035,.8,x,-5.52,z,mats.orange);stripe.rotation.y=-.5}const beam=box(18,.16,.14,0,-3.9,z,mats.red);const beam2=box(18,.1,.12,0,-2.4,z,mats.red);hazards.push({beam,beam2,z,active:true});box(.6,3,.6,-9,-4.2,z,mats.dark);box(.6,3,.6,9,-4.2,z,mats.dark);light(0xff6d36,12,1,-3,z,9)});
const breach=new THREE.Group();breach.position.set(10,-4.8,-6);scene.add(breach);for(let i=0;i<9;i++){const b=box(.5+Math.random(),.4,1.7,Math.random()*2,Math.random()*2,Math.random()*5-2,mats.edge,breach);b.rotation.set(Math.random(),Math.random(),Math.random())}light(0xe95b39,35,10,-1,-6,17);
const starGeo=new THREE.BufferGeometry();const starPositions=[];for(let i=0;i<1800;i++){const v=new THREE.Vector3((Math.random()-.5)*190,(Math.random()-.5)*170,(Math.random()-.5)*190);if(v.length()<45)v.setLength(70);starPositions.push(v.x,v.y,v.z)}starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xc0dfef,size:.11,transparent:true,opacity:.65})));
const planet=new THREE.Mesh(new THREE.SphereGeometry(24,48,32),new THREE.MeshStandardMaterial({color:0x173c51,roughness:1}));planet.position.set(-40,-32,-74);scene.add(planet);const ring=new THREE.Mesh(new THREE.RingGeometry(29,35,100),new THREE.MeshBasicMaterial({color:0x4e7384,side:THREE.DoubleSide,transparent:true,opacity:.14}));ring.position.copy(planet.position);ring.rotation.set(1.2,.2,.2);scene.add(ring);
const debris=[];for(let i=0;i<28;i++){const d=box(.15+Math.random()*.5,.1+Math.random()*.3,.3+Math.random()*.5,(Math.random()-.5)*18,-3+Math.random()*7,(Math.random()-.5)*40,i%5===0?mats.orange:mats.edge);d.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);debris.push(d)}
const cores=[];[[2,-4.2,13],[9.2,.2,-3],[-3,4.7,-15]].forEach((p,i)=>{const g=new THREE.Group();g.position.set(...p);const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.65,0),mats.core);g.add(mesh);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.045,8,48),mats.cyan);ring.rotation.x=Math.PI/2;g.add(ring);scene.add(g);const l=light(0x5ff5c7,10,...p,7);cores.push({g,mesh,ring,l,p:new THREE.Vector3(...p),collected:false});label('0'+(i+1),p[0],p[1]+1.5,p[2],.35,'#99eedb')});
const pickups=[];[[-7,-4.7,7],[7,-4.7,-10],[-7,4.5,-1]].forEach(p=>{const g=new THREE.Group();g.position.set(...p);cylinder(.28,.9,0,0,0,mats.white,g);box(.16,.4,.04,0,0,.29,mats.cyan,g);scene.add(g);pickups.push({g,used:false})});
const astronaut=new THREE.Group();scene.add(astronaut);const body=new THREE.Group();astronaut.add(body);box(.86,1.02,.58,0,.1,0,mats.white,body);box(.65,.7,.45,0,.2,-.48,mats.dark,body);box(.13,.65,.06,-.29,.16,.31,mats.orange,body);box(.44,.35,.08,.08,.24,.34,mats.dark,body);box(.16,.05,.02,.08,.28,.395,mats.cyan,body);const helmet=new THREE.Mesh(new THREE.SphereGeometry(.54,24,18),mats.white);helmet.position.y=1;body.add(helmet);const visor=new THREE.Mesh(new THREE.SphereGeometry(.48,24,16,0,Math.PI*2,Math.PI*.22,Math.PI*.55),mats.glass);visor.rotation.x=Math.PI/2;visor.position.set(0,1,.07);body.add(visor);box(.4,.055,.08,0,1.38,.38,mats.cyan,body);const legs=[],arms=[];for(let s of [-1,1]){const leg=box(.32,.7,.36,s*.24,-.73,0,mats.white,body);legs.push(leg);box(.34,.21,.5,s*.24,-1.12,.07,mats.dark,body);const arm=box(.28,.86,.32,s*.6,.13,0,mats.white,body);arm.rotation.z=s*.16;arms.push(arm);box(.3,.19,.34,s*.6,-.26,0,mats.orange,body)}const jet=new THREE.Mesh(new THREE.ConeGeometry(.25,1.3,12),mats.cyan);jet.position.set(0,-.2,-.8);jet.rotation.x=-Math.PI/2;body.add(jet);jet.visible=false;
const groundRing=new THREE.Mesh(new THREE.RingGeometry(.85,1,40),new THREE.MeshBasicMaterial({color:0x93f4d3,side:THREE.DoubleSide,transparent:true,opacity:.6}));groundRing.rotation.x=-Math.PI/2;scene.add(groundRing);
let state='ready',gravity=0,oxygen=100,health=100,elapsed=0,collected=0,boost=100,invuln=0,scanTime=0,soundEnabled=true,audioCtx,toastTimer,near=null;
const pos=new THREE.Vector3(0,-4.35,18),vel=new THREE.Vector3(),gravs=[new THREE.Vector3(0,-1,0),new THREE.Vector3(1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(-1,0,0)],keys={};astronaut.position.copy(pos);
function beep(freq=440,duration=.1,type='sine',volume=.045){if(!soundEnabled)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type=type;o.frequency.value=freq;gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3300)}
function setGravity(g){if(state!=='playing')return;gravity=(g+4)%4;vel.multiplyScalar(.25);$('#g-arrow').textContent=['↓','→','↑','←'][gravity];$('#g-name').textContent=['甲板方向','右侧舱壁','天花板方向','左侧舱壁'][gravity];document.querySelectorAll('[data-g]').forEach(b=>b.classList.toggle('active',+b.dataset.g===gravity));beep(180+gravity*90,.25,'triangle');toast('重力已切换 · '+$('#g-name').textContent)}
function reset(){oxygen=100;health=100;elapsed=0;collected=0;gravity=0;boost=100;invuln=0;pos.set(0,-4.35,18);vel.set(0,0,0);cores.forEach(c=>{c.collected=false;c.g.visible=true;c.l.visible=true});pickups.forEach(p=>{p.used=false;p.g.visible=true});document.querySelectorAll('[data-core]').forEach(e=>{e.classList.remove('done');e.querySelector('i').textContent='◇'});$('#mission-title').textContent='重新点亮归途';$('#mission-desc').textContent='回收 3 枚能源核心，恢复逃生舱供电。';$('#power').textContent='0%';$('#power-fill').style.width='0%';$('#start-screen').classList.add('hidden');$('#overlay').classList.add('hidden');state='playing';setGravity(0);$('#radio-text').textContent='“W / S 沿船舱前后移动，A / D 沿当前重力平面横移。先找到甲板核心。”';beep(650,.2)}
function openDialog(type){const was=state;state=type==='help'&&was==='ready'?'ready-help':type;$('#overlay').classList.remove('hidden');$('#resume').classList.remove('hidden');$('#dialog-label').textContent='GRAVITY PROTOCOL';if(type==='help'){$('#dialog-title').textContent='宇航员行动手册';$('#dialog-content').innerHTML='<p><b>W / S</b> 沿船舱前后移动，<b>A / D</b> 沿当前落脚面横移。<br><b>Q / E</b> 将重力旋转 90°，可登上天花板和舱壁。<br><b>空格</b> 推进器短暂抵抗重力（能量自动恢复）。<br><b>F</b> 拾取附近核心、氧气罐或启动逃生舱。<br><b>R</b> 扫描并显示最近核心位置。<br>电弧周期性关闭，可观察后通过，或切换到天花板避开。橙色破口会损伤宇航服。<br>收集 3 枚核心后，回到甲板并抵达船舱尽头的逃生门。拖动鼠标旋转视角，滚轮缩放。<br><b>Esc</b> 暂停 · 点击重力罗盘也能切换方向。</p>';$('#resume').textContent='明白了 →'}else{$('#dialog-title').textContent='任务暂停';$('#dialog-content').innerHTML='<p>呼吸，调整方向。飞船可以再等一会儿。</p>';$('#resume').textContent='继续任务 →'}}
function finish(won){state=won?'won':'lost';$('#overlay').classList.remove('hidden');$('#resume').classList.add('hidden');$('#dialog-label').textContent=won?'SIGNAL FOUND / 已脱离危险':'SIGNAL LOST / 信号中断';$('#dialog-title').textContent=won?'欢迎回家，宇航员。':'你的信号消失在星海。';$('#dialog-content').innerHTML=won?`<p>逃生舱成功发射。ECHO 已将求救信号发送至最近的空间站。</p><p>任务用时 <b>${formatTime(elapsed)}</b> · 剩余氧气 <b>${Math.ceil(oxygen)}%</b><br>回收核心 <b>3 / 3</b> · 宇航服完整度 <b>${Math.ceil(health)}%</b></p>`:`<p>${oxygen<=0?'氧气已经耗尽。注意回收沿途的白色氧气罐。':'宇航服严重损坏。利用天花板绕开电弧与船体破口。'}<br>已回收核心 ${collected} / 3 · 生存时间 ${formatTime(elapsed)}</p>`;$('#restart').textContent='重新执行任务 ↻';beep(won?880:120,.7,'triangle')}
function formatTime(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0')}
function interact(){if(state!=='playing'||!near)return;beep(780,.2);if(near.type==='core'){const c=cores[near.index];c.collected=true;c.g.visible=false;c.l.visible=false;collected++;const e=$(`[data-core="${near.index}"]`);e.classList.add('done');e.querySelector('i').textContent='✓';$('#power').textContent=Math.round(collected/3*100)+'%';$('#power-fill').style.width=(collected/3*100)+'%';toast('能源核心已回收 · '+collected+' / 3');oxygen=Math.min(100,oxygen+8);if(collected===3){$('#mission-title').textContent='最后一步：回家';$('#mission-desc').textContent='回到甲板，前往船舱尽头的逃生舱。';$('#radio-text').textContent='“供电恢复！逃生舱已经就绪。我在门口等你。”';toast('逃生舱已解锁 · 回到甲板前往蓝色舱门')}else $('#radio-text').textContent=collected===1?'“做得好。右侧舱壁上还有一枚，尝试 E 改变重力。”':'“最后一枚在天花板。继续改变重力，抬头看看。”'}else if(near.type==='oxygen'){pickups[near.index].used=true;pickups[near.index].g.visible=false;oxygen=Math.min(100,oxygen+32);health=Math.min(100,health+12);toast('补给已回收 · 氧气 +32% · 完整度 +12%')}else if(near.type==='exit'){if(collected===3)finish(true);else toast('逃生舱供电不足 · 还需要 '+(3-collected)+' 枚核心')}}
$('#start').onclick=reset;$('#restart').onclick=reset;$('#help').onclick=()=>openDialog('help');$('#pause').onclick=()=>{if(state==='playing')openDialog('paused');else if(state==='paused')resume()};function resume(){$('#overlay').classList.add('hidden');if(state==='ready-help'){state='ready';return}if(state==='paused'||state==='help')state='playing'}$('#resume').onclick=resume;$('#sound').onclick=()=>{soundEnabled=!soundEnabled;$('#sound').textContent=soundEnabled?'♫':'♩';$('#sound').style.opacity=soundEnabled?1:.4;beep()};document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>setGravity(+b.dataset.g));
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'){if(state==='playing')openDialog('paused');else resume()}if(state!=='playing')return;if(e.code==='KeyQ')setGravity(gravity-1);if(e.code==='KeyE')setGravity(gravity+1);if(e.code==='KeyF')interact();if(e.code==='KeyR'){scanTime=5;const c=cores.filter(c=>!c.collected).sort((a,b)=>a.p.distanceTo(pos)-b.p.distanceTo(pos))[0];toast(c?'扫描完成 · 最近核心 '+Math.round(c.p.distanceTo(pos))+' m · '+['甲板','右壁','天花板'][cores.indexOf(c)]:'所有核心已回收 · 前往船舱尽头逃生舱');beep(1000,.3)}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(state==='playing')openDialog('paused')});
let dragging=false,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{dragging=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;azimuth-=(e.clientX-lx)*.004;elevation=THREE.MathUtils.clamp(elevation+(e.clientY-ly)*.003,.24,1.3);lx=e.clientX;ly=e.clientY});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.035,34,85)},{passive:false});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function damage(amount){if(invuln>0)return;health=Math.max(0,health-amount);oxygen=Math.max(0,oxygen-3);invuln=1.6;beep(95,.25,'sawtooth');toast('宇航服受损 · 远离电弧和破口');$('#radio-text').textContent='“警告：检测到损伤。换一个重力方向绕过去。”'}
function physics(dt,t){elapsed+=dt;oxygen=Math.max(0,oxygen-dt*.24);invuln=Math.max(0,invuln-dt);scanTime=Math.max(0,scanTime-dt);const g=gravs[gravity],tangent=new THREE.Vector3(-g.y,g.x,0);const inputX=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),inputZ=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);const thrust=keys.Space&&boost>1;const speed=keys.ShiftLeft?7.5:5.4;const tangentSpeed=vel.dot(tangent);vel.addScaledVector(tangent,(inputX*speed-tangentSpeed)*Math.min(1,dt*9));vel.z=THREE.MathUtils.lerp(vel.z,inputZ*speed,Math.min(1,dt*9));vel.addScaledVector(g,(thrust?-13:12)*dt);if(thrust){boost=Math.max(0,boost-dt*31);oxygen=Math.max(0,oxygen-dt*.16)}else boost=Math.min(100,boost+dt*18);jet.visible=thrust;jet.scale.setScalar(.8+Math.sin(t*40)*.2);pos.addScaledVector(vel,dt);const bounds={x:9.55,y:4.35,z:20.6};for(let axis of ['x','y','z']){if(Math.abs(pos[axis])>bounds[axis]){pos[axis]=Math.sign(pos[axis])*bounds[axis];vel[axis]=0}}for(const ob of obstacles){if(Math.abs(pos.x-ob.x)<ob.w+.45&&Math.abs(pos.z-ob.z)<ob.w+.45&&pos.y<-5.6+ob.h+1.2){const top=-5.6+ob.h+1.2;if(gravity===0&&pos.y>top-.5){pos.y=top;vel.y=Math.max(0,vel.y)}else{const dx=pos.x-ob.x,dz=pos.z-ob.z;if(Math.abs(dx)>Math.abs(dz)){pos.x=ob.x+Math.sign(dx||1)*(ob.w+.46);vel.x=0}else{pos.z=ob.z+Math.sign(dz||1)*(ob.w+.46);vel.z=0}}}}
for(const h of hazards)if(h.active&&Math.abs(pos.z-h.z)<.5&&pos.y<-1.8&&Math.abs(pos.x)<9)damage(18);if(pos.x>8.3&&pos.z>-9&&pos.z<-3&&pos.y<1.5)damage(12);astronaut.position.copy(pos);const desired=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),g.clone().negate());astronaut.quaternion.slerp(desired,Math.min(1,dt*6));const moving=Math.abs(inputX)+Math.abs(inputZ)>0;legs.forEach((l,i)=>l.rotation.x=moving?Math.sin(t*10+i*Math.PI)*.32:0);arms.forEach((a,i)=>a.rotation.x=moving?Math.sin(t*10+i*Math.PI)*.2:0);astronaut.visible=invuln===0||Math.sin(t*30)>-.3;groundRing.position.set(pos.x,-5.62,pos.z);groundRing.visible=gravity===0;near=null;cores.forEach((c,i)=>{if(!c.collected&&c.p.distanceTo(pos)<2.6)near={type:'core',index:i}});pickups.forEach((p,i)=>{if(!p.used&&p.g.position.distanceTo(pos)<2.4)near={type:'oxygen',index:i}});if(pos.distanceTo(new THREE.Vector3(0,-4.35,-20.6))<3)near={type:'exit'};$('#interaction').style.display=near?'block':'none';if(near)$('#interaction').innerHTML='<kbd>F</kbd> '+(near.type==='core'?'回收能源核心':near.type==='oxygen'?'获取氧气与维修补给':collected===3?'启动逃生舱':'检查逃生舱 · 供电不足');$('#oxygen').innerHTML=Math.ceil(oxygen)+'<small>%</small>';$('#oxygen-fill').style.width=oxygen+'%';$('#oxygen-fill').style.background=oxygen<25?'#ef9767':'#76decb';$('#health').textContent=Math.ceil(health)+'%';$('#health-fill').style.width=health+'%';$('#elapsed').textContent=formatTime(elapsed);$('#game-status').textContent=thrust?'推进器 '+Math.ceil(boost)+'%':scanTime>0?'扫描中 · 能源信号已标记':collected===3?'逃生舱就绪 · 前往船舱尽头':'重力驱动在线 · 核心 '+collected+' / 3';if(oxygen<=0||health<=0)finish(false)}
let total=0;function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);total+=dt;const active=state==='playing'||state==='ready';if(active){cores.forEach((c,i)=>{c.mesh.rotation.y+=dt*.8;c.mesh.position.y=Math.sin(total*1.7+i)*.16;c.ring.rotation.z=total*.4;c.ring.scale.setScalar(scanTime>0?1.4+Math.sin(total*5)*.2:1)});debris.forEach((d,i)=>{d.rotation.y+=dt*.12;d.position.y+=Math.sin(total*.5+i)*dt*.06});hazards.forEach((h,i)=>{h.active=Math.sin(total*1.15+i*1.9)>.05;h.beam.visible=h.active;h.beam2.visible=h.active;h.beam.material.emissiveIntensity=1.6+Math.sin(total*28)*.4});if(state==='playing')physics(dt,total);else astronaut.position.y=-4.3+Math.sin(total)*.04}camera.position.set(Math.sin(azimuth)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(azimuth)*Math.cos(elevation)*distance);camera.lookAt(target);renderer.render(scene,camera)}animate();
// Read-only snapshot for browser diagnostics and automated smoke checks.
window.gravityGame={getState:()=>({state,gravity,oxygen,health,collected,elapsed,position:pos.toArray(),boost,near}),scene,renderer};
