import {Game,SPELLS,STAGES,RELICS,distance} from './engine.js';
import {BoardScene} from './scene.js';
const $=s=>document.querySelector(s);
const paths={spark:'M12 2l2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4L12 2z',diamond:'M12 2l9 10-9 10L3 12 12 2z M3 12h18 M12 2l-4 10 4 10 4-10-4-10',steps:'M8 3c-3 0-3 4-3 6s2 3 4 2 1-3 1-5-1-3-2-3z M6 14l3 1-1 4-3-1 1-4z M17 7c-2 0-3 3-3 5s2 4 4 3 2-3 1-5-1-3-2-3z M15 18h3v4h-3z',flame:'M13 2c1 5-5 6-3 10 1-2 3-3 5-4 0 4 5 5 5 9a8 8 0 01-16 0c0-5 5-7 5-12 2 2 2 4 4-3z',snow:'M12 2v20 M3.3 7l17.4 10 M3.3 17L20.7 7 M8 4l4 3 4-3 M8 20l4-3 4 3 M3 11l4-1-1-4 M21 13l-4 1 1 4 M6 18l1-4-4-1 M18 6l-1 4 4 1',portal:'M12 2c-5 0-8 5-8 10s3 10 8 10 8-5 8-10-3-10-8-10z M12 6c-3 0-4 3-4 6s1 6 4 6 4-3 4-6-1-6-4-6z M2 5l3 1 M19 18l3 1',shield:'M12 2l8 4v6c0 6-8 10-8 10S4 18 4 12V6l8-4z M8 12l3 3 5-6',moon:'M20 15A9 9 0 019 3a9 9 0 1011 12z M17 2v6 M14 5h6',map:'M3 5l6-3 6 3 6-3v17l-6 3-6-3-6 3V5z M9 2v17 M15 5v17',book:'M12 6c-3-3-7-3-10-2v16c4-1 7-1 10 2 3-3 6-3 10-2V4c-3-1-7-1-10 2z M12 6v16 M5 8l4 1 M15 9l4-1',muted:'M11 4L6 8H2v8h4l5 4V4z M17 9l5 6 M22 9l-5 6',sound:'M11 4L6 8H2v8h4l5 4V4z M15 8c3 2 3 6 0 8 M18 4c6 4 6 12 0 16',help:'M12 22a10 10 0 110-20 10 10 0 010 20z M9 8a3 3 0 016 0c0 3-3 2-3 5 M12 17v.1',settings:'M12 8a4 4 0 100 8 4 4 0 000-8z M9 2h6l1 3 3 1 3 3v6l-3 3-3 1-1 3H9l-1-3-3-1-3-3V9l3-3 3-1 1-3z',rotateLeft:'M4 10a8 8 0 111 8 M4 4v6h6',rotateRight:'M20 10a8 8 0 10-1 8 M20 4v6h-6',focus:'M3 8V3h5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M8 12h8 M12 8v8',grid:'M3 3h18v18H3z M3 9h18 M3 15h18 M9 3v18 M15 3v18',hat:'M5 17l7-15 6 15 M3 18c0-2 18-2 18 0s-18 5-18 0z M8 11l8 2 M12 7h.1',sword:'M5 3l4 1 9 12-3 3L3 7V3h2z M13 20l7-7 M17 19l4 3 M19 17l3 4',crown:'M3 7l5 5 4-9 4 9 5-5-2 13H5L3 7z M5 16h14',feather:'M20 2C10 2 4 7 7 16c8 2 14-4 13-14z M3 22L17 7 M7 16h6 M10 12h6',check:'M5 12l4 4L20 5',close:'M5 5l14 14 M19 5L5 19',hourglass:'M6 2h12 M6 22h12 M7 2v5l5 5-5 5v5 M17 2v5l-5 5 5 5v5',heart:'M12 21L3 12C-3 4 8-1 12 6c4-7 15-2 9 6l-9 9z'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
function icons(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
icons();
let game,scene,selected='move',currentModal=null,previousFocus=null,turnToken=0,soundOn=false,audioContext=null,toastTimer;
try{const saved=localStorage.getItem('astral-gambit-v1');game=saved?Game.restore(JSON.parse(saved)):new Game()}catch{game=new Game()}
function save(){if(game.phase==='enemy')return;try{localStorage.setItem('astral-gambit-v1',JSON.stringify(game.export()));$('#save-label').textContent='进度自动保存在此设备'}catch{$('#save-label').textContent='浏览器未允许保存进度'}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function sound(kind='spell'){if(!soundOn)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const tones=kind==='victory'?[440,554,659,880]:kind==='hurt'?[180,130]:kind==='move'?[300,400]:[520,780];tones.forEach((frequency,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+i*.09;osc.type=kind==='hurt'?'triangle':'sine';osc.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.06,t+.015);gain.gain.exponentialRampToValueAtTime(.001,t+.3);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.32)})}catch{}}
function renderSpells(){const bar=$('#spell-bar');bar.innerHTML=SPELLS.map(s=>{const unavailable=game.available(s.id);return `<button class="spell-button ${selected===s.id?'selected':''}" data-spell="${s.id}" style="--spell-color:${s.color}" ${unavailable?'disabled':''} aria-label="${s.name}，消耗 ${s.ap} 行动点，${game.cost(s)} 法力" aria-pressed="${selected===s.id}"><span class="spell-key">${s.key}</span><span class="spell-icon">${icon(s.icon)}</span><span class="spell-name">${s.name}</span><span class="spell-cost">${'◆'.repeat(s.ap)}<i>${game.cost(s)?'✦ '+game.cost(s):s.id==='meditate'?'✦ +4':'✦ 0'}</i></span><span class="spell-tip"><b>${s.name}</b>${s.desc}<br>消耗 ${s.ap} 行动点 · ${game.cost(s)} 法力</span></button>`}).join('');bar.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(b.dataset.spell)))}
function render(){const stage=STAGES[game.stage],h=game.hero;$('#chapter-num').textContent=String(game.stage+1).padStart(2,'0');$('#chapter-name').textContent=stage.name;$('#chapter-subtitle').textContent=stage.subtitle;$('#objective-text').textContent=stage.objective;$('#round-num').textContent=String(game.round).padStart(2,'0');$('#phase-label').textContent=game.phase==='enemy'?'敌方回合':game.phase==='player'?'你的回合':game.phase==='lost'?'冒险结束':'秘境已净化';$('#hp-text').innerHTML=`${h.hp} <em>/ ${h.maxHp}</em>`;$('#mana-text').innerHTML=`${h.mana} <em>/ ${h.maxMana}</em>`;$('#hp-fill').style.width=`${h.hp/h.maxHp*100}%`;$('#mana-fill').style.width=`${h.mana/h.maxMana*100}%`;$('#shield-text').textContent=h.shield;$('#gold-text').textContent=game.gold;$('#hero-level').textContent='LV. '+(game.stage+1);$('#ap-dots').innerHTML=Array.from({length:h.maxAp},(_,i)=>`<i class="${i<h.ap?'':'empty'}"></i>`).join('');$('#ap-dots').setAttribute('aria-label',`剩余 ${h.ap} 个行动点`);$('#enemy-count').textContent=game.enemies.length;$('#enemy-progress').textContent=`${stage.enemies.length-game.enemies.length} / ${stage.enemies.length}`;$('#relic-count').textContent=game.relics.length;
 $('#enemy-list').innerHTML=game.enemies.map(e=>`<button class="enemy-row" data-enemy="${e.id}" style="--enemy-color:${e.color}" aria-label="${e.name}，${e.hp} 生命"><span class="enemy-icon">${icon(e.icon)}</span><span class="enemy-info"><b>${e.name}</b><small>${e.frozen?'❄ 冻结 · 跳过行动':e.type==='boss'?'首领 · 每三回合蓄力':e.range>1?'远程 · 射程 '+e.range:'近战 · 移动 '+e.speed}</small></span><span class="enemy-hp">${e.hp} / ${e.maxHp}<span class="mini-bar"><div style="width:${e.hp/e.maxHp*100}%"></div></span></span></button>`).join('')||'<p style="font-size:12px;color:#9bd5bb;padding:10px 0">星光重归这片土地。</p>';$('#enemy-list').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const e=game.enemies.find(e=>e.id===b.dataset.enemy);scene?.focus(e.x,e.y);if(['bolt','ice','fire'].includes(selected))perform(selected,e.x,e.y);else toast(`${e.name} · 生命 ${e.hp} · 攻击 ${e.damage} · 射程 ${e.range}`)}));
 $('#journal').innerHTML=game.log.slice(0,12).map(l=>`<div class="journal-entry ${l.type}"><span class="log-time">${String(l.round).padStart(2,'0')}</span><span>${l.text}</span></div>`).join('');$('#action-title').textContent=game.phase==='enemy'?'暗影行动中':h.ap===0?'行动已用尽':'轮到你了';const s=SPELLS.find(s=>s.id===selected);$('#action-instruction').textContent=game.phase==='enemy'?'观察敌人的位置，准备下一步':h.ap===0?'结束回合，恢复行动点和法力':s?`${s.name} · ${s.range?'点击高亮目标':'点击技能立即使用'}`:'选择行动，再点击棋盘目标';$('#end-turn').disabled=game.phase==='enemy';$('#end-turn>span:first-child').textContent=game.phase==='enemy'?'敌方行动中':game.phase==='reward'?'选择遗物':['won','lost'].includes(game.phase)?'查看结局':'结束回合';renderSpells();scene?.sync(game);save();if(['reward','won','lost'].includes(game.phase)&&currentModal!==game.phase)openModal(game.phase)}
function select(id){if(game.available(id)){toast(game.available(id));return}selected=id;const s=SPELLS.find(s=>s.id===id);if(!s.range){perform(id,game.hero.x,game.hero.y);return}renderSpells();scene?.select(id);$('#action-instruction').textContent=`${s.name} · 点击高亮目标`;if(id!=='move')toast(s.id==='fire'?'陨火术：选择格子，攻击十字范围':'已选择'+s.name+'，点击高亮目标')}
function perform(id,x,y){if(currentModal)return {ok:false,error:'请先关闭弹窗'};const result=game.act(id,x,y);if(!result.ok){toast(result.error);return result}scene?.play(result.events);sound(id==='move'?'move':'spell');if(game.available(id)&&game.phase==='player')selected=game.hero.ap>0?'bolt':'move';render();if(game.hero.ap===0&&game.phase==='player')toast('本回合行动点已用尽，点击「结束回合」');return result}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function endTurn(){if(currentModal)return;if(game.phase==='reward'||game.phase==='lost'||game.phase==='won'){openModal(game.phase);return}if(game.phase!=='player')return;const token=++turnToken;game.beginEnemy();scene?.play(game.events);render();const ids=game.enemies.map(e=>e.id);for(const id of ids){await pause(440);if(token!==turnToken||game.phase!=='enemy')return;game.enemyTurn(id);scene?.sync(game);scene?.play(game.events);if(game.events.some(e=>e.type==='hurt'))sound('hurt');render()}await pause(360);if(token!==turnToken)return;game.finishEnemy();selected='move';render();if(game.phase==='player')toast(`第 ${game.round} 回合 · 行动点恢复，法力回复`)}
function tileHover(t,event){const tooltip=$('#tile-tooltip');if(!t||!event){tooltip.hidden=true;return}const tile=game.tile(t.x,t.y),e=game.enemy(t.x,t.y),hero=game.hero.x===t.x&&game.hero.y===t.y;const name=e?e.name:hero?'星行者':({ground:'苔纹石板',rock:'古树 / 遗迹',rift:'不稳定星隙',spring:'月辉之泉',chest:'星尘宝箱',portal:'远行星门'}[tile.type]);const desc=e?`${e.hp} 生命 · 攻击 ${e.damage} · 射程 ${e.range}`:hero?'你的巫师 · 选择法术开始行动':({ground:'可行走的地面',rock:'不可通行，阻挡法术视线',rift:'在此结束回合受到 2 点伤害',spring:tile.used?'泉水已经枯竭':'踏入回复 5 法力、3 生命',chest:tile.used?'宝箱已开启':'踏入获得 30 星尘、4 生命',portal:'击败所有敌人后，通往下一幕'}[tile.type]);const rect=$('.battle-area').getBoundingClientRect();tooltip.innerHTML=`<strong>${String.fromCharCode(65+t.x)}${8-t.y} · ${name}</strong><small>${desc}</small>`;tooltip.style.left=Math.min(event.clientX-rect.left+16,rect.width-207)+'px';tooltip.style.top=Math.min(event.clientY-rect.top+12,rect.height-92)+'px';tooltip.hidden=false}
try{scene=new BoardScene($('#scene'),{click:t=>{if(!selected){toast('先选择一种行动');return}perform(selected,t.x,t.y)},hover:tileHover});scene.rebuild(game)}catch(err){$('#scene').innerHTML='<div class="board-fallback"><h2>无法启动 3D 棋盘</h2><p>此浏览器尚未启用 WebGL。请在支持 3D 加速的现代浏览器中打开游戏。</p></div>';console.error(err)}
function modalHeader(eyebrow,title,subtitle){return `<div class="eyebrow">${eyebrow}</div><h2 id="modal-title">${title}</h2><p class="modal-subtitle">${subtitle}</p>`}
function openModal(type){if(!currentModal)previousFocus=document.activeElement;currentModal=type;const c=$('#modal-content');$('#modal-backdrop').hidden=false;$('#close-modal').hidden=['reward','won','lost'].includes(type);if(type==='help'){c.innerHTML=modalHeader('THE FIELD GUIDE','每一步，都有魔法','带领星行者穿过三座棋盘秘境。击败所有守卫，就能获得遗物并进入下一幕。')+`<div class="help-grid"><div class="help-item">${icon('steps')}<b>移动与行动点</b><p>每回合有 3 点行动力。行走消耗 1 点，最多移动 3 格。先选「行走」，再点击高亮地面。</p></div><div class="help-item">${icon('spark')}<b>自由组合你的法术</b><p>奥术飞弹不耗法力；陨火术命中十字范围；霜缚让普通敌人跳过行动；闪现能越过障碍。</p></div><div class="help-item">${icon('moon')}<b>让每个回合更从容</b><p>结束回合回复 2 法力、恢复全部行动点。冥想额外回复 4 法力，每回合一次。护盾会持续吸收伤害。</p></div><div class="help-item">${icon('map')}<b>读懂棋盘上的秘密</b><p>宝箱与月泉在踏入时自动触发。红色星隙在回合结束时造成 2 伤害。首领蓄力时，及时避开红色预警格。</p></div></div><div class="tutorial-note">试试第一步：行走到月泉补给，随后用奥术飞弹攻击靠近的骸骨卫士。按 1–7 选择行动，空格结束回合，Q / E 旋转棋盘。</div><div class="modal-actions"><small>进度自动保存在当前浏览器</small><button class="primary-button" data-close>开始我的冒险</button></div>`}
 if(type==='journey'){c.innerHTML=modalHeader('YOUR JOURNEY','星海中的三场棋局','一路收集星尘，选择遗物，让你的巫师变得更强。每幕结束后回复 8 生命、补满法力，并获得 3 护盾。')+STAGES.map((s,i)=>`<div class="journey-step ${i===game.stage?'current':''}"><span class="roman">${s.rune}</span><div><b>${s.name}</b><p>${s.subtitle}</p></div><small>${i<game.stage?'已净化':i===game.stage?'当前秘境':'尚未抵达'}</small></div>`).join('')+`<div class="modal-actions"><small>已击败 ${game.kills} 名敌人 · 收集 ${game.gold} 星尘</small><button class="primary-button" data-close>返回棋盘</button></div>`}
 if(type==='spells'){c.innerHTML=modalHeader('THE GRIMOIRE','法术之书','智慧比力量更重要。组合移动、攻击与防御，找到属于你的解法。')+SPELLS.map(s=>`<div class="spell-book-row" style="--spell-color:${s.color}">${icon(s.icon)}<div><b>${s.name}</b><small>${s.ap} 行动点 · ${game.cost(s)} 法力 · 按键 ${s.key}</small><p>${s.desc}</p></div></div>`).join('')}
 if(type==='relics'){c.innerHTML=modalHeader('YOUR COLLECTION','旅途中的馈赠',game.relics.length?'遗物的力量会持续到这次冒险结束。':'通过第一座秘境后，即可从三件遗物中选择一件。')+(game.relics.length?'<div class="relic-grid">'+game.relics.map(id=>{const r=RELICS.find(r=>r.id===id);return `<div class="relic-card">${icon(r.icon)}<b>${r.name}</b><p>${r.desc}</p><small>${r.detail}</small></div>`}).join('')+'</div>':'<div class="help-item">'+icon('diamond')+'<b>你的第一件遗物，正在前方等你。</b><p>古树之心、不灭余烬、月辉棱镜……每一次选择，都会带来不同的战斗方式。</p></div>')}
 if(type==='reward'){sound('victory');c.innerHTML=modalHeader('CHAPTER COMPLETE','秘境重归宁静','选择一件遗物，带着星光踏入下一幕。你的生命将恢复 8 点，法力补满。')+'<div class="relic-grid">'+game.rewardChoices().map(r=>`<button class="relic-card" data-reward="${r.id}">${icon(r.icon)}<b>${r.name}</b><p>${r.desc}</p><small>${r.detail}</small></button>`).join('')+'</div><div class="tutorial-note">下一站 · '+STAGES[game.stage+1].name+'　/　'+STAGES[game.stage+1].subtitle+'</div>';c.querySelectorAll('[data-reward]').forEach(b=>b.addEventListener('click',()=>{if(game.chooseRelic(b.dataset.reward)){closeModal(true);selected='move';scene?.rebuild(game);render();toast('新遗物已装备，继续你的旅程')}}))}
 if(type==='won'||type==='lost'){const won=type==='won';if(won)sound('victory');c.innerHTML='<div class="result-view"><div class="victory-icon">'+(won?'✧':'☾')+'</div>'+modalHeader(won?'THE STARS REMEMBER':'A NEW BEGINNING',won?'星辰，为你落子':'每一位巫师都曾迷途',won?'星蚀君王倒下，三座秘境重获自由。你的名字，已被写进群星之间。':'棋局尚未终结。记住这次旅程，再次踏入星海。')+`<div class="result-stats"><span><b>${game.stage+1}</b><small>抵达秘境</small></span><span><b>${game.kills}</b><small>击败敌人</small></span><span><b>${game.gold}</b><small>收集星尘</small></span></div><button class="primary-button" id="new-journey">再次启程</button></div>`;$('#new-journey').addEventListener('click',restart)}
 if(type==='settings'){c.innerHTML=modalHeader('YOUR PREFERENCES','旅途设置','让这场冒险保持你喜欢的节奏。')+`<div class="settings-row"><div><b>冒险难度</b><p>故事模式中，敌人每次攻击减少 1 点伤害。</p></div><select id="difficulty" aria-label="冒险难度"><option value="normal" ${game.difficulty==='normal'?'selected':''}>标准冒险</option><option value="story" ${game.difficulty==='story'?'selected':''}>故事模式</option></select></div><div class="settings-row"><div><b>魔法音效</b><p>轻盈的合成音，陪伴每一次行动。</p></div><button id="settings-sound" class="primary-button">${soundOn?'关闭':'开启'}</button></div><div class="settings-row"><div><b>重新启程</b><p>重新开始本次冒险，并清除当前进度。</p></div><button id="restart-confirm" class="danger-button">重新开始</button></div>`;$('#difficulty').addEventListener('change',e=>{game.difficulty=e.target.value;save();toast('冒险难度已更新')});$('#settings-sound').addEventListener('click',()=>{toggleSound();$('#settings-sound').textContent=soundOn?'关闭':'开启'});$('#restart-confirm').addEventListener('click',()=>openModal('restart'))}
 if(type==='restart'){c.innerHTML=modalHeader('START OVER','准备再次启程？','本次冒险进度和遗物将被清除，你将回到微光林地。')+'<div class="modal-actions"><button class="quiet-button" data-close>保留当前旅程</button><button class="primary-button" id="confirm-restart">重新开始</button></div>';$('#confirm-restart').addEventListener('click',restart)}
 c.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal()));requestAnimationFrame(()=>($('#modal').querySelector('button:not([hidden]),select')||$('#modal')).focus())}
function closeModal(force=false){if(!force&&['reward','won','lost'].includes(currentModal))return;currentModal=null;$('#modal-backdrop').hidden=true;previousFocus?.focus?.()}
function restart(){turnToken++;game=new Game(game.difficulty);selected='move';closeModal(true);scene?.rebuild(game);render();toast('新旅程开始，愿星光指引你')}
function toggleSound(){soundOn=!soundOn;$('#sound').innerHTML=icon(soundOn?'sound':'muted');$('#sound').setAttribute('aria-label',soundOn?'关闭音效':'开启音效');if(soundOn)sound('move')}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));$('#close-modal').addEventListener('click',()=>closeModal());$('#modal-backdrop').addEventListener('click',e=>{if(e.target===$('#modal-backdrop'))closeModal()});$('#end-turn').addEventListener('click',endTurn);$('#sound').addEventListener('click',toggleSound);$('#rotate-left').addEventListener('click',()=>scene?.rotate(-Math.PI/2));$('#rotate-right').addEventListener('click',()=>scene?.rotate(Math.PI/2));$('#reset-camera').addEventListener('click',()=>scene?.reset());$('#grid-toggle').addEventListener('click',()=>{if(scene){scene.showCoords=!scene.showCoords;$('#grid-state').textContent=scene.showCoords?'开':'关'}});
document.addEventListener('keydown',e=>{if(currentModal){if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=[...$('#modal').querySelectorAll('button:not([hidden]),select')].filter(el=>!el.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}return}if(e.target.matches('input,select,textarea'))return;if(e.key>='1'&&e.key<='7'){e.preventDefault();select(SPELLS[Number(e.key)-1].id)}if(e.code==='Space'){e.preventDefault();endTurn()}if(e.key.toLowerCase()==='q')scene?.rotate(-Math.PI/2);if(e.key.toLowerCase()==='e')scene?.rotate(Math.PI/2);if(e.key.toLowerCase()==='r')scene?.reset();if(e.key==='Escape'){selected=null;scene?.select(null);renderSpells();$('#action-instruction').textContent='选择行动，再点击棋盘目标'}});
render();if(game.phase==='player')setTimeout(()=>toast('欢迎，星行者。点击高亮棋格，迈出第一步。'),900);
const summary=()=>({chapter:STAGES[game.stage].name,stage:game.stage,round:game.round,phase:game.phase,hero:{...game.hero},enemies:game.enemies.map(e=>({id:e.id,name:e.name,x:e.x,y:e.y,hp:e.hp,frozen:e.frozen})),relics:[...game.relics],validTargets:game.targets(selected).map(t=>({x:t.x,y:t.y})),selected});
window.astral={getState:summary,game,scene};
if(document.modelContext?.registerTool){const options={signal:new AbortController().signal};const tools=[{name:'read_battle_state',title:'查看当前战局',description:'Read the current chapter, wizard resources, enemy positions and valid targets. Coordinates are integers from 0 to 7.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>summary()},{name:'perform_battle_action',title:'执行战斗行动',description:'Perform the same spell or movement as the visible game controls. Costs action points and possibly mana. end_turn resolves enemy actions. Does not restart the game.',inputSchema:{type:'object',properties:{action:{type:'string',enum:[...SPELLS.map(s=>s.id),'end_turn']},x:{type:'integer',minimum:0,maximum:7},y:{type:'integer',minimum:0,maximum:7}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input!=='object'||(!SPELLS.some(s=>s.id===input.action)&&input.action!=='end_turn'))throw Error('Unknown battle action');if(currentModal)throw Error('Close the current dialog before acting');if(input.action==='end_turn'){if(game.phase!=='player')throw Error('Not the player turn');await endTurn()}else{const s=SPELLS.find(s=>s.id===input.action);if(s.range&&(!Number.isInteger(input.x)||!Number.isInteger(input.y)||input.x<0||input.x>7||input.y<0||input.y>7))throw Error('Target coordinates must be integers from 0 to 7');const result=perform(input.action,s.range?input.x:game.hero.x,s.range?input.y:game.hero.y);if(!result.ok)throw Error(result.error)}return summary()}}];tools.forEach(tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,options)).catch(()=>{})}catch{}})}
