import * as THREE from 'three';
import './style.css';
const $=id=>document.getElementById(id);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e6eddf');scene.fog=new THREE.Fog('#e6eddf',45,85);
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setSize(innerWidth,innerHeight);
const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,150);let zoom=1;
function cameraUpdate(){const fit=Math.max(1,1.1/(innerWidth/innerHeight));camera.position.set(22*zoom*fit,26*zoom*fit,32*zoom*fit);scene.fog.near=45*fit*zoom;scene.fog.far=85*fit*zoom;camera.far=150*fit;camera.lookAt(0,0,0);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}cameraUpdate();
scene.add(new THREE.HemisphereLight('#ffffe2','#6e8f77',2.6));const sun=new THREE.DirectionalLight('#fff1cd',3.5);sun.position.set(-12,25,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:20,bottom:-20});sun.shadow.normalBias=.04;scene.add(sun);
const mats={};function mat(c){return mats[c]??(mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.9,flatShading:true}))}
function mesh(geo,c,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
const box=(w,h,d,c,x,y,z,p)=>mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p);
const ball=(r,c,x,y,z,p,detail=0)=>mesh(new THREE.IcosahedronGeometry(r,detail),c,x,y,z,p);
const cyl=(r1,r2,h,c,x,y,z,p,n=7)=>mesh(new THREE.CylinderGeometry(r1,r2,h,n),c,x,y,z,p);
const ground=box(180,.1,180,'#e6eddf',0,-2.2,0);ground.castShadow=false;
// A cutaway woodland diorama, with a winding, translucent stream.
box(25,1.7,18,'#a38b60',0,-1.15,0);box(25,.35,18,'#b5bb83',0,-.35,0);
box(9.1,.7,18,'#90ac6e',-8,-.02,0);box(9.1,.7,18,'#a2b87c',8,-.02,0);
box(9.2,.14,18,'#aec589',-8,.38,0);box(9.2,.14,18,'#bace90',8,.38,0);
const water=box(7.1,.3,18.02,'#79bfbc',0,-.01,0);water.material=new THREE.MeshStandardMaterial({color:'#74bab9',roughness:.25,metalness:.08,transparent:true,opacity:.88});
for(let i=0;i<30;i++){let z=-8.8+i*.62;ball(.42+(i%3)*.1,i%2?'#bbc5a0':'#d7d6b0',-3.65,.15,z);ball(.36+(i%4)*.07,'#b7c19a',3.65,.12,z)}
const ripples=[];for(let i=0;i<40;i++){const m=box(.25+Math.random()*.75,.018,.035,i%3?'#b9ddd0':'#e1eee0',-3+Math.random()*6,.16,-8.5+Math.random()*17);m.castShadow=false;ripples.push(m)}
// Soft footpaths and stepping stones.
for(const side of [-1,1]){box(8,.03,1.9,'#d4c797',side*8,.47,0);for(let i=0;i<14;i++){const x=side*(4.2+Math.random()*7.8);const z=(Math.random()-.5)*1.4;const m=cyl(.15,.2,.035,'#e3d7b0',x,.5,z,scene,5);m.rotation.y=Math.random()*3}}
const trees=[],particles=[],animals=[],bridge=[],decor=new THREE.Group();scene.add(decor);
function tree(x,z,scale=1){const group=new THREE.Group();group.position.set(x,.4,z);group.scale.setScalar(scale);scene.add(group);cyl(.17,.24,1.7,'#7d6745',0,.85,0,group);cyl(0,1.13,1.65,'#507c54',0,1.6,0,group);cyl(0,.91,1.6,'#66945d',0,2.35,0,group);cyl(0,.62,1.4,'#82a769',0,3,0,group);const t={group,x,z,hits:0,ready:true,regrow:0};group.traverse(o=>o.userData.tree=t);trees.push(t)}
[[-10,-6,1.2],[-8,-7,1.1],[-6,-6.8,.9],[-11,-3.8,1],[-8.4,-4,.85],[-5.4,-4.5,1.15],[-11,3.3,.85],[-9,5,1.1],[-6.1,5.9,.8],[-11,7,1.2],[-5.4,3.9,.75],[6,-6,1.2],[8,-7,1],[10.5,-5.3,1.3],[11.2,-2.6,.8],[10.8,5.7,1.1],[8.1,7,.9],[5.9,6,1.05]].forEach(t=>tree(...t));
for(let i=0;i<110;i++){const side=i%2?1:-1,x=side*(4.2+Math.random()*7.6),z=(Math.random()-.5)*16;if(Math.abs(z)<1.4)continue;const color=['#eae6ac','#eee8c9','#d5a385','#e9bd73'][i%4];if(i%3===0){const b=ball(.24,'#89a568',x,.55,z);b.scale.set(1.5,1,1)}else{cyl(.025,.025,.3,'#718f57',x,.6,z);ball(.08,color,x,.79,z)}}
for(const [x,z]of[[-6,-2.6],[-10,6.3],[5.1,-3.8],[10,3.8],[-4.7,7]]){const r=ball(.55,'#a4b09b',x,.55,z);r.scale.set(1.3,.7,.9);ball(.3,'#b8c1a8',x+.5,.5,z+.2)}
function sign(x,z,home=false){const g=new THREE.Group();g.position.set(x,.4,z);scene.add(g);box(.15,1.5,.15,'#8c704a',0,.75,0,g);box(1.1,.6,.15,home?'#e5ce96':'#c1a46d',0,1.3,0,g);const cv=document.createElement('canvas');cv.width=256;cv.height=128;const ctx=cv.getContext('2d');ctx.fillStyle=home?'#e5ce96':'#c1a46d';ctx.fillRect(0,0,256,128);ctx.fillStyle='#4c6446';ctx.font='bold 43px sans-serif';ctx.textAlign='center';ctx.fillText(home?'HOME →':'← WOODS',128,78);const m=new THREE.Mesh(new THREE.PlaneGeometry(1.07,.54),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(cv)}));m.position.set(0,1.3,.082);g.add(m)}sign(-4.8,-1.3);sign(7.7,-1.3,true);
// Destination cottage.
const house=new THREE.Group();house.position.set(10,.45,-.2);scene.add(house);box(2.1,1.8,2,'#e4cf9e',0,.9,0,house);const roof=cyl(0,1.9,1.35,'#a36e4f',0,2.3,0,house,4);roof.rotation.y=Math.PI/4;box(.65,1.1,.08,'#886d48',0,.55,1.04,house);box(.45,.45,.08,'#bad8c1',-.65,1.2,1.04,house);box(.4,.85,.4,'#af9b73',.7,2.3,-.3,house);
function creature(type,x,z){const g=new THREE.Group();g.position.set(x,.5,z);scene.add(g);const color=type==='beaver'?'#956343':type==='fox'?'#cc8245':type==='bear'?'#ab8758':'#eee5cc';const body=ball(.48,color,0,.5,0,g,1);body.scale.set(.9,1,.8);ball(.39,color,0,1.07,.05,g,1);const muzzle=ball(.22,type==='beaver'?'#c49a6b':'#f3e4c5',0,.96,.34,g);muzzle.scale.set(1,.65,.65);for(const s of [-1,1]){ball(.055,'#293b30',s*.15,1.15,.35,g);ball(.13,color,s*.3,.24,.2,g);const ear=ball(type==='rabbit'?.17:.14,color,s*.23,1.4,.02,g);if(type==='rabbit')ear.scale.set(.7,2.8,.7);if(type==='fox')ear.scale.set(.85,1.65,.8)}ball(.055,'#493e32',0,1.01,.5,g);if(type==='beaver'){const tail=ball(.35,'#614d38',0,.22,-.5,g);tail.scale.set(.75,.3,1.6);box(.15,.16,.07,'#f9f1d4',0,.86,.47,g);const hat=cyl(.33,.36,.09,'#dbb55d',0,1.39,0,g);cyl(.23,.27,.2,'#e2bf67',0,1.49,0,g);box(.58,.24,.05,'#5b8774',0,.63,.38,g)}if(type==='fox'){const tail=ball(.3,color,0,.48,-.47,g);tail.scale.set(.7,.7,1.7);ball(.18,'#eee6ce',0,.48,-.82,g)}return g}
const beaver=creature('beaver',-5.2,1.8);for(let i=0;i<3;i++){const g=creature(['rabbit','fox','bear'][i],-7.5-i*1.15,-.35+(i%2)*.7);g.rotation.y=Math.PI/2;animals.push({g,progress:0,saved:false})}
const ghostGroup=new THREE.Group();scene.add(ghostGroup);for(let i=0;i<6;i++){const ghost=box(1.12,.045,1.65,'#d5e3c1',-2.95+i*1.18,.25,0,ghostGroup);ghost.material=new THREE.MeshStandardMaterial({color:'#dbe9d0',transparent:true,opacity:.22,roughness:1});ghost.castShadow=false}
const ring=new THREE.Mesh(new THREE.RingGeometry(.65,.72,40),new THREE.MeshBasicMaterial({color:'#faf0b5',side:THREE.DoubleSide,transparent:true,opacity:.7}));ring.rotation.x=-Math.PI/2;scene.add(ring);
const marker=ring.clone();marker.material=ring.material.clone();marker.visible=false;scene.add(marker);
const state={wood:0,capacity:16,coins:0,saved:0,level:0,built:0,gathered:0,localSaved:0,upgrade:0,paused:false,mode:'idle',target:null,tree:null,actionTime:0,time:0,hazardAt:32,broken:-1,muted:true,won:false};
const levels=[{title:'溪流上的第一座桥',desc:'一条小河，隔开了回家的路。<br>用你的巧手，把森林重新连起来。',chapter:'第一章 · 春日来信',cost:2,weather:'晴朗 · 适合开工的一天',detail:'河水温柔地流淌着'},{title:'雨后，水流有点急',desc:'昨夜的雨让溪水涨了起来。<br>留意漂木，及时修补受损的桥面。',chapter:'第二章 · 雨后的约定',cost:3,weather:'急流 · 漂木正在靠近',detail:'桥面受损后，按 2 消耗 2 木材维修'},{title:'黄昏前的最后一程',desc:'森林深处还有朋友在等你。<br>造一座更结实的桥，点亮归家的路。',chapter:'第三章 · 把夕阳带回家',cost:4,weather:'黄昏 · 最后的救援',detail:'更频繁的漂木，需要及时修桥'}];
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800)}
let audioCtx;function tone(freq=440,duration=.1){if(state.muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function burst(pos,c,n=12){for(let i=0;i<n;i++){const p=box(.09,.09,.09,c,pos.x,pos.y+.7,pos.z);particles.push({m:p,v:new THREE.Vector3((Math.random()-.5)*3,1+Math.random()*2,(Math.random()-.5)*3),life:1})}}
function ui(){const l=levels[state.level];$('wood').textContent=state.wood;$('capacity').textContent=state.capacity;$('coins').textContent=state.coins;$('saved').textContent=state.saved;$('wood-total').textContent=`${Math.min(state.gathered,l.cost*6)} / ${l.cost*6}`;$('bridge-count').textContent=`${state.built} / 6`;$('rescue-count').textContent=`${state.localSaved} / 3`;$('check-wood').classList.toggle('done',state.gathered>=l.cost*6);$('check-bridge').classList.toggle('done',state.built===6&&state.broken<0);$('check-save').classList.toggle('done',state.localSaved===3);$('build').querySelector('strong').textContent=state.broken>=0?'维修桥面':`铺设桥面 · ${l.cost}`;animals.forEach((a,i)=>$('status'+i).textContent=a.saved?'已到家':state.mode==='rescue'?'过桥中':'等待中');$('upgrade-label').textContent=state.upgrade>=2?'工具已满级':'工具升级';$('upgrade-price').textContent=state.upgrade>=2?'采集 +2 · 快步':`${10+state.upgrade*10} 橡果`}
function allowed(){return !state.paused&&!state.won}
function gather(t){if(!allowed())return;if(state.wood>=state.capacity){toast('背包装满啦，先铺几段桥面吧');return}t??=trees.filter(t=>t.ready&&t.x<0).sort((a,b)=>beaver.position.distanceTo(a.group.position)-beaver.position.distanceTo(b.group.position))[0];if(!t||!t.ready){toast('小树正在休息，稍等片刻就会长回来');return}if(t.x>0&&state.built<6){toast('先连通两岸，才能去对面的森林');return}state.mode='gather';state.tree=t;setTarget(t.x,t.z+1);toast('出发！采集木材中…')}
function setTarget(x,z){state.target=new THREE.Vector3(x,.5,z);marker.position.set(x,.48,z);marker.visible=true}
function bridgePiece(i){const g=new THREE.Group();g.position.set(-2.95+i*1.18,.38,0);scene.add(g);for(let j=0;j<4;j++)box(.255,.16,1.85,j%2?'#c99b65':'#d8af77',-.42+j*.28,.05,0,g);for(const z of [-.78,.78]){box(1.2,.15,.14,'#8c6847',0,-.08,z,g);cyl(.065,.075,.8,'#93744c',-.49,.27,z,g);box(1.18,.065,.065,'#c0a375',0,.61,z,g)}g.scale.setScalar(.1);bridge.push(g)}
function build(){if(!allowed())return;if(state.broken>=0){if(state.wood<2){toast('维修需要 2 根木材，先去采集吧');return}state.wood-=2;bridge[state.broken].rotation.z=0;bridge[state.broken].position.y=.38;burst(bridge[state.broken].position,'#f3d47e');state.broken=-1;tone(600);toast('桥面修好了！朋友们可以继续前进');ui();return}if(state.built===6){toast('桥已经连通了！按 3 召集小伙伴');return}const cost=levels[state.level].cost;if(state.wood<cost){toast(`这段桥需要 ${cost} 根木材，按 1 去采集`);return}state.wood-=cost;bridgePiece(state.built);burst(bridge[state.built].position,'#e1bf7e',18);state.built++;tone(280+state.built*65);state.mode='idle';state.target=null;marker.visible=false;ui();if(state.built===6){toast('两岸连通啦！吹响哨子，接朋友回家');$('world-label').textContent='一座小桥，把想念连在一起。'}else toast(`桥面 +1 · 还差 ${6-state.built} 段就到对岸了`)}
function rescue(){if(!allowed())return;if(state.built<6){toast('桥还没连通，先把 6 段桥面铺好');return}if(state.broken>=0){toast('有一段桥面受损了，按 2 修好它');return}state.mode='rescue';state.target=null;marker.visible=false;toast('集合啦！小伙伴们正在过桥');tone(880,.3);ui()}
function upgrade(){if(!allowed())return;if(state.upgrade>=2){toast('已经是森林里最棒的工具啦');return}const price=10+state.upgrade*10;if(state.coins<price){toast(`升级需要 ${price} 颗橡果，帮助朋友过河即可获得`);return}state.coins-=price;state.upgrade++;state.capacity+=8;toast('工具升级！采集量、行走速度和背包容量提升');tone(740,.3);ui()}
function modal(title,content,button,callback,eyebrow='松果溪谷 · 森林日记'){$('modal-title').textContent=title;$('modal-content').innerHTML=content;$('modal-button').textContent=button;$('modal-eyebrow').textContent=eyebrow;$('modal').classList.remove('hidden');state.paused=true;$('modal-button').onclick=()=>{$('modal').classList.add('hidden');state.paused=false;callback?.()}}
function nextLevel(){state.level++;state.built=0;state.localSaved=0;state.gathered=0;state.broken=-1;state.mode='idle';state.hazardAt=state.time+27;bridge.splice(0).forEach(g=>scene.remove(g));beaver.position.set(-5.2,.5,1.8);animals.forEach((a,i)=>{a.saved=false;a.g.visible=true;a.g.position.set(-7.5-i*1.15,.5,-.35+(i%2)*.7)});const l=levels[state.level];$('level-title').textContent=l.title;$('level-desc').innerHTML=l.desc;$('season').textContent=l.chapter;$('level-label').textContent=`0${state.level+1} / 03`;$('weather-text').innerHTML=`${l.weather}<small>${l.detail}</small>`;$('world-label').textContent='新的旅程，新的朋友。';document.querySelectorAll('.objective small')[1].textContent=`每段桥面需要 ${l.cost} 根木材`;if(state.level===2){sun.color.set('#ffd19b');scene.background.set('#e9e5d5');scene.fog.color.set('#e9e5d5')}ui()}
function finish(){state.mode='idle';state.coins+=10;ui();tone(980,.5);if(state.level<2)modal('他们都平安到家了。',`<p>小桥那头，是久违的拥抱。<br>感谢你，又为森林带来了一点温暖。</p><div class="stats"><div><b>3</b><small>朋友平安回家</small></div><div><b>+10</b><small>关卡奖励橡果</small></div></div>`,'前往下一片森林 →',nextLevel,'章节完成 · 干得漂亮');else{state.won=true;let best=Number(localStorage.getItem('beaver-best')||0);localStorage.setItem('beaver-best',Math.max(best,state.coins));modal('森林，因为你重新相连。',`<p>三座桥，九位朋友，一位了不起的小工程师。<br>谢谢你让每一个等待，都有了归途。</p><div class="stats"><div><b>${state.saved}</b><small>累计救援</small></div><div><b>${state.coins}</b><small>剩余橡果</small></div><div><b>${Math.floor(state.time/60)}:${String(Math.floor(state.time%60)).padStart(2,'0')}</b><small>旅程时间</small></div></div>`,'再来一场冒险 ↻',()=>location.reload(),'森林守护者 · 全部章节完成')}}
$('gather').onclick=()=>gather();$('build').onclick=build;$('rescue').onclick=rescue;$('upgrade').onclick=upgrade;$('sound').style.opacity='.55';$('sound').onclick=()=>{state.muted=!state.muted;$('sound').textContent=state.muted?'♫':'♪';$('sound').style.opacity=state.muted?'.55':'1';toast(state.muted?'音效已关闭':'音效已开启');tone(500)};$('help').onclick=()=>modal('做一只快乐的工程狸。','<ol><li>点击树木或按 1：走近后自动采集，树木会再生。</li><li>按 2 铺桥：收集足够木材，铺满 6 段桥面。</li><li>按 3 吹哨：召集动物过桥，获得橡果奖励。</li><li>橡果可以升级工具，提高采集量与背包容量。</li><li>后续章节有漂木撞桥；按 2 消耗木材维修。</li><li>点击地面或 WASD 移动，滚轮调整视角。</li></ol>','明白了，开工！');$('pause').onclick=()=>{if(!state.paused)modal('在树荫下，歇一小会。','<p>河水仍在心里流淌，朋友们会等你。</p>','继续冒险 →')};$('zoom-in').onclick=()=>{zoom=Math.max(.65,zoom-.1);cameraUpdate()};$('zoom-out').onclick=()=>{zoom=Math.min(1.4,zoom+.1);cameraUpdate()};$('reset-view').onclick=()=>{zoom=1;cameraUpdate()};
const keys={};addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.repeat)return;if(e.key==='1')gather();if(e.key==='2'||e.key===' ')build();if(e.key==='3')rescue();if(e.key==='Escape'){$('modal').classList.contains('hidden')?$('pause').click():$('modal-button').click()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();$('world').addEventListener('pointerdown',e=>{if(!allowed())return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(scene.children,true);for(const h of hits){if(h.object.userData.tree){gather(h.object.userData.tree);return}if(h.object===ground)continue;const p=h.point;if(Math.abs(p.x)<3.5&&(state.built<6||Math.abs(p.z)>.8)){toast('这里是河水，海狸要从桥上通过哦');return}if(Math.abs(p.x)<12&&Math.abs(p.z)<8.5){if(p.x>3.5&&(state.built<6||state.broken>=0)){toast('先修好桥，再去对岸吧');return}state.mode='walk';setTarget(p.x,p.z);return}}});$('world').addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.001,.65,1.4);cameraUpdate()},{passive:false});
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);cameraUpdate()});
// Drifting logs telegraph a river hazard before a bridge segment needs repair.
const drift=cyl(.18,.2,1.5,'#8d7452',0,.32,-9);drift.rotation.z=Math.PI/2;drift.visible=false;let drifting=false;
function move(g,target,dt,speed){const d=target.clone().sub(g.position);d.y=0;const distance=d.length();if(distance<.13){g.position.x=target.x;g.position.z=target.z;return true}g.rotation.y=Math.atan2(d.x,d.z);g.position.addScaledVector(d.normalize(),Math.min(speed*dt,distance));g.position.y=.5+Math.abs(Math.sin(state.time*12))*.06;return false}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.1);if(!state.paused){state.time+=dt;ripples.forEach((m,i)=>{m.position.z+=dt*(.5+state.level*.4);if(m.position.z>8.8)m.position.z=-8.8;m.material.opacity=.7+Math.sin(state.time+i)*.2});ring.position.set(beaver.position.x,.49,beaver.position.z);ring.material.opacity=.45+Math.sin(state.time*3)*.18;bridge.forEach(g=>g.scale.lerp(new THREE.Vector3(1,1,1),dt*8));
const dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dz){state.target=null;state.mode='idle';marker.visible=false;const p=beaver.position.clone().add(new THREE.Vector3(dx,0,dz).normalize().multiplyScalar(dt*(3.2+state.upgrade)));if(Math.abs(p.x)<12&&Math.abs(p.z)<8.3&&(Math.abs(p.x)>3.6||(state.built===6&&state.broken<0&&Math.abs(p.z)<.68))){beaver.position.copy(p);beaver.rotation.y=Math.atan2(dx,dz)}}
if(state.target){let goal=state.target;const crossing=(beaver.position.x< -3.5&&goal.x> -3.5)||(beaver.position.x>3.5&&goal.x<3.5)||(Math.abs(beaver.position.x)<3.5);if(crossing){if(state.built<6||state.broken>=0){state.target=null;state.mode='idle';marker.visible=false;toast('先把桥修好，就能安全走到对岸');}else if(Math.abs(beaver.position.z)>.15&&Math.abs(beaver.position.x)>3.5)goal=new THREE.Vector3(beaver.position.x,.5,0);else if(Math.sign(beaver.position.x)!==Math.sign(goal.x)||Math.abs(beaver.position.x)<3.8)goal=new THREE.Vector3(Math.sign(goal.x)*4,.5,0)}if(state.target&&move(beaver,goal,dt,3.2+state.upgrade)&&goal===state.target){state.target=null;marker.visible=false;state.actionTime=0}}
if(state.mode==='gather'&&!state.target&&state.tree?.ready){state.actionTime+=dt;state.tree.group.rotation.z=Math.sin(state.time*25)*.025;beaver.rotation.y=Math.atan2(state.tree.x-beaver.position.x,state.tree.z-beaver.position.z);if(state.actionTime>1.05/(1+state.upgrade*.3)){const amount=Math.min(4+state.upgrade*2,state.capacity-state.wood);state.wood+=amount;state.gathered+=amount;state.tree.ready=false;state.tree.regrow=state.time+12;state.tree.group.scale.y=.17;state.tree.group.rotation.z=0;burst(state.tree.group.position,'#d9bd81',16);tone(350,.15);state.mode='idle';toast(`木材 +${amount} · 小树会在 12 秒后长回来`);ui()}}
trees.forEach(t=>{if(!t.ready&&state.time>t.regrow){t.ready=true;t.group.scale.y=t.group.scale.x}});
if(state.level>0&&state.built>0&&state.broken<0&&state.time>state.hazardAt&&!drifting&&state.localSaved<3){drifting=true;drift.visible=true;drift.position.set(-2.8+Math.random()*5.6,.32,-8.5);toast('上游漂来一根树干，留意桥面！')}
if(drifting){drift.position.z+=dt*(1.5+state.level*.4);if(drift.position.z>-.8){drifting=false;drift.visible=false;if(state.built>0){state.broken=Math.min(state.built-1,Math.floor((drift.position.x+3.5)/1.18));bridge[state.broken].rotation.z=.19;bridge[state.broken].position.y=.18;burst(bridge[state.broken].position,'#b9d9cf',20);toast('桥面受损！按 2 花费 2 根木材修补');ui()}state.hazardAt=state.time+(state.level===2?17:25)}}
if(state.mode==='rescue'&&state.broken<0){animals.forEach((a,i)=>{if(a.saved)return;const target=new THREE.Vector3(9,.5,0);if(a.g.position.x< -3.7&&Math.abs(a.g.position.z)>.08){move(a.g,new THREE.Vector3(a.g.position.x,.5,0),dt,1.7);return}if(move(a.g,target,dt,1.7-i*.13)){a.saved=true;a.g.visible=false;state.localSaved++;state.saved++;state.coins+=5;burst(target,'#f4d77d',25);tone(660+i*120,.25);toast(`${['棉花','枫叶','蜂蜜'][i]}到家了！橡果 +5`);ui();if(state.localSaved===3)finish()}})}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=dt*4;p.m.position.addScaledVector(p.v,dt);p.m.rotation.x+=dt*3;p.m.scale.setScalar(Math.max(0,p.life));if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();particles.splice(i,1)}}
}renderer.render(scene,camera)}
const clock=new THREE.Clock();ui();animate();setTimeout(()=>toast('欢迎，小工程师！点击一棵树，开始你的第一座桥。'),900);
window.__game={state,trees,animals,bridge,gather,build,rescue,upgrade,nextLevel,scene,renderer};
