import * as THREE from './vendor/three.module.min.js';
import {Game,CELLS,ABILITIES,RESEARCH,WAVES,GATES,dist} from './simulation.js';
const $=id=>document.getElementById(id),canvas=$('world'),field=canvas.parentElement;
const game=new Game();let selected=new Set(),paused=false,modalPaused=false,speed=1,targetMode=null,moveMode=false,soundEnabled=false,toastTimer,bannerTimer,lastUI=0,keys=new Set(),audioCtx;
const scene=new THREE.Scene();scene.background=new THREE.Color('#10292e');scene.fog=new THREE.FogExp2('#10292e',.003);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('loading').innerHTML='<strong>浏览器未启用 3D 渲染</strong><span>请开启硬件加速，或使用支持 WebGL 2 的 Chrome / Safari。</span>';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const camera=new THREE.OrthographicCamera(-36,36,26,-26,.1,180);let zoom=1,pan={x:0,z:0};const camOffset=new THREE.Vector3(30,44,40);const target=new THREE.Vector3();
scene.add(new THREE.HemisphereLight('#c4eff0','#092632',2.2));const light=new THREE.DirectionalLight('#d6fbec',3.7);light.position.set(-14,35,20);scene.add(light);const fill=new THREE.DirectionalLight('#578bab',1.4);fill.position.set(20,14,-20);scene.add(fill);
const sphereGeo=new THREE.SphereGeometry(1,24,16),smallSphere=new THREE.SphereGeometry(1,12,8),ico=new THREE.IcosahedronGeometry(1,1),ringCache=new Map();
function material(color,opt={}){return new THREE.MeshStandardMaterial({color,roughness:.38,metalness:.12,...opt})}
function ball(geo,mat,scale=[1,1,1],pos=[0,0,0]){const m=new THREE.Mesh(geo,mat);m.scale.set(...scale);m.position.set(...pos);return m}
function ring(radius,color,opacity=.5,thickness=.055){const mesh=new THREE.Mesh(new THREE.TorusGeometry(radius,thickness,6,80),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.y=.1;return mesh}
function disposeObject(g){g.traverse(o=>{if(o.isMesh){if(![sphereGeo,smallSphere,ico].includes(o.geometry))o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}})}
function makeCell(type,enemy=false){const stats=enemy?{bacteria:{size:.68,color:'#e6859a'},virus:{size:.62,color:'#cc74b6'},armored:{size:1.25,color:'#d98868'},boss:{size:2.7,color:'#eb627f'}}[type]:CELLS[type],r=stats.size;const group=new THREE.Group(),body=new THREE.Group();group.add(body);group.userData.body=body;const color=new THREE.Color(stats.color),mat=material(color,{emissive:color,emissiveIntensity:.1});
 if(!enemy){const membrane=ball(sphereGeo,material(color,{transparent:true,opacity:.48,roughness:.18,depthWrite:false,emissive:color,emissiveIntensity:.14}),[r,r*.87,r],[0,r*.91,0]);body.add(membrane);const nucleus=ball(sphereGeo,mat,[r*.52,r*.57,r*.48],[r*.06,r*.9,r*.03]);body.add(nucleus);
  if(type==='macro'){membrane.scale.set(r*1.15,r*.87,r);for(let i=0;i<9;i++){const a=i/9*Math.PI*2;body.add(ball(smallSphere,mat,[r*.34,r*.32,r*.34],[Math.cos(a)*r*.85,r*.55,Math.sin(a)*r*.75]))}nucleus.scale.set(r*.6,r*.42,r*.37);nucleus.rotation.y=.5;}
  if(type==='neutro'){nucleus.scale.setScalar(r*.34);nucleus.position.set(-r*.3,r*.9,0);for(let i=0;i<2;i++)body.add(ball(smallSphere,mat,[r*.35,r*.4,r*.33],[r*.3,r*.85,r*(i-.5)*.6]))}
  for(let i=0;i<8;i++){const a=i*2.39,rr=r*(.5+.2*Math.sin(i*5));body.add(ball(smallSphere,material(color.clone().lerp(new THREE.Color('#e6fff0'),.45)),[r*.075,r*.075,r*.075],[Math.cos(a)*rr,r*(.65+.5*Math.sin(i*3.17)),Math.sin(a)*rr]))}
  if(type==='killer'||type==='bcell'){for(let i=0;i<8;i++){const a=i*Math.PI/4;const spike=new THREE.Mesh(new THREE.CylinderGeometry(.045,.08,r*.36,5),mat);spike.position.set(Math.cos(a)*r,r*.9,Math.sin(a)*r);spike.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(Math.cos(a),0,Math.sin(a)));body.add(spike)}}
  if(type==='helper'){const halo=ring(r*1.2,color,.5,.025);halo.position.y=r*1.2;halo.rotation.z=.25;body.add(halo)}
 }else{const shell=ball(type==='virus'||type==='boss'?ico:sphereGeo,mat,[r,r*.85,r],[0,r*.85,0]);body.add(shell);body.add(ball(smallSphere,material('#6f2c60',{emissive:'#e15a9d',emissiveIntensity:.2}),[r*.43,r*.4,r*.4],[r*.05,r*1.02,r*.3]));if(type==='bacteria'){shell.scale.set(r*1.35,r*.72,r*.65);for(let i=0;i<8;i++){const a=i*Math.PI/4;const stem=new THREE.Mesh(new THREE.CylinderGeometry(.028,.04,r*.7,4),mat);stem.position.set(Math.cos(a)*r*1.1,r*.8,Math.sin(a)*r*.7);stem.rotation.z=a;body.add(stem)}}else{for(let i=0;i<(type==='boss'?22:13);i++){const a=i*2.399,y=1-2*(i+.5)/(type==='boss'?22:13),rr=Math.sqrt(1-y*y),dir=new THREE.Vector3(Math.cos(a)*rr,y,Math.sin(a)*rr),length=r*.56;const stem=new THREE.Mesh(new THREE.ConeGeometry(r*.13,length,5),mat);stem.position.copy(dir.clone().multiplyScalar(r*.99)).add(new THREE.Vector3(0,r*.85,0));stem.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);body.add(stem);if(type==='boss')body.add(ball(smallSphere,material('#ffafbd',{emissive:'#ec456a',emissiveIntensity:.55}),[r*.08,r*.08,r*.08],dir.clone().multiplyScalar(r*1.28).add(new THREE.Vector3(0,r*.85,0)).toArray()))}}
 }
 const shadow=new THREE.Mesh(new THREE.CircleGeometry(r*1.1,24),new THREE.MeshBasicMaterial({color:'#001c23',transparent:true,opacity:.35,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.035;group.add(shadow);const selectRing=ring(r+ .45,enemy?'#f9859b':'#c4f58b',.85,.055);selectRing.visible=false;group.add(selectRing);group.userData.selectRing=selectRing;return group;
}
// Subtle undulating tissue: all geometry is the interactive game environment.
const terrain=new THREE.PlaneGeometry(105,105,70,70);terrain.rotateX(-Math.PI/2);const positions=terrain.attributes.position,colors=[];for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i),edge=Math.max(0,(Math.hypot(x,z)-27)/15);positions.setY(i,-.55+Math.sin(x*.2)*Math.cos(z*.17)*.28+Math.sin(x*.52+z*.21)*.12+edge*.8);const c=new THREE.Color().setHSL(.515+Math.sin(x*.13)*.015,.29,.015+Math.sin(z*.13+x*.08)*.003);colors.push(c.r,c.g,c.b)}terrain.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();scene.add(new THREE.Mesh(terrain,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.9,metalness:.1})));
const grid=new THREE.GridHelper(64,32,'#28525a','#24484e');grid.position.y=-.1;grid.material.transparent=true;grid.material.opacity=.19;scene.add(grid);
// Boundary and fine range ticks.
scene.add(ring(28.5,'#426369',.3,.035));scene.add(ring(29,'#315157',.3,.018));for(let i=0;i<80;i++){const a=i*Math.PI*2/80,r=28.5;const p=[new THREE.Vector3(Math.cos(a)*r,.08,Math.sin(a)*r),new THREE.Vector3(Math.cos(a)*(r+(i%5===0?.65:.25)),.08,Math.sin(a)*(r+(i%5===0?.65:.25)))];scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:'#4b7779',transparent:true,opacity:.35})))}
// Peripheral tissue cells frame the arena without obstructing orders.
let seeded=31;function rand(){seeded=(seeded*1664525+1013904223)>>>0;return seeded/4294967296}
for(let i=0;i<115;i++){const a=rand()*Math.PI*2,r=30+rand()*25,s=.8+rand()*2.5;const rock=ball(ico,material(new THREE.Color().setHSL(.5+rand()*.045,.25,.029+rand()*.012),{roughness:.76}),[s,.6+rand()*1.3,s*.9],[Math.cos(a)*r,-.15,Math.sin(a)*r]);rock.rotation.y=rand()*6;scene.add(rock)}
const particlePos=[];for(let i=0;i<250;i++)particlePos.push((rand()-.5)*85,rand()*8+.2,(rand()-.5)*85);const particles=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(particlePos,3)),new THREE.PointsMaterial({color:'#83bdb5',size:.075,transparent:true,opacity:.35,depthWrite:false}));scene.add(particles);
// Core: layered translucent membrane, living nucleus and orbiting organelles.
const coreGroup=new THREE.Group();coreGroup.position.set(game.core.x,0,game.core.z);scene.add(coreGroup);coreGroup.add(ball(sphereGeo,material('#76d7b3',{transparent:true,opacity:.26,depthWrite:false,emissive:'#50b994',emissiveIntensity:.23}),[3.25,2.5,3.25],[0,2.7,0]));coreGroup.add(ball(sphereGeo,material('#82cf9d',{emissive:'#58c392',emissiveIntensity:.4,roughness:.19}),[1.58,1.65,1.58],[0,2.8,0]));const coreNucleus=ball(ico,material('#c5efaf',{emissive:'#99e897',emissiveIntensity:.6}),[.8,.85,.75],[.25,2.95,.4]);coreGroup.add(coreNucleus);coreGroup.add(ring(3.9,'#72d4ae',.8,.045));coreGroup.add(ring(4.15,'#619987',.3,.025));const coreOrbits=[];for(let i=0;i<12;i++){const a=i*Math.PI/6;const org=ball(smallSphere,material('#b4f0c4',{emissive:'#96edb6',emissiveIntensity:.5}),[.16,.16,.16],[Math.cos(a)*2.5,2.2+Math.sin(a*2)*1.2,Math.sin(a)*2.5]);coreGroup.add(org);coreOrbits.push(org)}const coreLight=new THREE.PointLight('#64e7b4',15,15,1.5);coreLight.position.set(game.core.x,4,game.core.z);scene.add(coreLight);
function makeLabel(cls,html){const el=document.createElement('div');el.className='world-label '+cls;el.innerHTML=html;$('world-labels').appendChild(el);return el}
const coreLabel=makeLabel('core','组织核心<small>IMMUNE NEXUS</small>');
const nodeVisuals=game.nodes.map((n,i)=>{const g=new THREE.Group();g.position.set(n.x,0,n.z);const base=ring(2.1,'#bba16b',.65,.045);g.add(base);g.add(ring(2.45,'#807450',.25,.025));const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.66),material('#dfc282',{emissive:'#d9b564',emissiveIntensity:.5,metalness:.25,roughness:.25}));crystal.position.y=1.3;g.add(crystal);const inner=new THREE.Mesh(new THREE.CylinderGeometry(.65,1,.3,6),material('#635f3d',{metalness:.3}));inner.position.y=.2;g.add(inner);scene.add(g);return{g,base,crystal,label:makeLabel('node',`${n.name}<small>未占领 · +3 ATP / s</small>`),i}});
const gateVisuals=GATES.map((g,i)=>{const group=new THREE.Group();group.position.set(g.x,0,g.z);const r=ring(2.1,'#df809b',.5,.09);group.add(r);group.add(ring(2.65,'#99647a',.2,.03));const cloud=ball(sphereGeo,material('#9d4b6c',{transparent:true,opacity:.23,emissive:'#d3417a',emissiveIntensity:.35,depthWrite:false}),[2,.6,2],[0,.2,0]);group.add(cloud);scene.add(group);return{group,r,label:makeLabel('gate',g.name),i}});
const unitVisuals=new Map(),effects=[];function addUnit(u){if(unitVisuals.has(u.id))return;const mesh=makeCell(u.type,u.team==='enemy');mesh.position.set(u.x,0,u.z);scene.add(mesh);const label=makeLabel('unit','<div class="bar"><i></i></div>');label.querySelector('i').style.background=u.team==='enemy'?'#e58198':CELLS[u.type].color;unitVisuals.set(u.id,{mesh,label,u})}game.units.forEach(addUnit);
function addPulse(x,z,color,radius=3,duration=.75){const m=ring(.7,color,.8,.075);m.position.set(x,.16,z);scene.add(m);effects.push({type:'pulse',mesh:m,life:duration,total:duration,radius})}
function addBurst(u){const geo=new THREE.BufferGeometry(),arr=[],velocity=[];for(let i=0;i<14;i++){arr.push(u.x,Math.max(.5,u.size),u.z);velocity.push((Math.random()-.5)*5,Math.random()*3,(Math.random()-.5)*5)}geo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));const mesh=new THREE.Points(geo,new THREE.PointsMaterial({color:u.color,size:u.team==='enemy'?.16:.12,transparent:true,opacity:1,depthWrite:false}));scene.add(mesh);effects.push({type:'burst',mesh,velocity,life:.7,total:.7})}
function addShot(from,to){const ranged=from.team==='ally'&&['bcell','killer'].includes(from.type);if(ranged){const mesh=ball(smallSphere,new THREE.MeshBasicMaterial({color:from.color}),[.15,.15,.15],[from.x,1,from.z]);scene.add(mesh);effects.push({type:'shot',mesh,life:.25,total:.25,from:{x:from.x,z:from.z},to:{x:to.x,z:to.z}})}else{addPulse(to.x,to.z,from.team==='enemy'?'#e77990':from.color,.8,.25)}}
function beep(freq=440,len=.07,type='sine',gain=.025){if(!soundEnabled)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;o.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+len);o.start();o.stop(audioCtx.currentTime+len)}catch{}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
function banner(title,sub){$('battle-banner').innerHTML=`<strong>${title}</strong><span>${sub}</span>`;$('battle-banner').hidden=false;clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('battle-banner').hidden=true,3200)}
game.on(event=>{switch(event.type){case'spawn':addUnit(event.unit);if(event.unit.team==='ally'){addPulse(event.unit.x,event.unit.z,'#b6f58b',2);beep(570)}break;case'attack':addShot(event.from,event.to);break;case'death':{const v=unitVisuals.get(event.unit.id);if(v){scene.remove(v.mesh);disposeObject(v.mesh);v.label.remove();unitVisuals.delete(event.unit.id)}selected.delete(event.unit.id);addBurst(event.unit);break}case'heal':addPulse(event.unit.x,event.unit.z,'#79dfe5',3,.6);break;case'command':addPulse(event.x,event.z,'#c4f58b',1.6);beep(520,.06);break;case'capture':toast(`${event.node.name} 已控制 · 每秒 +3 ATP`);beep(780,.16);addPulse(event.node.x,event.node.z,'#b8f285',4,1);break;case'nodeLost':toast(`${event.node.name} 被病原体夺回`);break;case'wave':banner(`WAVE ${String(event.wave).padStart(2,'0')}`,event.name+' · 病原体即将进入');$('onboarding').hidden=true;$('onboarding').style.display='none';beep(170,.3,'sawtooth',.025);break;case'waveClear':toast(`第 ${event.wave} 波已清除 · 奖励 ${event.reward} ATP`);beep(860,.15);break;case'ability':addPulse(event.x,event.z,ABILITIES[event.abilityType].color,event.radius,1.2);if(event.abilityType==='interferon'){const mesh=ring(event.radius,'#ab9bef',.65,.1);mesh.position.set(event.x,.12,event.z);scene.add(mesh);effects.push({type:'zone',mesh,life:9,total:9})}beep(320,.25,'triangle');break;case'bossWarning':{toast('首领蓄力：让细胞撤离红色范围');const m=ring(7,'#ff6786',.85,.13);m.position.set(event.unit.x,.18,event.unit.z);scene.add(m);effects.push({type:'warning',mesh:m,life:1.7,total:1.7,unit:event.unit});break}case'bossPulse':addPulse(event.unit.x,event.unit.z,'#ff6289',8,1);break;case'end':showResult(event.won);break;}});
// Render live 3D cell portraits using the same models as the battlefield.
const portraitRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true});portraitRenderer.setSize(144,144);portraitRenderer.setPixelRatio(1);portraitRenderer.outputColorSpace=THREE.SRGBColorSpace;const portraitScene=new THREE.Scene();portraitScene.add(new THREE.HemisphereLight('#ffffff','#31545a',2.5));const pl=new THREE.DirectionalLight('#f0ffe8',4);pl.position.set(-3,5,4);portraitScene.add(pl);const pc=new THREE.OrthographicCamera(-1.7,1.7,1.7,-1.7,.1,20);pc.position.set(3,3,5);pc.lookAt(0,.9,0);
Object.entries(CELLS).forEach(([type,s],i)=>{const m=makeCell(type);m.scale.setScalar(type==='macro'?.85:1.05);portraitScene.add(m);portraitRenderer.render(portraitScene,pc);const url=portraitRenderer.domElement.toDataURL();portraitScene.remove(m);disposeObject(m);const card=document.createElement('button');card.className='cell-card';card.dataset.type=type;card.style.setProperty('--cell-color',s.color);card.setAttribute('aria-label',`招募${s.name}，${s.cost} ATP，快捷键 ${i+1}`);card.title=`${s.name} · ${s.detail}\n生命 ${s.hp} · 攻击 ${s.damage} · 射程 ${s.range}`;card.innerHTML=`<img class="cell-image" src="${url}" alt=""><div class="cell-info"><h3>${s.name}</h3><span class="role">${s.role}</span><p>${s.detail}</p><div class="cell-cost">ϟ ${s.cost} <small>ATP</small></div></div><kbd>${i+1}</kbd><span class="count">× 0</span>`;card.addEventListener('click',()=>recruit(type));$('cell-cards').appendChild(card)});portraitRenderer.dispose();
Object.entries(ABILITIES).forEach(([type,a])=>{const btn=document.createElement('button');btn.className='ability';btn.dataset.ability=type;btn.title=a.name+' · '+a.detail;btn.setAttribute('aria-label',`${a.name} ${a.cost} ATP`);btn.innerHTML=`<span class="ability-icon">${a.icon}</span><div><strong>${a.name}</strong><small>${a.detail}</small></div><span class="ability-cost">ϟ ${a.cost}</span><kbd>${a.key}</kbd>`;btn.onclick=()=>armAbility(type);$('abilities').appendChild(btn)});
$('wave-dots').innerHTML=Array.from({length:8},()=>'<i></i>').join('');
function recruit(type){const result=game.recruit(type);toast(result.message);beep(result.ok?670:130,.07);updateUI();return result}
function armAbility(type){const a=ABILITIES[type];if(game.cooldowns[type]>0){toast(`冷却中 · ${Math.ceil(game.cooldowns[type])} 秒`);return}if(game.atp<a.cost){toast('ATP 不足');return}targetMode=targetMode===type?null:type;moveMode=false;updateTargetHint();updateUI()}
function updateTargetHint(){const active=targetMode||moveMode;$('target-hint').hidden=!active;$('target-hint').textContent=targetMode?`${ABILITIES[targetMode].name}：点击施放区域 · Esc 取消`:'点击地面移动，或点击病原体集火 · Esc 取消';canvas.style.cursor=active?'crosshair':'default';targetCircle.visible=!!targetMode;if(targetMode){targetCircle.material.color.set(ABILITIES[targetMode].color);targetCircle.scale.setScalar(ABILITIES[targetMode].radius/3)}}
const targetCircle=ring(3,'#baf29a',.8,.07);targetCircle.visible=false;scene.add(targetCircle);
function getSelection(){return game.units.filter(u=>selected.has(u.id))}
function selectAll(){selected=new Set(game.units.map(u=>u.id));updateUI();beep(560)}
function doCommand(point,enemy){const result=game.command([...selected],{x:point.x,z:point.z,targetId:enemy?.id});if(!result.ok)toast(result.message);moveMode=false;updateTargetHint();return result}
function retreat(){if(!selected.size){toast('请先选择细胞');return}doCommand({x:game.core.x,z:game.core.z+5});toast('编队已回防核心')}
function hold(){if(!selected.size){toast('请先选择细胞');return}game.hold([...selected]);toast('编队原地驻守');updateUI()}
function pause(){if(['won','lost'].includes(game.phase))return;paused=!paused;$('pause').textContent=paused?'▷':'Ⅱ';$('pause').setAttribute('aria-label',paused?'继续':'暂停');toast(paused?'战斗已暂停 · 空格继续':'战斗继续');updateUI()}
function openDialog(id){modalPaused=true;$(id).showModal();if(id==='research-dialog')renderResearch()}
function renderResearch(){$('research-list').innerHTML=Object.entries(RESEARCH).map(([type,r])=>{const lv=game.research[type],cost=r.base+lv*90;return`<div class="research-item"><div><h3>${r.name} <span style="color:#aacc8d">${'●'.repeat(lv)}${'○'.repeat(3-lv)}</span></h3><p>${r.detail}</p></div><button data-upgrade="${type}" ${lv===3?'disabled':''}>${lv===3?'已满级':'升级研究'}<small>${lv===3?'LEVEL MAX':'ϟ '+cost+' ATP'}</small></button></div>`}).join('');$('research-list').querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const r=game.upgrade(b.dataset.upgrade);toast(r.message);renderResearch();updateUI()})}
function restart(){for(const v of unitVisuals.values()){scene.remove(v.mesh);disposeObject(v.mesh);v.label.remove()}unitVisuals.clear();for(const fx of effects){scene.remove(fx.mesh);if(fx.mesh.geometry!==smallSphere)fx.mesh.geometry.dispose();fx.mesh.material.dispose()}effects.length=0;selected.clear();game.reset($('difficulty').value);paused=false;modalPaused=false;targetMode=null;moveMode=false;speed=1;zoom=1;pan={x:0,z:0};$('speed').textContent='1×';$('pause').textContent='Ⅱ';$('onboarding').style.display='flex';$('onboarding').hidden=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());resize();updateTargetHint();updateUI();toast('新的战役已就绪')}
function showResult(won){targetMode=null;moveMode=false;updateTargetHint();$('result-kicker').textContent=won?'MISSION COMPLETE':'DEFENSE BREACHED';$('result-title').textContent=won?'防线坚不可摧':'防线已被突破';$('result-icon').textContent=won?'✳':'◇';$('result-icon').style.color=won?'var(--lime)':'var(--pink)';$('result-description').textContent=won?'所有病原体已被清除。你的细胞军团守护了这片微观世界。':'组织核心失去活性。尝试让巨噬细胞承担伤害，用辅助 T 细胞维持防线，并尽早占领营养节点。';$('result-stats').innerHTML=`<div><strong>${game.wave}/8</strong><span>抵御波次</span></div><div><strong>${game.kills}</strong><span>清除病原体</span></div><div><strong>${timeLabel(game.time)}</strong><span>防御时长</span></div>`;openDialog('result-dialog');beep(won?880:110,.6,'triangle');try{const old=JSON.parse(localStorage.getItem('microfront-record')||'{}');if(won||game.kills>(old.kills||0))localStorage.setItem('microfront-record',JSON.stringify({won,kills:game.kills,wave:game.wave,time:game.time}))}catch{}}
$('next-wave').onclick=()=>{const r=game.startWave();if(!r.ok)toast(r.message);updateUI()};$('select-all').onclick=selectAll;$('hold').onclick=hold;$('retreat').onclick=retreat;$('move-mode').onclick=()=>{if(!selected.size){toast('请先选择细胞');return}moveMode=!moveMode;targetMode=null;updateTargetHint()};$('pause').onclick=pause;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';beep(600)};$('help').onclick=()=>openDialog('help-dialog');$('research-open').onclick=()=>openDialog('research-dialog');$('settings-open').onclick=()=>openDialog('settings-dialog');$('restart').onclick=restart;$('play-again').onclick=restart;$('dismiss-tip').onclick=()=>{$('onboarding').style.display='none'};$('sound').onclick=()=>{soundEnabled=!soundEnabled;$('sound').style.color=soundEnabled?'var(--lime)':'';$('sound').setAttribute('aria-label',soundEnabled?'关闭音效':'开启音效');$('sound').title=soundEnabled?'关闭音效':'开启音效';beep(640);toast(soundEnabled?'战场音效已开启':'战场音效已关闭')};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{modalPaused=!!document.querySelector('dialog[open]')}));
function timeLabel(n){return`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`}
function updateUI(){const hp=game.core.hp/game.core.maxHp;$('atp').textContent=Math.floor(game.atp);$('income').textContent=`+${game.income} / 秒`;$('population').innerHTML=`${game.units.length}<span> / ${game.capacity}</span>`;$('clock').textContent=timeLabel(game.time);$('health-text').textContent=Math.ceil(hp*100)+'%';$('health-bar').style.width=(hp*100)+'%';$('health-bar').style.background=hp<.3?'#e9788b':'';$('wave-fraction').textContent=`${String(game.wave).padStart(2,'0')} / 08`;$('kills').textContent=game.kills+' 消灭';const next=$('next-wave');if(game.phase==='prepare'){$('wave-title').textContent='战前部署';$('wave-detail').textContent='第一波 · 细菌先锋';$('wave-timer').textContent='READY';next.innerHTML='<span class="play-icon">▷</span> 开始防御 <kbd>↵</kbd>';next.disabled=false}else if(game.phase==='battle'){$('wave-title').textContent=WAVES[game.wave-1].name;$('wave-detail').textContent=`${game.enemies.length} 个在场 · ${game.spawnQueue.length} 个接近中`;$('wave-timer').textContent=paused?'PAUSED':'INCOMING';next.innerHTML='<span class="play-icon">◈</span> 防御进行中';next.disabled=true}else if(game.phase==='break'){$('wave-title').textContent='重新部署';$('wave-detail').textContent=`下一波 · ${WAVES[game.wave].name}`;$('wave-timer').textContent=Math.ceil(game.breakTimer)+' s';next.innerHTML='<span class="play-icon">▷</span> 立即迎敌 <kbd>↵</kbd>';next.disabled=false}else{$('wave-title').textContent=game.phase==='won'?'战役胜利':'战役结束';$('wave-timer').textContent='END';next.disabled=true}
 $('wave-dots').querySelectorAll('i').forEach((el,i)=>{el.className=i<game.wave-1||game.phase==='won'?'done':i===game.wave-1?'active':''});document.querySelectorAll('.cell-card').forEach(el=>{const t=el.dataset.type;el.querySelector('.count').textContent='× '+game.units.filter(u=>u.type===t).length;el.classList.toggle('unaffordable',game.atp<CELLS[t].cost);el.disabled=['won','lost'].includes(game.phase)});$('queue-status').textContent=game.queue.length?`分化中：${CELLS[game.queue[0].type].name} ${Math.ceil(game.queue[0].remaining)}s · 队列 ${game.queue.length}`:'点击招募 · 核心附近集结';
 const squad=getSelection();$('selected-count').textContent=squad.length+' 已选择';if(squad.length){const types=[...new Set(squad.map(u=>u.type))];const life=squad.reduce((n,u)=>n+u.hp,0)/squad.reduce((n,u)=>n+u.maxHp,0);$('selected-info').innerHTML=`<div class="selected-summary"><span class="squad-icon">◈</span><div><strong>${types.length===1?CELLS[types[0]].name:'混合细胞编队'} × ${squad.length}</strong><p>生命 ${Math.ceil(life*100)}% · ${squad.every(u=>u.hold)?'原地驻守':squad.some(u=>u.order)?'执行指令':'自动迎击'}</p></div></div>`}else $('selected-info').innerHTML='<div class="selection-empty">⌖<strong>等待指挥</strong><p>单击细胞或拖拽框选部队</p></div>';
 document.querySelectorAll('.ability').forEach(el=>{const type=el.dataset.ability,cd=game.cooldowns[type];el.classList.toggle('active',targetMode===type);el.querySelector('.ability-cost').textContent=cd>0?Math.ceil(cd)+' s':'ϟ '+ABILITIES[type].cost;el.disabled=cd>0||['won','lost'].includes(game.phase)});$('research-level').textContent=Object.values(game.research).reduce((a,b)=>a+b,0)+' / 9';$('difficulty-label').textContent={easy:'休闲战役',normal:'标准战役',hard:'危机战役'}[game.difficulty];
}
// Direct manipulation: click, shift-click, marquee, touch orders, right-click focus fire.
const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let pointerDown=null;
function worldPoint(e){const rect=canvas.getBoundingClientRect();ndc.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(ndc,camera);const hit=new THREE.Vector3();return raycaster.ray.intersectPlane(plane,hit)}
function screenPos(x,y,z){const v=new THREE.Vector3(x,y,z).project(camera);return{x:(v.x+1)*canvas.clientWidth/2,y:(1-v.y)*canvas.clientHeight/2}}
function pick(e,team){const rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top;let best=null,dmin=Infinity;for(const u of team==='ally'?game.units:game.enemies){const pos=screenPos(u.x,u.size*.8,u.z),d=Math.hypot(pos.x-px,pos.y-py),radius=Math.max(e.pointerType==='touch'?22:13,u.size*canvas.clientHeight/(52/zoom)*1.5);if(d<radius&&d<dmin){best=u;dmin=d}}return best}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(e.button===2){const p=worldPoint(e);if(p)doCommand(p,pick(e,'enemy'));return}pointerDown={x:e.clientX,y:e.clientY,button:e.button,shift:e.shiftKey,pan:{...pan},moved:false};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{const p=worldPoint(e);if(p)targetCircle.position.set(p.x,.2,p.z);if(!pointerDown)return;const dx=e.clientX-pointerDown.x,dy=e.clientY-pointerDown.y;if(Math.hypot(dx,dy)>5)pointerDown.moved=true;if(pointerDown.button===1){const scale=55/canvas.clientHeight/zoom;pan.x=pointerDown.pan.x-(dx*.8+dy*.6)*scale;pan.z=pointerDown.pan.z+(dx*.6-dy*.8)*scale;clampPan();updateCamera();return}if(pointerDown.button===0&&pointerDown.moved&&e.pointerType!=='touch'){const rect=canvas.getBoundingClientRect(),b=$('drag-box');b.style.display='block';b.style.left=Math.min(pointerDown.x,e.clientX)-rect.left+'px';b.style.top=Math.min(pointerDown.y,e.clientY)-rect.top+'px';b.style.width=Math.abs(dx)+'px';b.style.height=Math.abs(dy)+'px'}});
canvas.addEventListener('pointerup',e=>{if(!pointerDown)return;const down=pointerDown;pointerDown=null;$('drag-box').style.display='none';if(down.button!==0)return;const p=worldPoint(e);if(!p)return;if(targetMode){const r=game.cast(targetMode,p);toast(r.message);if(r.ok)targetMode=null;updateTargetHint();updateUI();return}if(moveMode){doCommand(p,pick(e,'enemy'));return}if(down.moved&&e.pointerType!=='touch'){if(!down.shift)selected.clear();const rect=canvas.getBoundingClientRect();for(const u of game.units){const s=screenPos(u.x,u.size,u.z),x=s.x+rect.left,y=s.y+rect.top;if(x>=Math.min(down.x,e.clientX)&&x<=Math.max(down.x,e.clientX)&&y>=Math.min(down.y,e.clientY)&&y<=Math.max(down.y,e.clientY))selected.add(u.id)}beep(570);updateUI();return}const ally=pick(e,'ally');if(ally){if(!down.shift)selected.clear();if(down.shift&&selected.has(ally.id))selected.delete(ally.id);else selected.add(ally.id);beep(560)}else if(selected.size&&e.pointerType==='touch'){doCommand(p,pick(e,'enemy'))}else if(!down.shift)selected.clear();updateUI()});
canvas.addEventListener('pointercancel',()=>{pointerDown=null;$('drag-box').style.display='none'});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom*(e.deltaY>0?.92:1.08),.65,2.1);updateCamera()},{passive:false});
function updateCamera(){target.set(pan.x,0,pan.z);camera.position.copy(target).add(camOffset);camera.lookAt(target);camera.zoom=zoom;camera.updateProjectionMatrix();camera.updateMatrixWorld()}
function clampPan(){pan.x=THREE.MathUtils.clamp(pan.x,-17,17);pan.z=THREE.MathUtils.clamp(pan.z,-17,17)}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);const span=w<430?49:55;camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;updateCamera()}
new ResizeObserver(resize).observe(field);$('zoom-in').onclick=()=>{zoom=Math.min(2.1,zoom*1.15);updateCamera()};$('zoom-out').onclick=()=>{zoom=Math.max(.65,zoom/1.15);updateCamera()};$('reset-view').onclick=()=>{zoom=1;pan={x:0,z:0};updateCamera()};
$('minimap').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();pan.x=((e.clientX-r.left)/r.width-.5)*60;pan.z=((e.clientY-r.top)/r.height-.5)*60;clampPan();updateCamera()};
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k===' ')pause();if(k==='a')selectAll();if(k==='h')hold();if(k==='r')retreat();if(k==='enter'){$('next-wave').click()}if(k==='escape'){targetMode=null;moveMode=false;selected.clear();updateTargetHint();updateUI()}if(['1','2','3','4','5'].includes(k))recruit(Object.keys(CELLS)[Number(k)-1]);if(k==='q')armAbility('heal');if(k==='w')armAbility('blast');if(k==='e')armAbility('interferon')});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();pointerDown=null;$('drag-box').style.display='none'});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.running&&!paused)pause()});
function positionLabel(el,x,y,z){const s=screenPos(x,y,z);el.style.left=s.x+'px';el.style.top=s.y+'px';el.style.display=s.x<0||s.x>canvas.clientWidth||s.y<0||s.y>canvas.clientHeight?'none':''}
function drawMinimap(){const c=$('minimap'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#24454b';ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(w*i/6,0);ctx.lineTo(w*i/6,h);ctx.moveTo(0,h*i/6);ctx.lineTo(w,h*i/6);ctx.stroke()}const point=(x,z,color,r)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc((x/60+.5)*w,(z/60+.5)*h,r,0,Math.PI*2);ctx.fill()};GATES.forEach(g=>point(g.x,g.z,'#966078',3));game.nodes.forEach(n=>point(n.x,n.z,n.owner?'#bdf285':'#d4b577',3));point(game.core.x,game.core.z,'#7aefb4',5);game.units.forEach(u=>point(u.x,u.z,selected.has(u.id)?'#e0ff97':'#68baad',1.8));game.enemies.forEach(u=>point(u.x,u.z,'#f085a2',u.type==='boss'?4:1.8));ctx.strokeStyle='#a0c2ba66';ctx.strokeRect((pan.x/60+.5)*w-30/zoom,(pan.z/60+.5)*h-22/zoom,60/zoom,44/zoom)}
let previous=performance.now();function frame(now){requestAnimationFrame(frame);const realDt=Math.min((now-previous)/1000,.05);previous=now;const dt=paused||modalPaused?0:realDt*speed;if(dt>0)game.tick(dt);const visualTime=now/1000;
 if(!modalPaused){const drift=realDt*14/zoom;if(keys.has('arrowleft'))pan.x-=drift;if(keys.has('arrowright'))pan.x+=drift;if(keys.has('arrowup'))pan.z-=drift;if(keys.has('arrowdown'))pan.z+=drift;if([...keys].some(k=>k.startsWith('arrow'))){clampPan();updateCamera()}}
 coreNucleus.rotation.y=visualTime*.2;coreGroup.children[0].scale.set(3.25*(1+Math.sin(visualTime*1.2)*.018),2.5,3.25*(1+Math.sin(visualTime*1.2)*.018));coreLight.intensity=13+Math.sin(visualTime*1.2)*2;positionLabel(coreLabel,game.core.x,6.4,game.core.z);
 for(const v of unitVisuals.values()){const u=v.u;v.mesh.position.set(u.x,0,u.z);const body=v.mesh.userData.body;body.position.y=Math.sin(visualTime*1.8+u.seed)*.085;body.rotation.y=Math.sin(visualTime*.6+u.seed)*.13;v.mesh.userData.selectRing.visible=selected.has(u.id);v.mesh.userData.selectRing.material.opacity=.7+Math.sin(visualTime*3)*.15;positionLabel(v.label,u.x,u.size*2.2+.55,u.z);v.label.style.visibility=(selected.has(u.id)||u.hp<u.maxHp||u.type==='boss')?'visible':'hidden';v.label.querySelector('i').style.width=(u.hp/u.maxHp*100)+'%';}
 for(const v of nodeVisuals){const n=game.nodes[v.i];v.crystal.rotation.y=visualTime*.5;v.crystal.position.y=1.35+Math.sin(visualTime*1.6+v.i)*.17;v.base.material.color.set(n.owner?'#bdf285':'#bba16b');positionLabel(v.label,n.x,2.9,n.z);const detail=n.owner?'已占领 · +3 ATP / s':n.progress>0?`占领中 ${Math.floor(n.progress/6*100)}%`:'未占领 · +3 ATP / s';v.label.querySelector('small').textContent=detail;v.label.style.color=n.owner?'#c4f58b':'#e3cf99'}
 for(const v of gateVisuals){positionLabel(v.label,GATES[v.i].x,1.5,GATES[v.i].z);const active=game.phase==='battle'&&WAVES[game.wave-1].gates.includes(v.i);v.r.material.opacity=active?.55+Math.sin(visualTime*3)*.25:.22;v.group.children[2].scale.y=.6+(active?Math.sin(visualTime*3)*.13:0)}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i],delta=dt||(['won','lost'].includes(game.phase)?realDt:0);e.life-=delta;const p=1-e.life/e.total;if(e.type==='pulse'){e.mesh.scale.setScalar(.5+p*e.radius/.7);e.mesh.material.opacity=(1-p)*.65}else if(e.type==='shot'){e.mesh.position.set(THREE.MathUtils.lerp(e.from.x,e.to.x,p),1+Math.sin(p*Math.PI)*.5,THREE.MathUtils.lerp(e.from.z,e.to.z,p))}else if(e.type==='burst'){const a=e.mesh.geometry.attributes.position;for(let j=0;j<a.count;j++){a.setXYZ(j,a.getX(j)+e.velocity[j*3]*delta,a.getY(j)+e.velocity[j*3+1]*delta,a.getZ(j)+e.velocity[j*3+2]*delta)}a.needsUpdate=true;e.mesh.material.opacity=1-p}else if(e.type==='warning'){e.mesh.position.set(e.unit.x,.18,e.unit.z);e.mesh.material.opacity=.3+Math.sin(visualTime*14)*.3}else if(e.type==='zone'){e.mesh.material.opacity=.3+Math.sin(visualTime*2)*.15}if(e.life<=0){scene.remove(e.mesh);if(e.mesh.geometry!==smallSphere)e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}
 renderer.render(scene,camera);if(now-lastUI>160){updateUI();drawMinimap();lastUI=now}}
resize();updateUI();renderer.render(scene,camera);$('loading').style.display='none';requestAnimationFrame(frame);
// Page-scoped agent tools share the same validated commands as the interface.
const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'read_battle_state',description:'Read the current immune defense battle, resources, cell IDs and locations.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>game.snapshot()});register({name:'recruit_immune_cells',description:'Spend ATP to recruit up to five immune cells into the differentiation queue.',inputSchema:{type:'object',properties:{type:{type:'string',enum:Object.keys(CELLS)},count:{type:'integer',minimum:1,maximum:5}},required:['type','count'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!CELLS[input.type]||!Number.isInteger(input.count)||input.count<1||input.count>5)throw new Error('Invalid cell type or count');const results=[];for(let i=0;i<input.count;i++){const r=game.recruit(input.type);results.push(r);if(!r.ok)break}updateUI();return{results,atp:Math.floor(game.atp),queue:game.queue.length}}});register({name:'command_immune_cells',description:'Move selected cell IDs to a battlefield coordinate. Coordinates range from -24 to 24.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'integer'},minItems:1},x:{type:'number',minimum:-24,maximum:24},z:{type:'number',minimum:-24,maximum:24}},required:['ids','x','z'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Array.isArray(input.ids)||!input.ids.every(Number.isInteger)||!Number.isFinite(input.x)||!Number.isFinite(input.z)||Math.abs(input.x)>24||Math.abs(input.z)>24)throw new Error('Invalid orders');const result=game.command(input.ids,input);updateUI();return result}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
