import * as THREE from './vendor/three.module.min.js';
import {DreamGame,CHAPTERS} from './engine.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const game=new DreamGame();let started=Date.now(),busy=false,swapping=false,sound=false,audioCtx,drone,gain,timer,elapsed=0;
const colors={mint:0x94efd8,gold:0xf3d194,purple:0xbca2fa,stone:0x324a5b};
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('#scene').innerHTML='<p style="padding:100px 40px;color:#bdded8">当前浏览器无法启动 3D 场景。请开启硬件加速，或使用支持 WebGL 的浏览器。</p>';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#scene').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x111b2c,.018);
const camera=new THREE.PerspectiveCamera(35,1,.1,160);let azimuth=.68,elevation=.79,distance=35;
const target=new THREE.Vector3(0,-.25,0);const cameraUpdate=()=>{camera.position.set(Math.sin(azimuth)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(azimuth)*Math.cos(elevation)*distance);camera.lookAt(target)};cameraUpdate();
scene.add(new THREE.HemisphereLight(0xbcd6f4,0x182c3a,2.4));const moonlight=new THREE.DirectionalLight(0xc5dfed,3.3);moonlight.position.set(-8,16,8);moonlight.castShadow=true;moonlight.shadow.mapSize.set(2048,2048);Object.assign(moonlight.shadow.camera,{left:-16,right:16,top:16,bottom:-16});moonlight.shadow.bias=-.001;scene.add(moonlight);
const mintlight=new THREE.PointLight(0x56eacb,28,22);mintlight.position.set(3,6,3);scene.add(mintlight);const purplelight=new THREE.PointLight(0xa787ff,45,25);purplelight.position.set(-7,5,-7);scene.add(purplelight);
const board=new THREE.Group();scene.add(board);const roomGroups=[],pickables=[],decorations=[],bridges=new THREE.Group();board.add(bridges);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.08,...opts});
const stone=mat(0x344d60),topstone=mat(0x405a69),darkstone=mat(0x20374a),bright=mat(colors.mint,{emissive:colors.mint,emissiveIntensity:.55}),gold=mat(colors.gold,{emissive:0xd79e51,emissiveIntensity:.55}),purple=mat(colors.purple,{emissive:0x9670ef,emissiveIntensity:.8});
function box(w,h,d,m,x=0,y=0,z=0,parent=board){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function ring(radius,tube,m,parent,x=0,y=0,z=0){const mesh=new THREE.Mesh(new THREE.TorusGeometry(radius,tube,8,56),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh}
function label(n){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.font='24px monospace';ctx.fillStyle='#aec4cf';ctx.textAlign='center';ctx.fillText(String(n+1).padStart(2,'0'),64,39);const texture=new THREE.CanvasTexture(c);const m=new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,opacity:.5});const p=new THREE.Mesh(new THREE.PlaneGeometry(.65,.325),m);p.rotation.x=-Math.PI/2;p.position.set(1.53,.065,1.55);return p}
const shards=new Map(),portals=[];let exitGroup,keyGroup,selection;
function disposeGroup(group){group.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(![stone,topstone,darkstone,bright,gold,purple].includes(o.material)){o.material.map?.dispose();o.material.dispose()}}});}
function build(){for(const r of roomGroups){board.remove(r);disposeGroup(r)}roomGroups.length=0;pickables.length=0;decorations.length=0;shards.clear();portals.length=0;exitGroup=null;keyGroup=null;
 game.rooms.forEach(room=>{const g=new THREE.Group();g.userData.id=room.id;roomGroups.push(g);board.add(g);const x=(room.pos%3-1)*5.1,z=(Math.floor(room.pos/3)-1)*5.1;g.position.set(x,0,z);
 const base=box(4.3,.95,4.3,darkstone,0,-.65,0,g);base.userData.room=room.id;pickables.push(base);const floor=box(4.32,.16,4.32,topstone,0,-.095,0,g);floor.userData.room=room.id;pickables.push(floor);
 box(4.02,.15,4.02,stone,0,-1.16,0,g);box(3.8,.16,3.8,darkstone,0,-1.3,0,g);
 const edge=new THREE.LineSegments(new THREE.EdgesGeometry(floor.geometry),new THREE.LineBasicMaterial({color:0x8cbbc1,transparent:true,opacity:.16}));edge.position.copy(floor.position);g.add(edge);
 for(let i=-1;i<=1;i++){box(.014,.01,4.25,darkstone,i*1.07,.005,0,g);box(4.25,.01,.014,darkstone,0,.005,i*1.07,g)}
 const rotating=new THREE.Group();g.add(rotating);g.userData.rotating=rotating;rotating.rotation.y=-room.rot*Math.PI/2;
 for(let d=0;d<4;d++){const a=d*Math.PI/2,dx=Math.sin(a),dz=-Math.cos(a);if(room.doors.includes(d)){const p=box(.40,.025,2.05,bright,dx*1.02,.035,dz*1.02,rotating);p.rotation.y=-a;for(const side of [-1,1]){const px=dx*1.92+Math.cos(a)*.58*side,pz=dz*1.92+Math.sin(a)*.58*side;box(.15,.46,.15,stone,px,.21,pz,rotating);box(.10,.06,.10,bright,px,.47,pz,rotating)}}else{const wall=box(3.8,.4,.21,stone,dx*2,.15,dz*2,rotating);wall.rotation.y=-a;}}
 box(.7,.03,.7,bright,0,.04,0,rotating).rotation.y=Math.PI/4;
 // Weathered corners form an open architectural room, preserving sightlines.
 for(const [cx,cz] of [[-1.85,-1.85],[1.85,-1.85],[-1.85,1.85],[1.85,1.85]]){const tall=(room.id+Math.round(cx+cz+4))%3===0;box(.38,tall?1.15:.57,.38,stone,cx,tall?.51:.22,cz,rotating);box(.47,.13,.47,topstone,cx,tall?1.11:.54,cz,rotating)}
 g.add(label(room.id));
 if(game.config.shards.includes(room.id)){const sg=new THREE.Group();g.add(sg);sg.position.y=1.2;const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.31,0),purple);sg.add(crystal);const halo=ring(.56,.012,purple,sg);halo.rotation.x=Math.PI/2;halo.position.y=-.61;shards.set(room.id,sg);decorations.push({object:sg,base:1.2,speed:1.4,offset:room.id});const l=new THREE.PointLight(colors.purple,2.5,3);l.position.y=.3;sg.add(l)}
 if(game.config.exit===room.id){exitGroup=new THREE.Group();g.add(exitGroup);exitGroup.position.set(0,0,-.3);box(.33,2.4,.38,stone,-.93,1.18,0,exitGroup);box(.33,2.4,.38,stone,.93,1.18,0,exitGroup);box(2.3,.32,.45,topstone,0,2.45,0,exitGroup);box(.075,2.12,.09,gold,-.71,1.18,.23,exitGroup);box(.075,2.12,.09,gold,.71,1.18,.23,exitGroup);box(1.48,.075,.09,gold,0,2.24,.23,exitGroup);const veil=new THREE.Mesh(new THREE.PlaneGeometry(1.35,2.05),new THREE.MeshBasicMaterial({color:colors.gold,transparent:true,opacity:.14,side:THREE.DoubleSide,depthWrite:false}));veil.position.set(0,1.17,0);exitGroup.add(veil);exitGroup.userData.veil=veil;for(let j=0;j<3;j++)box(2.3-j*.2,.12,1.1-j*.2,stone,0,j*.12,.65-j*.2,exitGroup);const e=ring(.21,.018,gold,exitGroup,0,2.8,0);e.rotation.z=Math.PI/4;const light=new THREE.PointLight(colors.gold,4,7);light.position.set(0,1.6,0);exitGroup.add(light)}
 if(game.config.key===room.id){keyGroup=new THREE.Group();g.add(keyGroup);const r=ring(.19,.055,gold,keyGroup,0,1.2,0);box(.06,.48,.06,gold,0,.85,0,keyGroup);box(.16,.065,.06,gold,.05,.69,0,keyGroup);decorations.push({object:keyGroup,base:0,speed:1.8,offset:0})}
 if(game.config.portals?.includes(room.id)){const p=ring(.74,.045,purple,g,0,.9,-.65);portals.push(p);ring(.87,.011,purple,g,0,.9,-.65)}
 if(room.id===3||room.id===5){const arch=new THREE.Group();g.add(arch);arch.position.set(-1.25,0,-1.3);box(.24,1.5,.24,stone,-.32,.75,0,arch);box(.24,1.5,.24,stone,.32,.75,0,arch);box(.95,.2,.3,stone,0,1.55,0,arch)}
 });
 if(selection)board.remove(selection);selection=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(4.53,.08,4.53)),new THREE.LineBasicMaterial({color:colors.mint,transparent:true,opacity:.85}));board.add(selection);updateScene();const p=roomGroups[game.player].position;traveler.position.set(p.x,.18,p.z);}
const traveler=new THREE.Group();scene.add(traveler);
const cloak=mat(0xd5f5ea,{emissive:0x6fa99b,emissiveIntensity:.18});const robe=new THREE.Mesh(new THREE.ConeGeometry(.25,.66,7),cloak);robe.position.y=.48;traveler.add(robe);const head=new THREE.Mesh(new THREE.SphereGeometry(.19,16,12),cloak);head.position.y=.88;traveler.add(head);const face=box(.15,.08,.1,mat(0x173b43),0,.89,.15,traveler);box(.065,.25,.075,stone,-.1,.07,0,traveler);box(.065,.25,.075,stone,.1,.07,0,traveler);const aura=ring(.44,.017,bright,traveler,0,.01,0);aura.rotation.x=-Math.PI/2;const lamp=new THREE.PointLight(colors.mint,4,4);lamp.position.y=1;traveler.add(lamp);const scarf=box(.09,.35,.05,bright,.19,.53,-.12,traveler);scarf.rotation.z=-.3;
// A quiet field of distant stars and suspended fragments.
let seed=173;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};const starPositions=[];for(let i=0;i<700;i++)starPositions.push((rand()-.5)*110,(rand()-.25)*65,(rand()-.5)*100);const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0x9ec8d8,size:.044,transparent:true,opacity:.6}));scene.add(stars);
const debris=new THREE.Group();scene.add(debris);for(let i=0;i<38;i++){const angle=rand()*Math.PI*2,r=11+rand()*13,s=.08+rand()*.35;const m=box(s,s*(1+rand()*2),s,darkstone,Math.cos(angle)*r,-2-rand()*7,Math.sin(angle)*r,debris);m.rotation.set(rand()*2,rand()*2,rand()*2)}
const moon=new THREE.Mesh(new THREE.SphereGeometry(1.15,32,24),mat(0x99c5d0,{emissive:0x577c92,emissiveIntensity:.5}));moon.position.set(-11,5,-13);scene.add(moon);const moonRing=ring(1.75,.01,new THREE.MeshBasicMaterial({color:0x6a92a9,transparent:true,opacity:.4}),scene,-11,5,-13);moonRing.rotation.set(.8,.2,.3);
const floorMist=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshBasicMaterial({color:0x0b1423,transparent:true,opacity:.35,side:THREE.DoubleSide}));floorMist.rotation.x=-Math.PI/2;floorMist.position.y=-5;scene.add(floorMist);
function updateScene(){for(const r of game.rooms){const g=roomGroups[r.id];g.userData.targetRotation=-r.rot*Math.PI/2;g.userData.targetX=(r.pos%3-1)*5.1;g.userData.targetZ=(Math.floor(r.pos/3)-1)*5.1;g.userData.inactive=!game.isActive(r.id);g.traverse(o=>{if(o.isMesh&&o.material){if(!o.userData.originalMaterial)o.userData.originalMaterial=o.material;if(g.userData.inactive){if(!o.userData.ghostMaterial)o.userData.ghostMaterial=o.material.clone();o.userData.ghostMaterial.transparent=true;o.userData.ghostMaterial.opacity=.22;o.material=o.userData.ghostMaterial}else o.material=o.userData.originalMaterial}});}
 for(const [id,s] of shards)s.visible=!game.collected.includes(id);if(keyGroup)keyGroup.visible=!game.key;
 while(bridges.children.length){const c=bridges.children[0];bridges.remove(c);c.geometry.dispose()}
 for(const r of game.rooms){for(const n of game.neighbors(r.id)){if(n<r.id)continue;const a=game.rooms[r.id].pos,b=game.rooms[n].pos;const x=((a%3+b%3)/2-1)*5.1,z=((Math.floor(a/3)+Math.floor(b/3))/2-1)*5.1;const horizontal=Math.floor(a/3)===Math.floor(b/3);box(horizontal?.88:.44,.08,horizontal?.44:.88,bright,x,-.04,z,bridges);}}
 if(exitGroup)exitGroup.userData.veil.material.opacity=game.collected.length===game.config.shards.length?.65:.14;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4400)}
function tone(freq=440){if(!sound||!audioCtx)return;const osc=audioCtx.createOscillator(),vol=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;vol.gain.setValueAtTime(.08,audioCtx.currentTime);vol.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.65);osc.connect(vol);vol.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.7)}
function updateUI(){const c=game.config;$('#chapter-num').textContent=String(game.level+1).padStart(2,'0');$('#chapter-title').textContent=c.name;$('#chapter-sub').textContent=c.sub;$('#intro').textContent=c.intro;$('#moves').textContent=String(game.moves).padStart(2,'0');$('#shard-count').textContent=`${game.collected.length} / ${c.shards.length}`;$('#shard-track').innerHTML=c.shards.map((s,i)=>`<span class="${i<game.collected.length?'found':''}"></span>`).join('');$('#phase').disabled=!c.phase;$('#swap').disabled=!c.swap;$('#undo').disabled=!game.history.length;$('#portal').hidden=!c.portals?.includes(game.player);$('#portal').style.display=$('#portal').hidden?'none':'flex';$('#phase-label').textContent=game.phase?'月影梦境':'浅层梦境';$('#world-label').textContent=game.phase?'SHADOW REALM':'LUCID REALM';document.body.classList.toggle('phase-night',!!game.phase);$('#phase').classList.toggle('active',!!game.phase);$('#swap').classList.toggle('active',swapping);$$('[data-level]').forEach(b=>b.classList.toggle('active',+b.dataset.level===game.level));
 $('#room-code').textContent=`ROOM ${String(game.selected+1).padStart(2,'0')}`;
 let name='浮光回廊',desc='旋转房间，让两端的光路连接相邻空间。';if(game.selected===c.start){name='旅人的起点';desc='一切始于微光，归途就在房间之间。'}if(c.shards.includes(game.selected)){name='记忆的容器';desc=game.collected.includes(game.selected)?'这里的记忆已被找回。':'一枚记忆碎片正在等待。沿连接的光路来到这里。'}if(c.spectral?.includes(game.selected)){name='月影之间';desc='只在月影相位中存在的房间。按 F 唤醒它。'}if(c.portals?.includes(game.selected)){name='回声之门';desc='走进这里，再点击「传送」跃迁到另一扇紫色门。'}if(c.key===game.selected){name='封印的钥匙';desc=game.key?'封印已解除，金色出口可以通行。':'走进这个房间，拾取通往出口的钥匙。'}if(c.exit===game.selected){name='醒来的门';desc='找回全部记忆碎片，再踏入金色的门。'}$('#room-name').textContent=name;$('#room-desc').textContent=desc;$('#room-tags').innerHTML=`<span>可旋转</span>${game.selected===game.player?'<span>旅人所在</span>':game.path(game.selected)?'<span>光路已连通</span>':'<span>光路未连通</span>'}`;$('#exit-title').textContent=game.collected.length===c.shards.length?'出口已苏醒':'找到梦境出口';$('#exit-detail').textContent=c.key!==undefined&&!game.key?'需要钥匙解除出口封印':game.collected.length===c.shards.length?'沿光路走向金色的门':'集齐碎片后，通向醒来的门将开启';$('#exit-lock').textContent=game.collected.length===c.shards.length?'✧':'⌑';}
function sync(){updateScene();updateUI()}
function select(id){if(busy||game.won)return;if(swapping){if(game.swap(id)){swapping=false;sync();tone(390);toast('空间已重新拼接。旅人与物品随房间一起移动。')}else toast('请选择与当前房间上下或左右相邻的房间。');return}game.selected=id;updateUI();tone(240+id*17)}
function rotate(n){if(busy||game.won)return;game.rotate(n);sync();tone(320)}
const ease=t=>t*t*(3-2*t);let walkAnimation=null;
async function walk(){if(busy||game.won)return;const result=game.move(game.selected);if(!result.ok){toast(result.message);tone(150);return}busy=true;updateUI();for(const id of result.path.slice(1)){await new Promise(resolve=>{walkAnimation={from:traveler.position.clone(),to:new THREE.Vector3(roomGroups[id].userData.targetX,.18,roomGroups[id].userData.targetZ),start:performance.now(),resolve}});tone(420+id*22)}busy=false;sync();toast(result.message);if(result.gained)tone(780);if(game.won)finish()}
function finish(){elapsed=Math.floor((Date.now()-started)/1000);$('#win-text').textContent=game.level===2?'遗失的记忆已全部归来。这一次，你终于带着完整的自己醒来。':`「${game.config.name}」中的记忆已经找回。更深处的梦境正在等待。`;$('#win-stats').textContent=`${game.moves} 步  ·  ${formatTime(elapsed)}  ·  ${game.collected.length} 枚记忆`;$('#next').textContent=game.level===2?'重新开启旅程':'进入下一重梦境';setTimeout(()=>$('#complete').showModal(),650);try{localStorage.setItem('oneira-completed',String(Math.max(game.level+1,+(localStorage.getItem('oneira-completed')||0))))}catch{}}
function load(level){if(busy)return;game.load(level);started=Date.now();elapsed=0;swapping=false;build();updateUI();toast(game.config.mechanic);$('#complete').close();}
function hint(){const c=game.config;let goal=c.shards.find(id=>!game.collected.includes(id));if(goal===undefined)goal=c.key!==undefined&&!game.key?c.key:c.exit;const path=game.path(goal);if(path){game.selected=goal;updateUI();toast(`光路已接通！前往 ${String(goal+1).padStart(2,'0')} 号房间${goal===c.exit?'抵达出口':'找回目标'}。`);return}if(!game.isActive(game.player)){toast('旅人位于虚影房间。按 F 切换到月影相位后再行走。');return}const a=game.rooms[game.player].pos,b=game.rooms[goal].pos;let dir=a%3!==b%3?(a%3<b%3?1:3):(a<b?2:0);const next=game.roomAt(game.neighbor(a,dir));game.selected=next.id;updateUI();toast(`目标在 ${goal+1} 号房间。先将 ${game.player+1} 号光路朝${['上','右','下','左'][dir]}，再将 ${next.id+1} 号光路朝${['下','左','上','右'][dir]}。${!game.isActive(next.id)?'并切换至月影相位。':''}`)}
$('#rotate-left').onclick=()=>rotate(-1);$('#rotate-right').onclick=()=>rotate(1);$('#walk').onclick=walk;$('#phase').onclick=()=>{if(busy)return;if(game.shift()){sync();tone(game.phase?220:440);toast(game.phase?'月影浮现。虚影房间已成为真实的通路。':'回到浅层梦境。部分房间重新隐入月影。')}};$('#swap').onclick=()=>{if(busy||game.won)return;swapping=!swapping;updateUI();toast(swapping?'拼接模式：点击一个相邻房间，与选中房间交换位置。':'已退出拼接模式。')};$('#portal').onclick=()=>{if(busy)return;if(game.teleport()){sync();tone(880);toast('回声折叠了距离，你已穿过传送门。')}};$('#undo').onclick=()=>{if(busy)return;if(game.undo()){swapping=false;sync();toast('时间回溯。上一步已撤销。')}};$('#restart').onclick=()=>load(game.level);$('#hint').onclick=hint;$('#help').onclick=()=>$('#guide').showModal();$('.close-dialog').onclick=()=>$('#guide').close();$('.close-guide').onclick=()=>$('#guide').close();$('#next').onclick=()=>load((game.level+1)%3);$('#replay').onclick=()=>load(game.level);$$('[data-level]').forEach(b=>b.onclick=()=>load(+b.dataset.level));
$('#sound').onclick=async()=>{try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=0;gain.connect(audioCtx.destination);[110,164.81,220,277.18].forEach((freq,i)=>{const o=audioCtx.createOscillator();o.frequency.value=freq;o.type='sine';const g=audioCtx.createGain();g.gain.value=.018/(i+1);o.connect(g);g.connect(gain);o.start()})}await audioCtx.resume();sound=!sound;gain.gain.setTargetAtTime(sound?1:0,audioCtx.currentTime,.6);$('.off-slash').style.display=sound?'none':'block';$('#sound').setAttribute('aria-label',sound?'关闭环境音':'开启环境音');$('#sound').title=sound?'关闭环境音':'开启环境音';tone(550)}catch{toast('当前浏览器暂不支持环境音。')}};
$('#zoom-in').onclick=()=>{distance=Math.max(19,distance-2);cameraUpdate()};$('#zoom-out').onclick=()=>{distance=Math.min(49,distance+2);cameraUpdate()};$('#view-reset').onclick=()=>{azimuth=.68;elevation=.79;distance=innerWidth<760?37:35;cameraUpdate()};
window.addEventListener('keydown',e=>{if($('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey)return;const actions={q:()=>rotate(-1),e:()=>rotate(1),z:()=>$('#undo').click(),f:()=>$('#phase').click(),x:()=>$('#swap').click(),h:hint,Enter:walk};const fn=actions[e.key.toLowerCase()]||actions[e.key];if(fn){e.preventDefault();fn()}});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null,lastClick=0,lastId=-1;
renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(drag.moved){azimuth-=dx*.006;elevation=THREE.MathUtils.clamp(elevation+dy*.004,.35,1.35);cameraUpdate()}drag.lastX=e.clientX;drag.lastY=e.clientY});
renderer.domElement.addEventListener('pointerup',e=>{if(!drag)return;const moved=drag.moved;drag=null;if(moved)return;const bounds=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(pickables)[0];if(hit){const id=hit.object.userData.room;if(!swapping&&lastId===id&&performance.now()-lastClick<360){select(id);walk();lastClick=0}else{select(id);lastClick=performance.now();lastId=id}}});renderer.domElement.addEventListener('pointercancel',()=>drag=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.025,19,49);cameraUpdate()},{passive:false});
function resize(){const {width,height}=$('#scene').getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('#scene'));if(innerWidth<760)distance=37;cameraUpdate();
const formatTime=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;setInterval(()=>{if(!game.won){elapsed=Math.floor((Date.now()-started)/1000);$('#time').textContent=formatTime(elapsed)}},1000);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let lastFrame=0;
function render(now){requestAnimationFrame(render);const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;const k=1-Math.exp(-dt*11);for(const g of roomGroups){g.position.x=THREE.MathUtils.lerp(g.position.x,g.userData.targetX,k);g.position.z=THREE.MathUtils.lerp(g.position.z,g.userData.targetZ,k);const rr=g.userData.rotating;let delta=g.userData.targetRotation-rr.rotation.y;delta=Math.atan2(Math.sin(delta),Math.cos(delta));rr.rotation.y+=delta*k;g.position.y=g.userData.inactive?-.18:0;}if(selection){const g=roomGroups[game.selected];selection.position.set(g.position.x,.05,g.position.z);selection.material.opacity=.6+(reduced?0:Math.sin(now*.003)*.22)}
 if(walkAnimation){const a=walkAnimation,t=Math.min((now-a.start)/430,1);traveler.position.lerpVectors(a.from,a.to,ease(t));traveler.position.y=.18+Math.sin(t*Math.PI)*.17;traveler.rotation.y=Math.atan2(a.to.x-a.from.x,a.to.z-a.from.z);if(t>=1){walkAnimation=null;a.resolve()}}else if(!busy){const p=roomGroups[game.player].position;traveler.position.x=THREE.MathUtils.lerp(traveler.position.x,p.x,k);traveler.position.z=THREE.MathUtils.lerp(traveler.position.z,p.z,k);traveler.position.y=p.y+.18;}
 if(!reduced){for(const d of decorations){d.object.position.y=d.base+Math.sin(now*.001*d.speed+d.offset)*.12;d.object.rotation.y=now*.0004}stars.rotation.y=now*.000004;debris.rotation.y=Math.sin(now*.00006)*.03;aura.material.emissiveIntensity=1.1+Math.sin(now*.002)*.3;for(const p of portals)p.rotation.z=now*.0003;}renderer.render(scene,camera)}
build();updateUI();resize();requestAnimationFrame(render);
window.dreamGame=game;
if(document.modelContext?.registerTool){for(const tool of [{name:'read_dream_state',title:'查看梦境状态',description:'读取当前章节、房间方向、旅人位置和记忆碎片。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({level:game.level,...game.snapshot()})},{name:'rotate_dream_room',title:'旋转梦境房间',description:'选择并旋转指定房间一个直角，与界面的旋转操作相同。',inputSchema:{type:'object',properties:{room:{type:'integer',minimum:0,maximum:8},direction:{type:'integer',enum:[-1,1]}},required:['room','direction'],additionalProperties:false},execute:input=>{if(!Number.isInteger(input.room)||input.room<0||input.room>8||![-1,1].includes(input.direction)||busy||game.won)throw new Error('无效房间、方向或当前不可操作');game.selected=input.room;rotate(input.direction);return game.snapshot()}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
