export const DIRS = [[1,0],[0,1],[-1,0],[0,-1]];
export const MATERIALS = ['metal','plastic','glass'];
export const MATERIAL_NAMES = {metal:'金属',plastic:'塑料',glass:'玻璃'};
export const MACHINES = {
 belt:{name:'传送带',price:40,power:1,time:1,description:'沿箭头输送物品。旋转方向，让产线拐弯。',color:'#59676b'},
 source:{name:'废料入口',price:280,power:3,time:4.4,description:'持续送入金属、塑料与玻璃废料。',color:'#d9af68'},
 sorter:{name:'智能分拣机',price:360,power:7,time:2,description:'识别并清洁废料，让销售价值提升 25%。',color:'#b9cc8b'},
 shredder:{name:'破碎机',price:420,power:10,time:2.6,description:'将废料破碎为颗粒，得到一级再生材料。',color:'#809ead'},
 furnace:{name:'熔炼炉',price:650,power:18,time:3.4,description:'高温精炼，将材料提升至二级品质。',color:'#d58d68'},
 press:{name:'压块机',price:520,power:12,time:3,description:'压制为成品材料块，提升至三级品质。',color:'#8eae97'},
 bin:{name:'出货仓',price:220,power:2,time:.8,description:'自动销售来料并积累再生库存，用于交付订单。',color:'#a6b589'},
 solar:{name:'太阳能板',price:380,power:-35,time:0,description:'提供 35 点稳定电力，搭配储能实现昼夜供电。',color:'#718d9f'},
 remove:{name:'拆除',price:0,power:0,description:'回收设备并返还 60% 建造费用。',color:'#a89685'}
};
export const TECHS=[{id:'speed',name:'高速传动',description:'每级让全厂输送与加工速度提升 20%。',price:500,icon:'»',max:3},{id:'value',name:'精密再生',description:'每级让所有材料的销售价格提升 25%。',price:600,icon:'◇',max:3},{id:'energy',name:'低耗能驱动',description:'每级降低全厂电力需求 15%。',price:450,icon:'ϟ',max:3}];
export const MILESTONES=[{title:'循环，从这里开始',description:'一条小小的流水线，一个更绿的未来。',reward:600,tasks:[['produced',10,'回收 10 份废料'],['built',3,'建造 3 台新设备'],['upgraded',1,'升级 1 台设备']]},{title:'让绿色生意长大',description:'接通更多设备，交付第一份绿色订单。',reward:1000,tasks:[['produced',40,'累计回收 40 份废料'],['orders',1,'完成 1 笔回收订单'],['built',8,'累计建造 8 台设备']]},{title:'循环经济，小小先锋',description:'研究自动化科技，打造高效的循环工厂。',reward:1800,tasks:[['produced',100,'累计回收 100 份废料'],['researched',2,'完成 2 次科技研究'],['orders',3,'完成 3 笔回收订单']]},{title:'零废弃的未来',description:'让这座小工厂，成为绿色世界的起点。',reward:3000,tasks:[['produced',250,'累计回收 250 份废料'],['orders',6,'完成 6 笔回收订单'],['built',20,'累计建造 20 台设备']]}];
export const ORDER_TEMPLATES=[{name:'社区的绿色长椅',client:'林间社区 · 公共空间计划',need:{metal:5,plastic:3},reward:620},{name:'一面会呼吸的窗',client:'青芽建筑 · 再生玻璃采购',need:{glass:6,metal:2},reward:750},{name:'旧物的新旅程',client:'循环商店 · 环保生活系列',need:{plastic:6,glass:3},reward:800}];
export const key=(x,z)=>`${x},${z}`;
export class Game{
 constructor(save){this.money=2400;this.inventory={metal:0,plastic:0,glass:0};this.stats={produced:0,recycled:0,built:0,upgraded:0,orders:0,researched:0,earned:0};this.tech={speed:0,value:0,energy:0};this.research=1;this.milestone=0;this.orderCounts=[0,0,0];this.elapsed=0;this.cells=new Map();this.items=[];this.nextItem=1;this.events=[];if(save){this.restore(save)}else{this.seed()}}
 seed(){const initial=[['source',-5,-2,0],['belt',-4,-2,0],['belt',-3,-2,0],['sorter',-2,-2,0],['belt',-1,-2,0],['shredder',0,-2,0],['belt',1,-2,0],['furnace',2,-2,0],['belt',3,-2,1],['belt',3,-1,1],['press',3,0,1],['belt',3,1,1],['belt',3,2,2],['belt',2,2,2],['bin',1,2,2],['source',-5,2,0],['belt',-4,2,0],['shredder',-3,2,0],['belt',-2,2,0],['belt',-1,2,0],['belt',0,2,0],['solar',-4,-5,0],['solar',-2,-5,0]];initial.forEach(([type,x,z,dir])=>this.cells.set(key(x,z),{type,x,z,dir,level:1,timer:Math.random()*2}));}
 get capacity(){return 55+[...this.cells.values()].filter(c=>c.type==='solar').reduce((n,c)=>n+35*c.level,0)}
 get demand(){return Math.ceil([...this.cells.values()].reduce((n,c)=>n+Math.max(0,MACHINES[c.type].power)*(1+(c.level-1)*.2),0)*(1-.15*this.tech.energy))}
 get efficiency(){return Math.min(1,this.capacity/Math.max(1,this.demand))}
 valid(x,z){return x>=-6&&x<=6&&z>=-5&&z<=4}
 build(type,x,z,dir=0){if(!MACHINES[type]||type==='remove')return '未知设备';if(!this.valid(x,z))return '请建造在工厂地板上';if(this.cells.has(key(x,z)))return '这里已经有设备了';if(this.money<MACHINES[type].price)return '资金不足，等待出货或完成订单';this.money-=MACHINES[type].price;const cell={type,x,z,dir,level:1,timer:0};this.cells.set(key(x,z),cell);this.stats.built++;return cell}
 remove(x,z){const cell=this.cells.get(key(x,z));if(!cell)return false;this.money+=Math.floor(MACHINES[cell.type].price*.6);this.cells.delete(key(x,z));this.items=this.items.filter(i=>i.x!==x||i.z!==z);return true}
 upgrade(x,z){const c=this.cells.get(key(x,z));if(!c)return '设备不存在';if(c.level>=3)return '已达到最高等级';const price=Math.round(MACHINES[c.type].price*.7*c.level);if(this.money<price)return '升级所需资金不足';this.money-=price;c.level++;this.stats.upgraded++;return c}
 researchTech(id){const t=TECHS.find(t=>t.id===id);if(!t)return false;const level=this.tech[id];if(level>=t.max||this.research<1||this.money<t.price*(level+1))return false;this.money-=t.price*(level+1);this.tech[id]++;this.research--;this.stats.researched++;return true}
 getOrder(i){const o=ORDER_TEMPLATES[i],n=this.orderCounts[i];return {...o,need:Object.fromEntries(Object.entries(o.need).map(([m,v])=>[m,v+n*2])),reward:o.reward+n*180}}
 fulfill(i){if(!ORDER_TEMPLATES[i])return false;const o=this.getOrder(i);if(!Object.entries(o.need).every(([m,v])=>this.inventory[m]>=v))return false;Object.entries(o.need).forEach(([m,v])=>this.inventory[m]-=v);this.money+=o.reward;this.orderCounts[i]++;this.stats.orders++;this.research++;return true}
 claim(){const m=MILESTONES[this.milestone];if(!m||!m.tasks.every(([s,n])=>this.stats[s]>=n))return false;this.money+=m.reward;this.research++;this.milestone++;return true}
 tick(dt){this.elapsed+=dt;const speed=(1+.2*this.tech.speed)*this.efficiency;const occupied=new Map(this.items.map(i=>[key(i.x,i.z),i]));for(const cell of this.cells.values()){if(cell.type!=='source')continue;cell.timer+=dt*speed*(1+.3*(cell.level-1));if(cell.timer>=MACHINES.source.time&&!occupied.has(key(cell.x,cell.z))){const item={id:this.nextItem++,type:MATERIALS[Math.floor(Math.random()*3)],x:cell.x,z:cell.z,progress:0,quality:0,sorted:false};this.items.push(item);occupied.set(key(cell.x,cell.z),item);cell.timer=0;}}
 const consumed=new Set();for(const item of this.items){const c=this.cells.get(key(item.x,item.z));if(!c){consumed.add(item.id);continue;}item.progress+=dt*speed*(1+.3*(c.level-1));const duration=c.type==='source'?.3:MACHINES[c.type].time;if(item.progress<duration)continue;if(c.type==='bin'){const value=Math.round((9+item.quality*9)*(item.sorted?1.25:1)*(1+.25*this.tech.value));this.money+=value;this.stats.earned+=value;this.stats.produced++;this.stats.recycled+=6;if(item.quality>0)this.inventory[item.type]++;this.events.push({type:'sale',x:c.x,z:c.z,value,material:item.type});consumed.add(item.id);occupied.delete(key(item.x,item.z));continue;}if(c.type==='sorter')item.sorted=true;if(c.type==='shredder')item.quality=Math.max(item.quality,1);if(c.type==='furnace')item.quality=Math.max(item.quality,2);if(c.type==='press')item.quality=Math.max(item.quality,3);const [dx,dz]=DIRS[c.dir],nx=c.x+dx,nz=c.z+dz,next=this.cells.get(key(nx,nz));if(next&&next.type!=='solar'&&next.type!=='source'&&!occupied.has(key(nx,nz))){occupied.delete(key(item.x,item.z));item.fromX=item.x;item.fromZ=item.z;item.x=nx;item.z=nz;item.progress=0;occupied.set(key(nx,nz),item);}}
 this.items=this.items.filter(i=>!consumed.has(i.id));}
 serialize(){return {version:1,money:this.money,inventory:this.inventory,stats:this.stats,tech:this.tech,research:this.research,milestone:this.milestone,orderCounts:this.orderCounts,elapsed:this.elapsed,cells:[...this.cells.values()],items:this.items,nextItem:this.nextItem}}
 restore(s){if(s.version!==1||!Array.isArray(s.cells)||!s.cells.length||!Number.isFinite(s.money))throw Error('存档版本不兼容');for(const k of ['money','inventory','stats','tech','research','milestone','orderCounts','elapsed','nextItem'])if(s[k]!==undefined)this[k]=s[k];for(const c of s.cells){if(!MACHINES[c.type]||c.type==='remove'||!this.valid(c.x,c.z)||!Number.isInteger(c.dir)||c.dir<0||c.dir>3)throw Error('存档设备数据无效');this.cells.set(key(c.x,c.z),c);}this.items=(s.items||[]).filter(i=>this.cells.has(key(i.x,i.z)));}
}
