import { PoolPhysics, makeRack, COLORS } from './physics.js';
import { ClubScene } from './scene.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CLUBS=[{name:'隐巷球房',en:'THE BURROW',title:'打响你的名号',shots:18,reward:300,balls:5},{name:'蓝调丝绒',en:'BLUE VELVET',title:'穿过午夜的蓝',shots:20,reward:500,balls:7},{name:'最后一袋',en:'LAST POCKET',title:'地下球王的试炼',shots:22,reward:800,balls:9}];
const SAVE='afterhours-pool-v1';
let saved={coins:0,unlocked:0,cleared:[],best:0,highScore:0,guide:0,control:0,stamina:0,sound:false};
try{const data=JSON.parse(localStorage.getItem(SAVE));if(data&&typeof data==='object'){for(const key of ['coins','best','highScore'])if(Number.isFinite(data[key]))saved[key]=Math.max(0,Math.floor(data[key]));for(const key of ['unlocked','guide','control','stamina'])if(Number.isFinite(data[key]))saved[key]=Math.max(0,Math.min(key==='unlocked'?2:3,Math.floor(data[key])));if(Array.isArray(data.cleared))saved.cleared=data.cleared.filter(x=>Number.isInteger(x)&&x>=0&&x<=2);saved.sound=data.sound===true;}}catch{}
const persist=()=>{try{localStorage.setItem(SAVE,JSON.stringify(saved));}catch{}};
let scene, physics, mode='career', level=0, score=0, combo=0, runBest=0, shots=0, totalShots=0, potCount=0, angle=-.35, spin=0, power=.48, shotActive=false, shotPots=[], scratch=false, paused=false, ended=false, timeLeft=60, timerStarted=false, chargeStart=0, charging=false, comboReward=false, gameReady=false, settleTime=0, shotElapsed=0;
let lastTime=performance.now(), accumulator=0, toastTimer, soundContext, audioLast=0, dragging=false, orbiting=false, lastPointerX=0;
const keys=new Set();
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3100);}
function sound(kind,value=1){if(!saved.sound)return;try{soundContext??=new (window.AudioContext||window.webkitAudioContext)();if(soundContext.state==='suspended')soundContext.resume();const now=soundContext.currentTime;if(kind==='hit'&&now-audioLast<.04)return;audioLast=now;const osc=soundContext.createOscillator(),gain=soundContext.createGain();osc.connect(gain);gain.connect(soundContext.destination);const freq={hit:370,rail:180,pocket:780,shoot:110,win:660,foul:140}[kind]||440;osc.type=kind==='pocket'||kind==='win'?'sine':'triangle';osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(kind==='pocket'?1250:Math.max(40,freq*.4),now+.12);gain.gain.setValueAtTime(Math.min(.1,.055*value),now);gain.gain.exponentialRampToValueAtTime(.001,now+.16);osc.start(now);osc.stop(now+.18);}catch{}}
function showModal(html){if(charging){charging=false;setPower(.48);}keys.clear();paused=true;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();$('#pause').textContent='▷';}
function closeModal(){if($('#modal').open)$('#modal').close();paused=false;keys.clear();lastTime=performance.now();$('#pause').textContent='Ⅱ';}
$('#modal').addEventListener('cancel',e=>{e.preventDefault();if(ended){closeModal();startGame(mode,level);}else {closeModal();updateUI();}});
function closeButton(){return '<button class="modal-close" data-action="close" aria-label="关闭">×</button>';}
function setPower(p){power=Math.max(.1,Math.min(1,p));$('#power').value=String(Math.round(power*100));$('#power-value').textContent=`${Math.round(power*100)}%`;$('#power').style.background=`linear-gradient(to right,var(--lime) ${power*100}%,#344337 ${power*100}%)`;}
function updateUI(){
 const club=CLUBS[level];$('#wallet').textContent=saved.coins.toLocaleString();$('#score').textContent=String(score).padStart(4,'0');$('#multiplier').innerHTML=`×${Math.min(5,combo+1)}<small>连杆倍率</small>`;$('#shots').textContent=mode==='practice'?'∞':mode==='timed'?`${Math.ceil(timeLeft)}s`:String(Math.max(0,shots));$('#shots').classList.toggle('timer-warning',mode==='timed'&&timeLeft<=10);$('#shots-label').textContent=mode==='timed'?'剩余时间':'剩余杆数';const targetCount=mode==='practice'?14:club.balls;$('#potted').innerHTML=`${potCount}<span>/${targetCount}</span>`;$('#best').textContent=runBest;$('#mission-progress').style.width=`${Math.min(100,potCount/targetCount*100)}%`;$('#combo-check').textContent=comboReward?'✓':'○';$('#remaining-label').textContent=potCount>=targetCount?'现在可以打黑八':'先彩球 · 后黑八';$('#shoot').disabled=!gameReady||shotActive||paused||ended;$('#power').disabled=shotActive||ended;$$('[data-spin]').forEach(b=>b.disabled=shotActive||ended);$('#player-rank').textContent=['街头新秀','夜场高手','地下传奇'][saved.unlocked];$('.player-badge').textContent=['Ⅰ','Ⅱ','Ⅲ'][saved.unlocked];$('#cue-name').textContent=saved.control>0?['午夜白蜡木','暗巷枫木','丝绒乌木','夜王之杖'][saved.control]:'午夜白蜡木';$('#cue-level').textContent=`${saved.guide?'精确延长线':'标准球杆'} · LV. ${1+saved.control}`;
 if(physics)for(const b of physics.balls){const chip=$(`#ball-${b.id}`);if(chip)chip.classList.toggle('potted',!b.active);}
 if(shotActive){$('#shot-state').textContent='好戏正在发生。';$('#instruction-text').textContent='球还在滚动，看看母球会停在哪里。';$('#shot-hint').textContent='等待球停稳，再准备下一杆。';}
 else if(!ended){$('#shot-state').textContent=potCount>=targetCount?'最后一杆，收下黑八。':combo>0?`${combo} 连杆！保持你的手感。`:'轮到你了，阿奇。';$('#instruction-text').textContent=potCount>=targetCount?'彩球已清空 · 瞄准黑八，结束这一局':(matchMedia('(pointer:coarse)').matches?'轻触球台瞄准 · 调整力度后点击击球':'移动鼠标瞄准 · 按住空格蓄力，松开击球');$('#shot-hint').textContent=spin<0?'低杆：碰撞后让母球向后回撤。':spin>0?'高杆：碰撞后让母球继续跟进。':'每一杆，都为下一杆留个好位置。';}
}
function trackBalls(){const ordered=physics.balls.filter(b=>b.id>0&&b.id!==8).concat(physics.balls.filter(b=>b.id===8));$('#ball-track').innerHTML=ordered.map(b=>`<span class="ball-chip ${b.id===8?'black':''}" id="ball-${b.id}" style="--ball:${COLORS[b.id]}" title="${b.id} 号球"><b>${b.id}</b></span>`).join('');}
function startGame(nextMode=mode,nextLevel=level){
 closeModal();mode=nextMode;level=nextLevel;score=0;combo=0;runBest=0;potCount=0;totalShots=0;shotActive=false;shotPots=[];scratch=false;ended=false;paused=false;shots=CLUBS[level].shots+saved.stamina*2;timeLeft=60;timerStarted=false;comboReward=false;charging=false;settleTime=0;shotElapsed=0;spin=0;setPower(.48);angle=-.4;accumulator=0;
 physics=new PoolPhysics(makeRack(level,mode==='practice'),onPhysicsEvent);scene?.setBalls(physics.balls);scene?.setTheme(level);trackBalls();$$('[data-spin]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.spin)===0));$('#spin-label').textContent='中杆';$$('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#mode-title').innerHTML=({career:'地下球房',timed:'计时冲刺',practice:'自由练习'}[mode])+'<span class="heading-dot">.</span>';$('#run-mode').textContent={career:'生涯挑战',timed:'60 秒挑战',practice:'无限练习'}[mode];$('#chapter').textContent=String(level+1).padStart(2,'0');$('#club-subtitle').textContent=CLUBS[level].en;$('#club-name').textContent=CLUBS[level].name;$('#round-label').textContent=mode==='practice'?'练习进行中':mode==='timed'?'首杆开始计时':'挑战进行中';$('#level-progress').textContent=`0${level+1} / 03`;$('#mission-title').textContent=mode==='practice'?'把好球练成习惯':mode==='timed'?'与午夜赛跑':CLUBS[level].title;$('#mission-description').textContent=mode==='practice'?'无限杆数，完整球阵。随时重开，放心练习。':mode==='timed'?'60 秒内尽可能多地得分。清台后自动续局。':`${shots} 杆内清空彩球，最后打进黑八。`;$('#reward').textContent=mode==='practice'?'自由发挥':mode==='timed'?'◈ 得分 ÷ 10':`◈ ${CLUBS[level].reward}`;$('#tip').innerHTML=mode==='timed'?'首杆才会开始计时。<br>连续进球，让每一秒更有价值。':'高手不只看这一颗球。<br>试试低杆，把母球留在好位置。';gameReady=true;updateUI();
}
function onPhysicsEvent(event){if(event.type==='collision'){sound('hit',Math.min(1,event.speed/3));return;}if(event.type==='rail'){sound('rail',.35);return;}const b=event.ball;scene.pocketEffect(...event.pocket);if(b.id===0){scratch=true;sound('foul');toast('母球落袋 · 本杆无得分，连杆中断');return;}shotPots.push(b.id);sound('pocket');if(b.id!==8){potCount++;const value=100*Math.min(5,combo+1);$('#floating-score').textContent=`+${value}`;$('#floating-score').classList.remove('show');void $('#floating-score').offsetWidth;$('#floating-score').classList.add('show');}updateUI();}
function shoot(){if(!gameReady||paused||ended||shotActive||physics.moving())return false;if(!physics.shoot(angle,power,spin))return false;shotActive=true;shotPots=[];scratch=false;settleTime=0;shotElapsed=0;totalShots++;if(mode==='career')shots--;if(mode==='timed'){timerStarted=true;$('#round-label').textContent='倒计时进行中';}sound('shoot');updateUI();return true;}
function endShot(){
 shotActive=false;const colored=shotPots.filter(id=>id!==8).length;const remaining=physics.balls.some(b=>b.id!==0&&b.id!==8&&b.active);const black=shotPots.includes(8);const earlyBlack=black&&(remaining||shotPots.indexOf(8)<shotPots.length-1);const foul=scratch||!physics.hit||earlyBlack;
 if(!foul&&colored>0){score+=colored*100*Math.min(5,combo+1);if(physics.railCount>=2){score+=50;toast('漂亮的借库！额外 +50 分');}combo++;runBest=Math.max(runBest,combo);if(combo>=2){$('#combo-pop').textContent=`${combo} SHOT STREAK`;$('#combo-pop').classList.remove('show');void $('#combo-pop').offsetWidth;$('#combo-pop').classList.add('show');}if(combo>=3&&!comboReward){comboReward=true;score+=150;toast('三连杆挑战完成 · +150 分');}}
 else {combo=0;if(scratch||!physics.hit){score=Math.max(0,score-100);if(!scratch)toast('未击中目标球 · −100 分，连杆中断');}}
 if(scratch)physics.respot(0);
 saved.best=Math.max(saved.best,runBest);saved.highScore=Math.max(saved.highScore,score);persist();
 if(black){if(earlyBlack||scratch){if(mode==='practice'){physics.respot(8);toast('黑八提前入袋 · 已重新摆回，继续练习');}else if(mode==='timed'){score=Math.max(0,score-200);combo=0;physics.respot(8);toast('黑八犯规 · −200 分');}else{finish(false,scratch?'最后的母球也落袋了。':'黑八提前落袋了。先清彩球，再打黑八。');return;}}
 else {score+=500;if(mode==='timed'){toast('清台！+500 分 · 新一轮已摆好');physics=new PoolPhysics(makeRack(level),onPhysicsEvent);scene.setBalls(physics.balls);potCount=0;trackBalls();}else{finish(true);return;}}}
 if(mode==='career'&&shots<=0){finish(false,'杆数已经用完。换个角度，再来一局。');return;}updateUI();
}
function finish(won,reason=''){if(ended)return;ended=true;shotActive=false;charging=false;let coins=0;if(mode==='career'&&won){const first=!saved.cleared.includes(level);coins=first?CLUBS[level].reward:100;if(first)saved.cleared.push(level);saved.unlocked=Math.max(saved.unlocked,Math.min(2,level+1));}else if(mode==='timed')coins=Math.floor(score/10);saved.coins+=coins;saved.best=Math.max(saved.best,runBest);saved.highScore=Math.max(saved.highScore,score);persist();updateUI();sound(won?'win':'foul');
 const title=mode==='timed'?'午夜的 60 秒。':won?level===2&&mode==='career'?'地下球王，诞生。':'漂亮的清台。':'下一杆，会更漂亮。';showModal(`<div class="modal-ball">${won?'8':'↻'}</div><p class="modal-kicker">${mode==='timed'?'TIME IS UP':won?'TABLE CLEARED':'ONE MORE ROUND'}</p><h2 class="modal-title">${title}</h2><p class="modal-copy">${reason||(mode==='timed'?'时间到！你的手感已经被这间球房记住。':mode==='practice'?'练得漂亮。完整球阵随时为你准备。':level===2?'你已经征服全部三间地下俱乐部。继续挑战，刷新你的最高分。':'下一间俱乐部的大门，已经为你打开。')}</p><div class="result-stats"><div><strong>${score}</strong><span>本局得分</span></div><div><strong>${runBest}</strong><span>最佳连杆</span></div><div><strong>+${coins}</strong><span>获得球币</span></div></div><div class="modal-actions"><button class="secondary-btn" data-action="restart">再来一局</button><button class="primary-btn" data-action="${won&&mode==='career'&&level<2?'next':'clubs'}">${won&&mode==='career'&&level<2?'前往下一间球房':'俱乐部地图'}</button></div>`);
}
function help(){showModal(`${closeButton()}<p class="modal-kicker">A LITTLE KNOW-HOW</p><h2 class="modal-title">先找角度，再出好杆。</h2><p class="modal-copy">你是浣熊阿奇。在午夜球房里，用走位和连杆赢得名声。</p><div class="control-grid"><div><strong>鼠标 / 触屏 · 瞄准</strong><span>移动鼠标或轻触台面选择方向；拖动也可调整。虚线展示母球路径，金线展示目标球方向。</span></div><div><strong>空格 / 击球按钮 · 出杆</strong><span>按住空格蓄力，松开出杆；或拖动力度滑条后点击击球。球完全停稳后才能再次出杆。</span></div><div><strong>W A S D · 浣熊走位</strong><span>围绕球台移动阿奇。左右方向键精细修正瞄准角度，按住 Shift 更精细。</span></div><div><strong>高杆 / 低杆 · 母球控制</strong><span>高杆让母球碰撞后跟进；低杆让母球回撤。中杆保持自然滚动，为下一杆预留角度。</span></div><div><strong>V / 右键拖动 · 观察球台</strong><span>V 切换俯视与球房视角。右键拖动环视。手机可使用球台右下角的视角按钮。</span></div><div><strong>Esc · 暂停</strong><span>暂停会同时冻结物理与计时；按 Esc 或继续游戏返回。页面切到后台也会自动暂停。</span></div></div><div class="rule-note">先打进所有彩球，再打黑八。每颗彩球 100 × 倍率分，连续有效进球最多 ×5；失误会中断连杆。母球落袋或没碰到球扣 100 分，本杆不计进球分。清台 +500 分；练习模式会重置犯规黑八。</div><div class="modal-actions"><button class="primary-btn" data-action="close">懂了，开打</button></div>`);}
function clubs(){showModal(`${closeButton()}<p class="modal-kicker">THE UNDERGROUND CIRCUIT</p><h2 class="modal-title">今夜，去哪一间？</h2><p class="modal-copy">清台上一间球房，解锁下一位传奇。你的最高得分：${saved.highScore}。</p><div class="club-list">${CLUBS.map((c,i)=>`<button class="club-option ${i===level?'current':''}" data-club="${i}" ${i>saved.unlocked?'disabled':''}><span>0${i+1}</span><div><strong>${c.name}</strong><p>${c.en} · ${c.balls} 颗彩球 · ${c.shots+saved.stamina*2} 杆</p></div><span>${i>saved.unlocked?'未解锁':saved.cleared.includes(i)?'已征服 ✓':'进入'}</span></button>`).join('')}</div><div class="modal-actions"><button class="secondary-btn" data-action="close">回到球台</button></div>`);}
function equipment(){const upgrades=[{id:'guide',name:'鹰眼瞄准',description:'延长母球轨迹辅助线，每级 +2 米。',cost:200},{id:'control',name:'精工球杆',description:'蓄力速度降低 15%，更容易锁定理想力度。',cost:250},{id:'stamina',name:'深夜耐力',description:'生涯每局增加 2 杆；新开局生效。',cost:300}];showModal(`${closeButton()}<p class="modal-kicker">THE CUE ROOM</p><h2 class="modal-title">好手感，值得好装备。</h2><p class="modal-copy">可用球币 <span style="color:var(--gold)">◈ ${saved.coins}</span> · 通过闯关和计时挑战赚取。升级保存在此设备。</p><div class="upgrade-list">${upgrades.map(u=>{const n=saved[u.id],cost=u.cost*(n+1);return `<div class="upgrade-row"><div><strong>${u.name} <span style="color:var(--lime)">LV. ${n}/3</span></strong><p>${u.description}</p></div><button data-upgrade="${u.id}" ${n>=3||saved.coins<cost?'disabled':''}>${n>=3?'已满级':`◈ ${cost}`}</button></div>`;}).join('')}</div><div class="modal-actions"><button class="primary-btn" data-action="close">回到球台</button></div>`);}
function pauseGame(){if(ended)return;if(paused){closeModal();updateUI();return;}showModal(`${closeButton()}<p class="modal-kicker">TAKE YOUR TIME</p><h2 class="modal-title">好球，值得等一会。</h2><p class="modal-copy">球台和计时已暂停。喝口水，想想下一杆。</p><div class="modal-actions"><button class="secondary-btn" data-action="help">玩法指南</button><button class="primary-btn" data-action="close">继续游戏</button></div>`);updateUI();}
function requestRestart(nextMode=mode){if(totalShots===0||ended){startGame(nextMode,level);return;}showModal(`${closeButton()}<p class="modal-kicker">FRESH FELT</p><h2 class="modal-title">重新摆一局？</h2><p class="modal-copy">当前球局会重新开始，已获得的球币、装备和解锁进度会保留。</p><div class="modal-actions"><button class="secondary-btn" data-action="close">继续本局</button><button class="primary-btn" data-action="confirmed-restart" data-next-mode="${nextMode}">重新开局</button></div>`);}
$('#modal-body').addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.club!==undefined){startGame('career',Number(el.dataset.club));return;}if(el.dataset.upgrade){const id=el.dataset.upgrade;if(!['guide','control','stamina'].includes(id))return;const cost={guide:200,control:250,stamina:300}[id]*(saved[id]+1);if(saved.coins>=cost&&saved[id]<3){saved.coins-=cost;saved[id]++;persist();updateUI();equipment();toast('升级完成 · 新的手感，新的可能');}return;}switch(el.dataset.action){case'close':if(ended){closeModal();startGame(mode,level);}else{closeModal();updateUI();}break;case'restart':startGame();break;case'confirmed-restart':startGame(el.dataset.nextMode,level);break;case'next':startGame('career',Math.min(2,level+1));break;case'clubs':clubs();break;case'help':help();break;}});
$('#shoot').addEventListener('click',()=>shoot());$('#power').addEventListener('input',e=>setPower(Number(e.target.value)/100));$$('[data-spin]').forEach(b=>b.addEventListener('click',()=>{spin=Number(b.dataset.spin);$$('[data-spin]').forEach(x=>x.classList.toggle('selected',x===b));$('#spin-label').textContent=b.textContent;updateUI();}));$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{if(mode!==b.dataset.mode)requestRestart(b.dataset.mode);}));$('#help').onclick=help;$('#equipment').onclick=equipment;$('#club-select').onclick=clubs;$('#pause').onclick=pauseGame;$('#restart').onclick=()=>requestRestart();
function toggleCamera(){if(!scene)return;scene.topView=!scene.topView;$('#camera-label').textContent=scene.topView?'俯视瞄准':'球房视角';$('#camera').title=scene.topView?'切换球房视角 · V':'切换俯视视角 · V';}
$('#camera').onclick=toggleCamera;$('#sound').onclick=()=>{saved.sound=!saved.sound;persist();$('#sound').style.color=saved.sound?'var(--lime)':'';$('#sound').setAttribute('aria-label',saved.sound?'关闭音效':'开启音效');$('#sound').title=saved.sound?'关闭音效':'开启音效';sound('pocket');toast(saved.sound?'音效已开启':'音效已关闭');};$('#sound').style.color=saved.sound?'var(--lime)':'';
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if($('#modal').open){if(e.code==='Space')e.preventDefault();return;}if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat&&['KeyV','Escape','Space'].includes(e.code))return;keys.add(e.code);if(e.code==='KeyV')toggleCamera();if(e.code==='Escape')pauseGame();if(e.code==='Space'&&!shotActive&&!ended&&!paused){charging=true;chargeStart=performance.now();setPower(.1);}});
window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space'&&charging){e.preventDefault();charging=false;shoot();}});window.addEventListener('blur',()=>{keys.clear();charging=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&!ended&&gameReady)pauseGame();});
function pointerAim(e){if(!scene||paused||shotActive||ended||orbiting)return;const p=scene.projectPointer(e.clientX,e.clientY);if(p&&Math.abs(p.x)<6.5&&Math.abs(p.z)<4){angle=Math.atan2(p.z-physics.balls[0].z,p.x-physics.balls[0].x);}}
const arena=$('#scene');arena.addEventListener('contextmenu',e=>e.preventDefault());arena.addEventListener('pointerdown',e=>{if(e.button===2){orbiting=true;lastPointerX=e.clientX;}else{dragging=true;pointerAim(e);}arena.setPointerCapture(e.pointerId);});arena.addEventListener('pointermove',e=>{if(orbiting){scene.orbit-=(e.clientX-lastPointerX)*.006;lastPointerX=e.clientX;scene.topView=false;$('#camera-label').textContent='球房视角';}else if(e.pointerType==='mouse'||dragging)pointerAim(e);});arena.addEventListener('pointerup',()=>{dragging=false;orbiting=false;});arena.addEventListener('pointercancel',()=>{dragging=false;orbiting=false;});
function frame(now){requestAnimationFrame(frame);const elapsed=Math.max(0,(now-lastTime)/1000),dt=Math.min(.05,elapsed);lastTime=now;if(!scene||!physics)return;if(!paused&&!ended){if(charging){const speed=1.3*(1-saved.control*.15);const cycle=((now-chargeStart)/1000*speed)%1.8;setPower(.1+(cycle<=.9?cycle:1.8-cycle));}if(!shotActive){let turn=0;if(keys.has('ArrowLeft'))turn-=1;if(keys.has('ArrowRight'))turn+=1;angle+=turn*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?.07:.4);}const dx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),dz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);scene.moveCharacter(dx,dz,dt);
 if(shotActive){shotElapsed+=dt;accumulator+=dt;while(accumulator>=1/240){physics.step(1/240);accumulator-=1/240;}if(!physics.moving())settleTime+=dt;else settleTime=0;if(settleTime>.3||shotElapsed>30){for(const b of physics.balls){b.vx=b.vz=0;}endShot();}}
 if(mode==='timed'&&timerStarted&&!ended){timeLeft=Math.max(0,timeLeft-elapsed);$('#shots').textContent=`${Math.ceil(timeLeft)}s`;$('#shots').classList.toggle('timer-warning',timeLeft<=10);if(timeLeft<=0){if(shotActive){for(const b of physics.balls){b.vx=b.vz=0;}endShot();}finish(false);}}
 }scene.updateBalls(physics.balls,paused?0:dt);scene.updateGuide(physics,angle,power,!shotActive&&!paused&&!ended,5+saved.guide*2);scene.render(paused?0:dt);}
try{scene=new ClubScene(arena);startGame();$('#scene-loading').classList.add('loaded');requestAnimationFrame(frame);}catch(error){console.error(error);$('#scene-loading').innerHTML='<p style="text-align:center;padding:25px">球房暂时无法启动。<br>请使用支持 WebGL 的浏览器，并开启硬件加速。</p>';$('#shoot').disabled=true;}
// Structured tools reuse the visible game's actions and never bypass progression.
const gameState=()=>({mode,club:CLUBS[level].name,score,combo,shots:mode==='practice'?null:shots,timeLeft:mode==='timed'?Math.ceil(timeLeft):null,paused,ended,moving:shotActive,coins:saved.coins,balls:physics?.balls.filter(b=>b.active).map(({id,x,z})=>({id,x:Number(x.toFixed(3)),z:Number(z.toFixed(3))}))});
if(document.modelContext?.registerTool){const abort=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:abort.signal})).catch(()=>{});}catch{}};register({name:'read_pool_game',title:'读取球局',description:'Read current balls, score, mode and shot state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameState()});register({name:'play_pool_shot',title:'打一杆台球',description:'Aim and shoot in the current game. Angle is radians on the table plane; power is 0.1 to 1; spin is -1, 0 or 1. Fails when paused or balls move.',inputSchema:{type:'object',properties:{angle:{type:'number'},power:{type:'number',minimum:.1,maximum:1},spin:{type:'integer',enum:[-1,0,1]}},required:['angle','power','spin'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isFinite(input.angle)||!Number.isFinite(input.power)||input.power<.1||input.power>1||![-1,0,1].includes(input.spin))throw new Error('Invalid shot settings');if(paused||ended||shotActive||!gameReady)throw new Error('The table is not ready for a shot');angle=input.angle;spin=input.spin;setPower(input.power);$$('[data-spin]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.spin)===spin));$('#spin-label').textContent=['低杆','中杆','高杆'][spin+1];shoot();return gameState();}});window.addEventListener('pagehide',()=>abort.abort(),{once:true});}
