import * as THREE from './vendor/three.module.js';
import {FIELD,TYPES,ICE,createStone,stepPhysics,scoreHouse,simulateShot,chooseAI,distance} from './physics.js';

const $=id=>document.getElementById(id), colors=[0x68edce,0xff957e], names=['海盐','珊瑚'];
let options={mode:'ai',difficulty:'normal',ice:'normal',trajectory:true,sound:false};
try{options={...options,...JSON.parse(localStorage.getItem('otter-preferences')||'{}')};}catch{}
if(!['ai','local','practice'].includes(options.mode))options.mode='ai';if(!['normal','fast','wind','varied'].includes(options.ice))options.ice='normal';
let game, shotType='normal', sweep=false,aiTimer=null,toastTimer=null,settleTimer=null,accumulator=0,last=performance.now(),cameraMode=0,audioContext,collisions=0;
const container=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(39,1,.1,240);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{container.innerHTML='<div style="padding:240px 30px;color:white">当前浏览器无法启动 3D 画面。请启用硬件加速，或使用支持 WebGL 的浏览器。</div>';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;container.appendChild(renderer.domElement);
scene.fog=new THREE.FogExp2(0x174859,.007);
scene.add(new THREE.HemisphereLight(0xd6f4ff,0x123b52,2));const sun=new THREE.DirectionalLight(0xe1f6ff,3.5);sun.position.set(-12,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;sun.shadow.normalBias=.045;scene.add(sun);const cyanLight=new THREE.PointLight(0x49fbc9,22,35);cyanLight.position.set(4,9,-12);scene.add(cyanLight);
const mat=(color,roughness=.75,extra={})=>new THREE.MeshStandardMaterial({color,roughness,...extra});
const snowMat=mat(0xd8eef4),iceMat=mat(0x9ccbd8,.16,{metalness:.1,transparent:true,opacity:.98}),brown=mat(0x7e5039),cream=mat(0xe3c09b),dark=mat(0x172736),black=mat(0x131e23,.25),wood=mat(0x805839);
function mesh(geo,material,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,material,x,y,z,parent){return mesh(new THREE.BoxGeometry(w,h,d),material,x,y,z,parent);}
function sphere(r,material,x,y,z,parent,sx=1,sy=1,sz=1){let o=mesh(new THREE.SphereGeometry(r,20,14),material,x,y,z,parent);o.scale.set(sx,sy,sz);return o;}
function cylinder(rt,rb,h,material,x,y,z,parent,segments=48){return mesh(new THREE.CylinderGeometry(rt,rb,h,segments),material,x,y,z,parent);}

// An actual 3D miniature arena: all stones, characters and terrain are rendered in WebGL.
const world=new THREE.Group();scene.add(world);
box(19,1.1,43,mat(0x3b829c),0,-1.3,0,world);
box(18.8,.6,42.8,snowMat,0,-.5,0,world);
box(10.35,.44,34.8,mat(0x4e9cad,.4),0,-.18,0,world);
box(10,.13,34,iceMat,0,.075,0,world);
for(const x of [-5.12,5.12]){box(.11,.045,34.5,mat(0x64dbc8,.2,{emissive:0x369e8a,emissiveIntensity:.9}),x,.175,0,world);box(.37,.3,34.5,snowMat,x+Math.sign(x)*.3,-.03,0,world);}
for(const z of [-17.2,17.2])box(10.8,.19,.45,snowMat,0,0,z,world);
function circle(r,color,z,y=.151){const m=mesh(new THREE.CircleGeometry(r,96),new THREE.MeshStandardMaterial({color,roughness:.35,transparent:true,opacity:.93}),0,y,z,world);m.rotation.x=-Math.PI/2;m.castShadow=false;return m;}
circle(3.6,0x28657d,-9);circle(2.85,0xe5f4f1,-9,.154);circle(2.12,0x59bfae,-9,.157);circle(1.37,0xe4f6f1,-9,.16);circle(.68,0xf29a82,-9,.163);circle(.17,0xfef1df,-9,.166);
circle(2.7,0x95c6d3,12.8);circle(2.5,0xb6d9e0,12.8,.155);
box(.034,.005,32,mat(0x659dac),0,.175,0,world);
for(const z of [-13,5.5])box(9.95,.006,.12,mat(0xd07774),0,.177,z,world);
box(9.95,.005,.04,mat(0x4f98a8),0,.178,-9,world);
for(const x of [-1,1])box(.32,.12,.72,dark,x,.18,14.2,world);
// Fine scratched ice, deterministic distribution.
let seed=6121;function rand(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}
const scratchMat=new THREE.LineBasicMaterial({color:0xe4f9fb,transparent:true,opacity:.19});const scratchPositions=[];
for(let i=0;i<200;i++){const x=(rand()-.5)*9.5,z=(rand()-.5)*33;const len=rand()*1.7+.1;scratchPositions.push(x,.184,z,x+.015,.184,z+len);}
const scratches=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(scratchPositions,3)),scratchMat);world.add(scratches);
// Side boards, lanterns, pines and spectator benches.
for(let side of [-1,1]){
 for(let z of [-16,-7,2,11,18]){box(.22,1.3,.22,wood,side*8.25,.25,z,world);sphere(.23,mat(0xffe7b1,.4,{emissive:0xffb965,emissiveIntensity:1.7}),side*8.25,1.13,z,world);}
 for(let z of [-12,0,12]){box(.15,.13,10.5,wood,side*8.25,.9,z,world);}
 for(let z of [-14,-4,6]){box(1.1,.17,3.2,wood,side*6.95,.25,z,world);for(let zz of [-1.2,1.2])box(.25,.8,.18,wood,side*6.95,-.1,z+zz,world);}
 for(let i=0;i<7;i++){let x=side*(10+rand()*5),z=-23+rand()*41,scale=.6+rand()*.65;let pine=new THREE.Group();world.add(pine);pine.position.set(x,-.4,z);cylinder(.16,.25,1.2,wood,0,.4,0,pine,7);for(let k=0;k<3;k++){const cone=mesh(new THREE.ConeGeometry((1.7-k*.38)*scale,(2.3-k*.1)*scale,7),k===0?mat(0x245163):mat(0x7daeb5),0,1.1+k*.85,0,pine);cone.rotation.y=.3*k;}pine.scale.setScalar(scale);}
}
for(let i=0;i<14;i++){const side=i%2===0?-1:1;const rock=mesh(new THREE.DodecahedronGeometry(.9+rand()*.8,0),i%3?snowMat:mat(0x5a8f9e),side*(9+rand()*5),-.7,-21+rand()*43,world);rock.scale.set(1.6,.8,1.2);}
function boardLabel(text,color,x,z,rotation=0){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=110;const ctx=canvas.getContext('2d');ctx.fillStyle='#113b4b';ctx.fillRect(0,0,512,110);ctx.fillStyle=color;ctx.font='bold 36px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,68);const texture=new THREE.CanvasTexture(canvas);const plane=mesh(new THREE.PlaneGeometry(5,1.05),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}),x,.75,z,world);plane.rotation.y=rotation;}
boardLabel('OTTER CURLING CLUB','#b9e8df',0,-19.5);boardLabel('STAY COOL. CURL ON.','#8bb9c8',-8.5,4,Math.PI/2);

function createOtter(team,x,z,scale=1,broom=false){const g=new THREE.Group();world.add(g);g.position.set(x,.18,z);g.scale.setScalar(scale);const fur=mat(team===0?0x87604a:0x9a6b4f);sphere(.48,fur,0,.6,0,g,.85,1.25,.8);sphere(.35,cream,0,.57,.28,g,.8,1.2,.45);sphere(.45,fur,0,1.29,.05,g,1.05,.88,.87);sphere(.27,cream,-.14,1.18,.35,g,1,.68,.6);sphere(.27,cream,.14,1.18,.35,g,1,.68,.6);sphere(.08,black,0,1.27,.54,g,1,.7,.7);for(const s of [-1,1]){sphere(.13,fur,s*.36,1.6,.03,g);sphere(.07,cream,s*.37,1.6,.115,g);sphere(.062,black,s*.18,1.38,.385,g);sphere(.019,mat(0xffffff),s*.18-.012,1.4,.433,g);sphere(.16,fur,s*.23,.13,.24,g,1,.6,1.45);const arm=sphere(.18,fur,s*.4,.66,.06,g,.64,1.65,.8);arm.rotation.z=s*.35;g.userData[s<0?'leftArm':'rightArm']=arm;}
const tail=sphere(.25,fur,0,.19,-.51,g,.75,.55,2.2);tail.rotation.x=.15;const scarf=mesh(new THREE.TorusGeometry(.315,.074,8,24),mat(colors[team]),0,1,.06,g);scarf.rotation.x=Math.PI/2;box(.15,.42,.1,mat(colors[team]),.21,.78,.39,g);const mouth=mesh(new THREE.TorusGeometry(.075,.011,6,12,Math.PI),dark,0,1.15,.506,g);mouth.rotation.z=Math.PI;
if(broom){const stick=cylinder(.03,.03,1.4,mat(0xd0ad7e),.52,.72,.36,g,8);stick.rotation.z=-.27;box(.54,.1,.19,mat(colors[team]),.72,.1,.36,g);box(.5,.07,.22,cream,.72,.035,.36,g);}
return g;}
const spectators=[];for(const side of [-1,1])for(const z of [-14,-11,-4,-1,6,9]){const o=createOtter(side===-1?0:1,side*6.95,z,.68);o.rotation.y=side===-1?Math.PI/2:-Math.PI/2;spectators.push(o);}
const playerOtters=[createOtter(0,-1.1,14.1,1.2,true),createOtter(1,1.1,14.1,1.2,true)];playerOtters.forEach(o=>o.rotation.y=Math.PI);
const sweepers=[createOtter(0,-1.1,10.8,.78,true),createOtter(1,1.1,10.8,.78,true)];sweepers.forEach(o=>o.visible=false);

function stoneMesh(team,type='normal',preview=false){const g=new THREE.Group(),t=TYPES[type],r=t.radius;const body=mat(preview?0xa0c2c8:0xabbec7,.25,{metalness:.32});cylinder(r*.78,r,.23,body,0,.16,0,g);cylinder(r,r*.94,.08,mat(0x536a79,.25),0,.06,0,g);cylinder(r*.84,r*.91,.10,body,0,.31,0,g);cylinder(r*.61,r*.70,.035,mat(colors[team],.25),0,.375,0,g);const handle=mesh(new THREE.TorusGeometry(r*.37,.065,10,24,Math.PI),mat(colors[team],.26),0,.40,0,g);handle.rotation.y=Math.PI/2;g.userData.type=type;world.add(g);return g;}
let readyStone=stoneMesh(0),stoneMeshes=[];readyStone.position.set(0,.17,FIELD.startZ);
const aimGroup=new THREE.Group();world.add(aimGroup);const aimMat=new THREE.MeshBasicMaterial({color:0x66efd0,transparent:true,opacity:.85});const dotGeo=new THREE.SphereGeometry(.063,7,5);for(let i=0;i<80;i++){const dot=mesh(dotGeo,aimMat,0,.24,0,aimGroup);dot.castShadow=false;}
const landing=mesh(new THREE.RingGeometry(.48,.53,48),new THREE.MeshBasicMaterial({color:0x66efd0,side:THREE.DoubleSide,transparent:true,opacity:.8}),0,.2,-9,world);landing.rotation.x=-Math.PI/2;landing.castShadow=false;
const highlight=mesh(new THREE.RingGeometry(.64,.70,48),new THREE.MeshBasicMaterial({color:0x66efd0,side:THREE.DoubleSide,transparent:true,opacity:.8}),0,.195,-9,world);highlight.rotation.x=-Math.PI/2;highlight.visible=false;highlight.castShadow=false;
const snowCount=170,snowGeo=new THREE.BufferGeometry(),snowPos=new Float32Array(snowCount*3);for(let i=0;i<snowCount;i++){snowPos[i*3]=(rand()-.5)*52;snowPos[i*3+1]=rand()*20;snowPos[i*3+2]=(rand()-.5)*60;}snowGeo.setAttribute('position',new THREE.BufferAttribute(snowPos,3));const snow=new THREE.Points(snowGeo,new THREE.PointsMaterial({color:0xe7ffff,size:.065,transparent:true,opacity:.6}));scene.add(snow);
let bursts=[];
function burst(x,z,strength,team){const group=new THREE.Group();world.add(group);for(let i=0;i<10;i++){const p=mesh(new THREE.SphereGeometry(.05,5,4),mat(i%2?colors[team]:0xe5ffff),x,.28,z,group);const a=rand()*Math.PI*2;p.userData={vx:Math.cos(a)*(1+strength*.2),vz:Math.sin(a)*(1+strength*.2),vy:1+rand()*2};}bursts.push({g:group,life:.6});}
function sound(freq=500,duration=.12,volume=.045,type='sine'){if(!options.sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();let o=audioContext.createOscillator(),gain=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.55),audioContext.currentTime+duration);gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(gain);gain.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);}catch{}}
function notify(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300);}
function iceForRound(){return options.ice==='varied'?['normal','fast','wind'][(game.round-1)%3]:options.ice;}
function newGame(){clearTimeout(aiTimer);clearTimeout(settleTimer);stopSweep();game={round:1,team:0,starter:0,thrown:[0,0],scores:[0,0],energy:[100,100],stones:[],phase:'aim',history:[],shotTime:0,practiceShots:0};for(const m of stoneMeshes)disposeGroup(m);stoneMeshes=[];for(const b of bursts)world.remove(b.g);bursts=[];document.querySelectorAll('dialog').forEach(d=>d.close());$('angle').value=0;$('power').value=50;$('spin').value=0;shotType='normal';setPhase('aim');setInputs();renderUI();updateAim();}
function isHuman(){return options.mode!=='ai'||game.team===0;}
function setPhase(phase){game.phase=phase;stopSweep();const aim=phase==='aim'&&isHuman();$('throw-btn').disabled=!aim;$('sweep-btn').disabled=!(phase==='moving'&&isHuman());for(const id of ['angle','power','spin'])$(id).disabled=!aim;for(const b of document.querySelectorAll('.stone-type'))b.disabled=!aim;readyStone.visible=aim;aimGroup.visible=aim&&options.trajectory;landing.visible=aim&&options.trajectory;document.body.dataset.team=String(game.team);$('control-panel')?.classList.toggle('muted-inputs',!aim);}
function setInputs(){const angle=+$('angle').value,power=+$('power').value,spin=+$('spin').value;$('angle-value').textContent=(angle>0?'+':'')+angle.toFixed(1)+'°';$('power-value').innerHTML=power+'<span>%</span>';$('spin-value').textContent=Math.abs(spin)<.01?'直线':(spin<0?'左旋 ':'右旋 ')+Math.round(Math.abs(spin)*100)+'%';for(const id of ['angle','power','spin']){const el=$(id);el.style.setProperty('--range',((+el.value-+el.min)/(+el.max-+el.min)*100)+'%');}document.querySelectorAll('.stone-type').forEach(b=>b.classList.toggle('selected',b.dataset.type===shotType));}
function disposeGroup(group){group.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});world.remove(group);}
function updateAim(){if(!game||game.phase!=='aim'||!isHuman())return;disposeGroup(readyStone);readyStone=stoneMesh(game.team,shotType,true);readyStone.position.set(0,.17,FIELD.startZ);const shot=createStone(game.team,shotType,+$('angle').value,+$('power').value,+$('spin').value);const result=simulateShot(game.stones,shot,iceForRound(),true);aimMat.color.setHex(colors[game.team]);landing.material.color.setHex(colors[game.team]);const points=result.points.filter((p,i)=>i%2===0);aimGroup.children.forEach((dot,i)=>{dot.visible=i<points.length;if(dot.visible)dot.position.set(points[i].x,.25,points[i].z);});const end=result.stones.at(-1);landing.position.set(end.x,.197,end.z);landing.visible=end.active&&options.trajectory;aimGroup.visible=options.trajectory;}
function renderUI(){if(!game)return;$('mode-badge').textContent={ai:'人机对战',local:'本地双人',practice:'无限练习'}[options.mode];$('mint-role').textContent=options.mode==='local'?'玩家一':'你的小队';$('coral-role').textContent=options.mode==='local'?'玩家二':options.mode==='practice'?'训练陪练':'电脑小队';$('round-label').textContent=options.mode==='practice'?'自由练习':'第 '+game.round+' / 3 局';$('round-dots').innerHTML=[1,2,3].map(n=>'<i class="'+(n===game.round?'on':'')+'"></i>').join('');for(let t=0;t<2;t++){$('score-'+t).textContent=game.scores[t];$('stones-'+t).innerHTML=Array.from({length:4},(_,i)=>'<i class="'+(i<game.thrown[t]?'used':'')+'"></i>').join('');}
$('turn-title').textContent=game.phase==='ai'?'珊瑚队思考中':game.phase==='moving'?names[game.team]+'队出手中':'轮到'+names[game.team]+'队';$('turn-dot').style.background='#'+colors[game.team].toString(16);$('shot-number').textContent=options.mode==='practice'?'第 '+(game.practiceShots+1)+' 壶':'第 '+Math.min(4,game.thrown[game.team]+(game.phase==='moving'?0:1))+' 壶';const ice=ICE[iceForRound()];$('ice-label').textContent=ice.label;$('ice-description').textContent=ice.description;$('wind-label').textContent=ice.wind?'侧风 · 向右偏移':'平静 · 无风';$('energy-value').textContent=Math.round(game.energy[game.team])+'%';$('energy-bar').style.width=game.energy[game.team]+'%';if(game.phase==='aim'){$('callout-eyebrow').textContent=options.mode==='practice'?'PRACTICE MAKES PERFECT':'YOUR TURN';$('callout-title').textContent=game.thrown[game.team]===0?'来一记漂亮的入营。':'下一壶，扭转局面。';$('callout-subtitle').textContent='点击冰面瞄准，调整力度后投出冰壶';$('control-tip').textContent='虚线为预估轨迹 · 扫冰可延长滑行';}updateHouse();}
function updateHouse(){const result=scoreHouse(game.stones);if(result.team===null){$('house-status').innerHTML='<span class="neutral-dot"></span>暂时没有队伍得分';}else{$('house-status').innerHTML='<span class="neutral-dot" style="background:#'+colors[result.team].toString(16)+'"></span>'+names[result.team]+'队暂得 <strong style="color:#'+colors[result.team].toString(16)+'">'+result.points+' 分</strong>';}$('distance-list').innerHTML=result.ranked.slice(0,3).map((s,i)=>'<div><span>'+(i+1)+'. '+names[s.team]+' · '+TYPES[s.type].label+'</span><span>'+s.distance.toFixed(2)+' m</span></div>').join('');highlight.visible=!!result.ranked.length;if(result.ranked.length){const s=result.ranked[0];highlight.position.set(s.x,.195,s.z);highlight.material.color.setHex(colors[s.team]);}}
function launch(config){if(!game||!['aim','ai'].includes(game.phase))return false;if(game.phase==='aim'&&!isHuman())return false;let c=config||{angle:+$('angle').value,power:+$('power').value,spin:+$('spin').value,type:shotType};if(!Number.isFinite(c.angle)||!Number.isFinite(c.power)||!Number.isFinite(c.spin)||!TYPES[c.type])throw new Error('Invalid shot');if(c.angle< -22||c.angle>22||c.power<8||c.power>100||c.spin< -1||c.spin>1)throw new Error('Shot outside allowed range');const stone=createStone(game.team,c.type,c.angle,c.power,c.spin);game.stones.push(stone);game.thrown[game.team]++;game.practiceShots++;const m=stoneMesh(game.team,c.type);m.position.set(stone.x,.17,stone.z);stoneMeshes.push(m);game.shotTime=0;collisions=0;game.settledFor=0;setPhase('moving');renderUI();$('callout-eyebrow').textContent='STONE IN MOTION';$('callout-title').textContent='滑向你的主场。';$('callout-subtitle').textContent=isHuman()?'按住空格或扫冰按钮，延长冰壶滑行':'珊瑚队出手了，看看它的落点';$('control-tip').textContent='扫冰能量每队每局共享 · 停稳后换手';sound(620,.18,.035);return true;}
function finishShot(){if(game.phase!=='moving')return;const lastStone=game.stones.at(-1);stopSweep();setPhase('settling');if(!lastStone.active){notify('滑出边线 · 这颗冰壶出局');sound(160,.3);}else if(distance(lastStone)<.72){notify('正中靶心！漂亮的精准投掷');sound(880,.2);setTimeout(()=>sound(1180,.2),130);}else if(collisions>0)notify('碰撞完成 · 冰场格局已改变');else if(distance(lastStone)<FIELD.radius)notify('成功入营 · '+distance(lastStone).toFixed(2)+' m');else notify('停壶完成 · 一道新的防线');updateHouse();settleTimer=setTimeout(nextTurn,1100);}
function nextTurn(){if(options.mode==='practice'){if(game.stones.length>=16){game.stones.shift();disposeGroup(stoneMeshes.shift());}game.energy=[100,100];game.team=0;game.thrown=[0,0];setPhase('aim');renderUI();updateAim();return;}if(game.thrown[0]===4&&game.thrown[1]===4){endRound();return;}game.team=1-game.team;if(options.mode==='ai'&&game.team===1){setPhase('ai');renderUI();$('callout-eyebrow').textContent='CORAL TEAM';$('callout-title').textContent='对手正在寻找机会。';$('callout-subtitle').textContent='观察大本营，计划你的下一步';aiTimer=setTimeout(()=>{if(game.phase!=='ai')return;const config=chooseAI(game.stones,1,iceForRound(),options.difficulty);const words={draw:'瞄准圆心，准备入营',hit:'瞄准你的冰壶，准备击打',guard:'布置一道保护壶'};notify('珊瑚队：'+words[config.intent]);aiTimer=setTimeout(()=>{if(game.phase==='ai')launch(config);},850);},600);}else{setPhase('aim');renderUI();updateAim();sound(440,.08);}}
function endRound(){const result=scoreHouse(game.stones);game.history.push({team:result.team,points:result.points});if(result.team!==null)game.scores[result.team]+=result.points;setPhase('result');renderUI();const final=game.round===3;$('result-eyebrow').textContent=final?'MATCH COMPLETE':'END '+game.round+' COMPLETE';let winning=final?(game.scores[0]===game.scores[1]?null:game.scores[0]>game.scores[1]?0:1):result.team;$('result-title').textContent=winning===null?(final?'旗鼓相当，握手言和。':'空局，蓄势待发。'):names[winning]+'队'+(final?'赢得比赛！':'拿下 '+result.points+' 分！');$('result-symbol').style.color=winning===1?'#fc997f':'#66efd0';$('result-copy').textContent=final?'最终比分 '+game.scores[0]+' : '+game.scores[1]+'。每一次碰撞，都是一次新的机会。':result.team===null?'没有有效得分，双方保留原先手顺序。':'只有比对手最近壶更靠近圆心的冰壶计分。下局由'+names[result.team]+'队先投。';$('round-history').innerHTML=game.history.map((r,i)=>'<div><small>第 '+(i+1)+' 局</small><span style="color:#66efd0">'+(r.team===0?r.points:0)+'</span> : <span style="color:#fc997f">'+(r.team===1?r.points:0)+'</span></div>').join('');$('continue-btn').textContent=final?'再来一场':'进入第 '+(game.round+1)+' 局';$('result-dialog').showModal();if(winning!==null){confetti(colors[winning]);sound(660,.3);setTimeout(()=>sound(990,.3),200);}}
function nextRound(){if(game.round===3){newGame();return;}const prev=game.history.at(-1);game.round++;if(prev.team!==null)game.starter=prev.team;game.team=game.starter;game.thrown=[0,0];game.energy=[100,100];game.stones=[];for(const m of stoneMeshes)disposeGroup(m);stoneMeshes=[];$('result-dialog').close();if(options.mode==='ai'&&game.team===1){game.team=0;nextTurn();}else{setPhase('aim');renderUI();updateAim();}}
function confetti(color){const surface=$('particles-ui');for(let i=0;i<45;i++){const e=document.createElement('i');e.className='confetti';e.style.left=(Math.random()*100)+'%';e.style.background=i%3?'#'+color.toString(16):'#ebf9f2';e.style.animationDelay=(Math.random()*.8)+'s';surface.appendChild(e);setTimeout(()=>e.remove(),4100);}}
function startSweep(){if(game.phase!=='moving'||!isHuman()||game.energy[game.team]<=0||!game.stones.at(-1)?.active)return;sweep=true;$('sweep-btn').classList.add('active');$('callout-title').textContent='一起扫冰，加把劲！';$('callout-subtitle').textContent='摩擦正在降低 · 留意前方的落点';}
function stopSweep(){sweep=false;$('sweep-btn').classList.remove('active');sweepers.forEach(o=>o.visible=false);}
function cameraTarget(){const mobile=container.clientWidth<550;if(cameraMode===1)return {position:new THREE.Vector3(0,52,.8),look:new THREE.Vector3(0,0,-.7)};if(cameraMode===2)return {position:new THREE.Vector3(0,12,30),look:new THREE.Vector3(0,0,-5)};return {position:new THREE.Vector3(mobile?25:22,mobile?32:29,mobile?35:32),look:new THREE.Vector3(0,0,-1.1)};}
let cameraLook=new THREE.Vector3(0,0,-1.1);function resize(){const width=container.clientWidth,height=container.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);resize();camera.position.copy(cameraTarget().position);camera.lookAt(cameraLook);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-.2);
function aimFromPointer(event){if(game.phase!=='aim'||!isHuman())return;const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const point=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,point)&&point.z<FIELD.startZ-1){const a=THREE.MathUtils.clamp(Math.atan2(point.x,FIELD.startZ-point.z)*180/Math.PI,-22,22);$('angle').value=a;const t=TYPES[shotType];const dist=Math.hypot(point.x,FIELD.startZ-point.z);$('power').value=THREE.MathUtils.clamp((Math.sqrt(2*ICE[iceForRound()].friction*dist)/t.speed-5)/.16,8,100);setInputs();updateAim();}}
let aiming=false;renderer.domElement.addEventListener('pointerdown',e=>{aiming=true;renderer.domElement.setPointerCapture(e.pointerId);aimFromPointer(e);});renderer.domElement.addEventListener('pointermove',e=>{if(aiming)aimFromPointer(e);});renderer.domElement.addEventListener('pointerup',()=>aiming=false);renderer.domElement.addEventListener('pointercancel',()=>aiming=false);
for(const id of ['angle','power','spin'])$(id).addEventListener('input',()=>{setInputs();updateAim();});document.querySelectorAll('.stone-type').forEach(b=>b.addEventListener('click',()=>{if(game.phase!=='aim'||!isHuman())return;shotType=b.dataset.type;setInputs();updateAim();sound(430,.05,.025);}));
$('throw-btn').addEventListener('click',()=>launch());$('sweep-btn').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);startSweep();});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('sweep-btn').addEventListener(type,stopSweep);window.addEventListener('blur',()=>{stopSweep();aiming=false;});document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;if(document.hidden)stopSweep();});
function switchCamera(){cameraMode=(cameraMode+1)%3;$('camera-btn').innerHTML='◫ <span>'+['俯瞰','追踪','环视'][cameraMode]+'</span>';}
$('camera-btn').addEventListener('click',switchCamera);$('fullscreen-btn').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.arena').requestFullscreen();}catch{notify('当前窗口暂不支持全屏');}});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(['SELECT','INPUT'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(game.phase==='aim')launch();else startSweep();}if(e.code==='KeyC'&&!e.repeat)switchCamera();if(game.phase!=='aim'||!isHuman())return;let id,delta;if(e.code==='ArrowLeft'){id='angle';delta=-.4;}if(e.code==='ArrowRight'){id='angle';delta=.4;}if(e.code==='ArrowUp'){id='power';delta=1;}if(e.code==='ArrowDown'){id='power';delta=-1;}if(e.code==='KeyQ'){id='spin';delta=-.1;}if(e.code==='KeyE'){id='spin';delta=.1;}if(id){e.preventDefault();const el=$(id);el.value=THREE.MathUtils.clamp(+el.value+delta,+el.min,+el.max);setInputs();updateAim();}});document.addEventListener('keyup',e=>{if(e.code==='Space')stopSweep();});
function showDialog(id){stopSweep();$(id).showModal();}document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('help-btn').addEventListener('click',()=>showDialog('help-dialog'));$('settings-btn').addEventListener('click',()=>{$('mode-select').value=options.mode;$('difficulty-select').value=options.difficulty;$('ice-select').value=options.ice;$('trajectory-toggle').checked=options.trajectory;showDialog('settings-dialog');});$('new-game-btn').addEventListener('click',()=>{if(game.stones.length||game.round>1){$('settings-btn').click();}else{newGame();notify('新比赛已准备好');}});$('apply-settings').addEventListener('click',()=>{options.mode=$('mode-select').value;options.difficulty=$('difficulty-select').value;options.ice=$('ice-select').value;options.trajectory=$('trajectory-toggle').checked;savePreferences();newGame();});$('continue-btn').addEventListener('click',nextRound);$('result-dialog').addEventListener('cancel',e=>e.preventDefault());function savePreferences(){try{localStorage.setItem('otter-preferences',JSON.stringify(options));}catch{}}
$('sound-btn').addEventListener('click',()=>{options.sound=!options.sound;savePreferences();$('sound-btn').style.color=options.sound?'#66efd0':'#c3d6dc';$('sound-btn').setAttribute('aria-label',options.sound?'关闭音效':'开启音效');notify(options.sound?'音效已开启':'音效已关闭');sound(700,.13);});

function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;const time=now*.001;const paused=!!$('help-dialog').open||!!$('settings-dialog').open;
if(game?.phase==='moving'&&!paused){accumulator+=dt;game.shotTime+=dt;const shot=game.stones.at(-1);if(sweep&&game.energy[game.team]>0&&shot.active&&Math.hypot(shot.vx,shot.vz)>.1){game.energy[game.team]=Math.max(0,game.energy[game.team]-dt*30);$('energy-value').textContent=Math.round(game.energy[game.team])+'%';$('energy-bar').style.width=game.energy[game.team]+'%';for(let i=0;i<2;i++){const o=sweepers[i];o.visible=true;o.position.set(shot.x+(i===0?-.85:.85),.18,shot.z-1);o.rotation.y=Math.PI+Math.sin(time*18)*.25;}}else if(sweep)stopSweep();
let moving=false;while(accumulator>=1/120){moving=stepPhysics(game.stones,1/120,iceForRound(),sweep?game.stones.length-1:-1,(x,z,strength,team)=>{collisions++;burst(x,z,strength,team);sound(210+strength*17,.09,Math.min(.12,strength*.013),'triangle');});accumulator-=1/120;}if(!moving&&game.stones.every(s=>!s.active||Math.hypot(s.vx,s.vz)<.05))game.settledFor+=dt;else game.settledFor=0;if(game.settledFor>.22||game.shotTime>12){for(const s of game.stones)s.vx=s.vz=0;finishShot();}if(Math.floor(time*7)!==Math.floor((time-dt)*7))updateHouse();}
game?.stones.forEach((s,i)=>{const m=stoneMeshes[i];if(!m)return;m.visible=s.active;m.position.set(s.x,.18,s.z);if(game.phase==='moving'&&!paused)m.rotation.y+=s.spin*dt*3;});
for(let i=0;i<spectators.length;i++){let o=spectators[i];o.position.y=.18+Math.sin(time*1.6+i)*.025;const cheer=game?.phase==='result'?Math.sin(time*9+i)*.6:Math.sin(time*2+i)*.09;o.userData.leftArm.rotation.z=.35+cheer;o.userData.rightArm.rotation.z=-.35-cheer;}
playerOtters.forEach((o,i)=>{o.visible=game?.team===i;o.position.y=.18+Math.sin(time*2)*.035;});readyStone.rotation.y=Math.sin(time*.6)*.15;
for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];b.life-=dt;b.g.children.forEach(p=>{p.position.x+=p.userData.vx*dt;p.position.z+=p.userData.vz*dt;p.position.y+=p.userData.vy*dt;p.userData.vy-=5*dt;p.scale.setScalar(Math.max(0,b.life/.6));});if(b.life<=0){disposeGroup(b.g);bursts.splice(i,1);}}
for(let i=0;i<snowCount;i++){snowPos[i*3+1]-=dt*(.3+(i%6)*.07);snowPos[i*3]+=dt*.08;if(snowPos[i*3+1]<0)snowPos[i*3+1]=20;}snowGeo.attributes.position.needsUpdate=true;
const target=cameraTarget();if(cameraMode===2&&game?.phase==='moving'){const s=game.stones.at(-1);if(s.active){target.position.set(s.x,11,s.z+18);target.look.set(s.x,0,s.z-5);}}camera.position.lerp(target.position,1-Math.exp(-dt*3));cameraLook.lerp(target.look,1-Math.exp(-dt*3));camera.lookAt(cameraLook);renderer.render(scene,camera);}
newGame();requestAnimationFrame(frame);

// Agent-facing controls share the exact game actions used by the visible interface.
function publicState(){return {mode:options.mode,phase:game.phase,round:game.round,team:names[game.team],scores:[...game.scores],remaining:game.thrown.map(n=>4-n),energy:[...game.energy],ice:iceForRound(),house:scoreHouse(game.stones),stones:game.stones.map(s=>({...s}))};}
window.otterGame={getState:publicState};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const definitions=[{name:'get_curling_match',description:'Read the current curling match, score and stone positions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>publicState()},{name:'throw_curling_stone',description:'Throw one stone on the current human turn using the visible game controls.',inputSchema:{type:'object',properties:{angle:{type:'number',minimum:-22,maximum:22},power:{type:'number',minimum:8,maximum:100},spin:{type:'number',minimum:-1,maximum:1},type:{type:'string',enum:['normal','light','heavy']}},required:['angle','power','spin','type'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(game.phase!=='aim'||!isHuman())throw new Error('Wait for a human aiming turn');if(!input||!launch(input))throw new Error('Shot could not be launched');return {launched:true,state:publicState()};}}];for(const def of definitions){try{Promise.resolve(context.registerTool(def,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
