export const FIELD={halfWidth:5,halfLength:17,startZ:12.8,targetZ:-9,radius:3.6};
export const TYPES={normal:{label:'标准壶',mass:1,radius:.48,speed:1,curl:1},light:{label:'轻巧壶',mass:.72,radius:.44,speed:1.035,curl:1.5},heavy:{label:'重击壶',mass:1.5,radius:.54,speed:.97,curl:.55}};
export const ICE={normal:{label:'标准冰面',friction:3.8,wind:0,description:'稳定滑行，适合精准落点'},fast:{label:'镜面冰',friction:3.25,wind:0,description:'滑行更远，记得收一点力'},wind:{label:'海湾侧风',friction:3.8,wind:.23,description:'微风向右，瞄准时留出余量'}};
export function createStone(team,type='normal',angle=0,power=50,spin=0){const t=TYPES[type];const a=angle*Math.PI/180,v=(5+power*.16)*t.speed;return {team,type,x:0,z:FIELD.startZ,vx:Math.sin(a)*v,vz:-Math.cos(a)*v,spin,mass:t.mass,radius:t.radius,active:true,travel:0};}
export function stepPhysics(stones,dt,ice='normal',sweepId=-1,onHit){const env=ICE[ice];let moving=false;for(let i=0;i<stones.length;i++){const s=stones[i];if(!s.active)continue;const v=Math.hypot(s.vx,s.vz);if(v<.045){s.vx=s.vz=0;continue;}const f=env.friction*(i===sweepId?.60:1);const nv=Math.max(0,v-f*dt);const turn=s.spin*.08*TYPES[s.type].curl*(v/14)*dt;const cos=Math.cos(turn),sin=Math.sin(turn);let vx=s.vx*cos-s.vz*sin,vz=s.vx*sin+s.vz*cos;s.vx=vx*nv/v+(nv>0?env.wind*dt:0);s.vz=vz*nv/v;s.spin*=Math.exp(-dt*.17);s.x+=s.vx*dt;s.z+=s.vz*dt;s.travel+=v*dt;moving=true;if(Math.abs(s.x)>FIELD.halfWidth-s.radius*.15||Math.abs(s.z)>FIELD.halfLength+s.radius){s.active=false;s.vx=s.vz=0;}}
for(let i=0;i<stones.length;i++)for(let j=i+1;j<stones.length;j++){const a=stones[i],b=stones[j];if(!a.active||!b.active)continue;const dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz),r=a.radius+b.radius;if(d>=r)continue;const nx=d>1e-6?dx/d:1,nz=d>1e-6?dz/d:0;const overlap=r-d+.001,ia=1/a.mass,ib=1/b.mass;a.x-=nx*overlap*ia/(ia+ib);a.z-=nz*overlap*ia/(ia+ib);b.x+=nx*overlap*ib/(ia+ib);b.z+=nz*overlap*ib/(ia+ib);const rel=(b.vx-a.vx)*nx+(b.vz-a.vz)*nz;if(rel<0){const imp=-(1+.86)*rel/(ia+ib);a.vx-=imp*nx*ia;a.vz-=imp*nz*ia;b.vx+=imp*nx*ib;b.vz+=imp*nz*ib;moving=true;if(onHit&&-rel>.45)onHit((a.x+b.x)/2,(a.z+b.z)/2,-rel,a.team);}}
return moving;}
export function distance(s){return Math.hypot(s.x,s.z-FIELD.targetZ);}
export function scoreHouse(stones){const ranked=stones.filter(s=>s.active&&distance(s)<=FIELD.radius+s.radius+1e-6).map(s=>({...s,distance:distance(s)})).sort((a,b)=>a.distance-b.distance);if(!ranked.length)return {team:null,points:0,ranked};const nearest=ranked[0],opponent=ranked.find(s=>s.team!==nearest.team);if(opponent&&Math.abs(opponent.distance-nearest.distance)<=.012+1e-9)return {team:null,points:0,ranked};return {team:nearest.team,points:ranked.filter(s=>s.team===nearest.team&&(!opponent||s.distance<opponent.distance-.012-1e-9)).length,ranked};}
export function simulateShot(existing,shot,ice='normal',trail=false){const stones=existing.map(s=>({...s})),index=stones.length;stones.push({...shot});let points=[];for(let n=0;n<1200;n++){const moving=stepPhysics(stones,1/120,ice);if(trail&&n%10===0)points.push({x:stones[index].x,z:stones[index].z});if(!moving)break;}return {stones,points,score:scoreHouse(stones)};}
export function chooseAI(existing,team,ice='normal',difficulty='normal'){const target=scoreHouse(existing),enemy=target.ranked.find(s=>s.team!==team),friction=ICE[ice].friction;const aims=[{x:0,z:-9,kind:'draw'},{x:-1.1,z:-8.7,kind:'draw'},{x:1.1,z:-9,kind:'draw'},{x:0,z:-5.8,kind:'guard'}];if(enemy)aims.push({x:enemy.x,z:enemy.z,kind:'hit'});let best=null,bestValue=-Infinity;for(const aim of aims){const dist=Math.hypot(aim.x,FIELD.startZ-aim.z),angle=Math.atan2(aim.x,FIELD.startZ-aim.z)*180/Math.PI;const base=(Math.sqrt(2*friction*dist)-5)/.16;for(const spin of [-.65,0,.65])for(const offset of [-3,0,3]){const type=aim.kind==='hit'?'heavy':'normal';const p=Math.max(8,Math.min(94,base+offset+(aim.kind==='hit'?12:0)));const shot=createStone(team,type,angle-spin*2,p,spin);const result=simulateShot(existing,shot,ice),score=result.score;let value=score.team===team?score.points*18:score.team===null?0:-score.points*22;const own=result.stones.filter(s=>s.active&&s.team===team);const closest=own.length?Math.min(...own.map(distance)):30;value+=Math.max(0,8-closest)*2;const last=result.stones.at(-1);if(!last.active)value-=12;if(aim.kind==='guard'&&score.team===team)value+=2;if(value>bestValue){bestValue=value;best={angle:angle-spin*2,power:p,spin,type,intent:aim.kind};}}}const error=difficulty==='easy'?1.1:difficulty==='hard'?.13:.42;best.angle+=(Math.random()-.5)*error*2;best.power+=(Math.random()-.5)*error*2;return best;}
