import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as RealThree from './dist/three.module.js';
class Element{constructor(){this.style={};this.dataset={};this.classList={add(){},remove(){},toggle(){}};this.open=false;this.hidden=false;}addEventListener(){}appendChild(){}before(){}remove(){}setAttribute(){}setPointerCapture(){}showModal(){this.open=true}close(){this.open=false}}
const els=new Map(),tones=[0,1,2].map(n=>Object.assign(new Element(),{dataset:{tone:String(n)}}));const doc={querySelector:s=>{if(!els.has(s))els.set(s,new Element());return els.get(s)},querySelectorAll:s=>s==='[data-tone]'?tones:[],createElement:()=>new Element(),addEventListener(){},body:new Element()};class Renderer{constructor(){this.domElement=new Element();this.shadowMap={}}setSize(){}setPixelRatio(){}render(){}}
let storage={};const context=vm.createContext({THREE:{...RealThree,WebGLRenderer:Renderer},document:doc,window:{addEventListener(){}},innerWidth:1280,innerHeight:720,devicePixelRatio:1,performance:{now:()=>0},requestAnimationFrame(){},localStorage:{setItem:(k,v)=>storage[k]=v,getItem:k=>storage[k]??null,removeItem:k=>delete storage[k]},location:{reload(){}},console,setTimeout:fn=>fn()});
vm.runInContext(fs.readFileSync('dist/game.js','utf8').replace("import * as THREE from './three.module.js';",''),context);const run=s=>vm.runInContext(s,context);
run('start(); interact("clock")');assert.match(els.get('#toast').textContent,/没有动力/);
run('state.gearIds=[0,1,2];interact("power")');els.get('#install').onclick();assert.equal(run('state.power'),true);
run('interact("clock")');for(let i=0;i<3;i++)els.get('#hour').onclick();els.get('#minute').onclick();els.get('#clockCheck').onclick();assert.equal(run('state.clock'),true);
run('interact("bells")');tones[0].onclick();tones[1].onclick();tones[2].onclick();assert.equal(run('state.bells'),false);tones[0].onclick();tones[2].onclick();tones[1].onclick();assert.equal(run('state.bells'),true);
assert.equal(run('canMove(11,-1.6,false,{x:11,z:-1.4})'),false);assert.equal(run('canMove(11,-1.6,true,{x:11,z:-1.4})'),true);assert.equal(run('canMove(14,0,true,{x:13,z:0})'),false);
run('interact("exit")');assert.equal(run('state.won'),true);assert.match(els.get('#modalBody').innerHTML,/回家了/);assert.ok(storage['midnight-ghost-v1']);console.log('PASS: locked clock, gear repair, 03:15 puzzle, wrong/right bell sequence, phase barrier, bounds, victory, save.');
