import * as THREE from 'three';
import './style.css';
const $=id=>document.getElementById(id);
const canvas=$('world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xbadbd5);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xbadbd5,.0038);
const camera=new THREE.PerspectiveCamera(53,innerWidth/innerHeight,.1,850);
scene.add(new THREE.HemisphereLight(0xeaffef,0xad7957,2.4));
const sun=new THREE.DirectionalLight(0xffeed1,3.1);sun.position.set(-65,100,20);scene.add(sun);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:1,flatShading:true,...extra});
const rockMats=[mat(0xc89774),mat(0xd4a582),mat(0xb88869),mat(0xe0b48e),mat(0xcea284)];
const grass=mat(0x8d9d70),trunk=mat(0x725d43),leaves=[mat(0x4e7d64),mat(0x66876a),mat(0x769572)];
function mesh(geo,material,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);parent.add(m);return m}
let seed=1321;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function center(z){return Math.sin(z*.008)*15+Math.sin(z*.021)*4}
const canyon=new THREE.Group();scene.add(canyon);
const terrainLength=1500;
for(let i=0;i<54;i++){const z=70-i*28;for(const side of [-1,1]){const x=center(z)+side*(36+rand()*17);const h=26+rand()*48;const radius=13+rand()*14;
const pillar=new THREE.Group();pillar.position.set(x,0,z);canyon.add(pillar);
const geo=new THREE.CylinderGeometry(radius*.75,radius*1.3,h,5+Math.floor(rand()*3),3);const positions=geo.attributes.position;for(let j=0;j<positions.count;j++){if(positions.getY(j)>-h/2+.1){positions.setX(j,positions.getX(j)+(rand()-.5)*3);positions.setZ(j,positions.getZ(j)+(rand()-.5)*3)}}geo.computeVertexNormals();mesh(geo,rockMats[i%5],pillar,0,h/2-12,0);
mesh(new THREE.CylinderGeometry(radius*.76,radius*.78,1.5,6),grass,pillar,0,h-11.6,0);
for(let t=0;t<2+rand()*4;t++){const tree=new THREE.Group();tree.position.set((rand()-.5)*radius, h-11,(rand()-.5)*radius);pillar.add(tree);const size=2+rand()*3;mesh(new THREE.CylinderGeometry(.3,.5,size*1.4,5),trunk,tree,0,size*.5);mesh(new THREE.ConeGeometry(size*.65,size*2,5),leaves[t%3],tree,0,size*1.6);mesh(new THREE.ConeGeometry(size*.5,size*1.6,5),leaves[(t+1)%3],tree,0,size*2.3)}
// Lower ledges make the canyon walls layered instead of flat.
mesh(new THREE.DodecahedronGeometry(radius*.9,0),rockMats[(i+2)%5],canyon,x-side*6,-4,z+9).scale.set(1,.65,1.4);
}}
// A winding river follows the same navigable canyon corridor.
const riverVertices=[],riverIndices=[];for(let i=0;i<=180;i++){const z=120-i*9;const c=center(z);riverVertices.push(c-16,-8,z,c+16,-8,z);if(i<180){const n=i*2;riverIndices.push(n,n+1,n+2,n+1,n+3,n+2)}}const riverGeo=new THREE.BufferGeometry();riverGeo.setAttribute('position',new THREE.Float32BufferAttribute(riverVertices,3));riverGeo.setIndex(riverIndices);riverGeo.computeVertexNormals();mesh(riverGeo,mat(0x70babc,{metalness:.15,roughness:.35,side:THREE.DoubleSide}),canyon);
for(let i=0;i<80;i++){const z=90-i*18;mesh(new THREE.PlaneGeometry(2+rand()*9,.16),mat(0xc4e0cc,{transparent:true,opacity:.3,side:THREE.DoubleSide}),canyon,center(z)+(rand()-.5)*22,-7.9,z).rotation.x=-Math.PI/2}
// Remote mountains, drifting clouds, and birds establish the scale.
const distant=new THREE.Group();scene.add(distant);for(let i=0;i<22;i++){const m=mesh(new THREE.ConeGeometry(65+rand()*45,110+rand()*80,5),mat(i%2?0x9bb4a0:0xacc6af),distant,(i%2?1:-1)*(130+rand()*110),20,-i*78);m.rotation.y=rand()*3}
const cloudMat=mat(0xf0f1dc,{transparent:true,opacity:.68});for(let i=0;i<28;i++){const g=new THREE.Group();g.position.set((rand()-.5)*500,85+rand()*60,80-rand()*1700);for(let j=0;j<3;j++)mesh(new THREE.IcosahedronGeometry(8+rand()*8,1),cloudMat,g,j*12,rand()*3,0).scale.set(1.6,.45,1);distant.add(g)}
// A handmade low-poly dragon with articulated wings, horns, feet and a segmented tail.
const dragon=new THREE.Group();scene.add(dragon);const orange=mat(0xdd804d),lightOrange=mat(0xf0ad68),belly=mat(0xf5d493),membrane=mat(0xbf664a,{side:THREE.DoubleSide}),horn=mat(0xf8e1a9),dark=mat(0x293e37);
mesh(new THREE.SphereGeometry(1,10,8),orange,dragon,0,0,0).scale.set(.9,.85,1.65);
mesh(new THREE.SphereGeometry(.8,10,8),belly,dragon,0,-.25,-.6).scale.set(.82,.8,1.45);
mesh(new THREE.SphereGeometry(.94,10,8),lightOrange,dragon,0,.7,-1.35).scale.set(1,.95,1.1);
mesh(new THREE.SphereGeometry(.68,8,6),lightOrange,dragon,0,.35,-2.05).scale.set(1,.6,.85);
for(const side of [-1,1]){mesh(new THREE.SphereGeometry(.23,8,6),horn,dragon,side*.77,.94,-1.69);mesh(new THREE.SphereGeometry(.11,8,6),dark,dragon,side*.9,.96,-1.8);const h=mesh(new THREE.ConeGeometry(.19,.8,5),horn,dragon,side*.58,1.58,-.93);h.rotation.z=side*-.35;h.rotation.x=.4;const foot=mesh(new THREE.SphereGeometry(.28,6,5),orange,dragon,side*.7,-.8,.6);foot.scale.set(1,1,1.5);mesh(new THREE.ConeGeometry(.13,.4,4),horn,dragon,side*.7,-.88,.25).rotation.x=-Math.PI/2}
const wings=[];for(const side of [-1,1]){const wing=new THREE.Group();wing.position.set(side*.65,.3,-.1);dragon.add(wing);const verts=[0,0,0,side*1.6,.7,-1.15,side*4.7,.2,-.45,side*3.3,-.05,.7,side*2.2,-.05,.4,side*1.3,-.1,1.35,0,0,.65];const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geometry.setIndex([0,1,2,0,2,3,0,3,4,0,4,5,0,5,6]);geometry.computeVertexNormals();mesh(geometry,membrane,wing);
for(const endpoint of [[side*1.6,.7,-1.15],[side*4.7,.2,-.45],[side*3.3,-.05,.7],[side*1.3,-.1,1.35]]){const end=new THREE.Vector3(...endpoint);const bone=mesh(new THREE.CylinderGeometry(.065,.12,end.length(),5),orange,wing);bone.position.copy(end.clone().multiplyScalar(.5));bone.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.normalize())}wings.push(wing)}
const tail=new THREE.Group();dragon.add(tail);for(let i=0;i<6;i++){mesh(new THREE.SphereGeometry(.48-i*.065,6,5),orange,tail,Math.sin(i*.4)*.3,-i*.065,1.2+i*.48);if(i<5)mesh(new THREE.ConeGeometry(.17-i*.017,.4,4),horn,tail,Math.sin(i*.4)*.3,.4-i*.1,1.2+i*.48)}
dragon.scale.setScalar(1.35);
// Flight course objects.
const course=new THREE.Group();scene.add(course);const rings=[],gems=[],targets=[],particles=[];
const gold=mat(0xf8c964,{emissive:0xdfa540,emissiveIntensity:.45,metalness:.45,roughness:.3});const crystal=mat(0xa7f4d9,{emissive:0x66d8bd,emissiveIntensity:.6,metalness:.25,roughness:.2});
function courseY(i){return 14+Math.sin(i*.8)*6}function courseX(i,z){return i===0?0:center(z)+Math.sin(i*.7)*10}
for(let i=0;i<26;i++){const z=-35-i*53;const r=mesh(new THREE.TorusGeometry(5,.22,8,48),gold,course,courseX(i,z),courseY(i),z);const aura=mesh(new THREE.TorusGeometry(5.45,.035,5,48),mat(0xfff0bb,{transparent:true,opacity:.6,emissive:0xffdd9c}),r);rings.push({mesh:r,passed:false,index:i});
for(let j=0;j<3;j++){const gem=mesh(new THREE.OctahedronGeometry(.75),crystal,course,r.position.x+(j-1)*1.8,r.position.y+(j===1?1:0),z+12+j*3);gems.push({mesh:gem,taken:false})}
if(i%3===1){const g=new THREE.Group();g.position.set(r.position.x+(i%2?6:-6),r.position.y,z-15);mesh(new THREE.TorusGeometry(1.7,.3,6,16),mat(0xa26947),g);mesh(new THREE.CircleGeometry(1.5,16),mat(0xf0b86e,{side:THREE.DoubleSide}),g);mesh(new THREE.TorusGeometry(.8,.08,5,16),mat(0xa46242),g);mesh(new THREE.SphereGeometry(.24,6,5),mat(0xb7603b),g,0,0,.3);course.add(g);targets.push({mesh:g,hit:false})}}
const keys=new Set();let mode='training',state='ready',elapsed=0,distance=0,score=0,ringCount=0,gemCount=0,targetCount=0,combo=0,energy=100,boostTime=0,lastFire=-9,invulnerable=0,toastTime=0,soundOn=false,audioCtx,finished=false;
let save={xp:0,best:0};try{save={...save,...JSON.parse(localStorage.getItem('dragonflight-save')||'{}')}}catch{}
function updateLevel(){$('level').textContent=`Lv. ${1+Math.floor(save.xp/500)} · ${save.xp>=500?'风之学徒':'初生之翼'}`}updateLevel();
const position=new THREE.Vector3(0,15,9);let velocityX=0,velocityY=0;const clock=new THREE.Clock();
function sound(freq=600,length=.12){if(!soundOn)return;try{audioCtx??=new AudioContext();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.55,audioCtx.currentTime+length);gain.gain.setValueAtTime(.07,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+length);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+length)}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTime=3}
function burst(p,color,count=16){for(let i=0;i<count;i++){const m=mesh(new THREE.IcosahedronGeometry(.1+Math.random()*.18,0),mat(color,{emissive:color,emissiveIntensity:.5}),scene,...p.toArray());particles.push({mesh:m,velocity:new THREE.Vector3((Math.random()-.5)*9,(Math.random()-.5)*9,(Math.random()-.5)*9),life:.6+Math.random()*.4})}}
function reset(){position.set(0,15,9);distance=elapsed=score=ringCount=gemCount=targetCount=combo=boostTime=0;energy=100;velocityX=velocityY=0;invulnerable=0;lastFire=-9;finished=false;keys.clear();canyon.position.z=0;distant.position.z=0;course.position.z=0;for(const r of rings){r.passed=false;r.mesh.visible=true}for(const g of gems){g.taken=false;g.mesh.visible=true}for(const t of targets){t.hit=false;t.mesh.visible=true}updateHud()}
function start(){reset();state='playing';document.body.classList.add('playing');$('live').classList.remove('hidden');$('modal').classList.add('hidden');toast(mode==='race'?'计时开始！90 秒内尽可能获得高分':mode==='explore'?'自由探索 · 享受风与山谷':'穿过金环，收集水晶，点亮 3 个靶标');sound(440,.25)}
function updateHud(){$('score').textContent=String(score).padStart(5,'0');$('ringsProgress').textContent=`${ringCount} / 8`;$('gemsProgress').textContent=`${gemCount} / 12`;$('targetsProgress').textContent=`${targetCount} / 3`;[$('ringsProgress'),$('gemsProgress'),$('targetsProgress')].forEach((e,i)=>e.parentElement.classList.toggle('complete',[ringCount>=8,gemCount>=12,targetCount>=3][i]));$('combo').textContent=combo>1?`${combo} 连环 · ×${Math.min(combo,5)}`:'自由翱翔';const time=mode==='race'?Math.max(0,90-elapsed):elapsed;$('timer').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;$('energyBar').style.width=`${energy}%`;$('energyNumber').textContent=`${Math.round(energy)}%`}
function finish(reason){if(finished)return;finished=true;state='ended';const xp=Math.max(20,Math.floor(score/10))+(reason==='训练完成'?500:0);save.xp+=xp;save.best=Math.max(save.best,score);try{localStorage.setItem('dragonflight-save',JSON.stringify(save))}catch{}updateLevel();$('modalLabel').textContent='A LITTLE BRAVER, A LITTLE HIGHER';$('modalTitle').textContent=reason;$('modalBody').innerHTML=`<p>每一次振翅，都是成长。阿焰已经迫不及待地想要再次出发了。</p><div class="stat-grid"><div><b>${score}</b><span>本次得分</span></div><div><b>+${xp}</b><span>成长经验</span></div><div><b>${save.best}</b><span>最高得分</span></div></div><p>穿环 ${ringCount} 次 · 水晶 ${gemCount} 枚 · 靶标 ${targetCount} 个</p>`;$('resume').textContent='再次出发 ↗';$('restart').textContent='返回营地';$('modal').classList.remove('hidden');sound(880,.5)}
function pause(help=false){if(state==='ended')return;if(state==='paused'){resume();return}const previous=state;state='paused';keys.clear();$('modal').dataset.previous=previous;$('modalLabel').textContent=help?'HOW TO FLY':'TAKE A BREATH';$('modalTitle').textContent=help?'跟着风，学会飞行':'让翅膀休息一下';$('modalBody').innerHTML='<p><b>W / ↑</b> 爬升，<b>S / ↓</b> 俯冲，<b>A D / ← →</b> 左右转向。小龙会自动向前飞。</p><p><b>空格</b> 振翅爬升 · <b>Shift</b> 消耗能量冲刺 · <b>F</b> 向前喷火（有效距离 42 米）。</p><p>穿过金环可得分，连续穿环提高倍率。水晶补充能量；靠近岩壁会打断连击。松开冲刺可恢复能量。</p>';$('resume').textContent=previous==='ready'?'准备好了':'继续飞行 ↗';$('restart').textContent='返回营地';$('modal').classList.remove('hidden')}
function resume(){if(state==='ended'){start();return}state=$('modal').dataset.previous||'playing';$('modal').classList.add('hidden')}
function camp(){if(!finished&&score>0){save.xp+=Math.floor(score/10);save.best=Math.max(save.best,score);try{localStorage.setItem('dragonflight-save',JSON.stringify(save))}catch{}updateLevel()}reset();state='ready';document.body.classList.remove('playing');$('live').classList.add('hidden');$('modal').classList.add('hidden')}
function fire(){if(state!=='playing'||elapsed-lastFire<.45||energy<8)return;lastFire=elapsed;energy-=8;sound(130,.2);const origin=position.clone().add(new THREE.Vector3(0,.4,-3));burst(origin,0xffa64e,20);for(const spark of particles.slice(-20)){spark.velocity.z=-35-Math.random()*25;spark.velocity.x*=.4;spark.velocity.y*=.4;spark.life=.65}for(const t of targets){const p=t.mesh.position.clone().add(course.position);const delta=p.clone().sub(position);if(!t.hit&&delta.z<0&&delta.z>-42&&Math.abs(delta.x)<5&&Math.abs(delta.y)<5){t.hit=true;t.mesh.visible=false;targetCount++;score+=250;burst(p,0xffd17c,24);toast('灯塔点亮！ +250');sound(780);break}}}
$('start').onclick=start;$('pause').onclick=()=>pause();$('help').onclick=()=>pause(true);$('resume').onclick=resume;$('restart').onclick=camp;$('sound').onclick=()=>{soundOn=!soundOn;$('sound').style.background=soundOn?'#ceddb6':'#f7f9ed55';$('sound').textContent=soundOn?'♪':'♫';$('sound').setAttribute('aria-label',soundOn?'关闭声音':'开启声音');toast(soundOn?'声音已开启':'声音已关闭');sound()};
document.querySelectorAll('.mode').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b===button));camp();$('missionTitle').textContent=mode==='training'?'初次展翼':mode==='explore'?'风的旅行者':'逐风竞速';$('missionDesc').textContent=mode==='race'?'90 秒，挑战你的峡谷最高分。':mode==='explore'?'没有倒计时，整个山谷都属于你。':'小小的勇气，成就大大的飞行。';$('hint').textContent=mode==='race'?'连续穿环，让每一秒都值得':'沿着光环，去更远的地方'});
const keyMap={arrowup:'w',arrowdown:'s',arrowleft:'a',arrowright:'d'};
addEventListener('keydown',e=>{let k=e.key.toLowerCase();k=keyMap[k]||k;if([' ','w','a','s','d','shift','escape','f'].includes(k))e.preventDefault();if(e.repeat&&['escape','f'].includes(k))return;if(k==='escape'){pause();return}if(k===' '&&state==='ready'){start();return}keys.add(k);if(k==='f')fire()});addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys.delete(keyMap[k]||k)});addEventListener('blur',()=>{keys.clear();if(state==='playing')pause()});
document.querySelectorAll('[data-key]').forEach(b=>{const clear=()=>keys.delete(b.dataset.key);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(state==='ready'&&b.dataset.key===' '){start();return}keys.add(b.dataset.key);if(b.dataset.key==='f')fire()});b.addEventListener('pointerup',clear);b.addEventListener('pointercancel',clear)});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;
if(state==='playing'){elapsed+=dt;const boosting=keys.has('shift')&&energy>1;const speed=boosting?49:25;boostTime+=boosting?dt:0;energy=THREE.MathUtils.clamp(energy+(boosting?-24:12)*dt,0,100);distance+=speed*dt;position.z=9-distance;const lateral=(keys.has('d')?1:0)-(keys.has('a')?1:0);const vertical=(keys.has('w')?1:0)-(keys.has('s')?1:0)+(keys.has(' ')?1.25:0);velocityX=THREE.MathUtils.damp(velocityX,lateral*18,5,dt);velocityY=THREE.MathUtils.damp(velocityY,vertical*13,5,dt);position.x+=velocityX*dt;position.y=THREE.MathUtils.clamp(position.y+velocityY*dt,0,64);
const localZ=position.z-canyon.position.z;const boundary=center(localZ);invulnerable-=dt;if(Math.abs(position.x-boundary)>29){position.x=THREE.MathUtils.clamp(position.x,boundary-29,boundary+29);velocityX*=-.6;if(invulnerable<=0){energy=Math.max(0,energy-18);combo=0;score=Math.max(0,score-50);invulnerable=1.5;burst(position,0xf8c591,12);toast('小心岩壁！返回峡谷中央');sound(90)}}
for(const r of rings){const p=r.mesh.position.clone().add(course.position);if(!r.passed&&position.z<p.z){r.passed=true;if(Math.hypot(position.x-p.x,position.y-p.y)<5.8){r.mesh.visible=false;ringCount++;combo++;const gain=100*Math.min(combo,5);score+=gain;energy=Math.min(100,energy+7);burst(p,0xffd376,24);toast(`完美穿环 +${gain}${combo>1?' · '+combo+' 连环':''}`);sound(540+Math.min(combo,5)*110)}else combo=0}}
for(const g of gems){if(!g.taken){const p=g.mesh.position.clone().add(course.position);if(p.distanceTo(position)<3.8){g.taken=true;g.mesh.visible=false;gemCount++;score+=30;energy=Math.min(100,energy+10);burst(p,0x9dffe1,8);sound(1100,.07)}}}
if(keys.has('f'))fire();if(mode==='training'&&ringCount>=8&&gemCount>=12&&targetCount>=3)finish('训练完成');if(mode==='race'&&elapsed>=90)finish('挑战完成');
if(position.z-course.position.z<-1395){course.position.z-=1378;canyon.position.z-=1378;distant.position.z-=1378;for(const r of rings){r.passed=false;r.mesh.visible=true}for(const g of gems){g.taken=false;g.mesh.visible=true}for(const t of targets){t.hit=false;t.mesh.visible=true}toast('新的一程 · 继续追风')}
updateHud();}
const flapping=state!=='paused'&&state!=='ended';if(flapping){const flap=Math.sin(time*(keys.has(' ')?12:5))*.32;wings[0].rotation.z=-flap-.06;wings[1].rotation.z=flap+.06;tail.rotation.y=Math.sin(time*2)*.13;dragon.rotation.z=THREE.MathUtils.damp(dragon.rotation.z,-velocityX*.026,5,dt);dragon.rotation.x=THREE.MathUtils.damp(dragon.rotation.x,-velocityY*.02,5,dt)}
dragon.position.copy(position);dragon.position.y+=Math.sin(time*3)*.15;dragon.visible=invulnerable>0?Math.sin(time*24)>-.5:true;
const ready=state==='ready'||(state==='paused'&&$('modal').dataset.previous==='ready');const desiredCamera=position.clone().add(new THREE.Vector3(ready?-5:0,ready?7:5,ready?25:19));camera.position.lerp(desiredCamera,1-Math.exp(-dt*3));camera.lookAt(position.x+(ready?5:velocityX*.3),position.y+(ready?0:1),position.z-(ready?35:24));camera.fov=THREE.MathUtils.damp(camera.fov,keys.has('shift')&&state==='playing'&&energy>1?65:53,3,dt);camera.updateProjectionMatrix();
for(const g of gems){if(flapping)g.mesh.rotation.y+=dt*1.4}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){scene.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();particles.splice(i,1)}}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show')}
renderer.render(scene,camera)}
camera.position.set(-5,22,34);animate();
// Read-only diagnostics make smoke testing deterministic without modifying gameplay.
window.dragonflight={getState:()=>({state,mode,score,ringCount,gemCount,targetCount,energy,elapsed,distance,position:position.toArray(),saved:{...save},objects:scene.children.length})};
