import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const $=s=>document.querySelector(s), R=4, SZ=1.13;
let seed=9271;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const scene=new THREE.Scene();scene.background=new THREE.Color('#14231f');scene.fog=new THREE.FogExp2('#14231f',.023);
const camera=new THREE.PerspectiveCamera(innerWidth<600?65:36,innerWidth/innerHeight,.1,120);camera.position.set(12,16,19);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#world').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.43;controls.minPolarAngle=.3;controls.minDistance=14;controls.maxDistance=35;controls.enablePan=false;controls.target.set(0,0,0);controls.update();
scene.add(new THREE.HemisphereLight('#e9eacc','#1b3930',2.4));const sun=new THREE.DirectionalLight('#ffdcac',3.2);sun.position.set(-6,15,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;sun.shadow.bias=-.001;scene.add(sun);const rim=new THREE.DirectionalLight('#7ac3a9',2);rim.position.set(8,5,-9);scene.add(rim);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.85,...opts});const mats={bark:mat('#514633'),stem:mat('#d6d7a2'),leaf:mat('#48634b'),leaf2:mat('#61805a'),leaf3:mat('#7c9263'),mint:mat('#acd1a2',{emissive:'#719666',emissiveIntensity:.22}),red:mat('#bd6a58'),rock:mat('#71817a'),water:mat('#639b9a',{metalness:.4,roughness:.2}),gold:mat('#b4ae6f')};
const terrain=new THREE.Group();scene.add(terrain);const pickables=[],tiles=[],effects=[];const geoHex=new THREE.CylinderGeometry(SZ,SZ,.42,6);const diskGeo=new THREE.CylinderGeometry(SZ*.95,SZ*.95,.07,6);const coord=(q,r)=>new THREE.Vector3(Math.sqrt(3)*SZ*(q+r/2),0,1.5*SZ*r);const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];const neighbor=t=>tiles.filter(a=>dirs.some(([q,r])=>a.q===t.q+q&&a.r===t.r+r));
function mesh(geometry,material,parent,x=0,y=0,z=0){let m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function mushroom(g,x,z,s,color){const root=new THREE.Group();root.position.set(x,0,z);root.scale.setScalar(s);g.add(root);mesh(new THREE.CylinderGeometry(.09,.14,.58,8),mats.stem,root,0,.3);const cap=mesh(new THREE.SphereGeometry(.4,14,8,0,Math.PI*2,0,Math.PI*.56),color,root,0,.59);cap.scale.y=.56;mesh(new THREE.CylinderGeometry(.395,.25,.035,16),mats.stem,root,0,.565);for(let i=0;i<5;i++){let a=i*2.4,rr=.12+(i%2)*.14;let spot=mesh(new THREE.SphereGeometry(.045,6,4),mats.stem,root,Math.cos(a)*rr,.77-rr*.27,Math.sin(a)*rr);spot.scale.y=.2}return root}
function tree(g,x,z,s=1,gold=false){let group=new THREE.Group();g.add(group);group.position.set(x,0,z);group.scale.setScalar(s);mesh(new THREE.CylinderGeometry(.055,.14,1.65,6),mats.bark,group,0,.78);for(let i=0;i<3;i++){let a=i*2.1;let branch=mesh(new THREE.CylinderGeometry(.025,.05,.8,5),mats.bark,group,Math.cos(a)*.22,1.15,Math.sin(a)*.22);branch.rotation.z=Math.cos(a)*.55;branch.rotation.x=Math.sin(a)*.55}for(let i=0;i<4;i++){let a=i*2.1;let crown=mesh(new THREE.IcosahedronGeometry(.64,1),gold?mats.gold:[mats.leaf,mats.leaf2,mats.leaf3][i%3],group,Math.cos(a)*.33,1.45+(i===3?.55:0),Math.sin(a)*.33);crown.scale.set(1,.8,1)}return group}
function pine(g,x,z,s){const gr=new THREE.Group();g.add(gr);gr.position.set(x,0,z);gr.scale.setScalar(s);mesh(new THREE.CylinderGeometry(.045,.10,1.3,5),mats.bark,gr,0,.65);for(let i=0;i<3;i++)mesh(new THREE.ConeGeometry(.58-i*.12,.9,6),i%2?mats.leaf2:mats.leaf,gr,0,.8+i*.38);return gr}
function outline(radius,color,opacity){let pts=[];for(let i=0;i<=6;i++){let a=i*Math.PI/3;pts.push(new THREE.Vector3(Math.sin(a)*radius,0,Math.cos(a)*radius))}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity}))}
for(let q=-R;q<=R;q++)for(let r=-R;r<=R;r++){if(Math.abs(q+r)>R)continue;let p=coord(q,r),dist=Math.max(Math.abs(q),Math.abs(r),Math.abs(q+r));let height=.15+rand()*.23;let type=q===0&&r===0?'ancient':rand()<.15?'spring':rand()<.24?'grove':'meadow';let t={id:tiles.length,q,r,x:p.x,z:p.z,h:height,type,owner:0,building:null,hp:2,root:new THREE.Group(),decor:new THREE.Group(),units:new THREE.Group()};t.root.position.set(p.x,height,p.z);terrain.add(t.root);let base=mesh(geoHex,mat(['#3b5141','#425947','#3a5145','#4b6049'][Math.floor(rand()*4)]),t.root,0,-.24);base.userData.tile=t;pickables.push(base);t.top=mesh(diskGeo,mat('#637454'),t.root,0,0);t.top.userData.tile=t;pickables.push(t.top);t.border=outline(SZ*.96,'#8aa576',.23);t.border.position.y=.043;t.root.add(t.border,t.decor,t.units);t.decor.position.y=.04;t.units.position.y=.05;
if(type==='spring'){let pond=mesh(new THREE.CylinderGeometry(.62,.62,.055,12),mats.water,t.decor,0,.05);for(let i=0;i<6;i++){let a=i*1.05;let rock=mesh(new THREE.DodecahedronGeometry(.13+rand()*.1),mats.rock,t.decor,Math.cos(a)*.65,.1,Math.sin(a)*.65);rock.scale.y=.6}}else if(type==='ancient'){tree(t.decor,0,0,1.55,true);let ring=mesh(new THREE.TorusGeometry(.78,.025,5,40),mats.gold,t.decor,0,.12);ring.rotation.x=Math.PI/2}else {let n=type==='grove'?3:rand()<.5?1:0;for(let j=0;j<n;j++){let a=j*2.5+rand();(rand()<.45?pine:tree)(t.decor,Math.cos(a)*.5,Math.sin(a)*.5,.7+rand()*.3)}for(let j=0;j<5;j++){let a=rand()*6.28,rr=.25+rand()*.6;let grass=mesh(new THREE.ConeGeometry(.035,.15+rand()*.12,3),mats.leaf3,t.decor,Math.cos(a)*rr,.08,Math.sin(a)*rr);grass.rotation.z=rand()*.4}if(rand()<.4){const stone=mesh(new THREE.DodecahedronGeometry(.17),mats.rock,t.decor,.5,.09,-.2);stone.scale.y=.6}}
tiles.push(t)}
// Suspended soil and little roots beneath the forest.
for(let i=0;i<75;i++){let a=rand()*6.28,rr=Math.sqrt(rand())*7.1;let y=-.75-rand()*.55;const rock=mesh(new THREE.DodecahedronGeometry(.5+rand()*.6,0),mat(i%3?'#303e32':'#435040'),scene,Math.cos(a)*rr,y,Math.sin(a)*rr);rock.scale.y=.6+rand()*.9}
const ground=mesh(new THREE.PlaneGeometry(200,200),mat('#14251f'),scene,0,-2.8);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
const motesGeo=new THREE.BufferGeometry();let positions=new Float32Array(180*3);for(let i=0;i<180;i++){positions[i*3]=(rand()-.5)*23;positions[i*3+1]=rand()*7;positions[i*3+2]=(rand()-.5)*21}motesGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const motes=new THREE.Points(motesGeo,new THREE.PointsMaterial({color:'#d8e7ab',size:.037,transparent:true,opacity:.7}));scene.add(motes);
const selectionRing=outline(SZ*1.015,'#e0f7bf',1);selectionRing.position.y=.13;scene.add(selectionRing);const glow=mesh(new THREE.RingGeometry(.66,.71,48),new THREE.MeshBasicMaterial({color:'#d0e7a0',side:THREE.DoubleSide,transparent:true,opacity:.6}),scene);glow.rotation.x=-Math.PI/2;
const playerHome=tiles.find(t=>t.q===-2&&t.r===1),enemyHome=tiles.find(t=>t.q===3&&t.r===-2),ancient=tiles.find(t=>t.type==='ancient');let state,selected=playerHome,action='expand',toastTimer,events=[];const tendrils=new THREE.Group();scene.add(tendrils);
function disposeGroup(g){while(g.children.length){const o=g.children[0];o.traverse(x=>{if(x.geometry)x.geometry.dispose()});g.remove(o)}}
function refreshTile(t){t.top.material.color.set(t.owner===1?'#7b9964':t.owner===2?'#876657':t.type==='spring'?'#586e5b':'#596e4e');t.border.material.color.set(t.owner===1?'#b4d795':t.owner===2?'#d7977b':'#849872');t.border.material.opacity=t.owner?.72:.23;disposeGroup(t.units);if(t.owner){let col=t.owner===1?mats.mint:mats.red;let home=t===playerHome||t===enemyHome;if(home){t.decor.visible=false;for(let i=0;i<6;i++){let a=i*2.4;mushroom(t.units,Math.cos(a)*.53,Math.sin(a)*.53,.55+rand()*.25,col)}let big=mushroom(t.units,0,0,1.9,col);mesh(new THREE.SphereGeometry(.047,8,6),mat('#253e29'),big,-.057,.4,.115);mesh(new THREE.SphereGeometry(.047,8,6),mat('#253e29'),big,.057,.4,.115)}else{t.decor.visible=true;mushroom(t.units,-.35,.36,.95,col);mushroom(t.units,.26,.38,.55,col)}if(t.building==='nursery'){for(let i=0;i<4;i++)mushroom(t.units,(i-1.5)*.2,-.25,.6,col)}if(t.building==='guard'){const tower=mesh(new THREE.CylinderGeometry(.2,.29,.65,6),mats.rock,t.units,.2,.35,0);mesh(new THREE.ConeGeometry(.4,.38,6),col,t.units,.2,.85,0);let halo=mesh(new THREE.TorusGeometry(.48,.035,6,6),mats.gold,t.units,.2,.32,0);halo.rotation.x=Math.PI/2}}}
function updateThreads(){disposeGroup(tendrils);for(const t of tiles.filter(t=>t.owner)){for(const n of neighbor(t).filter(n=>n.owner===t.owner&&n.id>t.id)){let a=new THREE.Vector3(t.x,t.h+.08,t.z),b=new THREE.Vector3(n.x,n.h+.08,n.z);let mid=a.clone().lerp(b,.5);mid.y+=.06;let c=new THREE.QuadraticBezierCurve3(a,mid,b);mesh(new THREE.TubeGeometry(c,10,.025,4,false),t.owner===1?mats.mint:mats.red,tendrils)}}}
function counts(){return {p:tiles.filter(t=>t.owner===1),e:tiles.filter(t=>t.owner===2)}}
function income(){let p=counts().p;return {spores:p.reduce((a,t)=>a+(t===playerHome?8:t.type==='ancient'?10:2)+(t.building==='nursery'?7:0),0),dew:3+p.filter(t=>t.type==='spring').length*6}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3300)}
function log(s){events.unshift({s,turn:state.turn});events=events.slice(0,3);$('#log').innerHTML=events.map(e=>`<p><i></i><span>${e.s}<small>第 ${e.turn} 回合</small></span></p>`).join('')}
function updateUI(){let {p,e}=counts(),inc=income();$('#spores').textContent=state.spores;$('#dew').textContent=state.dew;$('#lands').innerHTML=p.length+' <b>/ 61</b>';$('#income').textContent=`+${inc.spores} / 回合`;$('#dewIncome').textContent=`+${inc.dew} / 回合`;$('#pcount').textContent=p.length;$('#ecount').textContent=e.length;$('#balanceP').style.width=p.length/(p.length+e.length)*100+'%';$('#balanceE').style.width=e.length/(p.length+e.length)*100+'%';$('#progress1').textContent=`${Math.min(p.length,10)} / 10 片已共生`;$('#progressbar').style.width=Math.min(p.length/10,1)*100+'%';$('#goal1').textContent=p.length>=10?'●':'○';$('#goal2').textContent=ancient.owner===1?'●':'○';$('#goal3').textContent=p.filter(t=>t.building==='nursery').length>=3?'●':'○';$('#turn').textContent=String(state.turn).padStart(2,'0');$('#weather').textContent=state.turn%4===0?'甘霖滋养':'薄雾初晴';select(selected);updateThreads();updateLabels();}
function select(t){selected=t;selectionRing.position.set(t.x,t.h+.12,t.z);glow.position.set(t.x,t.h+.095,t.z);const own=t.owner===1,home=t===playerHome||t===enemyHome;$('#selectionTag').textContent=own?'YOUR SYMBIOTIC NETWORK':t.owner===2?'RIVAL TERRITORY':'UNDISCOVERED WOODLAND';$('#selectionTitle').textContent=home?(t===playerHome?'翡翠母巢':'绯红母巢'):t.building==='nursery'?'孢子苗圃':t.building==='guard'?'菌盖哨塔':({meadow:'苔藓草甸',grove:'幽静林地',spring:'月露泉眼',ancient:'古老灵树'}[t.type]);$('#selectionIcon').textContent=t.type==='spring'?'◈':t.type==='ancient'?'♜':t.building==='guard'?'⛨':'♧';$('#selectionDesc').textContent=home?'一切共生的起点。菌丝在此汇聚，生机由此延伸。':t.owner===2?`连接邻近菌群后可进攻。当前攻击力 ${attack(t)}，敌方防御 ${t.hp}。`:t.owner===1?'菌丝已与土地连接。建造苗圃或守卫，培育你的森林。':neighbor(t).some(n=>n.owner===1)?'菌丝能够抵达这里。花费 25 孢子，让生命继续蔓延。':'尚未与菌庭连接。先扩张到相邻地块，延伸共生网络。';$('#selectionYield').textContent=t.type==='spring'?'◈ +6 露水':`✦ +${t===playerHome?8:t.type==='ancient'?10:2} 孢子`;$('#selectionDefense').textContent=`⬡ 防御 ${t.hp}`;$('#selectionOwner').textContent=t.owner===1?'● 翡翠菌庭':t.owner===2?'● 绯红孢群':'○ 无主之地';}
function burst(t,color){for(let i=0;i<18;i++){let p=mesh(new THREE.SphereGeometry(.035,4,4),new THREE.MeshBasicMaterial({color,transparent:true}),scene,t.x,t.h+.4,t.z);effects.push({p,life:1,v:new THREE.Vector3((Math.random()-.5)*.06,Math.random()*.07+.01,(Math.random()-.5)*.06)})}}
function attack(t){return 2+neighbor(t).filter(n=>n.owner===1).length*2+(state.dew>=10?2:0)+Math.min(3,counts().p.filter(n=>n.building==='nursery').length)}
function doAction(a){action=a;document.querySelectorAll('.action').forEach(e=>e.classList.toggle('active',e.dataset.action===a));if(state.over)return toast('旅程已结束，可在设置中开启新的森林。');let t=selected;if(a==='bloom'){if(state.dew<30)return toast('需要 30 露水，连接泉眼可获得更多露水。');state.dew-=30;const amount=counts().p.length*6;state.spores+=amount;counts().p.forEach(t=>burst(t,'#e4efa1'));log(`生命绽放！收获 ${amount} 孢子。`);toast(`全境共鸣 · +${amount} 孢子`)}else if(a==='expand'){if(t.owner===1)return toast('选择相邻的中立或敌方领地，再点击菌丝蔓延。');if(!neighbor(t).some(n=>n.owner===1))return toast('菌丝尚未抵达，请选择与菌庭相邻的领地。');if(state.spores<25)return toast('需要 25 孢子，结束回合可收获资源。');state.spores-=25;if(t.owner===2){const power=attack(t);if(state.dew>=10)state.dew-=10;if(power<t.hp){t.hp-=power;log(`菌丝冲击削弱敌方，剩余防御 ${t.hp}。`);toast('敌方防线已削弱，继续进攻即可夺取。');burst(t,'#db9d79');updateUI();return}log('成功夺取绯红孢群的领地！')}else log(t.type==='ancient'?'古老灵树苏醒，共生网络获得祝福。':'新的土地加入共生网络。');t.owner=1;t.hp=t===enemyHome?5:3;t.building=null;if(t.type==='ancient'){state.dew+=20;state.spores+=30}refreshTile(t);burst(t,'#d8f3ad');toast(t.type==='ancient'?'古树的馈赠 · +30 孢子 / +20 露水':'共生连接成功 · 新领地已加入')}else{if(t.owner!==1)return toast('请先选择自己的领地进行建造。');if(t===playerHome)return toast('母巢不能建造，请选择另一片共生领地。');if(t.building)return toast('这里已有建筑，请选择其他领地。');const cost=a==='nursery'?[40,10]:[35,15];if(state.spores<cost[0]||state.dew<cost[1])return toast(`资源不足，需要 ${cost[0]} 孢子和 ${cost[1]} 露水。`);state.spores-=cost[0];state.dew-=cost[1];t.building=a;t.hp=a==='guard'?12:4;refreshTile(t);burst(t,'#d8f3ad');log(a==='nursery'?'孢子苗圃落成，每回合额外产出 7 孢子。':'菌盖守卫就位，防御提升至 12。');toast(a==='nursery'?'苗圃建造完成 · +7 孢子 / 回合':'菌盖守卫建成 · 防御提升至 12')}updateUI();checkEnd();saveGame(false)}
function enemyTurn(){const es=counts().e;let candidates=[];for(let e of es)for(let n of neighbor(e))if(n.owner!==2&&!candidates.includes(n))candidates.push(n);candidates.sort((a,b)=>{const score=t=>(t.owner===1?state.turn>4?5:-8:1)+(t.type==='ancient'?4:0)-(Math.abs(t.q-playerHome.q)+Math.abs(t.r-playerHome.r))*.1;return score(b)-score(a)});const t=candidates[0];if(!t)return;if(t.owner===1){let power=2+neighbor(t).filter(n=>n.owner===2).length*2;if(t.hp>power){t.hp-=Math.ceil(power/2);log('菌盖守卫抵御了绯红孢群的冲击。');burst(t,'#dfb591')}else{t.owner=2;t.building=null;t.hp=4;refreshTile(t);burst(t,'#db8b73');log('绯红孢群侵占了一片共生领地。')}}else{t.owner=2;t.hp=3+Math.floor(state.turn/5);refreshTile(t);burst(t,'#d69779');log('绯红孢群向森林深处蔓延。')}$('#enemyMood').textContent=state.turn>4?'正在争夺共生边界':'正在悄然生长'}
function endTurn(){if(state.over)return toast('本次旅程已结束。');const inc=income();state.turn++;state.spores+=inc.spores;state.dew+=inc.dew;for(let t of counts().p)t.hp=Math.min(t.building==='guard'?12:t===playerHome?8:4,t.hp+1);if(state.turn%4===0){state.dew+=20;log('甘霖降临，全境获得 20 露水。')}enemyTurn();updateUI();checkEnd();saveGame(false);toast(`第 ${state.turn} 回合 · +${inc.spores} 孢子 / +${inc.dew+(state.turn%4===0?20:0)} 露水`)}
function checkEnd(){if(state.over)return;if(playerHome.owner!==1||!counts().p.length){state.over=true;showResult(false)}else if(counts().p.length>=31||enemyHome.owner===1){state.over=true;showResult(true)}}
function showResult(win){setTimeout(()=>{openModal();$('.modal h2').textContent=win?'森林的每一处，都记得你的名字。':'森林暂归沉寂，孢子仍有希望。';$('.modal>p').textContent=win?`共生之胜！你在 ${state.turn} 回合内连接了 ${counts().p.length} 片领地，让生命重新流动。可以保存这片森林，或重新开始另一场旅程。`:'母巢被绯红孢群占领。下一次试试先建造苗圃，再在边界部署菌盖守卫。';$('#startGame').textContent='返回森林 →'},700)}
const labels=[];for(const [t,name,cls] of [[playerHome,'♧ 翡翠母巢',''],[enemyHome,'♧ 绯红母巢','enemy'],[ancient,'✧ 古老灵树','sacred']]){let el=document.createElement('div');el.className='map-label '+cls;el.textContent=name;$('#labels').appendChild(el);labels.push({t,el})}function updateLabels(){for(let {t,el} of labels){let p=new THREE.Vector3(t.x,t.h+(t===ancient?3.4:1.85),t.z).project(camera);el.style.left=(p.x*.5+.5)*innerWidth+'px';el.style.top=(-p.y*.5+.5)*innerHeight+'px';el.style.display=p.z<1?'block':'none'}}
function reset(){state={spores:120,dew:60,turn:1,over:false};events=[];for(let t of tiles){t.owner=0;t.building=null;t.hp=2;t.decor.visible=true}playerHome.owner=1;playerHome.hp=8;enemyHome.owner=2;enemyHome.hp=10;for(let t of tiles.filter(t=>(t.q===-3&&t.r===1)||(t.q===-2&&t.r===2))){t.owner=1;t.hp=4}for(let t of tiles.filter(t=>(t.q===2&&t.r===-2)||(t.q===3&&t.r===-3))){t.owner=2;t.hp=4}tiles.forEach(refreshTile);selected=playerHome;log('你的菌庭在晨光中苏醒。');updateUI()}
function saveGame(feedback=true){try{localStorage.setItem('mycelium-v1',JSON.stringify({state,tiles:tiles.map(({id,owner,building,hp})=>({id,owner,building,hp})),events}));if(feedback)toast('森林进度已保存。')}catch{if(feedback)toast('浏览器未允许保存，请保持页面打开。')}}function loadGame(){try{const data=JSON.parse(localStorage.getItem('mycelium-v1'));if(!data||!data.state||data.tiles.length!==61)return toast('还没有保存的森林。');state=data.state;events=data.events||[];data.tiles.forEach(d=>{Object.assign(tiles[d.id],d);refreshTile(tiles[d.id])});selected=playerHome;updateUI();log('共生网络恢复，欢迎回到森林。');closeModal();toast('已恢复保存的进度。')}catch{toast('存档无法读取，请开始新的旅程。')}}
function openModal(){$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
$('#help').onclick=$('#guide').onclick=$('#settings').onclick=openModal;$('#closeModal').onclick=$('#startGame').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#save').onclick=()=>saveGame();$('#load').onclick=loadGame;$('#restart').onclick=()=>{reset();closeModal();toast('一颗新的孢子，另一场森林旅程。')};$('#endTurn').onclick=endTurn;document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>doAction(el.dataset.action));
let down=null;const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(mouse,camera);let hit=raycaster.intersectObjects(pickables)[0];if(hit){select(hit.object.userData.tile);burst(selected,'#e2efb1')}down=null});renderer.domElement.addEventListener('pointermove',e=>{mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(mouse,camera);renderer.domElement.style.cursor=raycaster.intersectObjects(pickables).length?'pointer':'grab'});
function zoom(f){const d=camera.position.clone().sub(controls.target);d.multiplyScalar(f);d.clampLength(14,35);camera.position.copy(controls.target).add(d);controls.update()}$('#zoomIn').onclick=()=>zoom(.88);$('#zoomOut').onclick=()=>zoom(1.12);$('#resetCamera').onclick=()=>{camera.position.set(12,16,19);controls.target.set(0,0,0);controls.update()};$('#focus').onclick=()=>{controls.target.set(selected.x,0,selected.z);controls.update()};window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(!$('#modal').classList.contains('hidden'))return;if(['1','2','3','4'].includes(e.key))doAction(['expand','nursery','guard','bloom'][+e.key-1]);if(e.code==='Space'){e.preventDefault();endTurn()}});
let audioContext=null,audioGain=null;$('#sound').onclick=async()=>{if(!audioContext){audioContext=new AudioContext();audioGain=audioContext.createGain();audioGain.gain.value=0;audioGain.connect(audioContext.destination);[130.81,196,261.63,329.63].forEach((f,i)=>{let osc=audioContext.createOscillator(),g=audioContext.createGain();osc.frequency.value=f;g.gain.value=.18/(i+1);osc.connect(g);g.connect(audioGain);osc.start()})}if(audioContext.state==='suspended'){await audioContext.resume();audioGain.gain.value=.045;$('#sound').textContent='♫';toast('林间共鸣已开启')}else if(audioGain.gain.value){audioGain.gain.value=0;$('#sound').textContent='♪';toast('环境音已关闭')}else{audioGain.gain.value=.045;$('#sound').textContent='♫';toast('林间共鸣已开启')}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<600?65:36;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});reset();let time=0;function animate(){requestAnimationFrame(animate);time+=.01;controls.update();motes.rotation.y=Math.sin(time*.15)*.08;glow.material.opacity=.4+Math.sin(time*3)*.16;selectionRing.material.opacity=.75+Math.sin(time*4)*.25;for(let i=effects.length-1;i>=0;i--){let e=effects[i];e.life-=.018;e.p.position.add(e.v);e.p.material.opacity=e.life;if(e.life<=0){scene.remove(e.p);e.p.geometry.dispose();e.p.material.dispose();effects.splice(i,1)}}updateLabels();renderer.render(scene,camera)}animate();window.__game={get state(){return state},tiles,select,doAction,endTurn,reset,counts,income};
