import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s);
const canvas=$('#world');
const scene=new THREE.Scene();scene.background=new THREE.Color('#849785');scene.fog=new THREE.FogExp2('#8d9d87',.014);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.24;
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,180);let angle=.68,zoom=38;const focus=new THREE.Vector3(0,0,0);scene.add(new THREE.HemisphereLight('#dce7ba','#405e47',2.4));const sun=new THREE.DirectionalLight('#fff3b7',3.1);sun.position.set(-18,32,-8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-38,right:38,top:38,bottom:-38,far:90});sun.shadow.normalBias=.06;scene.add(sun);scene.add(new THREE.AmbientLight('#8bac90',.35));
let seed=531;function rnd(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}const mat=(c,o={})=>new THREE.MeshStandardMaterial({color:c,roughness:.95,...o});const materials={ground:mat('#5e7650'),bark:mat('#5b5140'),dark:mat('#172f34'),roof:mat('#5b5142'),wood:mat('#9a8460'),rock:mat('#8c9980'),path:mat('#b7b38a')};
function mesh(g,m,x=0,y=0,z=0,parent=scene){const a=new THREE.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}function box(w,h,d,m,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p)}function sphere(r,m,x,y,z,p){return mesh(new THREE.IcosahedronGeometry(r,1),m,x,y,z,p)}function cylinder(r1,r2,h,m,x,y,z,p,n=8){return mesh(new THREE.CylinderGeometry(r1,r2,h,n),m,x,y,z,p)}
const ground=mesh(new THREE.PlaneGeometry(150,150),materials.ground);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.name='ground';
// The woodland is hand-composed around navigable clearings.
const treeMats=['#344f3b','#456443','#536e44','#617d4b','#768957'].map(c=>mat(c));const trees=[];function tree(x,z,h=6){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);cylinder(.18,.38,h*.7,materials.bark,0,h*.35,0,g);const m=treeMats[Math.floor(rnd()*treeMats.length)];for(let i=0;i<3;i++){const c=mesh(new THREE.ConeGeometry(h*(.28-i*.055),h*.53,7),m,0,h*(.47+i*.2),0,g);c.rotation.y=rnd()*6}trees.push({x,z,r:.6});return g}
for(let i=0;i<210;i++){const x=(rnd()-.5)*90,z=(rnd()-.5)*85;const clear=Math.abs(x)<12&&z>-14&&z<15;const stream=Math.abs(x-(15+Math.sin(z*.13)*3))<3.2;if(!clear&&!stream&&Math.hypot(x+12,z+13)>5.2)tree(x,z,4+rnd()*7)}
for(const [x,z,h] of [[-10,5,8],[-11,-1,8],[-8,-10,7],[10,-9,7],[9,8,6],[-16,10,9],[21,8,8],[-20,-6,10],[-4,-18,9],[7,-17,7]])tree(x,z,h);
// Soft ochre footpaths, made of overlapping low flat stones.
function trail(points,width=1.2){for(let i=0;i<points.length-1;i++){const a=new THREE.Vector3(points[i][0],.026,points[i][1]),b=new THREE.Vector3(points[i+1][0],.026,points[i+1][1]);const d=a.distanceTo(b);for(let t=0;t<d;t+=.55){const p=a.clone().lerp(b,t/d);const s=cylinder(width*(.9+rnd()*.16),width, .035,materials.path,p.x,.025,p.z,scene,9);s.rotation.y=rnd()*6}}}
trail([[-4,18],[-3,12],[-1,7],[0,3],[2,-2],[0,-6],[-4,-10],[-12,-13]],1.45);trail([[0,3],[6,3],[11,2],[18,1],[23,-6]],1.05);trail([[0,-6],[5,-11],[8,-17]],.8);
// Curving river along the east side.
const riverShape=new THREE.Shape();for(let i=0;i<=80;i++){const z=-42+i;const x=15+Math.sin(z*.13)*3; i===0?riverShape.moveTo(x-1.5,z):riverShape.lineTo(x-1.5,z)}for(let i=80;i>=0;i--){const z=-42+i;riverShape.lineTo(16.5+Math.sin(z*.13)*3,z)}riverShape.closePath();const water=mesh(new THREE.ShapeGeometry(riverShape),mat('#7baba2',{metalness:.25,roughness:.3,transparent:true,opacity:.9}));water.rotation.x=Math.PI/2;water.position.y=.055;water.material.side=THREE.DoubleSide;
for(let i=0;i<45;i++){let z=rnd()*70-35,x=15+Math.sin(z*.13)*3;let stone=sphere(.25+rnd()*.55,materials.rock,x+(rnd()>.5?1.8:-1.8),.1,z);stone.scale.y=.55}
const bridge=new THREE.Group();bridge.position.set(15,0,1);scene.add(bridge);for(let i=0;i<13;i++)box(.43,.16,2.5,materials.wood,-2.7+i*.44,.35,0,bridge);for(const z of [-1.15,1.15]){for(const x of [-2.7,2.7])box(.14,1.3,.14,materials.bark,x,.9,z,bridge);box(5.5,.12,.13,materials.wood,0,1.3,z,bridge)}
// Ranger cabin and warm, inhabited details.
const cabin=new THREE.Group();cabin.position.set(-4,0,-6);scene.add(cabin);box(4,2.6,3.5,mat('#807352'),0,1.3,0,cabin);for(let i=0;i<10;i++){box(4.1,.07,3.6,materials.bark,0,.2+i*.26,0,cabin)}const roof=mesh(new THREE.ConeGeometry(3.2,1.9,4),mat('#535d48'),0,3.4,0,cabin);roof.rotation.y=Math.PI/4;roof.scale.z=.96;box(.9,1.8,.09,mat('#354639'),.6,.9,1.79,cabin);box(.9,.7,.1,mat('#eedca0',{emissive:'#e7c665',emissiveIntensity:.5}),-1,.0+1.5,1.81,cabin);box(.06,.7,.12,materials.bark,-1,1.5,1.85,cabin);box(.9,.06,.12,materials.bark,-1,1.5,1.85,cabin);box(4.6,.18,1.1,materials.wood,0,.15,2.1,cabin);box(.5,2,.5,materials.rock,1.2,3,-.7,cabin);
// Tent at the campsite.
const tent=new THREE.Group();tent.position.set(4.6,0,-3);tent.rotation.y=-.4;scene.add(tent);const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.Float32BufferAttribute([-1.5,0,1.8,0,2,1.8,0,2,-1.8,-1.5,0,1.8,0,2,-1.8,-1.5,0,-1.8,1.5,0,1.8,0,2,-1.8,0,2,1.8,1.5,0,1.8,1.5,0,-1.8,0,2,-1.8],3));tg.computeVertexNormals();mesh(tg,mat('#b9a16a',{side:THREE.DoubleSide}),0,0,0,tent);const face=new THREE.BufferGeometry();face.setAttribute('position',new THREE.Float32BufferAttribute([-1.5,0,1.81,0,2,1.81,1.5,0,1.81],3));face.computeVertexNormals();mesh(face,mat('#575b3e',{side:THREE.DoubleSide}),0,0,0,tent);box(.06,2.15,.06,materials.bark,0,1,1.85,tent);
const fire=new THREE.Group();fire.position.set(1.1,0,1);scene.add(fire);for(let i=0;i<10;i++){const a=i/10*Math.PI*2;const s=sphere(.25,materials.rock,Math.cos(a)*.8,.16,Math.sin(a)*.8,fire);s.scale.y=.65}for(let i=0;i<3;i++){const log=cylinder(.13,.13,1.25,materials.bark,0,.17,0,fire);log.rotation.z=Math.PI/2;log.rotation.y=i*1.1}const flame=mesh(new THREE.ConeGeometry(.32,.7,6),mat('#f2bd63',{emissive:'#ec8e37',emissiveIntensity:1}),0,.53,0,fire);const light=new THREE.PointLight('#ffbf61',5,7);light.position.set(1,1.1,1);scene.add(light);
for(const [x,z] of [[-1.5,1],[2.3,3]]){const l=cylinder(.3,.3,2.2,materials.bark,x,.3,z);l.rotation.z=Math.PI/2;l.rotation.y=.7}box(1.2,.8,.9,materials.wood,5,.4,1);box(.8,.55,.7,mat('#898361'),5.2,1.06,1.1);
// Old mine, sealed by a numbered lock.
const mine=new THREE.Group();mine.position.set(-12,0,-13);scene.add(mine);sphere(3,mat('#727d64'),0,.65,-1,mine);box(2.5,2.6,.15,mat('#182d29'),0,1.1,1.5,mine);for(const x of [-1.4,1.4])box(.4,3,.5,materials.bark,x,1.4,1.65,mine);box(3.25,.4,.5,materials.bark,0,2.85,1.65,mine);const mineBars=[];for(let i=0;i<4;i++)mineBars.push(box(.12,2.5,.1,materials.wood,-.95+i*.64,1.3,1.77,mine));box(.35,.4,.2,mat('#bdab67'),0,1.2,1.94,mine);
// Wildflowers, ferns, mushrooms and moss-covered boulders.
for(let i=0;i<280;i++){const x=(rnd()-.5)*54,z=(rnd()-.5)*48;if(Math.abs(x)<7&&z>-9&&z<10)continue;const g=new THREE.Group();g.position.set(x,.02,z);scene.add(g);const m=treeMats[Math.floor(rnd()*5)];for(let j=0;j<3;j++){const leaf=mesh(new THREE.ConeGeometry(.12,.5+rnd()*.45,3),m,(rnd()-.5)*.4,.3,(rnd()-.5)*.4,g);leaf.rotation.z=(rnd()-.5)*.8}if(i%8===0){const s=sphere(.3+rnd()*.4,materials.rock,x,.15,z);s.scale.y=.6}if(i%5===0){cylinder(.04,.05,.25,mat('#d6cca5'),x,.15,z);const cap=sphere(.17,mat(i%10===0?'#c8a576':'#d8cf9b'),x,.3,z);cap.scale.y=.45}}
function bird(){const g=new THREE.Group();const body=sphere(.4,mat('#233a40'),0,.65,0,g);body.scale.set(.8,1.15,.85);sphere(.3,materials.dark,0,1.13,-.09,g);const beak=mesh(new THREE.ConeGeometry(.11,.4,4),mat('#cca76b'),0,1.1,-.48,g);beak.rotation.x=-Math.PI/2;for(const x of [-.22,.22])sphere(.044,mat('#f0d996',{emissive:'#ccbb77',emissiveIntensity:.35}),x,1.19,-.3,g);const wings=[];for(const x of [-.35,.35]){const w=sphere(.29,mat('#293f43'),x,.7,.04,g);w.scale.set(.4,1.5,.9);wings.push(w)}cylinder(.38,.4,.08,mat('#827652'),0,1.4,0,g);cylinder(.23,.25,.3,mat('#8c8059'),0,1.57,0,g);cylinder(.247,.255,.065,mat('#3b4940'),0,1.46,0,g);const scarf=cylinder(.31,.29,.12,mat('#bdaa6b'),0,.96,0,g);box(.12,.4,.08,mat('#bdaa6b'),.18,.73,-.29,g);for(const x of [-.14,.14]){box(.065,.28,.065,mat('#a39970'),x,.18,0,g);box(.09,.045,.22,mat('#a39970'),x,.05,-.05,g)}const tail=mesh(new THREE.ConeGeometry(.25,.55,3),materials.dark,0,.5,.43,g);tail.rotation.x=.7;g.userData.wings=wings;return g}const crow=bird();crow.position.set(-1,0,6);scene.add(crow);let destination=null,flight=false,paused=false,scanning=false;
function animal(x,z,type){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const m=mat(type==='fox'?'#b98350':'#a49b76');sphere(.55,m,0,.55,0,g);sphere(.4,m,0,1.15,0,g);for(const a of [-.25,.25]){mesh(new THREE.ConeGeometry(.18,.45,3),m,a,1.53,0,g);sphere(.045,materials.dark,a*.8,1.2,.35,g)}sphere(.12,materials.dark,0,1.03,.4,g);if(type==='fox'){const tail=sphere(.4,m,.6,.4,-.4,g);tail.scale.set(1.7,.6,.7)}return g}animal(8,-10,'fox');animal(21,2,'owl');const deer=animal(-11,-9,'deer');deer.visible=false;for(const side of [-1,1]){const antler=box(.08,.7,.08,materials.wood,side*.25,1.85,0,deer);antler.rotation.z=side*.3;const branch=box(.3,.07,.07,materials.wood,side*.38,1.95,0,deer);branch.rotation.z=side*.35;}
const clues=[{id:'letter',name:'未寄出的信',type:'书面物证',x:-3,z:-3.8,icon:'✉',text:'“今晚七点，去旧矿井寻找失踪的萤火虫。别惊动森林里的孩子们。”落款是守林人鹿先生。信纸背面画着三颗星星。',note:'守林人主动前往旧矿井；密码第一位：3。'},{id:'scarf',name:'挂住的红围巾',type:'现场物证',x:5,z:1.5,icon:'◇',text:'围巾被箱子的木刺挂破了，周围没有打斗痕迹。上面沾着仅在矿井深处生长的银色苔藓。',note:'并非绑架现场；守林人曾接近矿井。'},{id:'tracks',name:'泥地里的脚印',type:'痕迹证据',x:10,z:2.8,icon:'⋰',text:'鹿蹄印和细小的萤火虫荧粉交织在一起。所有足迹都朝向西北，只有去程，没有返回。',note:'他跟随着萤火虫，向旧矿井走去。'},{id:'fox',name:'狐狸的证词',type:'居民证词',x:8,z:-10,icon:'♧',text:'“我看见鹿先生拿着灯往矿井去了！后来山里轰的一声……我太害怕，就跑回来了。矿门标牌上有一弯月亮。”',note:'坍塌发生在进入矿井之后；密码第二位：1。'},{id:'owl',name:'猫头鹰的目击',type:'居民证词',x:21,z:2,icon:'◉',text:'“我从上空看见，矿井里仍有灯光闪烁。那不是求救之外的任何东西。老矿工总说：先数星星，再看月亮，最后数树。”',note:'守林人可能还活着；密码按星、月、树排列。'},{id:'sign',name:'旧矿工的标记',type:'环境线索',x:-10,z:-11,icon:'⌁',text:'一块倒下的木牌刻着：星 → 月 → 树。底部整齐地雕着四棵松树。锁孔旁传来微弱的敲击声。',note:'密码第三位：4。矿井里有幸存者。'}];
let state={found:[],solved:false,rescued:false};try{const s=JSON.parse(localStorage.getItem('ravenwood-v1'));if(s&&Array.isArray(s.found))state={...state,...s,found:s.found.filter(id=>clues.some(c=>c.id===id))}}catch{}
const markers=[];const glowMat=mat('#d2e68c',{emissive:'#d0e98b',emissiveIntensity:.7});for(const c of clues){if(c.id==='letter'){const paper=box(.65,.03,.45,mat('#eee0b0'),c.x,.22,c.z);paper.rotation.y=.3}if(c.id==='scarf'){box(.6,.06,.3,mat('#a96d53'),c.x,.06,c.z)}if(c.id==='tracks'){for(let i=0;i<5;i++){const foot=sphere(.13,mat('#596344'),c.x+i*.19,.07,c.z-i*.3);foot.scale.y=.2}}if(c.id==='sign')box(.95,.7,.15,materials.wood,c.x,.4,c.z);const ring=mesh(new THREE.TorusGeometry(.48,.025,5,40),glowMat,c.x,.1,c.z);ring.rotation.x=-Math.PI/2;const dot=sphere(.075,glowMat,c.x,1.9,c.z);const el=document.createElement('button');el.className='world-label';el.innerHTML=`<span class="diamond">◇</span>${c.name}`;el.onclick=()=>approach(c);$('#world-labels').append(el);markers.push({c,ring,dot,el})}
const exitLabel=document.createElement('button');exitLabel.className='world-label';exitLabel.innerHTML='⌂ 旧矿井 · 密码锁';exitLabel.onclick=()=>approach({id:'mine',x:-12,z:-10});$('#world-labels').append(exitLabel);
const fireflies=new THREE.Group();scene.add(fireflies);for(let i=0;i<50;i++){const p=sphere(.025+rnd()*.025,glowMat,(rnd()-.5)*40,.6+rnd()*3,(rnd()-.5)*30);fireflies.add(p);p.userData.origin=p.position.clone()}
function save(){try{localStorage.setItem('ravenwood-v1',JSON.stringify(state))}catch{}updateUI()}function updateUI(){deer.visible=state.rescued;mineBars.forEach(b=>b.visible=!state.rescued);$('#progress').textContent=`${state.found.length} / 6`;$('#progress-bar').style.width=state.found.length/6*100+'%';if(state.rescued){$('#objective').textContent='案件告破 · 森林重逢';$('#objective-detail').textContent='你找到了守林人，也守住了森林的秘密。';$('#mission').textContent='继续探索，聆听森林'}else if(state.solved){$('#objective').textContent='前往旧矿井，救出守林人';$('#mission').textContent='按星、月、树顺序解开密码'}else if(state.found.length>=4){$('#objective').textContent='连接线索，重现真相';$('#mission').textContent='打开推理之线，验证你的推断'}else if(state.found.length>=2){$('#objective').textContent='追踪足迹，询问森林居民';$('#mission').textContent='寻找狐狸与猫头鹰'}markers.forEach(m=>{const found=state.found.includes(m.c.id);m.el.classList.toggle('found',found);m.ring.visible=!found;m.dot.visible=!found})}updateUI();
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}function modal(html){$('#modal-body').innerHTML=html;$('#modal').classList.remove('hidden');destination=null}function closeModal(){$('#modal').classList.add('hidden')}$('#close-modal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
function inspect(c){if(c.id==='mine')return mineModal();const already=state.found.includes(c.id);modal(`<div class="eyebrow">${c.type} <span>FOREST EVIDENCE</span></div><h2>${c.icon} ${c.name}</h2><p>${c.text}</p><div class="hint">阿墨的观察：${c.note}</div><button class="primary" id="collect">${already?'已收录 · 继续调查':'记录线索 →'}</button>`);$('#collect').onclick=()=>{if(!already){state.found.push(c.id);save();chime();toast(`线索已收录：${c.name} (${state.found.length}/6)`)}closeModal()}}
let pending=null;function approach(c){if(paused)return toast('请先继续游戏');if(Math.hypot(c.x-crow.position.x,c.z-crow.position.z)<2.6){inspect(c);return}pending=c;destination=new THREE.Vector3(c.x,0,c.z);toast('阿墨正前往调查地点…')}
function journal(){modal(`<div class="eyebrow">DETECTIVE'S JOURNAL <span>CASE 001</span></div><h2>每一条线索，都有回声。</h2><p>鹿先生在昨夜失踪。串联物证与证词，找出他去了哪里。</p><div class="clue-grid">${clues.map((c,i)=>`<article class="clue-card ${state.found.includes(c.id)?'':'locked'}"><div class="number">EVIDENCE 0${i+1} · ${c.type}</div><h3>${state.found.includes(c.id)?c.icon+' '+c.name:'◇ 未发现的线索'}</h3><p>${state.found.includes(c.id)?c.note:'探索森林，与发光的物件或居民互动。'}</p></article>`).join('')}</div><button class="primary" id="journal-deduce">连接线索 →</button>`);$('#journal-deduce').onclick=deduce}
function deduce(){modal(`<div class="eyebrow">THE DEDUCTION BOARD <span>${state.found.length}/6 EVIDENCE</span></div><h2>拼出森林的真相</h2><p>物证告诉你发生了什么，证词帮你理解为什么。至少需要四条线索才能验证推理。</p><div class="question">01 / 鹿先生去了哪里？<select id="where"><option value="">选择地点</option><option value="lake">河对岸的湖泊</option><option value="mine">西北方向的旧矿井</option><option value="cabin">守林人小屋</option></select></div><div class="question">02 / 他为什么离开营地？<select id="why"><option value="">选择动机</option><option value="kidnap">被狐狸绑架</option><option value="bugs">寻找失踪的萤火虫</option><option value="run">躲避森林居民</option></select></div><div class="question">03 / 是什么阻止了他回来？<select id="what"><option value="">选择原因</option><option value="lost">在森林迷路</option><option value="collapse">矿井坍塌，困在里面</option><option value="sleep">在小屋睡着了</option></select></div><div id="deduction-result" class="hint">${state.solved?'✓ 推理已验证。找到矿井密码，就能完成救援。':'选择三个推断，再用线索验证。'}</div><button id="verify" class="primary">验证推理 →</button>`);$('#verify').onclick=()=>{let msg;if(state.found.length<4)msg='证据还不够。再找到 '+(4-state.found.length)+' 条线索，才能形成可靠的推断。';else if(!$('#where').value||!$('#why').value||!$('#what').value)msg='请完成三个推断。';else if($('#where').value==='mine'&&$('#why').value==='bugs'&&$('#what').value==='collapse'){state.solved=true;save();chime();msg='✓ 推理成立！鹿先生为了寻找萤火虫进入旧矿井，随后被坍塌困住。立刻前往西北的旧矿井！'}else msg='有些推断和证据矛盾。再看看未寄出的信、脚印和狐狸的证词。';$('#deduction-result').textContent=msg}}
function mineModal(){if(state.rescued)return ending();if(!state.solved){modal('<div class="eyebrow">THE OLD MINE</div><h2>矿门之后，是谁？</h2><p>石壁后传来敲击声。你需要先弄清发生了什么，才能决定如何安全救援。</p><button class="primary" id="mine-deduce">打开推理之线</button>');$('#mine-deduce').onclick=deduce;return}modal('<div class="eyebrow">FINAL CHAPTER · THE RESCUE</div><h2>星星、月亮与松树</h2><p>矿井侧门的三位密码锁依然完好。旧矿工留下的提示是：<b>先数星星，再看月亮，最后数树。</b></p><div class="question">输入三位密码<input id="code" inputmode="numeric" maxlength="3" aria-label="矿井三位密码" placeholder="• • •" style="display:block;width:100%;padding:18px;font-size:24px;letter-spacing:20px;margin-top:12px;border:1px solid #aab494;background:#f4f1de;border-radius:5px;color:#354a31"/></div><div id="lock-result" class="hint">回顾信纸、狐狸的证词与旧矿工的标记。</div><button class="primary" id="unlock">打开侧门 →</button>');$('#unlock').onclick=()=>{if($('#code').value==='314'){state.rescued=true;save();chime();ending()}else{$('#lock-result').textContent='锁没有打开。星星的数量在信纸背面，月亮藏在狐狸的回忆里，树木刻在旧木牌上。'}}}
function ending(){modal(`<div class="ending"><div class="eyebrow">CASE CLOSED · NO. 001</div><div class="ending-icon">✧</div><h2>微光，终于回到了森林。</h2><p>侧门缓缓打开。鹿先生抱着一盏装满萤火虫的灯，从碎石后走出来。<br>“我就知道，会有人听见。”</p><p>有时候，最勇敢的事不是独自走进黑暗，<br>而是相信，总有朋友会循着微光而来。</p><div class="hint">案件已侦破 · ${state.found.length}/6 条线索 · ${state.found.length===6?'无遗漏的森林名侦探':'敏锐的森林调查员'}</div><button class="primary" id="continue">继续漫游森林</button><button class="text-button" id="restart">重新调查本案 ↻</button></div>`);$('#continue').onclick=closeModal;$('#restart').onclick=()=>{state={found:[],solved:false,rescued:false};save();crow.position.set(-1,0,6);$('#objective').textContent='调查守林人的营地';$('#objective-detail').textContent='靠近发光的物件，寻找失踪的线索。';$('#mission').textContent='检查营地里遗留的物品';closeModal();toast('新的一页，新的调查。')}}
function help(){modal('<div class="eyebrow">A SMALL GUIDE TO THE FOREST</div><h2>欢迎来到鸦林，侦探。</h2><p>扮演乌鸦侦探阿墨，寻找失踪的守林人。点击任意线索标签，阿墨会自动走过去调查。</p><div class="controls-table"><b>W A S D / 方向键</b><span>在森林中移动</span><b>点击 / 拖动 / 滚轮</b><span>移动 / 旋转视角 / 缩放</span><b>E</b><span>调查附近物品或询问居民</span><b>Q · 鸦之视野</b><span>揭示尚未发现的线索，指引最近目标</span><b>F · 低空飞行</b><span>展开翅膀，更快地越过河流和树林</span><b>J / R / M</b><span>线索手册 / 案件推理 / 森林地图</span><b>Esc</b><span>关闭面板 / 暂停游戏</span></div><div class="hint">调查 → 收集至少 4 条线索 → 验证推理 → 解开矿井密码 → 救出守林人。进度保存在当前浏览器。</div><button class="primary" id="help-go">开始探索 →</button>');$('#help-go').onclick=closeModal}
function toggleFly(){flight=!flight;$('#fly').classList.toggle('active',flight);$('#explore').classList.toggle('active',!flight);$('#mode').textContent=flight?'低空飞行中':'步行探索中';toast(flight?'展开翅膀 · 可以飞越河流，移动速度提升':'轻轻落地 · 继续寻找线索')}
let scanTimer;function scan(){scanning=true;$('#scan').classList.add('active');$('.vignette').classList.remove('scan-wash');void $('.vignette').offsetWidth;$('.vignette').classList.add('scan-wash');const remaining=clues.filter(c=>!state.found.includes(c.id)).sort((a,b)=>Math.hypot(a.x-crow.position.x,a.z-crow.position.z)-Math.hypot(b.x-crow.position.x,b.z-crow.position.z));toast(remaining.length?`鸦之视野：最近的线索是「${remaining[0].name}」，距你 ${Math.round(Math.hypot(remaining[0].x-crow.position.x,remaining[0].z-crow.position.z))} 米`:'所有线索已发现。前往推理之线，连接真相。');clearTimeout(scanTimer);scanTimer=setTimeout(()=>{scanning=false;$('#scan').classList.remove('active')},8000)}
$('#help').onclick=help;$('#journal-open').onclick=journal;$('#clues-open').onclick=journal;$('#deduce-open').onclick=deduce;$('#scan').onclick=scan;$('#fly').onclick=toggleFly;$('#explore').onclick=()=>{if(flight)toggleFly();closeModal()};function pause(){paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';toast(paused?'调查暂停 · 点击右上角继续':'调查继续')}$('#pause').onclick=pause;
const keys={};window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.repeat)return;if(e.key==='Escape'){if(!$('#modal').classList.contains('hidden'))closeModal();else pause();return}if(!$('#modal').classList.contains('hidden'))return;const k=e.key.toLowerCase();if(k==='j')journal();if(k==='r')deduce();if(k==='m')mapModal();if(k==='q')scan();if(k==='f')toggleFly();if(k==='e'&&nearest)inspect(nearest)});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});
const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();let down=null,dragged=false;canvas.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};dragged=false;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!down)return;const dx=e.clientX-down.x;if(Math.abs(dx)>3){dragged=true;angle-=dx*.006;down={x:e.clientX,y:e.clientY}}};canvas.onpointerup=e=>{if(!dragged&&!paused&&$('#modal').classList.contains('hidden')){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObject(ground);if(hits[0]){destination=hits[0].point.clone();destination.x=THREE.MathUtils.clamp(destination.x,-28,28);destination.z=THREE.MathUtils.clamp(destination.z,-27,24);pending=null}}down=null};canvas.onwheel=e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.025,20,65)};
let audioContext=null,soundOn=false,audioGain;$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound span').textContent=soundOn?'环境音开启':'环境音关闭';if(soundOn){audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();if(!audioGain){audioGain=audioContext.createGain();audioGain.gain.value=.025;audioGain.connect(audioContext.destination);[146.83,220,293.66].forEach(f=>{const o=audioContext.createOscillator();o.type='sine';o.frequency.value=f;o.connect(audioGain);o.start()})}audioGain.gain.setTargetAtTime(.025,audioContext.currentTime,.3)}else if(audioGain)audioGain.gain.setTargetAtTime(0,audioContext.currentTime,.3)};function chime(){if(!soundOn||!audioContext)return;[587,740,880].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.1;o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.08,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.5);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.6)})}
const map=$('#minimap'),ctx=map.getContext('2d');function drawMap(c,w,h,big=false){c.clearRect(0,0,w,h);c.fillStyle='#253e30';c.fillRect(0,0,w,h);const px=x=>w/2+x*w/58,pz=z=>h/2+z*h/48;c.strokeStyle='#7f9f8240';c.lineWidth=1;for(let i=0;i<5;i++){c.beginPath();c.ellipse(w*.48,h*.49,w*(.16+i*.09),h*(.14+i*.085),-.3,0,Math.PI*2);c.stroke()}c.strokeStyle='#688f80';c.lineWidth=big?10:4;c.beginPath();for(let z=-24;z<=24;z++)c.lineTo(px(15+Math.sin(z*.13)*3),pz(z));c.stroke();c.strokeStyle='#acae7750';c.lineWidth=big?4:2;c.beginPath();[[-4,18],[0,3],[0,-6],[-12,-13]].forEach(([x,z])=>c.lineTo(px(x),pz(z)));c.stroke();c.fillStyle='#a8af83';c.fillRect(px(-5),pz(-7),big?17:7,big?13:5);for(const cl of clues){c.beginPath();c.arc(px(cl.x),pz(cl.z),big?5:2.2,0,Math.PI*2);c.fillStyle=state.found.includes(cl.id)?'#6f8764':'#d6df9a';c.fill();if(big){c.fillStyle='#d6dfbd';c.font='12px sans-serif';c.fillText(cl.name,px(cl.x)+9,pz(cl.z)+4)}}c.fillStyle='#f3f4c4';c.shadowColor='#e2ee9a';c.shadowBlur=10;c.beginPath();c.arc(px(crow.position.x),pz(crow.position.z),big?6:3,0,Math.PI*2);c.fill();c.shadowBlur=0;if(big){c.fillStyle='#dee5bd';c.font='12px sans-serif';c.fillText('⌂ 旧矿井',px(-16),pz(-17));c.fillText('点击地图标记，前往对应地点',15,h-16)}}function mapModal(){modal('<div class="eyebrow">THE MISTY WOODLAND</div><h2>森林不会让你迷路。</h2><p>亮点是尚待调查的线索。点击地图中的地点，阿墨会前往那里。</p><canvas id="big-map" class="big-map" width="660" height="340"></canvas>');const b=$('#big-map');drawMap(b.getContext('2d'),660,340,true);b.onclick=e=>{const r=b.getBoundingClientRect();const x=((e.clientX-r.left)/r.width-.5)*58,z=((e.clientY-r.top)/r.height-.5)*48;const cl=clues.find(c=>Math.hypot(c.x-x,c.z-z)<3);closeModal();if(cl)approach(cl);else{destination=new THREE.Vector3(x,0,z);pending=null}}}$('#map-open').onclick=mapModal;
let nearest=null,elapsed=0;const clock=new THREE.Clock();const vec=new THREE.Vector3();function projectLabel(el,x,y,z){vec.set(x,y,z).project(camera);const sx=(vec.x*.5+.5)*innerWidth,sy=(-vec.y*.5+.5)*innerHeight;el.style.left=sx+'px';el.style.top=sy+'px';el.style.display=vec.z<1&&sx>10&&sx<innerWidth-10&&sy>95&&sy<innerHeight-145?'block':'none'}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);const open=!$('#modal').classList.contains('hidden');if(!paused&&!open){elapsed+=dt;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let moving=false;if(dx||dz){destination=null;pending=null;const ca=Math.cos(angle),sa=Math.sin(angle);const xx=dx*ca+dz*sa,zz=-dx*sa+dz*ca;dx=xx;dz=zz;moving=true}else if(destination){dx=destination.x-crow.position.x;dz=destination.z-crow.position.z;if(Math.hypot(dx,dz)<(pending?1.75:.2)){destination=null;if(pending){const p=pending;pending=null;inspect(p)}}else moving=true}if(moving){const len=Math.hypot(dx,dz);let nx=crow.position.x+dx/len*dt*(flight?7:3.8),nz=crow.position.z+dz/len*dt*(flight?7:3.8);const rx=15+Math.sin(nz*.13)*3;const inRiver=Math.abs(nx-rx)<1.35&&Math.abs(nz-1)>1.4;if(inRiver&&!flight){if(destination){destination=null;pending=null;toast('河水有些深。按 F 飞过去，或从木桥通过。')}}else{crow.position.x=THREE.MathUtils.clamp(nx,-28,28);crow.position.z=THREE.MathUtils.clamp(nz,-27,24)}crow.rotation.y=Math.atan2(-dx,-dz)}const targetY=flight?2.2+Math.sin(elapsed*3)*.12:moving?Math.abs(Math.sin(elapsed*13))*.12:0;crow.position.y=THREE.MathUtils.lerp(crow.position.y,targetY,dt*9);crow.userData.wings.forEach((w,i)=>w.rotation.z=flight?(i?1:-1)*(1+Math.sin(elapsed*13)*.65):0);flame.scale.setScalar(.9+Math.sin(elapsed*11)*.13);light.intensity=4+Math.sin(elapsed*11);fireflies.children.forEach((p,i)=>{const o=p.userData.origin;p.position.set(o.x+Math.sin(elapsed*.5+i)*.3,o.y+Math.sin(elapsed+i)*.2,o.z+Math.cos(elapsed*.4+i)*.3)});markers.forEach((m,i)=>{m.dot.position.y=1.9+Math.sin(elapsed*2+i)*.17;m.ring.scale.setScalar(scanning?1.35+Math.sin(elapsed*4)*.2:1)})}
focus.lerp(new THREE.Vector3(crow.position.x*.68,0,crow.position.z*.65-1),.035);camera.position.set(focus.x+Math.sin(angle)*zoom,zoom*.78,focus.z+Math.cos(angle)*zoom);camera.lookAt(focus.x,0,focus.z);markers.forEach(m=>projectLabel(m.el,m.c.x,2.5,m.c.z));projectLabel(exitLabel,-12,3.6,-13);nearest=[...clues,{id:'mine',name:'旧矿井密码锁',x:-12,z:-10}].filter(c=>Math.hypot(c.x-crow.position.x,c.z-crow.position.z)<2.6).sort((a,b)=>Math.hypot(a.x-crow.position.x,a.z-crow.position.z)-Math.hypot(b.x-crow.position.x,b.z-crow.position.z))[0];const interaction=$('#interaction');interaction.style.display=nearest&&!open?'block':'none';if(nearest)interaction.innerHTML=`<kbd>E</kbd>调查 · ${nearest.name}`;interaction.onclick=()=>{if(nearest)inspect(nearest)};$('#location-name').textContent=crow.position.x>14?'萤光河畔':crow.position.z<-9&&crow.position.x<-5?'废弃的旧矿井':crow.position.z<-7?'低语松林':'守林人营地';drawMap(ctx,190,150);renderer.render(scene,camera)}animate();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});setTimeout(()=>toast(state.found.length?'欢迎回来，侦探。你的调查进度已恢复。':'欢迎来到鸦林。点击发光标签开始调查，按 ? 查看指引。'),1800);
