import { icon, hydrateIcons } from './icons.js';
import { createArena } from './scene.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const people=[
 {id:'fox',name:'阿栗',animal:'🦊',title:'森林小智者',skill:'自然亲和',detail:'自然秘境题答对额外获得 15 分。'},
 {id:'rabbit',name:'绵绵',animal:'🐰',title:'月光旅行家',skill:'从容思考',detail:'每道限时题额外获得 3 秒思考时间。'},
 {id:'panda',name:'竹竹',animal:'🐼',title:'竹林守护者',skill:'不屈之心',detail:'每局第一次答错时，保留当前连击。'},
 {id:'owl',name:'星咕',animal:'🦉',title:'星空观测员',skill:'博学洞察',detail:'灵光一闪每局可使用 2 次。'}
];
const modes={classic:{name:'经典赛',count:8,time:20,description:'8 道题 · 每题 20 秒 · 与 3 位 AI 选手争夺冠军'},blitz:{name:'疾速赛',count:12,time:12,description:'12 道题 · 每题 12 秒 · 更快思考，更高奖励'},practice:{name:'自由练习',count:10,time:0,description:'10 道题 · 不限时间 · 轻松积累知识，也有答题奖励'}};
const defaults={coins:120,gems:5,xp:0,matches:0,wins:0,totalCorrect:0,bestCombo:0,perfect:0,owned:[],equipped:'',sound:false,selected:0};
let profile={...defaults},saveAvailable=true;
try{const p=JSON.parse(localStorage.getItem('wild-wisdom-v1')||'{}');for(const key of ['coins','gems','xp','matches','wins','totalCorrect','bestCombo','perfect'])if(Number.isFinite(p?.[key])&&p[key]>=0)profile[key]=p[key];profile.owned=Array.isArray(p?.owned)?p.owned.filter(x=>['crown','moon','gold'].includes(x)):[];profile.equipped=profile.owned.includes(p?.equipped)?p.equipped:'';profile.sound=p?.sound===true;profile.selected=Number.isInteger(p?.selected)&&p.selected>=0&&p.selected<4?p.selected:0;}catch{saveAvailable=false;}
function save(){try{localStorage.setItem('wild-wisdom-v1',JSON.stringify(profile));}catch{saveAvailable=false;}}
let state={phase:'lobby',selected:profile.selected,mode:'classic',round:0,scores:[0,0,0,0],combo:0,correct:0,maxCombo:0,paused:false,skills:{hint:1,freeze:1,double:1},queue:[],remaining:0,totalTime:20,double:false,answers:[],ai:[],logs:[],pandaUsed:false};
let questions=[],arena=null,timer=null,lastTick=0,toastTimer,sceneToastTimer,audioContext;
hydrateIcons();
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2900);}
function sceneToast(message){clearTimeout(sceneToastTimer);$('#scene-toast').textContent=message;$('#scene-toast').classList.add('show');sceneToastTimer=setTimeout(()=>$('#scene-toast').classList.remove('show'),2600);}
function sound(kind){if(!profile.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const notes=kind==='correct'?[523,659,784]:kind==='wrong'?[233,196]:kind==='win'?[523,659,784,1047]:[660];notes.forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+i*.09;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.08,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+.24);o.connect(g);g.connect(audioContext.destination);o.start(at);o.stop(at+.25);});}catch{}}
function updateWallet(){$('#coins').textContent=profile.coins.toLocaleString();$('#gems').textContent=profile.gems;$('#level').textContent=1+Math.floor(profile.xp/250);$('.profile>span').textContent=people[state.selected].animal;$('#sound').innerHTML=icon(profile.sound?'volume':'volume-off');$('#sound').setAttribute('aria-label',profile.sound?'关闭音效':'开启音效');$('#daily-progress').textContent=profile.matches?`已完成 ${profile.matches} 局 · 累计答对 ${profile.totalCorrect} 题`:'完成一局，开启你的森林冒险。';}
function ranking(){return people.map((p,i)=>({...p,index:i,score:state.scores[i]})).sort((a,b)=>b.score-a.score||a.index-b.index);}
function renderStandings(){const active=state.phase!=='lobby',practice=state.mode==='practice'&&active,rows=ranking();
 $('#contestants').innerHTML=rows.map((p,i)=>{let subtitle=!active||state.phase==='finished'?p.title:state.answers[p.index]===undefined?'思考中…':state.answers[p.index]?'回答正确':'继续加油';if(practice&&p.index!==state.selected)subtitle='陪练观赛中';const place=1+rows.filter(x=>x.score>p.score).length;return `<div class="contestant ${p.index===state.selected?'mine':''}"><span class="rank">${active?place:i+1}</span><span class="animal-avatar ${p.id}">${p.animal}</span><div class="contestant-name"><b>${p.name}${p.index===state.selected?'<span class="you-tag">你</span>':''}</b><small>${subtitle}</small></div><div class="contestant-score">${p.score}<small>积分</small></div></div>`;}).join('');
 $('#round-track').innerHTML=Array.from({length:modes[state.mode].count},(_,i)=>`<span class="round-dot ${active&&i<state.round?'done':active&&i===state.round?'current':''}"></span>`).join('');
 $('#match-status').textContent=state.phase==='lobby'?'等待开赛':state.phase==='finished'?'比赛结束':`第 ${state.round+1} / ${modes[state.mode].count} 题`;$('#match-status').classList.toggle('live',state.phase==='question');
 $('#arena-state').textContent=state.phase==='lobby'?'4 位选手 · 即将开赛':practice?'自由练习 · 享受思考':state.phase==='finished'?'赛事已结束 · 下一场见':`4 位选手 · 第 ${state.round+1} 回合`;
 $('#leader-note').innerHTML=icon('sparkles')+(state.phase==='lobby'?'每个人都有成为冠军的可能':practice?'按照自己的节奏，慢慢积累知识':state.phase==='finished'?`本场最高积分：${rows[0].score}`:`${rows[0].name} 暂时领先 · 还有机会反超`);
 $('.skills .muted').textContent=state.selected===3?'灵光 2 次 · 其余 1 次':'每局各 1 次';
 const effects={hint:'排除两个错误答案',freeze:'增加 10 秒',double:'本题答对双倍积分'};
 $$('[data-skill]').forEach(b=>{const id=b.dataset.skill;b.classList.toggle('used',active&&state.skills[id]<=0);b.setAttribute('aria-label',`${b.querySelector('b').textContent}，${effects[id]}，剩余 ${state.skills[id]} 次`);b.disabled=state.phase==='question'&&(state.skills[id]<=0||(id==='freeze'&&state.mode==='practice'));});
}
function renderLobby(){state.phase='lobby';state.scores=[0,0,0,0];state.answers=[];state.skills={hint:state.selected===3?2:1,freeze:1,double:1};$('#arena-banner').innerHTML='<span class="tiny-star">✦</span> 森林知识杯 <span class="tiny-star">✦</span><small>智慧汇聚的地方</small>';
 $('#interaction-panel').innerHTML=`<div class="lobby-title"><div><h2>准备好，让智慧闪闪发光？</h2><p>选择你的森林伙伴，开启一场奇妙的知识冒险。</p></div><div class="mode-tabs" role="group" aria-label="比赛模式">${Object.entries(modes).map(([id,m])=>`<button data-mode="${id}" class="${state.mode===id?'selected':''}" aria-pressed="${state.mode===id}">${m.name}</button>`).join('')}</div></div><div class="lobby-controls"><div class="character-picks" role="group" aria-label="选择选手">${people.map((p,i)=>`<button class="char-pick ${state.selected===i?'selected':''}" data-character="${i}" aria-label="选择${p.name}，${p.skill}" aria-pressed="${state.selected===i}"><span class="animal">${p.animal}</span><span class="char-info"><b>${p.name}</b><small>${p.skill}</small></span></button>`).join('')}</div><button class="start-btn" id="start-game">${icon('play')} 开始比赛</button></div><div class="mode-description">${icon('clock')} ${modes[state.mode].description}</div>`;
 renderStandings();applyCosmetic();
}
function chooseCharacter(i){if(!Number.isInteger(i)||i<0||i>3)throw new Error('请选择有效选手。');if(state.phase!=='lobby'){toast('比赛开始后无法更换选手，下局再试试其他伙伴吧。');return false;}state.selected=i;profile.selected=i;save();arena?.select(i);updateWallet();renderLobby();sound('tap');return true;}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function startGame(){if(!questions.length){toast('题库还在准备，请稍后再试。');return false;}clearInterval(timer);const keep={mode:state.mode,selected:state.selected};state={...keep,phase:'question',round:0,scores:[0,0,0,0],combo:0,correct:0,maxCombo:0,paused:false,skills:{hint:keep.selected===3?2:1,freeze:1,double:1},queue:shuffle(questions).slice(0,modes[keep.mode].count),remaining:0,totalTime:20,double:false,answers:[],ai:[],logs:[],pandaUsed:false};sound('tap');nextQuestion();if(innerWidth<=780)$('#interaction-panel').scrollIntoView({behavior:'smooth',block:'start'});return true;}
function nextQuestion(){if(state.round>=state.queue.length){finishGame();return;}state.phase='question';state.answers=[];state.double=false;state.eliminated=[];state.questionElapsed=0;state.event=state.mode==='practice'?null:state.round===2?'blessing':state.round===5?'meteor':null;
 state.aiTime=state.event==='meteor'?Math.max(10,modes[state.mode].time-5):modes[state.mode].time;
 state.totalTime=state.aiTime+(state.selected===1&&state.mode!=='practice'?3:0);state.remaining=state.totalTime;state.ai=people.map((p,i)=>({index:i,answered:false,time:2+Math.random()*Math.max(3,state.aiTime-4),correct:Math.random()<(.87-state.queue[state.round].difficulty*.09),combo:state.ai?.[i]?.combo||0}));
 $('#arena-banner').innerHTML=`${state.event==='blessing'?'星辉赐福':state.event==='meteor'?'流星竞速':'森林知识杯'}<small>${state.event==='blessing'?'本回合全员基础积分 × 1.5':state.event==='meteor'?'时间缩短 · 全员基础积分 × 1.25':`第 ${state.round+1} 回合 · ${modes[state.mode].name}`}</small>`;
 if(state.event)sceneToast(state.event==='blessing'?'✦ 星辉降临！本题全员基础积分 × 1.5':'✦ 流星竞速！本题时间缩短，基础积分 × 1.25');
 renderQuestion();renderStandings();lastTick=performance.now();clearInterval(timer);timer=setInterval(tick,100);
}
function tick(){const now=performance.now(),dt=Math.min((now-lastTick)/1000,1);lastTick=now;if(state.phase!=='question'||state.paused)return;state.questionElapsed+=dt;if(state.mode!=='practice'){state.remaining=Math.max(0,state.remaining-dt);updateTimer();state.ai.forEach(ai=>{if(ai.index!==state.selected&&!ai.answered&&state.questionElapsed>=ai.time)commitAI(ai);});if(state.remaining<=0)submitAnswer(-1);}}
function updateTimer(){const t=$('#timer-value'),bar=$('#timer-fill');if(t)t.textContent=state.mode==='practice'?'∞':Math.ceil(state.remaining);if(bar)bar.style.width=state.mode==='practice'?'100%':(state.remaining/state.totalTime*100)+'%';$('.question-timer')?.classList.toggle('urgent',state.remaining<=5&&state.mode!=='practice');}
function renderQuestion(){const q=state.queue[state.round],solved=state.phase==='revealed',last=state.logs.at(-1);
 $('#interaction-panel').innerHTML=`<div class="question-top"><div class="question-meta"><span class="category-tag">${icon(q.category==='自然秘境'?'leaf':q.category==='星空奥秘'?'star':q.category==='奇妙科学'?'bulb':'book')}${q.category}</span><span>${['','初阶','进阶','高阶'][q.difficulty]}</span>${state.combo>=2?`<span class="combo-badge">${state.combo} 连击</span>`:''}</div><div class="question-top-right"><span class="question-timer">${icon('clock')}<span id="timer-value">${state.mode==='practice'?'∞':Math.ceil(state.remaining)}</span><small>${state.mode==='practice'?'':'秒'}</small></span><button class="pause-btn" id="pause-game" aria-label="暂停比赛">${icon('pause')}</button></div></div><h2 class="question-title">${q.question}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer ${solved&&i===q.correct?'correct':''} ${solved&&i===last?.chosen&&i!==q.correct?'wrong':''} ${state.eliminated.includes(i)?'eliminated':''}" data-answer="${i}" ${solved||state.eliminated.includes(i)?'disabled':''}><span class="letter">${'ABCD'[i]}</span><span>${o}</span>${solved&&i===q.correct?`<span class="answer-end">${icon('check')}</span>`:''}${solved&&i===last?.chosen&&i!==q.correct?`<span class="answer-end">${icon('close')}</span>`:''}</button>`).join('')}</div>${solved?`<div class="answer-feedback"><div class="feedback-copy"><b>${last.correct?`回答正确！+${last.points} 积分`:last.chosen===-1?'时间到了，下题再接再厉！':'差一点点，收获一个新知识。'}</b>${q.explanation}</div><button class="next-btn" id="next-question">${state.round===state.queue.length-1?'查看赛果':'下一道题'} ${icon(state.round===state.queue.length-1?'trophy':'play')}</button></div>`:`<div class="timer-line"><div class="timer-fill" id="timer-fill"></div></div>${state.double?'<div class="event-line">✦ 幸运加倍已激活，本题答对积分 × 2</div>':''}`}`;
 if(!solved)$('#interaction-panel').insertAdjacentHTML('beforeend',`<div class="mobile-skills">${[['hint','bulb','灵光一闪','排除错项'],['freeze','snow','时光慢行','增加10秒'],['double','zap','幸运加倍','积分翻倍']].map(([id,i,n,d])=>`<button data-skill="${id}">${icon(i)}<b>${n}</b><small>${d} · ${state.skills[id]}次</small></button>`).join('')}</div>`);
 updateTimer();
}
function pointsFor(remaining,combo,index,totalTime=state.totalTime){const multiplier=state.event==='blessing'?1.5:state.event==='meteor'?1.25:1,speed=state.mode==='practice'?0:Math.round(Math.min(1,Math.max(0,remaining/totalTime))*50);let value=Math.round(100*multiplier)+speed+Math.min(combo-1,5)*15;if(index===0&&state.queue[state.round].category==='自然秘境')value+=15;return value;}
function commitAI(ai){if(ai.answered||state.mode==='practice')return;ai.answered=true;state.answers[ai.index]=ai.correct;if(ai.correct){ai.combo++;const points=pointsFor(state.aiTime-ai.time,ai.combo,ai.index,state.aiTime);state.scores[ai.index]+=points;arena?.celebrate(ai.index,points);}else ai.combo=0;renderStandings();}
function submitAnswer(index){if(state.phase!=='question'||state.paused)return false;if(!Number.isInteger(index)||index< -1||index>3||state.eliminated.includes(index))return false;const q=state.queue[state.round],correct=index===q.correct;clearInterval(timer);state.phase='revealed';state.answers[state.selected]=correct;let points=0;
 if(correct){state.combo++;state.correct++;state.maxCombo=Math.max(state.maxCombo,state.combo);points=pointsFor(state.remaining,state.combo,state.selected)*(state.double?2:1);state.scores[state.selected]+=points;arena?.celebrate(state.selected,points);sound('correct');if(state.combo>=3)sceneToast(`🔥 ${state.combo} 连击！智慧之火正在燃烧`);}else{if(state.selected===2&&!state.pandaUsed){state.pandaUsed=true;sceneToast('不屈之心触发：本次失误保留连击！');}else state.combo=0;sound('wrong');}
 state.ai.forEach(ai=>{if(ai.index!==state.selected)commitAI(ai);});state.logs.push({question:q.question,chosen:index,correct,answer:q.options[q.correct],explanation:q.explanation,points});renderQuestion();renderStandings();return true;
}
function useSkill(skill){if(!['hint','freeze','double'].includes(skill))throw new Error('未知技能。');if(state.phase!=='question'||state.paused){toast(state.phase==='lobby'?'开始比赛后，就可以使用魔法锦囊。':'请在答题时使用锦囊。');return false;}if(state.skills[skill]<=0){toast('这份锦囊本局已经用完。');return false;}if(skill==='freeze'&&state.mode==='practice'){toast('自由练习不限时，无需时光魔法。');return false;}if(skill==='hint'&&state.eliminated.length){toast('本题已经排除两个错项。');return false;}if(skill==='double'&&state.double)return false;
 state.skills[skill]--;if(skill==='hint'){state.eliminated=shuffle([0,1,2,3].filter(x=>x!==state.queue[state.round].correct)).slice(0,2);sceneToast('灵光一闪！已排除两个错误答案。');}else if(skill==='freeze'){state.remaining+=10;state.totalTime+=10;sceneToast('时光慢行！额外获得 10 秒思考时间。');}else{state.double=true;sceneToast('幸运加倍！本题答对积分 × 2。');}sound('tap');renderQuestion();renderStandings();return true;
}
function next(){if(state.phase!=='revealed')return false;state.round++;nextQuestion();return true;}
function finishGame(){clearInterval(timer);state.phase='finished';const me=state.scores[state.selected],place=1+state.scores.filter(s=>s>me).length,practice=state.mode==='practice',winner=!practice&&place===1,multiplier=state.mode==='blitz'?1.25:1,coins=practice?state.correct*6:Math.round([120,70,45,25][place-1]*multiplier),gems=practice?1:[8,4,2,1][place-1];
 profile.coins+=coins;profile.gems+=gems;profile.xp+=state.correct*25+40;profile.matches++;profile.totalCorrect+=state.correct;profile.bestCombo=Math.max(profile.bestCombo,state.maxCombo);if(winner)profile.wins++;if(state.correct===state.queue.length)profile.perfect++;save();updateWallet();
 $('#arena-banner').innerHTML=winner?'森林冠军诞生<small>恭喜你，森林的智慧之星</small>':practice?'好奇心又长大了一点<small>每一个答案都是一份收获</small>':'精彩的知识冒险<small>下一场，继续向冠军出发</small>';if(winner){arena?.celebrate(state.selected,coins);sound('win');}
 $('#interaction-panel').innerHTML=`<div class="result-heading"><span class="big-trophy">${winner?'🏆':practice?'🌱':'✨'}</span><h2>${winner?'你是今天的森林智者！':practice?'一场美好的知识旅行':`第 ${place} 名，也有闪光时刻`}</h2><p>${winner?'好奇心与勇气，为你赢得了这座奖杯。':'带着新收获，再开启下一场冒险吧。'}</p></div><div class="result-stats"><div><strong>${me}</strong><small>最终积分</small></div><div><strong>${state.correct}/${state.queue.length}</strong><small>答对题数</small></div><div><strong>${state.maxCombo}</strong><small>最高连击</small></div></div><div class="earned-note">${icon('coin')} +${coins} 金币　 ${icon('gem')} +${gems} 水晶　 +${state.correct*25+40} 经验</div><div class="result-actions"><button class="secondary-btn" id="review-game">回顾本局</button><button class="start-btn" id="return-lobby">${icon('refresh')} 再来一场</button></div>`;
 renderStandings();if(!saveAvailable)toast('本次浏览器无法保存进度；当前页面仍可继续游玩。');
}
const modal=$('#modal');
function openModal(title,body){if(state.phase==='question')state.paused=true;$('#modal-title').textContent=title;$('#modal-content').innerHTML=body;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();state.paused=false;lastTick=performance.now();}
function pauseGame(){if(state.phase!=='question'&&state.phase!=='revealed')return;openModal('让思绪休息一下','<p class="modal-intro">比赛已暂停。倒计时和对手都在等你回来。</p><div class="pause-actions"><button class="secondary-btn" id="quit-game">结束本局</button><button class="next-btn" id="resume-game">继续比赛</button></div>');}
function showCharacters(){openModal('认识你的森林伙伴',`<p class="modal-intro">每位选手都有自己的小魔法。${state.phase==='lobby'?'选择最喜欢的一位，带上好奇心出发吧。':'本局已锁定选手，可在下一局更换。'}</p><div class="collection-grid">${people.map((p,i)=>`<div class="character-card ${i===state.selected?'selected':''}"><span class="big-animal">${p.animal}</span><h3>${p.name} · ${p.title}</h3><p><b>${p.skill}</b><br>${p.detail}</p><button data-modal-character="${i}" ${state.phase!=='lobby'?'disabled':''}>${i===state.selected?'当前伙伴':'选择伙伴'}</button></div>`).join('')}</div>`);}
function showAchievements(){const badges=[['🌱','初入森林','完成你的第一场比赛',profile.matches>=1],['🏆','森林智者','在竞技赛中赢得一次冠军',profile.wins>=1],['🔥','灵感不熄','达成 3 次连续答对',profile.bestCombo>=3],['💎','完美解答','一局中答对所有题目',profile.perfect>=1],['🧭','常驻冒险家','累计完成 5 场比赛',profile.matches>=5],['📚','知识收藏家','累计答对 50 道题',profile.totalCorrect>=50]];
 openModal('成就殿堂',`<p class="modal-intro">Lv.${1+Math.floor(profile.xp/250)} 森林学徒 · ${profile.xp%250}/250 经验<br>已完成 ${profile.matches} 场冒险，赢得 ${profile.wins} 次冠军。</p>${badges.map(([emoji,name,desc,unlocked])=>`<div class="badge-card ${unlocked?'':'locked'}"><span>${emoji}</span><div><h3>${name}</h3><p>${desc}</p></div><small>${unlocked?'已点亮':'待解锁'}</small></div>`).join('')}`);
}
const products=[{id:'crown',emoji:'👑',name:'晨曦小王冠',desc:'为你的 3D 选手戴上金色王冠',price:200,currency:'coins'},{id:'moon',emoji:'🌙',name:'月光森林',desc:'将竞技场染上梦幻的月夜色彩',price:18,currency:'gems'},{id:'gold',emoji:'☀️',name:'暖阳森林',desc:'为浮岛洒上温暖的金色阳光',price:150,currency:'coins'}];
function showShop(){openModal('魔法商店',`<p class="modal-intro">用比赛赢得的奖励，装点自己的冒险。<br>你的背包：${profile.coins} 金币 · ${profile.gems} 水晶</p>${products.map(p=>`<div class="shop-card"><span>${p.emoji}</span><div><h3>${p.name}</h3><p>${p.desc}</p></div><button data-buy="${p.id}">${profile.owned.includes(p.id)?profile.equipped===p.id?'取下装扮':'装备':`${p.price} ${p.currency==='coins'?'金币':'水晶'}`}</button></div>`).join('')}<p class="modal-intro shop-note">装扮不影响答题分数。每次可装备一件，进度仅保存在此设备。</p>`);}
function buyProduct(id){const p=products.find(x=>x.id===id);if(!p)return;if(!profile.owned.includes(id)){if(profile[p.currency]<p.price){toast('奖励还不够，再参加几场比赛吧。');return;}profile[p.currency]-=p.price;profile.owned.push(id);}profile.equipped=profile.equipped===id?'':id;save();applyCosmetic();updateWallet();showShop();sound('tap');}
function applyCosmetic(){for(let i=0;i<4;i++)arena?.setCrown(i,profile.equipped==='crown'&&i===state.selected);$('#arena').style.filter=profile.equipped==='moon'?'hue-rotate(31deg) saturate(.83)':profile.equipped==='gold'?'sepia(.17) saturate(1.14)':'';}
function showGuide(){openModal('森林冒险指南',`<div class="guide-step"><span>1</span><div><h3>挑选伙伴与赛事</h3><p>四位动物选手拥有不同被动能力。经典赛 8 题，疾速赛 12 题，自由练习 10 题且不限时。竞技赛中，你将面对 3 位 AI 对手。</p></div></div><div class="guide-step"><span>2</span><div><h3>让知识化为积分</h3><p>答对基础 100 分，越快作答最多额外获得 50 分。每多连对一题再加 15 分，连击加成最多 75 分。答错不扣分，会中断连击。AI 的作答时间与正确率由本局难度随机模拟。</p></div></div><div class="guide-step"><span>3</span><div><h3>善用魔法，把握事件</h3><p>Q 排除两个错项，W 增加 10 秒，E 将本题答对积分翻倍。每局各 1 次，星咕可使用 2 次排除。第 3 题星辉赐福提高全员基础分，第 6 题流星竞速缩短时间、提高全员基础分。</p></div></div><div class="guide-step"><span>4</span><div><h3>收集奖励，记录成长</h3><p>总积分最高的选手夺冠，同分并列。经典赛冠军获得 120 金币和 8 水晶，疾速赛金币提高 25%；每次完成赛事都有奖励，练习每题答对获得 6 金币。所有进度仅保存在此浏览器。</p></div></div><div class="guide-step"><span>⌨</span><div><h3>操作小抄</h3><p>数字 1–4 选择答案，Space 进入下一题，Esc 暂停。拖动场景旋转视角，点击小动物选择伙伴。切换到其他窗口时比赛会暂停。</p></div></div>`);}
function showReview(){openModal('本局知识手记',state.logs.map((q,i)=>`<div class="badge-card"><span class="review-mark">${q.correct?'✅':'🌱'}</span><div><h3>${i+1}. ${q.question}</h3><p>正确答案：${q.answer}<br>${q.explanation}</p></div></div>`).join(''));}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.nav){const nav=b.dataset.nav;if(nav==='arena'){closeModal();window.scrollTo({top:0,behavior:'smooth'});}if(nav==='characters')showCharacters();if(nav==='achievements')showAchievements();if(nav==='shop')showShop();if(nav==='guide')showGuide();return;}
 if(b.dataset.mode&&state.phase==='lobby'){state.mode=b.dataset.mode;renderLobby();}if(b.dataset.character!==undefined)chooseCharacter(Number(b.dataset.character));if(b.dataset.modalCharacter!==undefined&&chooseCharacter(Number(b.dataset.modalCharacter)))showCharacters();if(b.dataset.answer!==undefined)submitAnswer(Number(b.dataset.answer));if(b.dataset.skill)useSkill(b.dataset.skill);if(b.dataset.buy)buyProduct(b.dataset.buy);
 switch(b.id){case 'start-game':startGame();break;case 'next-question':next();break;case 'return-lobby':renderLobby();break;case 'pause-game':pauseGame();break;case 'review-game':showReview();break;case 'close-modal':case 'resume-game':closeModal();break;case 'quit-game':clearInterval(timer);closeModal();renderLobby();toast('本局已结束，未领取比赛奖励。');break;case 'sound':profile.sound=!profile.sound;save();updateWallet();sound('tap');break;case 'rotate':b.classList.toggle('active',arena?.rotate());break;case 'fullscreen':if(document.fullscreenElement)document.exitFullscreen?.();else if($('#arena').requestFullscreen)$('#arena').requestFullscreen().catch(()=>toast('当前浏览器暂不支持全屏。'));else toast('当前浏览器暂不支持全屏。');break;}
});
modal.addEventListener('cancel',e=>{e.preventDefault();closeModal();});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});modal.addEventListener('close',()=>{state.paused=false;lastTick=performance.now();});
document.addEventListener('keydown',e=>{if(modal.open)return;if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();submitAnswer(Number(e.key)-1);}if(e.code==='Space'&&state.phase==='revealed'){e.preventDefault();next();}if(e.key==='Escape'){e.preventDefault();pauseGame();}const key=e.key.toLowerCase();if(['q','w','e'].includes(key)){e.preventDefault();useSkill({q:'hint',w:'freeze',e:'double'}[key]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='question'&&!modal.open)pauseGame();});
async function init(){updateWallet();renderLobby();try{arena=createArena($('#scene'),chooseCharacter);arena.select(state.selected);applyCosmetic();}catch(e){console.error('3D scene unavailable:',e);const label=$('#scene-loading');if(label)label.innerHTML='当前设备暂不支持 3D 渲染<br>仍可在下方参加问答比赛';}try{const response=await fetch('./questions.json');if(!response.ok)throw new Error('题库加载失败');questions=await response.json();if(!Array.isArray(questions)||questions.length<12)throw new Error('题库不完整');}catch(e){console.error(e);toast('题库加载失败，请刷新页面重试。');$('#start-game').disabled=true;$('#start-game').textContent='请刷新重试';}registerTools();}
function snapshot(){return {phase:state.phase,mode:state.mode,selected:people[state.selected].name,round:Math.min(state.round+1,state.queue.length||modes[state.mode].count),question:state.phase==='question'?{text:state.queue[state.round].question,options:state.queue[state.round].options}:null,scores:[...state.scores],remaining:Math.ceil(state.remaining),paused:state.paused};}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[
 {name:'get_quiz_state',description:'Read the current quiz question, scores and state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>snapshot()},
 {name:'start_quiz_match',description:'Start a new single-player match against AI from the lobby.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['classic','blitz','practice']},character:{type:'integer',minimum:0,maximum:3}},required:['mode','character'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||!Object.hasOwn(modes,input.mode)||!Number.isInteger(input.character)||input.character<0||input.character>3||state.phase!=='lobby')throw new Error('A valid mode, character and lobby state are required.');state.mode=input.mode;chooseCharacter(input.character);if(!startGame())throw new Error('Questions are unavailable.');return snapshot();}},
 {name:'submit_quiz_answer',description:'Submit one answer to the current question, completing this round for the player.',inputSchema:{type:'object',properties:{answerIndex:{type:'integer',minimum:0,maximum:3}},required:['answerIndex'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||!Number.isInteger(input.answerIndex)||input.answerIndex<0||input.answerIndex>3||!submitAnswer(input.answerIndex))throw new Error('A valid answer and active unpaused question are required.');return {...snapshot(),result:state.logs.at(-1)};}}
 ];tools.forEach(tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('WebMCP registration failed',e));}catch(e){console.warn('WebMCP unavailable',e);}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
init();
