import test from 'node:test';
import assert from 'node:assert/strict';
import {RailGame} from '../dist/engine.js';
function start(){const g=new RailGame();g.start();return g}
function advance(g,seconds){for(let i=0;i<seconds*10;i++)g.tick(.1)}
test('opposite trains reserve distinct lanes and meet safely',()=>{const g=start();assert(g.dispatch('F101').ok);assert(g.dispatch('K102').ok);assert.equal(g.lanes[1],'F101');assert.equal(g.lanes[2],'K102');advance(g,15);assert.equal(g.meets,1);assert.equal(g.blocks.west,null);assert.equal(g.blocks.east,null)});
test('same lane cannot be reserved from both sides',()=>{const g=start();g.setSwitch('east',1);g.dispatch('F101');const r=g.dispatch('K102');assert(!r.ok);assert.equal(g.safety,97);assert.equal(g.blocks.east,null);assert.equal(g.trains[1].status,'queued')});
test('route switches are locked while trains occupy the section',()=>{const g=start();g.dispatch('F101');assert(!g.setSwitch('west',2).ok);assert.equal(g.switches.west,1);assert.equal(g.safety,100)});
test('unloading and exit alignment are required',()=>{const g=start();g.dispatch('F101');advance(g,15);assert.equal(g.trains[0].status,'working');assert(!g.dispatch('F101').ok);advance(g,10);assert.equal(g.trains[0].status,'ready');assert(!g.dispatch('F101').ok);g.setSwitch('east',1);assert(g.dispatch('F101').ok)});
test('opposing incoming section prevents departure; no position changes on failure',()=>{const g=start();g.dispatch('F101');advance(g,24);g.setSwitch('east',2);g.dispatch('K102');const before=g.trains[0].progress;assert(!g.dispatch('F101').ok);assert.equal(g.trains[0].progress,before);assert.equal(g.blocks.east,'K102')});
test('platform releases only after tail has cleared; exit releases on delivery',()=>{const g=start();g.dispatch('F101');advance(g,24);g.setSwitch('east',1);g.dispatch('F101');advance(g,4);assert.equal(g.lanes[1],'F101');advance(g,2);assert.equal(g.lanes[1],null);assert.equal(g.blocks.east,'F101');advance(g,9);assert.equal(g.blocks.east,null);assert.equal(g.delivered,1);assert.equal(g.money,240);assert.equal(g.onTime,1)});
test('pause freezes schedule, motion and loading without a time jump',()=>{const g=start();g.dispatch('F101');g.running=false;const before=g.snapshot();g.tick(20);assert.deepEqual(g.snapshot(),before);g.running=true;g.tick(1);assert.equal(g.time,1)});
test('passenger trains cannot use freight lane',()=>{const g=start();g.setSwitch('east',3);assert(!g.dispatch('K102').ok);assert.equal(g.safety,100);assert.equal(g.lanes[3],null)});
test('queue arrivals never occupy a blocked line',()=>{const g=start();g.dispatch('F101');advance(g,27);assert.equal(g.trains[2].status,'queued');assert.equal(g.trains[2].lane,null)});
test('end-of-shift is bounded and cannot complete twice',()=>{const g=start();advance(g,301);assert.equal(g.time,300);assert(g.ended);const s=g.snapshot();g.tick(100);assert.deepEqual(g.snapshot(),s);assert(!g.dispatch('F101').ok)});
test('contracts only pay once; upgrades require funds',()=>{const g=start();assert(!g.buy('signals').ok);assert(!g.claim('meet').ok);g.meets=3;assert(g.claim('meet').ok);assert.equal(g.money,300);assert(!g.claim('meet').ok);g.money=900;assert(g.buy('signals').ok);assert.equal(g.money,200);assert(!g.buy('signals').ok)});
test('all 14 trains can be delivered with a consistent safe policy',()=>{const g=start();for(let tick=0;tick<3000;tick++){for(const t of g.trains.filter(t=>t.status==='ready')){const exit=t.dir===1?'east':'west';if(!g.blocks[exit]){g.setSwitch(exit,t.lane);if(g.routeInfo(t).ok)g.dispatch(t.id)}}for(const t of g.trains.filter(t=>t.status==='queued')){if(g.blocks[t.side])continue;const free=[1,2,3].find(l=>!g.lanes[l]&&(!t.passenger||l!==3));if(free){g.setSwitch(t.side,free);if(g.routeInfo(t).ok)g.dispatch(t.id)}}g.tick(.1)}assert.equal(g.delivered,14);assert.equal(g.safety,100);assert(g.meets>0)});
for (const mode of ['rush','night']) test(`${mode} shift remains completable under automatic exit assistance`,()=>{const g=new RailGame(mode);g.start();g.upgrades.signals=true;g.upgrades.loading=true;for(let n=0;n<3001;n++){for(const t of g.trains.filter(t=>t.status==='queued')){if(g.blocks[t.side])continue;const lane=[1,2,3].find(l=>!g.lanes[l]&&(!t.passenger||l!==3));if(lane){g.setSwitch(t.side,lane);if(g.routeInfo(t).ok)g.dispatch(t.id)}}g.tick(.1)}assert.equal(g.delivered,14);assert.equal(g.safety,100);assert(g.trains.every(t=>t.deadline<=300))});
