import './style.css';
import {createIcons,icons} from 'lucide';
import {createWorld} from './scene.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icon=()=>createIcons({icons,attrs:{'stroke-width':1.7}});
const names=['松风小屋','竹影小屋','花园小屋','月见小屋','云杉树屋'];const types=['安静','竹林','花园','安静','森林'];
const templates=[{name:'栗栗',emoji:'🐿️',species:'松鼠',want:'安静',service:'茶点',bio:'带着一本书，来听松风。',price:120},{name:'绵绵',emoji:'🐰',species:'兔子',want:'花园',service:'温泉',bio:'想在开满花的地方睡个好觉。',price:150},{name:'团团',emoji:'🐼',species:'熊猫',want:'竹林',service:'晚餐',bio:'一根竹子，也能慢慢吃一下午。',price:140},{name:'阿鹿',emoji:'🦌',species:'小鹿',want:'森林',service:'茶点',bio:'走了很远的山路，想歇歇脚。',price:165},{name:'桃桃',emoji:'🦊',species:'狐狸',want:'花园',service:'温泉',bio:'听说这里的花香会落进温泉。',price:180},{name:'小满',emoji:'🐻',species:'小熊',want:'安静',service:'晚餐',bio:'想吃一顿热饭，再泡个暖汤。',price:135}];
function newGuest(i){return {...templates[i%templates.length],id:Date.now()+Math.random(),patience:150,maxPatience:150}}
function fresh(){return {version:1,coins:1280,rep:96,day:1,elapsed:0,speed:1,paused:false,rooms:names.slice(0,4).map((name,i)=>({name,type:types[i],state:'free',level:1,guest:null,time:0})),queue:[0,1,2].map(newGuest),staff:[{name:'小熊阿汤',emoji:'🐻',job:'服务'},{name:'浣熊小布',emoji:'🦝',job:'清洁'}],jobs:[],visitors:0,served:0,revenue:0,totalRevenue:0,totalVisitors:0,goalClaimed:false,herbs:3,snacks:3,poolLevel:1,teaLevel:1,marketing:false,autoAssign:false,journal:[],nextArrival:38,arrivalIndex:3}}
let state;try{const saved=JSON.parse(localStorage.getItem('bear-springs-v1'));state=saved?.version===1?saved:fresh()}catch{state=fresh()};state.paused=false;let selected=state.queue[0]?.id,modalType=null,roomFocus=null,toastTimer,audioCtx,audioOn=false,world;
function save(){try{localStorage.setItem('bear-springs-v1',JSON.stringify(state))}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function cash(n){state.coins+=n;if(n>0){state.revenue+=n;state.totalRevenue+=n}save()}
function spend(n){if(state.coins<n){toast('松果币还不够，接待几位旅客再来吧。');return false}state.coins-=n;save();return true}
function render(){
 $('#coins').textContent=state.coins.toLocaleString();$('#reputation').textContent=Math.round(state.rep);$('#occupancy').textContent=`${state.rooms.filter(r=>r.state==='occupied').length} / ${state.rooms.length}`;$('#dayLabel').textContent=`第 ${state.day} 天 · 春日`;const mins=9*60+Math.floor(state.elapsed/240*720);$('#clockLabel').textContent=`${String(Math.floor(mins/60)).padStart(2,'0')}:${String(mins%60).padStart(2,'0')} · ${state.elapsed>160?'夕阳正暖':'晴朗的一天'}`;$('#seasonText').textContent=`SPRING, DAY ${String(state.day).padStart(2,'0')}`;$('#dayProgress').style.width=state.elapsed/240*100+'%';$('#queueCount').textContent=state.queue.length;
 $('#guestList').innerHTML=state.queue.length?state.queue.slice(0,4).map(g=>`<article class="guest ${selected===g.id?'selected':''}" data-guest="${g.id}" tabindex="0"><div class="guest-top"><div class="avatar">${g.emoji}</div><div><div class="guest-name">${g.name} <span style="color:#a7ae97;font-size:9px;font-weight:400">· ${g.species}</span></div><div class="guest-sub">${g.bio}</div></div></div><div class="guest-tags"><span class="tag">♡ 喜欢${g.want}</span><span class="tag warm">♨ ${g.service}</span><span class="guest-price">${g.price} <span style="font-size:8px">/晚</span></span></div><div class="patience"><span>等待中</span><div><i style="width:${g.patience/g.maxPatience*100}%;background:${g.patience<40?'#cb9980':'#a6b68b'}"></i></div><span>${Math.ceil(g.patience)}s</span></div>${selected===g.id?'<button class="assign-btn" data-assign="'+g.id+'">为 TA 安排客房 <i data-lucide="arrow-right"></i></button>':''}</article>`).join(''):'<div class="empty">🍃<br>林间小路静悄悄<br>下一位朋友很快就到。</div>';
 $('#roomList').innerHTML=state.rooms.map((r,i)=>`<div class="room-row" data-room="${i}" tabindex="0"><div class="room-icon"><i data-lucide="${i===2?'flower-2':i===1?'sprout':'house'}"></i></div><div><b>${r.name} ${r.level>1?'✧':''}</b><small>${r.state==='occupied'?r.guest.name+' · '+(r.time>0?Math.ceil(r.time)+'s 后退房':'准备退房'):r.type+' · '+(r.level===1?'标准客房':'精致客房')}</small></div><span class="room-state ${r.state}">${r.state==='free'?'空闲':r.state==='occupied'?'入住中':r.state==='cleaning'?'清洁中':'待清洁'}</span></div>`).join('');$('.tiny-tag').textContent=state.rooms.length+' 间小屋';
 const goals=[['接待 3 位旅客',state.visitors,3],['完成 2 次暖心服务',state.served,2],['赚取 500 松果币',state.revenue,500]];$('#goalList').innerHTML=goals.map(([t,n,max])=>`<div class="goal"><div class="goal-top"><i data-lucide="${n>=max?'circle-check':'circle'}"></i>${t}<span>${Math.min(n,max)} / ${max}</span></div><div class="goal-progress"><i style="width:${Math.min(n/max*100,100)}%"></i></div></div>`).join('');const count=goals.filter(g=>g[1]>=g[2]).length;$('#goalCount').textContent=count+' / 3';$('#claimGoal').disabled=count<3||state.goalClaimed;$('#claimGoal').innerHTML=state.goalClaimed?'<span>今日小目标已完成</span><b>明天见 ✧</b>':'<span>✧ 完成全部目标</span><b>领取 200 <span class="coin">●</span></b>';
 const requests=state.rooms.filter(r=>r.state==='occupied'&&r.request&&!r.serviceDone).length;$('#serviceBadge').textContent=requests;$('#serviceBadge').classList.toggle('hidden',!requests);$('#pause').innerHTML=`<i data-lucide="${state.paused?'play':'pause'}"></i>`;$$('.speed').forEach(b=>b.classList.toggle('active',+b.dataset.speed===state.speed));icon();bindDynamic();
}
function bindDynamic(){ $$('[data-guest]').forEach(el=>{el.onclick=()=>{selected=+el.dataset.guest;render()};el.onkeydown=e=>{if(e.key==='Enter'){selected=+el.dataset.guest;showAssign()}}});$$('[data-assign]').forEach(el=>el.onclick=e=>{e.stopPropagation();selected=+el.dataset.assign;showAssign()});$$('[data-room]').forEach(el=>{el.onclick=()=>showRoom(+el.dataset.room);el.onkeydown=e=>{if(e.key==='Enter')showRoom(+el.dataset.room)}})}
function openModal(type,html){modalType=type;$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden');icon();$('#closeModal').focus()}
function closeModal(){modalType=null;$('#modalBackdrop').classList.add('hidden');$$('.dock-item').forEach(b=>b.classList.toggle('active',b.dataset.tab==='overview'))}
const title=(tag,name,sub)=>`<span class="modal-eyebrow">${tag}</span><h2 class="modal-title">${name}</h2><p class="modal-sub">${sub}</p>`;
function showAssign(){const g=state.queue.find(g=>g.id===selected);if(!g)return toast('先选择一位等待中的旅客。');openModal('assign',title('A ROOM FOR A FRIEND',`给${g.name}一间温暖的小屋`,` ${g.emoji} 喜欢${g.want}的环境，想体验${g.service}。匹配偏好可获得 25% 房费加成。`)+state.rooms.map((r,i)=>`<div class="option-row"><div class="option-icon">${r.type==='花园'?'🌼':'🏡'}</div><div class="option-text"><b>${r.name} ${r.type===g.want?'· ♡ 心仪客房':''}</b><small>${r.type} · Lv.${r.level} · ${r.state==='free'?'干净舒适，随时入住':r.state==='occupied'?'已有旅客入住':r.state==='dirty'?'等待清洁':'清洁进行中'}</small></div><button class="primary" data-checkin="${i}" ${r.state!=='free'?'disabled':''}>${r.state==='free'?'安排入住':'暂不可用'}</button></div>`).join(''));$$('[data-checkin]').forEach(b=>b.onclick=()=>checkIn(+b.dataset.checkin,g.id))}
function checkIn(i,id){const room=state.rooms[i],g=state.queue.find(g=>g.id===id);if(!g||room.state!=='free')return;const payment=Math.round(g.price*(room.type===g.want?1.25:1)*(room.type==='花园'?1.2:1)*(1+(room.level-1)*.25));Object.assign(room,{state:'occupied',guest:g,time:65+Math.random()*25,request:false,serviceDone:false,requestAt:10+Math.random()*8});state.queue=state.queue.filter(x=>x.id!==id);selected=state.queue[0]?.id;state.visitors++;state.totalVisitors++;cash(payment);closeModal();render();toast(`${g.emoji} ${g.name}住进了${room.name}，+${payment} 松果币${room.type===g.want?' · 偏好满足 ♡':''}`);chime()}
function showRoom(i){roomFocus=i;const r=state.rooms[i];openModal('room',title('A LITTLE WOODLAND HOME',r.name,`${r.type}景观 · Lv.${r.level} · 房费加成 ${Math.round((r.level-1)*25)}%`)+(r.state==='occupied'?`<div class="option-row"><div class="option-icon">${r.guest.emoji}</div><div class="option-text"><b>${r.guest.name}正在好好休息</b><small>${r.guest.bio}<br>约 ${Math.ceil(r.time)} 秒后离店 · ${r.serviceDone?'已经享受暖心服务':r.request?'正在等待'+r.guest.service:'暂时没有服务需求'}</small></div></div>${r.request&&!r.serviceDone?'<button class="primary" id="roomService">安排'+r.guest.service+'服务</button>':''}`:r.state==='free'?'<div class="empty">🛏️<br>被子晒过太阳，房间已经准备好了。</div><button class="primary" id="roomAssign">接待等待中的旅客</button>':`<div class="empty">🧹<br>${r.state==='dirty'?'上一位旅客刚刚离开，房间需要打扫。':'伙伴正在打扫，干净的小屋很快就好。'}</div><button class="primary" id="cleanRoom" ${r.state==='cleaning'?'disabled':''}>安排清洁 · 免费</button>`)+`<div class="option-row" style="margin-top:20px"><div class="option-text"><b>${r.level<3?'升级舒适度':'已达最高等级'}</b><small>每级增加 25% 房费，换上更柔软的被褥。</small></div><button class="secondary" id="upgradeRoom" ${r.level>=3?'disabled':''}>${r.level>=3?'已满级':r.level*300+' 松果币'}</button></div>`);$('#roomAssign')?.addEventListener('click',()=>{if(state.queue.length)showAssign();else toast('暂时没有等待中的旅客。')});$('#cleanRoom')?.addEventListener('click',()=>{scheduleClean(i);showRoom(i)});$('#roomService')?.addEventListener('click',()=>{scheduleService(i);showRoom(i)});$('#upgradeRoom').onclick=()=>{if(spend(r.level*300)){r.level++;render();showRoom(i);toast('柔软的被褥、新鲜的花束，小屋升级了。')}}}
function scheduleClean(i){const r=state.rooms[i];if(r.state!=='dirty')return; r.state='cleaning';state.jobs.push({type:'clean',room:i,time:14,total:14,started:false});save();render();toast('清洁任务已加入伙伴的工作队列。')}
function scheduleService(i){const r=state.rooms[i];if(!r||r.state!=='occupied'||r.serviceDone)return;if(state.jobs.some(j=>j.type==='service'&&j.room===i))return toast('伙伴已经收到安排，请稍等。');const cost=r.guest.service==='晚餐'?12:r.guest.service==='温泉'?8:5;if(!spend(cost))return;const total=r.guest.service==='温泉'?16:12;state.jobs.push({type:'service',room:i,time:total,total,started:false});render();save();toast(`${r.guest.service}已加入服务队列，材料费 ${cost} 松果币。`)}
function showServices(){openModal('services',title('WARM WATER, WARM HEARTS','暖汤与小小心意','为入住旅客安排服务。服务伙伴会按顺序处理，完成后收获收益与好评。')+state.rooms.filter(r=>r.state==='occupied').map(r=>{const i=state.rooms.indexOf(r),job=state.jobs.find(j=>j.room===i&&j.type==='service');return `<div class="option-row"><div class="option-icon">${r.guest.emoji}</div><div class="option-text"><b>${r.guest.name} · ${r.guest.service}</b><small>${r.name} · ${r.serviceDone?'已经心满意足 ♡':job?(job.started?'正在服务':'排队中')+' · '+Math.ceil(job.time)+'s':'需要一点暖心照顾'}</small>${job?`<span class="progress-pill"><i style="width:${(1-job.time/job.total)*100}%"></i></span>`:''}</div><button class="primary" data-service="${i}" ${r.serviceDone||job?'disabled':''}>${r.serviceDone?'已完成':job?'进行中':'安排服务'}</button></div>`}).join('')+(state.rooms.every(r=>r.state!=='occupied')?'<div class="empty">♨<br>先迎接一位旅客，再送上一份温暖。</div>':'')+`<p class="modal-bottom">温泉 Lv.${state.poolLevel} · 茶屋 Lv.${state.teaLevel} ｜ 草药 ${state.herbs} 份 · 点心 ${state.snacks} 份<br>草药与点心会在对应服务完成时自动使用，增加 30 松果币收益。</p>`);$$('[data-service]').forEach(b=>b.onclick=()=>{scheduleService(+b.dataset.service);showServices()})}
function showStaff(){openModal('staff',title('BETTER TOGETHER','森林里的好伙伴','伙伴会自动处理分工范围内的任务。清洁伙伴会主动打扫空出的房间，服务任务由你安排。')+state.staff.map((p,i)=>`<div class="option-row"><div class="option-icon">${p.emoji}</div><div class="option-text"><b>${p.name}</b><small>${p.job==='服务'?'为旅客送去温暖，处理泡汤、茶点与晚餐。':'发现脏房间后主动清洁，让下一位客人安心入住。'}</small><div class="service-choice"><button data-job="${i}:服务" class="${p.job==='服务'?'active':''}">♨ 暖心服务</button><button data-job="${i}:清洁" class="${p.job==='清洁'?'active':''}">🧹 客房清洁</button></div></div></div>`).join('')+`<div class="option-row"><div class="option-icon">🦦</div><div class="option-text"><b>${state.staff.length>=4?'伙伴们都到齐啦':'邀请一位新伙伴'}</b><small>更多伙伴可以同时处理更多任务 · 每日工资 30 / 位</small></div><button class="primary" id="hire" ${state.staff.length>=4?'disabled':''}>${state.staff.length>=4?'已满员':'邀请 · 350'}</button></div>`);$$('[data-job]').forEach(b=>b.onclick=()=>{const[i,job]=b.dataset.job.split(':');state.staff[i].job=job;save();showStaff();toast('分工已更新，伙伴开始新的工作。')});$('#hire').onclick=()=>{if(spend(350)){state.staff.push({name:state.staff.length===2?'水獭阿圆':'狐狸小橘',emoji:state.staff.length===2?'🦦':'🦊',job:'服务'});render();showStaff()}}}
function showBuild(){openModal('build',title('MAKE ROOM FOR LITTLE JOYS','让美好，再长大一点','用经营积攒的松果币，为森林里的朋友添一份舒适。')+`<div class="option-row"><div class="option-icon">🌲</div><div class="option-text"><b>扩建 · 云杉树屋</b><small>解锁第 5 间森林客房，可接待更多旅客。</small></div><button class="primary" id="newRoom" ${state.rooms.length>=5?'disabled':''}>${state.rooms.length>=5?'已建成':'建造 · 650'}</button></div><div class="option-row"><div class="option-icon">♨️</div><div class="option-text"><b>森林温泉 · Lv.${state.poolLevel}</b><small>每升一级，温泉服务收益增加 25 松果币。</small></div><button class="primary" id="poolUpgrade" ${state.poolLevel>=3?'disabled':''}>${state.poolLevel>=3?'已满级':'升级 · '+state.poolLevel*400}</button></div><div class="option-row"><div class="option-icon">🍵</div><div class="option-text"><b>林间茶屋 · Lv.${state.teaLevel}</b><small>每升一级，茶点与晚餐收益增加 20 松果币。</small></div><button class="primary" id="teaUpgrade" ${state.teaLevel>=3?'disabled':''}>${state.teaLevel>=3?'已满级':'升级 · '+state.teaLevel*300}</button></div><div class="option-row"><div class="option-icon">📮</div><div class="option-text"><b>森林明信片</b><small>让朋友们知道这里。永久提高旅客到访速度。</small></div><button class="primary" id="market" ${state.marketing?'disabled':''}>${state.marketing?'已寄出':'寄出 · 200'}</button></div>`);$('#newRoom').onclick=()=>{if(spend(650)){state.rooms.push({name:names[4],type:types[4],state:'free',level:1,guest:null,time:0});world?.unlock();render();showBuild();toast('云杉树屋建好啦！森林又多了一盏灯。')}};$('#poolUpgrade').onclick=()=>{if(spend(state.poolLevel*400)){state.poolLevel++;render();showBuild()}};$('#teaUpgrade').onclick=()=>{if(spend(state.teaLevel*300)){state.teaLevel++;render();showBuild()}};$('#market').onclick=()=>{if(spend(200)){state.marketing=true;render();showBuild();toast('明信片已寄出，更多朋友会找到这里。')}}}
function showShop(){openModal('shop',title('FROM THE FOREST, WITH LOVE','森林小商店','备好草药和点心，让每一次服务都多一点惊喜。')+`<div class="option-row"><div class="option-icon">🌿</div><div class="option-text"><b>山间草药 · 3 份</b><small>库存 ${state.herbs} 份 · 温泉服务自动消耗一份，收益 +30。</small></div><button class="primary" id="buyHerbs">购买 · 45</button></div><div class="option-row"><div class="option-icon">🍡</div><div class="option-text"><b>栗子点心 · 3 份</b><small>库存 ${state.snacks} 份 · 茶点或晚餐自动消耗一份，收益 +30。</small></div><button class="primary" id="buySnacks">购买 · 45</button></div><div class="option-row"><div class="option-icon">🍯</div><div class="option-text"><b>蜂蜜欢迎茶</b><small>给所有等待中的旅客送一杯热茶，耐心恢复 45 秒。</small></div><button class="primary" id="buyTea">分享 · 30</button></div>`);$('#buyHerbs').onclick=()=>{if(spend(45)){state.herbs+=3;render();showShop();toast('草药补给已送到温泉。')}};$('#buySnacks').onclick=()=>{if(spend(45)){state.snacks+=3;render();showShop();toast('热乎乎的栗子点心准备好了。')}};$('#buyTea').onclick=()=>{if(!state.queue.length)return toast('暂时没有等待中的旅客。');if(spend(30)){state.queue.forEach(g=>g.patience=Math.min(g.maxPatience,g.patience+45));render();toast('大家喝到了蜂蜜茶，等待也变得甜甜的。')}}}
function showStats(){openModal('stats',title('OUR LITTLE STORY','把温暖，记在手账里',`第 ${state.day} 天营业记录。每一枚松果币，都是一位朋友留下的心意。`)+`<div class="stat-grid"><div class="stat-box"><b>${state.revenue}</b><span>今日营业收入</span></div><div class="stat-box"><b>${state.visitors}</b><span>今日接待旅客</span></div><div class="stat-box"><b>${state.served}</b><span>暖心服务次数</span></div></div><div class="option-row"><div class="option-text"><b>开业以来</b><small>累计接待 ${state.totalVisitors} 位朋友，累计营业收入 ${state.totalRevenue} 松果币。<br>旅馆好评度 ${Math.round(state.rep)} / 100 · 共 ${state.rooms.length} 间客房、${state.staff.length} 位伙伴</small></div></div>`+state.journal.slice(-5).reverse().map(j=>`<div class="option-row"><div class="option-icon">${j.emoji}</div><div class="option-text"><b>${j.name}的旅行小记</b><small>「${j.review}」<br>第 ${j.day} 天 · ${j.happy?'★★★★★':'★★★☆☆'}</small></div></div>`).join(''))}
function showGuide(){openModal('guide',title('A SLOW & LOVELY START','小熊店长的经营指南','不必着急。先给旅客一个舒服的落脚处，再把今天过得暖暖的。')+[['迎接森林来客','点击左侧旅客，选择空闲客房。偏好匹配可增加 25% 房费，春日花园房额外增加 20%。'],['送上一份暖心服务','入住后点击「温泉与服务」安排茶点、泡汤或晚餐。伙伴按队列处理；错过服务会影响好评。'],['照顾好每一间小屋','旅客约 65–90 秒后退房。清洁伙伴自动打扫，你也可以点击房间手动加入清洁队列。'],['让旅馆慢慢长大','完成每日目标领取奖励。建设新客房、升级设施、邀请伙伴，在商店补充草药和点心。'],['按照自己的节奏','底部可暂停或调整速度。一天约 4 分钟，可点击月亮提前打烊。游戏自动保存，关闭面板用 Esc。拖动画面旋转，滚轮缩放。']].map((s,i)=>`<div class="guide-step"><span>${i+1}</span><div><strong>${s[0]}</strong><br>${s[1]}</div></div>`).join(''))}
function endDay(){state.paused=true;const wages=state.staff.length*30;openModal('endday',title('THE LIGHTS ARE STILL WARM',`第 ${state.day} 天，辛苦啦。`,'山风轻了，灯火暖了。收好今天的小小收获，明天再迎接新的朋友。')+`<div class="stat-grid"><div class="stat-box"><b>${state.visitors}</b><span>接待旅客</span></div><div class="stat-box"><b>${state.revenue}</b><span>营业收入</span></div><div class="stat-box"><b>${state.served}</b><span>暖心服务</span></div></div><p class="modal-sub">明日开门时支付伙伴工资 ${wages} 松果币。<br>尚未退房的旅客与未完成的服务会继续保留。</p><button class="primary" id="nextDay" style="width:100%">睡个好觉，开启第 ${state.day+1} 天 <span style="margin-left:8px">☀</span></button>`);render();$('#nextDay').onclick=()=>{if(state.coins<wages)toast('伙伴们决定陪你共渡难关，今天免收工资。');else state.coins-=wages;state.day++;state.elapsed=0;state.visitors=0;state.revenue=0;state.served=0;state.goalClaimed=false;state.paused=false;state.queue.forEach(g=>g.patience=g.maxPatience);state.nextArrival=25;closeModal();world?.setNight(false);save();render();toast('早上好，小熊店长。新的一天开始了！')}}
function settings(){openModal('settings',title('YOUR OWN PACE','慢慢来，也很好','存档保存在当前浏览器。可以开启自动分房，让小熊帮忙照顾等待中的朋友。')+`<div class="option-row"><div class="option-text"><b>小熊自动分房</b><small>优先匹配偏好，再安排其他空闲客房。</small></div><button class="primary" id="autoToggle">${state.autoAssign?'已开启':'开启'}</button></div><div class="option-row"><div class="option-text"><b>重新开始旅馆生活</b><small>清除当前经营存档，回到第 1 天。</small></div><button class="secondary" id="resetGame">重新开始</button></div>`);$('#autoToggle').onclick=()=>{state.autoAssign=!state.autoAssign;save();settings()};$('#resetGame').onclick=()=>{openModal('reset',title('A FRESH START','真的要重新开始吗？','当前松果币、客房升级和经营记录将被清除。')+'<button class="secondary" id="cancelReset">保留我的旅馆</button> <button class="primary" id="confirmReset">清除并重新开始</button>');$('#cancelReset').onclick=settings;$('#confirmReset').onclick=()=>{localStorage.removeItem('bear-springs-v1');location.reload()}}}
function tick(dt){if(state.paused||modalType==='endday')return;state.elapsed+=dt;state.nextArrival-=dt;state.queue.forEach(g=>g.patience-=dt);const lost=state.queue.filter(g=>g.patience<=0);if(lost.length){state.rep=Math.max(0,state.rep-lost.length*3);state.queue=state.queue.filter(g=>g.patience>0);if(!state.queue.some(g=>g.id===selected))selected=state.queue[0]?.id;toast(`${lost[0].name}等得有些久，先去森林里散步了。`)}if(state.nextArrival<=0){if(state.queue.length<4){state.queue.push(newGuest(state.arrivalIndex++));if(!selected)selected=state.queue[0].id}state.nextArrival=state.marketing?22:38}
 state.rooms.forEach((r,i)=>{if(r.state==='occupied'){r.time-=dt;r.requestAt-=dt;if(r.requestAt<=0&&!r.request){r.request=true;toast(`${r.guest.emoji} ${r.guest.name}想体验${r.guest.service}，去服务面板安排吧。`)}if(r.time<=0){const happy=r.serviceDone;state.rep=Math.max(0,Math.min(100,state.rep+(happy?1:-2)));if(happy)cash(25);state.journal.push({name:r.guest.name,emoji:r.guest.emoji,day:state.day,happy,review:happy?'热汤暖了身，店长暖了心。下次还想来住！':'小屋很舒服，不过期待的服务还没等到。'});state.journal=state.journal.slice(-30);state.jobs=state.jobs.filter(j=>j.room!==i);r.state='dirty';r.guest=null;}}});
 const cleaners=state.staff.filter(p=>p.job==='清洁').length;if(cleaners)state.rooms.forEach((r,i)=>{if(r.state==='dirty'){r.state='cleaning';state.jobs.push({type:'clean',room:i,time:14,total:14,started:false})}});
 for(const type of['clean','service']){const slots=state.staff.filter(p=>p.job===(type==='clean'?'清洁':'服务')).length;state.jobs.filter(j=>j.type===type).forEach((j,i)=>{j.started=i<slots;if(j.started)j.time-=dt})}
 const completed=state.jobs.filter(j=>j.time<=0);state.jobs=state.jobs.filter(j=>j.time>0);completed.forEach(j=>{const r=state.rooms[j.room];if(j.type==='clean'){r.state='free';r.guest=null}else if(r.state==='occupied'){r.serviceDone=true;state.served++;let earnings=r.guest.service==='温泉'?55+(state.poolLevel-1)*25:45+(state.teaLevel-1)*20;const supply=r.guest.service==='温泉'?'herbs':'snacks';if(state[supply]>0){state[supply]--;earnings+=30}cash(earnings);state.rep=Math.min(100,state.rep+1);toast(`♡ ${r.guest.name}的${r.guest.service}完成，+${earnings} 松果币。`);chime()}});
 if(state.autoAssign&&state.queue.length){const g=state.queue[0];let ri=state.rooms.findIndex(r=>r.state==='free'&&r.type===g.want);if(ri<0)ri=state.rooms.findIndex(r=>r.state==='free');if(ri>=0)checkIn(ri,g.id)}if(state.elapsed>=240){state.elapsed=240;endDay()}if(state.elapsed>160)world?.setNight(true);
}
function chime(){if(!audioOn||!audioCtx)return;[523,659,784].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,audioCtx.currentTime+i*.09);g.gain.linearRampToValueAtTime(.055,audioCtx.currentTime+i*.09+.03);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+i*.09+.6);o.connect(g);g.connect(audioCtx.destination);o.start(audioCtx.currentTime+i*.09);o.stop(audioCtx.currentTime+i*.09+.7)})}
$('#sound').onclick=()=>{audioOn=!audioOn;if(audioOn){audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();chime()}$('#sound').innerHTML=`<i data-lucide="${audioOn?'volume-2':'volume-x'}"></i>`;$('#sound').title=audioOn?'关闭音效':'开启音效';icon();toast(audioOn?'轻柔的经营音效已开启。':'音效已关闭。')};$('#settings').onclick=settings;$('#closeModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.code==='Space'&&e.target===document.body){e.preventDefault();state.paused=!state.paused;render()}});$('#pause').onclick=()=>{state.paused=!state.paused;render();toast(state.paused?'时光暂停了，慢慢规划吧。':'时光继续流动。')};$$('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;state.paused=false;render()});$('#endDay').onclick=endDay;$('#expandRooms').onclick=showBuild;$('#claimGoal').onclick=()=>{if(state.visitors>=3&&state.served>=2&&state.revenue>=500&&!state.goalClaimed){state.goalClaimed=true;state.coins+=200;save();render();toast('今日目标全部完成！200 松果币已收入小口袋。');chime()}};
const tabs={overview:closeModal,services:showServices,staff:showStaff,build:showBuild,shop:showShop,stats:showStats};$$('[data-tab]').forEach(b=>b.onclick=()=>{tabs[b.dataset.tab]();$$('.dock-item').forEach(x=>x.classList.toggle('active',x===b))});$$('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='guide')showGuide();else if(b.dataset.nav==='journal')showStats();else closeModal()});
render();try{world=createWorld((type,id)=>{if(type==='room')showRoom(id);else if(type==='services')showServices();else showGuide()});if(state.rooms.length>4)world.unlock()}catch(e){console.error(e);$('#worldLabels').innerHTML='<div class="empty" style="position:absolute;top:40%;width:100%">3D 画面需要启用浏览器硬件加速。<br>你仍然可以通过两侧面板经营旅馆。</div>'}
let last=performance.now(),ui=0,sv=0;function loop(now){const dt=Math.min((now-last)/1000,1);last=now;tick(dt*state.speed);ui+=dt;sv+=dt;if(ui>.8){ui=0;render();if(modalType==='services')showServices()}if(sv>5){sv=0;save()}requestAnimationFrame(loop)}requestAnimationFrame(loop);document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)save()});window.addEventListener('beforeunload',save);
