import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import './style.css';
import {SilkPhysics,segmentDistance} from './physics.js';

const $=id=>document.getElementById(id), canvas=$('scene'),world=document.querySelector('.world');
const SAVE='silkbound-save-v1';
const defaults={silk:120,energy:0,night:1,caught:0,built:0,upgraded:0,questClaimed:false,levels:{silk:1,sticky:1,metabolism:1}};
let stored;try{stored=JSON.parse(localStorage.getItem(SAVE));}catch{}
let state={...defaults,...stored,levels:{...defaults.levels,...stored?.levels}};
let tool='weave',selected=null,paused=false,phase='build',remaining=60,elapsed=0,spawnClock=0,nightCatches=0,nightEnergy=0,wind=1.2,storm=false,modalPaused=false;
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('toast').textContent='当前浏览器不支持 WebGL，请使用支持硬件加速的浏览器。';$('toast').classList.add('show');throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x182d2b);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x203d37,.045);
const camera=new THREE.PerspectiveCamera(43,1,.1,100);const target=new THREE.Vector3(.15,4,0);let orbit={theta:.075,phi:1.39,distance:16.4};
function updateCamera(){camera.position.set(target.x+orbit.distance*Math.sin(orbit.theta)*Math.sin(orbit.phi),target.y+orbit.distance*Math.cos(orbit.phi),orbit.distance*Math.cos(orbit.theta)*Math.sin(orbit.phi));camera.lookAt(target);}
updateCamera();
scene.add(new THREE.HemisphereLight(0xc9e2ca,0x182b23,2));const moon=new THREE.DirectionalLight(0xe8f1ce,3);moon.position.set(-4,12,5);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);moon.shadow.camera.left=-12;moon.shadow.camera.right=12;moon.shadow.camera.top=14;moon.shadow.camera.bottom=-5;scene.add(moon);const fill=new THREE.DirectionalLight(0x80bdc5,1.4);fill.position.set(8,6,-8);scene.add(fill);
const rand=(a,b)=>a+Math.random()*(b-a);let seed=63;const sr=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};const rr=(a,b)=>a+sr()*(b-a);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.94,...opts});
const bark=mat(0x354b3c),barkDark=mat(0x253c32),barkLight=mat(0x52604a),leafMats=[mat(0x42694a),mat(0x2e5741),mat(0x658552),mat(0x253f33)],stoneMats=[mat(0x344b42),mat(0x536653)];leafMats.forEach(m=>m.side=THREE.DoubleSide);
function mesh(geo,material,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);parent.add(m);return m;}
function branch(a,b,r1,r2,material=bark,parent=scene){const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),dir=end.clone().sub(start);const m=mesh(new THREE.CylinderGeometry(r2,r1,dir.length(),7,1),material,0,0,0,parent);m.position.copy(start.add(end).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());m.castShadow=true;return m;}
const ground=mesh(new THREE.PlaneGeometry(120,120),mat(0x203b2a),0,-.5,-14);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
// Layered woodland: trunk silhouettes, angled roots and leafy canopies.
for(let i=0;i<47;i++){const x=rr(-25,25),z=rr(-35,-6),r=rr(.13,.6),h=rr(10,23);branch([x,-.5,z],[x+rr(-2,2),h,z],r,r*.53,i%3?barkDark:bark);for(let j=0;j<3;j++){const yy=h*rr(.5,.85),endX=x+rr(-4,4);branch([x,yy,z],[endX,yy+rr(1,3),z+rr(-1,1)],r*.45,.04,barkDark);const crown=mesh(new THREE.IcosahedronGeometry(rr(1.7,3.8),1),leafMats[i%4],endX,yy+2,z);crown.scale.y=.6;}}
// Foreground framing trees and the branches that anchor the web.
branch([-5.5,-1,.15],[-5.8,12,-.3],.71,.4,bark);branch([5.4,-1,-.1],[6.7,13,-1.5],.83,.41,barkDark);
branch([-5.6,4.7,0],[-3.05,7.24,0],.24,.06,barkLight);branch([-5.7,7.1,0],[-.1,9.35,-.4],.29,.07,bark);
branch([5.9,5.4,-.4],[3.15,7.35,0],.24,.045,bark);branch([5.5,2.4,0],[3.35,1.68,0],.2,.055,barkLight);branch([-5.4,1.2,.2],[-3.4,1.65,0],.2,.05,barkLight);
for(const side of [-1,1])for(let i=0;i<6;i++){branch([side*5.5,0,0],[side*(5.5+rr(-2,1.4)),-.3,rr(0,3)],.3,.02,barkDark);}
for(let i=0;i<60;i++){const x=rr(-10,10),z=rr(-6,6);if(Math.abs(x)<3&&z<2)continue;const rock=mesh(new THREE.IcosahedronGeometry(rr(.12,.6),0),stoneMats[i%2],x,-.25,z);rock.scale.set(1.4,.7,1);rock.rotation.set(rr(0,3),rr(0,3),0);}
// Each fern leaf is a curved tapered blade; all plant geometry shares four materials.
function fern(x,y,z,size){const group=new THREE.Group();group.position.set(x,y,z);group.rotation.y=rr(0,6.28);scene.add(group);for(let f=0;f<6;f++){const a=f/6*Math.PI*2,verts=[];for(let j=0;j<8;j++){const t=j/7,rad=t*size,yy=Math.sin(t*Math.PI*.86)*size*.55;const width=Math.sin(t*Math.PI)*size*.065;verts.push(Math.cos(a)*rad-Math.sin(a)*width,yy,Math.sin(a)*rad+Math.cos(a)*width,Math.cos(a)*rad+Math.sin(a)*width,yy,Math.sin(a)*rad-Math.cos(a)*width);}const idx=[];for(let j=0;j<7;j++)idx.push(j*2,j*2+1,j*2+2,j*2+1,j*2+3,j*2+2);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(idx);geo.computeVertexNormals();const m=leafMats[f%4];mesh(geo,m,0,0,0,group);for(let j=2;j<7;j++){const t=j/7,rad=t*size,yy=Math.sin(t*Math.PI*.86)*size*.55;for(const s of [-1,1]){const l=mesh(new THREE.ConeGeometry(size*(1-t)*.095,size*(1-t)*.49,3),leafMats[(f+j)%4],Math.cos(a)*rad-Math.sin(a)*s*size*(1-t)*.1,yy,Math.sin(a)*rad+Math.cos(a)*s*size*(1-t)*.1,group);l.rotation.z=s*1.15;l.rotation.y=-a;}}}}
for(let i=0;i<64;i++){const x=rr(-12,12),z=rr(-9,5);fern(x,-.2,z,rr(.4,1.4));}fern(-4.5,-.1,3,2.5);fern(4,-.2,3,2.6);
for(let i=0;i<13;i++){const x=rr(-5.8,-3.8),z=rr(-.2,2.5),h=rr(.12,.4);mesh(new THREE.CylinderGeometry(.026,.045,h,5),mat(0x9caa81),x,h/2-.2,z);const cap=mesh(new THREE.SphereGeometry(h*.55,9,5,0,Math.PI*2,0,Math.PI/2),mat(i%2?0xcaa967:0x8baf9d),x,h-.2,z);cap.scale.y=.45;}
// Soft shafts of light and drifting woodland motes.
const shaftMat=new THREE.MeshBasicMaterial({color:0xc4d7ac,transparent:true,opacity:.018,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending});for(let i=0;i<8;i++){const ray=mesh(new THREE.PlaneGeometry(rr(.2,1),24),shaftMat,rr(-8,8),8,rr(-16,-5));ray.rotation.z=-.32;}
const dustGeometry=new THREE.BufferGeometry(),dustPositions=new Float32Array(180*3);for(let i=0;i<180;i++){dustPositions[i*3]=rr(-10,10);dustPositions[i*3+1]=rr(0,12);dustPositions[i*3+2]=rr(-10,5);}dustGeometry.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({color:0xd4e9a6,size:.035,transparent:true,opacity:.7,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(dust);
const glowTexture=(()=>{const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(226,255,175,1)');g.addColorStop(.15,'rgba(195,255,128,.65)');g.addColorStop(1,'rgba(165,255,100,0)');ctx.fillStyle=g;ctx.fillRect(0,0,64,64);return new THREE.CanvasTexture(c);})();
const fireflies=[];for(let i=0;i<22;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:0xc6fda4,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set(rr(-9,9),rr(.5,8),rr(-9,3));s.scale.setScalar(rr(.07,.15));scene.add(s);fireflies.push({s,base:s.position.clone(),phase:rr(0,6.28)});}

// Merge the static woodland by material to keep draw calls low on laptops.
scene.updateMatrixWorld(true);
const staticGroups=new Map(),originalMeshes=[];
scene.traverse(o=>{if(o.isMesh){const key=o.material.uuid+String(o.castShadow)+String(o.receiveShadow);if(!staticGroups.has(key))staticGroups.set(key,{material:o.material,cast:o.castShadow,receive:o.receiveShadow,geometries:[]});const g=o.geometry.clone();g.applyMatrix4(o.matrixWorld);staticGroups.get(key).geometries.push(g);originalMeshes.push(o);}});
for(const o of originalMeshes)o.removeFromParent();
for(const group of staticGroups.values()){const geometry=mergeGeometries(group.geometries,false);if(geometry){const combined=new THREE.Mesh(geometry,group.material);combined.castShadow=group.cast;combined.receiveShadow=group.receive;scene.add(combined);}for(const g of group.geometries)g.dispose();}

const physics=new SilkPhysics(),webGroup=new THREE.Group();scene.add(webGroup);const CX=.45,CY=4.15,ringNodes=[];const center=physics.addNode(CX,CY,.02);
for(let ring=0;ring<5;ring++){const nodes=[],radius=[.65,1.22,1.9,2.62,3.35][ring];for(let i=0;i<12;i++){const a=i/12*Math.PI*2;nodes.push(physics.addNode(CX+Math.cos(a)*radius*(1+Math.sin(i*7)*.045),CY+Math.sin(a)*radius*.95,Math.sin(a*2)*.065,ring===4));}ringNodes.push(nodes);}
for(let i=0;i<12;i++){physics.connect(center,ringNodes[0][i]);for(let r=0;r<4;r++){physics.connect(ringNodes[r][i],ringNodes[r+1][i]);if(!(r===3&&[1,2,8,9].includes(i)))physics.connect(ringNodes[r][i],ringNodes[r][(i+1)%12]);}}
// Attach outer web to solid boughs, creating a natural silhouette.
const anchors=[[-4.7,7.1,0],[-4.9,3.9,0],[-4.4,1.4,0],[4.9,1.6,0],[5.3,4.1,0],[4.6,7.4,0],[.1,9,0]];
for(const [x,y,z] of anchors){const n=physics.addNode(x,y,z,true);const closest=ringNodes[4].reduce((a,b)=>Math.hypot(a.x-x,a.y-y)<Math.hypot(b.x-x,b.y-y)?a:b);physics.connect(n,closest);}
let savedWeb=stored?.web;if(savedWeb?.nodes?.length&&savedWeb?.edges?.length){try{physics.nodes=[];physics.edges=[];physics.nextId=0;for(const n of savedWeb.nodes)physics.addNode(n.x,n.y,n.z,n.fixed);for(const e of savedWeb.edges){const edge=physics.connect(physics.nodes[e.a],physics.nodes[e.b],e.reinforced);if(edge)edge.health=e.health??1;}}catch{localStorage.removeItem(SAVE);location.reload();}}
const maxSegments=6000,webGeo=new THREE.BufferGeometry(),webPos=new Float32Array(maxSegments*6),webColor=new Float32Array(maxSegments*6);webGeo.setAttribute('position',new THREE.BufferAttribute(webPos,3).setUsage(THREE.DynamicDrawUsage));webGeo.setAttribute('color',new THREE.BufferAttribute(webColor,3).setUsage(THREE.DynamicDrawUsage));const webLines=new THREE.LineSegments(webGeo,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.7,blending:THREE.AdditiveBlending,depthWrite:false}));webLines.frustumCulled=false;webGroup.add(webLines);
const nodeGeo=new THREE.SphereGeometry(.045,8,6),nodeMat=new THREE.MeshBasicMaterial({color:0xd9ecc7}),anchorMat=new THREE.MeshBasicMaterial({color:0xe2ddb2});const nodeMeshes=new Map();const selectedRing=mesh(new THREE.TorusGeometry(.13,.013,6,28),new THREE.MeshBasicMaterial({color:0xe0f3ad}),0,0,0,webGroup);selectedRing.visible=false;
const previewGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);const previewLine=new THREE.Line(previewGeo,new THREE.LineDashedMaterial({color:0xe4f5b7,dashSize:.12,gapSize:.09,transparent:true,opacity:.7}));webGroup.add(previewLine);previewLine.visible=false;
const dewGeo=new THREE.SphereGeometry(.019,5,4),dewMat=new THREE.MeshBasicMaterial({color:0xf3f8db,transparent:true,opacity:.7});const dew=[];for(let i=0;i<100;i++){const m=mesh(dewGeo,dewMat,0,0,0,webGroup);dew.push({m,edge:Math.floor(sr()*physics.edges.length),t:sr()});}
function renderWeb(t){let offset=0;for(const e of physics.edges){const segments=8;for(let j=0;j<segments;j++){for(let k=0;k<2;k++){const u=(j+k)/segments;const sag=Math.sin(u*Math.PI);webPos[offset]=THREE.MathUtils.lerp(e.a.x,e.b.x,u);webPos[offset+1]=THREE.MathUtils.lerp(e.a.y,e.b.y,u)-sag*.035*e.rest;webPos[offset+2]=THREE.MathUtils.lerp(e.a.z,e.b.z,u)+sag*Math.sin(t*1.4+e.a.id)*.016*wind;const damaged=e.health<.45;webColor[offset]=damaged?.9:e.reinforced?.82:.65;webColor[offset+1]=damaged?.47:e.reinforced?1:.83;webColor[offset+2]=damaged?.3:e.reinforced?.52:.79;offset+=3;}}}webGeo.setDrawRange(0,offset/3);webGeo.attributes.position.needsUpdate=true;webGeo.attributes.color.needsUpdate=true;
for(const n of physics.nodes){let m=nodeMeshes.get(n.id);if(!m){m=mesh(nodeGeo,n.fixed?anchorMat:nodeMat,0,0,0,webGroup);nodeMeshes.set(n.id,m);}m.position.set(n.x,n.y,n.z);m.scale.setScalar(selected===n?1.9:n.fixed?1.15:1);}
if(selected){selectedRing.visible=true;selectedRing.position.set(selected.x,selected.y,selected.z);selectedRing.rotation.z=t*.5;}else selectedRing.visible=false;
for(const d of dew){const e=physics.edges[d.edge%physics.edges.length];d.m.visible=!!e;if(e){d.m.position.set(THREE.MathUtils.lerp(e.a.x,e.b.x,d.t),THREE.MathUtils.lerp(e.a.y,e.b.y,d.t)-Math.sin(d.t*Math.PI)*.035*e.rest,THREE.MathUtils.lerp(e.a.z,e.b.z,d.t));}}
}
// The resident orb-weaver, modelled from a velvet abdomen, glossy eyes and articulated legs.
const spider=new THREE.Group();scene.add(spider);spider.position.set(CX,CY,.22);const spiderBody=mat(0x272e26,{roughness:.45}),spiderGold=mat(0xc6a568,{metalness:.25,roughness:.6});const abdomen=mesh(new THREE.SphereGeometry(.19,16,12),spiderBody,0,.15,0,spider);abdomen.scale.set(.86,1.25,.8);mesh(new THREE.SphereGeometry(.115,12,10),spiderBody,0,-.08,.035,spider);const stripe=mesh(new THREE.SphereGeometry(.09,10,8),spiderGold,0,.19,.128,spider);stripe.scale.set(.56,1,.12);for(const s of [-1,1]){mesh(new THREE.SphereGeometry(.027,8,6),new THREE.MeshBasicMaterial({color:0xecf4bb}),s*.05,-.12,.13,spider);}const legs=[];for(let i=0;i<4;i++)for(const s of [-1,1]){const group=new THREE.Group();spider.add(group);const y=.08-i*.068;const knee=[s*(.29+Math.sin(i)*.07),y+(.19-i*.12),.09],foot=[s*(.4+Math.sin(i)*.09),y+(.29-i*.195),-.07];branch([s*.07,y,0],knee,.022,.015,spiderBody,group);branch(knee,foot,.016,.006,spiderBody,group);legs.push({group,i,s});}
let spiderTarget=null,harvesting=null;const insects=[],particles=[];
const insectTypes=[{name:'月光蛾',color:0xdfdbc0,wing:0xe3e1c8,reward:8,weight:1,speed:.6,escape:17},{name:'绿瓶蝇',color:0x75a98c,wing:0xc2ddd1,reward:12,weight:1.4,speed:1.05,escape:12},{name:'金龟子',color:0xb79748,wing:0xceaa65,reward:20,weight:3.1,speed:.43,escape:22}];
function createInsect(type,pos){const info=insectTypes[type],g=new THREE.Group();const body=mesh(new THREE.SphereGeometry(type===2?.115:.065,10,8),mat(info.color,{metalness:.3,roughness:.4}),0,0,0,g);body.scale.set(.72,type===2?1.25:1.55,1);mesh(new THREE.SphereGeometry(.045,8,6),mat(0x293b29),0,.1,0,g);const wings=[];for(const s of [-1,1]){const wing=mesh(new THREE.SphereGeometry(type===0?.19:.12,12,8),new THREE.MeshStandardMaterial({color:info.wing,transparent:true,opacity:type===2?.8:.65,side:THREE.DoubleSide,roughness:.5}),s*(type===0?.14:.1),.025,0,g);wing.scale.set(1,type===0?.65:.45,.065);wing.rotation.z=s*.45;wings.push(wing);if(type===0){const dot=mesh(new THREE.SphereGeometry(.035,8,6),mat(0x929877),s*.18,.045,.013,g);dot.scale.z=.1;}}g.position.copy(pos);scene.add(g);const bug={g,info,type,wings,trapped:false,trapTime:0,phase:rand(0,6.28),vx:rand(-.22,.22),vy:rand(-.17,.17),edge:null};insects.push(bug);return bug;}
function spawnInsect(){const type=Math.random()<.2?2:Math.random()<.45?1:0;const p=new THREE.Vector3(rand(-2.7,3.3),rand(1.5,7.1),-5);createInsect(type,p);}
// Peaceful ambient butterflies remain visible before the first hunt.
const ambient=[];for(let i=0;i<4;i++){const bug=createInsect(i%2,new THREE.Vector3([-3.6,3.6,2.9,-1.8][i],[5.2,6.2,2.1,7.6][i],1.4));bug.ambient=true;bug.base=bug.g.position.clone();ambient.push(bug);}
function puff(pos,color=0xdceeb3){for(let i=0;i<12;i++){const m=mesh(new THREE.SphereGeometry(.024,4,3),new THREE.MeshBasicMaterial({color,transparent:true}),pos.x,pos.y,pos.z);particles.push({m,v:new THREE.Vector3(rand(-.8,.8),rand(-.3,1),rand(-.4,.4)),life:1});}}
function removeBug(b){scene.remove(b.g);b.g.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});const i=insects.indexOf(b);if(i>=0)insects.splice(i,1);if(harvesting===b)harvesting=null;}
function capture(b,e){b.trapped=true;b.edge=e;b.trapTime=b.info.escape+state.levels.sticky*4;b.g.position.z=(e.a.z+e.b.z)/2+.06;b.anchorT=segmentDistance(b.g.position,e.a,e.b).t;physics.impact(e,b.info.weight/state.levels.silk);playTone(320,.07,'sine',.05);toast(`${b.info.name}落网了！切换「捕食」点击猎物`,2200);if(tool==='hunt'&&!harvesting)seekFood(b);}
function seekFood(b){if(!b.trapped)return;harvesting=b;spiderTarget=b.g.position.clone();toast(`正在靠近${b.info.name}…`,1200);}
function harvest(b){const reward=b.info.reward;state.energy+=reward;state.silk=Math.min(silkCap(),state.silk+reward*.75);state.caught++;nightCatches++;nightEnergy+=reward;const p=b.g.position.clone();puff(p);floatingReward(p,`+${reward} ✧`);playTone(650,.12,'sine',.08);setTimeout(()=>playTone(870,.15,'sine',.05),80);removeBug(b);updateUI();save();}
function floatingReward(pos,text){const p=pos.clone().project(camera);const el=document.createElement('div');el.className='float-reward';el.textContent=text;el.style.left=`${(p.x*.5+.5)*world.clientWidth}px`;el.style.top=`${(-p.y*.5+.5)*world.clientHeight}px`;$('floating').appendChild(el);setTimeout(()=>el.remove(),1800);}
function silkCap(){return 180+(state.levels.metabolism-1)*40;}
let toastTimer;function toast(msg,time=2600){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),time);}
function save(){try{const web={nodes:physics.nodes.map(n=>({x:n.ox,y:n.oy,z:n.oz,fixed:n.fixed})),edges:physics.edges.map(e=>({a:physics.nodes.indexOf(e.a),b:physics.nodes.indexOf(e.b),reinforced:e.reinforced,health:e.health}))};localStorage.setItem(SAVE,JSON.stringify({...state,web}));}catch{$('save-state').textContent='存储不可用';}}
function updateUI(){ $('silk').innerHTML=`${Math.floor(state.silk)}<small> / ${silkCap()}</small>`;$('energy').innerHTML=`${state.energy}<small> 萤光</small>`;$('season').textContent=`暮夏 · 第 ${state.night} 夜`;$('level').textContent=`Lv. ${String(1+Math.floor(state.caught/5)).padStart(2,'0')}`;$('total-caught').textContent=String(state.caught).padStart(2,'0');let done=0;for(const [id,count,max]of[['build',state.built,3],['catch',state.caught,3],['upgrade',state.upgraded,1]]){const el=$('quest-'+id);el.classList.toggle('done',count>=max);el.querySelector('b').textContent=`${Math.min(count,max)}/${max}`;if(count>=max)done++;}$('quest-counter').textContent=`${done} / 3`;if(done===3&&!state.questClaimed){state.questClaimed=true;state.energy+=30;state.silk=Math.min(silkCap(),state.silk+40);toast('挑战完成！获得 30 能量与 40 蛛丝',4000);puff(spider.position);save();updateUI();return;}if(state.questClaimed){$('quest-title').textContent='森林记住了你的名字';$('quest-description').textContent='挑战已完成。继续狩猎，成为林间的织网大师。';document.querySelector('.reward').innerHTML='<span>挑战已完成</span><b>✓ 奖励已领取</b>';}
for(const type of ['silk','sticky','metabolism']){const level=state.levels[type],cost=upgradeCost(type);$('upgrade-'+type).textContent=['','Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ'][level];$('cost-'+type).textContent=level>=5?'MAX':`✧ ${cost}`;document.querySelector(`[data-upgrade="${type}"]`).classList.toggle('affordable',state.energy>=cost&&level<5);}
const health=physics.edges.length?Math.round(physics.edges.reduce((s,e)=>s+Math.max(0,e.health),0)/physics.edges.length*100):0;$('health-bar').style.width=health+'%';$('health-text').textContent=health+'%';}
function upgradeCost(type){return({silk:20,sticky:25,metabolism:30}[type])*state.levels[type];}
for(const btn of document.querySelectorAll('.upgrade'))btn.addEventListener('click',()=>{const type=btn.dataset.upgrade;if(state.levels[type]>=5){toast('这项进化已达到最高等级');return;}const cost=upgradeCost(type);if(state.energy<cost){toast(`还需要 ${cost-state.energy} 能量，捕食飞虫即可获得`);return;}state.energy-=cost;state.levels[type]++;state.upgraded++;playTone(540,.2,'triangle',.1);toast('进化完成！你变得更强大了');updateUI();save();});
function setTool(next){tool=next;selected=null;previewLine.visible=false;for(const b of document.querySelectorAll('[data-tool]'))b.classList.toggle('active',b.dataset.tool===tool);$('tool-hint').innerHTML={weave:'点击两个节点连接蛛丝，或点击空处延伸蛛网 <span>ESC 取消连线</span>',reinforce:'点击蛛丝，消耗 8 蛛丝加固并修复 <span>承重提升 2.5 倍</span>',cut:'点击蛛丝回收部分材料 <span>注意保留主承重线</span>',hunt:'点击落网的飞虫，蜘蛛会前往捕食 <span>挣脱前收获更多能量</span>'}[tool];if(tool==='hunt'){const b=insects.find(b=>b.trapped);if(b)seekFood(b);}}
for(const b of document.querySelectorAll('[data-tool]'))b.addEventListener('click',()=>setTool(b.dataset.tool));
function startHunt(){if(phase==='hunt')return;phase='hunt';remaining=60+Math.min(30,(state.night-1)*5);spawnClock=1.8;nightCatches=0;nightEnergy=0;storm=state.night%3===0;wind=storm?3.8:1.2+state.night*.15;$('phase-label').textContent=storm?'风雨狩猎':'狩猎进行中';$('start-hunt').disabled=true;$('start-hunt').innerHTML='狩猎中 <span>◌</span>';$('weather-name').innerHTML=`${storm?'风雨欲来':'晴朗的暮色'}<small id="wind-label">${storm?'强风':'微风'} · ${wind.toFixed(1)} m/s</small>`;$('weather-icon').textContent=storm?'☂':'☾';setTool('hunt');toast(storm?'暴风即将来临，加固蛛网抵御冲击！':'狩猎开始。等待飞虫触网，再点击捕食。',3500);spawnInsect();}
$('start-hunt').addEventListener('click',startHunt);
function endHunt(){phase='build';state.night++;wind=1.2;storm=false;for(const b of [...insects])if(!b.ambient)removeBug(b);harvesting=null;spiderTarget=null;state.silk=Math.min(silkCap(),state.silk+30);$('phase-label').textContent='自由建造';$('phase-time').textContent='等待狩猎';$('start-hunt').disabled=false;$('start-hunt').innerHTML='开始狩猎 <span>↗</span>';$('weather-name').innerHTML='晴朗的暮色<small id="wind-label">微风 · 1.2 m/s</small>';$('weather-icon').textContent='☾';showModal('又一夜，悄然过去。',`<p>晨露为你补充了 30 蛛丝。修补蛛网，准备迎接下一场夜猎。</p><div class="summary-stats"><div><b>${nightCatches}</b><span>本夜捕食</span></div><div><b>${nightEnergy}</b><span>收获能量</span></div><div><b>${state.night}</b><span>即将到来的夜晚</span></div></div><p>${nightCatches===0?'试试在蛛网中部添加交叉细丝，提高拦截率。捕食模式下点击落网飞虫，蜘蛛便会出发。':'更细密的网能拦截更多访客，但金龟子需要更强韧的蛛丝。'}</p>`);updateUI();save();}
function showModal(title,body){modalPaused=true;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal').classList.remove('hidden');$('modal-ok').focus();}
function hideModal(){modalPaused=false;$('modal').classList.add('hidden');}
$('modal-ok').addEventListener('click',hideModal);$('close-modal').addEventListener('click',hideModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))hideModal();});
$('help').addEventListener('click',()=>showModal('做一只聪明的小蜘蛛',`<p>你在一片暮色森林中拥有一张小网。织出更多连接，捕食飞虫，让自己的领地慢慢成长。</p><div class="help-row"><b>1 · 织网</b><span>点击一个亮色节点，再点击另一个节点或空白位置。按距离消耗蛛丝；蛛丝会随时间恢复。</span></div><div class="help-row"><b>2 · 加固</b><span>点击蛛丝消耗 8 丝，修复磨损并提升承重。金龟子与暴风会损伤蛛丝。</span></div><div class="help-row"><b>3 · 回收</b><span>点击多余蛛丝返还部分材料。不要拆掉太多支撑线。</span></div><div class="help-row"><b>4 · 捕食</b><span>开始狩猎后飞虫从林中穿过蛛网。点击落网猎物，蜘蛛靠近后自动捕食；倒计时结束猎物会逃脱。</span></div><div class="help-row"><b>视角</b><span>拖动空白区域旋转，滚轮缩放，⌖ 归位。空格暂停；Esc 取消连线或关闭窗口。手机支持单指操作。</span></div><p>每 3 夜遭遇一次强风。挑战奖励、升级与蛛网会自动存到本机。</p><button class="reset-btn" id="reset-game">重新开始一段旅程</button>`));
$('modal-body').addEventListener('click',e=>{if(e.target.id==='reset-game'){showModal('重新开始？','<p>这将清除当前设备保存的蛛网、能量和进化进度。</p><button class="reset-btn" id="confirm-reset">确认清除进度并重新开始</button>');}else if(e.target.id==='confirm-reset'){localStorage.removeItem(SAVE);location.reload();}});
$('guide').addEventListener('click',()=>showModal('林地访客手记',`<div class="help-row"><b>✦ 月光蛾</b><span>被暮光吸引的温和访客。重量轻，普通蛛丝即可捕获。奖励 8 能量。</span></div><div class="help-row"><b>❖ 绿瓶蝇</b><span>飞行快速，挣扎频繁。优先捕食，或升级黏性腺体。奖励 12 能量。</span></div><div class="help-row"><b>⬢ 金龟子</b><span>沉重的甲壳会损伤蛛丝。加固关键连接，提升韧性后再迎接它。奖励 20 能量。</span></div><p>飞虫触网后会振动并闪光。蛛丝发橙意味着已经受损；及时修补可避免猎物随断丝一起逃走。</p>`));
function togglePause(){paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').title=paused?'继续游戏':'暂停游戏';$('pause').setAttribute('aria-label',paused?'继续游戏':'暂停游戏');toast(paused?'林间时光已暂停':'林间时光继续流动');}
$('pause').addEventListener('click',togglePause);$('camera-reset').addEventListener('click',()=>{orbit={theta:.075,phi:1.39,distance:16.4};updateCamera();toast('视角已归位',1200);});
let audioCtx=null,soundEnabled=false,ambience=null;
function playTone(freq,duration,type='sine',volume=.05){if(!soundEnabled||!audioCtx)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.8,audioCtx.currentTime+duration);gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration);}
$('sound').addEventListener('click',()=>{soundEnabled=!soundEnabled;if(soundEnabled){audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();if(!ambience){const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.04-.02)/1.02;data[i]=last;}const source=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),gain=audioCtx.createGain();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=500;gain.gain.value=.2;source.connect(filter).connect(gain).connect(audioCtx.destination);source.start();ambience=gain;}ambience.gain.value=.2;playTone(880,.1);toast('森林环境音已开启');}else{if(ambience)ambience.gain.value=0;toast('环境音已关闭');}$('sound').style.color=soundEnabled?'#d1e7a0':'';$('sound').setAttribute('aria-pressed',soundEnabled);});
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.code==='Escape'){selected=null;previewLine.visible=false;hideModal();}if(!$('modal').classList.contains('hidden'))return;if('1234'.includes(e.key))setTool(['weave','reinforce','cut','hunt'][+e.key-1]);if(e.code==='Space'){e.preventDefault();togglePause();}});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0),pointerWorld=new THREE.Vector3();
function pointFromEvent(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(plane,pointerWorld);}
function nearestNode(p){let best=null,d=.24;for(const n of physics.nodes){const dd=Math.hypot(n.x-p.x,n.y-p.y);if(dd<d){d=dd;best=n;}}return best;}
function nearestEdge(p){let best=null,d=.18;for(const e of physics.edges){const dd=segmentDistance({...p,z:0},{...e.a,z:0},{...e.b,z:0}).distance;if(dd<d){d=dd;best=e;}}return best;}
function handleClick(e){if(paused||modalPaused)return;const p=pointFromEvent(e);if(!p)return;if(tool==='hunt'){let b=null,d=.6;for(const bug of insects){if(!bug.trapped)continue;const dist=Math.hypot(bug.g.position.x-p.x,bug.g.position.y-p.y);if(dist<d){b=bug;d=dist;}}if(b)seekFood(b);else{spiderTarget=p.clone();harvesting=null;toast('点击落网飞虫即可捕食',1400);}return;}
if(tool==='weave'){const n=nearestNode(p);if(!selected){if(n){selected=n;playTone(440,.08);toast('选择另一节点，或点击空白处延伸',1700);}else toast('先点击一个蛛网节点，再向外延伸',1800);return;}if(n===selected){selected=null;previewLine.visible=false;return;}if(physics.nodes.length>=150&&!n){toast('节点数量已达上限，请连接现有节点');return;}if(physics.edges.length>=300){toast('蛛丝数量已达上限，请回收多余蛛丝');return;}if(Math.abs(p.x)>5.2||p.y<.65||p.y>8.6){toast('请在两棵树之间编织');return;}const destination=n||p,dist=Math.hypot(selected.x-destination.x,selected.y-destination.y);if(dist<.2){toast('两个节点距离太近');return;}const cost=Math.ceil(dist*3+2);if(state.silk<cost){toast(`需要 ${cost} 蛛丝，稍作等待即可恢复`);return;}if(n&&physics.edges.some(e=>(e.a===selected&&e.b===n)||(e.b===selected&&e.a===n))){toast('这两个节点已经连接了');return;}const to=n||physics.addNode(p.x,p.y,0,Math.abs(p.x)>4.3);const edge=physics.connect(selected,to);if(edge){state.silk-=cost;state.built++;spiderTarget=new THREE.Vector3(to.x,to.y,.16);playTone(600,.13);toast(`织下一根新蛛丝 · −${cost} 丝`,1500);selected=to;updateUI();save();}return;}
const edge=nearestEdge(p);if(!edge){toast('点击一根蛛丝进行操作',1400);return;}if(tool==='reinforce'){if(edge.reinforced&&edge.health>.98){toast('这根蛛丝已经很牢固了');return;}if(state.silk<8){toast('加固需要 8 蛛丝');return;}state.silk-=8;edge.reinforced=true;edge.health=1;playTone(380,.15,'triangle');toast('蛛丝已加固并完全修复 · −8 丝');}else if(tool==='cut'){state.silk=Math.min(silkCap(),state.silk+Math.ceil(edge.rest*1.5));for(const b of insects)if(b.edge===edge){b.trapped=false;b.edge=null;}physics.remove(edge);toast('已回收蛛丝');playTone(200,.08,'triangle');}updateUI();save();}
let down=null,dragging=false;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,theta:orbit.theta,phi:orbit.phi};dragging=false;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{const p=pointFromEvent(e);if(down){const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(dx,dy)>6)dragging=true;if(dragging){orbit.theta=THREE.MathUtils.clamp(down.theta-dx*.003,-.6,.6);orbit.phi=THREE.MathUtils.clamp(down.phi-dy*.002,1.04,1.75);updateCamera();}}if(selected&&p&&!dragging){previewLine.visible=true;const a=previewGeo.attributes.position;a.setXYZ(0,selected.x,selected.y,selected.z);a.setXYZ(1,p.x,p.y,.01);a.needsUpdate=true;previewLine.computeLineDistances();}canvas.style.cursor=dragging?'grabbing':p&&nearestNode(p)?'pointer':'crosshair';});canvas.addEventListener('pointerup',e=>{if(down&&!dragging)handleClick(e);down=null;dragging=false;});canvas.addEventListener('pointercancel',()=>{down=null;dragging=false;});canvas.addEventListener('wheel',e=>{e.preventDefault();orbit.distance=THREE.MathUtils.clamp(orbit.distance+e.deltaY*.012,10,23);updateCamera();},{passive:false});
function resize(){const {width,height}=world.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(world);resize();
let last=performance.now(),uiClock=0,saveClock=0;
function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!modalPaused){elapsed+=dt;physics.step(dt,elapsed,wind,state.levels.silk);state.silk=Math.min(silkCap(),state.silk+dt*(.6+state.levels.metabolism*.25));if(phase==='hunt'){remaining-=dt;spawnClock-=dt;$('phase-time').textContent=`${Math.ceil(Math.max(0,remaining))}s`;if(spawnClock<=0){spawnInsect();spawnClock=Math.max(.9,2.5-state.night*.15)+Math.random();}if(storm){for(const e of physics.edges)e.health-=dt*.003/(e.reinforced?3:1)/state.levels.silk;}if(remaining<=0)endHunt();}
for(const b of [...insects]){for(let i=0;i<b.wings.length;i++){const w=b.wings[i];w.rotation.y=Math.sin(elapsed*(b.trapped?20:30)+b.phase)*(b.trapped?.2:.75)*(i?1:-1);}if(b.ambient){b.g.position.x=b.base.x+Math.sin(elapsed*.36+b.phase)*.5;b.g.position.y=b.base.y+Math.cos(elapsed*.5+b.phase)*.3;b.g.rotation.z=Math.sin(elapsed*.6+b.phase)*.2;continue;}if(b.trapped){if(!physics.edges.includes(b.edge)){b.trapped=false;b.edge=null;continue;}b.trapTime-=dt;const edge=b.edge,u=b.anchorT;b.g.position.set(THREE.MathUtils.lerp(edge.a.x,edge.b.x,u)+Math.sin(elapsed*16)*.012,THREE.MathUtils.lerp(edge.a.y,edge.b.y,u),THREE.MathUtils.lerp(edge.a.z,edge.b.z,u)+.06);b.g.rotation.z=Math.sin(elapsed*11)*.07;if(Math.random()<dt*.7)physics.impact(edge,b.info.weight*.15/state.levels.silk);const danger=b.trapTime<5;b.g.scale.setScalar(danger?1+Math.sin(elapsed*10)*.12:1);if(b.trapTime<=0){toast(`${b.info.name}挣脱了，再快一点！`,1700);b.trapped=false;b.g.position.z=.45;b.edge=null;if(harvesting===b)harvesting=null;}continue;}
b.g.position.z+=dt*b.info.speed*1.45;b.g.position.x+=dt*(b.vx+Math.sin(elapsed*2+b.phase)*.12);b.g.position.y+=dt*(b.vy+Math.cos(elapsed*1.7+b.phase)*.1);if(Math.abs(b.g.position.z)<.25){let hit=null,best=.18+(state.levels.sticky-1)*.023;for(const e of physics.edges){const dist=segmentDistance(b.g.position,e.a,e.b).distance;if(dist<best){best=dist;hit=e;}}if(hit)capture(b,hit);}if(b.g.position.z>5)removeBug(b);}
if(harvesting&&!insects.includes(harvesting))harvesting=null;if(harvesting)spiderTarget=harvesting.g.position.clone();if(spiderTarget){const goal=spiderTarget.clone();goal.z+=.18;const dir=goal.sub(spider.position),distance=dir.length();if(distance>.12){spider.position.addScaledVector(dir.normalize(),Math.min(distance,dt*(1.4+state.levels.metabolism*.35)));spider.rotation.z=THREE.MathUtils.lerp(spider.rotation.z,Math.atan2(-dir.x,dir.y)+Math.PI,.12);for(const l of legs)l.group.rotation.z=Math.sin(elapsed*18+l.i*1.6)*.15*l.s;}else{if(harvesting?.trapped)harvest(harvesting);spiderTarget=null;}}else{for(const l of legs)l.group.rotation.z=Math.sin(elapsed*1.4+l.i)*.025;spider.position.z=.2+Math.sin(elapsed)*.025;}
for(const f of fireflies){f.s.position.x=f.base.x+Math.sin(elapsed*.3+f.phase)*.5;f.s.position.y=f.base.y+Math.cos(elapsed*.4+f.phase)*.25;f.s.material.opacity=.45+Math.sin(elapsed*1.1+f.phase)*.35;}dust.rotation.y=elapsed*.005;for(const p of [...particles]){p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.m.material.opacity=p.life;if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();particles.splice(particles.indexOf(p),1);}}
uiClock+=dt;saveClock+=dt;if(uiClock>.25){updateUI();uiClock=0;}if(saveClock>8){save();saveClock=0;}}
renderWeb(elapsed);renderer.render(scene,camera);}
updateUI();requestAnimationFrame(tick);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();last=performance.now();});
// Read-only runtime diagnostics aid local verification without changing game progress.
window.__silkbound={snapshot:()=>({phase,paused,night:state.night,silk:state.silk,energy:state.energy,nodes:physics.nodes.length,edges:physics.edges.length,bugs:insects.length,trapped:insects.filter(b=>b.trapped).length,renderer:renderer.info.render}),projectNode:index=>{const n=physics.nodes[index];if(!n)return null;const p=new THREE.Vector3(n.x,n.y,n.z).project(camera),r=canvas.getBoundingClientRect();return{x:r.left+(p.x*.5+.5)*r.width,y:r.top+(-p.y*.5+.5)*r.height};}};
