import * as THREE from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { frameComplete, scores, rollLabel } from './scoring.js';
const $=id=>document.getElementById(id);
const container=$('scene');
const scene=new THREE.Scene();scene.background=new THREE.Color('#d5e7e8');scene.fog=new THREE.Fog('#d5e7e8',48,130);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(39,1,.1,200);
scene.add(new THREE.HemisphereLight('#f0fdff','#829a99',2.6));
const sun=new THREE.DirectionalLight('#fff2d2',3.4);sun.position.set(-22,35,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-38,right:38,top:35,bottom:-35,near:1,far:100});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;scene.add(sun);
const mats={snow:new THREE.MeshStandardMaterial({color:'#f5fcf7',roughness:.94}),ice:new THREE.MeshStandardMaterial({color:'#91cbd0',roughness:.22,metalness:.12}),wood:new THREE.MeshStandardMaterial({color:'#966d4a',roughness:.85}),darkwood:new THREE.MeshStandardMaterial({color:'#604f3f',roughness:.85}),green:new THREE.MeshStandardMaterial({color:'#386758',roughness:1}),orange:new THREE.MeshStandardMaterial({color:'#ee7340',roughness:.8}),dark:new THREE.MeshStandardMaterial({color:'#334e48',roughness:.85}),black:new THREE.MeshStandardMaterial({color:'#293a3e'}),red:new THREE.MeshStandardMaterial({color:'#ce503d'}),pin:new THREE.MeshStandardMaterial({color:'#fff9e6',roughness:.35}),gold:new THREE.MeshStandardMaterial({color:'#f8c36a',emissive:'#f8bb49',emissiveIntensity:1})};
function mesh(geo,mat,x,y,z,parent=scene){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
const sphereGeo=new THREE.SphereGeometry(1,20,14);
function sphere(x,y,z,s,mat,parent){const m=mesh(sphereGeo,mat,x,y,z,parent);m.scale.setScalar(s);return m}
function box(x,y,z,w,h,d,mat,parent){return mesh(new THREE.BoxGeometry(w,h,d),mat,x,y,z,parent)}
function cylinder(x,y,z,rt,rb,h,mat,parent,segments=12){return mesh(new THREE.CylinderGeometry(rt,rb,h,segments),mat,x,y,z,parent)}
function rod(a,b,r,mat,parent=scene){const delta=new THREE.Vector3().subVectors(b,a),m=cylinder(0,0,0,r,r,delta.length(),mat,parent,8);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());return m}
const ground=box(0,-.65,0,180,1,180,mats.snow);
// An elevated, frosted lane with wooden gutters and etched guide marks.
box(0,-.13,-3,9.9,.55,34,mats.snow);box(0,.16,-3,8.2,.12,33,mats.ice);
const lineMat=new THREE.MeshStandardMaterial({color:'#d4efeb',transparent:true,opacity:.48});
for(let x=-3;x<=3;x++)box(x,.226,-3,.025,.006,32,lineMat);
for(const x of [-4.5,4.5]){box(x,.14,-3,.7,.25,33,mats.darkwood);box(x,.29,-3,.42,.18,33,mats.snow);for(let z=-18;z<=13;z+=4)box(x,.03,z,.65,.5,.3,mats.wood)}
box(0,.23,8.5,8.2,.02,.14,mats.dark);for(let i=-3;i<=3;i++){const m=mesh(new THREE.ConeGeometry(.12,.4,3),mats.dark,i*.8,.25,3);m.rotation.x=-Math.PI/2;}
for(let i=0;i<5;i++)box(0,.23,11+i*.55,7.8,.012,.025,lineMat);
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g);cylinder(0,.7,0,.18,.23,1.5,mats.wood,g);for(let i=0;i<3;i++){let y=1.6+i*.95,r=1.45-i*.3;mesh(new THREE.ConeGeometry(r,2.25-i*.23,7),mats.green,0,y,0,g);mesh(new THREE.ConeGeometry(r*.97,1.82-i*.2,7),mats.snow,0,y+.3,0,g)}return g}
let seed=37;function rand(){seed=(seed*16807)%2147483647;return (seed-1)/2147483646}
for(let i=0;i<55;i++){let x=(rand()-.5)*90,z=rand()*65-48;if(Math.abs(x)<9&&z>-22) x+=x<0?-12:12;if(x<-11&&x>-23&&z<-4&&z>-17)continue;tree(x,z,.6+rand()*1.1)}
const mountainMat=new THREE.MeshStandardMaterial({color:'#9fbcbc',flatShading:true,roughness:1});
for(let i=0;i<10;i++){let x=-70+i*15,z=-65-rand()*15,h=14+rand()*17,r=12+rand()*9;mesh(new THREE.ConeGeometry(r,h,5),mountainMat,x,h/2-1,z);mesh(new THREE.ConeGeometry(r*.56,h*.56,5),mats.snow,x,h*.73-1,z)}
for(let i=0;i<26;i++){let x=(rand()-.5)*70,z=rand()*55-28;if(Math.abs(x)<7)continue;const rock=sphere(x,-.2,z,1+rand()*2,mats.snow);rock.scale.y*=.35;}
function cabin(){const g=new THREE.Group();g.position.set(-17,0,-12);g.rotation.y=.3;scene.add(g);box(0,1.6,0,6,3.2,4.8,mats.wood,g);for(let y=.3;y<3.2;y+=.4)box(0,y,2.43,6,.08,.08,mats.darkwood,g);const roof=mesh(new THREE.ConeGeometry(4.9,2.7,4),mats.darkwood,0,4.1,0,g);roof.rotation.y=Math.PI/4;roof.scale.z=.88;const roofSnow=mesh(new THREE.ConeGeometry(5,2.5,4),mats.snow,0,4.3,0,g);roofSnow.rotation.y=Math.PI/4;roofSnow.scale.z=.88;box(-1.5,1.7,2.48,1.25,1.1,.12,mats.gold,g);box(-1.5,1.7,2.56,.07,1.2,.06,mats.darkwood,g);box(-1.5,1.7,2.56,1.3,.07,.06,mats.darkwood,g);box(1,1.15,2.48,1.05,2.3,.13,mats.darkwood,g);sphere(1.35,1.1,2.58,.07,mats.gold,g);box(1.5,4.8,-.5,.65,2,.75,mats.darkwood,g);box(0,.1,3.4,7,.3,1.8,mats.wood,g);return g}cabin();
function sign(text,x,y,z,w=4){const c=document.createElement('canvas');c.width=512;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle='#36564b';ctx.fillRect(0,0,512,160);ctx.strokeStyle='#8aab92';ctx.lineWidth=3;ctx.strokeRect(12,12,488,136);ctx.fillStyle='#fff8e5';ctx.font='bold 44px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,95);const mat=new THREE.MeshStandardMaterial({map:new THREE.CanvasTexture(c),roughness:1});box(x,y,z,w,w*.31,.18,mats.wood);mesh(new THREE.PlaneGeometry(w,w*.31),mat,x,y,z+.1);for(const dx of [-w*.35,w*.35])box(x+dx,y/2,z,.13,y,.13,mats.wood)}
sign('PINE VALLEY',0,3.4,-21,5.1);sign('HOT COCOA ↗',-10,1.9,-8,2.7);
// Festoon lights at the far end of the lane.
for(const x of [-6.2,6.2]){cylinder(x,2.8,-18,.1,.14,5.6,mats.wood);sphere(x,5.6,-18,.2,mats.snow)}
const points=[];for(let i=0;i<=20;i++){const t=i/20,x=-6.2+t*12.4,y=5.5-Math.sin(t*Math.PI)*1.15;points.push(new THREE.Vector3(x,y,-18));if(i%2===1)sphere(x,y-.14,-18,.095,mats.gold)}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#53635d'})));
// Batch the static resort by material to keep draw calls low on mobile GPUs.
scene.updateMatrixWorld(true);
const staticBatches=new Map(),staticMeshes=[];
scene.traverse(o=>{if(o.isMesh){const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(o.matrixWorld);if(!staticBatches.has(o.material))staticBatches.set(o.material,[]);staticBatches.get(o.material).push(geo);staticMeshes.push(o)}});
staticMeshes.forEach(o=>o.removeFromParent());
for(const [mat,geometries] of staticBatches){const merged=mergeGeometries(geometries);const m=new THREE.Mesh(merged,mat);m.castShadow=true;m.receiveShadow=true;scene.add(m);geometries.forEach(g=>g.dispose())}
// The club's very enthusiastic resident snowman.
const snowman=new THREE.Group();snowman.position.set(-3.1,.24,11.6);snowman.rotation.y=-.08;scene.add(snowman);
sphere(0,1.02,0,1.04,mats.snow,snowman);sphere(0,2.28,0,.78,mats.snow,snowman);sphere(0,3.35,0,.62,mats.snow,snowman);
for(let i=0;i<3;i++)sphere(0,1.3+i*.5,.8-i*.06,.075,mats.black,snowman);
for(const x of [-.23,.23])sphere(x,3.47,.54,.068,mats.black,snowman);
const nose=mesh(new THREE.ConeGeometry(.12,.57,10),mats.orange,0,3.29,.82,snowman);nose.rotation.x=Math.PI/2;
for(let i=0;i<5;i++){let a=(i-2)*.27;sphere(Math.sin(a)*.3,3.18-Math.cos(a)*.09,.54,.029,mats.black,snowman)}
cylinder(0,3.87,0,.73,.73,.1,mats.dark,snowman);cylinder(0,4.15,0,.43,.48,.54,mats.dark,snowman);cylinder(0,3.98,0,.49,.49,.13,mats.orange,snowman);
const scarf=cylinder(0,2.85,0,.59,.66,.2,mats.orange,snowman);box(.43,2.51,.58,.3,.65,.12,mats.orange,snowman);
const arm=new THREE.Group();arm.position.set(.65,2.5,0);snowman.add(arm);rod(new THREE.Vector3(0,0,0),new THREE.Vector3(.95,.4,.15),.065,mats.wood,arm);rod(new THREE.Vector3(.8,.35,.13),new THREE.Vector3(.88,.67,.1),.045,mats.wood,arm);sphere(1.1,.5,.15,.3,mats.snow,arm);
rod(new THREE.Vector3(-.6,2.55,0),new THREE.Vector3(-1.35,2.8,.05),.065,mats.wood,snowman);rod(new THREE.Vector3(-1.1,2.7,.05),new THREE.Vector3(-1.4,3.02,.05),.04,mats.wood,snowman);
sphere(-.48,.15,.45,.4,mats.snow,snowman).scale.y=.45;sphere(.48,.15,.45,.4,mats.snow,snowman).scale.y=.45;
// Pins are compound meshes and react as rigid circles on the lane.
const pins=[];
const profile=[[0,.3],[.09,.36],[.4,.39],[.65,.31],[.9,.17],[1.14,.13],[1.27,.22],[1.48,.22],[1.58,.12],[1.6,0]].map(p=>new THREE.Vector2(p[1],p[0]));
const pinGeo=new THREE.LatheGeometry(profile,18);
for(let row=0,index=0;row<4;row++)for(let col=0;col<=row;col++,index++){const x=(col-row/2)*1.04,z=-11.5-row*1.03;const g=new THREE.Group();g.position.set(x,.25,z);scene.add(g);mesh(pinGeo,mats.pin,0,0,0,g);cylinder(0,1.09,0,.15,.15,.1,mats.red,g);cylinder(0,1.22,0,.16,.14,.06,mats.red,g);pins.push({g,x,z,homeX:x,homeZ:z,vx:0,vz:0,down:false,active:true,tilt:0,rot:0});const dot=document.createElement('span');dot.className='pin-dot';dot.style.left=`${35+(col-row/2)*19}px`;dot.style.top=`${(3-row)*16}px`;$('pinDiagram').appendChild(dot)}
const ball=sphere(0,.86,9.4,.62,mats.snow);ball.castShadow=true;const seamMat=new THREE.MeshStandardMaterial({color:'#d4e6de',roughness:1});for(let i=0;i<9;i++){const a=i*2.4,m=sphere(Math.cos(a)*.58,Math.sin(a)*.48,.17,.065,seamMat,ball);m.scale.y=.4}
const aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:'#f6faf0',dashSize:.35,gapSize:.24,transparent:true,opacity:.9}));scene.add(aimLine);
const aimRing=mesh(new THREE.RingGeometry(.69,.72,40),new THREE.MeshBasicMaterial({color:'#f5faf0',side:THREE.DoubleSide,transparent:true,opacity:.7}),0,.25,9.4);aimRing.rotation.x=-Math.PI/2;
const obstacles=[];for(const [x,z] of [[-1.8,-1.5],[1.7,-6.1]]){const g=mesh(new THREE.OctahedronGeometry(.78),new THREE.MeshStandardMaterial({color:'#6aa9b5',metalness:.2,roughness:.17,transparent:true,opacity:.85}),x,.8,z);g.scale.y=1.5;g.visible=false;obstacles.push(g)}
const snowCount=550,snowPositions=new Float32Array(snowCount*3);for(let i=0;i<snowCount;i++){snowPositions[i*3]=(rand()-.5)*80;snowPositions[i*3+1]=rand()*30;snowPositions[i*3+2]=(rand()-.5)*65}
const snowGeo=new THREE.BufferGeometry();snowGeo.setAttribute('position',new THREE.BufferAttribute(snowPositions,3));const snowfall=new THREE.Points(snowGeo,new THREE.PointsMaterial({color:'#ffffff',size:.09,transparent:true,opacity:.65,depthWrite:false}));scene.add(snowfall);
const particles=[];function burst(x,z,count=16){for(let i=0;i<count;i++){const m=sphere(x,.5,z,.04+Math.random()*.07,mats.snow);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*6,2+Math.random()*4,(Math.random()-.5)*6),life:1})}}
let frames=Array.from({length:10},()=>[]),frameIndex=0,mode='classic',aim=0,spin=0,wind=0,state='ready',charge=0,chargeTime=0,paused=false,view=0,elapsed=0,flightTime=0,settleTime=0,ballVX=0,ballVZ=0,toastTime=0,best=0,sound=false,audioCtx;
try{best=Number(localStorage.getItem('snowball-best')||0)}catch{}$('bestScore').textContent=String(best).padStart(3,'0');
function tone(freq,duration=.15,type='sine',volume=.04){if(!sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.6,audioCtx.currentTime+duration);gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration)}catch{}}
function toast(title,sub,detail){$('toastTitle').textContent=title;$('toastSmall').textContent=sub;$('toastDetail').textContent=detail;$('toast').classList.add('visible');toastTime=2.5}
function resetPins(){pins.forEach(p=>{p.x=p.homeX;p.z=p.homeZ;p.vx=p.vz=p.tilt=p.rot=0;p.down=false;p.active=true;p.g.visible=true;p.g.position.set(p.x,.25,p.z);p.g.rotation.set(0,0,0)});updatePinDots()}
function updatePinDots(){[...$('pinDiagram').children].forEach((dot,i)=>dot.classList.toggle('down',pins[i].down||!pins[i].active))}
function updateScore(){const totals=scores(frames);$('frames').innerHTML=frames.map((f,i)=>`<div class="frame ${i===frameIndex?'current':''}"><span class="frame-number">${String(i+1).padStart(2,'0')}</span><span class="frame-rolls">${rollLabel(f,i)}</span><span class="frame-score">${totals[i]??'·'}</span></div>`).join('');let total=totals.filter(n=>n!==null).at(-1)??0;$('totalScore').textContent=total;$('frameNo').textContent=String(Math.min(frameIndex+1,10)).padStart(2,'0');$('rollNo').textContent=['第一球','第二球','奖励球'][frames[Math.min(frameIndex,9)].length]||'本场结束';return total}
function setupBall(){ball.visible=true;ball.position.set(0,.86,9.4);ball.rotation.set(0,0,0);ball.scale.setScalar(.62);state='ready';charge=0;wind=mode==='wind'?(Math.random()-.5)*3:0;$('windCard').innerHTML=`${wind<0?'←':'→'} <span>风速 ${Math.abs(wind).toFixed(1)} m/s</span>`;$('locationWeather').textContent=mode==='wind'?`PINE VALLEY · −12°C · ${wind<0?'向左':'向右'}侧风`:'PINE VALLEY · −4°C · 微风';$('launchBtn').disabled=false;$('launchLabel').textContent='按住蓄力，松开发射';$('powerLabel').textContent='长按按钮 / SPACE';$('powerFill').style.width='0';$('readyBadge').innerHTML='<span></span>准备就绪';aimLine.visible=aimRing.visible=true;updateAim();updateScore()}
function resetGame(){frames=Array.from({length:10},()=>[]);frameIndex=0;paused=false;$('pauseOverlay').classList.add('hidden');$('pauseBtn').textContent='Ⅱ';$('toast').classList.remove('visible');$('resultDialog').close();resetPins();setupBall();updateScore()}
function updateAim(){const pts=[];const angle=THREE.MathUtils.degToRad(aim);for(let i=0;i<=40;i++){const z=9.4-i*.38,t=i*.38/18;pts.push(new THREE.Vector3(Math.tan(angle)*(9.4-z)+spin*t*t*.9+wind*t*t*.3,.27,z))}aimLine.geometry.dispose();aimLine.geometry=new THREE.BufferGeometry().setFromPoints(pts);aimLine.computeLineDistances();$('aimValue').textContent=`${aim>0?'+':''}${Math.round(aim)}°`}
function startCharge(){if(state!=='ready'||paused||$('helpDialog').open||$('resultDialog').open)return;state='charging';chargeTime=0;charge=.08;tone(220,.06);$('launchLabel').textContent='松开，漂亮出手！';$('readyBadge').innerHTML='<span></span>蓄力中'}
function release(){if(state!=='charging')return;if(paused){state='ready';return}const angle=THREE.MathUtils.degToRad(aim),speed=11+charge*17;ballVX=Math.sin(angle)*speed;ballVZ=-Math.cos(angle)*speed;flightTime=settleTime=0;state='rolling';$('launchBtn').disabled=true;$('launchLabel').textContent='雪球正在出发…';$('readyBadge').innerHTML='<span></span>好球在路上';aimLine.visible=aimRing.visible=false;tone(170,.3,'triangle');arm.rotation.z=-.7}
function knockPin(p,vx,vz){if(!p.active)return;if(!p.down){p.down=true;p.rot=Math.atan2(vx,vz);p.vx+=vx*.7;p.vz+=vz*.7;tone(330+Math.random()*300,.11,'triangle',.022);burst(p.x,p.z,7);updatePinDots()}else{p.vx+=vx*.15;p.vz+=vz*.15}}
function finishRoll(){const knocked=pins.filter(p=>p.active&&p.down).length;const frame=frames[frameIndex];frame.push(knocked);const strike=knocked===10,spare=frame.length===2&&frame[0]!==10&&frame[0]+knocked===10;toast(strike?'一击全中！':spare?'漂亮补中！':knocked?`击倒 ${knocked} 瓶`:'差一点点！',strike?'S T R I K E':spare?'S P A R E':knocked?'NICE ROLL':'KEEP ON ROLLING',strike?'雪人都忍不住为你欢呼。':spare?'每一瓶，都值得认真对待。':knocked>=7?'手感来了，继续保持。':'调整角度，下一球更精彩。');if(strike||spare){tone(660,.2);setTimeout(()=>tone(880,.3),130);burst(0,-12,50)}
let fresh=false;if(frameIndex<9){if(frameComplete(frame,frameIndex)){frameIndex++;fresh=true}}else if(frameComplete(frame,9)){state='finished';const total=updateScore();if(total>best){best=total;try{localStorage.setItem('snowball-best',String(best))}catch{}$('bestScore').textContent=String(best).padStart(3,'0')}$('resultScore').textContent=total;$('resultTitle').textContent=total>=200?'雪谷传奇，就是你。':total>=100?'今天的手感，真不错。':'漂亮收官！';$('resultText').textContent=`完成十局 · ${frames.flat().filter(n=>n===10).length} 次全中 · 个人最佳 ${best} 分`;$('readyBadge').innerHTML='<span></span>本场完成';$('launchLabel').textContent='比赛结束 · 再来一场';setTimeout(()=>{if(state==='finished')$('resultDialog').showModal()},1700);return}else{fresh=knocked===10||(frame.length===2&&frame[0]+frame[1]===10)}
if(fresh)resetPins();else pins.forEach(p=>{if(p.down){p.active=false;p.g.visible=false}});setupBall();}
function physics(dt){flightTime+=dt;ballVX+=(spin*.85+wind*.38)*dt;ball.position.x+=ballVX*dt;ball.position.z+=ballVZ*dt;ballVZ*=Math.pow(.985,dt);ball.rotation.x+=ballVZ*dt/.62;ball.rotation.z-=ballVX*dt/.62;
if(Math.abs(ball.position.x)>4.06){ball.position.x=THREE.MathUtils.clamp(ball.position.x,-4.3,4.3);ballVX=0;ball.position.y=.47;ballVZ*=Math.pow(.7,dt)}
if(mode==='trick')for(const o of obstacles){const dx=ball.position.x-o.position.x,dz=ball.position.z-o.position.z,dist=Math.hypot(dx,dz);if(dist<1.22){const nx=dx/dist,nz=dz/dist,dot=ballVX*nx+ballVZ*nz;if(dot<0){ballVX-=1.65*dot*nx;ballVZ-=1.65*dot*nz;ball.position.x=o.position.x+nx*1.23;ball.position.z=o.position.z+nz*1.23;burst(o.position.x,o.position.z,12);tone(950,.13)}}}
for(const p of pins){if(!p.active)continue;const dx=p.x-ball.position.x,dz=p.z-ball.position.z,dist=Math.hypot(dx,dz);if(dist<(p.down?.87:.98)&&ball.visible){const norm=Math.max(dist,.01),impact=Math.max(2,Math.abs(ballVZ)*.72);knockPin(p,dx/norm*impact+ballVX*.4,dz/norm*impact+ballVZ*.35);ballVX-=dx/norm*1.15;ballVZ*=.93}}
for(let i=0;i<pins.length;i++){const p=pins[i];if(!p.active)continue;if(p.down){p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-2.1*dt);p.vz*=Math.exp(-2.1*dt);p.tilt=Math.min(Math.PI*.48,p.tilt+dt*4.5);p.g.rotation.set(Math.cos(p.rot)*p.tilt,0,-Math.sin(p.rot)*p.tilt);p.g.position.set(p.x,.25,p.z);if(Math.abs(p.x)>4.05){p.x=THREE.MathUtils.clamp(p.x,-4.05,4.05);p.vx*=-.35}for(let j=0;j<pins.length;j++){if(i===j)continue;const q=pins[j];if(!q.active||q.down)continue;const dx=q.x-p.x,dz=q.z-p.z,dist=Math.hypot(dx,dz);if(dist<1.1&&Math.hypot(p.vx,p.vz)>1.3)knockPin(q,dx/Math.max(dist,.1)*Math.hypot(p.vx,p.vz)*.82,dz/Math.max(dist,.1)*Math.hypot(p.vx,p.vz)*.82)}}}
if(ball.position.z<-19||ball.position.z>17||flightTime>7){ball.visible=false;settleTime+=dt;if(settleTime>1.35)finishRoll()}}
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;const mobile=w<650;camera.position.set(view?0:mobile?19:20,view?38:mobile?28:24,view?23:mobile?36:31);camera.fov=mobile?43:39;camera.lookAt(mobile?-1:0,0,-3);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(container);resize();
function setSpin(v){spin=v;$('spinValue').textContent=v===0?'直球':v<0?'左旋':'右旋';document.querySelectorAll('[data-spin]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.spin)===v));updateAim()}
$('aim').addEventListener('input',e=>{aim=Number(e.target.value);updateAim()});document.querySelectorAll('[data-spin]').forEach(b=>b.onclick=()=>setSpin(Number(b.dataset.spin)));
$('launchBtn').addEventListener('pointerdown',e=>{e.preventDefault();$('launchBtn').setPointerCapture(e.pointerId);startCharge()});$('launchBtn').addEventListener('pointerup',release);$('launchBtn').addEventListener('pointercancel',()=>{if(state==='charging'){state='ready';setupBall()}});
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{if(state==='ready'){drag=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)}});renderer.domElement.addEventListener('pointermove',e=>{if(drag!==null){aim=THREE.MathUtils.clamp(aim+(e.clientX-drag)*.08,-18,18);drag=e.clientX;$('aim').value=aim;updateAim()}});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);
function togglePause(){if(state==='finished')return;if(state==='charging'){state='ready';setupBall()}paused=!paused;$('pauseOverlay').classList.toggle('hidden',!paused);$('pauseBtn').textContent=paused?'▶':'Ⅱ';$('pauseBtn').setAttribute('aria-label',paused?'继续游戏':'暂停游戏')}
$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('viewBtn').onclick=()=>{view=1-view;resize()};$('fullBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.game-shell').requestFullscreen()}catch{toast('全屏不可用','BROWSER TIP','请使用浏览器的全屏功能。')}};
$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'♫':'♪';$('soundBtn').style.background=sound?'#e3e9d9':'';$('soundBtn').setAttribute('aria-label',sound?'关闭音效':'开启音效');tone(660,.18)};
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{if(mode===b.dataset.mode)return;mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));obstacles.forEach(x=>x.visible=mode==='trick');scene.fog.color.set(mode==='wind'?'#c3d8dc':'#d5e7e8');scene.background.copy(scene.fog.color);snowfall.material.size=mode==='wind'?.14:.09;$('sceneCaption').textContent=mode==='wind'?'风会改变方向，快乐不会。注意每球的侧风。':mode==='trick'?'绕过冰晶障碍，让曲线球替你开路。':'深呼吸，瞄准，然后让雪球飞一会儿。';resetGame();toast(mode==='wind'?'迎风出发':mode==='trick'?'挑战开始':'回归经典','NEW ADVENTURE','新模式，新的一场。')});
$('restartBtn').onclick=()=>{resetGame();toast('新的好球，正在路上','FRESH START','记分卡已重置，个人最佳已保留。')};$('playAgain').onclick=resetGame;
function showHelp(){if(state==='charging'){state='ready';setupBall()}$('helpDialog').showModal()};$('howNav').onclick=$('helpBtn').onclick=showHelp;$('playNav').onclick=()=>document.querySelector('.game-shell').scrollIntoView({behavior:'smooth',block:'center'});document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('.close-help').onclick=()=>$('helpDialog').close();
window.addEventListener('keydown',e=>{if($('helpDialog').open||$('resultDialog').open)return;if(['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!e.repeat)startCharge();if(e.code==='KeyP'&&!e.repeat)togglePause();if(!paused&&state==='ready'){if(e.code==='ArrowLeft'||e.code==='ArrowRight'){aim=THREE.MathUtils.clamp(aim+(e.code==='ArrowLeft'?-0.7:.7),-18,18);$('aim').value=aim;updateAim()}if(e.code==='KeyA')setSpin(-1);if(e.code==='KeyD')setSpin(1);if(e.code==='KeyS')setSpin(0)}});window.addEventListener('keyup',e=>{if(e.code==='Space')release()});window.addEventListener('blur',()=>{if(state==='charging'){state='ready';setupBall()}});
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.045);last=now;if(!paused&&!$('helpDialog').open){elapsed+=dt;arm.rotation.z=THREE.MathUtils.lerp(arm.rotation.z,Math.sin(elapsed*1.8)*.13,dt*3);snowman.rotation.z=Math.sin(elapsed*1.6)*.018;if(state==='charging'){chargeTime+=dt;charge=.08+(1-Math.cos(Math.min(chargeTime,2.5)/2.5*Math.PI*2))*.46;$('powerFill').style.width=`${charge*100}%`;$('powerLabel').textContent=`力量 ${Math.round(charge*100)}%${charge>=.65&&charge<=.85?' · 完美区间':''}`;if(chargeTime>=2.5)chargeTime=0;ball.scale.setScalar(.62+Math.sin(elapsed*18)*.012)}if(state==='rolling'){const steps=3;for(let i=0;i<steps&&state==='rolling';i++)physics(dt/steps)}
for(let i=0;i<snowCount;i++){snowPositions[i*3]+=dt*(mode==='wind'?wind*2:.3);snowPositions[i*3+1]-=dt*(mode==='wind'?3.5:.9);if(snowPositions[i*3+1]<0)snowPositions[i*3+1]=28;if(snowPositions[i*3]>40)snowPositions[i*3]=-40;if(snowPositions[i*3]<-40)snowPositions[i*3]=40}snowGeo.attributes.position.needsUpdate=true;for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.v.y-=9*dt;p.m.position.addScaledVector(p.v,dt);p.m.scale.multiplyScalar(1-dt*.7);if(p.life<0){scene.remove(p.m);particles.splice(i,1)}}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('visible')}}renderer.render(scene,camera)}
resetGame();updateAim();requestAnimationFrame(animate);
