import {BandStage} from './stage.js';
import {BandAudio} from './audio.js';
import {SONGS,DIFFICULTIES,makeChart,judge,formatTime,gradeFor} from './game-core.js';
window.addEventListener('unhandledrejection',event=>console.error('Robot Band async error:',String(event.reason),event.reason?.stack||''));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLORS=['#c6ff5e','#66dbf8','#b39cff','#ffac76'];
let stage;try{stage=new BandStage($('#stageCanvas'))}catch(err){console.warn('3D unavailable',err);$('#noWebgl').hidden=false}
const audio=new BandAudio();let songIndex=0,difficulty='easy',mode='rhythm',state='idle',startTime=0,elapsed=0,nextBeat=0,notes=[],score=0,combo=0,maxCombo=0,energy=0,perfect=0,good=0,miss=0,brokenHolds=0,overdriveUntil=0,feedbackUntil=0,lastCount='',generation=0,missionDone=false,volume=.65,offset=0;
const held=[false,false,false,false],flashes=[0,0,0,0];const hitEffects=[];let records={};try{records=JSON.parse(localStorage.getItem('neon-assembly-records')||'{}')}catch{}
const song=()=>SONGS[songIndex],beat=()=>60/song().bpm,totalDuration=()=>song().beats*beat(),recordKey=()=>songIndex+'-'+difficulty;
const notesCanvas=$('#notesCanvas'),ctx=notesCanvas.getContext('2d');let cw=0,ch=0;function resizeNotes(){const r=notesCanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);cw=r.width;ch=r.height;notesCanvas.width=cw*dpr;notesCanvas.height=ch*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}new ResizeObserver(resizeNotes).observe($('#highway'));
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2400)}
function modal(html){if(state==='playing'||state==='countdown')pause();$('#modalContent').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close()}
$('.modal-close').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
function renderSongs(){$('#songList').innerHTML=SONGS.map((s,i)=>`<button class="song-card ${i===songIndex?'selected':''}" data-song="${i}" aria-pressed="${i===songIndex}" ${state!=='idle'&&state!=='ended'?'disabled':''}><span class="song-cover"><span>${['N','M','O'][i]}</span></span><span class="song-info"><strong>${s.title}</strong><span>${s.zh} · ${s.genre}</span><small>${s.tag}</small></span><span class="song-end">${i===songIndex?'≋':'·'}<small>0${i+1}</small></span></button>`).join('');$$('[data-song]').forEach(b=>b.onclick=()=>selectSong(+b.dataset.song));updateDetails()}
function updateDetails(){$('#bpmValue').textContent=song().bpm;$('#lengthValue').textContent=formatTime(totalDuration()).replace(/^0/,'');$('#selectedGenre').textContent=song().genre;$('#timeDisplay').innerHTML=`00:00 <b>/ ${formatTime(totalDuration())}</b>`;const r=records[recordKey()];$('#bestScore').textContent=r?`${r.grade} · ${r.score.toLocaleString()}`:'尚未演出'}
function selectSong(i){if(!Number.isInteger(i)||!SONGS[i])throw new Error('无效曲目');if(!['idle','ended'].includes(state))throw new Error('请先结束当前演出');songIndex=i;renderSongs()}
function setDifficulty(value){if(!DIFFICULTIES[value])throw new Error('无效难度');if(!['idle','ended'].includes(state))throw new Error('演出中无法更改难度');difficulty=value;$$('[data-difficulty]').forEach(b=>{b.classList.toggle('selected',b.dataset.difficulty===value);b.setAttribute('aria-pressed',b.dataset.difficulty===value)});$('#difficultyCaption').textContent={easy:'找到你的节奏',normal:'加入切分与连音',hard:'双押与密集节奏'}[value];updateDetails()}
$$('[data-difficulty]').forEach(b=>b.onclick=()=>setDifficulty(b.dataset.difficulty));
function lockControls(locked){$$('[data-song],[data-difficulty]').forEach(b=>b.disabled=locked||(mode==='jam'&&'difficulty' in b.dataset))}
function resetStats(){score=combo=maxCombo=energy=perfect=good=miss=brokenHolds=0;overdriveUntil=0;missionDone=false;$('#missionCheck').textContent='↗';$('#missionTitle').textContent=mode==='jam'?'这一首，没有标准答案。':'让默契，持续 20 拍。';$('#missionText').textContent=mode==='jam'?'选择喜欢的伴奏，组合属于你的现场。':'达成 20 次连击，点亮「电路默契」徽章。';held.fill(false);hitEffects.length=0;updateStats()}
function updateStats(){$('#score').textContent=String(score).padStart(6,'0');$('#combo').innerHTML=`${combo} <small>×</small>`;const count=perfect+good+miss;const accuracy=count?(perfect+good*.7)/count*100:0;$('#accuracy').innerHTML=`${count?accuracy.toFixed(1):'—'}<small>%</small>`;$('#energyBar').style.width=energy+'%';$('.energy-stat').classList.toggle('ready',energy>=100);$('#overdriveBtn').disabled=!(state==='playing'&&(mode==='jam'||energy>=100));}
async function start(){if(state==='loading')return;if(state==='paused'){await resume();return}if(state==='playing'||state==='countdown'){endRun(false);return}const token=++generation;state='loading';$('#startBtn').disabled=true;try{await audio.init();if(token!==generation)return;audio.stop();audio.setVolume(volume);resetStats();notes=mode==='rhythm'?makeChart(song(),difficulty):[];startTime=audio.time+beat()*3;elapsed=-beat()*3;nextBeat=0;lastCount='';state='countdown';for(let i=0;i<3;i++)audio.cue(audio.time+i*beat());$('#trackIdle').style.display='none';$('#pauseBtn').disabled=false;$('#pauseBtn span').textContent='暂停';$('#startBtn').innerHTML='<span>■</span><span>结束演出</span><kbd>ENTER</kbd>';$('#stageStatus').textContent='准备开演';document.body.classList.add('game-running');lockControls(true);if(window.innerWidth<=800)$('.performance').scrollIntoView({behavior:'smooth',block:'start'});$('#trackHint').textContent=mode==='jam'?'自由演奏，D / F / J / K 加入乐队':'跟随音符 · 长条音符请按住';}catch(e){state='idle';toast('声音启动失败，请重试或换用支持 Web Audio 的浏览器');console.error(e)}finally{$('#startBtn').disabled=false}}
function endRun(showResults=true){++generation;const wasJam=mode==='jam';audio.stop();state='ended';$('#countdown').textContent='';$('#stageFeedback').textContent='';$('#stageStatus').textContent='演出结束';document.body.classList.remove('game-running','overdrive');held.fill(false);$$('[data-lane]').forEach(b=>b.classList.remove('pressed'));$('#pauseBtn').disabled=true;$('#startBtn').innerHTML='<span class="play-icon">▶</span><span>再次演出</span><kbd>ENTER</kbd>';lockControls(false);if(showResults&&!wasJam){showResult()}else{$('#trackIdle').style.display='flex';$('#trackIdle strong').textContent=wasJam?'即兴时刻，随时开始':'下一场，会更精彩';$('#trackIdle div>span').textContent='换一首歌，或者挑战新的难度'}updateDetails();updateStats()}
function showResult(){const total=notes.length;const acc=total?(perfect+good*.7)/total*100:0;const grade=gradeFor(acc,miss+brokenHolds);const old=records[recordKey()];const newBest=!old||score>old.score;let saved=true;if(newBest){records[recordKey()]={score,grade,accuracy:acc,maxCombo,date:new Date().toISOString()};try{localStorage.setItem('neon-assembly-records',JSON.stringify(records))}catch{saved=false}}
 modal(`<span class="eyebrow">SHOW COMPLETE · 演出完成</span><h2>${song().title}</h2><div class="result-grade">${grade}</div><div class="result-subtitle">${newBest?'✦ 新的个人最佳':'每一次演出，都更有默契'}</div><div class="result-grid"><div><strong>${score.toLocaleString()}</strong><span>演出得分</span></div><div><strong>${maxCombo}</strong><span>最高连击</span></div><div><strong>${acc.toFixed(1)}%</strong><span>精准率</span></div></div><div class="result-details"><span>PERFECT ${perfect}</span><span>GOOD ${good}</span><span>MISS ${miss}</span></div><p>${missionDone?'✦ 已解锁「电路默契」：连续命中 20 个音符。':'再试一次：连续命中 20 个音符，获得电路默契徽章。'}${brokenHolds?`<br>有 ${brokenHolds} 个长音提前松开。`:''}${saved?'':'<br>浏览器存储不可用，本次记录仅保留到关闭页面。'}</p><button class="start-btn" id="replayBtn">再来一场</button>`);$('#replayBtn').onclick=()=>{closeModal();start()}}
async function pause(){if(state!=='playing'&&state!=='countdown')return;const previous=state;state='paused';pause.previous=previous;held.fill(false);$$('[data-lane]').forEach(b=>b.classList.remove('pressed'));await audio.suspend();$('#countdown').textContent='PAUSED';$('#stageStatus').textContent='演出暂停';$('#pauseBtn span').textContent='继续';$('#startBtn').innerHTML='<span>▶</span><span>继续演出</span><kbd>ENTER</kbd>';}
async function resume(){if(state!=='paused')return;await audio.resume();state=pause.previous||'playing';notes.filter(n=>n.status==='holding').forEach(n=>n.grace=audio.time-startTime+.35);$('#countdown').textContent='';lastCount='';$('#stageStatus').textContent=state==='countdown'?'准备开演':'LIVE · 演出中';$('#pauseBtn span').textContent='暂停';$('#startBtn').innerHTML='<span>■</span><span>结束演出</span><kbd>ENTER</kbd>';}
$('#startBtn').onclick=start;$('#pauseBtn').onclick=()=>state==='paused'?resume():pause();
function feedback(text,color=COLORS[0]){$('#stageFeedback').textContent=text;$('#stageFeedback').style.color=color;feedbackUntil=performance.now()+600}
function award(n,judgment){n.status=n.duration?'holding':'hit';n.heldFrom=elapsed;n.grace=elapsed+.12;n.judgment=judgment;combo++;maxCombo=Math.max(maxCombo,combo);if(judgment==='perfect'){perfect++;energy=Math.min(100,energy+4)}else{good++;energy=Math.min(100,energy+2)}const multiplier=1+Math.min(3,Math.floor(combo/10));score+=(judgment==='perfect'?100:60)*multiplier*(elapsed<overdriveUntil?2:1);feedback(judgment==='perfect'?'PERFECT':'GOOD',judgment==='perfect'?COLORS[n.lane]:'#dfedce');hitEffects.push({lane:n.lane,t:performance.now(),text:judgment.toUpperCase()});if(combo>=20&&!missionDone){missionDone=true;$('#missionCheck').textContent='✓';$('#missionTitle').textContent='电路默契，已达成。';$('#missionText').textContent='20 连击完成！继续挑战更高纪录。';toast('✦ 解锁「电路默契」· 20 连击')}updateStats()}
function missNote(n){n.status='miss';miss++;combo=0;energy=Math.max(0,energy-10);feedback('MISS','#859575');updateStats()}
function completeHold(n){if(n.status!=='holding')return;n.status='hit';score+=50*(elapsed<overdriveUntil?2:1);updateStats()}
function breakHold(n){n.status='broken';brokenHolds++;combo=0;energy=Math.max(0,energy-7);feedback('HOLD LOST','#859575');updateStats()}
async function pressLane(lane){if(held[lane]||$('#modal').open)return;held[lane]=true;flashes[lane]=1;stage?.hit(lane);$$('[data-lane]')[lane].classList.add('pressed');if(state==='paused'||state==='loading')return;
 if(!audio.context||audio.context.state==='suspended'){try{await audio.init()}catch{toast('无法启用声音');return}if(!held[lane])return}if(state==='paused')return;
 const freqs=[110,song().root*2,song().root*4,song().root*8*Math.pow(2,[0,3,7,10][Math.floor(Math.max(0,elapsed)/beat())%4]/12)];audio.playLane(lane,audio.time,freqs[lane]);
 if(state!=='playing'||mode==='jam')return;const t=audio.time-startTime-offset/1000;let best=null,delta=Infinity;for(const n of notes){if(n.lane!==lane||n.status!=='pending')continue;const d=Math.abs(n.t-t);if(d<delta){delta=d;best=n}if(n.t>t+DIFFICULTIES[difficulty].window)break}if(best&&delta<=DIFFICULTIES[difficulty].window){award(best,judge(delta,DIFFICULTIES[difficulty].window))}else if(!notes.some(n=>n.lane===lane&&n.status==='holding')){combo=0;energy=Math.max(0,energy-2);feedback('跟上节拍','#94a580');updateStats()}}
function releaseLane(lane){held[lane]=false;$$('[data-lane]')[lane].classList.remove('pressed');if(state!=='playing')return;const t=audio.time-startTime-offset/1000;notes.filter(n=>n.lane===lane&&n.status==='holding').forEach(n=>{if(t<n.t+n.duration-.11)breakHold(n);else completeHold(n)})}
$$('[data-lane]').forEach((b,i)=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pressLane(i)});b.addEventListener('pointerup',()=>releaseLane(i));b.addEventListener('pointercancel',()=>releaseLane(i));b.addEventListener('lostpointercapture',()=>releaseLane(i))});
const KEY_LANES={KeyD:0,KeyF:1,KeyJ:2,KeyK:3};document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.repeat)return;if($('#modal').open)return;if(e.code in KEY_LANES){e.preventDefault();pressLane(KEY_LANES[e.code])}else if(e.code==='Space'){e.preventDefault();activateOverdrive()}else if(e.code==='Enter'){if(e.target.closest('button'))return;e.preventDefault();start()}else if(e.code==='Escape'){e.preventDefault();state==='paused'?resume():pause()}});document.addEventListener('keyup',e=>{if(e.code in KEY_LANES){e.preventDefault();releaseLane(KEY_LANES[e.code])}});window.addEventListener('blur',()=>{if(state==='playing'||state==='countdown')pause();held.fill(false);$$('[data-lane]').forEach(b=>b.classList.remove('pressed'))});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='playing'||state==='countdown'))pause()});
function activateOverdrive(){if(state!=='playing')return;if(mode==='jam'){overdriveUntil=elapsed+beat()*8;feedback('JAM SESSION ✦');return}if(energy<100){toast('精准演奏积累能量，充满后按空格');return}energy=0;overdriveUntil=elapsed+beat()*8;feedback('OVERDRIVE ×2');toast('能量爆发 · 8 拍双倍得分');updateStats()}$('#overdriveBtn').onclick=activateOverdrive;
function setMode(value){if(!['rhythm','jam'].includes(value))throw new Error('无效模式');if(value===mode)return;if(!['idle','ended'].includes(state))endRun(false);mode=value;state='idle';document.body.classList.toggle('jam-mode',mode==='jam');$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));resetStats();$('#trackIdle').style.display='flex';$('#trackIdle strong').textContent=mode==='jam'?'没有对错，只有你的律动':'乐队已经就位';$('#trackIdle div>span').textContent=mode==='jam'?'按 D / F / J / K 试奏，开始后加入循环伴奏':'选一首歌，开始你的第一场演出';$('#trackHint').textContent=mode==='jam'?'自由弹奏四个声部 · 空格切换灯光爆发':'音符到达判定线时，按下对应按键';$('#startBtn').innerHTML=`<span class="play-icon">▶</span><span>${mode==='jam'?'开始即兴':'开始演出'}</span><kbd>ENTER</kbd>`;$('#stageStatus').textContent=mode==='jam'?'JAM · 即兴待命':'等待开演';$$('[data-difficulty]').forEach(b=>b.disabled=mode==='jam');$('#missionTitle').textContent=mode==='jam'?'这一首，没有标准答案。':'让默契，持续 20 拍。';$('#missionText').textContent=mode==='jam'?'选择喜欢的伴奏，组合属于你的现场。':'达成 20 次连击，点亮「电路默契」徽章。'}$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#cameraBtn').onclick=()=>{const index=stage?.cycleCamera();toast(['正面全景','舞台右侧','舞台左侧'][index]||'3D 视角暂不可用')};$('#fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('.performance').requestFullscreen)await $('.performance').requestFullscreen();else toast('当前浏览器不支持全屏')}catch{toast('无法切换全屏')}};
$('#helpBtn').onclick=()=>modal(`<span class="eyebrow">HOW TO PLAY</span><h2>找到节拍，接管舞台。</h2><p>音符落到亮色判定线时，按下对应按键。也可以直接触摸底部四个演奏键。</p><div class="help-grid"><div><kbd>D · F · J · K</kbd>鼓点、贝斯、和弦与旋律</div><div><kbd>按住长条音符</kbd>保持到尾部通过判定线</div><div><kbd>SPACE</kbd>能量满后，8 拍双倍得分</div><div><kbd>ESC</kbd>暂停或继续演出</div></div><p>每 10 连击提升倍率，最高 4 倍。PERFECT 积累更多能量；按空键会中断连击。精准率按 PERFECT 100%、GOOD 70%、MISS 0% 计算。<br>自由即兴模式没有判定，和伴奏一起探索四个声部。</p>`);
$('#settingsBtn').onclick=()=>{modal(`<span class="eyebrow">SOUND CHECK</span><h2>调好声音，准备登台。</h2><label>主音量 <input id="volumeSlider" type="range" min="0" max="100" value="${Math.round(volume*100)}" aria-label="主音量"></label><label>音符补偿 <span id="offsetValue">${offset} ms</span></label><input id="offsetSlider" type="range" min="-150" max="150" step="5" value="${offset}" aria-label="音符补偿" style="width:100%"><p>如果蓝牙耳机让声音比画面晚到，可增加补偿。推荐使用有线耳机，将延迟降到更低。</p>`);$('#volumeSlider').oninput=e=>{volume=+e.target.value/100;audio.setVolume(volume)};$('#offsetSlider').oninput=e=>{offset=+e.target.value;$('#offsetValue').textContent=offset+' ms'}};
$('#recordsBtn').onclick=()=>{const rows=Object.entries(records).filter(([k,r])=>/^\d-(easy|normal|hard)$/.test(k)&&Number.isFinite(r.score)).map(([k,r])=>{const [si,diff]=k.split('-');if(!SONGS[si])return '';return `<div class="record-row"><span>${SONGS[si].title}<small>${DIFFICULTIES[diff].label} · 精准率 ${Number(r.accuracy).toFixed(1)}% · ${r.maxCombo} 连击</small></span><strong>${r.grade} / ${r.score.toLocaleString()}</strong></div>`}).join('');modal(`<span class="eyebrow">PERSONAL RECORDS</span><h2>每次登台，都有回响。</h2>${rows||'<p>还没有演出记录。完成一首曲目，留下属于你的第一束聚光灯。</p>'}<p style="font-size:11px">成绩保存在当前浏览器中。提前结束的演出不计入记录。</p>`)};
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function renderNotes(now){ctx.clearRect(0,0,cw,ch);const lw=cw/4,hitY=ch-(window.innerWidth<=800?69:62),lookahead=DIFFICULTIES[difficulty].lookahead;for(let lane=0;lane<4;lane++){flashes[lane]*=.9;if(flashes[lane]>.01){const g=ctx.createLinearGradient(0,hitY,0,0);g.addColorStop(0,COLORS[lane]+'38');g.addColorStop(1,COLORS[lane]+'00');ctx.globalAlpha=flashes[lane];ctx.fillStyle=g;ctx.fillRect(lane*lw,0,lw,hitY);ctx.globalAlpha=1}}
 if(state==='playing'||state==='countdown'||state==='paused'){if(mode==='rhythm'){for(const n of notes){if(!['pending','holding'].includes(n.status))continue;const t=elapsed-offset/1000;let y=hitY-(n.t-t)/lookahead*hitY;const endY=hitY-(n.t+n.duration-t)/lookahead*hitY;if(y<-15||endY>ch)continue;const x=n.lane*lw+lw*.22,w=lw*.56;if(n.duration){ctx.fillStyle=COLORS[n.lane]+'30';roundedRect(x+w*.28,Math.max(-10,endY),w*.44,Math.max(0,(n.status==='holding'?hitY:y)-Math.max(-10,endY)),4);ctx.fill();ctx.fillStyle=COLORS[n.lane]+'90';ctx.fillRect(x+w*.46,Math.max(0,endY),w*.08,Math.max(0,(n.status==='holding'?hitY:y)-Math.max(0,endY)));if(n.status==='holding')y=hitY;}ctx.shadowColor=COLORS[n.lane];ctx.shadowBlur=10;ctx.fillStyle=COLORS[n.lane];roundedRect(x,y-5,w,10,3);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ffffff80';ctx.fillRect(x+3,y-4,w-6,2);}}
 else{for(let l=0;l<4;l++){ctx.strokeStyle=COLORS[l]+'60';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<lw;x+=3){const y=hitY*.5+Math.sin(x*.065-now*.006+l)*Math.sin(x/lw*Math.PI)*(held[l]?25:8);if(!x)ctx.moveTo(l*lw+x,y);else ctx.lineTo(l*lw+x,y)}ctx.stroke()}}}
 for(let i=hitEffects.length-1;i>=0;i--){const fx=hitEffects[i],age=(now-fx.t)/550;if(age>1){hitEffects.splice(i,1);continue}ctx.globalAlpha=1-age;ctx.strokeStyle=COLORS[fx.lane];ctx.lineWidth=2;ctx.beginPath();ctx.ellipse((fx.lane+.5)*lw,hitY,lw*.22+age*20,7+age*13,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle=COLORS[fx.lane];ctx.font='600 10px DM Sans, sans-serif';ctx.textAlign='center';ctx.fillText(fx.text,(fx.lane+.5)*lw,hitY-20-age*25);ctx.globalAlpha=1}}
function frame(now){requestAnimationFrame(frame);if(state==='playing'||state==='countdown'){elapsed=audio.time-startTime;const b=beat();if(elapsed<0){const count=String(Math.ceil(-elapsed/b));if(count!==lastCount){$('#countdown').textContent=count;lastCount=count}}else{if(state==='countdown'){state='playing';$('#countdown').textContent='';$('#stageStatus').textContent='LIVE · 演出中';if(mode==='jam'){toast('自由即兴 · D / F / J / K 随时加入');updateStats()}}while(nextBeat*b<elapsed+.15&&nextBeat<=(mode==='jam'?Infinity:song().beats)){audio.scheduleBacking(startTime+nextBeat*b,nextBeat,song().bpm,songIndex);nextBeat++}
 if(mode==='rhythm'){const t=elapsed-offset/1000;for(const n of notes){if(n.status==='pending'&&t>n.t+DIFFICULTIES[difficulty].window)missNote(n);else if(n.status==='holding'){if(t>=n.t+n.duration-.065){completeHold(n)}else if(!held[n.lane]&&t>n.grace)breakHold(n)}}if(elapsed>=totalDuration()+.4){endRun(true);return}}$('#timeDisplay').innerHTML=`${formatTime(elapsed)} <b>/ ${mode==='jam'?'LIVE':formatTime(totalDuration())}</b>`;document.body.classList.toggle('overdrive',elapsed<overdriveUntil);}}
 if(now>feedbackUntil)$('#stageFeedback').textContent='';renderNotes(now);stage?.update(['playing','paused','countdown'].includes(state)?elapsed:now/1000,state==='playing',song().bpm,state==='playing'&&elapsed<overdriveUntil)}
renderSongs();setDifficulty('easy');updateStats();resizeNotes();requestAnimationFrame(frame);
// A small feature-detected WebMCP surface mirrors the visible song selector and records.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tools=[{name:'read_band_status',title:'读取乐队状态',description:'Read current mode, selected song, difficulty, score and local personal records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,mode,song:song().title,difficulty,score,combo,energy,records})},{name:'configure_band_session',title:'设置演奏曲目',description:'Select a song, difficulty and mode while the band is idle. Does not start audio or gameplay.',inputSchema:{type:'object',properties:{songIndex:{type:'integer',minimum:0,maximum:2},difficulty:{type:'string',enum:['easy','normal','hard']},mode:{type:'string',enum:['rhythm','jam']}},required:['songIndex','difficulty','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.songIndex)||!SONGS[input.songIndex]||!DIFFICULTIES[input.difficulty]||!['rhythm','jam'].includes(input.mode))throw new Error('Invalid session configuration');if(!['idle','ended'].includes(state))throw new Error('Finish the current session first');setMode(input.mode);selectSong(input.songIndex);setDifficulty(input.difficulty);return {song:song().title,difficulty,mode}}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
