import * as THREE from 'three';
import './style.css';
import { seeded, generateMaze } from './maze.js';
const $=id=>document.getElementById(id), N=19, S=1.18;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x16261d,.011);
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const camera=new THREE.PerspectiveCamera(36,1,.1,150);let azimuth=-.48,zoom=1,targetZoom=1;
scene.add(new THREE.HemisphereLight(0xcdebb0,0x403327,2.5));const sun=new THREE.DirectionalLight(0xffe5ab,4);sun.position.set(-8,18,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-19,right:19,top:19,bottom:-19,near:.1,far:60});sun.shadow.bias=-.001;scene.add(sun);const fill=new THREE.DirectionalLight(0x70cabc,1.7);fill.position.set(10,5,-10);scene.add(fill);
let world=new THREE.Group();scene.add(world);let grid=[],walls=new Map(),items=[],bugs=[],mole,visited=new Set(),keys={},particles=[],playing=false,paused=false,won=false,stepCD=0,bugCD=0,sonarCD=0,hitCD=0,elapsed=0,moveFrom=null,moveT=1,sonarUntil=0;
let state={level:1,x:1,z:1,dir:[0,1],health:100,energy:100,coins:0,gems:0,upgrade:0,totalGems:0,seed:Math.floor(Math.random()*1e8)};let rnd=Math.random;
const mat=(color,roughness=1,emissive=0,intensity=0)=>new THREE.MeshStandardMaterial({color,roughness,emissive,emissiveIntensity:intensity});const materials={floor:mat(0x63764b),soil:mat(0x566b3f),side:mat(0x3d4830),stone:mat(0x506448),grass:mat(0x7e9360),wood:mat(0x765439),gem:mat(0x8eefe0,.24,0x31bca2,.7),coin:mat(0xf4c775,.35,0xbb8528,.2),mush:mat(0xb0a7e8,.7,0x6d5aab,.4),mole:mat(0x9c7760),pink:mat(0xdba99b),dark:mat(0x1d241e),cream:mat(0xe5d5b0),helmet:mat(0xd5ae59,.6)};
const boxG=new THREE.BoxGeometry(1,1,1),sphereG=new THREE.SphereGeometry(1,12,8);
function mesh(g,m,x,y,z,sx=1,sy=1,sz=1,parent=world){let o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function coord(x){return (x-(N-1)/2)*S}function block(m,x,y,z,sx,sy,sz,parent){return mesh(boxG,m,x,y,z,sx,sy,sz,parent)}

function createMole(){let g=new THREE.Group();mesh(sphereG,materials.mole,0,.43,0,.31,.37,.36,g);mesh(sphereG,materials.mole,0,.7,.17,.29,.28,.28,g);mesh(sphereG,materials.pink,0,.65,.43,.14,.085,.11,g);for(let a of [-1,1]){mesh(sphereG,materials.dark,a*.155,.77,.375,.035,.043,.034,g);mesh(sphereG,materials.pink,a*.3,.35,.1,.1,.09,.13,g);mesh(sphereG,materials.cream,a*.18,.13,.14,.1,.07,.15,g);mesh(sphereG,materials.pink,a*.235,.85,.12,.07,.08,.05,g)}mesh(sphereG,materials.helmet,0,.92,.16,.29,.13,.27,g);mesh(sphereG,materials.cream,0,.94,.407,.09,.08,.04,g);const lamp=new THREE.PointLight(0xffe6a1,2,3);lamp.position.set(0,1,.5);g.add(lamp);block(materials.wood,0,.48,-.28,.32,.37,.16,g);const marker=mesh(new THREE.TorusGeometry(.46,.023,6,32),materials.gem,0,.1,0,1,1,1,g);marker.rotation.x=Math.PI/2;world.add(g);return g}
function mushroom(x,z,scale=1,color=materials.mush){let g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(scale);mesh(new THREE.CylinderGeometry(.035,.055,.26,7),materials.cream,0,.13,0,1,1,1,g);mesh(new THREE.SphereGeometry(.18,10,6,0,Math.PI*2,0,Math.PI/2),color,0,.27,0,1,.7,1,g);world.add(g);return g}
function build(saved=null){const disposed=new Set(),shared=new Set(Object.values(materials));for(const c of [...world.children]){c.traverse(o=>{if(o.geometry&&o.geometry!==boxG&&o.geometry!==sphereG&&!disposed.has(o.geometry)){o.geometry.dispose();disposed.add(o.geometry)}if(o.material&&!shared.has(o.material)&&!disposed.has(o.material)){o.material.dispose();disposed.add(o.material)}});world.remove(c)}items=[];bugs=[];walls.clear();particles=[];visited=new Set(saved?.visited||[]);rnd=seeded(state.seed);grid=generateMaze(N,rnd);
if(saved?.grid)grid=saved.grid;
block(materials.side,0,-.78,0,N*S+.3,1.35,N*S+.3);block(materials.floor,0,-.07,0,N*S,.2,N*S);
// Stratified earthen edges.
for(let i=0;i<4;i++){const m=mat([0x544b31,0x3c402a,0x605337,0x414a2e][i]);block(m,0,-.3-i*.27,(N*S+.32)/2,N*S+.36,.08,.025);block(m,-(N*S+.32)/2,-.3-i*.27,0,.025,.08,N*S+.36)}
const floorMats=[mat(0x738258),mat(0x69794e),mat(0x627347),mat(0x7c8758)];const wallMats=[mat(0x455c36),mat(0x51663b),mat(0x596d43),mat(0x64774b)];
for(let z=0;z<N;z++)for(let x=0;x<N;x++){let px=coord(x),pz=coord(z);block(floorMats[Math.floor(rnd()*4)],px,.015,pz,S-.025,.09,S-.025);if(grid[z][x]){let g=new THREE.Group();let soft=grid[z][x]===2,h=soft?.53:.7+rnd()*.18;block(soft?materials.wood:wallMats[Math.floor(rnd()*4)],px,h/2,pz,S-.065,h,S-.065,g);block(soft?mat(0x967951):materials.grass,px,h+.025,pz,S-.08,.06,S-.08,g);if(soft){for(let k=0;k<3;k++)block(materials.side,px+(k-1)*.28,h+.059,pz,.04,.015,.5,g)}else if(rnd()<.4){for(let k=0;k<2;k++){let rock=mesh(new THREE.DodecahedronGeometry(.12,0),materials.stone,px+(rnd()-.5)*.7,h+.1,pz+(rnd()-.5)*.7,1,.8,1,g);rock.rotation.set(rnd(),rnd(),rnd())}}world.add(g);walls.set(`${x},${z}`,g)}else if(rnd()<.2){mushroom(px+(rnd()-.5)*.7,pz+(rnd()-.5)*.7,.45+rnd()*.5)}}
let cells=[];for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(!grid[z][x]&&x+z>6&&!(x===17&&z===17))cells.push([x,z]);cells.sort(()=>rnd()-.5);
function item(type,x,z){let g=new THREE.Group();g.position.set(coord(x),0,coord(z));if(type==='gem'){let crystal=mesh(new THREE.OctahedronGeometry(.25),materials.gem,0,.48,0,1,1.65,1,g);crystal.rotation.z=.15;const ring=mesh(new THREE.TorusGeometry(.33,.013,5,24),materials.gem,0,.08,0,1,1,1,g);ring.rotation.x=Math.PI/2;let l=new THREE.PointLight(0x65edd5,1.5,2);l.position.y=.6;g.add(l)}if(type==='coin'){const c=mesh(new THREE.CylinderGeometry(.16,.16,.065,12),materials.coin,0,.32,0,1,1,1,g);c.rotation.x=Math.PI/2}if(type==='camp'){for(let a=0;a<3;a++){let m=mushroom(coord(x)+Math.cos(a*2.1)*.28,coord(z)+Math.sin(a*2.1)*.28,1.4);world.remove(m);m.position.x-=coord(x);m.position.z-=coord(z);g.add(m)}let l=new THREE.PointLight(0xba9bff,2,3);l.position.y=.5;g.add(l)}world.add(g);items.push({type,x,z,g,taken:false})}
if(saved?.itemLayout){for(const i of saved.itemLayout)item(i.type,i.x,i.z)}else{for(let i=0;i<3;i++)item('gem',...cells.pop());for(let i=0;i<23;i++)item('coin',...cells.pop());for(let i=0;i<4;i++)item('camp',...cells.pop())}
for(let i=0;i<Math.min(3+state.level,8);i++){let[x,z]=cells.pop(),g=new THREE.Group();mesh(sphereG,mat(0x9e6448),0,.24,0,.24,.19,.3,g);block(materials.dark,0,.37,0,.018,.014,.46,g);for(let s of [-1,1])for(let k=0;k<3;k++){let leg=block(materials.dark,s*.25,.12,(k-1)*.17,.18,.035,.025,g);leg.rotation.z=s*.4}mesh(sphereG,materials.dark,0,.24,.26,.16,.12,.12,g);g.position.set(coord(x),0,coord(z));world.add(g);bugs.push({x,z,g,stun:0})}
// A welcoming entry and the old brass lift.
block(materials.wood,coord(1),.07,coord(1),1.05,.1,1.05);const exit=new THREE.Group();exit.position.set(coord(17),0,coord(17));block(materials.wood,0,.1,0,.9,.15,.9,exit);for(let a of [-.42,.42]){block(materials.helmet,a,.7,0,.09,1.3,.09,exit)}block(materials.helmet,0,1.32,0,.96,.12,.13,exit);const halo=mesh(new THREE.TorusGeometry(.3,.04,6,24),materials.coin,0,.75,0,1,1,1,exit);let exitLight=new THREE.PointLight(0xffbd60,2,4);exitLight.position.y=1;exit.add(exitLight);world.add(exit);items.push({type:'exit',x:17,z:17,g:exit,taken:false});
if(saved?.taken)for(let i of items){if(saved.taken.includes(i.type+':'+i.x+','+i.z)){i.taken=true;i.g.visible=false}}
mole=createMole();mole.position.set(coord(state.x),0,coord(state.z));moveFrom=null;moveT=1;reveal();updateUI();}
function reveal(){for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++){let x=state.x+dx,z=state.z+dz;if(x>=0&&z>=0&&x<N&&z<N)visited.add(x+','+z)}drawMap()}
function drawMap(){let c=$('minimap').getContext('2d'),s=126/N;c.fillStyle='#142019';c.fillRect(0,0,126,126);for(let z=0;z<N;z++)for(let x=0;x<N;x++){let seen=visited.has(x+','+z);if(seen||sonarUntil>elapsed){c.fillStyle=grid[z][x]===1?'#344936':grid[z][x]===2?'#786449':'#82966b';c.fillRect(x*s+1,z*s+1,s-1,s-1)}}for(let i of items)if(!i.taken&&(visited.has(i.x+','+i.z)||sonarUntil>elapsed)){c.fillStyle={gem:'#8ef0de',coin:'#e4b35e',camp:'#b1a2e4',exit:'#ffe29a'}[i.type];c.fillRect(i.x*s+1,i.z*s+1,s-1,s-1)}c.fillStyle='#fff7cd';c.beginPath();c.arc((state.x+.5)*s,(state.z+.5)*s,3,0,Math.PI*2);c.fill();$('explored').textContent=Math.round(visited.size/(N*N)*100)+'%'}
function updateUI(){$('mobileStats').textContent=`♥ ${Math.ceil(state.health)}   ϟ ${Math.floor(state.energy)}   ◇ ${state.gems}/3   ✦ ${state.coins}`;$('healthText').textContent=Math.ceil(state.health)+' / 100';$('energyText').textContent=Math.floor(state.energy)+' / 100';$('healthBar').style.width=state.health+'%';$('energyBar').style.width=state.energy+'%';$('coinText').textContent=state.coins;$('goalCount').textContent=state.gems+' / 3';document.querySelectorAll('.gem-slots span').forEach((e,i)=>e.classList.toggle('found',i<state.gems));$('floorLabel').textContent=`第 ${state.level} 层 · 地下 ${state.level*12} 米`;$('depth').textContent=state.level*12+' m';$('depthBar').style.width=Math.min(100,state.level*15)+'%';$('levelTag').textContent=String(state.level).padStart(2,'0');$('upgradeBtn').innerHTML=state.upgrade>=3?'✓ 利爪已升至满级':`＋ 强化利爪 Lv.${state.upgrade+1} <span>${8+state.upgrade*5} ✦</span>`;$('sonarText').textContent=sonarCD>0?`充能中 · ${Math.ceil(sonarCD)} 秒`:'探测附近宝物'}
let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400)}
let sound=false,audio;function beep(freq=440,duration=.12){if(!sound)return;audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.5,audio.currentTime+duration);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function burst(x,z,color,count=12){let m=mat(color,.7,color,.3);for(let j=0;j<count;j++){let g=mesh(new THREE.IcosahedronGeometry(.04),m,coord(x),.5,coord(z));particles.push({g,v:new THREE.Vector3((Math.random()-.5)*2,1+Math.random()*2,(Math.random()-.5)*2),life:1})}}
function save(){try{localStorage.setItem('underburrow-save',JSON.stringify({state,grid,itemLayout:items.filter(i=>i.type!=='exit').map(({type,x,z})=>({type,x,z})),visited:[...visited],taken:items.filter(i=>i.taken).map(i=>i.type+':'+i.x+','+i.z),elapsed}))}catch{}}
function collect(){for(let i of items){if(i.taken||i.x!==state.x||i.z!==state.z)continue;if(i.type==='gem'){state.gems++;state.totalGems++;i.taken=true;i.g.visible=false;burst(i.x,i.z,0x99ffdf);beep(700);toast(state.gems===3?'升降梯已唤醒！前往地图右下角。':`月光水晶 +1 · ${state.gems}/3`)}if(i.type==='coin'){state.coins++;i.taken=true;i.g.visible=false;beep(480)}if(i.type==='camp'){state.health=Math.min(100,state.health+30);state.energy=100;i.taken=true;i.g.children.forEach(c=>{if(c.isLight)c.intensity=.3});toast('营地蘑菇：恢复 30 生命，体力已充满');beep(330)}if(i.type==='exit'){if(state.gems>=3){nextFloor();return}else toast(`升降梯还需要 ${3-state.gems} 枚月光水晶`)}}updateUI();save()}
function move(dx,dz){if(!playing||paused||won||stepCD>0)return;state.dir=[dx,dz];mole.rotation.y=Math.atan2(dx,dz);let nx=state.x+dx,nz=state.z+dz;if(nx<1||nz<1||nx>=N-1||nz>=N-1||grid[nz][nx]){stepCD=.12;return}const sprint=(keys.Shift||keys.shift)&&state.energy>4;stepCD=sprint?.105:.2;if(sprint)state.energy=Math.max(0,state.energy-3);moveFrom=mole.position.clone();moveT=0;state.x=nx;state.z=nz;reveal();collect()}
function dig(){if(!playing||paused||won)return;let[x,z]=[state.x+state.dir[0],state.z+state.dir[1]];if(x<=0||z<=0||x>=N-1||z>=N-1){toast('外层岩壁太坚硬了，试试棕色松土');return}if(grid[z][x]!==2){toast('面对棕色松软土块，再按 E 挖掘');return}let cost=18-state.upgrade*4;if(state.energy<cost){toast('体力不足，休息片刻或寻找紫色营地蘑菇');return}state.energy-=cost;grid[z][x]=0;world.remove(walls.get(x+','+z));walls.delete(x+','+z);burst(x,z,0xc5a571,18);beep(130,.18);if(Math.random()<.35){state.coins+=2;toast('挖到了古老的蘑菇币！+2 ✦')}else toast('新通道打开了 · 消耗 '+cost+' 体力');reveal();updateUI();save()}
function sonar(){if(!playing||paused||won)return;if(sonarCD>0){toast('声呐还在充能');return}if(state.energy<20){toast('声呐需要 20 体力');return}state.energy-=20;sonarCD=18;sonarUntil=elapsed+7;for(let b of bugs)b.stun=5;const ring=mesh(new THREE.TorusGeometry(1,.026,6,80),materials.gem,coord(state.x),.22,coord(state.z));ring.rotation.x=Math.PI/2;particles.push({g:ring,ring:true,life:2});toast('声呐展开：地图显影 7 秒，甲虫眩晕 5 秒');beep(220,.6);updateUI()}
function modal(html){keys={};$('modalContent').innerHTML=html;$('modal').showModal();paused=true;$('pauseBtn').textContent='▷'}function closeModal(){$('modal').close();if(!won){paused=false;$('pauseBtn').textContent='Ⅱ';$('statusLabel').textContent=playing?'探索进行中':'准备出发'}}$('closeModal').onclick=()=>{if(won){restart()}closeModal()};$('modal').addEventListener('cancel',e=>{e.preventDefault();$('closeModal').click()});
function nextFloor(){paused=true;save();modal(`<div class="eyebrow">EXPEDITION COMPLETE</div><h2>更深处，还有星光。</h2><p>你成功探索了第 ${state.level} 层，收集了所有月光水晶。<br>层数奖励 <b>+5 蘑菇币</b>，下一层将出现更多巡逻甲虫。</p><div class="stats">${state.level*12} m <small>↓</small></div><button class="primary" id="nextFloor">乘坐升降梯 · 继续深入 ↗</button>`);$('nextFloor').onclick=()=>{state.coins+=5;state.level++;Object.assign(state,{x:1,z:1,gems:0,health:100,energy:100,seed:Math.floor(Math.random()*1e8)});sonarCD=0;sonarUntil=0;build();save();closeModal();toast('抵达地下 '+state.level*12+' 米，新迷宫已展开')}}
function die(){won=true;try{localStorage.removeItem('underburrow-save')}catch{}modal(`<div class="eyebrow">A BRAVE LITTLE JOURNEY</div><h2>先回地面，休息一下。</h2><p>Molly 的救援气球把它带回了家。下次探险，记得用声呐暂时击晕甲虫。</p><div class="stats">${state.level*12} m · ${state.totalGems} ◇</div><p>探险用时 ${$('timer').textContent} · 收集 ${state.coins} 枚蘑菇币</p><button class="primary" id="retry">新的探险 ↗</button>`);$('retry').onclick=()=>{restart();closeModal()}}
function restart(){Object.assign(state,{level:1,x:1,z:1,dir:[0,1],health:100,energy:100,coins:0,gems:0,upgrade:0,totalGems:0,seed:Math.floor(Math.random()*1e8)});won=false;paused=false;elapsed=0;sonarCD=0;sonarUntil=0;hitCD=0;build();save();if(playing)toast('一片全新的地下世界已经生成')}
$('startBtn').onclick=()=>{playing=true;paused=false;$('startCard').style.display='none';document.querySelector('.player-badge').style.display='block';$('statusLabel').textContent='探索进行中';toast('WASD 移动 · 棕色软土可用 E 挖掘 · Q 声呐');beep(400);save()};$('digBtn').onclick=dig;$('sonarBtn').onclick=sonar;$('upgradeBtn').onclick=()=>{if(!playing||paused)return;if(state.upgrade>=3){toast('利爪已是最高等级');return}let price=8+state.upgrade*5;if(state.coins<price){toast(`还需要 ${price-state.coins} 枚蘑菇币`);return}state.coins-=price;state.upgrade++;updateUI();save();toast('利爪升级！挖掘体力消耗降低')};$('guideBtn').onclick=()=>modal('<div class="eyebrow">FIELD NOTES / 探险手册</div><h2>小鼹鼠，大冒险。</h2><p><b>目标</b> · 每层收集 3 枚青色月光水晶，再前往地图右下角的金色升降梯。层数越深，甲虫越多。</p><p><b>移动</b> · WASD / 方向键移动，Shift 冲刺。按住鼠标拖动旋转视角，滚轮缩放。方向键始终对应地图方向。</p><p><b>挖掘</b> · 面向棕色土块按 E 开辟捷径。收集金色蘑菇币，强化利爪降低体力消耗。</p><p><b>生存</b> · Q 声呐让完整地图短暂显影，并击晕甲虫。紫色营地蘑菇可恢复生命与体力。体力会自动恢复。</p><p><b>存档</b> · 每次移动和收集自动保存在当前浏览器。空格 / P 暂停。手机上使用方向按钮，点鼹鼠可挖掘，双击场景发出声呐。</p>');$('pauseBtn').onclick=()=>{if(!playing)return;paused=!paused;$('pauseBtn').textContent=paused?'▷':'Ⅱ';$('statusLabel').textContent=paused?'探险已暂停':'探索进行中';toast(paused?'休息一下 · 点击右上角继续':'继续探索！')};$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'♪':'♫';$('soundBtn').style.color=sound?'#d1ea91':'';beep();toast(sound?'音效已开启':'音效已关闭')};$('newBtn').onclick=()=>{modal('<div class="eyebrow">A FRESH START</div><h2>开启新的探险？</h2><p>当前进度将被新的随机世界替代。</p><button class="primary" id="confirmNew">生成新世界 ↗</button>');$('confirmNew').onclick=()=>{restart();closeModal()}};
$('zoomIn').onclick=()=>targetZoom=Math.max(.65,targetZoom-.12);$('zoomOut').onclick=()=>targetZoom=Math.min(1.5,targetZoom+.12);$('resetView').onclick=()=>{azimuth=-.48;targetZoom=1};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if($('modal').open)return;keys[e.key]=true;const direction={w:[0,-1],W:[0,-1],ArrowUp:[0,-1],s:[0,1],S:[0,1],ArrowDown:[0,1],a:[-1,0],A:[-1,0],ArrowLeft:[-1,0],d:[1,0],D:[1,0],ArrowRight:[1,0]}[e.key];if(direction)move(...direction);if(!e.repeat){if(e.key.toLowerCase()==='e')dig();if(e.key.toLowerCase()==='q')sonar();if(e.key.toLowerCase()==='p'||e.key===' ')$('pauseBtn').click()}});window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>{keys={};if(playing&&!paused){$('pauseBtn').click()}});$('mobileDig').onclick=dig;$('mobileSonar').onclick=sonar;document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys[b.dataset.key]=true;b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});let drag=null;$('scene').addEventListener('pointerdown',e=>{drag={x:e.clientX,start:e.clientX};$('scene').setPointerCapture(e.pointerId)});$('scene').addEventListener('pointermove',e=>{if(drag){azimuth-=(e.clientX-drag.x)*.005;drag.x=e.clientX}});$('scene').addEventListener('pointerup',e=>{if(drag&&Math.abs(e.clientX-drag.start)<5&&innerWidth<800)dig();drag=null});$('scene').addEventListener('dblclick',sonar);$('scene').addEventListener('wheel',e=>{e.preventDefault();targetZoom=THREE.MathUtils.clamp(targetZoom+e.deltaY*.001,.65,1.5)},{passive:false});
function resize(){let w=$('world').clientWidth,h=$('world').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('world'));
let loaded=null;try{loaded=JSON.parse(localStorage.getItem('underburrow-save'));if(loaded?.state&&loaded.grid?.length===N&&loaded.state.health>0){state=loaded.state;elapsed=loaded.elapsed||0;$('startBtn').innerHTML='继续探险 <span>↗</span>'}else loaded=null}catch{loaded=null}build(loaded);resize();let last=performance.now();
function animate(now){requestAnimationFrame(animate);let dt=Math.min((now-last)/1000,.05);last=now;const active=playing&&!paused&&!won;if(active){elapsed+=dt;stepCD=Math.max(0,stepCD-dt);sonarCD=Math.max(0,sonarCD-dt);hitCD=Math.max(0,hitCD-dt);state.energy=Math.min(100,state.energy+dt*4);if(keys.w||keys.W||keys.ArrowUp)move(0,-1);else if(keys.s||keys.S||keys.ArrowDown)move(0,1);else if(keys.a||keys.A||keys.ArrowLeft)move(-1,0);else if(keys.d||keys.D||keys.ArrowRight)move(1,0);bugCD-=dt;if(bugCD<=0){bugCD=.65;for(let b of bugs){if(b.stun>0)continue;let dirs=[[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dz])=>grid[b.z+dz]?.[b.x+dx]===0);if(Math.abs(b.x-state.x)+Math.abs(b.z-state.z)<5)dirs.sort((a,c)=>Math.abs(b.x+a[0]-state.x)+Math.abs(b.z+a[1]-state.z)-Math.abs(b.x+c[0]-state.x)-Math.abs(b.z+c[1]-state.z));else dirs.sort(()=>Math.random()-.5);if(dirs[0]){b.x+=dirs[0][0];b.z+=dirs[0][1];b.g.rotation.y=Math.atan2(dirs[0][0],dirs[0][1])}}}for(let b of bugs){b.stun=Math.max(0,b.stun-dt);if(b.x===state.x&&b.z===state.z&&hitCD<=0&&b.stun<=0){state.health=Math.max(0,state.health-17);hitCD=1.7;burst(state.x,state.z,0xeb9978);beep(90,.2);toast('小心甲虫！按 Q 声呐可暂时击晕它们');save();if(state.health<=0)die()}}$('timer').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(Math.floor(elapsed%60)).padStart(2,'0');updateUI();drawMap()}
moveT=Math.min(1,moveT+dt*9);if(moveFrom)mole.position.lerpVectors(moveFrom,new THREE.Vector3(coord(state.x),0,coord(state.z)),moveT);mole.position.y=active&&moveT<1?Math.sin(moveT*Math.PI)*.1:Math.sin(now*.002)*.015;mole.visible=hitCD<=0||Math.floor(now/90)%2===0;for(let b of bugs){b.g.position.x=THREE.MathUtils.lerp(b.g.position.x,coord(b.x),dt*7);b.g.position.z=THREE.MathUtils.lerp(b.g.position.z,coord(b.z),dt*7);b.g.rotation.z=b.stun>0?Math.sin(now*.018)*.3:0}for(let i of items)if(!i.taken&&(i.type==='gem'||i.type==='coin')){i.g.position.y=Math.sin(now*.002+i.x)*.07;i.g.rotation.y+=dt*.8}for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;if(p.ring){p.g.scale.setScalar(1+(2-p.life)*7);p.g.position.y=.25}else{p.v.y-=dt*4;p.g.position.addScaledVector(p.v,dt);p.g.scale.setScalar(Math.max(0,p.life))}if(p.life<=0){world.remove(p.g);particles.splice(i,1)}}zoom=THREE.MathUtils.lerp(zoom,targetZoom,dt*6);let distance=34*zoom*(camera.aspect<1.2?1.22:1);camera.position.set(Math.sin(azimuth)*distance,distance*.86,Math.cos(azimuth)*distance);camera.lookAt(0,-.1,0);renderer.render(scene,camera)}requestAnimationFrame(animate);
// Read-only diagnostics for automated playability checks.
window.__underburrow={get state(){return {...state}},get grid(){return grid.map(r=>[...r])},get items(){return items.map(({type,x,z,taken})=>({type,x,z,taken}))},get playing(){return playing},get paused(){return paused}};
