import {TheatreStage} from './stage.js';
import {TheatreGame,CAST,ACTS} from './game.js';

const $=id=>document.getElementById(id);const $$=s=>[...document.querySelectorAll(s)];
let logs=[{time:'00:00',text:'舞台监督：所有演员已就位，等待开场。'},{time:'00:00',text:'灯光师：月色氛围与追光已准备。'},{time:'00:00',text:'导演提示：先选演员，再点击舞台地面。'}];
let selected=0,stage=null,lastRender=0,lastTime=performance.now(),soundEnabled=false,audioContext=null,visibleIncident=null,modalPaused=false;
let saved;try{saved=JSON.parse(localStorage.getItem('curtain-call-v1')||'{}');}catch{saved={};}let history=Array.isArray(saved.history)?saved.history:[];
const game=new TheatreGame(onGameEvent);game.difficulty=['easy','normal','hard'].includes(saved.difficulty)?saved.difficulty:'normal';
const time=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
function toast(message,warn=false){const div=document.createElement('div');div.className=`toast${warn?' warn':''}`;div.textContent=message;$('toast-container').appendChild(div);setTimeout(()=>div.remove(),3400);}
function persist(){try{localStorage.setItem('curtain-call-v1',JSON.stringify({history:history.slice(0,20),difficulty:game.difficulty}));$('save-status').textContent='本地进度已保存';}catch{$('save-status').textContent='当前浏览器无法保存';}}

function addLog(text,warn=false){logs.unshift({time:time(game.elapsed),text,warn});logs=logs.slice(0,4);renderLog();}
function renderLog(){$('comms-log').innerHTML=logs.map(l=>`<div class="comms-entry ${l.warn?'warn':''}"><time>${l.time}</time><span>${l.text}</span></div>`).join('');}
function buildCast(){$('cast-list').innerHTML=CAST.map((a,i)=>`<button class="cast-card ${i===selected?'active':''}" data-actor="${i}" aria-label="选择${a.name}，${a.role}" style="--actor-color:${a.hex};--avatar-bg:${a.bg}"><span class="avatar"><span>${a.symbol}</span></span><span><strong>${a.name}</strong><small>${a.title} · ${a.role}</small></span><span class="cast-key">${i+1}</span><span class="cast-active">${i===selected?'● 已选中':'在场'}</span></button>`).join('');$$('[data-actor]').forEach(b=>b.onclick=()=>selectActor(+b.dataset.actor));}
function selectActor(i){selected=i;if(stage)stage.selected=i;buildCast();const a=game.actors[i];$('actor-name').textContent=a.name.split('').join('  ');$('actor-role').textContent=`${a.title} · ${a.role}`;$('actor-description').textContent=a.description;$('selected-key').textContent=`快捷键 ${i+1}`;$('walk-button').classList.toggle('active',!a.run);$('run-button').classList.toggle('active',a.run);$('hold-button').classList.remove('active');renderStatus();}
function renderTimeline(){$('timeline').innerHTML=game.cues.map((c,i)=>`<button class="cue-item ${c.type} ${c.status==='done'?'done':''} ${c.status==='missed'?'missed':''}" data-cue="${i}" data-time="${time(c.at)}" title="${c.label}。提示时间前 5 秒可执行，正式演出需要按时完成。"><strong>${c.title}</strong><small>${c.status==='missed'?'错过提示':c.label}</small></button>`).join('');$$('[data-cue]').forEach(b=>b.onclick=()=>{const c=game.cues[+b.dataset.cue];game.cueAction(+b.dataset.cue);if(c.status==='pending'&&game.elapsed<c.at-5)toast(`已准备「${c.title}」，请留意 ${time(c.at)} 的提示窗口`);});}
function renderLabels(){if(!stage)return;$('stage-labels').innerHTML=CAST.map((a,i)=>`<div class="actor-label ${i===selected?'active':''}" id="actor-label-${i}" style="--actor-color:${a.hex}"><i></i>${a.name}</div>`).join('')+stage.marks.map((m,i)=>`<span class="mark-label" id="mark-label-${i}">${m.label}</span>`).join('');}
function resetStage(){logs=[{time:'00:00',text:'舞台监督：新一场演出已准备，等待导演指令。'}];renderLog();$('cue-status').textContent='等待导演发出第一个指令';if(!stage){renderAct();return;}stage.actors=game.actors;stage.setMarks(ACTS[game.act].marks);stage.closed=false;stage.fogOn=false;stage.setScene(game.act);stage.setMood('moon');stage.setIntensity(.75);stage.follow=true;$('light-intensity').value=75;$('intensity-value').textContent='75%';$('fog-button').classList.remove('active');$('fog-button').setAttribute('aria-pressed','false');$('curtain-button').classList.remove('active');$('spotlight-toggle').classList.add('active');$('spotlight-toggle').setAttribute('aria-checked','true');$$('[data-sound]').forEach(b=>b.classList.remove('active'));$('sound-status').textContent='待命';setLight('moon',false);$('incident-host').innerHTML='';$('stage-viewport').querySelector('.act-transition')?.remove();renderAct();selectActor(0);}
function renderAct(){const act=ACTS[game.act];$('scene-label').textContent=`${act.number} · ${act.title}`;$('stage-act-title').textContent=act.title;$('stage-instruction').textContent=game.act===0?'星光落下，故事即将开始。':game.act===1?'每一场风暴，都等待导演的指令。':'让所有相遇，都拥有一个好结局。';$('director-note').textContent=act.note;$('duration').textContent=time(act.duration);if(stage){stage.setMarks(act.marks);stage.setScene(game.act);}renderTimeline();renderLabels();renderStatus();}
function renderStatus(){if(!game)return;const a=game.actors[selected];$('stamina-label').textContent=`${Math.round(a.stamina)}%`;$('stamina-bar').style.width=`${a.stamina}%`;$('stamina-bar').style.background=a.stamina<25?'#d9ac79':'var(--lime)';$('audience-score').innerHTML=`${Math.round(game.audience)}<span>%</span>`;$('audience-mood').textContent=game.audience>=92?'全场沉醉':game.audience>=75?'满怀期待':game.audience>=50?'渐渐分心':'需要挽回';$('combo-label').textContent=game.combo>=2?`${game.combo} 连击 · 调度渐入佳境`:game.started?'观众正在关注舞台':'好戏正在酝酿';$('combo-value').textContent=`×${game.combo}`;$('audience-meter').innerHTML=Array.from({length:24},(_,i)=>`<i class="${i<Math.round(game.audience/100*24)?'on':''}"></i>`).join('');$('timer').textContent=time(game.elapsed);$('act-progress-bar').style.width=`${game.elapsed/ACTS[game.act].duration*100}%`;$('rescue-count').textContent=`${game.rescues} 次机会`;$('rescue-button').disabled=game.rescues<=0;
  $('start-button').innerHTML=game.finished?'<span>↻</span> 再演一场':game.intermission?'<span>▶</span> 继续演出':game.running?'<span>Ⅱ</span> 暂停演出':game.started?'<span>▶</span> 继续演出':`<span>▶</span> 开始${game.mode==='rehearsal'?'排练':'演出'}`;$('mode-label').textContent=game.finished?'已谢幕':game.intermission?'幕间休息':game.running?(game.mode==='rehearsal'?'排练中':'演出中'):game.started?'已暂停':game.mode==='rehearsal'?'排练中':'准备开演';$('mode-dot').style.background=game.running?'#d2ed95':'#9ea98e';$('rehearsal-mode').classList.toggle('active',game.mode==='rehearsal');$('performance-mode').classList.toggle('active',game.mode==='performance');$('next-act-button').textContent=game.act===2?'完成谢幕 ›':'下一幕 ›';$('next-act-button').disabled=game.mode==='performance'&&!game.intermission&&!game.finished;$('speed-button').textContent=`${game.speed}×`;$('cue-count').textContent=`${game.cues.filter(c=>c.status==='done').length} / 5 提示已执行`;
  const current=game.cues.findIndex(c=>c.status==='pending'&&game.elapsed>=c.at-5);$$('[data-cue]').forEach((b,i)=>{b.classList.toggle('current',i===current);b.disabled=game.cues[i].status!=='pending';});if(game.incident){const timer=$('incident-countdown'),bar=$('incident-timer-bar');if(timer)timer.textContent=`${Math.ceil(game.incident.left)}s`;if(bar)bar.style.width=`${game.incident.left/game.incident.duration*100}%`;}
  $('stage-status').textContent=game.hold>0?`场务处理中 · ${Math.ceil(game.hold)}s`:a.moving?`${a.name}正在${a.run?'快跑':'走位'}`:game.running?'演出进行中':game.started?'演出已暂停':'舞台就绪';
}
function onGameEvent(type,data){if(type==='reset')return;switch(type){case 'select':selectActor(data.index);break;case 'mode':resetStage();toast(game.mode==='performance'?'正式演出已准备：按时执行提示，留意突发状况':'已进入自由排练，可自由走位、跳幕练习');break;case 'transport':initAudio();renderStatus();$('footer-tip').textContent=game.running?'演出开始。看时间轴，也别忘了看观众。':'时间已暂停，准备好后继续。';break;case 'move':addLog(`走位指令：${game.actors[data.index].name}正在前往指定位置。`);$('footer-tip').textContent=`已向${game.actors[data.index].name}发出走位指令`;renderLabels();break;case 'cueAction':if(data.cue.type==='lighting')setLight(data.cue.value);else playSound(data.cue.value);break;case 'cueComplete':addLog(`提示完成：${data.cue.title} · +${data.points} 分。`);toast(`✓ ${data.cue.title} · +${data.points}${game.combo>1?' · '+game.combo+' 连击':''}`);$('cue-status').textContent=`${data.cue.title}已完成 · +${data.points}`;renderTimeline();playTone(660,.09,.045);break;case 'cueMissed':addLog(`错过提示：${data.cue.title}，请调整下一条调度。`,true);toast(`错过「${data.cue.title}」· 观众满意度 −7`,true);$('cue-status').textContent=`${data.cue.title}未按时完成`;renderTimeline();break;case 'incident':addLog(`场务呼叫：${data.incident.title}，等待导演处理。`,true);showIncident();playTone(330,.15,.07);break;case 'incidentResolved':addLog(data.succeeded?`已处理：${data.event.title}。`:`即兴失败：${data.event.title}。`,!data.succeeded);$('incident-host').innerHTML='';if(stage)stage.follow=$('spotlight-toggle').classList.contains('active');toast(data.succeeded?`化险为夷！${data.rescue?'锦囊救场':'临场调度'} · +${data.option.points}`:'即兴尝试没有奏效 · 观众满意度 −7',!data.succeeded);$('footer-tip').textContent=data.succeeded?`${data.event.title}已妥善处理`:'稳住节奏，下一次提示还有机会。';renderStatus();break;case 'incidentTimeout':$('incident-host').innerHTML='';if(stage)stage.follow=$('spotlight-toggle').classList.contains('active');toast(game.mode==='performance'?'突发事件未及时处理 · 观众有些失望':'排练提示：突发事件已超时，本次不扣观众分',game.mode==='performance');break;case 'light':setLight(data.value,false);break;case 'set':changeSet();break;case 'actEnd':$('incident-host').innerHTML='';if(stage)stage.closed=true;showIntermission();renderTimeline();break;case 'actStart':if(stage)stage.closed=false;$('stage-viewport').querySelector('.act-transition')?.remove();renderAct();toast(`${ACTS[game.act].number} · ${ACTS[game.act].title}，准备就绪`);break;case 'finish':$('incident-host').innerHTML='';if(stage)stage.closed=false;history.unshift(data.result);persist();showResults(data.result);renderTimeline();playApplause();break;}
}

function showIncident(){const incident=game.incident;if(!incident)return;if(incident.effect==='light'&&stage)stage.follow=false;$('incident-host').innerHTML=`<article class="incident-card"><header><span>ϟ 现场突发状况</span><b id="incident-countdown">${incident.duration}s</b></header><h3>${incident.title}</h3><p>${incident.description}</p>${incident.options.map((o,i)=>`<button data-incident-option="${i}">${o.title}<small>${o.detail}</small></button>`).join('')}<div class="incident-timer"><i id="incident-timer-bar" style="width:100%"></i></div></article>`;$$('[data-incident-option]').forEach(b=>b.onclick=()=>game.resolveIncident(+b.dataset.incidentOption));}
function showIntermission(){const act=ACTS[game.act];$('stage-viewport').querySelector('.act-transition')?.remove();const div=document.createElement('div');div.className='act-transition';div.innerHTML=`<small>INTERMISSION · 幕间休息</small><h2>${act.number}落幕</h2><p>${game.cues.filter(c=>c.status==='done').length} / 5 提示完成 · 当前得分 ${game.score}</p><button id="intermission-next">准备${ACTS[game.act+1].number}</button>`;$('stage-viewport').appendChild(div);$('intermission-next').onclick=()=>game.nextAct();renderStatus();}
function setLight(value,score=true){if(stage)stage.setMood(value);if(score)game.lightAction(value);else game.light=value;$('light-value').textContent={moon:'月色',warm:'暖场',rose:'梦境'}[value];$$('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===value));}
function changeSet(){if(!stage)return;const next=(stage.setIndex+1)%3;stage.setScene(next);$('prop-status').textContent=['森林布景','风暴布景','谢幕布景'][next];toast(`已切换${$('prop-status').textContent}`);}

function initAudio(){if(!soundEnabled)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();}catch{soundEnabled=false;toast('当前浏览器暂不支持声音，仍可正常完成音效提示',true);}}
function playTone(frequency,duration=.3,volume=.1,offset=0,type='sine'){if(!soundEnabled)return;initAudio();if(!audioContext)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain(),start=audioContext.currentTime+offset;osc.type=type;osc.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.02);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start);osc.stop(start+duration+.02);}
function noise(duration,volume,filterFreq){if(!soundEnabled)return;initAudio();if(!audioContext)return;const buffer=audioContext.createBuffer(1,audioContext.sampleRate*duration,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1);const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=filterFreq;gain.gain.setValueAtTime(.001,audioContext.currentTime);gain.gain.linearRampToValueAtTime(volume,audioContext.currentTime+.25);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);source.connect(filter);filter.connect(gain);gain.connect(audioContext.destination);source.start();}
function playSound(value){initAudio();game.soundAction(value);$$('[data-sound]').forEach(b=>b.classList.toggle('active',b.dataset.sound===value));$('sound-status').textContent={forest:'林间风声',chime:'精灵铃声',thunder:'雷雨音效'}[value];if(value==='chime'){[523.25,659.25,783.99,1046.5].forEach((f,i)=>playTone(f,1.4,.11,i*.22));}else if(value==='thunder'){noise(2.3,.45,230);playTone(42,1.7,.22);}else{noise(4,.15,750);[1500,1870,1400].forEach((f,i)=>playTone(f,.16,.025,i*.65));}if(!soundEnabled)toast('音效指令已执行 · 右上角 ♪ 可打开声音');}
function playApplause(){noise(3,.12,3600);[523,659,783].forEach((f,i)=>playTone(f,1,.09,i*.12));}

function openModal(html,bind){modalPaused=game.running;if(modalPaused){game.running=false;renderStatus();}$('modal-content').innerHTML=html;$('modal').showModal();if(bind)bind();}
function closeModal(){$('modal').close();if(modalPaused&&!game.finished&&!game.intermission){game.running=true;modalPaused=false;renderStatus();}}
function showGuide(){openModal(`<div class="modal-eyebrow">A DIRECTOR'S HANDBOOK</div><h2 class="modal-title">聚光灯下，由你掌舵。</h2><p class="modal-description">你是环球剧院今晚的导演。让四位演员找到自己的位置，在恰当的时刻点亮舞台，把每次意外变成好戏。</p><div class="guide-grid"><div class="guide-item"><strong>01 / 安排走位</strong><p>点击演员卡或按 1–4 选人，再点击舞台地面。按 M 可前往当前剧本标记。拖动旋转视角，滚轮缩放。</p></div><div class="guide-item"><strong>02 / 跟随提示</strong><p>时间轴会提示走位、灯光与音效。提前 5 秒可以执行，连续完成会提高得分。点击提示卡即可发出相应指令。</p></div><div class="guide-item"><strong>03 / 应对意外</strong><p>演出中会出现 8 类突发事件。选择稳妥处理，或明确概率的即兴方案。按 R 可消耗一次导演锦囊直接救场。</p></div><div class="guide-item"><strong>04 / 赢得掌声</strong><p>自由排练可以跳幕，超时不扣观众分。正式演出按时完成三幕，争取 S 级评价。空格暂停，帮助窗口也会暂停。</p></div></div><button class="modal-primary" id="guide-done">回到导演席</button>`,()=>{$('guide-done').onclick=closeModal;});}
function showScript(){openModal(`<div class="modal-eyebrow">TONIGHT'S PRODUCTION</div><h2 class="modal-title">仲夏夜之梦</h2><p class="modal-description">根据莎士比亚同名作品改编的三幕舞台练习。每幕 75 秒，幕间可休息。正式演出共 15 条提示，6 次现场挑战。</p>${ACTS.map((a,i)=>`<section class="script-act"><small>${a.en} · 75 SEC</small><h3>${a.number} · ${a.title}</h3><p>${a.description}</p><p>灯光：${{moon:'月色',rose:'梦境',warm:'暖场'}[a.light]}　音效：${{forest:'林间风声',thunder:'雷雨音效',chime:'精灵铃声'}[a.sound]}</p><small>${a.cues.map(c=>`${time(c.at)} ${c.title}`).join(' · ')}</small></section>`).join('')}<button class="modal-primary" id="script-done">记住了，回到舞台</button>`,()=>{$('script-done').onclick=closeModal;});}
function showRecords(){openModal(`<div class="modal-eyebrow">THE PERFORMANCE ARCHIVE</div><h2 class="modal-title">每一场，都值得记住。</h2><p class="modal-description">最近 20 场完整演出保存在当前浏览器。</p>${history.length?history.map(r=>`<div class="history-entry"><b>${r.grade}</b><div><strong>${r.title}</strong><small>${new Date(r.date).toLocaleDateString('zh-CN')} · ${r.mode==='rehearsal'?'自由排练':'正式演出'} · 完成率 ${r.accuracy}%</small></div><span>${r.score}</span></div>`).join(''):'<div class="empty-records">舞台已经准备好了。<br>完成三幕演出，留下你的第一张成绩单。</div>'}<button class="modal-primary" id="records-done">回到舞台</button>`,()=>{$('records-done').onclick=closeModal;});}
function showSettings(){openModal(`<div class="modal-eyebrow">DIRECTOR'S PREFERENCES</div><h2 class="modal-title">演出设置</h2><p class="modal-description">让节奏适合你。难度影响技术提示的容错时间和现场意外的处理时间。</p><label class="setting-row"><span>导演难度</span><select id="difficulty-select"><option value="easy">从容 · 24 秒处理意外</option><option value="normal">标准 · 18 秒处理意外</option><option value="hard">挑战 · 12 秒处理意外</option></select></label><div class="setting-row"><span>演出声音</span><button id="settings-sound" class="outline-button">${soundEnabled?'已开启 · 点击静音':'已静音 · 点击开启'}</button></div><p class="modal-description" style="margin-top:20px">本游戏为单机体验。演出档案保存在当前浏览器，清除浏览器数据会移除档案。</p><button class="modal-primary" id="settings-done">保存并返回</button>`,()=>{$('difficulty-select').value=game.difficulty;$('difficulty-select').onchange=e=>{game.difficulty=e.target.value;persist();};$('settings-sound').onclick=()=>{toggleSound();$('settings-sound').textContent=soundEnabled?'已开启 · 点击静音':'已静音 · 点击开启';};$('settings-done').onclick=closeModal;});}
function showResults(result){const stars=result.grade==='S'?'✦ ✦ ✦':result.grade==='A'?'✦ ✦':'✦';openModal(`<div class="modal-eyebrow">THE FINAL CURTAIN · ${game.mode==='rehearsal'?'REHEARSAL':'PERFORMANCE'}</div><h2 class="modal-title">${result.title}</h2><div class="score-hero"><div class="score-grade">${result.grade}</div><div><h3>${stars}</h3><p>导演总分 ${result.score.toLocaleString()} · 最高 ${result.bestCombo} 连击</p></div></div><div class="score-metrics"><div><b>${result.accuracy}%</b><small>提示完成率</small></div><div><b>${result.audience}%</b><small>观众满意度</small></div><div><b>${result.resolved}/${result.incidentCount}</b><small>意外成功处理</small></div></div><p class="modal-description" style="margin-top:22px">${result.grade==='S'?'你把每个走位、每束光和每次意外编排成了一场完整的梦。':result.grade==='A'?'观众记住了这个夜晚。把握技术提示的时间，下次向 S 级发起挑战。':'走位可以提前准备，灯光要留意亮度。善用暂停、标记点与导演锦囊，再来一次。'}</p><button class="modal-primary" id="results-again">再导一场</button>`,()=>{$('results-again').onclick=()=>{modalPaused=false;closeModal();game.reset();resetStage();};});}
function toggleSound(){soundEnabled=!soundEnabled;initAudio();$('sound-button').textContent=soundEnabled?'♫':'♪';$('sound-button').style.color=soundEnabled?'var(--lime)':'';$('sound-button').setAttribute('aria-label',soundEnabled?'关闭声音':'打开声音');if(soundEnabled)playTone(523,.3,.06);else if(audioContext)audioContext.suspend();}

function bindControls(){
 $('start-button').onclick=()=>{if(game.finished){game.reset();resetStage();}game.toggle();};$('restart-button').onclick=()=>{if(!game.started){game.reset();resetStage();toast('排练已重置');return;}openModal('<div class="modal-eyebrow">A FRESH TAKE</div><h2 class="modal-title">重新开场？</h2><p class="modal-description">这场尚未完成的演出将重新开始。已保存的演出档案会保留。</p><button class="modal-primary" id="confirm-restart">重新开场</button>',()=>{$('confirm-restart').onclick=()=>{modalPaused=false;closeModal();game.reset();resetStage();toast('已回到第一幕');};});};
 $('rehearsal-mode').onclick=()=>game.setMode('rehearsal');$('performance-mode').onclick=()=>game.setMode('performance');$('speed-button').onclick=()=>{game.speed=game.speed===1?1.5:game.speed===1.5?2:1;renderStatus();toast(`演出速度 ${game.speed}×`);};$('next-act-button').onclick=()=>{if(game.finished){showResults(game.result());return;}if(game.intermission)game.nextAct();else if(game.mode==='rehearsal'){game.endAct();}};
 $('walk-button').onclick=()=>{game.actors[selected].run=false;selectActor(selected);};$('run-button').onclick=()=>{game.actors[selected].run=true;selectActor(selected);toast('快跑会消耗更多体力');};$('hold-button').onclick=()=>{const a=game.actors[selected];a.tx=a.x;a.tz=a.z;a.moving=false;$('hold-button').classList.add('active');toast(`${a.name}原地待命`);};$('mark-button').onclick=()=>game.mark(selected);
 $$('[data-light]').forEach(b=>b.onclick=()=>setLight(b.dataset.light));$('light-intensity').oninput=e=>{game.intensity=+e.target.value/100;stage?.setIntensity(game.intensity);$('intensity-value').textContent=`${e.target.value}%`;game.checkCues();};$('spotlight-toggle').onclick=()=>{if(!stage)return;stage.follow=!stage.follow;$('spotlight-toggle').classList.toggle('active',stage.follow);$('spotlight-toggle').setAttribute('aria-checked',String(stage.follow));};$$('[data-sound]').forEach(b=>b.onclick=()=>playSound(b.dataset.sound));$('fog-button').onclick=()=>{if(!stage)return;stage.fogOn=!stage.fogOn;$('fog-button').classList.toggle('active',stage.fogOn);$('fog-button').setAttribute('aria-pressed',String(stage.fogOn));};$('set-button').onclick=changeSet;$('curtain-button').onclick=()=>{if(!stage)return;stage.closed=!stage.closed;$('curtain-button').classList.toggle('active',stage.closed);toast(stage.closed?'幕布正在合拢':'幕布正在拉开');};
 ['orbit','front','top'].forEach(view=>$(`camera-${view}`).onclick=()=>{stage?.setView(view);['orbit','front','top'].forEach(v=>$(`camera-${v}`).classList.toggle('active',v===view));});$('grid-button').onclick=()=>{if(!stage)return;stage.setGrid(!stage.gridVisible);$('grid-button').classList.toggle('active',stage.gridVisible);};$('fullscreen-button').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('stage-viewport').requestFullscreen();}catch{toast('当前浏览器不支持全屏模式',true);}};
 $('rescue-button').onclick=()=>{if(!game.incident){toast('当前没有突发状况，把锦囊留到关键时刻');return;}game.resolveIncident(0,true);};$('sound-button').onclick=toggleSound;$('help-button').onclick=showGuide;$('settings-button').onclick=showSettings;$('show-script').onclick=showScript;$('timeline-help').onclick=showScript;$$('[data-tab]').forEach(b=>b.onclick=()=>b.dataset.tab==='script'?showScript():b.dataset.tab==='records'?showRecords():toast('你已在导演控制台'));
 document.querySelector('.modal-close').onclick=closeModal;$('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
 document.addEventListener('keydown',e=>{if($('modal').open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('start-button').click();}if(/^[1-4]$/.test(e.key))selectActor(+e.key-1);if(e.key.toLowerCase()==='m')game.mark(selected);if(e.key.toLowerCase()==='r')$('rescue-button').click();if(e.key==='?')showGuide();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.running){game.running=false;renderStatus();toast('离开导演席，演出已自动暂停');}});
}

try{stage=new TheatreStage($('stage-canvas'),game.actors,selectActor,(x,z)=>game.move(selected,x,z));$('stage-loading').remove();}catch(error){console.error(error);$('stage-loading').innerHTML='<strong>3D 舞台无法启动，请开启浏览器硬件加速后刷新。</strong>';}
buildCast();renderAct();selectActor(0);bindControls();persist();renderLog();
if(stage){stage.setMarks(ACTS[0].marks);renderLabels();}
function frame(now){const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;game.update(dt);if(stage){stage.update(dt,game.started&&!game.running);game.actors.forEach((a,i)=>{const p=stage.project(a.x,2.23,a.z),label=$(`actor-label-${i}`);if(label){label.style.left=`${p.x}px`;label.style.top=`${p.y}px`;label.classList.toggle('active',i===selected);label.style.display=p.visible?'flex':'none';}});stage.marks.forEach((m,i)=>{const p=stage.project(m.x,.2,m.z),label=$(`mark-label-${i}`);if(label){label.style.left=`${p.x}px`;label.style.top=`${p.y}px`;label.style.display=stage.gridVisible?'block':'none';}});}if(now-lastRender>150){renderStatus();lastRender=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
