import * as THREE from 'three';
const $=id=>document.getElementById(id);
const container=$('scene'),scene=new THREE.Scene();
scene.background=new THREE.Color('#e8ece0');scene.fog=new THREE.Fog('#e8ece0',48,100);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;container.appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-20,20,12,-12,.1,150);const target=new THREE.Vector3(0,0,0);let angle=.72;
scene.add(new THREE.HemisphereLight(0xfff9e8,0x819875,2.5));const sun=new THREE.DirectionalLight(0xfff3db,4);sun.position.set(-12,25,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.5,far:70});sun.shadow.normalBias=.035;scene.add(sun);
const house=new THREE.Group();scene.add(house);const colliders=[],stars=[],spinners=[],particles=[];
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.65,...extra});const palette={wood:mat('#d6af81'),edge:mat('#ead0a4'),cream:mat('#fff5dd'),mint:mat('#97bba7'),pink:mat('#dfaa98'),blue:mat('#9aafbb'),yellow:mat('#e7bd67'),green:mat('#829b66'),white:mat('#fffaf0')};
function box(x,y,z,w,h,d,m,solid=false,parent=house){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof m==='string'?mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);if(solid)colliders.push({x,z,w:w/2+.3,d:d/2+.3,h:y+h/2});return o;}
function cylinder(x,y,z,r,h,m,parent=house){let o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,40),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function sphere(x,y,z,r,m,parent=house){let o=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o;}
function torus(x,y,z,r,t,m,rx=0,parent=house){const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,10,48),m);o.position.set(x,y,z);o.rotation.x=rx;parent.add(o);return o;}
function textLabel(text,x,y,z,color='#7b6650',size=128){const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font=`bold ${size}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,132);const tex=new THREE.CanvasTexture(c);const o=new THREE.Mesh(new THREE.PlaneGeometry(.85,.85),new THREE.MeshBasicMaterial({map:tex,transparent:true}));o.position.set(x,y,z);house.add(o);return o;}
// A real, open-front dollhouse, built entirely from three-dimensional toys.
box(0,-.72,0,23,.8,17,palette.edge);box(0,-.27,0,22.7,.15,16.7,palette.wood);
for(let i=0;i<28;i++){let x=-10.95+i*.8;box(x,-.17,0,.016,.015,16.4,'#bd966f');for(let j=0;j<3;j++)box(x+.39,-.165,-7+j*5+(i%2)*2.3,.77,.012,.015,'#c29d77');}
box(0,2.25,-8.2,23,5,.28,palette.mint,true);box(-11.35,1.45,0,.28,3.2,16.7,palette.cream,true);box(11.35,.27,0,.28,.65,16.7,palette.cream,true);box(0,.12,8.25,23,.4,.28,palette.cream,true);
box(0,4.77,-8.2,23.6,.25,.55,palette.white);box(-11.35,3.09,0,.5,.2,17.2,palette.white);box(0,.15,-7.97,22.7,.25,.14,palette.white);
// Back wall wallpaper, windows and bunting.
for(let x=-10.5;x<11;x+=.8)box(x,2.45,-8.025,.025,4.3,.02,'#bdd0b7');
for(const x of [-6.8,6.5]){box(x,2.9,-7.96,2.9,2.4,.12,palette.white);box(x,2.9,-7.86,2.55,2.08,.1,'#c0dce0');box(x,2.9,-7.77,.11,2.08,.12,palette.white);box(x,2.9,-7.77,2.55,.1,.12,palette.white);box(x,1.66,-7.65,3.2,.15,.55,palette.white);}
for(let i=0;i<14;i++){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([-.24,0,0,.24,0,0,0,-.48,0],3));geo.computeVertexNormals();const f=new THREE.Mesh(geo,mat(['#e8c274','#f1e3c6','#bb9790','#90b7b2'][i%4],{side:THREE.DoubleSide}));f.position.set(-5.2+i*.79,4.05-Math.sin(i/13*Math.PI)*.52,-7.8);house.add(f);}
// Interior partition walls with wide marble doorways.
box(-2.8,.75,-6.3,.2,1.7,3.7,palette.cream,true);box(-2.8,.75,-.75,.2,1.7,3.4,palette.cream,true);box(3.4,.75,-6.35,.2,1.7,3.7,palette.pink,true);box(3.4,.75,-.8,.2,1.7,3.3,palette.pink,true);
box(-8.85,.65,1.0,4.8,1.5,.2,palette.cream,true);box(-1.5,.65,1,4.1,1.5,.2,palette.cream,true);box(8.2,.65,1,6.2,1.5,.2,palette.cream,true);
// Playroom: woven circular rug, miniature bed, railway, alphabet blocks.
cylinder(-7.0,-.09,-2.9,2.3,.05,mat('#bac4ad'));for(let r=.4;r<2.3;r+=.25)torus(-7,-.045,-2.9,r,.015,mat('#d4d6b9'),Math.PI/2);
box(-9.35,.48,-5.7,2.8,.75,3.1,palette.edge,true);box(-9.35,.96,-5.6,2.7,.32,2.9,palette.white);box(-9.35,1.15,-5.15,2.72,.2,1.9,palette.pink);box(-9.35,1.2,-6.55,2.15,.25,.65,palette.cream);box(-9.35,1.3,-7.1,2.95,1,.18,palette.edge);for(let i=0;i<7;i++)box(-10.5+i*.38,1.22,-5.2,.035,.025,1.8,'#e9c2ac');
function block(x,z,color,letter,y=.42){box(x,y,z,.85,.85,.85,mat(color),true);box(x,y,z+.431,.7,.7,.02,palette.edge);textLabel(letter,x,y,z+.45);}
block(-5.1,-6.1,'#a1b8aa','A');block(-4.15,-6,'#deb17d','B');block(-4.7,-6.1,'#c8917d','C',1.27);block(-8.8,-.25,'#a8b6bd','D');
// Tiny locomotive.
box(-6.6,.25,-.7,1.5,.35,.6,palette.green);box(-6.2,.65,-.7,.65,.65,.6,palette.pink);cylinder(-7,.65,-.7,.16,.5,palette.wood);for(let x of [-7.05,-6.2])for(let z of [-1.03,-.38]){let wh=cylinder(x,.18,z,.24,.12,palette.wood);wh.rotation.x=Math.PI/2;}
// Central living room and little arched tunnel.
box(.3,-.06,-3.8,4.1,.055,4.6,mat('#d7b998'));for(let i=0;i<6;i++)box(-1.6+i*.7,-.02,-3.8,.035,.02,4.4,'#e9d5b6');
box(.3,.45,-6.4,3.6,.7,1.1,palette.mint,true);box(.3,1.0,-6.87,3.6,.8,.3,palette.mint);for(let x of [-1.4,2])box(x,.8,-6.4,.25,.7,1.2,palette.mint);box(-.5,.92,-6.35,.8,.4,.6,palette.cream);box(.7,.92,-6.35,.75,.4,.6,palette.pink);
cylinder(.3,.45,-4.4,.9,.13,palette.edge);for(let x of [-.2,.8])box(x,.18,-4.4,.09,.5,.09,palette.wood);cylinder(.3,.57,-4.4,.2,.13,palette.white);sphere(.3,.76,-4.4,.17,palette.green);
// Stacking rainbow toy, a recognizable tiny landmark.
for(let i=0;i<5;i++){const arch=new THREE.Mesh(new THREE.TorusGeometry(1.25-i*.2,.12,10,40,Math.PI),mat(['#bc8675','#d49d74','#e2be7e','#b8c3a1','#86a899'][i]));arch.position.set(.25,.08,-1.0);house.add(arch);}box(-1.06,.18,-1,.24,.5,.55,palette.edge);box(1.56,.18,-1,.24,.5,.55,palette.edge);
// Kitchen: terrazzo floor and fitted cabinetry.
box(7.3,-.1,-3.65,7.5,.1,8.1,'#ebddc2');for(let x=4;x<11;x+=.85)for(let z=-7.5;z<.8;z+=.85)box(x,-.039,z,.42,.025,.42,((Math.round(x*10)+Math.round(z*10))%3===0)?'#a8b8a4':'#e1cfac');
box(7.2,.65,-7.1,6.6,1.4,1.55,palette.cream,true);box(7.2,1.4,-7.1,6.9,.16,1.7,palette.edge);for(let x=4.6;x<10.4;x+=1.3){box(x,.65,-6.3,1.15,1.1,.055,palette.mint);box(x,.95,-6.25,.35,.045,.07,palette.wood);}box(9.2,1.5,-7.1,1.4,.08,1.1,'#e9e6d5');for(let x of [8.9,9.5])for(let z of [-7.4,-6.9])torus(x,1.57,z,.18,.035,palette.wood,Math.PI/2);
cylinder(6.8,.75,-3.4,1.2,.16,palette.edge);for(let x of [6,7.6])for(let z of [-4.1,-2.7])box(x,.33,z,.13,.8,.13,palette.wood);cylinder(6.8,.89,-3.4,.37,.1,palette.white);sphere(6.8,1.08,-3.4,.23,palette.pink);for(let z of [-5,-1.8]){box(6.8,.35,z,.8,.14,.7,palette.mint);box(6.8,.78,z+(z<-3?-.3:.3),.8,.8,.12,palette.mint);}
// Garden, picket fence and flower beds.
box(3.8,-.07,4.55,14.6,.11,6.7,mat('#a9bc88'));for(let i=0;i<12;i++)box(10.8,.4,1.5+i*.56,.15,1,.15,palette.cream);box(10.8,.5,4.5,.15,.12,6.7,palette.cream);
for(const [x,z] of [[8.8,6.3],[9.2,2.2],[-1.8,6.8]]){cylinder(x,.27,z,.54,.7,palette.pink);sphere(x,1.14,z,.83,palette.green);sphere(x-.3,1.65,z,.55,palette.green);for(let i=0;i<4;i++)sphere(x+Math.cos(i*2)*.65,1.1,z+Math.sin(i*2)*.5,.13,palette.cream);}
for(let i=0;i<12;i++){const x=-1.2+i*.84,z=3.2+Math.sin(i*.6)*.65;const p=cylinder(x,-.005,z,.37,.08,mat('#e7dcc3'));p.scale.z=.7;}
// Toy race track, launch strip, bridge and flags.
box(-7,.02,4.9,7.5,.16,2.1,palette.edge);box(-7,.13,4.9,7.5,.045,1.45,'#d3b18a');for(let x=-10.6;x<-3.5;x+=.5)box(x,.17,4.9,.25,.02,.04,palette.cream);box(-7,.25,3.9,7.5,.3,.12,palette.pink);box(-7,.25,5.9,7.5,.3,.12,palette.pink);
for(let i=0;i<3;i++){const o=box(-8.7+i*.4,.17,4.9,.2,.035,1.1,'#e5a45e');o.rotation.y=-.3;}
const checkpoints=[{x:-5.4,z:2.2},{x:4.5,z:2.2}];checkpoints.forEach(p=>{cylinder(p.x,.6,p.z,.035,1.3,palette.cream);box(p.x+.25,1.08,p.z,.48,.34,.04,palette.mint);torus(p.x,.015,p.z,.5,.035,palette.mint,Math.PI/2);});
function spinner(x,z){const group=new THREE.Group();group.position.set(x,.5,z);house.add(group);box(0,0,0,2.5,.23,.3,palette.pink,false,group);box(0,0,0,.3,.23,2.5,palette.yellow,false,group);cylinder(x,.38,z,.2,.85,palette.white);sphere(x,.87,z,.25,palette.wood);spinners.push(group);}spinner(-3.6,4.8);spinner(4.1,4.6);
const portal=torus(7.3,1.0,5.5,.9,.13,mat('#f4cf70',{emissive:'#e3a631',emissiveIntensity:.25}));box(7.3,.05,5.5,2,.18,1.1,palette.edge);for(let i=0;i<7;i++){const o=box(6.5+i*.26,.155,5.45,.13,.02,.75,i%2?'#faf4dc':'#638f77');}
// Stars are extruded, so they remain clearly visible from every view.
const shape=new THREE.Shape();for(let i=0;i<10;i++){const a=Math.PI/2+i*Math.PI/5,r=i%2?.19:.39;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?shape.lineTo(x,y):shape.moveTo(x,y);}shape.closePath();const starGeo=new THREE.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:true,bevelThickness:.04,bevelSize:.025,bevelSegments:2,steps:1});
const starPositions=[[-7,-3.6],[-4.4,-3.2],[.2,-2.7],[2,-5.2],[4.5,-4.7],[9,-3],[9.6,-.1],[6.5,2.6],[1.7,3.7],[-3,2.2],[-9,4.9],[-6.2,6.7]];
starPositions.forEach(([x,z],i)=>{const mesh=new THREE.Mesh(starGeo,mat('#f0c565',{metalness:.35,roughness:.25,emissive:'#b47f20',emissiveIntensity:.13}));mesh.position.set(x,.82,z);mesh.castShadow=true;house.add(mesh);stars.push({mesh,x,z,collected:false,phase:i});});
// A few toys outside the house give the model a handmade diorama setting.
const ground=box(0,-1.2,0,200,.15,200,mat('#e8ece0'),false,scene);
for(const [x,z,c] of [[-13,5,'#e2bf87'],[12,5,'#c4917d'],[11,10,'#95ada1']]){const b=box(x,-.65,z,.7,.8,.7,c,false,scene);b.rotation.y=.25;}
const marble=new THREE.Group();house.add(marble);const ball=sphere(0,0,0,.34,mat('#70a994',{metalness:.38,roughness:.13} ),marble);torus(0,0,0,.329,.025,mat('#e6f3d8'),.65,marble);torus(0,0,0,.33,.018,mat('#c6e0b4'),1.12,marble);sphere(-.11,.16,.23,.08,mat('#ffffff',{roughness:.05}),marble);
const pos=new THREE.Vector3(-7,.35,-3.6),vel=new THREE.Vector3();let vy=0,jump=0,started=false,paused=false,finished=false,elapsed=0,collected=0,level=0,timeTrial=false,sound=false,checkpoint={x:-7,z:-3.6},lastCheckpoint=-1,toastTimeout=0,rotating=false;const keys={};marble.position.copy(pos);
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);const ratio=w/h;const size=ratio<1.3?18:13.6;camera.left=-size*ratio;camera.right=size*ratio;camera.top=size;camera.bottom=-size;camera.updateProjectionMatrix();}
function placeCamera(){const wide=container.clientWidth/container.clientHeight>1.5;target.set(wide?-3.7:0,0,0);camera.position.set(target.x+Math.sin(angle)*30,27,target.z+Math.cos(angle)*30);camera.lookAt(target);}
new ResizeObserver(()=>{resize();placeCamera();}).observe(container);resize();placeCamera();
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('show'),2800);}
let audio;function tone(freq=660,duration=.14){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.5,audio.currentTime+duration);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function fmt(n){return `${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;}
function loadBest(){try{const b=localStorage.getItem('marble-house-best-'+level+(timeTrial?'-trial':''));$('best').textContent=b?fmt(+b):'— —';}catch{}}
function reset(auto=false){started=auto;paused=false;finished=false;elapsed=0;collected=0;jump=0;vy=0;vel.set(0,0,0);checkpoint={x:-7,z:-3.6};lastCheckpoint=-1;pos.set(-7,.35,-3.6);stars.forEach(s=>{s.collected=false;s.mesh.visible=true;});$('score').textContent='0';$('timer').textContent=timeTrial?'01:30':'00:00';$('paused').classList.add('hidden');$('startBtn').innerHTML=auto?'Pause <span>Ⅱ</span>':"Let's roll <span>↗</span>";$('startMarker').classList.toggle('hidden',auto);document.body.classList.toggle('playing',auto);loadBest();}
function start(){if(!started){started=true;document.body.classList.add('playing');$('startMarker').classList.add('hidden');$('startBtn').innerHTML='Pause <span>Ⅱ</span>';toast('Your adventure starts here. Follow the golden stars!');tone(440);}else togglePause();}
function togglePause(){if(!started||finished)return;paused=!paused;$('paused').classList.toggle('hidden',!paused);$('startBtn').innerHTML=paused?'Resume <span>▶</span>':'Pause <span>Ⅱ</span>';Object.keys(keys).forEach(k=>keys[k]=false);}
function finish(won){finished=true;started=false;document.body.classList.remove('playing');$('resultEyebrow').textContent=won?'A LITTLE VICTORY':'ANOTHER LITTLE ADVENTURE?';$('resultTitle').textContent=won?'Home, sweet home.':'Time flew by.';$('resultText').textContent=won?`All 12 stars, a house full of memories. You made it home in ${fmt(elapsed)}.`:`You found ${collected} of 12 stars. Take another roll, or explore at your own pace in Free roam.`;if(won){try{const key='marble-house-best-'+level+(timeTrial?'-trial':''),b=localStorage.getItem(key);if(!b||elapsed<+b)localStorage.setItem(key,String(elapsed));}catch{}loadBest();tone(880,.4);}$('winDialog').showModal();$('startBtn').innerHTML="Let's roll <span>↗</span>";}
function burst(x,y,z){for(let i=0;i<12;i++){const p=sphere(x,y,z,.055,palette.yellow);particles.push({mesh:p,v:new THREE.Vector3((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:.7});}}
function update(dt,t){stars.forEach(s=>{s.mesh.rotation.y=t*.8+s.phase;s.mesh.position.y=.85+Math.sin(t*2+s.phase)*.13;});spinners.forEach((s,i)=>s.rotation.y=t*(.65+level*.3)*(i?1:-1));portal.material.emissiveIntensity=.25+Math.sin(t*2)*.12;
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=5*dt;p.mesh.position.addScaledVector(p.v,dt);p.mesh.scale.setScalar(Math.max(0,p.life/.7));if(p.life<0){house.remove(p.mesh);p.mesh.geometry.dispose();particles.splice(i,1);}}
if(rotating){angle+=dt*.3;placeCamera();}if(!started||paused||finished)return;elapsed+=dt;$('timer').textContent=fmt(timeTrial?Math.max(0,90-elapsed):elapsed);if(timeTrial&&elapsed>=90){finish(false);return;}
let dx=Number(!!(keys.d||keys.arrowright))-Number(!!(keys.a||keys.arrowleft)),dz=Number(!!(keys.s||keys.arrowdown))-Number(!!(keys.w||keys.arrowup));const input=new THREE.Vector3(dx,0,dz);if(input.lengthSq()){input.normalize();const c=Math.cos(angle),s=Math.sin(angle);const ix=input.x*c+input.z*s,iz=-input.x*s+input.z*c;vel.x+=ix*12*dt;vel.z+=iz*12*dt;}vel.multiplyScalar(Math.exp(-(keys.shift?10:2.8)*dt));if(vel.length()>5.5)vel.setLength(5.5);
if(keys[' ']&&jump===0){vy=4.6;jump=.001;tone(300,.1);}vy-=12*dt;jump=Math.max(0,jump+vy*dt);if(jump===0)vy=0;
const oldX=pos.x,oldZ=pos.z;pos.x+=vel.x*dt;pos.z+=vel.z*dt;for(const c of colliders){if(jump+.4>c.h+.25)continue;if(Math.abs(pos.x-c.x)<c.w&&Math.abs(pos.z-c.z)<c.d){if(Math.abs(oldX-c.x)>=c.w){pos.x=oldX;vel.x*=-.4;}else if(Math.abs(oldZ-c.z)>=c.d){pos.z=oldZ;vel.z*=-.4;}else {const px=c.w-Math.abs(pos.x-c.x),pz=c.d-Math.abs(pos.z-c.z);if(px<pz){pos.x=c.x+(pos.x>=c.x?1:-1)*(c.w+.01);vel.x=0;}else{pos.z=c.z+(pos.z>=c.z?1:-1)*(c.d+.01);vel.z=0;}}}}
if(Math.abs(pos.x)>11||Math.abs(pos.z)>8){pos.x=THREE.MathUtils.clamp(pos.x,-11,11);pos.z=THREE.MathUtils.clamp(pos.z,-8,8);vel.multiplyScalar(-.4);}
if(pos.x<-7.8&&pos.x>-9.5&&Math.abs(pos.z-4.9)<.7){vel.x+=16*dt;if(Math.random()<.04)tone(450,.1);}
spinners.forEach(s=>{const diff=new THREE.Vector3(pos.x-s.position.x,0,pos.z-s.position.z);if(diff.length()<1.5&&jump<.7){const a=Math.atan2(diff.z,diff.x)+s.rotation.y;if(Math.abs(Math.sin(a*2))<.3){diff.normalize();vel.addScaledVector(diff,8*dt*10);tone(190,.08);}}});
checkpoints.forEach((p,i)=>{if(Math.hypot(pos.x-p.x,pos.z-p.z)<.65&&lastCheckpoint!==i){lastCheckpoint=i;checkpoint=p;toast('Checkpoint saved. A little closer to home.');tone(520);}});
stars.forEach(s=>{if(!s.collected&&Math.hypot(pos.x-s.x,pos.z-s.z)<.7){s.collected=true;s.mesh.visible=false;collected++;$('score').textContent=collected;burst(s.x,.8,s.z);tone(540+collected*35);if(collected===12)toast('Every star is yours! Find the golden garden portal.');}});
if(Math.hypot(pos.x-7.3,pos.z-5.5)<.9){if(collected===12)finish(true);else if(!portal.userData.hint||t-portal.userData.hint>4){toast(`${12-collected} more stars to find. The house is full of surprises.`);portal.userData.hint=t;}}
pos.y=.35+jump+(pos.x<-3.3&&pos.x>-10.8&&Math.abs(pos.z-4.9)<1?.16:0);marble.position.copy(pos);ball.rotation.z-=vel.x*dt*2;ball.rotation.x+=vel.z*dt*2;
}
let prev=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-prev)/1000,.033);prev=now;update(dt,now/1000);if(!started)marble.position.copy(pos);if(!started){const projected=pos.clone().add(new THREE.Vector3(0,1,0)).project(camera);$('startMarker').style.left=((projected.x*.5+.5)*container.clientWidth-52)+'px';$('startMarker').style.top=((-projected.y*.5+.5)*container.clientHeight-50)+'px';}renderer.render(scene,camera);});
$('startBtn').onclick=start;$('resumeBtn').onclick=togglePause;$('cameraBtn').onclick=()=>{rotating=!rotating;$('cameraBtn').style.background=rotating?'#cadbc2':'';toast(rotating?'Taking a look around. Click again to hold the view.':'View locked. Ready to roll.');};$('fullBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.game-shell').requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'♫':'♪';$('soundBtn').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('soundBtn').style.background=sound?'#dce8d5':'';tone();toast(sound?'Little sounds are on':'Sound is off');};
function openDialog(id){if(started&&!paused)togglePause();$(id).showModal();} $('howBtn').onclick=()=>openDialog('helpDialog');$('levelsBtn').onclick=()=>openDialog('levelsDialog');$('gotIt').onclick=()=>$('helpDialog').close();document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('againBtn').onclick=()=>{$('winDialog').close();reset(true);};
$('modeBtn').onclick=()=>{timeTrial=!timeTrial;$('modeBtn').innerHTML=`<i></i> ${timeTrial?'Time trial':'Free roam'} <span>⌄</span>`;reset(false);toast(timeTrial?'90 seconds. 12 stars. One little adventure.':'No rush. The whole house is yours.');};
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=+b.dataset.level;const names=['THE TOY HOUSE','PEACH AFTERNOON','MOONLIGHT DREAM'];$('worldLabel').textContent=names[level];$('levelLabel').textContent=`WORLD 0${level+1}`;const colors=['#e8ece0','#efe2d5','#dce0eb'];scene.background.set(colors[level]);scene.fog.color.set(colors[level]);ground.material.color.set(colors[level]);palette.mint.color.set(['#97bba7','#d9aa8b','#a4a2cb'][level]);sun.color.set(['#fff3db','#ffdbb1','#e5e6ff'][level]);$('levelsDialog').close();reset(false);toast('A new little world is ready.');});
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape'){togglePause();return;}if(k==='r'){reset(true);toast('A fresh start. You know the way.');return;}if(k==='c'&&started){pos.set(checkpoint.x,.35,checkpoint.z);vel.set(0,0,0);toast('Back at your checkpoint.');}keys[k]=true;});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(started&&!paused)togglePause();});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false);});
loadBest();window.__marbleGame={get state(){return{started,paused,collected,elapsed,level,timeTrial,position:pos.toArray(),stars:stars.map(s=>({x:s.x,z:s.z,collected:s.collected}))};}};

document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused)togglePause();});
