import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s), canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene();scene.background=new THREE.Color('#082c39');scene.fog=new THREE.FogExp2('#082c39',.025);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,150);camera.position.set(21,24,29);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight('#a6e7e1','#173b46',2.2));const sun=new THREE.DirectionalLight('#afe8de',3.3);sun.position.set(-9,24,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24});scene.add(sun);
const mat=(c,metal=0,rough=.8)=>new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough});
const wood=mat('#665943'),wood2=mat('#77664b'),darkWood=mat('#3d443b'),edge=mat('#8d7953'),iron=mat('#3b686c',.65),brass=mat('#d3b273',.65,.4),coral=mat('#c87869'),sand=mat('#3b6669');
const glow=(c)=>new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.6,roughness:.25});const mint=glow('#7cddc5'),gold=glow('#f6c97c');
function mesh(geo,m,parent=scene,x=0,y=0,z=0){const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(w,h,d,m,p=scene,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),m,p,x,y,z)}
function sphere(r,m,p=scene,x=0,y=0,z=0){return mesh(new THREE.SphereGeometry(r,16,12),m,p,x,y,z)}
function cyl(r,h,m,p=scene,x=0,y=0,z=0,r2=r){return mesh(new THREE.CylinderGeometry(r,r2,h,12),m,p,x,y,z)}
function tube(points,r,m,p=scene){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(a=>new THREE.Vector3(...a))),18,r,7,false),m,p)}
const seabed=box(180,.7,180,sand,scene,0,-2.2,0);
for(let i=0;i<110;i++){const x=(Math.random()-.5)*64,z=(Math.random()-.5)*48;if(Math.abs(x)<11&&Math.abs(z)<6)continue;const rock=mesh(new THREE.DodecahedronGeometry(.4+Math.random()*1.4),mat(i%3?'#375758':'#456c6b'),scene,x,-1.6,z);rock.scale.y=.45+Math.random()*.6;rock.rotation.set(Math.random(),Math.random(),0)}
const ship=new THREE.Group();scene.add(ship);
// A hand-built open hull, staggered planks and exposed ribs.
for(let x=-10;x<10;x+=.72){const taper=1-Math.pow(Math.abs(x)/12,4)*.64;for(let z=-4.6*taper;z<4.6*taper;z+=.62){const p=box(.68,.22,.58,Math.random()>.4?wood:wood2,ship,x,-.05,z);p.position.y+=(Math.random()-.5)*.05}}
for(const side of [-1,1]){for(let x=-9.5;x<9.7;x+=1.4){const z=side*(4.9-Math.pow(Math.abs(x)/11,4)*2.3);const rib=box(.26,side===-1?2.8:1.1,.25,darkWood,ship,x,side===-1?1.05:.2,z);rib.rotation.x=-side*.16;for(let k=0;k<(side===-1?4:2);k++){const wall=box(1.5,.34,.2,k%2?wood:darkWood,ship,x,k*.46,z+side*k*.04);wall.rotation.y=side*x*.025}}}
for(let x of [-10.1,10.1]){const bow=box(.32,1.2,5.1,darkWood,ship,x,.35,0);bow.rotation.z=x>0?-.13:.13}
for(let x of [-5,3]){box(.25,.35,8.5,darkWood,ship,x,.25,0);for(let z of [-4,-2,0,2,4])box(.35,.5,.35,edge,ship,x,.4,z)}
// Stern cabin and broken windows.
box(4.1,2.8,.32,darkWood,ship,7.4,1.3,-3.65);for(let x of [6.2,8.4]){box(1.25,1.1,.36,iron,ship,x,1.7,-3.42);box(.9,.75,.38,mat('#38676b',.2,.2),ship,x,1.7,-3.39);box(.06,.8,.4,brass,ship,x,1.7,-3.36)}
box(4.6,.25,2.2,wood2,ship,7.3,2.9,-3.45).rotation.z=.06;
// Mast, boom, faded sail, rigging.
cyl(.23,8.6,darkWood,ship,1,4,0);cyl(.29,.35,brass,ship,1,.45,0);const boom=cyl(.12,6.8,wood2,ship,.5,6.4,0);boom.rotation.z=Math.PI/2;
const sailGeo=new THREE.PlaneGeometry(5.8,3.4,10,8),pos=sailGeo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,Math.sin((x+2.9)/5.8*Math.PI)*.75);if(y<-.8)pos.setY(i,y+.28*Math.sin(x*3));}sailGeo.computeVertexNormals();const sail=mesh(sailGeo,new THREE.MeshStandardMaterial({color:'#b0aa83',side:THREE.DoubleSide,transparent:true,opacity:.64,roughness:1}),ship,.5,4.62,.03);sail.rotation.y=-.08;
for(const x of [-5.5,6.5])tube([[1,7.8,0],[x,2,-2],[x,.3,-4]],.028,mat('#859586'),ship);
// Cargo, barrels, anchor, scattered bones of the wreck.
function barrel(x,z){const g=new THREE.Group();g.position.set(x,.5,z);ship.add(g);cyl(.46,1,wood,g);for(let y of [-.35,.35])mesh(new THREE.TorusGeometry(.46,.045,6,16),iron,g,0,y,0).rotation.x=Math.PI/2;return g}
for(const [x,z] of [[-8,-3],[-7,-3.2],[4,3.3],[5,3.4],[8,2.7]])barrel(x,z);
for(const [x,z] of [[-4,-3],[4,-3],[7,2.5]]){box(1.05,1,1,wood2,ship,x,.5,z);for(let k of [-.4,.4])box(.1,1.04,1.04,darkWood,ship,x+k,.5,z)}
for(let i=0;i<11;i++){const p=box(1+Math.random(),.09,.22,darkWood,ship,(Math.random()-.5)*17,.15,(Math.random()-.5)*7);p.rotation.y=Math.random()*6}
const anchor=new THREE.Group();anchor.position.set(-11,-.9,3);anchor.rotation.z=.45;ship.add(anchor);cyl(.09,2,iron,anchor);box(1,.14,.14,iron,anchor,0,.5,0);tube([[-.8,-.3,0],[-.5,-1,0],[0,-.8,0],[.5,-1,0],[.8,-.3,0]],.12,iron,anchor);
const weeds=[];
for(let i=0;i<45;i++){const x=(Math.random()-.5)*33,z=(Math.random()-.5)*23;if(Math.abs(x)<10&&Math.abs(z)<4.6)continue;const g=new THREE.Group();g.position.set(x,-1.8,z);scene.add(g);for(let j=0;j<4;j++){const h=.7+Math.random()*2.2;const stem=tube([[j*.16,0,0],[j*.16+.2,h*.5,.1],[j*.16-.1,h,.1]],.06,mat(i%4?'#327d70':'#b98076'),g);weeds.push(stem)}if(i%4===0){for(let j=0;j<5;j++)sphere(.18,coral,g,Math.random()-.5,Math.random()*.8,Math.random()-.5)}}
// Objective machines.
const machines=[];const labels=[];
function marker(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=128;const cx=c.getContext('2d');cx.fillStyle='rgba(5,32,39,.75)';cx.roundRect(36,20,440,76,35);cx.fill();cx.strokeStyle='rgba(158,212,194,.35)';cx.stroke();cx.font='24px sans-serif';cx.textAlign='center';cx.fillStyle='#c6dbce';cx.fillText(text,256,68);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),depthTest:false,transparent:true}));sp.position.set(x,y,z);sp.scale.set(3.8,.95,1);scene.add(sp);labels.push(sp);return sp}
const names=['潮汐阀门','星象齿轮','回声石阵'];const positions=[[-7,0],[-1,-2.6],[5.6,.2]];
for(let i=0;i<3;i++){const [x,z]=positions[i],g=new THREE.Group();g.position.set(x,.3,z);ship.add(g);cyl(.9,.35,iron,g);cyl(.77,.13,brass,g,0,.23,0);const ring=mesh(new THREE.TorusGeometry(1.12,.026,7,50),mint,g,0,-.05,0);ring.rotation.x=Math.PI/2;
if(i===0){box(.65,1.1,.5,iron,g,0,.65,0);const wheel=new THREE.Group();wheel.position.set(0,1.3,.32);g.add(wheel);mesh(new THREE.TorusGeometry(.58,.08,8,24),brass,wheel);for(let k=0;k<6;k++){const spoke=box(.06,1.08,.06,brass,wheel);spoke.rotation.z=k*Math.PI/3}sphere(.14,mint,wheel);g.userData.spin=wheel}
if(i===1){for(let k=0;k<3;k++){const r=mesh(new THREE.TorusGeometry(.35+k*.2,.045,8,40),brass,g,0,1.1,0);r.rotation.set(.5+k*.5,k*.6,0)}sphere(.22,mint,g,0,1.1,0)}
if(i===2){for(let k=0;k<4;k++){const a=k*Math.PI/2;const crystal=mesh(new THREE.OctahedronGeometry(.25),k%2?mint:gold,g,Math.cos(a)*.55,.75,Math.sin(a)*.55);crystal.scale.y=1.7}}
const light=new THREE.PointLight('#75edc4',2.5,4);light.position.set(0,1.7,0);g.add(light);marker(`0${i+1}  ${names[i]}`,x,2.7,z);machines.push({g,x,z,ring,light});}
const chest=new THREE.Group();chest.position.set(8.1,.3,-1.7);ship.add(chest);box(1.5,.65,1,wood2,chest,0,.3,0);const lid=box(1.55,.32,1.05,brass,chest,0,.8,0);for(let x of [-.5,.5])box(.12,.9,1.07,brass,chest,x,.4,0);box(.24,.3,.1,gold,chest,0,.5,.57);marker('⚿  船长的宝藏',8.1,2.3,-1.7);
// The octopus: pear-shaped mantle, expressive eyes and eight animated articulated arms.
const octo=new THREE.Group();scene.add(octo);octo.position.set(-5,1.1,2.2);const skin=mat('#ed967d',0,.45),underside=mat('#f3c3a4',0,.65);
const head=sphere(.68,skin,octo,0,.38,0);head.scale.set(.91,1.13,.85);sphere(.5,skin,octo,0,-.08,.08);for(let x of [-.26,.26]){sphere(.205,mat('#f7edcf'),octo,x,.34,.48);sphere(.108,mat('#142d36',0,.2),octo,x,.33,.65);sphere(.036,mat('#ffffff'),octo,x-.025,.38,.735)}const arms=[];
for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const arm=new THREE.Group();octo.add(arm);const parts=[];for(let k=0;k<8;k++){const s=sphere(.17*(1-k/10),skin,arm);const sucker=sphere(.069*(1-k/10),underside,s,0,-.13,0);parts.push(s)}arms.push({a,parts})}
const pearlItems=[];for(const [x,z] of [[-8,2.5],[-8,-2],[-3,2.5],[-2,-3.6],[2,3],[4,-2],[7,3],[9,0]]){const p=sphere(.14,glow('#c7f4e7'),scene,x,.6,z);const halo=mesh(new THREE.TorusGeometry(.27,.012,6,24),mint,scene,x,.5,z);halo.rotation.x=Math.PI/2;pearlItems.push({p,halo,x,z,taken:false})}
// Sea life and suspended particles.
const fishes=[];for(let i=0;i<22;i++){const g=new THREE.Group(),m=mat(i%3?'#75a5a0':'#dcb184');const body=sphere(.14,m,g);body.scale.set(1.8,.65,.65);const tail=mesh(new THREE.ConeGeometry(.15,.25,3),m,g,-.32,0,0);tail.rotation.z=Math.PI/2;scene.add(g);fishes.push({g,phase:Math.random()*6.28,r:12+Math.random()*7,y:Math.random()*6})}
const jelly=[];for(let i=0;i<5;i++){const g=new THREE.Group();g.position.set(-14+i*7,4+Math.random()*4,-9-Math.random()*5);scene.add(g);const jm=new THREE.MeshStandardMaterial({color:'#8cd4d7',emissive:'#3b8eaa',emissiveIntensity:.5,transparent:true,opacity:.42,side:THREE.DoubleSide});mesh(new THREE.SphereGeometry(.55,20,12,0,Math.PI*2,0,Math.PI/2),jm,g);for(let j=0;j<5;j++)tube([[j*.15-.3,0,0],[j*.15-.2,-.5,.1],[j*.15-.3,-1.2,.1]],.018,jm,g);jelly.push(g)}
const particles=new Float32Array(650*3);for(let i=0;i<particles.length;i+=3){particles[i]=(Math.random()-.5)*70;particles[i+1]=Math.random()*22-2;particles[i+2]=(Math.random()-.5)*60}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(particles,3));scene.add(new THREE.Points(pg,new THREE.PointsMaterial({color:'#b2d9d5',size:.045,transparent:true,opacity:.48})));
const eel=new THREE.Group();scene.add(eel);for(let i=0;i<10;i++){const s=sphere(.16*(1-i/16),mat('#527f89'),eel,i*.23,0,0);if(i===0)sphere(.055,gold,s,-.08,.07,.13)}
const sonar=mesh(new THREE.TorusGeometry(1,.035,8,80),mint);sonar.rotation.x=Math.PI/2;sonar.visible=false;const inkClouds=[];
const state={solved:[false,false,false],pearls:0,energy:100,paused:false,modal:false,won:false,time:0,sound:false,ink:0,sonar:0};let nearest=-1,lastToast=0,goalTime=0,heading=0;const pressed=new Set();
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(lastToast);lastToast=setTimeout(()=>$('#toast').classList.remove('show'),3400)}
function beep(freq=500,d=.12){if(!state.sound)return;const ac=audioCtx||(audioCtx=new AudioContext());const osc=ac.createOscillator(),gain=ac.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.055,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);osc.connect(gain);gain.connect(ac.destination);osc.start();osc.stop(ac.currentTime+d)}let audioCtx;
function updateHUD(){const n=state.solved.filter(Boolean).length;$('#progress').textContent=`${n} / 3`;$('#keys').textContent=n;$('#pearls').textContent=state.pearls;$('#tasks').innerHTML=names.map((t,i)=>`<div class="task ${state.solved[i]?'done':i===state.solved.indexOf(false)?'active':''}"><b>${state.solved[i]?'✓':`0${i+1}`}</b><div>${t}<small>${['平衡水压 · 唤醒引擎','校准星环 · 寻找航向','聆听回声 · 重现旋律'][i]}</small></div></div>`).join('');if(n===3)$('#hint').textContent='三枚符印已集齐。前往右侧船长宝箱，找回海洋之心。'}updateHUD();
function closeModal(){state.modal=false;$('#modal').classList.add('hidden');pressed.clear()}
function modal(html){state.modal=true;pressed.clear();$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
$('#close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
function solve(i){state.solved[i]=true;machines[i].ring.material=gold;machines[i].light.color.set('#ffd58a');updateHUD();beep(880,.4);closeModal();toast(`${names[i]}已唤醒 · 获得第 ${state.solved.filter(Boolean).length} 枚符印`)}
const valve=[0,0,0],stars=[0,0,0],symbols=['☾','✦','☀','♆'];let memory=[];let playing=false;let puzzleToken=0;
function puzzle(i){puzzleToken++;if(state.solved[i])return toast('这座机关已被你唤醒。继续探索吧。');if(i===0){modal(`<div class="eyebrow">MECHANISM 01 / 水压控制室</div><h2>潮汐阀门</h2><p>船匠的刻痕写着：「左舷三潮，中舱一潮，右舷两潮。」<br>每次转动阀门，水压增加一格，超过四格归零。</p><div class="puzzle">${valve.map((v,j)=>`<button class="dial" data-valve="${j}">◉<small id="v${j}">${v} / 4</small></button>`).join('')}</div><div class="note" id="note">让三条管道恢复正确的水压</div><button class="primary" id="check">注入潮汐</button>`);document.querySelectorAll('[data-valve]').forEach(b=>b.onclick=()=>{const j=+b.dataset.valve;valve[j]=(valve[j]+1)%5;$(`#v${j}`).textContent=`${valve[j]} / 4`;beep(240+valve[j]*70)});$('#check').onclick=()=>valve.join()==='3,1,2'?solve(0):($('#note').textContent='水压尚未平衡。再看看船匠留下的刻痕。',beep(130));}
if(i===1){modal(`<div class="eyebrow">MECHANISM 02 / 星象导航仪</div><h2>失落的航向</h2><p>航海日志：「月升，星引，日归。」<br>转动三个星环，让它们依次对应日志中的天象。</p><div class="puzzle">${stars.map((v,j)=>`<button class="dial" data-star="${j}">${symbols[v]}</button>`).join('')}</div><div class="note" id="note">航线藏在月亮、星辰和太阳之间</div><button class="primary" id="check">锁定航向</button>`);document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{const j=+b.dataset.star;stars[j]=(stars[j]+1)%4;b.textContent=symbols[stars[j]];beep(400+stars[j]*80)});$('#check').onclick=()=>stars.join()==='0,1,2'?solve(1):($('#note').textContent='航向偏离了。按照日志，从左到右排列天象。',beep(130));}
if(i===2){memory=[];playing=false;modal(`<div class="eyebrow">MECHANISM 03 / 古老的声呐</div><h2>深海的回声</h2><p>石阵记住了最后一位船长的旋律。<br>聆听并观察发光顺序，然后依次触碰四枚符文。</p><div class="puzzle">${['◇','≋','✧','◎'].map((s,j)=>`<button class="rune" data-rune="${j}">${s}</button>`).join('')}</div><div class="note" id="note">点击「聆听回声」开始</div><button class="primary" id="listen">聆听回声</button>`);const seq=[0,2,1,3,2],token=puzzleToken;let ready=false;$('#listen').onclick=async()=>{if(playing)return;playing=true;ready=false;memory=[];$('#note').textContent='记住闪光顺序…';for(const n of seq){await new Promise(r=>setTimeout(r,450));if(token!==puzzleToken||!state.modal)return;const b=$(`[data-rune="${n}"]`);b.classList.add('flash');beep(330+n*120,.25);await new Promise(r=>setTimeout(r,360));if(!b.isConnected)return;b.classList.remove('flash')}playing=false;ready=true;$('#note').textContent='轮到你了 · 0 / 5'};document.querySelectorAll('[data-rune]').forEach(b=>b.onclick=()=>{if(!ready||playing)return;const n=+b.dataset.rune;beep(330+n*120);b.classList.add('flash');setTimeout(()=>b.classList.remove('flash'),200);if(n!==seq[memory.length]){memory=[];ready=false;$('#note').textContent='回声有些不同。重新聆听，再试一次。';return}memory.push(n);$('#note').textContent=`回声共鸣 · ${memory.length} / 5`;if(memory.length===5)solve(2)})}}
function interact(){if(state.modal||state.paused)return;if(nearest>=0&&nearest<3)puzzle(nearest);if(nearest===3){if(state.solved.every(Boolean)){if(!state.won){state.won=true;goalTime=state.time;lid.rotation.x=-.9;lid.position.y=1.1;const gem=mesh(new THREE.OctahedronGeometry(.48),mint,chest,0,1.2,0);chest.add(new THREE.PointLight('#7fffcc',5,8));beep(1000,.6)}modal(`<div class="successicon">✧</div><div class="eyebrow">THE HEART OF THE OCEAN</div><h2>海洋之心，重见天光</h2><p>小墨用八只腕足，解开了一百年的秘密。<br>沉船再次亮起温柔的光，海洋记住了你的名字。</p><div class="puzzle"><div><strong>${state.pearls} / 8</strong><p>发现珍珠</p></div><div><strong>${Math.floor(goalTime/60)} 分 ${Math.floor(goalTime%60)} 秒</strong><p>探索时长</p></div><div><strong>${state.pearls===8?'深海收藏家':'沉船解谜者'}</strong><p>获得称号</p></div></div><button class="primary" id="continue">继续探索</button><button class="secondary" id="restart">重新启航</button>`);$('#continue').onclick=closeModal;$('#restart').onclick=()=>location.reload()}else toast(`宝箱需要三枚符印。还差 ${3-state.solved.filter(Boolean).length} 枚。`)}}
function sonarPing(){if(state.energy<20)return toast('能量不足，休息片刻再使用声呐。');state.energy-=20;state.sonar=2.2;sonar.position.set(octo.position.x,.35,octo.position.z);sonar.visible=true;beep(700,.7);toast('声呐已展开 · 发光圆环标记机关，微光标记珍珠')}
function dash(){if(state.energy<30||state.ink>0)return;state.energy-=30;state.ink=1;const cloud=sphere(.5,new THREE.MeshBasicMaterial({color:'#182c46',transparent:true,opacity:.7}),scene,octo.position.x,octo.position.y,octo.position.z);inkClouds.push({cloud,life:2});beep(150,.2)}
$('#help').onclick=()=>modal(`<div class="eyebrow">EXPLORER'S FIELD GUIDE</div><h2>欢迎来到深海</h2><p>操纵小墨探索鹦鹉螺号，破解三座机关，<br>收集符印并打开船长的宝箱。</p><div class="legend"><span><kbd>W A S D</kbd> / 方向键 游动</span><span><kbd>E</kbd> 靠近机关交互</span><span><kbd>空格</kbd> 喷墨冲刺 / 驱赶海鳗</span><span><kbd>Q</kbd> 声呐扫描</span><span><kbd>Esc</kbd> 关闭面板 / 暂停</span><span>靠近珍珠自动收集</span></div><p>海鳗接近时会消耗能量，喷墨可暂时驱散它。<br>能量随时间恢复。机关可以按任意顺序挑战。</p><button class="primary" id="go">开始探索</button>` )||null;
$('#help').addEventListener('click',()=>{$('#go').onclick=closeModal});
$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').style.color=state.sound?'#e7cb8d':'#e0ecea';toast(state.sound?'水下音效已开启':'水下音效已关闭');beep()};
function pause(){if(state.modal)return;state.paused=!state.paused;$('#pause').textContent=state.paused?'▶':'Ⅱ';toast(state.paused?'探索已暂停 · 再次点击继续':'继续探索')};$('#pause').onclick=pause;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;const k=e.key.toLowerCase();if(k==='escape'){if(state.modal)closeModal();else pause();return}if(state.modal||state.paused)return;pressed.add(k);if(k==='e')interact();if(k==='q')sonarPing();if(e.code==='Space')dash()});window.addEventListener('keyup',e=>pressed.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>pressed.clear());document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();pressed.add(b.dataset.key);b.setPointerCapture(e.pointerId)};b.onpointerup=()=>pressed.delete(b.dataset.key);b.onpointercancel=()=>pressed.delete(b.dataset.key)});$('#mobileE').onclick=interact;
const raycaster=new THREE.Raycaster();canvas.addEventListener('click',e=>{if(state.modal)return;raycaster.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hits=raycaster.intersectObjects(machines.map(m=>m.g),true);if(hits.length){let o=hits[0].object;while(o.parent&&o.parent!==ship)o=o.parent;const i=machines.findIndex(m=>m.g===o);if(i>=0){if(Math.hypot(octo.position.x-machines[i].x,octo.position.z-machines[i].z)<2.6)puzzle(i);else toast(`游近「${names[i]}」，按 E 开始解谜`)}}});
const clock=new THREE.Clock();let elapsed=0,damageCooldown=0;
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;const t=elapsed;
if(!state.paused&&!state.modal){state.time+=dt;state.energy=Math.min(100,state.energy+dt*5);state.ink=Math.max(0,state.ink-dt);damageCooldown=Math.max(0,damageCooldown-dt);
let dx=0,dz=0;if(pressed.has('w')||pressed.has('arrowup')){dx-=.6;dz-=.8}if(pressed.has('s')||pressed.has('arrowdown')){dx+=.6;dz+=.8}if(pressed.has('a')||pressed.has('arrowleft')){dx-=.8;dz+=.6}if(pressed.has('d')||pressed.has('arrowright')){dx+=.8;dz-=.6}const len=Math.hypot(dx,dz);if(len){dx/=len;dz/=len;const speed=state.ink>.5?7.5:2.8;octo.position.x=THREE.MathUtils.clamp(octo.position.x+dx*dt*speed,-9.3,9.3);octo.position.z=THREE.MathUtils.clamp(octo.position.z+dz*dt*speed,-3.65,3.65);heading=Math.atan2(dx,dz)}octo.rotation.y+=Math.atan2(Math.sin(heading-octo.rotation.y),Math.cos(heading-octo.rotation.y))*dt*7;
nearest=-1;let dist=2.3;[...positions,[8.1,-1.7]].forEach(([x,z],i)=>{let d=Math.hypot(octo.position.x-x,octo.position.z-z);if(d<dist){dist=d;nearest=i}});$('#interact').classList.toggle('hidden',nearest===-1);if(nearest>=0)$('#interact span').textContent=nearest===3?'打开船长宝箱':state.solved[nearest]?'查看已唤醒的机关':`触碰${names[nearest]}`;
for(const item of pearlItems)if(!item.taken&&Math.hypot(octo.position.x-item.x,octo.position.z-item.z)<.75){item.taken=true;item.p.visible=false;item.halo.visible=false;state.pearls++;updateHUD();beep(1000,.15);toast(state.pearls===8?'八颗珍珠集齐 · 获得「深海收藏家」称号':`发现一颗珍珠 · ${state.pearls} / 8`)}
eel.position.set(Math.sin(t*.3)*7,1,Math.cos(t*.45)*2.7);eel.rotation.y=-t*.3;if(state.ink>0)eel.position.z+=5;if(damageCooldown===0&&Math.hypot(eel.position.x-octo.position.x,eel.position.z-octo.position.z)<1.1){state.energy=Math.max(0,state.energy-18);damageCooldown=5;toast('海鳗被惊动了！按空格喷墨驱散，或游开恢复能量。')}
}
octo.position.y=1.05+Math.sin(t*2)*.11;head.scale.y=1.13+Math.sin(t*2)*.035;
for(const arm of arms)for(let k=0;k<8;k++){const r=.36+k*.135,a=arm.a+Math.sin(t*2.3-k*.45+arm.a)*.21;arm.parts[k].position.set(Math.cos(a)*r,-.15-k*.073+Math.sin(t*2.8-k*.7+arm.a)*.1,Math.sin(a)*r)}
for(let i=0;i<fishes.length;i++){const f=fishes[i],a=t*.1+f.phase;f.g.position.set(Math.cos(a)*f.r,f.y+Math.sin(t+i)*.15,Math.sin(a)*f.r*.55);f.g.rotation.y=-a-Math.PI/2}jelly.forEach((g,i)=>{g.position.y+=Math.sin(t+i)*dt*.2;g.scale.setScalar(1+Math.sin(t*1.7+i)*.045)});weeds.forEach((w,i)=>w.rotation.z=Math.sin(t*.7+i)*.065);
for(let i=0;i<machines.length;i++){const m=machines[i];m.ring.scale.setScalar(1+Math.sin(t*2+i)*.035);if(m.g.userData.spin)m.g.userData.spin.rotation.z=t*(state.solved[i]?.35:.08)}pearlItems.forEach((p,i)=>{p.p.position.y=.65+Math.sin(t*2+i)*.15;p.halo.rotation.z=t});
if(state.sonar>0){state.sonar-=dt;sonar.scale.setScalar((2.2-state.sonar)*7+.1);sonar.visible=state.sonar>0}for(let i=inkClouds.length-1;i>=0;i--){const c=inkClouds[i];c.life-=dt;c.cloud.scale.multiplyScalar(1+dt*.9);c.cloud.material.opacity=Math.max(0,c.life*.25);if(c.life<=0){scene.remove(c.cloud);c.cloud.geometry.dispose();c.cloud.material.dispose();inkClouds.splice(i,1)}}
$('#energy').style.width=`${state.energy}%`;$('#energyLabel').textContent=`腕足能量 · ${Math.round(state.energy)}%`;renderer.render(scene,camera)}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.position.set(21,24,29).multiplyScalar(innerWidth<700?1.38:innerWidth<1100?1.12:1);camera.lookAt(innerWidth<700?0:-2,0,0);camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;animate();
window.__abyssal={state,octo,positions,interact,puzzle,sonarPing,dash};
setTimeout(()=>toast('欢迎来到鹦鹉螺号 · 使用 WASD 游动，靠近机关按 E'),1600);
