import './style.css';
import {createScene} from './scene.js';
const $=id=>document.getElementById(id);
let world;try{world=createScene($('scene'));}catch(e){$('scene').innerHTML='<p style="padding:80px 30px">3D 场景需要浏览器开启硬件加速。下方工作台仍可正常制作寿司。</p>';console.error(e);}
const recipes=[{id:'salmon',name:'极光三文鱼握寿司',short:'三文鱼握寿司',art:'🍣',ingredient:'三文鱼',price:32},{id:'shrimp',name:'甜虾海风握寿司',short:'甜虾握寿司',art:'🍤',ingredient:'甜虾',price:38},{id:'cucumber',name:'森林黄瓜寿司卷',short:'黄瓜寿司卷',art:'🥒',ingredient:'黄瓜',price:26}];
let saved={};try{saved=JSON.parse(localStorage.getItem('penguin-sushi-v1')||'{}');}catch{}
const state={coins:Number(saved.coins)||0,day:Number(saved.day)||1,upgrades:saved.upgrades||{speed:0,patience:0,tips:0},time:180,orders:[],selected:null,plate:[],ready:false,cooking:0,served:0,missed:0,combo:0,best:0,goal:false,paused:false,started:false,ended:false,sound:true,nextId:1,spawn:0};
const names=['围巾先生','小团子','阿啾','小海盐','桃桃','渔夫皮皮','棉花糖'];
function save(){try{localStorage.setItem('penguin-sushi-v1',JSON.stringify({coins:state.coins,day:state.day,upgrades:state.upgrades}));}catch{}}
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
let audio;function beep(freq=600,duration=.12){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function addOrder(type){const recipe=recipes[type??Math.floor(Math.random()*3)];const duration=Math.max(27,65-state.day*3)+state.upgrades.patience*10;state.orders.push({id:state.nextId++,recipe,time:duration,max:duration,name:names[Math.floor(Math.random()*names.length)]});if(!state.selected)state.selected=state.orders[0].id;renderOrders();}
function renderOrders(){ $('order-count').textContent=state.orders.length;$('orders').innerHTML=state.orders.map(o=>`<button class="order ${o.id===state.selected?'active':''}" data-order="${o.id}"><div class="order-head"><span class="avatar">🐧</span>${o.name}<span class="order-num">#${String(o.id).padStart(3,'0')}</span></div><div class="order-title"><span>${o.recipe.art}</span><div><b>${o.recipe.short}</b><small>米饭 + ${o.recipe.ingredient} · 1 份</small></div></div><div class="order-price"><span class="wait-label">${Math.ceil(o.time)} 秒 · 耐心等待中</span><b>${o.recipe.price} G</b></div><div class="patience"><i style="width:${o.time/o.max*100}%"></i></div></button>`).join('')||'<p style="padding:25px;color:#9aab90">大家正在赶来的路上…</p>';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.order);renderOrders();renderPlate();beep(450);});renderPlate();}
function renderStats(){$('clock').textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`;$('coins').textContent=state.coins;$('served').textContent=state.served+' 份';$('combo').innerHTML='×'+state.best+' <span>✧</span>';$('satisfaction').innerHTML=(state.served+state.missed?Math.round(state.served/(state.served+state.missed)*100):100)+'<span>%</span>';$('goal-number').textContent=Math.min(state.served,8)+' / 8';$('goal-bar').style.width=Math.min(state.served/8*100,100)+'%';$('day-label').textContent=`第 ${state.day} 天 · ${state.day===1?'初次开张':state.day<4?'渐入佳境':'人气小店'}`;}
function renderPlate(){const r=recipes.find(r=>r.id===state.plate[1]);$('plate-art').textContent=state.ready?r.art:state.plate.length===2?'🍚'+r.art:state.plate.length?'🍚':'🍽️';$('plate-art').style.fontSize=state.plate.length===2&&!state.ready?'23px':'35px';$('plate-name').textContent=state.ready?'美味已就绪':state.cooking?'用心制作中':state.plate.length?'等待制作':'空空的餐盘';const o=state.orders.find(o=>o.id===state.selected);$('recipe-hint').textContent=o?`所需：米饭 + ${o.recipe.ingredient} → 制作 → 出餐`:'新的客人马上就到';$('work-status').textContent=state.cooking?'小企鹅正在制作…':state.ready?'做好啦！快把美味送出去':state.started?'跟随食谱，按顺序制作':'点击米饭或按 1 开始营业';for(let i=0;i<3;i++)$('step'+i).classList.toggle('current',i===Math.min(state.plate.length,2));}
function action(type){if(state.paused||state.ended)return;if(!state.started){state.started=true;$('chef-bubble').textContent='第一份订单，开工！';}if(state.cooking)return toast('再等一下，寿司马上就好！');if(state.ready)return toast('餐盘已做好，请先出餐或重新制作');if(type==='rice'){if(state.plate.length)return toast('已经有米饭啦，挑选一种配料吧');state.plate=['rice'];}else if(type==='roll'){if(state.plate.length!==2)return toast('还需要米饭和一种配料哦');state.cooking= Math.max(.85,2.8-state.upgrades.speed*.55);state.cookTotal=state.cooking;$('chef-bubble').textContent='捏一捏，卷一卷…';}else{if(!state.plate.length)return toast('先盛一份香喷喷的米饭吧');if(state.plate.length===2)return toast('配料已齐，点击制作寿司');state.plate.push(type);}world?.move(type);beep(type==='roll'?400:620);renderPlate();}
function discard(){if(state.paused||state.ended)return;state.plate=[];state.ready=false;state.cooking=0;world?.stop();$('cook-progress').style.width='0';renderPlate();toast('餐盘清空，重新开始吧');}
function serve(){if(state.paused||state.ended)return;if(!state.ready)return toast('先完成寿司制作，再出餐哦');const o=state.orders.find(o=>o.id===state.selected);if(!o)return toast('请先选择一个订单');if(o.recipe.id!==state.plate[1])return toast('这份寿司和订单不同，试试选择另一张小票');state.served++;state.combo++;state.best=Math.max(state.best,state.combo);const tip=Math.round(o.time/o.max*8)+Math.min(state.combo-1,8)*2+state.upgrades.tips*3;const earned=o.recipe.price+tip;state.coins+=earned;state.orders=state.orders.filter(x=>x.id!==o.id);state.selected=state.orders[0]?.id??null;state.plate=[];state.ready=false;world?.move('serve');world?.celebrate();beep(880,.22);$('chef-bubble').textContent=state.combo>1?`${state.combo} 连击！大家都很喜欢你的寿司！`:'谢谢款待，真的好好吃！';$('float-message').textContent=`+${earned} G ✦`;$('float-message').className='';void $('float-message').offsetWidth;$('float-message').className='float-up';toast(`出餐成功！${o.recipe.price} 金币 + ${tip} 小费${state.combo>1?' · '+state.combo+' 连击':''}`);if(state.served>=8&&!state.goal){state.goal=true;state.coins+=80;setTimeout(()=>toast('今日目标达成！额外获得 80 金币 ✦'),1600);}state.spawn=Math.min(state.spawn,2);renderOrders();renderStats();save();}
function modal(html){state.paused=true;$('pause').textContent='▶';$('modal').innerHTML=`<div class="modal-card"><button class="close" id="modal-close" aria-label="关闭">×</button>${html}</div>`;$('modal').classList.remove('hidden');$('modal-close').onclick=closeModal;}
function closeModal(){if(state.ended){nextDay();return;}$('modal').classList.add('hidden');state.paused=false;$('pause').textContent='Ⅱ';}
function help(){modal('<p class="eyebrow">WELCOME TO THE ICEBERG</p><h2>小小企鹅，大大主厨 🐧</h2><p>点击订单小票，按食谱完成料理。客人的耐心会慢慢减少，及时出餐就能赚到更多小费！</p><div class="recipe-row"><span>① 米饭 → ② 配料 → ③ 制作 → 出餐</span></div><p><b>快捷键</b><br>1 米饭 · 2 三文鱼 · 3 甜虾 · 4 黄瓜<br>空格 制作 · Enter 出餐 · R 清空 · P 暂停<br><br>每个营业日 3 分钟，完成 8 单可得额外奖励。金币可升级厨房，并自动保存在此浏览器。<br>首次开始前不会计时，准备好再点击米饭。</p><button class="primary" id="help-done">好的，开始做寿司！</button>');$('help-done').onclick=closeModal;}
function shop(){modal(`<p class="eyebrow">A COZIER LITTLE KITCHEN</p><h2>给厨房一点新变化</h2><p>可用金币：<b>${state.coins} G</b> · 升级将在后续营业日保留</p>${[{id:'speed',name:'🔪 精巧竹帘',desc:'每级缩短 0.55 秒制作时间'},{id:'patience',name:'🍵 暖心热茶',desc:'每级增加 10 秒顾客耐心'},{id:'tips',name:'🌸 精致摆盘',desc:'每级额外获得 3 金币小费'}].map(u=>`<div class="upgrade"><div><b>${u.name} · Lv.${state.upgrades[u.id]}</b><small>${u.desc}</small></div><button data-upgrade="${u.id}">${state.upgrades[u.id]>=3?'已满级':(80+state.upgrades[u.id]*70)+' G 升级'}</button></div>`).join('')}`);document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const id=b.dataset.upgrade,lv=state.upgrades[id],cost=80+lv*70;if(lv>=3)return toast('已达到最高等级');if(state.coins<cost)return toast('金币还不够，再制作几份寿司吧！');state.coins-=cost;state.upgrades[id]++;save();renderStats();shop();beep(1000);toast('升级成功，下份寿司更美味！');});}
function endDay(){state.ended=true;state.paused=true;const stars=state.served>=8?'★★★':state.served>=4?'★★☆':'★☆☆';save();modal(`<p class="eyebrow">THE OCEAN SAYS GOOD NIGHT</p><h2>辛苦啦，企鹅店长！</h2><div style="font-size:40px;color:#c4a168;margin:20px 0">${stars}</div><p>第 ${state.day} 天完成了 <b>${state.served}</b> 份订单<br>最佳连击 <b>×${state.best}</b> · 离开的客人 ${state.missed} 位<br>${state.goal?'今日目标达成，80 金币奖励已到账。':'明天继续向 8 份订单的小目标努力吧。'}<br>钱包现有 <b>${state.coins} G</b>。</p><button class="primary" id="next-day">迎接新的一天 →</button>`);$('next-day').onclick=nextDay;}
function nextDay(){state.day++;Object.assign(state,{time:180,orders:[],selected:null,plate:[],ready:false,cooking:0,served:0,missed:0,combo:0,best:0,goal:false,paused:false,started:false,ended:false,spawn:5});$('modal').classList.add('hidden');$('pause').textContent='Ⅱ';[0,1,2].forEach(addOrder);renderStats();renderPlate();save();$('chef-bubble').textContent='新的海风，新的美味。准备好开门了吗？';}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('serve').onclick=serve;$('discard').onclick=discard;$('help').onclick=help;$('shop-open').onclick=shop;$('recipe-open').onclick=()=>modal(`<p class="eyebrow">LITTLE BOOK OF SUSHI</p><h2>企鹅的手作食谱</h2><p>每份寿司都从温热的米饭开始。选好配料后，记得点击制作。</p>${recipes.map(r=>`<div class="recipe-row"><span style="font-size:34px">${r.art}</span><div><strong>${r.name}</strong><small>米饭 + ${r.ingredient} → 手作成型</small></div><b>${r.price} G</b></div>`).join('')}`);$('pause').onclick=()=>{if(state.ended)return;state.paused=!state.paused;$('pause').textContent=state.paused?'▶':'Ⅱ';$('chef-bubble').textContent=state.paused?'休息一下，海风会等你。':'欢迎回来，继续制作美味！';};$('sound').onclick=()=>{state.sound=!state.sound;$('sound').textContent=state.sound?'♫':'♩';$('sound').style.opacity=state.sound?'1':'.4';toast(state.sound?'音效已开启':'音效已关闭');beep();};$('camera-reset').onclick=()=>world?.reset();
document.addEventListener('keydown',e=>{if(!e.repeat&&['1','2','3','4',' ','Enter','r','R','p','P','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape'&&!$('modal').classList.contains('hidden'))return closeModal();if(!$('modal').classList.contains('hidden'))return;if(e.key.toLowerCase()==='p')return $('pause').click();if(e.key==='Enter')return serve();if(e.key.toLowerCase()==='r')return discard();action({'1':'rice','2':'salmon','3':'shrimp','4':'cucumber',' ':'roll'}[e.key]);}});
let last=performance.now();setInterval(()=>{let now=performance.now(),dt=Math.min((now-last)/1000,.5);last=now;if(!state.started||state.paused||state.ended)return;state.time=Math.max(0,state.time-dt);$('clock').textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`;if(state.time<=0)return endDay();if(state.cooking>0){state.cooking=Math.max(0,state.cooking-dt);$('cook-progress').style.width=(1-state.cooking/state.cookTotal)*100+'%';if(state.cooking===0){state.ready=true;world?.stop();beep(750);renderPlate();$('chef-bubble').textContent='寿司做好啦，点击出餐！';$('cook-progress').style.width='0';}}let expired=false;state.orders.forEach(o=>{o.time-=dt;if(o.time<=0){state.missed++;state.combo=0;expired=true;}});if(expired){state.orders=state.orders.filter(o=>o.time>0);if(!state.orders.find(o=>o.id===state.selected))state.selected=state.orders[0]?.id??null;renderOrders();renderStats();toast('客人等不及离开了，优先处理快超时的订单吧');}state.orders.forEach(o=>{const el=document.querySelector(`[data-order="${o.id}"]`);if(!el)return;el.querySelector('.patience i').style.width=o.time/o.max*100+'%';el.querySelector('.patience i').style.background=o.time<15?'#d99977':'#9eb67d';el.querySelector('.wait-label').textContent=`${Math.ceil(o.time)} 秒 · ${o.time<15?'有点着急了':'耐心等待中'}`;});state.spawn-=dt;if(state.orders.length<3&&state.spawn<=0){addOrder();state.spawn=Math.max(2,6-state.day*.5);}},100);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.started&&!state.paused&&!state.ended)$('pause').click();});[0,1,2].forEach(addOrder);renderStats();renderPlate();
