import * as THREE from './vendor/three.module.js';
export class VaultScene {
 constructor(host, onDial, onInteract) {
  this.host=host;this.onDial=onDial;this.onInteract=onInteract;this.angle=0;this.open=0;this.targetOpen=0;this.yaw=.26;this.pitch=.10;this.zoom=8.3;this.targetZoom=8.3;this.tool='listen';this.phase=0;this.listening=false;this.signal=0;this.lowMotion=false;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x18271f);this.scene.fog=new THREE.FogExp2(0x18271f,.034);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.35;host.appendChild(this.renderer.domElement);
  this.camera=new THREE.PerspectiveCamera(35,1,.1,80);this.scene.add(new THREE.HemisphereLight(0xd3dfba,0x263128,2.2));
  const key=new THREE.SpotLight(0xffe1a1,70,25,Math.PI/4,.6,1.6);key.position.set(-4,7,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.bias=-.0005;key.target.position.set(0,0,0);this.scene.add(key,key.target);
  const fill=new THREE.PointLight(0x9ebdad,17,20,1.5);fill.position.set(5,2,3);this.scene.add(fill);const rim=new THREE.PointLight(0xd9b56c,20,15,1.5);rim.position.set(-2,3,-4);this.scene.add(rim);
  const env=new THREE.Scene();env.background=new THREE.Color(0x59654f);const lightPanel=new THREE.Mesh(new THREE.PlaneGeometry(6,8),new THREE.MeshBasicMaterial({color:0xf7e7bb}));lightPanel.position.set(-5,4,3);lightPanel.lookAt(0,0,0);env.add(lightPanel);const p2=lightPanel.clone();p2.position.set(4,1,4);p2.lookAt(0,0,0);p2.material=new THREE.MeshBasicMaterial({color:0x839c8e});env.add(p2);const pmrem=new THREE.PMREMGenerator(this.renderer);this.scene.environment=pmrem.fromScene(env,.03).texture;pmrem.dispose();
  this.mats={body:new THREE.MeshStandardMaterial({color:0x394439,metalness:.75,roughness:.4}),face:new THREE.MeshStandardMaterial({color:0x29342c,metalness:.68,roughness:.44}),brass:new THREE.MeshStandardMaterial({color:0xa28d57,metalness:.9,roughness:.3}),gold:new THREE.MeshStandardMaterial({color:0xc5ac6f,metalness:.87,roughness:.24}),dark:new THREE.MeshStandardMaterial({color:0x101812,metalness:.55,roughness:.4}),inner:new THREE.MeshStandardMaterial({color:0x19211a,metalness:.1,roughness:.95}),silver:new THREE.MeshStandardMaterial({color:0x8c9682,metalness:.88,roughness:.3}),glow:new THREE.MeshStandardMaterial({color:0xb7c295,emissive:0x789745,emissiveIntensity:.5,metalness:.5,roughness:.4})};
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x29362a,roughness:.86,metalness:.23}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.64;floor.receiveShadow=true;this.scene.add(floor);
  const grid=new THREE.GridHelper(32,64,0x657357,0x3d4c37);grid.position.y=-1.635;grid.material.transparent=true;grid.material.opacity=.16;this.scene.add(grid);
  this.vault=new THREE.Group();this.scene.add(this.vault);this.build();this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.bind();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.animate();
 }
 rounded(w,h,d,r,material){const s=new THREE.Shape();s.moveTo(-w/2+r,-h/2);s.lineTo(w/2-r,-h/2);s.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);s.lineTo(w/2,h/2-r);s.quadraticCurveTo(w/2,h/2,w/2-r,h/2);s.lineTo(-w/2+r,h/2);s.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);s.lineTo(-w/2,-h/2+r);s.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);const g=new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.025,bevelThickness:.025,curveSegments:8});g.translate(0,0,-d/2);const m=new THREE.Mesh(g,material);m.castShadow=true;m.receiveShadow=true;return m;}
 box(w,h,d,mat,x=0,y=0,z=0,parent=this.vault){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 cyl(r,depth,mat,x,y,z,parent=this.door,segments=64){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,depth,segments),mat);m.rotation.x=Math.PI/2;m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
 ring(r,t,mat,x,y,z,parent=this.door){const m=new THREE.Mesh(new THREE.TorusGeometry(r,t,12,100),mat);m.position.set(x,y,z);parent.add(m);return m;}
 label(text,w,h,size,color='#bbaa7d',font='serif'){const c=document.createElement('canvas');c.width=1024;c.height=Math.round(1024*h/w);const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font=`${size}px ${font}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,c.height/2);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));}
 build(){
  const m=this.mats;
  this.box(2.92,.19,2.26,m.body,0,-1.43,0);this.box(.18,2.75,2.25,m.body,-1.43,0,0);this.box(.18,2.75,2.25,m.body,1.43,0,0);this.box(2.92,.18,2.25,m.body,0,1.36,0);this.box(2.92,2.75,.18,m.body,0,0,-1.06);
  this.box(2.68,2.55,.04,m.inner,0,0,-.94);this.box(2.66,.04,1.91,m.inner,0,-1.28,0);this.box(2.66,.07,1.8,m.brass,0,-.5,-.06);
  for(const x of[-1.17,1.17])for(const z of[-.8,.8]){this.box(.29,.28,.34,m.dark,x,-1.54,z);this.box(.34,.05,.39,m.brass,x,-1.46,z);}
  for(const x of[-1.46,1.46])this.box(.10,2.91,.12,m.brass,x,0,1.15);for(const y of[-1.40,1.40])this.box(2.92,.10,.12,m.brass,0,y,1.15);const opening=this.rounded(2.82,2.72,.13,.09,m.dark);opening.position.z=1.22;this.vault.add(opening);this.opening=opening;
  this.door=new THREE.Group();this.door.position.set(-1.39,0,1.29);this.vault.add(this.door);const slab=this.rounded(2.78,2.65,.16,.11,m.face);slab.position.set(1.39,0,0);this.door.add(slab);
  const border=this.rounded(2.51,2.4,.014,.14,m.brass);border.position.set(1.39,0,.098);this.door.add(border);const inset=this.rounded(2.47,2.36,.025,.13,m.face);inset.position.set(1.39,0,.11);this.door.add(inset);
  for(const y of[-1.16,1.16])this.box(2.26,.007,.01,m.gold,1.39,y,.131,this.door);
  for(const y of[-.88,.87]){const h=new THREE.Mesh(new THREE.CylinderGeometry(.10,.10,.49,20),m.brass);h.position.set(-.02,y,.03);h.castShadow=true;this.door.add(h);for(const yy of[-.21,.21]){const hh=new THREE.Mesh(new THREE.CylinderGeometry(.112,.112,.035,20),m.gold);hh.position.set(-.02,y+yy,.03);this.door.add(hh);}}
  for(const x of[.26,2.51])for(const y of[-1.08,1.08]){this.cyl(.035,.014,m.brass,x,y,.144);this.box(.041,.005,.004,m.dark,x,y,.155,this.door);}
  this.dialBase=new THREE.Group();this.dialBase.position.set(1.12,.13,.155);this.door.add(this.dialBase);
  this.cyl(.68,.085,m.dark,0,0,0,this.dialBase);this.cyl(.63,.055,m.brass,0,0,.053,this.dialBase);this.cyl(.60,.06,m.face,0,0,.09,this.dialBase);this.ring(.605,.009,m.gold,0,0,.127,this.dialBase);this.ring(.53,.006,m.brass,0,0,.129,this.dialBase);
  this.dial=new THREE.Group();this.dial.position.z=.14;this.dialBase.add(this.dial);for(let i=0;i<60;i++){const a=i/60*Math.PI*2;const len=i%5===0?.072:.032;const tick=new THREE.Mesh(new THREE.BoxGeometry(.008,len,.006),m.gold);tick.position.set(Math.sin(a)*(.57-len/2),Math.cos(a)*(.57-len/2),0);tick.rotation.z=-a;this.dial.add(tick);}
  const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#c1b482';ctx.font='21px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';for(let i=0;i<12;i++){const a=i/12*Math.PI*2;ctx.fillText(String(i*5).padStart(2,'0'),256+Math.sin(a)*182,256-Math.cos(a)*182);}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const num=new THREE.Mesh(new THREE.PlaneGeometry(1.16,1.16),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));num.position.z=.011;this.dial.add(num);
  this.cyl(.352,.09,m.dark,0,0,.01,this.dial);this.cyl(.332,.10,m.brass,0,0,.071,this.dial);this.cyl(.274,.07,m.gold,0,0,.15,this.dial);this.ring(.28,.012,m.dark,0,0,.192,this.dial);this.cyl(.237,.009,m.brass,0,0,.19,this.dial);for(let i=0;i<64;i++){const a=i/64*Math.PI*2;this.box(.013,.027,.072,m.gold,Math.sin(a)*.327,Math.cos(a)*.327,.104,this.dial);}
  const star=new THREE.Group();for(let i=0;i<4;i++){const bar=this.box(.012,.145,.008,m.dark,0,0,.199,star);bar.rotation.z=i*Math.PI/4;}this.dial.add(star);const pointer=new THREE.Mesh(new THREE.ConeGeometry(.034,.066,3),m.gold);pointer.rotation.z=Math.PI;pointer.position.set(0,.733,.081);this.dialBase.add(pointer);
  this.dialHit=this.cyl(.66,.04,new THREE.MeshBasicMaterial({visible:false}),0,0,.26,this.dialBase);
  this.cyl(.139,.044,m.brass,2.20,.01,.164);this.cyl(.09,.085,m.dark,2.20,.01,.222);const handle=this.rounded(.13,.65,.105,.057,m.brass);handle.position.set(2.20,.22,.32);handle.rotation.z=-.10;this.door.add(handle);this.ring(.165,.01,m.gold,2.20,.01,.19);
  const plate=this.rounded(1.1,.30,.018,.035,m.brass);plate.position.set(1.29,.91,.14);this.door.add(plate);const name=this.label('O R P H E U S',.97,.19,65,'#273022');name.position.set(1.29,.925,.185);this.door.add(name);this.nameLabel=name;
  const desc=this.label('ACOUSTIC SECURITY · 1924',1.53,.15,38,'#b1a676','monospace');desc.position.set(1.39,-.91,.162);this.door.add(desc);this.serial=desc;
  this.leds=[];for(let i=0;i<3;i++){this.cyl(.06,.014,m.brass,.93+i*.24,-.63,.149);const led=this.cyl(.039,.018,new THREE.MeshStandardMaterial({color:0x485641,emissive:0x597840,emissiveIntensity:0}),.93+i*.24,-.63,.165);this.leds.push(led);}
  for(const z of[-.82,.80]){const strip=this.box(.016,2.48,.035,m.brass,1.526,0,z);strip.rotation.y=Math.PI/2;}for(let i=0;i<12;i++)this.box(.022,.019,.46,m.dark,1.528,-.67+i*.105,-.07);const sideLabel=this.label('R V / 0 1',.65,.2,80,'#bca671','monospace');sideLabel.rotation.y=Math.PI/2;sideLabel.position.set(1.53,.69,.01);this.vault.add(sideLabel);
  this.resonanceRing=this.ring(.78,.012,new THREE.MeshBasicMaterial({color:0xd0c08c,transparent:true,opacity:0}),0,0,.12,this.dialBase);
  this.artifact=new THREE.Group();this.artifact.position.set(0,.13,-.25);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.32,0),new THREE.MeshPhysicalMaterial({color:0xd9b95f,metalness:.1,roughness:.14,transmission:.2,emissive:0x9c7930,emissiveIntensity:.8}));this.artifact.add(crystal);const ar=this.ring(.46,.014,m.gold,0,0,0,this.artifact);ar.rotation.x=.6;const ar2=this.ring(.49,.008,m.gold,0,0,0,this.artifact);ar2.rotation.y=.9;this.vault.add(this.artifact);
  const dustG=new THREE.BufferGeometry();const pos=new Float32Array(100*3);for(let i=0;i<100;i++){pos[i*3]=(Math.random()-.5)*12;pos[i*3+1]=Math.random()*6-1.4;pos[i*3+2]=(Math.random()-.5)*9;}dustG.setAttribute('position',new THREE.BufferAttribute(pos,3));this.dust=new THREE.Points(dustG,new THREE.PointsMaterial({color:0xb2b88d,size:.013,transparent:true,opacity:.38,sizeAttenuation:true}));this.scene.add(this.dust);
 }
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 bind(){let start=null,mode='orbit',prevAngle=0;const el=this.renderer.domElement;el.addEventListener('pointerdown',e=>{this.host.focus({preventScroll:true});const r=el.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObject(this.dialHit);mode=hit.length&&this.tool==='listen'&&this.phase===0?'dial':'orbit';start={x:e.clientX,y:e.clientY,moved:false};prevAngle=this.angle;el.setPointerCapture(e.pointerId);el.style.cursor=mode==='dial'?'grabbing':'move';});el.addEventListener('pointermove',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start.moved=start.moved||Math.abs(dx)+Math.abs(dy)>3;if(mode==='dial'){this.onDial(Math.round((prevAngle+dx*.7-dy*.45+720)%360));}else{this.yaw=Math.max(-1.12,Math.min(1.15,this.yaw+e.movementX*.005));this.pitch=Math.max(-.12,Math.min(.55,this.pitch+e.movementY*.003));}});const release=e=>{if(start&&!start.moved)this.onInteract(this.tool);start=null;el.style.cursor='grab';};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',()=>{start=null;});el.addEventListener('wheel',e=>{e.preventDefault();this.targetZoom=Math.max(5.1,Math.min(11,this.targetZoom+e.deltaY*.006));},{passive:false});el.style.cursor='grab';}
 setCase(index){const colors=[0x394439,0x274348,0x555047];this.mats.body.color.setHex(colors[index]);this.mats.face.color.setHex([0x29342c,0x23393b,0x3f3b32][index]);const names=['O R P H E U S','N A U T I L U S','S E L E N E'];const label=this.label(names[index],.97,.19,index===1?57:65,'#273022');label.position.copy(this.nameLabel.position);this.door.remove(this.nameLabel);this.nameLabel=label;this.door.add(label);this.targetOpen=0;this.open=0;this.resetView();}
 setState({angle,phase,pins,listening,signal,complete}){this.angle=angle;this.phase=phase;this.listening=listening;this.signal=signal;this.targetOpen=complete?-1.8:0;for(let i=0;i<3;i++){this.leds[i].material.emissiveIntensity=(phase>0||i<pins)?1.6:0;this.leds[i].material.color.setHex((phase>0||i<pins)?0xbfc992:0x485641);}this.opening.visible=!complete;}
 resetView(){this.yaw=.26;this.pitch=.1;this.targetZoom=this.host.clientWidth<500?10.1:8.3;}
 focus(){this.yaw=.02;this.pitch=0;this.targetZoom=this.targetZoom<7?8.3:5.7;}
 animate=()=>{requestAnimationFrame(this.animate);const t=performance.now()*.001;this.zoom+=(this.targetZoom-this.zoom)*.06;this.open+=(this.targetOpen-this.open)*.04;this.door.rotation.y=this.open;this.dial.rotation.z=-this.angle*Math.PI/180;const aspect=this.camera.aspect;const responsive=aspect<1?1.13:1;const z=this.zoom*responsive;this.camera.position.set(Math.sin(this.yaw)*z,1.18+this.pitch*5,Math.cos(this.yaw)*z);this.camera.lookAt(0,-.12,0);this.resonanceRing.material.opacity=this.listening?.12+this.signal*.28+(this.lowMotion?0:Math.sin(t*4)*.06):0;const scale=1+(this.lowMotion?0:Math.sin(t*3)*.015);this.resonanceRing.scale.setScalar(scale);if(!this.lowMotion){this.artifact.rotation.y=t*.2;this.artifact.position.y=.13+Math.sin(t)*.04;this.dust.rotation.y=t*.006;}this.renderer.render(this.scene,this.camera);};
}
