import * as THREE from './vendor/three.module.js';
import * as CANNON from './vendor/cannon-es.js';

const $ = id => document.getElementById(id);
const ui = Object.fromEntries(['height','score','best','start-card','action-dock','phase-label','combo','toast','cat-speech','drop','rotate','steady','slow','steady-count','slow-count','stability-fill','stability-word','stability-tip','goal-fill','goal-count','goal-title','goal-text','session-mode','wind-label','wind-detail','wind-icon','material-pill','block-name','block-description','material-friction','material-weight','block-preview'].map(id=>[id,$(id)]));
const MODES = {
  classic: {name:'经典模式',speed:1.02,wind:.14,target:20,tools:2,description:'搭到 20 层，让小猫摘颗星星。'},
  cozy: {name:'悠闲模式',speed:.62,wind:0,target:0,tools:4,description:'没有终点，慢慢搭出你的天空。'},
  storm: {name:'暴风挑战',speed:1.18,wind:.9,target:20,tools:2,description:'90 秒内，在阵风中挑战 20 层。'}
};
const MATERIALS={
  wood:{name:'温暖的木头',label:'木质积木',desc:'稳稳当当，适合打个好基础。',color:0xe9b86e,mass:1,friction:.68,h:.67,w:2.55,d:2.05},
  mint:{name:'薄荷小方糖',label:'木质积木',desc:'宽宽的肩膀，多一点安全感。',color:0x99c7ad,mass:1.1,friction:.7,h:.63,w:2.8,d:2.05},
  coral:{name:'落日小砖块',label:'木质积木',desc:'换个方向，让高塔更有个性。',color:0xeb9b80,mass:1,friction:.65,h:.7,w:2.45,d:2.05},
  ice:{name:'滑溜溜的冰块',label:'冰晶积木',desc:'轻轻放！光滑的表面容易打滑。',color:0xa7dce5,mass:.8,friction:.12,h:.63,w:2.5,d:2.05},
  stone:{name:'有分量的小石头',label:'石质积木',desc:'沉甸甸的，尽量放在正中间。',color:0xa9aabc,mass:1.8,friction:.75,h:.72,w:2.35,d:2.0},
  long:{name:'柠檬小长条',label:'长条积木',desc:'长长的一块，旋转后更好找平衡。',color:0xe8ce78,mass:1.05,friction:.65,h:.58,w:3.1,d:1.55}
};
const sequence=['wood','mint','coral','long','wood','ice','mint','stone','coral','long','ice','mint','stone'];
let mode='classic',phase='ready',paused=false,score=0,layers=0,perfects=0,combo=0,toolsLeft={steady:2,slow:2};
let runTime=0,worldTime=0,moveTime=0,slowUntil=0,settleTimer=0,dropTime=0,resultCountdown=-1,toastUntil=0,lastMaterial='wood';
let active=null,falling=null,axis='x',aimOffset=0,rotation=0,windValue=0,windDirection=1,highest=0,catHop=0,cozySaves=2;
let cameraAngle=.65,cameraTargetAngle=.65,zoom=1,currentTargetY=2.5,elapsed=0,lastFrame=performance.now(),danger=0;
let audioEnabled=false,audioContext=null;const keys=new Set(),blocks=[],particles=[],clouds=[];
let records={classic:0,cozy:0,storm:0};try{records={...records,...JSON.parse(localStorage.getItem('cat-stack-records')||'{}')};}catch{}

const scene=new THREE.Scene();scene.background=new THREE.Color('#e9f0e6');scene.fog=new THREE.Fog('#e9f0e6',25,60);
const host=$('scene');let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){host.innerHTML='<div style="padding:120px 35px;text-align:center">这个浏览器还不能显示 3D 场景，请用支持 WebGL 的现代浏览器打开。</div>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;host.appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-8,8,8,-8,.1,100);camera.position.set(10,9,13);
scene.add(new THREE.HemisphereLight(0xfffbec,0xb5c4ad,1.8));const sunlight=new THREE.DirectionalLight(0xfff8e9,2.3);sunlight.position.set(-5,14,8);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-13;sunlight.shadow.camera.right=13;sunlight.shadow.camera.top=20;sunlight.shadow.camera.bottom=-10;sunlight.shadow.camera.far=40;sunlight.shadow.bias=-.0004;sunlight.shadow.normalBias=.035;sunlight.shadow.radius=4;scene.add(sunlight);scene.add(sunlight.target);
const fill=new THREE.DirectionalLight(0xdcf5ff,.7);fill.position.set(6,7,-8);scene.add(fill);
const standard=(color,more={})=>new THREE.MeshStandardMaterial({color,roughness:.78,metalness:0,...more});
const colors={cream:0xffeac7,orange:0xe6a062,pink:0xe4aa9f,dark:0x494c43,white:0xfff3da};
const mats=Object.fromEntries(Object.entries(colors).map(([n,c])=>[n,standard(c)]));
function mesh(geo,mat,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(sx,sy,sz,mat,x,y,z,parent){const m=mesh(new THREE.SphereGeometry(1,24,16),mat,x,y,z,parent);m.scale.set(sx,sy,sz);return m;}
function box(w,h,d,color,x,y,z,parent=scene){return mesh(roundGeo(w,h,d,.08),typeof color==='number'?standard(color):color,x,y,z,parent);}
function roundGeo(w,h,d,r=.055){const shape=new THREE.Shape(),x=-w/2+r,y=-h/2+r,ww=w-2*r,hh=h-2*r;shape.moveTo(x,y);shape.lineTo(x+ww,y);shape.lineTo(x+ww,y+hh);shape.lineTo(x,y+hh);shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth:d-2*r,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:r,bevelThickness:r,curveSegments:1});g.translate(0,0,-d/2+r);g.computeVertexNormals();return g;}
function tube(points,radius,mat,parent=scene){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));return mesh(new THREE.TubeGeometry(curve,20,radius,8,false),mat,0,0,0,parent);}
// The entire garden is built as a playable 3D toy scene, without remote model dependencies.
const floor=mesh(new THREE.PlaneGeometry(180,180),standard(0xe9edda),0,-.18,0);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
const island=new THREE.Group();scene.add(island);
mesh(new THREE.CylinderGeometry(6.0,5.8,.56,96),standard(0xe3a58c),0,-.08,0,island);
mesh(new THREE.CylinderGeometry(6.04,6.04,.18,96),standard(0xf0c3a6),0,.27,0,island);
mesh(new THREE.CylinderGeometry(5.96,5.96,.1,96),standard(0xf5d3b5),0,.39,0,island);
const topRing=mesh(new THREE.TorusGeometry(5.63,.025,6,96),standard(0xe8b89b),0,.45,0,island);topRing.rotation.x=Math.PI/2;
const base=box(3.65,.35,3.15,0xf1dcae,0,.59,0);box(3.45,.12,2.95,0xf9e7bd,0,.81,0);
// Tiny surface decorations keep the playing silhouette clean.
for(const [x,z,scale,c] of [[4.1,1.8,.55,0x95bca1],[-3.9,-1.6,.7,0xa9c4a1],[3.2,-3.6,.8,0x88b598],[-4.6,1.0,.35,0xb0c7a2]]){
 const pot=new THREE.Group();pot.position.set(x,.47,z);scene.add(pot);mesh(new THREE.CylinderGeometry(.34*scale,.28*scale,.48*scale,16),standard(0xd9b18b),0,.24*scale,0,pot);sphere(.53*scale,.56*scale,.48*scale,standard(c),0,.8*scale,0,pot);sphere(.3*scale,.37*scale,.32*scale,standard(c),.27*scale,1.12*scale,0,pot);
}
const spare1=box(1.0,.52,.8,0xa6c6b0,3.65,.72,2.2);spare1.rotation.y=.3;
const spare2=box(.8,.42,.65,0xe4bc70,3.7,1.19,2.23);spare2.rotation.y=-.3;
const spare3=box(1.2,.4,.7,0xe7ac8c,-2.1,.65,3.6);spare3.rotation.y=-.3;
const spare4=box(.7,.7,.65,0x9abebc,-3.3,.8,-2.4);spare4.rotation.y=.45;
for(let i=0;i<14;i++){const a=i*2.39;const rad=7.8+(i%3)*2.4;const stone=sphere(.2+.05*(i%3),.13,.15,standard(i%2?0xc9d3b6:0xd8d8bf),Math.cos(a)*rad,-.04,Math.sin(a)*rad);stone.rotation.y=a;}
for(const [x,y,z,s] of [[-8,5,-8,1.2],[5,7,-10,1.05],[-6,8,-14,.7],[10,4,-7,.6]]){const cloud=new THREE.Group();cloud.position.set(x,y,z);scene.add(cloud);const cm=standard(0xfcfcf4);sphere(1.2*s,.46*s,.56*s,cm,0,0,0,cloud);sphere(.63*s,.6*s,.55*s,cm,-.4*s,.22*s,0,cloud);sphere(.7*s,.76*s,.6*s,cm,.36*s,.32*s,0,cloud);clouds.push({mesh:cloud,x});}

// A tiny expressive low-poly kitten, with animated paws and tail.
const cat=new THREE.Group();cat.position.set(-2.65,.47,2.15);cat.rotation.y=.5;scene.add(cat);
sphere(.6,.72,.46,mats.orange,0,.69,0,cat);sphere(.4,.53,.38,mats.cream,0,.68,.28,cat);
sphere(.26,.17,.36,mats.white,-.34,.17,.28,cat);sphere(.26,.17,.36,mats.white,.34,.17,.28,cat);
const catHead=new THREE.Group();catHead.position.set(0,1.44,.03);cat.add(catHead);
sphere(.73,.64,.59,mats.orange,0,0,0,catHead);sphere(.58,.43,.22,mats.cream,0,-.17,.43,catHead);
for(const side of [-1,1]){const ear=mesh(new THREE.ConeGeometry(.35,.69,3),mats.orange,side*.48,.53,-.02,catHead);ear.rotation.z=-side*.2;ear.rotation.y=side*.12;const inner=mesh(new THREE.ConeGeometry(.21,.44,3),mats.pink,side*.49,.55,.12,catHead);inner.rotation.z=-side*.2;
 sphere(.096,.14,.06,mats.dark,side*.27,.045,.535,catHead);sphere(.026,.037,.02,mats.white,side*.25,.083,.588,catHead);sphere(.13,.07,.022,mats.pink,side*.43,-.16,.52,catHead);
 for(let j=0;j<2;j++)tube([[side*.37,-.21-j*.09,.565],[side*.64,-.17-j*.14,.6],[side*.8,-.13-j*.16,.55]],.009,standard(0xb58864),catHead);
}
const nose=mesh(new THREE.ConeGeometry(.072,.07,3),mats.pink,0,-.16,.64,catHead);nose.rotation.z=Math.PI;
tube([[0,-.2,.64],[0,-.28,.64],[-.09,-.3,.6]],.012,mats.dark,catHead);tube([[0,-.26,.64],[.07,-.31,.63],[.11,-.29,.61]],.012,mats.dark,catHead);
for(let i=-1;i<=1;i++){const stripe=box(.075,.2,.025,0xc28b59,i*.16,.39,.51,catHead);stripe.rotation.z=i*.2;}
const scarf=mesh(new THREE.TorusGeometry(.43,.09,8,36),standard(0x93bca9),0,1.04,.05,cat);scarf.rotation.x=Math.PI/2;box(.15,.38,.08,0x83ac9c,.23,.9,.45,cat).rotation.z=-.3;
const pawLeft=new THREE.Group();pawLeft.position.set(-.5,.95,.06);cat.add(pawLeft);sphere(.18,.37,.2,mats.orange,0,-.17,.1,pawLeft);sphere(.17,.17,.19,mats.cream,0,-.38,.13,pawLeft);
const pawRight=new THREE.Group();pawRight.position.set(.5,.95,.06);cat.add(pawRight);sphere(.18,.37,.2,mats.orange,0,-.17,.1,pawRight);sphere(.17,.17,.19,mats.cream,0,-.38,.13,pawRight);
const tail=new THREE.Group();tail.position.set(0,.35,-.3);cat.add(tail);tube([[0,0,0],[-.6,.1,-.2],[-1,.48,-.1],[-1.05,.9,.15],[-.85,1.0,.25]],.13,mats.orange,tail);
// A little toy mouse beside the builder.
sphere(.18,.12,.28,standard(0xb7baa7),-2.5,.56,3.1);tube([[-2.5,.56,3.35],[-2.4,.53,3.6],[-2.1,.49,3.6]],.013,standard(0xacad9c));

const world=new CANNON.World({gravity:new CANNON.Vec3(0,-13.5,0),allowSleep:true});world.solver.iterations=30;world.solver.tolerance=.001;world.broadphase=new CANNON.SAPBroadphase(world);world.defaultContactMaterial.friction=.65;world.defaultContactMaterial.restitution=.015;
const physicsMaterials={};for(const [name,data] of Object.entries(MATERIALS))physicsMaterials[name]=new CANNON.Material(name);
for(const [a,ma] of Object.entries(physicsMaterials))for(const [b,mb] of Object.entries(physicsMaterials)){world.addContactMaterial(new CANNON.ContactMaterial(ma,mb,{friction:Math.min(MATERIALS[a].friction,MATERIALS[b].friction),restitution:.005,contactEquationStiffness:1e7,contactEquationRelaxation:5}));}
const groundBody=new CANNON.Body({mass:0,shape:new CANNON.Plane(),material:physicsMaterials.wood});groundBody.quaternion.setFromEuler(-Math.PI/2,0,0);groundBody.position.y=.46;world.addBody(groundBody);
const pedestal=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(1.825,.21,1.575)),material:physicsMaterials.wood,position:new CANNON.Vec3(0,.67,0)});world.addBody(pedestal);
const geoCache={},matCache={};
function blockMesh(type){const data=MATERIALS[type];if(!geoCache[type])geoCache[type]=roundGeo(data.w,data.h,data.d,.055);if(!matCache[type])matCache[type]=standard(data.color,type==='ice'?{transparent:true,opacity:.8,roughness:.2,metalness:.02}:{});const group=new THREE.Group();const cube=mesh(geoCache[type],matCache[type],0,0,0,group);group.userData.type=type;
 // Inlaid stripes on the toy block emphasize its shape and rotation.
 const decalMat=standard(type==='ice'?0xe2f9f7:type==='stone'?0xc9c9d7:0xffe9b7,{transparent:true,opacity:type==='stone'?.35:.32});
 for(const side of [-1,1]){const stripe=mesh(new THREE.BoxGeometry(data.w*.71,.012,.012),decalMat,0,side*data.h*.31,data.d/2+.005,group);stripe.castShadow=false;}
 if(type==='ice'){const shard=mesh(new THREE.OctahedronGeometry(.14,0),standard(0xebffff,{transparent:true,opacity:.65}),0,0,data.d/2+.005,group);shard.scale.set(1,1,.08);}else{for(const [x,y,r] of [[-.1,.03,.05],[.02,.03,.05],[-.04,-.04,.07]]){const dot=mesh(new THREE.CircleGeometry(r,12),decalMat,x,y,data.d/2+.01,group);dot.castShadow=false;}}
 scene.add(group);return group;}
function addBlock(type,x,y,z,yaw=0,seed=false){const data=MATERIALS[type],m=blockMesh(type);m.position.set(x,y,z);m.rotation.y=yaw;const body=new CANNON.Body({mass:data.mass,material:physicsMaterials[type],shape:new CANNON.Box(new CANNON.Vec3(data.w/2,data.h/2,data.d/2)),position:new CANNON.Vec3(x,y,z),linearDamping:.2,angularDamping:.38,sleepTimeLimit:.6,sleepSpeedLimit:.075});body.quaternion.setFromEuler(0,yaw,0);world.addBody(body);const b={mesh:m,body,type,data,yaw,seed,accepted:seed,contact:false,hitGround:false,perfect:false};blocks.push(b);body.addEventListener('collide',event=>{if(event.body===groundBody)b.hitGround=true;if(event.body!==groundBody&&event.contact.ni.y!==0){b.contact=true;if(b===falling&&body.velocity.length()>1.0)playSound('land');}});return b;}
function disposeGroup(g){g.traverse(o=>{if(o.isMesh&&!Object.values(geoCache).includes(o.geometry))o.geometry.dispose();});scene.remove(g);}
function clearBlocks(){for(const b of blocks){world.removeBody(b.body);disposeGroup(b.mesh);}blocks.length=0;if(active){disposeGroup(active);active=null;}falling=null;}
function towerTop(){let top=.88,block=null;for(const b of blocks){if(!b.accepted)continue;if(b.body.position.y+b.data.h/2>top){top=b.body.position.y+b.data.h/2;block=b;}}return {height:top,block,x:block?.body.position.x||0,z:block?.body.position.z||0};}
const ghost=new THREE.Group();scene.add(ghost);const ghostFill=mesh(new THREE.BoxGeometry(1,.025,1),new THREE.MeshBasicMaterial({color:0xfdf1bc,transparent:true,opacity:.28,depthWrite:false}),0,0,0,ghost);ghostFill.castShadow=false;ghostFill.receiveShadow=false;
const guideMaterial=new THREE.LineDashedMaterial({color:0x98aa83,dashSize:.11,gapSize:.12,transparent:true,opacity:.7});const guide=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,2,0)]),guideMaterial);guide.computeLineDistances();scene.add(guide);
function createActive(){if(active)disposeGroup(active);lastMaterial=sequence[layers%sequence.length];active=blockMesh(lastMaterial);active.userData.active=true;rotation=layers%2?Math.PI/2:0;active.rotation.y=rotation;axis=layers%2?'z':'x';aimOffset=0;moveTime=Math.PI*.55+layers*.93;phase='aiming';falling=null;settleTimer=0;updateMaterial();updateHUD();}
function reset(preview=false){clearBlocks();for(const p of particles)scene.remove(p.mesh);particles.length=0;runTime=0;moveTime=0;score=0;layers=0;perfects=0;combo=0;highest=0;resultCountdown=-1;slowUntil=0;danger=0;windValue=0;cozySaves=2;paused=false;keys.clear();toolsLeft={steady:MODES[mode].tools,slow:MODES[mode].tools};for(const d of document.querySelectorAll('dialog[open]'))d.close();
 let y=.88;const starters=preview?['mint','wood','coral','mint','wood','long']:['mint','wood'];starters.forEach((type,i)=>{const data=MATERIALS[type];y+=data.h/2;const b=addBlock(type,preview?Math.sin(i*1.3)*.19:0,y,preview?Math.cos(i*1.9)*.1:0,i%2?Math.PI/2:0,true);b.body.sleep();y+=data.h/2;});
 currentTargetY=preview?2.8:2.45;cameraTargetAngle=.65;zoom=1;ui['start-card'].hidden=!preview;ui['action-dock'].hidden=preview;ui.combo.textContent='';ui['cat-speech'].textContent=preview?'喵～一起把云朵垫高一点！':'轻轻放，第一块一定没问题。';phase=preview?'ready':'aiming';createActive();if(preview)phase='ready';updateHUD();}
function startGame(){audioContext?.resume();reset(false);window.scrollTo({top:0,behavior:'instant'});playSound('start');showToast(mode==='storm'?'90 秒挑战开始，小心阵风！':mode==='cozy'?'慢慢来，今天没有终点。':'看准中心，按空格放下');}
function drop(){if(phase==='ready'){startGame();return;}if(phase!=='aiming'||paused||document.querySelector('dialog[open]')||!active)return;const p=active.position.clone();const top=towerTop();const data=MATERIALS[lastMaterial];const offset=Math.hypot(p.x-top.x,p.z-top.z);disposeGroup(active);active=null;falling=addBlock(lastMaterial,p.x,p.y,p.z,rotation);falling.perfect=offset<.25;falling.offset=offset;phase='falling';dropTime=runTime;settleTimer=0;catHop=.3;playSound('drop');updateHUD();}
function acceptBlock(){const b=falling;if(!b||b.accepted)return;b.accepted=true;layers++;highest=Math.max(highest,layers);if(b.perfect){perfects++;combo++;score+=100+50*Math.min(combo,5);ui.combo.textContent=`精准！ ${combo>1?'× '+combo:'✦'}`;burst(b.mesh.position,0xffd777,16);catHop=1;playSound('perfect');if(combo===3){toolsLeft.slow=Math.min(toolsLeft.slow+1,5);showToast('3 连击！获得一次慢动作');}ui['cat-speech'].textContent=['喵！你是天生的建筑师！','稳稳的，我的小心脏放心啦。','这块放得太漂亮了！'][layers%3];}else{combo=0;score+=Math.max(35,100-Math.round(b.offset*30));ui.combo.textContent='';playSound('land');ui['cat-speech'].textContent=b.offset>.8?'哎呀，爪爪都紧张了……':'再来一块，离云朵更近啦。';}
 if(layers>records[mode]){records[mode]=layers;try{localStorage.setItem('cat-stack-records',JSON.stringify(records));}catch{}}
 if(layers%5===0){showToast(`第 ${layers} 层！小猫为你撒花 ✦`);burst(b.mesh.position,0xb7d8a7,25);}
 if(MODES[mode].target&&layers>=MODES[mode].target){finish(true,'你真的把云朵垫高了！');return;}falling=null;createActive();updateHUD();}
function finish(won=false,reason='积木滑下来啦，下次一定搭得更高。'){if(phase==='ended')return;phase='ended';if(active){disposeGroup(active);active=null;}ghost.visible=false;guide.visible=false;ui['action-dock'].hidden=true;resultCountdown=won?.8:1.75;ui['phase-label'].textContent=won?'星星收集成功！':'高塔倒下了';$('result-height').textContent=layers;$('result-score').textContent=score;$('result-perfect').textContent=perfects;$('result-title').textContent=won?'小猫摸到星星啦！':'小猫已经很努力啦！';$('result-eyebrow').textContent=won?'20 层的小小奇迹':'每一次倒下，都是新的开始';$('result-emoji').textContent=won?'✧':'ฅ';$('result-note').textContent=reason;ui['cat-speech'].textContent=won?'这是我们的天空！喵呜～':'没关系，我还想和你再搭一次。';playSound(won?'win':'fail');if(won){for(let i=0;i<4;i++)burst(new THREE.Vector3((i-2)*1.5,towerTop().height+1,0),[0xebad73,0x9cc6a6,0xdfab9d][i%3],28);}updateHUD();}
function recoverCozy(){if(mode!=='cozy'||!cozySaves||!falling)return false;cozySaves--;world.removeBody(falling.body);disposeGroup(falling.mesh);blocks.splice(blocks.indexOf(falling),1);falling=null;showToast(`小猫接住了！还剩 ${cozySaves} 次补救`);createActive();return true;}
function rotate(){if(phase!=='aiming'||paused||!active)return;rotation+=Math.PI/2;active.rotation.y=rotation;playSound('tick');}
function steady(){if(phase!=='aiming'||paused||!toolsLeft.steady)return;const candidates=blocks.filter(b=>b.accepted&&!b.seed);const b=candidates.at(-1);if(!b){showToast('先搭上一层，猫爪才能帮忙哦');return;}const i=blocks.indexOf(b);const under=blocks[i-1];toolsLeft.steady--;b.body.position.set(under.body.position.x,under.body.position.y+under.data.h/2+b.data.h/2+.008,under.body.position.z);b.body.quaternion.setFromEuler(0,b.yaw,0);b.body.velocity.setZero();b.body.angularVelocity.setZero();b.body.wakeUp();b.mesh.position.copy(b.body.position);b.mesh.quaternion.copy(b.body.quaternion);burst(b.mesh.position,0xc8ecba,24);showToast('猫爪轻轻一扶，稳住啦！');catHop=.7;playSound('magic');updateHUD();}
function slow(){if(phase!=='aiming'||paused||!toolsLeft.slow||slowUntil>runTime)return;toolsLeft.slow--;slowUntil=runTime+5;showToast('慢一点嘛……5 秒从容时光');playSound('magic');updateHUD();}
function togglePause(){if(!['aiming','falling'].includes(phase))return;paused=!paused;if(paused)$('pause-dialog').showModal();else $('pause-dialog').close();keys.clear();updateHUD();}
function showToast(text){ui.toast.textContent=text;ui.toast.classList.add('visible');toastUntil=elapsed+3.1;}
function updateMaterial(){const data=MATERIALS[lastMaterial];ui['material-pill'].textContent=data.label;ui['block-name'].textContent=data.name;ui['block-description'].textContent=data.desc;ui['material-friction'].textContent=data.friction<.3?'低摩擦 · 易滑动':'高摩擦';ui['material-weight'].textContent=`重量 ${data.mass.toFixed(1)}`;const color='#'+new THREE.Color(data.color).getHexString();const block=ui['block-preview'].querySelector('.iso-block');block.style.background=color;block.style.boxShadow=`11px 12px 0 ${'#'+new THREE.Color(data.color).multiplyScalar(.79).getHexString()},14px 19px 18px #836e3a18`;block.style.width=lastMaterial==='long'?'100px':'77px';block.style.opacity=lastMaterial==='ice'?'.7':'1';}
function updateHUD(){ui.height.textContent=layers;ui.score.textContent=String(score).padStart(4,'0');ui.best.textContent=records[mode]||0;ui['steady-count'].textContent=toolsLeft.steady;ui['slow-count'].textContent=toolsLeft.slow;ui.steady.disabled=phase!=='aiming'||!toolsLeft.steady||paused;ui.slow.disabled=phase!=='aiming'||!toolsLeft.slow||paused||slowUntil>runTime;ui.drop.disabled=phase!=='aiming'||paused;ui.rotate.disabled=phase!=='aiming'||paused;ui.drop.innerHTML=phase==='falling'?'等它站稳…':'放下积木 <kbd>SPACE</kbd>';ui['phase-label'].textContent=phase==='ready'?'小猫已就位':phase==='aiming'?'看准时机，轻轻放下':phase==='falling'?'嘘……等积木站稳':phase==='ended'?'这一局结束啦':'休息一下';if(paused)ui['phase-label'].textContent='小猫休息中';ui['goal-fill'].style.width=(MODES[mode].target?Math.min(100,layers/MODES[mode].target*100):(layers%10)*10)+'%';ui['goal-count'].textContent=MODES[mode].target?`${layers} / ${MODES[mode].target}`:`${layers} / ∞`;ui['goal-title'].textContent=mode==='cozy'?'慢慢搭，没有终点':mode==='storm'?'和风赛跑':'向云朵出发';ui['goal-text'].textContent=MODES[mode].description;ui['session-mode'].textContent=`${MODES[mode].name} · ${MODES[mode].target?'目标 20 层':'无限搭建'}`;}
function burst(position,color,count){for(let i=0;i<count;i++){const m=mesh(new THREE.OctahedronGeometry(.05+Math.random()*.035),standard(color),position.x,position.y,position.z);m.castShadow=false;particles.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*3,1+Math.random()*3,(Math.random()-.5)*3),life:1.2+Math.random()*.7});}}
function playSound(kind){if(!audioEnabled)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();const notes={tick:[550],drop:[320,240],land:[190,270],perfect:[660,880,1100],start:[440,550,660],magic:[520,780,1040],win:[523,659,784,1047],fail:[390,310,220]}[kind]||[400];notes.forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=kind==='land'?'triangle':'sine';o.frequency.value=f;o.connect(g);g.connect(audioContext.destination);const t=audioContext.currentTime+i*.085;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.07,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.start(t);o.stop(t+.24);});}catch{}}

function update(dt){elapsed+=dt;worldTime+=dt;const running=['aiming','falling'].includes(phase)&&!paused;
 if(running)runTime+=dt;
 if(!paused&&phase!=='ready'){world.step(1/90,dt,5);for(const b of blocks){b.mesh.position.copy(b.body.position);b.mesh.quaternion.copy(b.body.quaternion);}}
 const top=towerTop();
 if(active){if(!paused){const speed=MODES[mode].speed*(1+layers*.035)*(slowUntil>runTime?.26:1);moveTime+=dt*speed;if(running){if(keys.has('ArrowLeft')||keys.has('a'))aimOffset=Math.max(-1.3,aimOffset-dt*1.4);if(keys.has('ArrowRight')||keys.has('d'))aimOffset=Math.min(1.3,aimOffset+dt*1.4);}}
 const sway=Math.sin(moveTime)*2.65+aimOffset;active.position.set(top.x+(axis==='x'?sway:0),top.height+1.9+MATERIALS[lastMaterial].h/2,top.z+(axis==='z'?sway:0));
 const data=MATERIALS[lastMaterial],rotated=Math.round(rotation/(Math.PI/2))%2;ghost.visible=phase!=='ready';guide.visible=phase!=='ready';ghostFill.scale.set(rotated?data.d:data.w,1,rotated?data.w:data.d);ghost.position.set(active.position.x,top.height+.04,active.position.z);const pts=[new THREE.Vector3(active.position.x,top.height+.05,active.position.z),new THREE.Vector3(active.position.x,active.position.y-data.h/2,active.position.z)];guide.geometry.setFromPoints(pts);guide.computeLineDistances();}else{ghost.visible=false;guide.visible=false;}
 if(running){
  if(phase==='falling'&&falling){const b=falling;const speed=b.body.velocity.length();const angular=b.body.angularVelocity.length();const up=new CANNON.Vec3();b.body.quaternion.vmult(new CANNON.Vec3(0,1,0),up);const stable=b.contact&&speed<.19&&angular<.22&&up.y>.8&&b.body.position.y>1.0;settleTimer=stable?settleTimer+dt:0;if(settleTimer>.36){acceptBlock();}
   else if(b.body.position.y<.88||Math.hypot(b.body.position.x,b.body.position.z)>5.8||runTime-dropTime>7){if(!recoverCozy())finish(false,runTime-dropTime>7?'积木迟迟站不稳。试试中心对齐，或换一个方向。':'这块积木没站稳，下一次轻轻放在中间。');}
  }
  const endangered=blocks.filter(b=>b.accepted&&(b.hitGround||b.body.position.y<.7));if(endangered.length)finish(false,'高塔失去平衡啦。猫爪扶正能帮顶层回到中心。');
  const maxLean=blocks.reduce((max,b)=>{const up=new CANNON.Vec3();b.body.quaternion.vmult(new CANNON.Vec3(0,1,0),up);return Math.max(max,b.accepted?1-up.y:0);},0);
  const drift=top.block?Math.hypot(top.x,top.z)/2.8:0;danger=THREE.MathUtils.lerp(danger,Math.min(1,maxLean*2.5+drift*.6),dt*4);
  if(mode==='storm'){const cycle=runTime%12;const blowing=cycle>=9;windDirection=Math.floor(runTime/12)%2? -1:1;windValue=blowing?MODES[mode].wind*(.8+layers*.1)*Math.sin((cycle-9)/3*Math.PI):0;if(cycle>7&&cycle<9){ui['wind-label'].textContent='阵风要来了！';ui['wind-detail'].textContent=`${windDirection>0?'向右':'向左'}吹 · 先把中心对齐`;ui['wind-icon'].style.color='#cf9763';}else{ui['wind-label'].textContent=blowing?'呼——抓稳啦！':'风暂时停下来啦';ui['wind-detail'].textContent=`剩余 ${Math.max(0,90-Math.floor(runTime))} 秒 · ${blowing?'风力 '+windValue.toFixed(1):'准备下一阵风'}`;ui['wind-icon'].style.color=blowing?'#cf9763':'#a1b1a0';}if(runTime>=90)finish(false,'时间到！这是小猫和风一起完成的作品。');}
  else{windValue=mode==='cozy'?0:Math.sin(runTime*.55)*MODES[mode].wind*Math.min(layers/6,1);ui['wind-label'].textContent=mode==='cozy'?'一整个晴朗的下午':'微风刚刚好';ui['wind-detail'].textContent=mode==='cozy'?`温柔补救 ${cozySaves} 次 · 慢慢来`:`风力 ${Math.abs(windValue).toFixed(1)} · 注意保持重心`;}
  if(Math.abs(windValue)>.01){for(const b of blocks){if(b.accepted){b.body.wakeUp();b.body.applyForce(new CANNON.Vec3(windValue*windDirection*b.data.mass*.6,0,windValue*.1),new CANNON.Vec3(0,b.data.h/2,0));}}}
  if(slowUntil>0&&slowUntil<=runTime){slowUntil=0;updateHUD();}if(slowUntil>runTime)ui['phase-label'].textContent=`慢动作 · ${Math.ceil(slowUntil-runTime)} 秒`;
 }
 ui['stability-fill'].style.left=`${Math.min(98,danger*100)}%`;ui['stability-word'].textContent=danger>.65?'小心呀！':danger>.3?'有点晃':'很稳哦';ui['stability-word'].style.color=danger>.65?'#c08d67':'#97b089';ui['stability-tip'].textContent=danger>.65?'试试猫爪扶正，或用旋转扩大支撑。':danger>.3?'下一块放在偏移的反方向试试看。':'让积木的中心尽量对齐。';
 if(resultCountdown>=0){resultCountdown-=dt;if(resultCountdown<0&&!$('result-dialog').open)$('result-dialog').showModal();}
 if(elapsed>toastUntil)ui.toast.classList.remove('visible');
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];if(!paused){p.life-=dt;p.v.y-=dt*3;p.mesh.position.addScaledVector(p.v,dt);p.mesh.rotation.x+=dt*3;p.mesh.rotation.y+=dt*2;p.mesh.scale.setScalar(Math.max(0,Math.min(1,p.life*2)));}if(p.life<0){scene.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();particles.splice(i,1);}}
 if(!paused){catHop=Math.max(0,catHop-dt*1.8);cat.position.y=.47+Math.sin(catHop*Math.PI)*.45;catHead.rotation.z=Math.sin(elapsed*1.5)*.055;catHead.rotation.y=Math.sin(elapsed*.7)*.09;tail.rotation.y=Math.sin(elapsed*2.5)*.24;pawRight.rotation.z=Math.sin(catHop*Math.PI)*-1.25;pawLeft.rotation.z=Math.sin(elapsed*2)*.04+Math.sin(catHop*Math.PI)*.6;cat.scale.y=1+Math.sin(elapsed*2)*.012;for(const cloud of clouds)cloud.mesh.position.x=cloud.x+Math.sin(elapsed*.09+cloud.x)*.6;}
 const targetY=phase==='ready'?3.1:Math.max(2.4,top.height*.55+.9);currentTargetY=THREE.MathUtils.lerp(currentTargetY,targetY,dt*2);cameraAngle=THREE.MathUtils.lerp(cameraAngle,cameraTargetAngle,dt*6);const mobile=host.clientWidth<600;const baseView=mobile?11.3:12.8;const aspect=host.clientWidth/host.clientHeight;const viewSize=Math.max(baseView,top.height+5,mobile?10.5/aspect:0)*zoom;camera.left=-viewSize*aspect/2;camera.right=viewSize*aspect/2;camera.top=viewSize/2;camera.bottom=-viewSize/2;camera.updateProjectionMatrix();const xOffset=phase==='ready'&&!mobile?-.75:0;camera.position.set(Math.sin(cameraAngle)*16+xOffset,currentTargetY+9,Math.cos(cameraAngle)*16);camera.lookAt(xOffset,currentTargetY,0);sunlight.target.position.y=Math.max(0,top.height-5);renderer.render(scene,camera);
}
function resize(){renderer.setSize(host.clientWidth,host.clientHeight);const dock=$('action-dock');if(innerWidth<=560){dock.style.top=(124+Math.max(615,Math.min(innerHeight-144,840))-116)+'px';}else if(innerWidth<=850){dock.style.top=(82+Math.max(innerHeight*.7,570)-130)+'px';}else dock.style.top='';}
new ResizeObserver(resize).observe(host);window.addEventListener('resize',resize);
let pointer=null;renderer.domElement.addEventListener('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(pointer){cameraTargetAngle-=(e.clientX-pointer.x)*.007;pointer.x=e.clientX;}});renderer.domElement.addEventListener('pointerup',()=>{pointer=null;});renderer.domElement.addEventListener('pointercancel',()=>{pointer=null;});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.0007,.75,1.5);},{passive:false});
$('start').addEventListener('click',startGame);$('drop').addEventListener('click',drop);$('rotate').addEventListener('click',rotate);$('steady').addEventListener('click',steady);$('slow').addEventListener('click',slow);$('pause').addEventListener('click',togglePause);$('resume').addEventListener('click',togglePause);$('restart').addEventListener('click',startGame);$('pause-restart').addEventListener('click',startGame);$('return').addEventListener('click',()=>reset(true));$('camera').addEventListener('click',()=>{cameraTargetAngle+=Math.PI/2;showToast('换个角度，看看你的高塔');});
$('help').addEventListener('click',()=>{if(['aiming','falling'].includes(phase))paused=true;$('help-dialog').showModal();keys.clear();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{b.closest('dialog').close();paused=false;updateHUD();}));$('help-dialog').addEventListener('cancel',()=>{paused=false;});$('pause-dialog').addEventListener('cancel',()=>{paused=false;updateHUD();});$('result-dialog').addEventListener('cancel',e=>e.preventDefault());
$('sound').addEventListener('click',()=>{audioEnabled=!audioEnabled;$('sound').classList.toggle('on',audioEnabled);$('sound').setAttribute('aria-label',audioEnabled?'关闭音效':'开启音效');$('sound').setAttribute('aria-pressed',String(audioEnabled));if(audioEnabled)playSound('perfect');showToast(audioEnabled?'音效已开启 ♪':'音效已关闭');});
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{if(mode===b.dataset.mode)return;mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(m=>m.classList.toggle('active',m===b));reset(true);showToast(mode==='cozy'?'悠闲时光：更慢、无风，还有两次补救':mode==='storm'?'暴风挑战：90 秒，留意阵风预告':'经典搭塔：向 20 层的星星出发');}));
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if([' ','arrowleft','arrowright','arrowup','arrowdown'].includes(key))e.preventDefault();if(document.querySelector('dialog[open]')){if(key==='p'&&$('pause-dialog').open&&!e.repeat)togglePause();return;}keys.add(e.key);keys.add(key);if(e.repeat)return;if(key===' ')drop();else if(key==='r')rotate();else if(key==='q')steady();else if(key==='e')slow();else if(key==='p')togglePause();});window.addEventListener('keyup',e=>{keys.delete(e.key);keys.delete(e.key.toLowerCase());});window.addEventListener('blur',()=>{keys.clear();if(['aiming','falling'].includes(phase)&&!paused)togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['aiming','falling'].includes(phase)&&!paused)togglePause();});
for(const [id,key] of [['aim-left','ArrowLeft'],['aim-right','ArrowRight']]){const button=$(id);button.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(key);button.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keys.delete(key));}
// A concise read-only state tool allows assistants to understand the live game.
function gameState(){return {mode,phase,paused,layers,score,perfects,combo,remainingTools:{...toolsLeft},remainingSeconds:mode==='storm'?Math.max(0,90-Math.floor(runTime)):null,best:records[mode],material:lastMaterial,axis,active:active?{x:active.position.x,y:active.position.y,z:active.position.z}:null,towerTop:towerTop().height};}
window.catStack={getState:gameState};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_cat_stack_state',title:'查看小猫搭塔状态',description:'Read the current game mode, score, height, material, tools and status without changing gameplay.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input&&Object.keys(input).length)throw new Error('This tool takes no arguments.');return gameState();}})).catch(()=>{});}catch{}}
reset(true);resize();function animate(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;update(dt);requestAnimationFrame(animate);}requestAnimationFrame(animate);
