import * as THREE from 'three';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import './style.css';
const $=id=>document.getElementById(id), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let stored={};try{stored=JSON.parse(localStorage.getItem('cat-stack')||'{}')}catch{}
let mode='classic',paused=false,ended=false,won=false,score=0,combo=0,best=stored.best||0,wallet=stored.wallet||0,braces=2,slows=2,slowUntil=0,time=0,lastTime=0,toastUntil=5,angle=.64,targetAngle=.64,drag=null,moving,falling=null,blocks=[],debris=[],particles=[],wind=0,bias=0,sound=true,goal=12,shake=0;
const host=$('scene'),scene=new THREE.Scene();scene.background=new THREE.Color('#555974');scene.fog=new THREE.Fog('#555974',24,65);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#555974');host.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,1,.1,120);const ambient=new THREE.HemisphereLight(0xe0e2ff,0x4d6d63,2.3);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffd6b9,3.2);sun.position.set(-7,14,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=15;sun.shadow.camera.bottom=-12;sun.shadow.normalBias=.04;scene.add(sun);const fill=new THREE.DirectionalLight(0xb9c9ff,1.3);fill.position.set(7,6,-6);scene.add(fill);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.83});const mats={grass:mat('#a5bfa7'),edge:mat('#718e82'),rock:mat('#666579'),cream:mat('#f6ddaf'),orange:mat('#ce946b'),pink:mat('#eeb1a4'),eye:mat('#35333b')};
function mesh(geo,material,parent=scene,x=0,y=0,z=0){let m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w,h,d,c,parent,x=0,y=0,z=0,r=.08){return mesh(new RoundedBoxGeometry(w,h,d,3,r),typeof c==='string'?mat(c):c,parent,x,y,z)}
function ball(r,c,parent,x,y,z,sx=1,sy=1,sz=1){let m=mesh(new THREE.SphereGeometry(r,24,16),typeof c==='string'?mat(c):c,parent,x,y,z);m.scale.set(sx,sy,sz);return m}
const island=new THREE.Group();scene.add(island);mesh(new THREE.CylinderGeometry(5.3,4.6,.55,9),mats.grass,island,0,-.3,0);mesh(new THREE.CylinderGeometry(4.6,2.9,1.8,9),mats.rock,island,0,-1.45,0);mesh(new THREE.ConeGeometry(3.0,2.1,8),mats.rock,island,0,-3.2,0).rotation.z=Math.PI;
const platform=mesh(new THREE.CylinderGeometry(2.0,2.1,.2,48),mat('#ded6b7'),scene,0,.1,0);mesh(new THREE.TorusGeometry(1.9,.022,8,64),mat('#f5e9cf'),scene,0,.215,0).rotation.x=Math.PI/2;
// Hand-built little orange cat, with paws, whiskers and a curled tail.
const cat=new THREE.Group();cat.position.set(-2.6,.03,1.25);cat.rotation.y=.22;scene.add(cat);ball(.52,mats.cream,cat,0,.61,0,.88,1.05,.8);ball(.56,mats.cream,cat,0,1.34,.03,1, .9,.86);for(const s of [-1,1]){const ear=mesh(new THREE.ConeGeometry(.25,.48,3),mats.orange,cat,s*.34,1.87,.03);ear.rotation.z=-s*.2;mesh(new THREE.ConeGeometry(.13,.26,3),mats.pink,cat,s*.34,1.88,.16).rotation.z=-s*.2;ball(.16,mats.cream,cat,s*.27,.14,.25,1,.7,1.4);ball(.16,mats.orange,cat,s*.44,.64,.17,.8,1.2,.8);ball(.059,mats.eye,cat,s*.19,1.39,.466,.7,1.25,.6);ball(.025,'#ffffff',cat,s*.19-.014,1.414,.498);ball(.10,mats.pink,cat,s*.31,1.24,.439,1,.46,.25);for(let k=0;k<2;k++){box(.23,.014,.015,'#ad9077',cat,s*.43,1.23+k*.09,.40,.004).rotation.z=s*(.14-k*.3)}}ball(.057,mats.pink,cat,0,1.26,.516,1,.7,.6);box(.016,.065,.02,mats.eye,cat,0,1.2,.514,.006);for(let i=-1;i<=1;i++)box(.075,.2,.03,mats.orange,cat,i*.15,1.69,.36,.02).rotation.z=i*.2;box(.78,.12,.55,'#9dbdc0',cat,0,.99,0,.05);ball(.075,'#e7c16e',cat,0,.94,.34);const tailCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,.3,-.3),new THREE.Vector3(-.65,.35,-.5),new THREE.Vector3(-.87,.72,-.4),new THREE.Vector3(-.76,.92,-.35)]);mesh(new THREE.TubeGeometry(tailCurve,20,.12,10,false),mats.orange,cat);
// Meadow details, stepping stones and toy blocks.
let seed=21;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
for(let i=0;i<50;i++){const a=random()*Math.PI*2,r=2.8+random()*2.05,x=Math.cos(a)*r,z=Math.sin(a)*r;if(x< -1.5&&z>0&&z<2.3)continue;const g=new THREE.Group();g.position.set(x,.02,z);scene.add(g);for(let j=0;j<3;j++){const blade=mesh(new THREE.ConeGeometry(.025,.15+random()*.15,3),mat(i%2?'#718f7d':'#c1cfab'),g,(j-1)*.07,.08,0);blade.rotation.z=(j-1)*.3}if(i%5===0){ball(.055,'#f4d8aa',g,0,.28,0);ball(.035,'#e9b6b0',g,.09,.21,0)}}
for(let i=0;i<4;i++){box(.5,.14,.33,'#ced0b5',scene,1.4+i*.48,.08,2.3+Math.sin(i)*.3).rotation.y=i*.4}box(.65,.36,.55,'#d9a485',scene,2.7,.2,.7).rotation.y=.25;box(.55,.37,.5,'#a8bbca',scene,3.2,.2,1.3).rotation.y=-.25;box(.5,.4,.4,'#e2c487',scene,2.7,.59,.7).rotation.y=-.1;
const clouds=[];for(let i=0;i<13;i++){const g=new THREE.Group();g.position.set((random()-.5)*45,-1+random()*12,-9-random()*20);for(let j=0;j<4;j++)ball(1,'#b2b0c8',g,(j-1.5)*.75,Math.sin(j)*.22,0,1,.43,.6);g.scale.setScalar(.8+random());scene.add(g);clouds.push(g)}
const starGeo=new THREE.BufferGeometry(),starPositions=[];for(let i=0;i<100;i++)starPositions.push((random()-.5)*65,6+random()*25,-10-random()*25);starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:'#eee0d4',size:.07,transparent:true,opacity:.8})));
const palette=['#dfad8d','#adc4bf','#e7c58d','#b8aed0','#d59e9a','#93b1c2'];const names=['焦糖饼干','薄荷方糖','黄油吐司','云朵软糖','蜜桃布丁','海盐奶盖'];
function makeBlock(x,y,z,w=1.85,d=1.7,color=0){const m=box(w,.51,d,palette[color%6],scene,x,y,z,.085);const ridge=box(w*.7,.009,.017,'#ffffff',m,0,.259,d*.2,.004);ridge.material.transparent=true;ridge.material.opacity=.14;return {mesh:m,x,z,w,d,y,mass:w*d}}
function save(){try{localStorage.setItem('cat-stack',JSON.stringify({best,wallet}))}catch{}}
function tone(freq=440,duration=.1,type='sine'){if(!sound)return;try{const ctx=audio||(audio=new AudioContext()),o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.7,ctx.currentTime+duration);g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}catch{}}let audio;
function toast(s){$('toast').textContent=s;toastUntil=time+3.5;$('toast').style.opacity=1}
function spawn(){const n=blocks.length,c=n%6;let w=n%5===0?1.45:1.85,d=n%7===0?1.3:1.7;moving=makeBlock(0,.22+(n+.5)*.51+1.3,0,w,d,c);moving.mesh.material.emissive=new THREE.Color(palette[c]);moving.mesh.material.emissiveIntensity=.08;$('block-name').textContent=names[c];$('block-info').textContent=w<1.8?'窄型积木 · 更有挑战':'标准积木 · 重量 1.0';document.querySelector('.mini-block').style.background=palette[c];$('block-index').textContent='#'+String(n+1).padStart(3,'0')}
const ghost=box(1.85,.018,1.7,'#fff5db',scene,0,.22,0,.006);ghost.material.transparent=true;ghost.material.opacity=.21;ghost.castShadow=false;
function stability(){return clamp(100-bias*67-blocks.length*(mode==='storm'?1.2:.5),0,100)}
function update(){const n=blocks.length;$('height').textContent=n;$('score').textContent=score;$('combo').textContent=combo;$('best').textContent=best;$('wallet').textContent=wallet;$('progress-number').textContent=n;$('goal-number').textContent=goal;$('progress-bar').style.width=clamp(n/goal*100,0,100)+'%';let st=stability();$('stability-bar').style.width=st+'%';$('stability-label').textContent=st>70?'非常稳固':st>35?'有点摇晃':'摇摇欲坠';$('stability-label').style.color=st>70?'#a8d5bd':st>35?'#e9c28f':'#ee9a92';$('brace-count').textContent='× '+braces;$('slow-count').textContent='× '+slows;$('brace').disabled=braces===0||ended;$('slow').disabled=slows===0||ended}
function remove(m){scene.remove(m);m.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()})}
function reset(){[...blocks,...debris].forEach(b=>remove(b.mesh));if(moving)remove(moving.mesh);if(falling)remove(falling.mesh);particles.forEach(p=>remove(p.mesh));blocks=[];debris=[];particles=[];moving=null;falling=null;score=0;combo=0;bias=0;braces=2;slows=2;slowUntil=0;ended=false;paused=false;won=false;goal=mode==='storm'?16:12;shake=0;time=0;phase=0;$('overlay').classList.add('hidden');$('pause').textContent='Ⅱ';$('drop').disabled=false;$('scene-status').textContent='小猫已就位，等你放下第一块';$('stage-name').textContent=mode==='storm'?'03 / 风暴山谷':mode==='zen'?'02 / 慢悠悠岛':'01 / 云朵草甸';$('mode-label').textContent=mode==='zen'?'自由模式 · 无倒塌，尽情搭建':(mode==='storm'?'暴风模式':'经典模式')+' · 目标 '+goal+' 层';document.querySelector('.mission h2').textContent=mode==='storm'?'在风里站稳脚跟':mode==='zen'?'慢慢来，也很棒':'把云朵踩在脚下';document.querySelector('.mission p').textContent=mode==='zen'?'没有失败，没有催促。按自己的节奏，搭起一座独一无二的高塔。':`搭起一座 ${goal} 层的高塔，让米粒看看云上的风景。`;for(let i=0;i<3;i++)blocks.push(makeBlock(0,.22+(i+.5)*.51,0,1.85,1.7,i));spawn();update();toast('准备好了吗？一起向天空出发！')}
function drop(){if(paused||ended||falling||!moving)return;falling=moving;moving=null;falling.velocity=0;falling.targetY=.22+(blocks.length+.5)*.51;tone(300,.1)}
function confetti(x,y,z,count=28){for(let i=0;i<count;i++){const m=box(.075,.075,.075,palette[i%6],scene,x,y,z,.01);particles.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*3,Math.random()*3+1,(Math.random()-.5)*3),life:2})}}
function land(){const b=falling;falling=null;const top=blocks.at(-1);const dx=Math.abs(b.x-top.x),dz=Math.abs(b.z-top.z);const overlapX=Math.max(0,(b.w+top.w)/2-dx),overlapZ=Math.max(0,(b.d+top.d)/2-dz);const overlap=overlapX*overlapZ/(b.w*b.d);let error=Math.hypot(dx,dz);if(mode==='zen'&&overlap<.3){b.x=top.x;b.z=top.z;b.mesh.position.x=b.x;b.mesh.position.z=b.z;error=0}bias+=error*.29;if(error<.2){combo++;score+=100+combo*25;wallet+=combo>2?3:1;bias=Math.max(0,bias-.07);toast('✦ 完美叠放！ '+combo+' 连击 · +'+(100+combo*25));tone(620+combo*60,.18);confetti(b.x,b.y+.4,b.z,12)}else{combo=0;score+=Math.round(60*clamp(overlap,0,1));toast(error>.7?'喵呜！有点歪了，试试稳稳爪。':'轻轻落下，再接再厉。');tone(380,.15)}blocks.push(b);shake=.08+error*.15;best=Math.max(best,blocks.length);save();update();if(mode!=='zen'&&(overlap<.35||bias>1.38)){collapse();return}if(blocks.length>=goal&&!won){won=true;wallet+=30;save();update();confetti(b.x,b.y+1,b.z,65);paused=true;showOverlay('✦','碰到星星啦！',`米粒成功搭到了 ${blocks.length} 层！获得 30 小鱼干。还想再高一点吗？`,'继续挑战');tone(980,.35)}$('scene-status').textContent=`${blocks.length} 层小小的努力，离星星又近了一点`;spawn()}
function collapse(){ended=true;$('drop').disabled=true;ghost.visible=false;debris=blocks;blocks=[];debris.forEach((b,i)=>{b.v=new THREE.Vector3((Math.random()-.4)*3,Math.random()*1.5,(Math.random()-.5)*2);b.spin=new THREE.Vector3(Math.random()-.5,Math.random()-.5,Math.random()-.5)});toast('哎呀！高塔倒下啦……小猫没事！');tone(100,.65,'triangle');setTimeout(()=>{if(ended)showOverlay('♡','倒下了，也没关系',`这一回搭到了 ${debris.length} 层，获得 ${score} 分。米粒已经准备好再试一次！`,'再搭一次')},1500);update()}
function showOverlay(icon,title,copy,button){$('overlay-icon').textContent=icon;$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('resume').textContent=button;$('overlay').classList.remove('hidden')}
function pause(){if(ended)return;paused=!paused;if(paused)showOverlay('☾','休息一下','小猫正在看守你的高塔。准备好后，我们再继续。','继续搭建');else $('overlay').classList.add('hidden');$('pause').textContent=paused?'▷':'Ⅱ'}
function rotate(){if(!moving||paused||ended)return;const b=moving;const m=makeBlock(b.x,b.y,b.z,b.d,b.w,blocks.length%6);remove(b.mesh);moving=m;tone(480,.08);toast('积木旋转了 90°')}
$('drop').onclick=drop;$('rotate').onclick=rotate;$('pause').onclick=pause;$('restart').onclick=reset;$('restart-overlay').onclick=reset;$('resume').onclick=()=>{if(ended)reset();else{paused=false;$('overlay').classList.add('hidden');$('pause').textContent='Ⅱ'}};$('brace').onclick=()=>{if(paused||ended||!braces)return;braces--;bias=Math.max(0,bias-.6);shake=0;tone(700,.2);toast('⌁ 稳稳爪生效，高塔安心多了！');update()};$('slow').onclick=()=>{if(paused||ended||!slows)return;slows--;slowUntil=time+6;tone(550,.2);toast('◷ 慢一点魔法 · 6 秒精准时刻');update()};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').style.opacity=sound?1:.4;toast(sound?'音效已开启':'音效已关闭')};$('help').onclick=()=>{if(ended)return;paused=true;showOverlay('✧','小猫建筑师手册','空格或按钮放下积木；R 旋转，P 暂停。积木会交替沿两个方向移动。对齐上一层可获得连击，偏心过大会倒塌。用工具稳住塔、减慢积木；拖动场景调整视角。','我准备好了')};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));reset()});$('camera-left').onclick=()=>targetAngle-=Math.PI/4;$('camera-right').onclick=()=>targetAngle+=Math.PI/4;window.addEventListener('keydown',e=>{if(['Space','KeyR','KeyP'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Space')drop();if(e.code==='KeyR')rotate();if(e.code==='KeyP')pause()});renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,angle:targetAngle};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(drag)targetAngle=drag.angle-(e.clientX-drag.x)*.008});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);
let phase=0;function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-lastTime)/1000,.05);lastTime=now;if(!paused)time+=dt;const n=ended?debris.length:blocks.length;const targetY=Math.max(1.6,n*.51*.44);angle+=(targetAngle-angle)*Math.min(dt*5,1);const radius=17+Math.max(0,n-10)*.62;camera.position.lerp(new THREE.Vector3(Math.sin(angle)*radius,targetY+8+Math.max(0,n-10)*.23,Math.cos(angle)*radius),Math.min(1,dt*3));camera.lookAt(0,targetY,0);if(!paused){wind=(Math.sin(time*.61)+Math.sin(time*.29))*(mode==='storm'?1.1:.2);$('weather').textContent=mode==='storm'?'阵风来袭':Math.abs(wind)>.24?'风儿变大了':'微风轻拂';$('wind-value').textContent='风速 '+(Math.abs(wind)*3+.4).toFixed(1)+' m/s';if(moving){phase+=dt*(time<slowUntil?.38:1)*(mode==='zen'?.7:mode==='storm'?1.35:1)*(1+n*.022);const top=blocks.at(-1),sway=Math.sin(phase)*2.3+wind*.13;moving.x=top.x+(n%2===0?sway:0);moving.z=top.z+(n%2!==0?sway:0);moving.mesh.position.set(moving.x,moving.y+Math.sin(time*2)*.045,moving.z);ghost.visible=true;ghost.position.set(moving.x,.23+n*.51,moving.z);ghost.scale.set(moving.w/1.85,1,moving.d/1.7)}else ghost.visible=false;if(falling){falling.velocity+=dt*17;falling.mesh.position.y-=falling.velocity*dt;if(falling.mesh.position.y<=falling.targetY){falling.mesh.position.y=falling.targetY;land()}}shake*=Math.exp(-dt*3);for(let i=0;i<blocks.length;i++){const b=blocks[i],s=Math.sin(time*3)*bias*.012+Math.sin(time*12)*shake*.02;b.mesh.rotation.z=s*(i+1)/3;b.mesh.position.x=b.x+s*i*.15}cat.position.y=Math.sin(time*2.1)*.025;cat.rotation.z=Math.sin(time*1.7)*.025+(falling?-.12:0);cat.children[4].rotation.z=falling?-.7:0;for(const b of debris){b.v.y-=dt*9;b.mesh.position.addScaledVector(b.v,dt);b.mesh.rotation.x+=b.spin.x*dt*5;b.mesh.rotation.z+=b.spin.z*dt*5;if(b.mesh.position.y<.3&&Math.hypot(b.mesh.position.x,b.mesh.position.z)<4.7){b.mesh.position.y=.3;b.v.y=Math.abs(b.v.y)*.25;b.v.x*=.94;b.v.z*=.94;b.spin.multiplyScalar(.94)}}for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.v.y-=dt*3;p.mesh.position.addScaledVector(p.v,dt);p.mesh.rotation.z+=dt*4;if(p.life<=0){remove(p.mesh);particles.splice(i,1)}}clouds.forEach((c,i)=>c.position.x+=dt*.025*(i%2?1:-1))}if(time>toastUntil)$('toast').style.opacity=0;renderer.render(scene,camera)}
reset();resize();camera.position.set(10,10,14);requestAnimationFrame(frame);
