import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id), TAU=Math.PI*2;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), lerp=(a,b,t)=>a+(b-a)*t;
const canvas=$('sea');let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('load').innerHTML='当前浏览器无法启动 3D 画面，请启用硬件加速后刷新。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x264e5a);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x315965,.0036);const camera=new THREE.PerspectiveCamera(48,1,.5,1800);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xb7d6de,0x142b32,2));const sunLight=new THREE.DirectionalLight(0xffdc9b,3.2);sunLight.position.set(-110,130,-260);sunLight.castShadow=true;sunLight.shadow.mapSize.set(1024,1024);sunLight.shadow.camera.left=-32;sunLight.shadow.camera.right=32;sunLight.shadow.camera.top=32;sunLight.shadow.camera.bottom=-32;scene.add(sunLight);scene.add(sunLight.target);
const mat=(color,roughness=1)=>new THREE.MeshStandardMaterial({color,roughness,flatShading:true});const wood=mat(0x693d25),trim=mat(0xc99554),deckMat=mat(0xb58047),dark=mat(0x2a2420),sailMat=mat(0xf1d49b),red=mat(0xa9583c),rockmat=mat(0x304b4b),grass=mat(0x52644f);
function mesh(geo,material,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,m,p,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),m,p,x,y,z);}
function rope(a,b,parent,color=0x766a4e,r=.035){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),dif=vb.clone().sub(va);const m=mesh(new THREE.CylinderGeometry(r,r,dif.length(),5),mat(color),parent);m.position.copy(va.add(vb).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dif.normalize());return m;}
const sky=new THREE.Mesh(new THREE.SphereGeometry(1400,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#102e41')},bottom:{value:new THREE.Color('#779b97')}},vertexShader:'varying vec3 v; void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v; uniform vec3 top;uniform vec3 bottom; void main(){float h=normalize(v).y;gl_FragColor=vec4(mix(bottom,top,smoothstep(-.08,.65,h)),1.);}'}));scene.add(sky);
const sun=mesh(new THREE.SphereGeometry(35,24,16),new THREE.MeshBasicMaterial({color:0xffd499}),scene,-240,90,-850);sun.castShadow=false;
const clouds=new THREE.Group();scene.add(clouds);let seed=827;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
for(let i=0;i<85;i++){const c=mesh(new THREE.IcosahedronGeometry(1,1),mat(i%4===0?0x668080:0x294851),clouds,(rnd()-.5)*1500,90+rnd()*100,-350+(rnd()-.5)*1100);c.scale.set(50+rnd()*85,13+rnd()*20,22+rnd()*50);c.castShadow=false;}
let visualTime=0,storm=.4;function wave(x,z,t=visualTime){return Math.sin(x*.067+z*.034+t*1.45)*(.85+storm*.9)+Math.sin(z*.116-x*.031+t*1.9)*.55+Math.sin(x*.23+z*.19+t*2.4)*.17;}
const oceanGeo=new THREE.PlaneGeometry(1500,1500,140,140);oceanGeo.rotateX(-Math.PI/2);const oceanMat=new THREE.MeshStandardMaterial({color:0x236371,roughness:.38,metalness:.32,flatShading:true});const ocean=mesh(oceanGeo,oceanMat,scene);ocean.castShadow=false;const op=oceanGeo.attributes.position,base=new Float32Array(op.array);
const foamCount=550;const foam=new THREE.InstancedMesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({color:0xb2e0d7,transparent:true,opacity:.22,side:THREE.DoubleSide}),foamCount);scene.add(foam);const dummy=new THREE.Object3D();const foams=Array.from({length:foamCount},()=>({x:(rnd()-.5)*600,z:(rnd()-.5)*650,length:1+rnd()*5}));
const boat=new THREE.Group();scene.add(boat);const hullShape=new THREE.Shape();hullShape.moveTo(0,-6.5);hullShape.quadraticCurveTo(3.2,-3,2.7,2.9);hullShape.quadraticCurveTo(2.4,4.2,0,4.5);hullShape.quadraticCurveTo(-2.4,4.2,-2.7,2.9);hullShape.quadraticCurveTo(-3.2,-3,0,-6.5);
const hullGeo=new THREE.ExtrudeGeometry(hullShape,{depth:2,bevelEnabled:true,bevelThickness:.7,bevelSize:.5,bevelSegments:1,steps:1});hullGeo.rotateX(Math.PI/2);const hull=mesh(hullGeo,wood,boat,0,1.65,0);const deckGeo=new THREE.ShapeGeometry(hullShape);deckGeo.rotateX(Math.PI/2);mesh(deckGeo,new THREE.MeshStandardMaterial({color:0xad7a45,side:THREE.DoubleSide,roughness:1}),boat,0,1.7,0);
for(let i=-2;i<=2;i++)box(.045,.035,7,wood,boat,i,1.73,-.1);rope([-2.65,2,2.8],[-2.2,2,-3],boat,0xc99f62,.11);rope([2.65,2,2.8],[2.2,2,-3],boat,0xc99f62,.11);rope([-2.2,2,-3],[0,2,-6.4],boat,0xc99f62,.11);rope([2.2,2,-3],[0,2,-6.4],boat,0xc99f62,.11);box(4.6,.22,.2,trim,boat,0,2,3.5);box(2,.5,1.4,deckMat,boat,0,2,1.8);
mesh(new THREE.CylinderGeometry(.12,.2,13,9),trim,boat,0,7.6,-1);rope([0,1.7,-6.5],[0,13.5,-1],boat);rope([-2.5,1.8,2.8],[0,13,-1],boat);rope([2.5,1.8,2.8],[0,13,-1],boat);
const sailGroup=new THREE.Group();sailGroup.position.set(0,0,-1);boat.add(sailGroup);const sailGeo=new THREE.BufferGeometry();const sv=[],si=[];const rows=14,cols=12;for(let j=0;j<=rows;j++){const t=j/rows;for(let i=0;i<=cols;i++){const u=i/cols;sv.push(u*(1-t)*6.2,3.4+t*9.4,Math.sin(u*Math.PI)*Math.sin(t*Math.PI)*1.3);if(j<rows&&i<cols){const n=j*(cols+1)+i;si.push(n,n+1,n+cols+1,n+1,n+cols+2,n+cols+1);}}}sailGeo.setAttribute('position',new THREE.Float32BufferAttribute(sv,3));sailGeo.setIndex(si);sailGeo.computeVertexNormals();sailMat.side=THREE.DoubleSide;mesh(sailGeo,sailMat,sailGroup);rope([0,3.3,0],[6.3,3.3,0],sailGroup,0xbc9156,.07);
const jibGeo=new THREE.BufferGeometry();jibGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,12,-1,0,2.8,-6,1,3,-1],3));jibGeo.computeVertexNormals();mesh(jibGeo,sailMat,boat);
const flag=mesh(new THREE.PlaneGeometry(2,1),red,boat,1,14.1,-1);flag.material.side=THREE.DoubleSide;
// A tiny captain at the stern, complete with raincoat, hat and ship's wheel.
const captain=new THREE.Group();captain.position.set(0,2,2.5);boat.add(captain);mesh(new THREE.CylinderGeometry(.43,.55,1.1,8),mat(0xd7a449),captain,0,.55,0);mesh(new THREE.SphereGeometry(.39,12,8),mat(0xe7bb8a),captain,0,1.4,0);mesh(new THREE.CylinderGeometry(.48,.52,.17,12),mat(0x244c59),captain,0,1.75,0);box(.7,.08,.5,mat(0x244c59),captain,0,1.68,-.2);const wheel=mesh(new THREE.TorusGeometry(.52,.07,6,16),trim,boat,0,2.8,1.5);for(let i=0;i<4;i++){const r=box(1.2,.04,.04,trim,wheel);r.rotation.z=i*Math.PI/4;}
const routes=[{x:-35,z:-165,name:'琥珀灯塔',desc:'沿着金色航标，穿过第一片海域。'},{x:150,z:-325,name:'沉船湾',desc:'绕过东侧礁石，留意落水的船员。'},{x:30,z:-510,name:'风眼海峡',desc:'大风正在增强，收帆保持船体稳定。'},{x:-145,z:-720,name:'北境避风港',desc:'最后一程！带着收获平安抵达港湾。'}];
const islands=[],land=new THREE.Group();scene.add(land);function island(x,z,size,lighthouse=false){const g=new THREE.Group();g.position.set(x,-1,z);land.add(g);islands.push({x,z,r:size*.75});const rock=mesh(new THREE.IcosahedronGeometry(size,1),rockmat,g);rock.scale.set(1,.62,.83);rock.rotation.y=rnd()*6;const grassTop=mesh(new THREE.IcosahedronGeometry(size*.78,1),grass,g,0,size*.35,0);grassTop.scale.set(1,.3,.9);for(let i=0;i<7;i++){const px=(rnd()-.5)*size,pz=(rnd()-.5)*size;const h=4+rnd()*7;mesh(new THREE.CylinderGeometry(.15,.4,h,5),wood,g,px,size*.49+h/2,pz);mesh(new THREE.ConeGeometry(2,h*.9,6),mat(0x1c4540),g,px,size*.49+h,pz);}if(lighthouse){const y=size*.55;mesh(new THREE.CylinderGeometry(2,3,16,12),mat(0xd6c9a8),g,0,y+8,0);mesh(new THREE.CylinderGeometry(2.1,2.35,3,12),red,g,0,y+10,0);mesh(new THREE.CylinderGeometry(2.6,2.6,2.8,8),new THREE.MeshStandardMaterial({color:0xffcc73,emissive:0xffb547,emissiveIntensity:2}),g,0,y+17,0);mesh(new THREE.ConeGeometry(3.4,3,8),dark,g,0,y+20,0);const light=new THREE.PointLight(0xffbc62,250,95);light.position.set(0,y+18,0);g.add(light);const beam=mesh(new THREE.ConeGeometry(34,220,24,1,true),new THREE.MeshBasicMaterial({color:0xffdfa0,transparent:true,opacity:.04,side:THREE.DoubleSide,depthWrite:false}),g,0,y+18,0);beam.geometry.translate(0,-110,0);beam.rotation.z=Math.PI/2;g.userData.beam=beam;}return g;}
island(-95,-185,29,true);island(215,-345,36,true);island(-30,-535,26,true);island(-210,-750,42,true);island(110,-140,30);island(-180,-350,45);island(245,-610,50);island(-125,-430,18);island(35,-330,15);island(340,-210,58);island(-360,-570,75);
const gates=routes.map((p,i)=>{const g=new THREE.Group();g.position.set(p.x,0,p.z);scene.add(g);const ring=mesh(new THREE.TorusGeometry(13,.13,6,64),new THREE.MeshBasicMaterial({color:0xf9cc7e,transparent:true,opacity:.85}),g);ring.rotation.x=Math.PI/2;const pole=mesh(new THREE.CylinderGeometry(.12,.12,12,6),trim,g,0,6,0);const pennant=mesh(new THREE.ConeGeometry(2,4,3),new THREE.MeshBasicMaterial({color:0xffd388}),g,0,13,0);pennant.rotation.z=-Math.PI/2;g.userData={ring,pennant};return g;});
const pickups=[];function pickup(x,z,type){const g=new THREE.Group();scene.add(g);if(type==='rescue'){mesh(new THREE.TorusGeometry(1.1,.3,7,14),red,g).rotation.x=Math.PI/2;mesh(new THREE.SphereGeometry(.45,8,6),mat(0xe5bb8a),g,0,.8,0);box(.6,.7,.4,mat(0xe9bd65),g,0,.3,0);}else{box(1.7,1.7,1.7,deckMat,g);box(1.85,.18,1.85,trim,g,0,.6,0);box(1.85,.18,1.85,trim,g,0,-.6,0);box(.2,1.85,1.85,wood,g);}const halo=mesh(new THREE.TorusGeometry(2,.05,5,24),new THREE.MeshBasicMaterial({color:type==='rescue'?0xff9d76:0xeed095}),g);halo.rotation.x=Math.PI/2;pickups.push({x,z,type,g,taken:false});}
[[-15,-45],[0,-96],[-30,-132],[18,-210],[75,-245],[120,-300],[110,-385],[70,-438],[15,-480],[-23,-560],[-72,-617],[-117,-674]].forEach(([x,z],i)=>pickup(x,z,i===4||i===8?'rescue':'supply'));
const rainN=800,rainPos=new Float32Array(rainN*6);const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rain=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:0xafccd0,transparent:true,opacity:.18}));scene.add(rain);const rainDrops=Array.from({length:rainN},()=>({x:(rnd()-.5)*130,y:rnd()*70,z:(rnd()-.5)*130}));
const wakeGeo=new THREE.BufferGeometry(),wakePos=new Float32Array(150*3);wakeGeo.setAttribute('position',new THREE.BufferAttribute(wakePos,3));const wake=new THREE.Points(wakeGeo,new THREE.PointsMaterial({color:0xc2e3da,size:.7,transparent:true,opacity:.38}));scene.add(wake);const trail=[];
const lightning=new THREE.PointLight(0xd8eaff,0,700);scene.add(lightning);let flashTime=0;
const state={started:false,paused:false,ended:false,x:0,z:25,heading:0,speed:0,sail:.65,hull:100,wood:3,leg:0,items:0,rescued:0,score:0,elapsed:0,anchor:false,collisionCooldown:0,travel:0,camera:0};let buoyY=0,buoyV=0,heel=0,turn=0,modalKind='',audioCtx,windGain,soundOn=false;const keys=new Set();let toastTimer;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300);}
function start(){Object.assign(state,{started:true,paused:false,ended:false,x:0,z:25,heading:0,speed:0,sail:.65,hull:100,wood:3,leg:0,items:0,rescued:0,score:0,elapsed:0,anchor:false,collisionCooldown:0,travel:0});$('sail').value=65;$('anchor').innerHTML='抛锚 <kbd>空格</kbd>';buoyY=0;buoyV=0;trail.length=0;pickups.forEach(p=>{p.taken=false;p.g.visible=true;});$('intro').classList.add('hidden');$('mission').classList.remove('hidden');closeModal();updateMission();toast('欢迎登船，船长！W / S 调帆，A / D 掌舵。');}
function repair(){if(!state.started||state.ended)return;if(state.wood<1)return toast('木材不足，寻找海上的补给箱。');if(state.hull>=99)return toast('船体完好，暂时无需修复。');state.wood--;state.hull=Math.min(100,state.hull+25);toast('修复完成 · 船体 +25% · 木材 −1');}
function anchor(){if(!state.started||state.ended)return;state.anchor=!state.anchor;toast(state.anchor?'已抛下海锚，船速降低。':'海锚已收起，继续航行。');$('anchor').innerHTML=(state.anchor?'起锚':'抛锚')+' <kbd>空格</kbd>';}
function updateMission(){const p=routes[state.leg];$('leg').textContent=String(state.leg+1).padStart(2,'0')+' / 04';$('missionTitle').textContent='驶向'+p.name;$('missionDesc').textContent=p.desc;gates.forEach((g,i)=>g.visible=i===state.leg);}
function showModal(html,kind='help'){keys.clear();modalKind=kind;state.paused=true;$('modalContent').innerHTML=html;$('modal').classList.remove('hidden');$('pauseBtn').textContent='▷';}
function closeModal(){if(state.ended)return;state.paused=false;modalKind='';$('modal').classList.add('hidden');$('pauseBtn').textContent='Ⅱ';}
function help(){showModal('<div class="eyebrow">CAPTAIN’S HANDBOOK</div><h2>每一阵风，都是方向。</h2><p>依次抵达四座金色航标完成远航。靠近补给箱和落水船员即可自动收集与救援，避开岛礁、保持船体完好。</p><div class="help-row"><span>向左 / 向右掌舵</span><span><kbd>A</kbd> <kbd>D</kbd> 或方向键</span></div><div class="help-row"><span>升帆 / 收帆</span><span><kbd>W</kbd> <kbd>S</kbd> 或拖动主帆</span></div><div class="help-row"><span>海锚减速 / 木材修船</span><span><kbd>空格</kbd> / <kbd>R</kbd></span></div><div class="help-row"><span>航海图 / 镜头 / 暂停</span><span><kbd>M</kbd> / <kbd>C</kbd> / <kbd>P</kbd></span></div><p>逆风时用之字形航线前进；暴风中把主帆收至 55% 以下，能减少危险横倾。触屏可用右下方舵盘按钮。</p>');}
function map(){showModal('<div class="eyebrow">CHART NO. 001</div><h2>北境群岛航海图</h2><canvas id="chart" width="600" height="600" aria-label="航线、船只与岛礁地图"></canvas><p>金色：灯塔航标 · 白色：你的小船 · 橙色：待救援船员</p>','map');drawMap();}
function drawMap(){const c=$('chart');if(!c)return;const ctx=c.getContext('2d'),project=(x,z)=>[300+x*.64,535+z*.64];ctx.fillStyle='#102d38';ctx.fillRect(0,0,600,600);ctx.strokeStyle='#719f9430';for(let i=0;i<600;i+=50){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,600);ctx.moveTo(0,i);ctx.lineTo(600,i);ctx.stroke();}ctx.setLineDash([6,7]);ctx.strokeStyle='#e8c38277';ctx.beginPath();ctx.moveTo(...project(0,25));routes.forEach(p=>ctx.lineTo(...project(p.x,p.z)));ctx.stroke();ctx.setLineDash([]);islands.forEach(p=>{ctx.fillStyle='#608077';ctx.beginPath();ctx.ellipse(...project(p.x,p.z),p.r*.7,p.r*.55,0,0,TAU);ctx.fill();});routes.forEach((p,i)=>{const [x,y]=project(p.x,p.z);ctx.strokeStyle=i===state.leg?'#ffe0a0':'#ad966c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,10,0,TAU);ctx.stroke();ctx.fillStyle='#e4d9b9';ctx.font='16px sans-serif';ctx.fillText((i+1)+' '+p.name,x+15,y+5);});pickups.filter(p=>!p.taken).forEach(p=>{ctx.fillStyle=p.type==='rescue'?'#ff9c77':'#b7c9b1';ctx.beginPath();ctx.arc(...project(p.x,p.z),3,0,TAU);ctx.fill();});ctx.save();ctx.translate(...project(state.x,state.z));ctx.rotate(-state.heading);ctx.fillStyle='#fff9df';ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(-7,8);ctx.lineTo(0,4);ctx.lineTo(7,8);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#c1d3c7';ctx.font='14px sans-serif';ctx.fillText('N ↑',25,32);}
function end(win){state.ended=true;state.score+=win?Math.round(state.hull*8+Math.max(0,600-state.elapsed)*2):0;showModal(`<div class="eyebrow">${win?'VOYAGE COMPLETE':'LOST AT SEA'}</div><h2>${win?'灯塔亮起，欢迎回港。':'风暴赢了这一回。'}</h2><p>${win?'你穿越了北境风暴，把勇气和收获带回了港湾。':'船体已无法承受巨浪。下次提前收帆，避开礁石，记得用木材修复船体。'}</p><div class="stats"><div><b>${Math.round(state.score)}</b><span>航海得分</span></div><div><b>${state.items}</b><span>收集补给</span></div><div><b>${state.rescued}</b><span>救援船员</span></div></div><p>航行 ${Math.floor(state.elapsed/60)} 分 ${Math.floor(state.elapsed%60)} 秒 · ${Math.round(state.travel)} 米</p><button id="restart" class="primary">再次扬帆</button>`,'end');$('restart').onclick=start;}
function sound(){soundOn=!soundOn;$('sound').textContent='声音 '+(soundOn?'开':'关');if(soundOn&&!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const source=audioCtx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=450;windGain=audioCtx.createGain();source.connect(filter).connect(windGain).connect(audioCtx.destination);source.start();}if(audioCtx){audioCtx.resume();windGain.gain.setTargetAtTime(soundOn?.06:0,audioCtx.currentTime,.3);}}
$('anchorTouch').onclick=anchor;$('start').onclick=start;$('repair').onclick=repair;$('anchor').onclick=anchor;$('mapBtn').onclick=map;$('helpBtn').onclick=help;$('sound').onclick=sound;$('closeModal').onclick=closeModal;$('pauseBtn').onclick=()=>state.paused?closeModal():showModal('<div class="eyebrow">TAKE A BREATH</div><h2>海风会等你。</h2><p>航程已暂停。点击右上角关闭按钮，或按 P 继续航行。</p>','pause');$('sail').oninput=e=>state.sail=Number(e.target.value)/100;
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='r')repair();if(k===' ')anchor();if(k==='m')modalKind==='map'?closeModal():map();if(k==='p'||k==='escape')state.paused?closeModal():$('pauseBtn').click();if(k==='c'){state.camera=(state.camera+1)%3;toast(['跟随镜头','俯瞰镜头','船长镜头'][state.camera]);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.started&&!state.paused&&!state.ended)$('pauseBtn').click();});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(b.dataset.key)));});
function damage(amount){state.hull=Math.max(0,state.hull-amount);$('damageFlash').style.opacity=.35;setTimeout(()=>$('damageFlash').style.opacity=0,220);if(state.hull<=0)end(false);}
function physics(dt){state.elapsed+=dt;storm=.35+.3*Math.sin(state.elapsed*.023)+.3*Math.sin(state.elapsed*.009);storm=clamp(storm+(state.leg===2?.28:0),.12,1);if(keys.has('w')||keys.has('arrowup'))state.sail=clamp(state.sail+dt*.25,0,1);if(keys.has('s')||keys.has('arrowdown'))state.sail=clamp(state.sail-dt*.25,0,1);$('sail').value=state.sail*100;const input=(keys.has('a')||keys.has('arrowleft')?1:0)-(keys.has('d')||keys.has('arrowright')?1:0);turn=lerp(turn,input,.07);state.heading+=turn*dt*(.27+Math.min(state.speed,10)*.045);const windAngle=.9+Math.sin(state.elapsed*.012)*.5,alignment=Math.cos(state.heading-windAngle);const efficiency=.16+.84*Math.sqrt((alignment+1)/2);const drive=state.sail*(2.2+storm*2.1)*efficiency;const drag=.025*state.speed*Math.abs(state.speed)+.15*state.speed+(state.anchor?state.speed*1.6:0);state.speed=clamp(state.speed+(drive-drag)*dt,0,13);const dx=-Math.sin(state.heading)*state.speed*dt,dz=-Math.cos(state.heading)*state.speed*dt;state.x+=dx+Math.sin(windAngle)*storm*.25*dt;state.z+=dz;state.travel+=Math.hypot(dx,dz);state.collisionCooldown-=dt;for(const rock of islands){const dist=Math.hypot(state.x-rock.x,state.z-rock.z),r=rock.r+4;if(dist<r){const nx=(state.x-rock.x)/(dist||1),nz=(state.z-rock.z)/(dist||1);state.x=rock.x+nx*(r+.3);state.z=rock.z+nz*(r+.3);if(state.collisionCooldown<=0){damage(10+state.speed*2);toast('撞上礁石！减速转向，按 R 修复船体。');state.collisionCooldown=2;}state.speed*=.3;}}if(Math.abs(state.x)>580||state.z>160||state.z< -920){state.x=clamp(state.x,-580,580);state.z=clamp(state.z,-920,160);state.speed*=.95;toast('前方是未知海域，请转向金色航标。');}if(storm>.68&&state.sail>.6){state.hull-=dt*(state.sail-.6)*storm*2.3;if(state.hull<=0)end(false);}pickups.forEach(p=>{if(!p.taken&&Math.hypot(state.x-p.x,state.z-p.z)<8){p.taken=true;p.g.visible=false;if(p.type==='rescue'){state.rescued++;state.score+=500;state.hull=Math.min(100,state.hull+10);toast('救援成功！船员已登船 · +500 分 · 船体 +10%');}else{state.items++;state.wood+=2;state.score+=150;toast('获得漂流补给 · 木材 +2 · +150 分');}}});const target=routes[state.leg];if(Math.hypot(state.x-target.x,state.z-target.z)<18){state.score+=400;state.hull=Math.min(100,state.hull+12);if(state.leg===3){end(true);return;}state.leg++;updateMission();toast('抵达航标！船体 +12% · 新航程：'+routes[state.leg].name);}if(state.elapsed>25&&Math.random()<dt*.045&&storm>.5){flashTime=.16;lightning.position.set(state.x+80,70,state.z-80);}}
let hudTimer=0;function hud(dt){hudTimer+=dt;if(hudTimer<.1)return;hudTimer=0;const target=routes[state.leg],distance=Math.hypot(state.x-target.x,state.z-target.z);const head=(((-state.heading*180/Math.PI)%360)+360)%360;const bearing=((Math.atan2(target.x-state.x,-(target.z-state.z))*180/Math.PI)+360)%360;$('speed').textContent=(state.speed*1.94).toFixed(1);$('speedBar').style.width=state.speed/13*100+'%';$('sailValue').textContent=Math.round(state.sail*100)+'%';$('hullValue').textContent=Math.max(0,Math.round(state.hull))+'%';$('hullBar').style.width=Math.max(0,state.hull)+'%';$('hullBar').style.background=state.hull<35?'#e58f6b':'#9cbdac';$('wood').textContent='木材 '+state.wood;$('heading').textContent=String(Math.round(head)%360).padStart(3,'0');$('needle').style.transform='rotate('+(bearing-head)+'deg)';$('bearing').textContent='航标方位 '+Math.round(bearing)+'°';$('distance').textContent=Math.round(distance)+' m';$('collected').textContent='补给 '+state.items+' · 救援 '+state.rescued;$('routeProgress').style.width=clamp(100-distance/2.5,0,100)+'%';$('weatherName').textContent=storm>.68?'暴风海域':storm>.4?'风暴前沿':'海风渐缓';$('weatherDetail').textContent='西南风 · 海况 '+Math.round(2+storm*5)+' 级';$('windValue').innerHTML=Math.round(12+storm*23)+'<small>节</small>';$('tip').textContent=state.anchor?'海锚已放下，按空格收起。':storm>.68?'风力危险：请将主帆收至 55% 以下。':'逆风时尝试斜向航行，借风前进。';if(windGain&&soundOn)windGain.gain.value=.035+storm*.08;}
let frame=0;function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);if(!state.paused){visualTime+=dt;if(state.started&&!state.ended)physics(dt);}const t=visualTime;frame++;ocean.position.x=Math.round(state.x/50)*50;ocean.position.z=Math.round(state.z/50)*50;for(let i=0;i<op.count;i++){op.array[i*3+1]=wave(base[i*3]+ocean.position.x,base[i*3+2]+ocean.position.z);}op.needsUpdate=true;if(frame%3===0)oceanGeo.computeVertexNormals();foams.forEach((f,i)=>{const x=f.x+Math.round(state.x/200)*200,z=f.z+Math.round(state.z/200)*200;dummy.position.set(x,wave(x,z)+.15,z);dummy.rotation.set(-Math.PI/2,0,.3);dummy.scale.set(f.length,.13+Math.sin(t+i)*.07,1);dummy.updateMatrix();foam.setMatrixAt(i,dummy.matrix);});foam.instanceMatrix.needsUpdate=true;
const wy=wave(state.x,state.z);if(!state.paused){buoyV+=(wy-buoyY)*dt*15-buoyV*dt*5;buoyY+=buoyV*dt;}boat.position.set(state.x,buoyY+.1,state.z);const slopeX=(wave(state.x+2,state.z)-wave(state.x-2,state.z))/4,slopeZ=(wave(state.x,state.z+3)-wave(state.x,state.z-3))/6;heel=lerp(heel,-slopeX*.7+turn*state.speed*.017+Math.sin(t*1.8)*storm*state.sail*.11,.06);boat.rotation.set(slopeZ*.55,state.heading,heel);sailGroup.rotation.y=-.65+Math.sin(t*.6)*.08;sailGroup.scale.x=.35+state.sail*.65;flag.rotation.y=Math.sin(t*7)*.2;wheel.rotation.z=-turn*.6;
pickups.forEach(p=>{if(p.taken)return;p.g.position.set(p.x,wave(p.x,p.z)+.6,p.z);p.g.rotation.set(Math.sin(t+p.x)*.1,t*.08,Math.cos(t+p.z)*.1);});gates.forEach((g,i)=>{g.position.y=wave(g.position.x,g.position.z)+.3;g.userData.pennant.rotation.y=t*.8;if(!state.started)g.visible=i===0;});land.children.forEach(g=>{if(g.userData.beam)g.userData.beam.rotation.y=t*.2;});
if(!state.paused){rainDrops.forEach((p,i)=>{p.y-=dt*(25+storm*15);p.x+=dt*5;if(p.y<0){p.y=70;p.x=(rnd()-.5)*130;p.z=(rnd()-.5)*130;}const k=i*6;rainPos[k]=p.x+state.x;rainPos[k+1]=p.y;rainPos[k+2]=p.z+state.z;rainPos[k+3]=p.x+state.x-1;rainPos[k+4]=p.y+2.3;rainPos[k+5]=p.z+state.z;});rainGeo.attributes.position.needsUpdate=true;}rain.material.opacity=storm*.28;flashTime=Math.max(0,flashTime-dt);lightning.intensity=flashTime>0?30000:0;
if(!state.paused&&state.speed>1){trail.unshift({x:state.x+Math.sin(state.heading)*4+(Math.random()-.5)*3,z:state.z+Math.cos(state.heading)*4});if(trail.length>150)trail.pop();}for(let i=0;i<150;i++){const p=trail[i]||{x:state.x,z:state.z};wakePos[i*3]=p.x;wakePos[i*3+1]=wave(p.x,p.z)+.15;wakePos[i*3+2]=p.z;}wakeGeo.attributes.position.needsUpdate=true;wake.material.opacity=Math.min(.45,state.speed*.06);
const offset=state.started?(state.camera===1?new THREE.Vector3(0,65,40):state.camera===2?new THREE.Vector3(0,7,6):new THREE.Vector3(18,20,34)):new THREE.Vector3(27,19,42);if(state.started)offset.applyAxisAngle(new THREE.Vector3(0,1,0),state.heading);const desired=new THREE.Vector3(state.x,0,state.z).add(offset);camera.position.lerp(desired,state.started?.045:.025);const look=state.started?new THREE.Vector3(state.x-Math.sin(state.heading)*14,4,state.z-Math.cos(state.heading)*14):new THREE.Vector3(state.x-13,4,state.z-15);camera.lookAt(look);sky.position.copy(camera.position);sunLight.position.set(state.x-110,130,state.z-260);sunLight.target.position.copy(boat.position);hud(dt);renderer.render(scene,camera);}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();camera.position.set(27,19,67);$('load').classList.add('hidden');updateMission();animate();
window.__stormCaptain={state,start,repair,anchor,pause:()=>state.paused?closeModal():$('pauseBtn').click(),getStatus:()=>({started:state.started,paused:state.paused,leg:state.leg+1,hull:Math.round(state.hull),sail:state.sail,speed:state.speed,wood:state.wood})};
if(document.modelContext?.registerTool){for(const tool of [{name:'read_voyage_status',description:'Read the current sailing game status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.__stormCaptain.getStatus()},{name:'set_mainsail',description:'Set the current sail opening from zero to one.',inputSchema:{type:'object',properties:{opening:{type:'number',minimum:0,maximum:1}},required:['opening'],additionalProperties:false},execute:({opening})=>{if(typeof opening!=='number'||!Number.isFinite(opening)||opening<0||opening>1)throw new Error('opening must be between 0 and 1');state.sail=opening;$('sail').value=opening*100;return {sail:opening};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
