import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import * as core from '../dist/game-core.js';
const elements=new Map(),laneButtons=[],songButtons=[],difficultyButtons=[];
const context2d=new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
class Element{constructor(){this.style={};this.dataset={};this._html='';this.textContent='';this.open=false;this.disabled=false;this.classList={add(){},remove(){},toggle(){}}}set innerHTML(v){this._html=v}get innerHTML(){return this._html}addEventListener(){}setAttribute(){}getContext(){return context2d}getBoundingClientRect(){return {width:800,height:202}}showModal(){this.open=true}close(){this.open=false}scrollIntoView(){}}
const $=selector=>{if(!elements.has(selector))elements.set(selector,new Element());return elements.get(selector)};
for(let i=0;i<4;i++){const e=new Element();e.dataset.lane=String(i);laneButtons.push(e)}for(let i=0;i<3;i++){const e=new Element();e.dataset.song=String(i);songButtons.push(e)}for(const d of ['easy','normal','hard']){const e=new Element();e.dataset.difficulty=d;difficultyButtons.push(e)}
class Audio{constructor(){this.time=0;this.context=null;this.scheduled=[]}async init(){this.context={};return this}setVolume(){}stop(){this.scheduled=[]}async suspend(){this.suspended=true}async resume(){this.suspended=false}playLane(){}scheduleBacking(...x){this.scheduled.push(x)}cue(){}}
const stored=new Map(),tools=[];
const scope={...core,BandAudio:Audio,BandStage:class{hit(){}update(){}cycleCamera(){return 0}},console,Math,Number,String,Array,JSON,Date,Map,Set,AbortController,performance:{now:()=>1000},devicePixelRatio:1,innerWidth:1280,requestAnimationFrame(){},setTimeout(){},clearTimeout(){},ResizeObserver:class{observe(){}},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},window:{innerWidth:1280,addEventListener(){}},document:{querySelector:$,querySelectorAll:s=>s==='[data-lane]'?laneButtons:s==='[data-song]'?songButtons:s==='[data-difficulty]'?difficultyButtons:s==='[data-song],[data-difficulty]'?[...songButtons,...difficultyButtons]:[],body:new Element(),addEventListener(){},modelContext:{registerTool:t=>tools.push(t)}}};vm.createContext(scope);
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');vm.runInContext(source+`\nglobalThis.qa={start,pressLane,releaseLane,pause,resume,endRun,frame,setMode,setDifficulty,selectSong,activateOverdrive,closeModal,audio,get state(){return state},get startTime(){return startTime},get notes(){return notes},get stats(){return {score,combo,maxCombo,energy,perfect,good,miss,brokenHolds,overdriveUntil}},get elapsed(){return elapsed}};`,scope);
const g=scope.qa,results=[];const frame=t=>{g.audio.time=g.startTime+t;g.frame(1000)};
for(let si=0;si<3;si++)for(const d of ['easy','normal','hard']){g.closeModal();g.selectSong(si);g.setDifficulty(d);await g.start();const events=[];for(const n of g.notes){events.push({t:n.t,type:'press',lane:n.lane});events.push({t:n.t+(n.duration||.02),type:'release',lane:n.lane})}events.sort((a,b)=>a.t-b.t);for(const e of events){frame(e.t);if(e.type==='press')await g.pressLane(e.lane);else g.releaseLane(e.lane);if(g.stats.energy===100)g.activateOverdrive()}frame(core.SONGS[si].beats*60/core.SONGS[si].bpm+.5);assert.equal(g.state,'ended');assert.equal(g.stats.perfect,g.notes.length);assert.equal(g.stats.good,0);assert.equal(g.stats.miss,0);assert.equal(g.stats.brokenHolds,0);assert.equal(g.stats.maxCombo,g.notes.length);assert(g.stats.score>g.notes.length*100);results.push({song:si,difficulty:d,notes:g.notes.length,score:g.stats.score,perfect:g.stats.perfect});}
g.closeModal();g.selectSong(0);g.setDifficulty('easy');await g.start();frame(g.notes[0].t);await g.pressLane(g.notes[0].lane);g.releaseLane(g.notes[0].lane);assert.equal(g.stats.combo,1);await g.pause();assert.equal(g.state,'paused');assert(g.audio.suspended);const score=g.stats.score;g.frame(2000);assert.equal(g.stats.score,score);await g.resume();assert.equal(g.state,'playing');assert(!g.audio.suspended);g.endRun(false);
g.setMode('jam');await g.start();frame(2);await g.pressLane(0);g.releaseLane(0);assert.equal(g.stats.score,0);assert.equal(g.stats.miss,0);frame(180);assert.equal(g.state,'playing');g.endRun(false);g.setMode('rhythm');await g.start();const hold=g.notes.find(n=>n.duration);frame(hold.t);await g.pressLane(hold.lane);frame(hold.t+.1);g.releaseLane(hold.lane);assert.equal(g.stats.brokenHolds,1);assert.equal(g.stats.combo,0);g.endRun(false);
g.closeModal();await g.start();const acceptedHold=g.notes.find(n=>n.duration);frame(acceptedHold.t);await g.pressLane(acceptedHold.lane);frame(acceptedHold.t+acceptedHold.duration-.1);g.releaseLane(acceptedHold.lane);frame(acceptedHold.t+acceptedHold.duration-.08);assert.equal(acceptedHold.status,'hit');assert.equal(g.stats.brokenHolds,0);g.endRun(false);
assert.equal(tools.length,2);const configure=tools.find(t=>t.name==='configure_band_session');configure.execute({songIndex:2,difficulty:'hard',mode:'rhythm'});assert.throws(()=>configure.execute({songIndex:99,difficulty:'easy',mode:'rhythm'}));
console.log(JSON.stringify({perfectRuns:results,checks:['nine complete perfect runs','hold completion','early hold release','overdrive scoring','pause and resume','endless jam without miss penalties','configuration input validation'],result:'PASS',limitations:'AudioContext and DOM are mocked; browser rendering and actual audio startup checked separately.'},null,2));
