import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id), clamp=THREE.MathUtils.clamp;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dce9cb');scene.fog=new THREE.Fog('#dce9cb',25,100);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('scene').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,160);const light=new THREE.DirectionalLight('#fff2ce',3.8);light.position.set(-12,25,14);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-30,right:30,top:30,bottom:-30,far:80});light.shadow.bias=-.001;scene.add(light,new THREE.HemisphereLight('#e3f4e7','#546a37',2.8));
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.85});const materials={fur:mat('#b76532'),light:mat('#d98c45'),cream:mat('#f3d29a'),dark:mat('#2d261c'),pink:mat('#e8a084'),tail:mat('#a9542a'),grass:mat('#819b4c'),path:mat('#cbb784'),wood:mat('#795237'),gold:mat('#e5a33c'),cap:mat('#744625'),leaf:mat('#d29a38')};
function mesh(g,m,x=0,y=0,z=0,parent=scene){const a=new THREE.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
function ell(m,x,y,z,sx,sy,sz,p){const o=mesh(new THREE.SphereGeometry(1,16,12),m,x,y,z,p);o.scale.set(sx,sy,sz);return o}
function cyl(m,x,y,z,r1,r2,h,p){return mesh(new THREE.CylinderGeometry(r1,r2,h,9),m,x,y,z,p)}
const ground=mesh(new THREE.PlaneGeometry(220,220),materials.grass,0,-.08,-45);ground.rotation.x=-Math.PI/2;
const path=mesh(new THREE.PlaneGeometry(8.8,180),materials.path,0,.01,-60);path.rotation.x=-Math.PI/2;
for(const x of [-4.5,4.5]){const a=mesh(new THREE.BoxGeometry(.24,.12,180),mat('#a4ad61'),x,.04,-60)}
const squirrel=new THREE.Group();scene.add(squirrel);
ell(materials.fur,0,1.08,0,.52,.69,.43,squirrel);ell(materials.cream,0,1.07,.365,.35,.46,.12,squirrel);ell(materials.light,0,1.92,.06,.56,.53,.49,squirrel);
ell(materials.cream,0,1.69,.43,.36,.23,.23,squirrel);
for(const x of [-.35,.35]){ell(materials.fur,x,2.36,.01,.2,.4,.17,squirrel);ell(materials.pink,x,2.39,.135,.105,.24,.04,squirrel);ell(materials.dark,x*.91,2.02,.448,.072,.09,.049,squirrel);ell(mat('#fffdf0'),x*.91-.016,2.049,.486,.022,.025,.018,squirrel);ell(materials.light,x*.98,1.78,.447,.18,.12,.06,squirrel)}
ell(materials.dark,0,1.8,.637,.075,.058,.055,squirrel);
const legs=[];for(const x of [-.32,.32]){legs.push(ell(materials.fur,x,.31,.16,.24,.28,.37,squirrel));ell(materials.fur,x*1.65,1.1,.11,.18,.38,.18,squirrel)}
const tail=new THREE.Group();squirrel.add(tail);tail.rotation.x=-.18;ell(materials.tail,.15,1.25,-.68,.48,.87,.49,tail);ell(materials.fur,.15,2,-.84,.65,.82,.56,tail);ell(materials.light,.16,2.35,-.68,.52,.46,.43,tail);
const scarf=mat('#608779');cyl(scarf,0,1.52,0,.46,.45,.16,squirrel);mesh(new THREE.BoxGeometry(.19,.48,.07),scarf,.35,1.26,.4,squirrel).rotation.z=-.3;
const scenery=[];let seed=348;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function tree(x,z){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const h=3+rand()*4;cyl(materials.wood,0,h*.36,0,.15,.27,h*.8,g);const colors=['#667f3b','#8d9b46','#baa347','#cb903c','#a87534'];const m=mat(colors[Math.floor(rand()*colors.length)]);for(let i=0;i<3;i++){const o=mesh(new THREE.ConeGeometry(1.7-i*.28,h*.6,7),m,0,h*.65+i*h*.21,0,g);o.rotation.y=rand()}g.scale.setScalar(.8+rand()*.8);scenery.push(g)}
for(let i=0;i<100;i++)tree((i%2?1:-1)*(6+rand()*24),-rand()*130+15);
for(let i=0;i<90;i++){const g=new THREE.Group();g.position.set((i%2?1:-1)*(4.9+rand()*15),0,-rand()*100+12);scene.add(g);if(i%3===0){cyl(materials.cream,0,.22,0,.09,.13,.42,g);const c=ell(mat('#cc7546'),0,.46,0,.38,.2,.38,g);for(let j=0;j<3;j++)ell(materials.cream,(rand()-.5)*.35,.6,(rand()-.5)*.3,.048,.025,.048,g)}else{ell(mat(i%2?'#768941':'#a6ac54'),0,.15,0,.7,.25,.55,g)}scenery.push(g)}
const motes=[];for(let i=0;i<45;i++){const o=mesh(new THREE.OctahedronGeometry(.035),mat('#fff4b1'),(rand()-.5)*35,rand()*7,-rand()*70);motes.push(o)}
const rings=[];for(let i=0;i<12;i++){const o=mesh(new THREE.BoxGeometry(8.3,.025,.035),mat('#f0dbac'),0,.03,-i*7);rings.push(o)}
const aura=mesh(new THREE.TorusGeometry(.83,.035,8,48),mat('#fbd675'),0,.05,0);aura.rotation.x=-Math.PI/2;
const objects=[],particles=[];let mode='normal',state='menu',lane=0,score=0,nuts=0,health=3,combo=0,maxCombo=0,perfect=0,hits=0,elapsed=0,bpm=108,beatSec=60/bpm,lastBeat=-1,lastJumpBeat=-99,jumpTime=-9,slideUntil=0,shieldUntil=0,magnetUntil=0,invincible=0,lastSpawn=-1,feedbackUntil=0,pauseAt=0,best=0;try{best=+localStorage.getItem('pinebeat-best')||0}catch{}
let audio,master,muted=false,audioStart=0;const duration=90,speed=13,hitZ=2;
function initAudio(){if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted?0:.23;master.connect(audio.destination)}audio.resume()}
function tone(freq,t,length,type='sine',volume=.3){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g);g.connect(master);o.start(t);o.stop(t+length+.02)}
const melody=[523.25,659.25,783.99,659.25,587.33,659.25,440,392,523.25,659.25,880,783.99,659.25,587.33,523.25,392];
function musicBeat(b){const t=audio.currentTime+.015;tone(b%4===0?65:85,t,.15,'sine',.9);tone(melody[b%16],t,.21,'triangle',.21);tone([130.81,110,146.83,98][Math.floor(b/4)%4],t,.32,'triangle',.18);if(b%2)tone(1900,t,.045,'triangle',.1);tone(melody[(b+4)%16]*2,t+beatSec*.5,.08,'sine',.06)}
function acorn(parent,color=materials.gold){const g=new THREE.Group();parent.add(g);ell(color,0,0,0,.23,.32,.23,g);ell(materials.cap,0,.2,0,.29,.12,.29,g);cyl(materials.wood,0,.35,0,.037,.045,.17,g);return g}
function spawn(type,l,beat){const g=new THREE.Group();scene.add(g);let model;if(type==='nut'){model=acorn(g);g.position.y=1.1}else if(type==='log'){cyl(materials.wood,0,.38,0,.37,.42,1.55,g).rotation.z=Math.PI/2;for(const x of [-.79,.79]){const d=cyl(materials.cream,x,.38,0,.3,.3,.02,g);d.rotation.z=Math.PI/2}}else if(type==='branch'){cyl(materials.wood,-.9,1.25,0,.09,.13,2.5,g);cyl(materials.wood,.9,1.25,0,.09,.13,2.5,g);mesh(new THREE.BoxGeometry(2.1,.4,.42),materials.wood,0,1.9,0,g);ell(mat('#7d914d'),.7,2.2,0,.5,.3,.4,g)}else{model=mesh(new THREE.OctahedronGeometry(.43),mat(type==='shield'?'#6dd8d1':'#b692ed'),0,0,0,g);g.position.y=1.15;const r=mesh(new THREE.TorusGeometry(.6,.035,6,24),mat('#fff1b8'),0,0,0,g);r.rotation.x=.4}g.position.x=l*2.65;objects.push({g,type,l,beat,done:false,baseY:g.position.y,model})}
function pattern(b){if(b<6)return;const l=((Math.floor(b/4)*7+Math.floor(b/2))%3)-1;if(b%20===12)spawn('shield',l,b);else if(b%24===18)spawn('magnet',l,b);else if(b%4===0&&b>14)spawn(b%12===0?'branch':'log',l,b);else{spawn('nut',l,b);if(b%8===7)spawn('nut',-l,b)}}
function burst(x,y,z,color){for(let i=0;i<10;i++){const g=mesh(new THREE.OctahedronGeometry(.06),mat(color),x,y,z);particles.push({g,v:new THREE.Vector3((rand()-.5)*5,2+rand()*3,(rand()-.5)*5),life:.7})}}
function say(text,color='#fff2af'){ $('feedback').textContent=text;$('feedback').style.color=color;feedbackUntil=elapsed+.65}
function jump(){if(state!=='playing')return;const beat=elapsed/beatSec,near=Math.round(beat),delta=Math.abs(beat-near)*beatSec;if(elapsed-jumpTime<.28)return;jumpTime=elapsed;hits++;const win=mode==='easy'?.22:mode==='hard'?.095:.15;if(lastJumpBeat!==near&&delta<win){lastJumpBeat=near;combo++;maxCombo=Math.max(maxCombo,combo);const isPerfect=delta<(mode==='easy'?.12:.075);score+=(isPerfect?100:60)*multiplier();if(isPerfect)perfect++;say(isPerfect?'PERFECT ✦':'GOOD',isPerfect?'#fff0a8':'#e9fff0');if(combo%8===0){shieldUntil=Math.max(shieldUntil,elapsed+4);say('连击奖励 · 护盾！','#b4fff0')}tone(1046.5,audio.currentTime,.12,'sine',.12)}else{combo=0;say('跟紧节拍','#fff8e1')}updateHud()}
function multiplier(){return Math.min(5,1+Math.floor(combo/8))}
function move(d){if(state==='playing')lane=clamp(lane+d,-1,1)}function slide(){if(state==='playing'){slideUntil=elapsed+.65;combo=Math.max(0,combo)}}
function updateHud(){$('score').textContent=String(score).padStart(5,'0');$('nuts').innerHTML=nuts+' <em> / 40</em>';$('hearts').textContent='♥ '.repeat(health)+'♡ '.repeat(3-health);$('combo').textContent=combo>1?`${combo} 连击 · COMBO`:'';$('multiplier').textContent='×'+multiplier()}
function start(){initAudio();for(const o of objects)scene.remove(o.g);objects.length=0;for(const p of particles)scene.remove(p.g);particles.length=0;lane=score=nuts=combo=maxCombo=perfect=hits=elapsed=0;health=3;bpm=mode==='easy'?96:mode==='hard'?132:108;beatSec=60/bpm;lastBeat=-1;lastSpawn=-1;lastJumpBeat=-99;jumpTime=-9;slideUntil=shieldUntil=magnetUntil=invincible=0;audioStart=audio.currentTime;state='playing';$('welcome').hidden=true;$('scene-caption').hidden=true;$('footer').hidden=true;$('modal').hidden=true;$('hud').hidden=false;$('rhythm').hidden=false;document.body.classList.add('playing');$('bpm').textContent=bpm+' BPM';updateHud();say('准备好了吗？')}
function pause(){if(state==='playing'){state='paused';pauseAt=audio.currentTime;$('modal-label').textContent='TAKE A LITTLE BREATH';$('modal-title').textContent='森林在等你';$('modal-description').textContent='休息一下，下一拍继续。';$('results').innerHTML='';$('resume').hidden=false;$('resume').textContent='继续冒险';$('modal').hidden=false}else if(state==='paused')resume()}
function resume(){if(state!=='paused')return;audio.resume();audioStart+=audio.currentTime-pauseAt;state='playing';$('modal').hidden=true}
function finish(){state='ended';best=Math.max(best,score);try{localStorage.setItem('pinebeat-best',best)}catch{}const won=elapsed>=duration;$('modal-label').textContent=won?'FOREST JOURNEY COMPLETE':'A NEW ADVENTURE AWAITS';$('modal-title').textContent=won?(nuts>=40?'丰收的节拍大师！':'森林旅程完成！'):'再试一次，栗栗！';$('modal-description').textContent=won?'每一颗松果，都藏着秋天的好心情。':'木桩要跳过，低树枝要滑行。跟着光点找到下一拍。';$('results').innerHTML=`<div>本次得分<strong>${score}</strong></div><div>松果收藏<strong>${nuts} / 40</strong></div><div>最长连击<strong>${maxCombo}</strong></div><div>本机最高分<strong>${best}</strong></div>`;$('resume').hidden=true;$('restart').textContent='再来一场';$('modal').hidden=false}
function home(){state='menu';for(const o of objects)scene.remove(o.g);objects.length=0;$('modal').hidden=true;$('welcome').hidden=false;$('scene-caption').hidden=false;$('footer').hidden=false;$('hud').hidden=true;$('rhythm').hidden=true;$('feedback').textContent='';$('combo').textContent='';document.body.classList.remove('playing');squirrel.scale.set(1,1,1)}
$('start').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('restart').onclick=start;$('home').onclick=home;$('left').onpointerdown=()=>move(-1);$('right').onpointerdown=()=>move(1);$('jump').onpointerdown=jump;$('slide').onpointerdown=slide;$('sound').onclick=()=>{muted=!muted;if(master)master.gain.value=muted?0:.23;$('sound').textContent=muted?'♪̸':'♫';$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音')};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b))});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape','KeyP'].includes(e.code)){e.preventDefault();if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP')pause();else if(e.code==='Space'||e.code==='ArrowUp')jump();else if(e.code==='ArrowLeft')move(-1);else if(e.code==='ArrowRight')move(1);else slide()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
const beatDots=[];for(let i=-4;i<=4;i++){const a=document.createElement('i');a.className='beat-dot';$('beat-dots').appendChild(a);beatDots.push(a)}
let prev=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-prev)/1000,.05);prev=now;const t=now/1000;if(state==='playing'){elapsed=audio.currentTime-audioStart;const beat=Math.floor(elapsed/beatSec);if(beat>lastBeat){musicBeat(beat);lastBeat=beat}while(lastSpawn<beat+12){lastSpawn++;pattern(lastSpawn)}const progress=elapsed/duration;$('progress').style.width=Math.min(100,progress*100)+'%';$('time').textContent=Math.max(0,Math.ceil(duration-elapsed))+'s';const stage=Math.min(2,Math.floor(elapsed/30));$('stage').textContent=['01 阳光林地','02 金色溪谷','03 暮光秘境'][stage];const colors=['#dce9cb','#e9d6ae','#bbccce'];scene.background.lerp(new THREE.Color(colors[stage]),dt*.6);scene.fog.color.copy(scene.background);
const runSpeed=speed*(1+stage*.1);const jumpAge=elapsed-jumpTime;const height=jumpAge>=0&&jumpAge<.7?Math.sin(jumpAge/.7*Math.PI)*2.25:0;const sliding=elapsed<slideUntil;
squirrel.position.x=THREE.MathUtils.lerp(squirrel.position.x,lane*2.65,dt*13);squirrel.position.y=height+Math.abs(Math.sin(elapsed*12))*.035;squirrel.position.z=hitZ;squirrel.rotation.y=Math.PI;squirrel.rotation.z=clamp((lane*2.65-squirrel.position.x)*-.1,-.2,.2);squirrel.scale.set(1,sliding?.46:1,sliding?1.3:1);squirrel.visible=elapsed>invincible||Math.floor(elapsed*14)%2===0;tail.rotation.z=Math.sin(elapsed*9)*.1;legs.forEach((l,i)=>l.position.z=.16+Math.sin(elapsed*18+i*Math.PI)*.13);
for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.g.position.z=hitZ-(o.beat*beatSec+(['log','branch'].includes(o.type)?.24:0)-elapsed)*runSpeed;if(o.model){o.model.rotation.y+=dt*1.5;o.g.position.y=o.baseY+Math.sin(t*4+o.beat)*.12}const aligned=Math.abs(o.g.position.x-squirrel.position.x)<1.2;const magnetic=o.type==='nut'&&elapsed<magnetUntil;const inRange=Math.abs(o.g.position.z-hitZ)<(magnetic?2.7:.65);if(!o.done&&inRange&&(aligned||magnetic)){if(o.type==='nut'){o.done=true;nuts++;score+=25*multiplier();burst(o.g.position.x,1.1,hitZ,'#efc777');tone(880,audio.currentTime,.08,'sine',.1)}else if(o.type==='shield'||o.type==='magnet'){o.done=true;if(o.type==='shield')shieldUntil=elapsed+9;else magnetUntil=elapsed+9;say(o.type==='shield'?'森林护盾 · 9 秒':'松果磁铁 · 9 秒','#b5fff0');burst(o.g.position.x,1.2,hitZ,'#a5ead1')}else if(o.type==='log'?height<.7:!sliding&&height<2.6){o.done=true;if(elapsed<shieldUntil){shieldUntil=0;say('护盾抵挡！','#befff2')}else if(elapsed>invincible){health--;combo=0;invincible=elapsed+1.4;say('小心！','#ffd4ad');tone(120,audio.currentTime,.2,'sawtooth',.14)}}updateHud()}if(o.done||o.g.position.z>10){scene.remove(o.g);objects.splice(i,1)}}
for(const g of scenery){g.position.z+=dt*runSpeed;if(g.position.z>23)g.position.z-=145}for(const r of rings){r.position.z+=dt*runSpeed;if(r.position.z>9)r.position.z-=84}const activeShield=elapsed<shieldUntil,activeMagnet=elapsed<magnetUntil;aura.visible=true;aura.position.set(squirrel.position.x,.05,hitZ);aura.material.color.set(activeShield?'#80ffe2':'#fbd675');aura.scale.setScalar(1+Math.exp(-(elapsed%beatSec)*12)*.35);$('power').textContent=activeShield?`护盾 ${Math.ceil(shieldUntil-elapsed)}s`:activeMagnet?`磁铁 ${Math.ceil(magnetUntil-elapsed)}s`:nuts>=40?'松果目标已达成！':'目标：收集 40 颗松果';beatDots.forEach((d,i)=>{d.style.left=(50+((i-4)-(elapsed/beatSec%1))*24)+'%'});if(elapsed>feedbackUntil)$('feedback').textContent='';camera.position.lerp(new THREE.Vector3(squirrel.position.x*.22,6.5,13.8),dt*3);camera.lookAt(0,1,-12);if(health<=0||elapsed>=duration)finish();
}else if(state==='menu'){squirrel.visible=true;const mobile=innerWidth<760;squirrel.position.set(mobile?0:3.5,Math.sin(t*2)*.06,0);squirrel.rotation.set(0,-.3+Math.sin(t*.5)*.1,0);tail.rotation.z=Math.sin(t*2)*.07;aura.position.set(squirrel.position.x,.06,0);aura.visible=true;camera.position.set(mobile?6:10,mobile?6:5.8,mobile?17:14);camera.lookAt(mobile?0:-.7,mobile?-1.3:1,-1);scene.background.lerp(new THREE.Color('#dce9cb'),dt);scene.fog.color.copy(scene.background)}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];if(state==='playing'){p.life-=dt;p.g.position.addScaledVector(p.v,dt);p.v.y-=dt*8;p.g.scale.setScalar(Math.max(0,p.life));if(p.life<=0){scene.remove(p.g);particles.splice(i,1)}}}motes.forEach((m,i)=>{m.position.y+=Math.sin(t+i)*dt*.15;m.rotation.y+=dt});renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});$('loading').hidden=true;requestAnimationFrame(frame);
window.pinebeat={getState:()=>({state,mode,score,nuts,health,combo,elapsed:Math.round(elapsed)}),start,pause,resume,move,jump,slide};
if(document.modelContext?.registerTool){for(const tool of [{name:'get_game_state',description:'Read the current Pinebeat score, mode and game status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.pinebeat.getState()},{name:'pause_game',description:'Pause the current Pinebeat run.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state!=='playing')throw new Error('No active run');pause();return window.pinebeat.getState()}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
