import * as THREE from 'three';
import * as CANNON from 'cannon-es';

const $=id=>document.getElementById(id);
const colors={amber:0xd9a348,teal:0x72a8a2,steel:0x8b9690};
const levels=[
 {name:'初次吸引',tag:'入门训练',desc:'让磁力成为你的新手臂。将两件货物送入对应的装卸区。',hint:'靠近货箱，按 E 开启磁力。到达装卸区后，再按 E 释放。',robot:[-1,3.7],crates:[[-1,0,'amber'],[2,1.8,'teal']],docks:[[3,-2.8,'amber'],[5,0.4,'teal']]},
 {name:'一道门的距离',tag:'压力机关',desc:'用一件货物压住开关，为另一件打开通往装卸区的闸门。',hint:'灰色辅助箱可以压住左侧圆形开关。闸门打开后再运输彩色货箱。',robot:[-3,3],crates:[[-2,1,'amber'],[-4,-1,'steel'],[0,3,'teal']],docks:[[3,-3,'amber'],[5,1,'teal']],gate:true,plate:[-4,-3]},
 {name:'逆流而上',tag:'传送带作业',desc:'货物也有自己的方向。克服传送带推力，稳稳停入装卸区。',hint:'在传送带边缘吸住货箱，横向拉离皮带。排斥脉冲可以快速改变货物速度。',robot:[-3,3],crates:[[-2,0,'amber'],[1,0,'teal'],[3,0,'amber']],docks:[[-3,-3,'amber'],[1,-3,'teal'],[5,2.5,'amber']],belt:true},
 {name:'重力与磁力',tag:'重载搬运',desc:'大型货箱需要耐心。绕开红色危险区，利用脉冲搬运重物。',hint:'带有双条纹的重型货箱更重。持续吸引慢慢拖动；不要把货物推入红色区域。',robot:[-4,3],crates:[[-3,0,'amber',true],[0,2,'teal'],[3,-1,'amber',true]],docks:[[-3,-3,'amber'],[1,-3,'teal'],[5,2.5,'amber']],hazards:[[1,0],[4,-3]]},
 {name:'最后一班',tag:'综合挑战',desc:'机关、传送带与重型货物同时上线。让工厂完美收工。',hint:'先用灰箱开门，再将货物拉离传送带。注意能量，关闭磁力可以快速恢复。',robot:[-4,3.6],crates:[[-4,-.8,'steel'],[-2,0,'amber',true],[0,1,'teal'],[3,0,'amber']],docks:[[3,-3,'amber'],[5,-1,'teal'],[5,3,'amber']],gate:true,plate:[-4,-3],belt:true,hazards:[[-1,-3]]}
];
let current=0,world,objects=[],crates=[],docks=[],robot,robotBody,gate,plate,magnet=false,repel=false,energy=100,moves=0,elapsed=0,paused=false,won=false,started=false,held=null,angle=0,sound=false,toastTime=0,gateOpen=false,frameTime=0,mouseTarget=null;
let best={};try{best=JSON.parse(localStorage.getItem('magnet-works-best')||'{}')}catch{}
const physicsSurface=new CANNON.Material('surface'),physicsRobot=new CANNON.Material('robot');
const keys=new Set();const stage=$('scene');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdde3d5);scene.fog=new THREE.Fog(0xdde3d5,35,75);
const camera=new THREE.PerspectiveCamera(36,1,.1,100);let cameraTarget=new THREE.Vector3(-.8,-.9,0);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;stage.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xf8f5df,0x899785,3));const sun=new THREE.DirectionalLight(0xfff2d8,4.2);sun.position.set(-5,14,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;sun.shadow.normalBias=.03;scene.add(sun);
const root=new THREE.Group();scene.add(root);
const mat=(c,metal=.0,rough=.75)=>new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough});
const mats={floor:mat(0xc8cdb9),edge:mat(0xa5ae97),dark:mat(0x576456),cream:mat(0xe9e9d9),gold:mat(0xdba342,.3),black:mat(0x303e37),metal:mat(0x9eaa95,.35)};
function box(w,h,d,m,x=0,y=0,z=0,parent=root){const a=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof m==='number'?mat(m):m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
function cyl(r,h,m,x,y,z,parent=root,r2=r){const a=new THREE.Mesh(new THREE.CylinderGeometry(r,r2,h,24),typeof m==='number'?mat(m):m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
function label(text,x,y,z,size=.6,color='#f1edd6',rotation=-Math.PI/2,parent=root){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.font='bold 60px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,64);const texture=new THREE.CanvasTexture(canvas);const m=new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false});const a=new THREE.Mesh(new THREE.PlaneGeometry(size*2,size),m);a.position.set(x,y,z);a.rotation.x=rotation;parent.add(a);return a}
function fixedBox(w,h,d,x,y,z){const body=new CANNON.Body({mass:0,material:physicsSurface,shape:new CANNON.Box(new CANNON.Vec3(w/2,h/2,d/2))});body.position.set(x,y,z);world.addBody(body);return body}
function stripe(x,z,length,rotation=0){const g=new THREE.Group();g.position.set(x,.052,z);g.rotation.y=rotation;root.add(g);box(length,.015,.19,0xd6b55f,0,0,0,g);for(let i=-length/2+.1;i<length/2;i+=.35){const b=box(.1,.022,.22,0x6b7358,i,.01,0,g);b.rotation.y=-.45}}
function pipe(x,z){const g=new THREE.Group();root.add(g);g.position.set(x,0,z);cyl(.18,2.6,mats.metal,0,1.3,0,g);cyl(.28,.15,mats.dark,0,.2,0,g);cyl(.25,.15,mats.dark,0,2.1,0,g);const elbow=new THREE.Mesh(new THREE.TorusGeometry(.4,.18,10,20,Math.PI/2),mats.metal);elbow.position.set(.4,2.6,0);g.add(elbow);const a=cyl(.18,1,mats.metal,.9,3,0,g);a.rotation.z=Math.PI/2}
function environment(){box(14,.55,10,mats.edge,0,-.3,0);box(13.9,.13,9.9,mats.floor,0,-.015,0);fixedBox(14,1,10,0,-.52,0);
 for(let x=-6.5;x<=6.5;x+=1)for(let z=-4.5;z<=4.5;z+=1){box(.012,.008,.96,0xb4bda7,x,.055,z);box(.96,.008,.012,0xb4bda7,x,.055,z)}
 for(const z of [-5,5]){fixedBox(14,1,.18,0,.5,z);box(14,.3,.17,mats.dark,0,.1,z);for(let x=-6.5;x<7;x+=1.3){cyl(.055,.75,mats.gold,x,.55,z);box(.09,.1,.1,mats.black,x,.93,z)}box(14,.055,.055,mats.gold,0,.9,z)}
 for(const x of [-7,7]){fixedBox(.18,1,10,x,.5,0);box(.17,.3,10,mats.dark,x,.1,0);for(let z=-4.7;z<5;z+=1.3)cyl(.055,.75,mats.gold,x,.55,z);box(.055,.055,10,mats.gold,x,.9,0)}
 stripe(0,4.5,12);stripe(0,-4.5,12);
 // rear loading wall and industrial utilities
 box(14,.75,.35,0xaab39a,0,.32,-5.4);box(14,.13,.65,mats.cream,0,.73,-5.4);for(let x=-5;x<=5;x+=2){box(.06,.75,.05,0x909d83,x,.3,-5.18)}
 const machine=new THREE.Group();root.add(machine);machine.position.set(-5.5,0,-3.8);box(1.6,1.8,.7,mats.cream,0,.9,0,machine);box(1.3,1.25,.06,0xa7b5a0,0,1,-.38,machine);box(.65,.35,.08,mats.black,0,1.35,.38,machine);box(.45,.12,.09,0x87ae8a,0,1.35,.43,machine);for(let i=0;i<4;i++)box(.07,.36,.08,mats.dark,-.4+i*.26,.65,.39,machine);cyl(.075,.05,mats.gold,.5,1.35,.44,machine).rotation.x=Math.PI/2;
 pipe(-6.1,-2.7);pipe(-6.1,-1.5);
 // gantry crane
 for(const x of [-6.8,6.8]){box(.22,4.25,.25,0xb5bda6,x,2.1,-4.85);box(.48,.18,.6,mats.dark,x,.1,-4.85)}box(13.8,.35,.45,0xd8bd77,0,4.15,-4.85);box(13.9,.07,.5,mats.dark,0,4.35,-4.85);for(let x=-6.5;x<7;x+=.48)box(.045,.38,.46,0xc1a968,x,4.15,-4.85);box(.9,.32,.85,0x72816b,2.4,3.89,-4.85);cyl(.026,1.2,mats.dark,2.4,3.1,-4.65);const hook=new THREE.Mesh(new THREE.TorusGeometry(.16,.045,8,20,Math.PI*1.5),mats.gold);hook.position.set(2.55,2.52,-4.65);root.add(hook);
 label('07',5.7,.065,3.5,1.05,'#a5ad97');label('MAGNET / WORKS',0,.07,-3.9,.45,'#a0aa92');
 for(let i=0;i<4;i++){cyl(.27,.7,i%2?mats.dark:mats.gold,-6.2+i*.65,.35,4);cyl(.28,.04,mats.metal,-6.2+i*.65,.71,4)}
 // surrounding floor and feet
 box(200,.2,200,0xdde3d5,0,-1,0);for(const x of [-5.7,5.7])for(const z of [-3.8,3.8])box(.9,.5,.9,mats.dark,x,-.65,z);
}
function makeRobot(x,z){robot=new THREE.Group();root.add(robot);robot.position.set(x,0,z);box(.9,.26,.85,mats.black,0,.29,0,robot);for(const side of [-1,1])for(const zz of [-.3,.3]){let wheel=cyl(.22,.16,mats.black,side*.48,.24,zz,robot);wheel.rotation.z=Math.PI/2;cyl(.095,.18,mats.metal,side*.49,.24,zz,robot).rotation.z=Math.PI/2}
 box(.78,.53,.68,mats.gold,0,.65,0,robot);box(.85,.07,.74,mats.cream,0,.96,0,robot);box(.66,.23,.07,mats.black,0,.75,.36,robot);for(const xx of [-.18,.18])box(.09,.08,.02,0xb9eacb,xx,.76,.406,robot);box(.22,.07,.035,mats.black,0,.53,.355,robot);cyl(.025,.27,mats.dark,.27,1.1,-.18,robot);cyl(.07,.09,0xd67e43,.27,1.25,-.18,robot);for(const side of [-1,1]){box(.13,.17,.35,mats.metal,side*.49,.65,.3,robot);box(.14,.21,.2,side<0?0xdd895a:0x85aea2,side*.4,.65,.54,robot)}
 label('M-01',0,.6,-.35,.17,'#5c6452',0,robot).rotation.y=Math.PI;
 robotBody=new CANNON.Body({mass:8,material:physicsRobot,shape:new CANNON.Box(new CANNON.Vec3(.48,.48,.48)),fixedRotation:true,linearDamping:.94});robotBody.position.set(x,.51,z);world.addBody(robotBody)}
function makeCrate(data,index){const [x,z,color,heavy]=data;const size=heavy?1.12:.85;const mesh=new THREE.Group();root.add(mesh);const bodyMat=mat(colors[color],.18);box(size,size,size,bodyMat,0,0,0,mesh);for(const side of [-1,1]){box(size+.025,.08,.055,mats.cream,0,side*(size/2-.08),size/2,mesh);box(.07,size+.01,.045,mats.cream,side*(size/2-.08),0,size/2+.015,mesh);box(.07,.025,size+.02,mats.cream,side*size*.31,size/2+.01,0,mesh);box(size+.02,.08,.035,mats.dark,0,side*(size/2-.08),-size/2,mesh)}
 label(color==='steel'?'＋':heavy?'▰':'↑',0,0,size/2+.027,.28,'#f6edd8',0,mesh);if(heavy)box(.12,.02,size,mats.dark,0,size/2+.018,0,mesh);
 const body=new CANNON.Body({mass:heavy?9:3,material:physicsSurface,shape:new CANNON.Box(new CANNON.Vec3(size/2,size/2,size/2)),linearDamping:.52,angularDamping:.8});body.position.set(x,size/2+.08,z);world.addBody(body);const c={mesh,body,color,heavy,size,index,delivered:false,settle:0,spawn:new CANNON.Vec3(x,size/2+.1,z)};crates.push(c)}
function makeDock(data,i){const [x,z,color]=data,g=new THREE.Group();g.position.set(x,.066,z);root.add(g);box(1.65,.028,1.65,mat(colors[color]),0,0,0,g);box(1.45,.031,1.45,mats.floor,0,.008,0,g);for(const side of [-1,1])for(const zz of [-1,1]){box(.32,.035,.055,colors[color],side*.61,.027,zz*.7,g);box(.055,.035,.32,colors[color],side*.7,.027,zz*.61,g)}label('↓',0,.032,0,.55,color==='teal'?'#729c94':'#b59350',-Math.PI/2,g);label('BAY 0'+(i+1),0,.034,.98,.18,'#919b83',-Math.PI/2,g);docks.push({x,z,color,g,filled:false})}
function loadLevel(n){current=n;while(root.children.length){const o=root.children[0];root.remove(o);o.traverse(a=>{if(a.geometry)a.geometry.dispose();if(a.material){const ms=Array.isArray(a.material)?a.material:[a.material];ms.forEach(m=>{if(!Object.values(mats).includes(m)){m.map?.dispose();m.dispose()}})}})}world=new CANNON.World({gravity:new CANNON.Vec3(0,-15,0)});world.defaultContactMaterial.friction=.008;world.addContactMaterial(new CANNON.ContactMaterial(physicsRobot,physicsSurface,{friction:.005,restitution:0}));world.defaultContactMaterial.restitution=.08;world.solver.iterations=12;crates=[];docks=[];objects=[];gate=null;plate=null;gateOpen=false;magnet=false;repel=false;energy=100;moves=0;elapsed=0;won=false;paused=false;started=false;held=null;mouseTarget=null;keys.clear();$('overlay').classList.add('hidden');
 environment();const l=levels[n];l.crates.forEach(makeCrate);l.docks.forEach(makeDock);makeRobot(...l.robot);
 if(l.gate){gate={mesh:box(.23,1.7,4,0xaeb7a0,1,1,-2.6),body:fixedBox(.23,1.7,4,1,1,-2.6)};for(let i=0;i<7;i++)box(.25,.055,4,mats.dark,1,.3+i*.2,-2.6);objects=root.children.slice(-7);plate={mesh:cyl(.65,.07,0xd7b163,l.plate[0],.09,l.plate[1]),x:l.plate[0],z:l.plate[1]};label('＋',plate.x,.14,plate.z,.5,'#faf0cd')}
 if(l.belt){box(8,.07,1.45,0x718275,0,.08,0);for(let x=-3.8;x<4;x+=.3){const a=box(.08,.025,1.25,0x98a48c,x,.13,0);a.userData.belt=true;objects.push(a)}stripe(0,-.78,8);stripe(0,.78,8);label('→  →  →',0,.155,0,.8,'#c7cbb7')}
 for(const h of l.hazards||[]){box(1.35,.015,1.35,0xbd8061,h[0],.07,h[1]);label('×',h[0],.084,h[1],.65,'#f4c9a2')}
 $('level-number').textContent=String(n+1).padStart(2,'0');$('level-title').textContent=l.name;$('difficulty').textContent=l.tag;$('level-desc').textContent=l.desc;$('hint').textContent=l.hint;$('stage-label').textContent=`SECTOR 0${n+1} / 05`;$('total').textContent=docks.length;$('cargo-list').innerHTML=docks.map((d,i)=>`<div class="cargo-item" id="cargo-${i}" style="--c:#${colors[d.color].toString(16)}"><i></i><span>${d.color==='amber'?'琥珀':'青绿'}货物 · 0${i+1}</span><b>等待入库</b></div>`).join('');updateHUD();toast(n===0?'欢迎来到磁力工坊。你的第一班，即刻开始。':l.hint,6)}
const field=new THREE.Group();scene.add(field);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.85+i*.43,.014,6,64),new THREE.MeshBasicMaterial({color:0xe9b64e,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;field.add(ring)}field.visible=false;
const beamGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);const beam=new THREE.Line(beamGeo,new THREE.LineBasicMaterial({color:0xe7b044,transparent:true,opacity:.8}));scene.add(beam);
function toast(s,secs=3){$('toast').textContent=s;$('toast').style.opacity=1;toastTime=secs}
let audio;function beep(freq=440,duration=.1){if(!sound)return;try{audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=freq;gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.start();osc.stop(audio.currentTime+duration)}catch{}}
function toggleMagnet(){if(paused||won)return;started=true;if(energy<8&&!magnet){toast('能量正在恢复，稍等片刻。');return}magnet=!magnet;held=null;moves++;beep(magnet?620:350);updateHUD()}
function polarity(){repel=!repel;held=null;beep(repel?280:550);updateHUD();toast(repel?'排斥模式：推开附近货物。':'吸引模式：靠近并拖运货物。')}
function pulse(){if(paused||won)return;if(energy<25){toast('脉冲需要 25% 能量。关闭磁力可加快充能。');return}started=true;energy-=25;moves++;for(const c of crates){if(c.delivered)continue;const dx=c.body.position.x-robotBody.position.x,dz=c.body.position.z-robotBody.position.z,d=Math.hypot(dx,dz);if(d<3.5&&d>.1){const sign=repel?1:-1;c.body.applyImpulse(new CANNON.Vec3(dx/d*13*sign,1,dz/d*13*sign));}}beep(180,.2);toast(repel?'排斥脉冲已释放':'吸引脉冲已释放');field.scale.setScalar(1.8);updateHUD()}
function updateHUD(){$('magnet-status').textContent=magnet?(held?'已连接 · 稳定拖运':repel?'已启动 · 排斥场':'已启动 · 搜索货物'):'待机 · 按 E 启动';$('magnet-dot').classList.toggle('on',magnet);$('polarity').innerHTML=`${repel?'－ 排斥模式':'＋ 吸引模式'} <span>Q</span>`;$('moves').textContent=String(moves).padStart(2,'0');$('delivered').textContent=docks.filter(d=>d.filled).length;$('energy-value').textContent=Math.round(energy)+'%';$('energy-bar').style.width=energy+'%';$('timer').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(Math.floor(elapsed%60)).padStart(2,'0')}
function showOverlay(html){paused=true;keys.clear();mouseTarget=null;$('overlay').innerHTML='<div class="modal">'+html+'</div>';$('overlay').classList.remove('hidden')}
function closeOverlay(){paused=false;$('overlay').classList.add('hidden');$('pause').textContent='Ⅱ'}
function win(){won=true;magnet=false;held=null;const stars=elapsed<100&&moves<18?3:elapsed<180?2:1;best[current]=Math.max(best[current]||0,stars);try{localStorage.setItem('magnet-works-best',JSON.stringify(best))}catch{}beep(880,.3);showOverlay(`<span class="eyebrow">SHIFT COMPLETE / 作业完成</span><h2>${current===4?'完美收工，小小工程师。':'每件货物，都已就位。'}</h2><div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${current===4?'五个工厂区域已全部体验。试着用更少的操作和时间完成三星挑战。':'磁力、耐心，还有一点巧思。下一片工厂区域等待你的到来。'}</p><div class="win-stats"><span>作业用时<b>${$('timer').textContent}</b></span><span>磁力操作<b>${moves}</b></span><span>归位货物<b>${docks.length}/${docks.length}</b></span></div><button class="primary" id="continue">${current===4?'重新挑战第一关':'前往下一区域 →'}</button><button class="secondary" id="retry">再试一次，争取三星</button>`);$('continue').onclick=()=>loadLevel((current+1)%levels.length);$('retry').onclick=()=>loadLevel(current)}
function tick(dt){if(paused)return;if(started&&!won)elapsed+=dt;frameTime+=dt;
 const right=new THREE.Vector3(1,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/4+angle),forward=new THREE.Vector3(-right.z,0,right.x);let mx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),mz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);let dir=right.multiplyScalar(mx).add(forward.multiplyScalar(mz));
 if(mouseTarget){dir.set(mouseTarget.x-robotBody.position.x,0,mouseTarget.z-robotBody.position.z);if(dir.length()<.2){mouseTarget=null;dir.set(0,0,0)}}
 if(dir.lengthSq()>.001){dir.normalize();started=true;robotBody.velocity.x=dir.x*3.2;robotBody.velocity.z=dir.z*3.2;const target=Math.atan2(dir.x,dir.z);robot.rotation.y+=Math.atan2(Math.sin(target-robot.rotation.y),Math.cos(target-robot.rotation.y))*Math.min(1,dt*12)}else{robotBody.velocity.x*=Math.pow(.02,dt);robotBody.velocity.z*=Math.pow(.02,dt)}
 energy=THREE.MathUtils.clamp(energy+dt*(magnet?-3.5:15),0,100);if(energy<=0&&magnet){magnet=false;held=null;toast('磁力暂时离线。休息一下，能量会自动恢复。')}
 if(magnet){if(!repel){if(!held){let distance=2.5;for(const c of crates){const d=c.body.position.distanceTo(robotBody.position);if(!c.delivered&&d<distance){held=c;distance=d;beep(700)}}}if(held){const c=held,dx=c.body.position.x-robotBody.position.x,dz=c.body.position.z-robotBody.position.z,d=Math.hypot(dx,dz);if(d>4)held=null;else{const targetX=robotBody.position.x+(d>.01?dx/d:0)*1.02,targetZ=robotBody.position.z+(d>.01?dz/d:1)*1.02;c.body.applyImpulse(new CANNON.Vec3(((targetX-c.body.position.x)*8-c.body.velocity.x)*Math.min(1,dt*12)*c.body.mass*(c.heavy?.6:1),0,((targetZ-c.body.position.z)*8-c.body.velocity.z)*Math.min(1,dt*12)*c.body.mass*(c.heavy?.6:1)))}}}else{for(const c of crates){const dx=c.body.position.x-robotBody.position.x,dz=c.body.position.z-robotBody.position.z,d=Math.hypot(dx,dz);if(!c.delivered&&d<2.8&&d>.1)c.body.applyImpulse(new CANNON.Vec3(dx/d*22*(1-d/3)*dt,0,dz/d*22*(1-d/3)*dt))}}}
 const l=levels[current];if(l.belt){for(const c of crates)if(!c.delivered&&Math.abs(c.body.position.z)<.75&&Math.abs(c.body.position.x)<4)c.body.applyImpulse(new CANNON.Vec3(c.body.mass*4*dt,0,0));for(const o of objects)if(o.userData.belt){o.position.x+=dt*.8;if(o.position.x>3.9)o.position.x=-3.9}}
 if(plate){const open=crates.some(c=>Math.hypot(c.body.position.x-plate.x,c.body.position.z-plate.z)<.68)||Math.hypot(robotBody.position.x-plate.x,robotBody.position.z-plate.z)<.65;if(open!==gateOpen){gateOpen=open;gate.body.collisionResponse=!open;plate.mesh.material.color.set(open?0x89b183:0xd7b163);toast(open?'压力开关已激活 · 闸门开启':'压力开关已释放 · 闸门关闭');beep(open?540:260)}const y=gateOpen?-.9:1;gate.mesh.position.y=THREE.MathUtils.lerp(gate.mesh.position.y,y,dt*5);objects.filter(o=>!o.userData.belt).forEach((o,i)=>o.position.y=gate.mesh.position.y-.7+i*.2)}
 world.step(1/60,dt,3);robot.position.set(robotBody.position.x,robotBody.position.y-.5,robotBody.position.z);
 for(const c of crates){if(c.delivered)continue;if(c.body.position.y<-1||Math.abs(c.body.position.x)>7.5||Math.abs(c.body.position.z)>5.5||(l.hazards||[]).some(h=>Math.hypot(c.body.position.x-h[0],c.body.position.z-h[1])<.55)){c.body.position.copy(c.spawn);c.body.velocity.setZero();c.body.angularVelocity.setZero();c.body.quaternion.set(0,0,0,1);held=null;toast('货物已自动回收。绕开危险区域，再试一次。')}
 c.mesh.position.copy(c.body.position);c.mesh.quaternion.copy(c.body.quaternion);
 const dock=docks.find(d=>!d.filled&&d.color===c.color&&Math.hypot(c.body.position.x-d.x,c.body.position.z-d.z)<.72);if(dock&&(!magnet||held!==c)&&c.body.velocity.length()<.75){c.settle+=dt;if(c.settle>.6){dock.filled=true;c.delivered=true;c.body.position.set(dock.x,c.size/2+.02,dock.z);c.body.quaternion.set(0,0,0,1);c.mesh.position.copy(c.body.position);c.mesh.quaternion.copy(c.body.quaternion);c.body.velocity.setZero();c.body.angularVelocity.setZero();c.body.type=CANNON.Body.STATIC;c.body.mass=0;c.body.updateMassProperties();const i=docks.indexOf(dock);$('cargo-'+i).classList.add('complete');$('cargo-'+i).querySelector('b').textContent='已入库 ✓';beep(780,.2);toast('货物入库成功。干得漂亮！');if(docks.every(d=>d.filled))win()}}else c.settle=0;
 }
 field.visible=magnet;field.position.set(robotBody.position.x,.19,robotBody.position.z);field.scale.lerp(new THREE.Vector3(1,1,1),dt*4);field.children.forEach((r,i)=>{r.material.color.set(repel?0x70a9a1:0xe9b64e);r.material.opacity=.13+Math.sin(frameTime*3-i)*.12});beam.visible=!!held&&magnet&&!repel;if(beam.visible){const a=beam.geometry.attributes.position;a.setXYZ(0,robot.position.x,.65,robot.position.z);a.setXYZ(1,held.body.position.x,held.body.position.y,held.body.position.z);a.needsUpdate=true;beam.geometry.computeBoundingSphere()}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0}updateHUD();}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();updateCamera()}
function updateCamera(){const narrow=stage.clientWidth<760;const dist=narrow?39:20;camera.position.set(Math.sin(Math.PI/4+angle)*dist,dist*.92,Math.cos(Math.PI/4+angle)*dist);camera.lookAt(narrow?new THREE.Vector3(0,0,0):cameraTarget);}
$('pulse').onclick=pulse;$('polarity').onclick=polarity;$('reset').onclick=()=>loadLevel(current);$('rotate').onclick=()=>{angle+=Math.PI/2;updateCamera()};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♩';$('sound').title=sound?'声音已开启':'声音已关闭';beep(550)};
function pause(){if(won)return;if(paused){closeOverlay();return}showOverlay('<span class="eyebrow">TAKE A BREATHER</span><h2>稍作休息。</h2><p>工厂会等你回来。准备好后，继续你的搬运作业。</p><button class="primary" id="resume">继续作业 →</button>');$('resume').onclick=closeOverlay;$('pause').textContent='▶'}$('pause').onclick=pause;
$('guide').onclick=()=>{showOverlay('<span class="eyebrow">OPERATOR’S MANUAL</span><h2>你好，磁力操作员。</h2><p>把彩色货箱放进同色装卸区，关闭磁力并等待货物稳定，即可完成入库。也可以点击地面移动机器人。</p><div class="guide-row"><kbd>W A S D / 方向键</kbd>移动机器人<br><kbd>E</kbd>开启吸引 / 释放货物<br><kbd>Q</kbd>切换吸引与排斥极性<br><kbd>SPACE</kbd>释放磁力脉冲，消耗 25% 能量<br><kbd>R</kbd>重置本关 <kbd>ESC</kbd>暂停</div><p>灰箱用于压住开关；箭头皮带推动货物；红色区域会回收误入货物。关闭磁力自动充能。100 秒内且少于 18 次磁力操作可获三星。</p><button class="primary" id="got-it">准备好了 →</button>');$('got-it').onclick=closeOverlay};
$('levels').onclick=()=>{showOverlay('<span class="eyebrow">EXPLORE THE FACTORY</span><h2>每一区，都是新挑战。</h2>'+levels.map((l,i)=>`<button class="level-btn" data-level="${i}"><strong>0${i+1}</strong><span>${l.name}<small>${l.tag}</small></span><em>${best[i]?'★'.repeat(best[i]):i===current?'进行中':'→'}</em></button>`).join('')+'<button class="secondary" id="back">返回作业</button>');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>loadLevel(Number(b.dataset.level)));$('back').onclick=closeOverlay};$('next-hint').onclick=()=>toast(levels[current].hint,8);
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'){pause();return}if(paused)return;keys.add(k);mouseTarget=null;if(k==='e')toggleMagnet();if(k==='q')polarity();if(k===' ')pulse();if(k==='r')loadLevel(current)});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();mouseTarget=null});
const raycaster=new THREE.Raycaster();const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);renderer.domElement.addEventListener('pointerdown',e=>{if(paused||won)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){mouseTarget={x:THREE.MathUtils.clamp(p.x,-6.4,6.4),z:THREE.MathUtils.clamp(p.z,-4.3,4.3)};started=true}});$('magnet-status').parentElement.parentElement.style.cursor='pointer';$('magnet-status').parentElement.parentElement.onclick=toggleMagnet;
new ResizeObserver(resize).observe(stage);loadLevel(0);resize();let last=performance.now();function animate(now){const dt=Math.min((now-last)/1000,.05);last=now;tick(dt);renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate);
// Read-only diagnostic snapshot for local verification.
window.gameSnapshot=()=>({level:current+1,paused,magnet,held:held?.color||null,repel,energy,moves,elapsed,delivered:docks.filter(d=>d.filled).length,robot:{x:robotBody.position.x,z:robotBody.position.z},crates:crates.map(c=>({color:c.color,x:c.body.position.x,z:c.body.position.z,delivered:c.delivered})),gateOpen});
