#!/usr/bin/env python3
"""Build the static game collection with only the Python standard library."""

import argparse
import html
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import quote


REPOSITORY_URL = "https://github.com/QZEming/sentence-to-game"
GAME_DIRECTORY = re.compile(r"^\d{3}-[a-z0-9]+(?:-[a-z0-9]+)*$")
BUILD_MARKER = ".sentence-to-game-build"
BUILD_MARKER_CONTENT = "Generated by scripts/build-site.py\n"
EXCLUDED_DIRECTORIES = {"node_modules", "__pycache__", "venv"}
EXCLUDED_FILES = {
    "id_rsa", "id_ed25519", "credentials", "credentials.json",
    "secrets.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock",
}
EXCLUDED_SUFFIXES = {".pem", ".key", ".p12", ".pfx", ".keystore", ".pyc"}


def excluded(path):
    name = path.name.lower()
    return (
        name.startswith(".")
        or name in EXCLUDED_DIRECTORIES
        or name in EXCLUDED_FILES
        or path.suffix.lower() in EXCLUDED_SUFFIXES
    )


def game_title(game):
    readme = game / "README.md"
    if readme.is_file():
        for line in readme.read_text(encoding="utf-8").splitlines():
            match = re.match(r"^#\s+(.+?)\s*#*\s*$", line)
            if match:
                return match.group(1)
    return game.name.split("-", 1)[1].replace("-", " ")


def discover_games(root):
    games = []
    games_directory = root / "games"
    if not games_directory.is_dir():
        return games
    for game in sorted(games_directory.iterdir()):
        if not GAME_DIRECTORY.fullmatch(game.name):
            continue
        if game.is_symlink():
            raise ValueError(f"游戏目录不能是符号链接：{game}")
        if not game.is_dir():
            continue
        source = next(
            (game / folder for folder in ("dist", "src")
             if (game / folder / "index.html").is_file()),
            None,
        )
        if source is None:
            raise ValueError(
                f"游戏 {game.name} 缺少静态入口：请提供 "
                "dist/index.html 或 src/index.html。需要构建的项目请先生成 dist/。"
            )
        if source.is_symlink() or (source / "index.html").is_symlink():
            raise ValueError(f"游戏入口不能是符号链接：{source / 'index.html'}")
        games.append((game, source, game_title(game)))
    return games


def copy_web_files(source, destination):
    destination.mkdir(parents=True, exist_ok=True)
    for item in sorted(source.iterdir()):
        if excluded(item):
            continue
        if item.is_symlink():
            raise ValueError(f"发布资源不能是符号链接：{item}")
        target = destination / item.name
        if item.is_dir():
            copy_web_files(item, target)
        elif item.is_file():
            shutil.copy2(item, target)


def render_index(games):
    cards = []
    for game, source, title in games:
        name = quote(game.name, safe="")
        cards.append(f"""<article class="game">
  <span class="number">{html.escape(game.name[:3])}</span>
  <h2>{html.escape(title)}</h2>
  <div class="links">
    <a class="play" href="games/{name}/">开始体验 <span aria-hidden="true">↗</span></a>
    <a href="{REPOSITORY_URL}/tree/main/games/{name}/src">源码</a>
    <a href="{REPOSITORY_URL}/blob/main/games/{name}/prompt.txt">提示词</a>
  </div>
</article>""")
    collection = "\n".join(cards) if cards else """<div class="empty">
  <h2>第一个游戏，即将登场。</h2>
  <p>把一个想法写成一句话，再把它变成可以玩的游戏。</p>
</div>"""
    count = len(games)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="一句话，100 个游戏。收录原始提示词、源码和可以直接体验的游戏。">
  <title>一句话，100 个游戏 · sentence-to-game</title>
  <style>
    :root {{ color-scheme: light; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #202836; background: #f7f7f4; }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; }}
    main {{ max-width: 1040px; margin: 0 auto; padding: 64px 24px 40px; }}
    a {{ color: #304e87; text-underline-offset: 4px; }}
    a:hover {{ color: #152b52; }}
    a:focus-visible {{ outline: 3px solid #6384bd; outline-offset: 4px; }}
    .eyebrow {{ font-size: 14px; letter-spacing: .04em; color: #68717f; }}
    h1 {{ margin: 14px 0; font-size: clamp(30px, 5vw, 48px); letter-spacing: -.04em; line-height: 1.2; }}
    .intro {{ max-width: 650px; color: #68717f; font-size: 17px; line-height: 1.8; }}
    .progress {{ display: flex; align-items: center; gap: 18px; margin: 28px 0 42px; }}
    .progress strong {{ font-size: 15px; white-space: nowrap; }}
    progress {{ width: min(280px, 50vw); height: 8px; accent-color: #304e87; border: 0; border-radius: 8px; overflow: hidden; }}
    progress::-webkit-progress-bar {{ background: #e3e6e9; }}
    progress::-webkit-progress-value {{ background: #304e87; }}
    .collection {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 280px), 1fr)); gap: 18px; }}
    .game, .empty {{ background: #fff; border: 1px solid #e3e6e9; border-radius: 14px; padding: 26px; }}
    .number {{ color: #7a8492; font-size: 13px; font-variant-numeric: tabular-nums; }}
    h2 {{ margin: 12px 0 24px; font-size: 22px; line-height: 1.4; overflow-wrap: anywhere; }}
    .links {{ display: flex; align-items: center; gap: 16px; flex-wrap: wrap; font-size: 14px; }}
    .play {{ font-weight: 600; }}
    .empty {{ padding: 42px 28px; }}
    .empty h2 {{ margin: 0 0 12px; }}
    .empty p {{ margin: 0; color: #68717f; line-height: 1.8; }}
    footer {{ margin-top: 40px; padding-top: 22px; border-top: 1px solid #e3e6e9; color: #68717f; font-size: 14px; line-height: 1.8; }}
    @media (max-width: 520px) {{ main {{ padding: 40px 18px 28px; }} .intro {{ font-size: 16px; }} .progress {{ margin-bottom: 30px; }} }}
  </style>
</head>
<body>
  <main>
    <header>
      <div class="eyebrow">sentence-to-game</div>
      <h1>一句话，100 个游戏。</h1>
      <p class="intro">记录用一句话做出游戏的过程。每个游戏都保留原始提示词、源码和体验地址，让想法可以被试玩，也可以被继续改造。</p>
      <div class="progress">
        <strong>{count} / 100</strong>
        <progress value="{min(count, 100)}" max="100" aria-label="已收录 {count} 个游戏"></progress>
      </div>
    </header>
    <section class="collection" aria-label="游戏合集">
      {collection}
    </section>
    <footer><a href="{REPOSITORY_URL}">在 GitHub 查看项目、提示词与源码</a></footer>
  </main>
</body>
</html>
"""


def prepare_output(root, output):
    protected = [root, root / "games", root / "templates", root / "scripts", root / ".github", root / ".git"]
    if any(output == path or output in path.parents for path in protected):
        raise ValueError(f"输出路径不能覆盖仓库或源码目录：{output}")
    if any(path in output.parents for path in protected[1:]):
        raise ValueError(f"输出路径不能位于源码或仓库配置目录中：{output}")
    if output.exists():
        marker = output / BUILD_MARKER
        if any(output.iterdir()) and (
            not marker.is_file()
            or marker.read_text(encoding="utf-8") != BUILD_MARKER_CONTENT
        ):
            raise ValueError(f"输出目录不是本脚本生成的站点，请使用空目录：{output}")
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / BUILD_MARKER).write_text(BUILD_MARKER_CONTENT, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="Repository root")
    parser.add_argument("--output", type=Path, help="Output directory; relative paths are resolved from the repository root (default: docs)")
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output or Path("docs")
    if not output.is_absolute():
        output = root / output
    if output.is_symlink():
        parser.exit(1, f"构建失败：输出目录不能是符号链接：{output}\n")
    output = output.resolve()
    try:
        games = discover_games(root)
        prepare_output(root, output)
        for game, source, _ in games:
            copy_web_files(source, output / "games" / game.name)
        (output / "index.html").write_text(render_index(games), encoding="utf-8")
        (output / ".nojekyll").touch()
    except (OSError, UnicodeError, ValueError) as error:
        parser.exit(1, f"构建失败：{error}\n")
    print(f"已构建 {len(games)} / 100 个游戏：{output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
