import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import './style.css';
const icons={spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>',play:'<path d="m8 5 11 7-11 7Z"/>',undo:'<path d="M9 5 4 10l5 5M4 10h10a6 6 0 0 1 0 12"/>',reset:'<path d="M4 10a8 8 0 1 1 1 8M4 3v7h7"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3c-1 0-1 1-1 2m0 3h.01"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',leaf:'<path d="M20 3C4 2 1 12 7 17S22 15 20 3ZM4 21 16 9"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
const ico=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icons[n]||icons.spark}</svg>`;
const levels=[
{name:'初见微光',sub:'THE AWAKENING',story:'森林睡着了，一位旅人还没有回家。\n借一点萤火，为他照亮前方吧。',budget:14,start:[0,5],goal:[6,1],blocks:[[0,0],[1,0],[5,6],[6,6],[2,2],[2,3],[4,3]],stars:[[2,5],[4,1]],switches:[],gates:[],mud:[],portals:[],shadow:[]},
{name:'苔间回声',sub:'MOSS & MEMORIES',story:'遗落的记忆藏在苔藓深处。\n湿地会消耗两份光能，试着绕行。',budget:16,start:[0,6],goal:[6,0],blocks:[[1,1],[2,1],[4,1],[4,2],[2,4],[3,4],[4,4]],stars:[[1,4],[5,2],[3,0]],switches:[],gates:[],mud:[[1,5],[2,5],[3,5],[5,3]],portals:[],shadow:[]},
{name:'月门低语',sub:'THE MOON GATE',story:'古老的月门挡住了归途。\n先唤醒月光石，再穿过封印。',budget:18,start:[0,5],goal:[6,1],blocks:[[3,0],[3,1],[3,2],[3,4],[3,5],[3,6],[1,3]],stars:[[2,1],[5,4]],switches:[[1,1]],gates:[[3,3]],mud:[[4,3]],portals:[],shadow:[]},
{name:'星河两岸',sub:'ACROSS THE STARS',story:'有些距离，只有星光能够跨越。\n踏上紫色星石，点击另一端瞬间穿行。',budget:15,start:[0,6],goal:[6,0],blocks:[[3,0],[3,1],[3,2],[3,3],[3,4],[3,5],[3,6]],stars:[[0,2],[6,3]],switches:[],gates:[],mud:[[1,4],[5,2]],portals:[[2,2],[4,4]],shadow:[]},
{name:'暗影之舞',sub:'A DANCE WITH SHADOWS',story:'暗影在林间徘徊，光也学会等待。\n旅人会在安全处停步，等暗影经过。',budget:16,start:[0,5],goal:[6,1],blocks:[[2,2],[2,3],[4,3],[4,4]],stars:[[2,5],[4,1],[6,4]],switches:[],gates:[],mud:[[3,4],[3,3]],portals:[],shadow:[[3,1],[3,2],[3,3],[3,4],[3,5]]},
{name:'长夜归途',sub:'THE WAY HOME',story:'所有微小的光，终会汇成星河。\n穿过月门与暗影，把最后一位旅人送回家。',budget:22,start:[0,6],goal:[6,0],blocks:[[3,0],[3,1],[3,2],[3,4],[3,5],[3,6],[1,3]],stars:[[0,1],[4,5],[5,1]],switches:[[2,1]],gates:[[3,3]],mud:[[1,5],[2,5],[4,2]],portals:[[1,1],[5,5]],shadow:[[4,1],[4,2],[4,3],[4,4]]}
];
const key=p=>p.join(',');const eq=(a,b)=>a&&b&&key(a)===key(b);const has=(xs,p)=>xs.some(x=>eq(x,p));
let saved={};try{saved=JSON.parse(localStorage.getItem('lumen-progress')||'{}')}catch{}
let index=0,route=[],running=false,paused=false,elapsed=0,walkIndex=0,walkT=0,collected=[],sound=false,audioCtx,hoverCell=null,hintCell=null;
document.querySelector('#app').innerHTML=`<header><a class="brand" href="./"><span class="brand-mark">${ico('spark')}</span><strong>萤途<span>LUMEN</span></strong></a><nav><span class="nav-active">林间旅程</span><button id="chapters">旅途手记 <span class="tiny">06</span></button></nav><div class="header-right"><span class="night">● 夜色正好</span><button class="icon-button" id="sound" title="开启环境音" aria-label="开启环境音">${ico('sound')}</button><button class="icon-button" id="help" title="玩法说明" aria-label="玩法说明">${ico('help')}</button></div></header>
<main><aside><div class="eyebrow">A LITTLE LIGHT. A WAY HOME.</div><h1>把微光，<br>连成归途<span>。</span></h1><p class="intro">你是森林里的引路者。<br>让萤火相连，带迷路的人回家。</p><div class="chapter-heading"><span>当前旅程</span><span id="chapter-count">01 / 06</span></div><button class="chapter-card" id="chapter-card"><div class="chapter-icon">${ico('leaf')}</div><div><small id="level-sub"></small><h2 id="level-name"></h2></div><span class="chevron">⌄</span></button><p class="story" id="story"></p><div class="resources"><div><span>可用光能</span><strong><b id="energy">14</b><small id="energy-total"> / 14</small></strong></div><div class="energy-bars" id="energy-bars"></div><div class="resource-foot"><span>${ico('spark')} 每一步，都是一点希望</span><span id="cost">已用 0</span></div></div><div class="memory"><div class="memory-icon">◇</div><div><span>记忆碎片</span><small>收集散落的故事，点亮这片森林</small></div><strong id="fragments">0 / 2</strong></div><div class="objective"><span class="objective-dot"></span><div><strong id="objective">为旅人规划一条光路</strong><p id="instruction">从旅人脚下开始，点击相邻的石块</p></div></div><button class="primary" id="go">${ico('play')}<span>跟随微光</span><kbd>SPACE</kbd></button><div class="secondary-row"><button id="undo">${ico('undo')} 撤回</button><button id="reset">${ico('reset')} 重新规划</button></div><div class="sidebar-bottom">${ico('moon')} 不必匆忙，微光会等你。</div></aside>
<section class="world"><div id="scene"></div><div class="scene-top"><div><span class="live-dot"></span> 静谧森林 <span class="scene-divider">/</span> <span id="scene-title">第一章 · 初见微光</span></div><button id="view" class="glass-button">${ico('eye')} 视角复位</button></div><div class="scene-label"><span>THE WHISPERING WOODS</span><h3>每一束微光，都有方向。</h3></div><div class="compass"><span>N</span><div>✧</div></div><div class="toast" id="toast">点击旅人附近的石块，唤醒第一束光</div><div class="scene-bottom"><div class="legend"><span><i class="dot mint"></i>光路</span><span><i class="dot gold"></i>记忆碎片</span><span><i class="dot white"></i>归途</span></div><button id="hint" class="glass-button">${ico('spark')} 借一点灵感 <span>↗</span></button></div><div class="controls-note">左键铺设光路 <span>·</span> 拖动旋转 <span>·</span> 滚轮缩放</div></section></main><footer><span>让世界亮一点点。</span><div id="level-dots"></div><span>LUMEN <i>✧</i> A QUIET ADVENTURE</span></footer><div id="modal" class="modal" hidden></div>`;
const $=s=>document.querySelector(s);const level=()=>levels[index];
let scene,camera,renderer,controls,board,traveler,routeGroup,particles,shadowMesh,gateMeshes=[],starMeshes=[],tiles=[],portalMeshes=[],time=0;
const canvasHost=$('#scene');
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('#toast').textContent='当前浏览器未开启 WebGL，请在支持 3D 的浏览器中打开。';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x091719,0);canvasHost.appendChild(renderer.domElement);
scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0b1c20,.023);camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(12,14,16);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.minDistance=12;controls.maxDistance=29;controls.maxPolarAngle=Math.PI*.43;controls.minPolarAngle=.3;controls.enablePan=false;
scene.add(new THREE.HemisphereLight(0xc1e5d7,0x16302d,2.8));const moon=new THREE.DirectionalLight(0xaad6ce,3.8);moon.position.set(-5,12,4);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-12;moon.shadow.camera.right=12;moon.shadow.camera.top=12;moon.shadow.camera.bottom=-12;scene.add(moon);const rim=new THREE.DirectionalLight(0x42c5a9,1.3);rim.position.set(4,3,-8);scene.add(rim);
const mat=(c,opts={})=>new THREE.MeshStandardMaterial({color:c,roughness:.9,...opts});const terrainMats=[mat(0x456059),mat(0x4b655d),mat(0x3d5852),mat(0x526b61)];
function mesh(geo,material,x,y,z,parent=board){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function pos(p,y=.22){return new THREE.Vector3((p[0]-3)*1.13,y,(p[1]-3)*1.13)}
function rng(n){let x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)}
function tree(x,z,s=1,seed=1){const g=new THREE.Group();g.position.set(x,-.3,z);board.add(g);mesh(new THREE.CylinderGeometry(.08*s,.14*s,1.2*s,5),mat(0x433f36),0,.55*s,0,g);for(let j=0;j<3;j++)mesh(new THREE.ConeGeometry((.8-j*.16)*s,(1.5-j*.17)*s,6),mat([0x20463e,0x285449,0x356556][j]),0,(1.05+j*.55)*s,0,g);g.rotation.y=seed;}
function clearGroup(g){if(!g)return;g.traverse(o=>{if(o.geometry)o.geometry.dispose();});scene.remove(g)}
function build(){clearGroup(board);clearGroup(routeGroup);board=new THREE.Group();scene.add(board);tiles=[];starMeshes=[];gateMeshes=[];portalMeshes=[];const l=level();
mesh(new THREE.CylinderGeometry(6.15,5.1,1.3,11),mat(0x203c37),0,-1.12,0);mesh(new THREE.CylinderGeometry(6.2,6.05,.28,11),mat(0x314d42),0,-.42,0);
for(let x=0;x<7;x++)for(let z=0;z<7;z++){const p=[x,z],v=pos(p,0);if(has(l.blocks,p)){mesh(new THREE.DodecahedronGeometry(.48,0),mat(0x3a4b46),v.x,.2,v.z).scale.set(1,1.1,1);continue}const tile=mesh(new THREE.BoxGeometry(1.05,.34,1.05),has(l.mud,p)?mat(0x756344):terrainMats[(x*7+z)%4],v.x,-.15,v.z);tile.userData.cell=p;tiles.push(tile);if(rng(x*7+z)>.7){for(let q=0;q<3;q++)mesh(new THREE.ConeGeometry(.04,.2,3),mat(0x6b8870),v.x+.37+q*.04,.12,v.z+.3-q*.1);}}
for(let i=0;i<27;i++){const a=i/27*Math.PI*2,r=4.45+rng(i+10)*1.05,x=Math.cos(a)*r,z=Math.sin(a)*r;if(z>2&&x>-4&&x<3&&i%2===0)continue;tree(x,z,(.65+rng(i+20)*.65)*(x+z>2?.58:1),i);}
for(let i=0;i<30;i++){const a=rng(i+50)*Math.PI*2,r=4+rng(i+60)*1.8;mesh(new THREE.DodecahedronGeometry(.1+rng(i+70)*.2),mat(0x708574),Math.cos(a)*r,-.16,Math.sin(a)*r);}
for(let i=0;i<19;i++){const a=rng(i+80)*6.28,r=4.05+rng(i+90)*1.3,x=Math.cos(a)*r,z=Math.sin(a)*r;mesh(new THREE.CylinderGeometry(.035,.045,.19,5),mat(0x9cae93),x,-.1,z);mesh(new THREE.SphereGeometry(.115,8,5,0,6.28,0,Math.PI/2),mat(0x83ead4,{emissive:0x43caaa,emissiveIntensity:.7}),x,.01,z);}
for(const p of l.stars){const v=pos(p,.52);const s=mesh(new THREE.OctahedronGeometry(.16),mat(0xffd58a,{emissive:0xf6b957,emissiveIntensity:1.3}),v.x,v.y,v.z);s.userData.cell=p;starMeshes.push(s);const ring=mesh(new THREE.TorusGeometry(.29,.014,5,32),mat(0xa98c54,{emissive:0x6f5422}),v.x,.045,v.z);ring.rotation.x=-Math.PI/2;}
for(const p of l.switches){const v=pos(p);mesh(new THREE.CylinderGeometry(.3,.35,.16,6),mat(0x506b91,{emissive:0x476db2,emissiveIntensity:.4}),v.x,.1,v.z);mesh(new THREE.OctahedronGeometry(.17),mat(0xb0ceff,{emissive:0x638cff,emissiveIntensity:1}),v.x,.4,v.z);}
for(const p of l.gates){const v=pos(p);const gate=mesh(new THREE.TorusGeometry(.46,.08,6,20,Math.PI),mat(0x839eb3,{emissive:0x4c709e,emissiveIntensity:.5}),v.x,.43,v.z);gateMeshes.push(gate);}
for(const p of l.portals){const v=pos(p);const m=mesh(new THREE.TorusGeometry(.34,.045,8,40),mat(0xc6a1ef,{emissive:0x9d64e4,emissiveIntensity:1.4}),v.x,.13,v.z);m.rotation.x=-Math.PI/2;portalMeshes.push(m);}
const g=pos(l.goal);const stone=mat(0xc5d3bb);mesh(new THREE.BoxGeometry(.13,.85,.19),stone,g.x-.33,.45,g.z);mesh(new THREE.BoxGeometry(.13,.85,.19),stone,g.x+.33,.45,g.z);mesh(new THREE.BoxGeometry(.82,.13,.24),stone,g.x,.89,g.z);mesh(new THREE.PlaneGeometry(.48,.72),new THREE.MeshBasicMaterial({color:0xdaf5c0,transparent:true,opacity:.32,side:THREE.DoubleSide}),g.x,.44,g.z);const homeLight=new THREE.PointLight(0xd8ffb1,2,3);homeLight.position.set(g.x,.7,g.z);board.add(homeLight);
traveler=new THREE.Group();board.add(traveler);mesh(new THREE.ConeGeometry(.19,.4,7),mat(0xd2b38a),0,.32,0,traveler);mesh(new THREE.SphereGeometry(.115,10,8),mat(0xe7c9a2),0,.57,0,traveler);mesh(new THREE.ConeGeometry(.18,.2,6),mat(0xdbc5a2),0,.7,0,traveler);mesh(new THREE.SphereGeometry(.065,8,6),mat(0xffe6a1,{emissive:0xffcc66,emissiveIntensity:2}),.24,.36,0,traveler);traveler.position.copy(pos(l.start,0));shadowMesh=mesh(new THREE.SphereGeometry(.38,12,8),mat(0x373045,{transparent:true,opacity:.85}),0,.3,0);shadowMesh.visible=l.shadow.length>0;
updateRoute();}
const particleGeo=new THREE.BufferGeometry();const pp=new Float32Array(180*3);for(let i=0;i<180;i++){pp[i*3]=(rng(i+200)-.5)*20;pp[i*3+1]=rng(i+500)*5;pp[i*3+2]=(rng(i+900)-.5)*20}particleGeo.setAttribute('position',new THREE.BufferAttribute(pp,3));particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({color:0xc8eea9,size:.037,transparent:true,opacity:.65}));scene.add(particles);
const fireflies=[];for(let i=0;i<7;i++){const fly=new THREE.Group();scene.add(fly);mesh(new THREE.SphereGeometry(.045,8,6),mat(0xeaffad,{emissive:0xcaff7d,emissiveIntensity:2}),0,0,0,fly);for(const side of [-1,1]){const wing=mesh(new THREE.SphereGeometry(.055,6,4),new THREE.MeshBasicMaterial({color:0xcaffdf,transparent:true,opacity:.45}),side*.052,.025,0,fly);wing.scale.set(1,.2,.55)}fireflies.push(fly)}const guideLight=new THREE.PointLight(0xd9ff99,1.4,3);scene.add(guideLight);
function spent(r=route){return r.slice(1).reduce((a,p)=>a+(has(level().mud,p)?2:1),0)}function unlocked(r=route){return level().switches.some(p=>has(r,p))}
function updateRoute(){clearGroup(routeGroup);routeGroup=new THREE.Group();scene.add(routeGroup);for(let i=0;i<route.length;i++){const p=pos(route[i],.08);const disc=mesh(new THREE.CylinderGeometry(.16,.16,.025,20),mat(0xa8f3bd,{emissive:0x78eaa4,emissiveIntensity:1}),p.x,p.y,p.z,routeGroup);if(i){const before=pos(route[i-1],.08);if(p.distanceTo(before)<1.5){const curve=new THREE.LineCurve3(before,p);mesh(new THREE.TubeGeometry(curve,1,.027,5,false),mat(0xc7ffb7,{emissive:0x91e8a4,emissiveIntensity:1}),0,0,0,routeGroup)}}}updateUI()}
function updateUI(){const l=level(),cost=spent();$('#level-name').textContent=l.name;$('#level-sub').textContent=l.sub;$('#story').innerText=l.story;$('#chapter-count').textContent=`0${index+1} / 06`;$('#scene-title').textContent=`第${'一二三四五六'[index]}章 · ${l.name}`;$('#energy').textContent=l.budget-cost;$('#energy-total').textContent=` / ${l.budget}`;$('#cost').textContent=`已用 ${cost}`;$('#energy-bars').innerHTML=Array.from({length:l.budget},(_,i)=>`<i class="${i<l.budget-cost?'filled':''}"></i>`).join('');const n=l.stars.filter(p=>has(running?collected:route,p)).length;$('#fragments').textContent=`${n} / ${l.stars.length}`;$('#go span').textContent=running?(paused?'继续前行':'暂停脚步'):'跟随微光';$('#objective').textContent=running?(paused?'旅人正在休息':'旅人正跟随微光'):eq(route.at(-1),l.goal)?'光路已连通，准备出发':'为旅人规划一条光路';$('#instruction').textContent=running?'等待暗影离开，旅人会自动继续':`${route.length-1} 步光路 · ${unlocked()?'月门已唤醒':'点击已点亮的石块可回退'}`;$('#level-dots').innerHTML=levels.map((l,i)=>`<button class="level-dot ${i===index?'active':''} ${saved[i]?'complete':''}" data-level="${i}" aria-label="第${i+1}章 ${l.name}">${i===index?`<span>0${i+1}</span>`:''}</button>`).join('');$('#undo').disabled=running;$('#hint').disabled=running;}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function load(i){index=i;route=[level().start];running=false;paused=false;collected=[];hintCell=null;build();toast(i===0?'点击旅人附近的石块，唤醒第一束光':level().story.split('\n')[1]);}
function neighbors(p,r){const l=level();let ns=[[p[0]+1,p[1]],[p[0]-1,p[1]],[p[0],p[1]+1],[p[0],p[1]-1]];if(has(l.portals,p))ns.push(l.portals.find(a=>!eq(a,p)));return ns.filter(q=>q[0]>=0&&q[0]<7&&q[1]>=0&&q[1]<7&&!has(l.blocks,q)&&(!has(l.gates,q)||unlocked(r)));}
function choose(p){if(running)return;const at=route.findIndex(q=>eq(q,p));if(at>=0){route=route.slice(0,at+1);updateRoute();return}if(!has(neighbors(route.at(-1),route),p)){toast(has(level().gates,p)?'月门还在沉睡，先经过蓝色月光石。':'光只能连接相邻石块；紫色星石可跨越两岸。');return}if(spent()+ (has(level().mud,p)?2:1)>level().budget){toast('光能不足。试试撤回几步，寻找更短的路线。');return}route.push(p);hintCell=null;chime(420+route.length*23);updateRoute();if(eq(p,level().goal))toast('归途已点亮。点击「跟随微光」，送旅人回家。');}
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();function hit(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster.intersectObjects(tiles)[0]?.object.userData.cell}let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<6){const p=hit(e);if(p)choose(p)}});renderer.domElement.addEventListener('pointermove',e=>{hoverCell=hit(e);renderer.domElement.style.cursor=hoverCell&&!running?'pointer':'grab'});
function chime(freq=440){if(!sound||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;o.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.65);o.start();o.stop(audioCtx.currentTime+.65)}
function go(){if(running){paused=!paused;updateUI();return}if(!eq(route.at(-1),level().goal)){toast('先把光路连接到发光的石门，再让旅人出发。');return}running=true;paused=false;walkIndex=0;walkT=0;elapsed=0;collected=[];traveler.position.copy(pos(route[0],0));updateUI();chime(660);}
function complete(){running=false;const count=level().stars.filter(p=>has(collected,p)).length;const rating=1+(count>0?1:0)+(count===level().stars.length?1:0);saved[index]=Math.max(saved[index]||0,rating);try{localStorage.setItem('lumen-progress',JSON.stringify(saved))}catch{}updateUI();chime(880);showModal(`<div class="completion-symbol">${ico('spark')}</div><div class="eyebrow">A LIGHT FOUND ITS WAY HOME</div><h2>${index===5?'长夜尽头，终于归家':'谢谢你，为我点亮归途。'}</h2><p>你的一点微光，成了旅人的整个星河。</p><div class="rating">${'✦'.repeat(rating)}<span>${'✧'.repeat(3-rating)}</span></div><div class="results"><div><strong>${route.length-1}</strong><span>温柔的脚步</span></div><div><strong>${count} / ${level().stars.length}</strong><span>找回的记忆</span></div><div><strong>${level().budget-spent()}</strong><span>剩余光能</span></div></div><button class="primary" id="next">${index===5?'重访这片森林':'走向下一片微光'} ${ico('arrow')}</button><button class="text-button" id="replay">再次探索 · 收集所有记忆</button>`);$('#next').onclick=()=>{closeModal();load((index+1)%levels.length)};$('#replay').onclick=()=>{closeModal();load(index)}}
function showModal(html){$('#modal').innerHTML=`<div class="modal-card"><button class="modal-close icon-button" aria-label="关闭">${ico('close')}</button>${html}</div>`;$('#modal').hidden=false;$('.modal-close').onclick=closeModal}function closeModal(){$('#modal').hidden=true}
function chapters(){showModal(`<div class="eyebrow">YOUR LITTLE JOURNEY</div><h2>森林还藏着许多故事。</h2><p>六段旅程，六种与微光相遇的方式。</p><div class="chapter-list">${levels.map((l,i)=>`<button data-chapter="${i}"><span class="chapter-num">0${i+1}</span><div><strong>${l.name}</strong><small>${l.sub}</small></div><span class="chapter-stars">${saved[i]?'✦'.repeat(saved[i]):'未探索'}</span>${ico('arrow')}</button>`).join('')}</div>`);document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{closeModal();load(+b.dataset.chapter)})}
$('#help').onclick=()=>showModal(`<div class="eyebrow">HOW TO FIND THE WAY</div><h2>做一位温柔的引路者。</h2><div class="help-list"><p><b>01 · 编织光路</b>从戴帽子的旅人出发，点击上下左右相邻石块。点击已铺设的位置可回退，空格开始或暂停行走。</p><p><b>02 · 留住微光</b>普通石块消耗 1 点光能，褐色湿地消耗 2 点。尽量收集金色记忆碎片，获得三颗星。</p><p><b>03 · 聆听森林</b>蓝色月光石开启月门；两块紫色星石可互相传送；遇见移动暗影时，旅人会在原地等待。</p><p><b>04 · 慢慢探索</b>拖动旋转视角，滚轮缩放。按 Z 撤回、R 重置、H 获取下一步提示、Esc 关闭弹窗。进度自动保存在此浏览器。</p></div>`);
$('#chapters').onclick=chapters;$('#chapter-card').onclick=chapters;$('#go').onclick=go;$('#undo').onclick=()=>{if(!running&&route.length>1){route.pop();updateRoute()}};$('#reset').onclick=()=>load(index);$('#view').onclick=()=>{camera.position.set(12,14,16);controls.target.set(0,0,0)};$('#level-dots').onclick=e=>{const b=e.target.closest('[data-level]');if(b)load(+b.dataset.level)};
$('#sound').onclick=()=>{sound=!sound;if(sound){audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();chime(528)}$('#sound').classList.toggle('enabled',sound);$('#sound').title=sound?'关闭环境音':'开启环境音';$('#sound').setAttribute('aria-label',$('#sound').title);toast(sound?'林间音符已开启':'林间音符已关闭')};
$('#hint').onclick=()=>{const queue=[route],visited=new Set();let found=null;while(queue.length){queue.sort((a,b)=>spent(a)-spent(b));const r=queue.shift(),p=r.at(-1),s=key(p)+'/'+unlocked(r);if(visited.has(s))continue;visited.add(s);if(eq(p,level().goal)){found=r;break}for(const n of neighbors(p,r))if(!has(r,n)&&spent(r)+(has(level().mud,n)?2:1)<=level().budget)queue.push([...r,n]);}if(found&&found.length>route.length){hintCell=found[route.length];toast('下一步已被金色微光标记。提示优先寻找归途，记忆需要你探索。')}else toast(eq(route.at(-1),level().goal)?'光路已经连通，可以出发了。':'从这里无法在剩余光能内抵达，试试撤回或重新规划。')};
window.addEventListener('keydown',e=>{if(e.code==='Escape'){closeModal();return}if(!$('#modal').hidden)return;if(e.code==='Space'){e.preventDefault();go()}if(e.code==='KeyR')load(index);if(e.code==='KeyZ')$('#undo').click();if(e.code==='KeyH')$('#hint').click()});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
function resize(){const w=canvasHost.clientWidth,h=canvasHost.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvasHost);
load(0);resize();let prev=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-prev)/1000,.05);prev=now;time+=dt;controls.update();const center=running?traveler.position:pos(route.at(-1),0);fireflies.forEach((fly,i)=>{const a=time*(.6+i*.05)+i*6.28/7,r=.25+(i%3)*.13;fly.position.set(center.x+Math.cos(a)*r,center.y+.55+Math.sin(a*1.8)*.15,center.z+Math.sin(a)*r);fly.rotation.y=-a});guideLight.position.copy(center).y+=.8;particles.rotation.y=time*.013;for(const s of starMeshes){s.rotation.y=time;s.position.y=.52+Math.sin(time*2+s.position.x)*.075;s.visible=!has(running?collected:route,s.userData.cell)}for(const m of portalMeshes)m.rotation.z=time*.4;for(const m of gateMeshes)m.material.emissiveIntensity=unlocked()?1.5:.3;for(const t of tiles){if(!t.userData.original)t.userData.original=t.material;t.material=t.userData.original;t.scale.y=eq(t.userData.cell,hoverCell)&&!running?1.15:1;if(eq(t.userData.cell,hintCell)){if(!t.userData.hintMat)t.userData.hintMat=mat(0xd0bc6d,{emissive:0x7d6b20,emissiveIntensity:.4});t.material=t.userData.hintMat}}
const shadows=level().shadow;const shadowPos=shadows.length?shadows[Math.floor(time/1.1)%shadows.length]:null;if(shadowPos){shadowMesh.position.copy(pos(shadowPos,.36+Math.sin(time*3)*.08));shadowMesh.scale.set(1,1.25+Math.sin(time*4)*.1,1)}
if(running&&!paused){elapsed+=dt;const next=route[walkIndex+1];if(next){if(!eq(next,shadowPos)||walkT>0){walkT+=dt*1.7;traveler.position.lerpVectors(pos(route[walkIndex],0),pos(next,0),Math.min(walkT,1));traveler.position.y=Math.sin(walkT*Math.PI)*.09;if(walkT>=1){walkIndex++;walkT=0;if(has(level().stars,next)){collected.push(next);chime(790);updateUI()}if(walkIndex===route.length-1)complete()}}}}renderer.render(scene,camera)}requestAnimationFrame(animate);
// A small read-only diagnostic surface for automated validation.
window.lumen={getState:()=>({level:index,route:route.map(p=>[...p]),running,paused,energy:level().budget-spent(),saved:{...saved}}),cellScreen:(p)=>{const v=pos(p,.05).project(camera),r=renderer.domElement.getBoundingClientRect();return {x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2}},levels};
