import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s), TAU=Math.PI*2;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dfe9cf');scene.fog=new THREE.Fog('#dfe9cf',65,140);
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,220);
scene.add(new THREE.HemisphereLight('#fff7dc','#7b9962',2.1));const sun=new THREE.DirectionalLight('#fff2ca',3);sun.position.set(-20,40,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,far:120});sun.shadow.bias=-.0005;scene.add(sun);
const materials=new Map();function mat(c){if(!materials.has(c))materials.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.92}));return materials.get(c)}
function mesh(geo,color,x=0,y=0,z=0,parent=scene){let m=new THREE.Mesh(geo,mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function ball(c,x,y,z,s=1,p=scene){let m=mesh(new THREE.IcosahedronGeometry(s,1),c,x,y,z,p);return m}
function cyl(c,x,y,z,r,h,p=scene,r2=r){return mesh(new THREE.CylinderGeometry(r,r2,h,8),c,x,y,z,p)}
function box(c,x,y,z,w,h,d,p=scene){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p)}
let seed=39;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}const range=(a,b)=>a+rnd()*(b-a);
mesh(new THREE.PlaneGeometry(250,250),'#a9c584',0,-.25,0).rotation.x=-Math.PI/2;
let ground=cyl('#a8c779',0,-.45,0,34,1.2,scene,35);ground.geometry=new THREE.CylinderGeometry(34,35,1.2,70);
// Gently rolling backdrop, distant shrubs and a garden boundary.
for(let i=0;i<28;i++){let a=i/28*TAU;let b=ball(i%2?'#a6be85':'#b8cb98',Math.cos(a)*range(44,75),range(0,3),Math.sin(a)*range(44,75),range(7,15));b.scale.y=.6;}
for(let i=0;i<43;i++){let a=i/43*TAU;let x=Math.cos(a)*31,z=Math.sin(a)*31;box('#e6dcb1',x,1,z,.3,2,.3);if(i<42){let b=box('#e4d8a9',Math.cos(a+.073)*31,.7,Math.sin(a+.073)*31,4.6,.16,.14);b.rotation.y=-a-Math.PI/2;let c=b.clone();c.position.y=1.4;scene.add(c)}}
// Warm stepping-stone trail into the apiary.
for(let i=0;i<19;i++){let x=-15+i*1.45,z=9+Math.sin(i*.35)*2;const stone=cyl(i%2?'#d4cfab':'#e1d9b7',x,.08,z,range(.6,1),.16);stone.scale.z=.68;stone.rotation.y=rnd()*3;}
const pond=cyl('#77b8b0',15,.055,-8,5.4,.1);pond.scale.z=.63;const water=mat('#77b8b0');water.metalness=.25;water.roughness=.3;
for(let i=0;i<19;i++){let a=i/19*TAU;let b=ball('#c0c5aa',15+Math.cos(a)*5.6,.25,-8+Math.sin(a)*3.55,.65);b.scale.set(1,.5,.7)}
for(let i=0;i<4;i++){let lily=cyl('#71966b',13+i,.17,-8+Math.sin(i),.58,.06);lily.rotation.y=i;}
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g);cyl('#9d865b',0,2,0,.42,4,g,.6);ball('#789c58',0,5,0,2.7,g);ball('#88a960',-1.4,4.4,.7,1.8,g);ball('#97b56b',1.2,5.4,.3,2,g);}
[[-24,-13,1.4],[-21,15,1.15],[24,12,1.3],[4,-25,1.4],[26,-20,1.1],[-9,-25,1.2],[-27,1,1]].forEach(a=>tree(...a));
for(let i=0;i<110;i++){let x=range(-30,30),z=range(-30,30);if(x*x+z*z>870)continue;let b=ball(['#91b166','#8eae63','#a2bf70'][i%3],x,.25,z,range(.25,.65));b.scale.y=.65;}
// Little wooden beehive with rounded honey-coloured tiers.
const home=new THREE.Vector3(-10,2,7);const hive=new THREE.Group();hive.position.set(home.x,0,home.z);scene.add(hive);
box('#967947',0,.5,0,3.7,.35,3.2,hive);for(const x of [-1.35,1.35])for(const z of [-1,1])box('#816b45',x,.2,z,.25,.6,.25,hive);
for(let i=0;i<5;i++)cyl(i%2?'#dfae48':'#e9bd56',0,1+i*.5,0,1.65-i*.18,.56,hive,1.72-i*.18);
ball('#f3ce70',0,3.35,0,.67,hive).scale.y=.6;let hole=ball('#604b30',0,1.1,1.55,.43,hive);hole.scale.z=.14;box('#ba8f44',0,.66,1.95,1.3,.15,1,hive);
function sign(text,x,z){const c=document.createElement('canvas');c.width=256;c.height=96;let ctx=c.getContext('2d');ctx.fillStyle='#fff6d8';ctx.fillRect(0,0,256,96);ctx.fillStyle='#7c7951';ctx.font='500 29px sans-serif';ctx.textAlign='center';ctx.fillText(text,128,59);const t=new THREE.CanvasTexture(c);let m=new THREE.Mesh(new THREE.PlaneGeometry(2.8,1.05),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide}));m.position.set(x,2,z);m.rotation.y=.35;scene.add(m);cyl('#95805a',x,.9,z,.08,1.8);}
sign('HOME · 蜂巢',-7,8.7);
const ring=new THREE.Mesh(new THREE.TorusGeometry(3,.045,8,64),new THREE.MeshBasicMaterial({color:'#ffe6a4',transparent:true,opacity:.65}));ring.rotation.x=-Math.PI/2;ring.position.set(home.x,.15,home.z);scene.add(ring);
const species=[{name:'雏菊',color:'#fff6df',center:'#eac247',value:3},{name:'粉蔷薇',color:'#eaa5b0',center:'#f5d379',value:4},{name:'薰衣草',color:'#ac95d2',center:'#e6c16e',value:5},{name:'金盏花',color:'#efbd50',center:'#9b6f38',value:6}];
const flowers=[];function flower(x,z,type,size=1){let sp=species[type],g=new THREE.Group();g.position.set(x,0,z);scene.add(g);let h=range(1.2,2.4)*size;cyl('#72974e',0,h/2,0,.055,h,g);let leaf=ball('#80a55d',.2,h*.4,0,.32,g);leaf.scale.set(1.4,.25,.65);leaf.rotation.z=.4;let head=new THREE.Group();head.position.y=h;g.add(head);for(let p=0;p<6;p++){let a=p/6*TAU;let petal=ball(sp.color,Math.cos(a)*.39*size,0,Math.sin(a)*.39*size,.31*size,head);petal.scale.set(1,.38,1.3);petal.rotation.y=-a;petal.rotation.z=.15;}ball(sp.center,0,.12,0,.23*size,head).scale.y=.6;flowers.push({g,head,x,z,type,h,ready:0,phase:rnd()*6});}
const patches=[[-2,4,0],[6,7,1],[3,-6,2],[-14,-5,3],[-18,2,0],[14,16,3],[20,2,1],[-3,-17,1],[12,-18,2],[0,18,0]];
patches.forEach(([x,z,t])=>{for(let i=0;i<13;i++){const a=rnd()*TAU,r=Math.sqrt(rnd())*3.4;flower(x+Math.cos(a)*r,z+Math.sin(a)*r,t,range(.8,1.35));}});
// Decorative tiny ground flowers and mushrooms.
for(let i=0;i<100;i++){let x=range(-29,29),z=range(-28,28);if(x*x+z*z>800)continue;let f=ball(i%3?'#d6d88d':'#fff7d7',x,.24,z,.12);f.scale.y=.5;}
for(let i=0;i<9;i++){let x=-21+range(-2,3),z=-9+range(-2,3);cyl('#eee3c0',x,.35,z,.1,.7);ball('#ca8c65',x,.72,z,.4).scale.y=.5;}
function makeBee(s=1){const g=new THREE.Group();let body=ball('#f3bf42',0,0,0,.6,g);body.scale.set(.82,.8,1.25);for(let z of [-.3,.15,.47]){let stripe=cyl('#534638',0,0,z,.485,.17,g);stripe.rotation.x=Math.PI/2;stripe.scale.x=.99;}ball('#f5cc58',0,.05,-.67,.42,g);for(let x of [-.2,.2]){ball('#403f33',x,.17,-.98,.085,g);const antenna=cyl('#534638',x,.52,-.73,.018,.38,g);antenna.rotation.z=-x;ball('#534638',x*1.2,.71,-.73,.05,g)}const wings=[];for(let side of [-1,1]){let w=new THREE.Mesh(new THREE.SphereGeometry(.54,12,8),new THREE.MeshStandardMaterial({color:'#f3fcf4',transparent:true,opacity:.74,roughness:.2}));w.scale.set(1,.07,.52);w.position.set(side*.53,.38,.03);g.add(w);wings.push(w)}g.scale.setScalar(s);g.userData.wings=wings;return g;}
const bee=makeBee();bee.position.set(-5,3.2,6);scene.add(bee);const beeShadow=new THREE.Mesh(new THREE.CircleGeometry(.65,24),new THREE.MeshBasicMaterial({color:'#536839',transparent:true,opacity:.17,depthWrite:false}));beeShadow.rotation.x=-Math.PI/2;beeShadow.position.y=.17;scene.add(beeShadow);
const friends=[];for(let i=0;i<7;i++){let b=makeBee(.45);scene.add(b);friends.push(b)}
const butterflies=[];for(let i=0;i<9;i++){let g=new THREE.Group();let ws=[];for(let side of [-1,1]){let w=ball(i%2?'#e9bd82':'#c2a6d1',side*.2,0,0,.3,g);w.scale.set(1,.15,1.4);ws.push(w)}scene.add(g);butterflies.push({g,ws,x:range(-23,23),z:range(-22,22)})}
const selection=new THREE.Mesh(new THREE.TorusGeometry(.85,.035,8,40),new THREE.MeshBasicMaterial({color:'#fff7c1',transparent:true,opacity:.9}));selection.rotation.x=-Math.PI/2;scene.add(selection);
const particles=[];function sparkle(pos,color='#ffe898',n=12){for(let i=0;i<n;i++){let p=ball(color,pos.x,pos.y,pos.z,.06);particles.push({p,v:new THREE.Vector3(range(-1,1),range(.8,2),range(-1,1)),life:1});}}
const SAVE='honey-meadow-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(SAVE)||'{}')}catch{};
const state={honey:0,total:0,visits:0,delivered:0,bag:0,energy:100,capacity:30,speedLevel:0,bagLevel:0,types:[],claimed:[],time:0,...saved};state.bag=Math.min(state.capacity,state.bag);const keys={};let paused=false,nearest=null,atHome=false,collectTime=0,toastTimer=0,sound=false,audio=null,wind='sun',lastSave=0;const clock=new THREE.Clock();
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state))}catch{}}function toast(t){$('#toast').textContent=t;$('#toast').style.opacity=1;toastTimer=4;}
function note(freq=660){if(!sound)return;audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.5,audio.currentTime+.12);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.25)}
const missions=[{title:'第一份花园礼物',desc:'采集 5 朵花 · 奖励 10g',goal:5,value:()=>state.visits,reward:10},{title:'甜蜜满载而归',desc:'带回 30 花蜜 · 奖励 20g',goal:30,value:()=>state.delivered,reward:20},{title:'花香收藏家',desc:'发现 4 种花 · 奖励 30g',goal:4,value:()=>state.types.length,reward:30}];
function updateUI(){for(let i=0;i<missions.length;i++){let q=missions[i];if(q.value()>=q.goal&&!state.claimed.includes(i)){state.claimed.push(i);state.honey+=q.reward;toast('手记完成：'+q.title+' · +'+q.reward+'g 蜂蜜');note(880);save();}}$('#honey').innerHTML=state.honey+' <em>g</em>';$('#count').innerHTML=state.visits+' <em>朵</em>';$('#bag-text').textContent=state.bag+' / '+state.capacity;$('#bag-bar').style.width=state.bag/state.capacity*100+'%';$('#energy-bar').style.width=state.energy+'%';$('#level').textContent='Lv. '+(1+Math.floor(state.total/75));$('#quests').innerHTML=missions.map((q,i)=>`<div class="quest ${state.claimed.includes(i)?'done':''}"><div class="quest-line"><span class="quest-circle">${state.claimed.includes(i)?'✓':''}</span>${q.title}</div><small>${q.desc} · ${Math.min(q.value(),q.goal)}/${q.goal}</small><div class="quest-track"><i style="width:${Math.min(q.value()/q.goal,1)*100}%"></i></div></div>`).join('');}
function action(){if(paused)return;if(atHome){if(state.bag){const n=state.bag;state.honey+=n;state.total+=n;state.delivered+=n;state.bag=0;state.energy=100;sparkle(bee.position,'#ffcf4b',28);toast('甜蜜入库！酿成 '+n+'g 蜂蜜，能量已恢复');note(540);updateUI();save();}else{state.energy=100;toast('蜂巢让你恢复了能量。去花园看看吧！');}return;}if(nearest){if(state.bag>=state.capacity){toast('蜜囊满啦！回到金色蜂巢，按 E 酿蜜');return;}const f=nearest,sp=species[f.type],n=Math.min(sp.value+(wind==='sun'?1:0),state.capacity-state.bag);state.bag+=n;state.visits++;if(!state.types.includes(f.type))state.types.push(f.type);f.ready=state.time+24;f.head.scale.setScalar(.55);sparkle(new THREE.Vector3(f.x,f.h+.3,f.z),sp.color,16);toast(sp.name+' · +'+n+' 花蜜'+(state.bag===state.capacity?' · 蜜囊已满，回家酿蜜吧！':''));note(550+f.type*100);nearest=null;updateUI();save();}}
function show(content){paused=true;$('#modal-body').innerHTML=content;$('#modal').classList.remove('hidden');keys.e=false;}function close(){paused=false;$('#modal').classList.add('hidden');$('#pause').textContent='Ⅱ';}
function shop(){show(`<div class="eyebrow">THE HIVE WORKSHOP</div><h2>为下一次远行</h2><p>用辛勤酿造的蜂蜜，换一点小小的进步。<br>现有蜂蜜 <strong>${state.honey}g</strong> · 升级会自动保存</p><button class="upgrade" id="buy-bag" ${state.honey<(25+state.bagLevel*25)||state.bagLevel>=5?'disabled':''}><span><strong>⬡ 扩大蜜囊 · Lv.${state.bagLevel}</strong><small>${state.bagLevel>=5?'已满级':'容量 '+state.capacity+' → '+(state.capacity+15)}</small></span><b>${state.bagLevel>=5?'MAX':25+state.bagLevel*25+'g'}</b></button><button class="upgrade" id="buy-speed" ${state.honey<(35+state.speedLevel*30)||state.speedLevel>=4?'disabled':''}><span><strong>ϟ 轻盈翅膀 · Lv.${state.speedLevel}</strong><small>${state.speedLevel>=4?'已满级':'飞行速度 +15%，冲刺更省力'}</small></span><b>${state.speedLevel>=4?'MAX':35+state.speedLevel*30+'g'}</b></button><p>小提示：晴天花朵会多产 1 点花蜜，花朵采集后会重新绽放。</p>`);$('#buy-bag').onclick=()=>{let cost=25+state.bagLevel*25;if(state.honey<cost||state.bagLevel>=5)return;state.honey-=cost;state.bagLevel++;state.capacity+=15;save();updateUI();shop();note()};$('#buy-speed').onclick=()=>{let cost=35+state.speedLevel*30;if(state.honey<cost||state.speedLevel>=4)return;state.honey-=cost;state.speedLevel++;save();updateUI();shop();note()};}
function help(){show('<div class="eyebrow">WELCOME TO HONEY MEADOW</div><h2>你好呀，小小采蜜家。</h2><p>花园不催你。自由飞行，靠近花朵，收集四种花香，再回蜂巢把花蜜酿成蜂蜜。</p><div class="help-grid"><kbd>W A S D / ↑ ↓ ← →</kbd> 在花园中飞行<br><kbd>E</kbd> 靠近花朵采蜜 / 在蜂巢酿蜜<br><kbd>Shift</kbd> 消耗能量，加速飞行<br><kbd>Space</kbd> 升高，松开自动降低<br><kbd>H</kbd> 显示回家方向　<kbd>Esc</kbd> 暂停<br><kbd>滚轮</kbd> 缩放视野</div><p>花朵约 24 秒后再次开放。完成手记获得额外蜂蜜。晴雨天气自动交替，升级与采集进度自动保存在此浏览器。</p><button class="primary" id="begin">出发，去寻一点甜 →</button>');$('#begin').onclick=close;}
$('#shop').onclick=shop;$('#help').onclick=help;$('#close').onclick=close;$('#pause').onclick=()=>paused?close():show('<div class="eyebrow">TAKE A LITTLE BREAK</div><h2>花园，等你回来。</h2><p>游戏已暂停，进度已自动保存。</p><button class="primary" id="resume">继续飞行 →</button>');$('#modal').addEventListener('click',e=>{if(e.target.id==='resume')close()});$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'♫':'♩';toast(sound?'花园音效已开启':'花园音效已关闭');note()};
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(k==='e'&&!e.repeat)action();if(k==='escape'){if(paused)close();else{$('#pause').click();save()}}if(k==='h'&&!paused){toast('蜂巢在你的'+(home.x<bee.position.x?'西':'东')+'侧 · 跟随地面的金色指引');guideTime=8;}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);save()});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;}$('#mobile-action').onclick=action;
let zoom=1;window.addEventListener('wheel',e=>{zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.0005,.65,1.45)},{passive:true});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const guide=new THREE.ArrowHelper(new THREE.Vector3(0,0,1),new THREE.Vector3(),4,0xf6d477,.7,.5);scene.add(guide);let guideTime=0;
const rainGeo=new THREE.BufferGeometry(),rainPos=new Float32Array(600*3);for(let i=0;i<600;i++){rainPos[i*3]=range(-33,33);rainPos[i*3+1]=range(0,28);rainPos[i*3+2]=range(-33,33)}rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:'#d4e9e6',size:.10,transparent:true,opacity:.7}));scene.add(rain);rain.visible=false;
const map=$('#minimap').getContext('2d');function drawMap(){map.clearRect(0,0,220,170);map.fillStyle='#dde6cd';map.beginPath();map.ellipse(110,85,100,76,0,0,TAU);map.fill();const xy=(x,z)=>[110+x*2.9,85+z*2.15];map.fillStyle='#9bc7bd';map.beginPath();map.ellipse(...xy(15,-8),16,8,0,0,TAU);map.fill();for(const f of flowers){map.fillStyle=f.ready>state.time?'#c2c9ae':['#e4d294','#d8a3a9','#ab96c8','#d8b650'][f.type];map.beginPath();map.arc(...xy(f.x,f.z),1.8,0,TAU);map.fill()}map.fillStyle='#c5932e';let h=xy(home.x,home.z);map.fillRect(h[0]-4,h[1]-4,8,8);let p=xy(bee.position.x,bee.position.z);map.strokeStyle='#fff9d9';map.lineWidth=3;map.fillStyle='#456c47';map.beginPath();map.arc(...p,4,0,TAU);map.fill();map.stroke();}
const target=new THREE.Vector3(),camOffset=new THREE.Vector3(25,31,37);let uiTick=0;updateUI();toast('欢迎来到蜜野 · WASD 飞行，靠近花朵按 E 采蜜');
function frame(){requestAnimationFrame(frame);let dt=Math.min(clock.getDelta(),.05);if(!paused){state.time+=dt;const t=state.time;let ax=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),az=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const moving=ax||az;const sprint=keys.shift&&state.energy>1&&moving;const speed=5.3*(1+state.speedLevel*.15)*(sprint?1.85:1)*(wind==='rain'?.9:1);if(moving){let dir=new THREE.Vector3(ax*.829+az*.559,0,az*.829-ax*.559).normalize();bee.position.addScaledVector(dir,dt*speed);const angle=Math.atan2(-dir.x,-dir.z);bee.rotation.y+=Math.atan2(Math.sin(angle-bee.rotation.y),Math.cos(angle-bee.rotation.y))*Math.min(dt*9,1);bee.rotation.z=Math.sin(t*9)*.055;state.energy=THREE.MathUtils.clamp(state.energy+dt*(sprint?-15+state.speedLevel*1.5:6),0,100);}else state.energy=Math.min(100,state.energy+dt*10);if(bee.position.length()>31){const planar=new THREE.Vector2(bee.position.x,bee.position.z);if(planar.length()>30)planar.setLength(30);bee.position.x=planar.x;bee.position.z=planar.y;}
let altitude=keys[' ']?6:3.1;bee.position.y=THREE.MathUtils.lerp(bee.position.y,altitude+Math.sin(t*4)*.12,dt*3);bee.userData.wings.forEach((w,i)=>w.rotation.z=Math.sin(t*70)*(i?1:-1)*.5);beeShadow.position.x=bee.position.x;beeShadow.position.z=bee.position.z;nearest=null;let dist=2.3;for(const f of flowers){f.head.rotation.z=Math.sin(t*1.4+f.phase)*.07;const ready=f.ready<=t;f.head.scale.lerp(new THREE.Vector3(ready?1:.55,ready?1:.55,ready?1:.55),dt*3);let d=Math.hypot(bee.position.x-f.x,bee.position.z-f.z);if(ready&&d<dist&&bee.position.y<4.2){nearest=f;dist=d}}selection.visible=!!nearest&&!atHome;if(nearest)selection.position.set(nearest.x,nearest.h+.28,nearest.z);atHome=Math.hypot(bee.position.x-home.x,bee.position.z-home.z)<3.3;const prompt=$('#prompt');prompt.style.display=atHome||nearest||state.bag>=state.capacity?'block':'none';prompt.innerHTML=atHome?'<kbd>E</kbd> '+(state.bag?'回巢酿蜜 · '+state.bag+'g':'温暖的家 · 恢复能量'):state.bag>=state.capacity?'蜜囊满啦 · 按 <kbd>H</kbd> 寻找蜂巢':nearest?'<kbd>E</kbd> 采集'+species[nearest.type].name+' <span style="color:#aa984a">✧</span>':'';
if(keys.e){collectTime+=dt;if(collectTime>.45){action();collectTime=0}}else collectTime=0;
for(let i=0;i<friends.length;i++){const b=friends[i],a=t*.17+i*1.8;b.position.set(Math.sin(a)*11,2.6+Math.sin(t+i)*.5,Math.cos(a*.8)*12);b.rotation.y=-a;b.userData.wings.forEach((w,j)=>w.rotation.z=Math.sin(t*65+i)*(j?1:-1)*.5)}for(let i=0;i<butterflies.length;i++){let b=butterflies[i];b.g.position.set(b.x+Math.sin(t*.5+i)*2,2+Math.sin(t+i)*.6,b.z+Math.cos(t*.4+i)*2);b.ws.forEach((w,j)=>w.rotation.z=Math.sin(t*10)*(j?1:-1)*.8)}
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.p.position.addScaledVector(p.v,dt);p.p.scale.setScalar(Math.max(0,p.life));if(p.life<=0){scene.remove(p.p);p.p.geometry.dispose();particles.splice(i,1)}}
const newWind=Math.floor(t/90)%3===2?'rain':'sun';if(newWind!==wind){wind=newWind;rain.visible=wind==='rain';toast(wind==='rain'?'一场温柔的小雨 · 飞行速度略微降低':'雨过天晴 · 花蜜产量 +1');}if(rain.visible){for(let i=0;i<600;i++){rainPos[i*3+1]-=dt*12;if(rainPos[i*3+1]<0)rainPos[i*3+1]=28}rainGeo.attributes.position.needsUpdate=true;}sun.intensity=THREE.MathUtils.lerp(sun.intensity,wind==='rain'?1.5:3,dt);$('#weather-icon').textContent=wind==='rain'?'☂':'☀';$('#weather').innerHTML=wind==='rain'?'小雨 <em>慢慢飞就好</em>':'晴朗 <em>采蜜好时光</em>';$('#day').textContent='第 '+(1+Math.floor(t/270))+' 天 · '+(['上午','午后','傍晚'][Math.floor(t/90)%3]);
guideTime=Math.max(0,guideTime-dt);guide.visible=guideTime>0||state.bag>=state.capacity;if(guide.visible){let d=home.clone().sub(bee.position);d.y=0;guide.position.copy(bee.position).add(new THREE.Vector3(0,-1,0));guide.setDirection(d.normalize());}toastTimer-=dt;if(toastTimer<=0)$('#toast').style.opacity=0;uiTick+=dt;if(uiTick>.15){updateUI();drawMap();uiTick=0}if(t-lastSave>10){save();lastSave=t;}}
target.set(bee.position.x*.45,0,bee.position.z*.45-1);camera.position.lerp(target.clone().addScaledVector(camOffset,zoom),1-Math.exp(-dt*2.5));camera.lookAt(target);renderer.render(scene,camera);}
camera.position.copy(camOffset);frame();
// Deterministic read-only snapshot for smoke tests and diagnostics.
window.__meadow={snapshot:()=>({honey:state.honey,bag:state.bag,capacity:state.capacity,visits:state.visits,paused,flowers:flowers.length,position:bee.position.toArray(),atHome,near:nearest?.type,weather:wind,availableFlowers:flowers.filter(f=>f.ready<=state.time).map(f=>({x:f.x,z:f.z,type:f.type}))})};
