const fold=(name,stations,color)=>({name,stations,color});
const node=(id,x,z,extra={})=>({id,x,z,...extra});
const edge=(a,b,when={},extra={})=>({a,b,when,...extra});
export const levels=[
 {title:'初见 · 纸之彼岸',subtitle:'有些距离，只需要轻轻一折。',realm:'晨光群岛',description:'收集两颗星光，折起晨光折痕，抵达光之门。',start:'S',goal:'T',initial:[0],folds:[fold('晨光折痕',['A'],0xd1a492)],nodes:[node('S',-5.5,2.6),node('A',-2.3,1.1,{label:'Ⅰ 折叠台',size:2.1}),node('U',-3.1,-2.3,{star:true}),node('D',1.3,1.1,{star:true}),node('T',4.3,-1.6,{size:2.1})],edges:[edge('S','A'),edge('A','U'),edge('A','D',{0:1}),edge('D','T')],intro:'你好，小纸灵。点击前方的纸岛，开始这段旅程。'},
 {title:'回声 · 星在另一面',subtitle:'折起这一岸，才会看见那一岸。',realm:'回声花园',description:'两翼道路无法同时展开。回到中央折叠台，找齐两颗星光。',start:'S',goal:'T',initial:[1],folds:[fold('双翼折痕',['C'],0xc48f97)],nodes:[node('S',-5.5,2.4),node('C',-2,0,{label:'Ⅰ 折叠台',size:2.3}),node('U',-2.5,-3.8,{star:true}),node('V',1.5,1,{star:true}),node('T',4.8,-1.4,{size:2})],edges:[edge('S','C'),edge('C','U',{0:0}),edge('C','V',{0:1}),edge('V','T')],intro:'两片纸翼，一道折痕。记得去看看另一面。'},
 {title:'秘钥 · 风中的信',subtitle:'星光藏在归途，钥匙藏在远方。',realm:'风信庭院',description:'找到金色钥匙，收集两颗星光，再重新连接通往光门的路。',start:'S',goal:'T',initial:[1,0],folds:[fold('风信折痕',['C'],0x92aea6),fold('暮色折痕',['D'],0xcb969a)],nodes:[node('S',-6,2.8),node('C',-3,.5,{label:'Ⅰ 折叠台',size:2}),node('K',-3.5,-3.2,{star:true,key:true}),node('D',.8,.6,{label:'Ⅱ 折叠台',size:2}),node('U',1.1,-3.4,{star:true}),node('T',4.7,.2,{size:2})],edges:[edge('S','C'),edge('C','K',{0:0}),edge('C','D',{0:1}),edge('D','U',{1:1}),edge('D','T',{1:0},{key:true})],intro:'有的门，要带着星光和钥匙才能穿过。'},
 {title:'留白 · 留路给明天',subtitle:'出发之前，替未来的自己折一条路。',realm:'留白之庭',description:'先在起点准备远处的纸桥，再到远岸切换旧路与新路。',start:'S',goal:'T',initial:[0,0],folds:[fold('归途折痕',['P'],0x92aea6),fold('远方折痕',['S','D'],0xcb969a)],nodes:[node('S',-5.3,2.4,{label:'Ⅱ 折叠台',size:2}),node('C',-5.3,-1.4,{star:true}),node('P',-1.7,-3.6,{star:true,label:'Ⅰ 折叠台',size:2}),node('D',.8,.2,{label:'Ⅱ 折叠台',size:2.2}),node('T',4.6,-2,{size:2})],edges:[edge('S','C',{0:0}),edge('C','P'),edge('S','D',{0:1}),edge('P','D',{0:1,1:1}),edge('D','T',{1:0})],intro:'不是每座折叠台都在手边。有些准备，要在出发前做好。'},
 {title:'双翼 · 星光邮局',subtitle:'把所有远行，折成一封回家的信。',realm:'双翼邮局',description:'唤醒纸扣、找到钥匙。协调两道折痕，让去路变成归途。',start:'S',goal:'T',initial:[0,0],folds:[fold('青叶折痕',['A','E'],0x92aea6),fold('花信折痕',['B','E'],0xcb969a)],nodes:[node('S',-6,3.1),node('A',-3.8,1,{label:'Ⅰ 折叠台'}),node('B',-4.7,-2,{label:'Ⅱ 折叠台'}),node('P',-2.5,-4.3,{star:true,switch:true}),node('D',-.2,1.7,{star:true}),node('E',2.4,-1,{label:'Ⅰ Ⅱ 折叠台',size:2}),node('K',1.1,-4.5,{star:true,key:true}),node('T',4,3,{size:2})],edges:[edge('S','A'),edge('A','B',{0:0}),edge('B','P',{1:0}),edge('A','D',{0:1},{switch:true}),edge('D','E',{0:1,1:1}),edge('D','E',{0:0,1:0},{key:true,offset:.4}),edge('E','K',{0:0}),edge('D','T',{0:0,1:0},{key:true})],intro:'踩上青色纸扣，就能永远松开远方的束缚。'},
 {title:'归家 · 把光折进梦里',subtitle:'原来每一道折痕，都曾替你记住方向。',realm:'星归之屿',description:'收齐四颗星光，解开三重折痕，把最后一束光带回家。',start:'S',goal:'T',initial:[0,0,0],folds:[fold('青叶折痕',['A','E'],0x92aea6),fold('花信折痕',['B','E'],0xcb969a),fold('星河折痕',['K'],0xb2a3ce)],nodes:[node('S',-6,3.8),node('A',-4.5,1,{label:'Ⅰ 折叠台'}),node('B',-5.2,-2.2,{label:'Ⅱ 折叠台'}),node('C',-3.1,-4.5,{star:true,switch:true}),node('D',-.6,2.1,{star:true}),node('E',1,-1.2,{label:'Ⅰ Ⅱ 折叠台',size:2}),node('K',1.2,-4.5,{star:true,key:true,label:'Ⅲ 折叠台'}),node('P',4.4,-2.5,{star:true}),node('T',3.7,3.5,{size:2})],edges:[edge('S','A'),edge('A','B',{0:0}),edge('B','C',{1:0}),edge('A','D',{0:1},{switch:true}),edge('D','E',{0:1,1:1}),edge('D','E',{0:0,1:0},{key:true,offset:.4}),edge('E','K',{0:0,2:0}),edge('K','P',{2:1}),edge('P','E',{1:0}),edge('D','T',{0:0,1:0,2:1},{key:true})],intro:'三道折痕，一封星光的信。小纸灵，家就在那束光里。'}
];
export function initialState(level){return collect(level,{at:level.start,folds:[...level.initial],stars:[],key:false,switch:false,moves:0,foldCount:0})}
export function collect(level,state){const n=level.nodes.find(n=>n.id===state.at);return{...state,stars:n.star&&!state.stars.includes(n.id)?[...state.stars,n.id]:[...state.stars],key:state.key||!!n.key,switch:state.switch||!!n.switch}}
export function edgeOpen(edge,state){return Object.entries(edge.when).every(([i,v])=>state.folds[Number(i)]===v)&&(!edge.key||state.key)&&(!edge.switch||state.switch)}
export function neighbors(level,state,id=state.at){return [...new Set(level.edges.filter(e=>edgeOpen(e,state)&&(e.a===id||e.b===id)).map(e=>e.a===id?e.b:e.a))]}
export function complete(level,state){return state.at===level.goal&&state.stars.length===level.nodes.filter(n=>n.star).length}
export function moveState(level,state,id){if(!neighbors(level,state).includes(id))throw new Error('这条道路还未连通。');return collect(level,{...state,at:id,moves:state.moves+1})}
export function foldState(level,state,id){if(!level.folds[id]||!level.folds[id].stations.includes(state.at))throw new Error('需要先走到对应的折叠台。');const folds=[...state.folds];folds[id]=1-folds[id];return{...state,folds,stars:[...state.stars],foldCount:state.foldCount+1}}
export function pathTo(level,state,dest){const q=[[state.at]],seen=new Set([state.at]);for(let i=0;i<q.length;i++){const p=q[i];if(p.at(-1)===dest)return p;for(const n of neighbors(level,state,p.at(-1)))if(!seen.has(n)){seen.add(n);q.push([...p,n])}}return null}
function stateKey(s){return [s.at,s.folds.join(''),[...s.stars].sort().join(''),+s.key,+s.switch].join('|')}
export function solve(level,state){const q=[{s:state,path:[]}],seen=new Set([stateKey(state)]);for(let j=0;j<q.length&&j<100000;j++){const{s,path}=q[j];if(complete(level,s))return path;const actions=[...neighbors(level,s).map(id=>({type:'move',id})),...level.folds.flatMap((f,id)=>f.stations.includes(s.at)?[{type:'fold',id}]:[])];for(const a of actions){const next=a.type==='move'?moveState(level,s,a.id):foldState(level,s,a.id);const key=stateKey(next);if(!seen.has(key)){seen.add(key);q.push({s:next,path:[...path,a]})}}}return null}
