const points = (values) => values.map(([x, z]) => ({ x, z }));
const pads = (values) => values.map(([x, z], i) => ({ id: "p" + i, x, z }));
export const TOWERS = {
  carrot: {
    id: "carrot",
    name: "胡萝卜弩台",
    description: "可靠的单体射手，擅长唤醒跑在最前面的团子。",
    color: "#ff9b5c",
    cost: 70,
    damage: 18,
    range: 4.7,
    interval: 0.72,
    branches: {
      a: { name: "流星长弓", description: "大幅增加伤害与射程，瞄准强敌。" },
      b: { name: "双叶快弩", description: "射速翻倍，用绵密的糖箭守住路口。" },
    },
  },
  berry: {
    id: "berry",
    name: "莓果投手",
    description: "投出软软的莓果糖，唤醒一整簇团子。",
    color: "#ed769b",
    cost: 110,
    damage: 24,
    range: 4.3,
    interval: 1.55,
    branches: {
      a: { name: "星莓派对", description: "更大的范围与更强的爆发。" },
      b: { name: "暖莓糖浆", description: "溅射留下持续唤醒的暖糖浆。" },
    },
  },
  frost: {
    id: "frost",
    name: "霜糖风铃",
    description: "清凉铃声降低团子速度，为伙伴争取时间。",
    color: "#87dceb",
    cost: 85,
    damage: 9,
    range: 4.5,
    interval: 1.05,
    branches: {
      a: { name: "深雪摇篮", description: "单体强力减速，持续更久。" },
      b: { name: "雪花合唱", description: "让一小群团子一起慢下来。" },
    },
  },
  spark: {
    id: "spark",
    name: "星火线圈",
    description: "魔法星火跳向附近团子，忽略护甲。",
    color: "#b8a0f5",
    cost: 145,
    damage: 17,
    range: 4.7,
    interval: 1.05,
    branches: {
      a: { name: "银河接力", description: "星火最多连锁六个目标。" },
      b: { name: "晴空闪光", description: "提高首击威力，并让目标短暂停步。" },
    },
  },
  honey: {
    id: "honey",
    name: "蜂蜜小屋",
    description: "黏黏蜂蜜持续唤醒团子，优先照顾未沾蜜的目标。",
    color: "#efbd5c",
    cost: 100,
    damage: 5,
    range: 4.2,
    interval: 0.9,
    branches: {
      a: { name: "蜜花飞沫", description: "蜂蜜飞溅，持续效果覆盖附近目标。" },
      b: { name: "黏糖抱抱", description: "加强持续效果并附带减速。" },
    },
  },
  bloom: {
    id: "bloom",
    name: "花灯花园",
    description: "每波结束产糖，并提升附近攻击塔射速；同类光环取最强。",
    color: "#9dcc8a",
    cost: 90,
    damage: 0,
    range: 4.8,
    interval: 1,
    branches: {
      a: { name: "丰糖温室", description: "每波结算产出 32 颗糖果。" },
      b: { name: "星光花环", description: "强化射速光环，并提升友塔射程。" },
    },
  },
};
export const HEROES = {
  momo: {
    id: "momo",
    name: "Momo · 兔邮差",
    description: "远程糖箭手，射程长、出手快，能够唤醒飞行团子。",
    color: "#ffd0db",
    damage: 11,
    range: 5,
    interval: 0.8,
    speed: 5.2,
  },
  pip: {
    id: "pip",
    name: "Pip · 狐灯匠",
    description: "投出星灯火花，范围唤醒聚在一起的团子。",
    color: "#ffbd85",
    damage: 14,
    range: 4.2,
    interval: 1.25,
    speed: 4.9,
  },
  bao: {
    id: "bao",
    name: "Bao · 熊猫茶师",
    description: "以热茶温暖近处的地面团子，并使它们放慢脚步。",
    color: "#d2e8bd",
    damage: 22,
    range: 2.7,
    interval: 1.05,
    speed: 4.6,
  },
};
export const ENEMIES = {
  puff: {
    id: "puff",
    name: "困困团子",
    description: "走得慢，爱打瞌睡的普通团子。",
    color: "#ddd2ed",
    health: 46,
    speed: 1.36,
    reward: 7,
    damage: 1,
  },
  hopper: {
    id: "hopper",
    name: "蹦蹦团子",
    description: "脚步轻快，需要远程火力和风铃照顾。",
    color: "#f1bfce",
    health: 34,
    speed: 2.35,
    reward: 8,
    damage: 1,
  },
  shell: {
    id: "shell",
    name: "软壳团子",
    description: "枕头护甲降低物理伤害，魔法与蜂蜜更有效。",
    color: "#a7c1d4",
    health: 125,
    speed: 1.05,
    reward: 13,
    damage: 2,
    armor: 0.45,
  },
  moth: {
    id: "moth",
    name: "云翼团子",
    description: "沿着道路轻轻飘行，Bao 的近战无法触及。",
    color: "#dcc7f1",
    health: 48,
    speed: 1.9,
    reward: 10,
    damage: 1,
    flying: true,
  },
  shaman: {
    id: "shaman",
    name: "摇铃团子",
    description: "每隔一会儿给附近伙伴补充梦力，优先唤醒它。",
    color: "#b7d9c0",
    health: 84,
    speed: 1.2,
    reward: 15,
    damage: 2,
  },
  splitter: {
    id: "splitter",
    name: "抱枕双子",
    description: "醒来时蹦出两只迷你团子，留心后续小伙伴。",
    color: "#e9c0ad",
    health: 104,
    speed: 1.3,
    reward: 14,
    damage: 2,
  },
  boss: {
    id: "boss",
    name: "迷雾团长",
    description: "大大的云团抱着借来的星光，抵抗部分减速。",
    color: "#c1b0e7",
    health: 610,
    speed: 0.92,
    reward: 70,
    damage: 5,
  },
};
export const SPELLS = {
  meteor: {
    id: "meteor",
    name: "星糖雨",
    description: "在选定区域落下星糖，对地面与飞行团子造成大量魔法伤害。",
    cost: 45,
    cooldown: 35,
    radius: 3.8,
    color: "#ffc86c",
  },
  frost: {
    id: "frost",
    name: "晚安结界",
    description: "布置持续 8 秒的清凉结界，使经过的团子放慢脚步。",
    cost: 35,
    cooldown: 40,
    radius: 4.1,
    color: "#97e6ef",
  },
  bell: {
    id: "bell",
    name: "团圆钟",
    description: "修复 4 点星灯生命，并让所有守卫在 9 秒内加快攻击。",
    cost: 50,
    cooldown: 55,
    radius: 30,
    color: "#ffe49b",
  },
};
export const DIFFICULTIES = {
  easy: {
    id: "easy",
    name: "暖心故事",
    description: "团子梦力较低，适合轻松欣赏故事。",
    health: 0.78,
    speed: 0.92,
  },
  normal: {
    id: "normal",
    name: "星灯守卫",
    description: "平衡的策略挑战。",
    health: 1,
    speed: 1,
  },
  hard: {
    id: "hard",
    name: "勇气之夜",
    description: "更结实、更迅速的梦游队伍。",
    health: 1.25,
    speed: 1.08,
  },
};
export const LEVELS = [
  {
    id: "meadow",
    index: 0,
    name: "糖果草甸",
    subtitle: "第一章 · 未送达的邀请",
    description: "在开阔的糖果草甸点亮第一盏星灯，学会搭配输出与减速。",
    waves: 6,
    palette: {
      ground: "#b9dba0",
      grass: "#9dc982",
      path: "#f4d8a5",
      water: "#99d7de",
      sky: "#f4e4cc",
      fog: "#eddccf",
      accent: "#f3bcb4",
      tree: "#afd093",
    },
    paths: [
      points([
        [-13, -5],
        [-8, -5],
        [-8, 4],
        [-1, 4],
        [-1, -4],
        [6, -4],
        [6, 5],
        [13, 5],
      ]),
    ],
    pads: pads([
      [-11, -2],
      [-11, 3],
      [-5, -3],
      [-5, 1],
      [-5, 7],
      [2, 1],
      [2, -7],
      [5, -7],
      [9, -3],
      [9, 1],
      [9, 8],
      [4, 8],
      [-1, 7],
      [-11, -8],
    ]),
    core: { x: 13, z: 5 },
    intro: [
      "星灯节前夜，兔邮差 Momo 发现，最后一封邀请函上的星星正在慢慢熄灭。",
      "草甸那头，裹着薄雾的团子们闭着眼睛走来；她架起糖果哨塔，决定先把大家叫醒。",
    ],
    outro:
      "醒来的团子递给 Momo 一枚湿漉漉的云朵纽扣，纽扣里传来很轻的一声「回家」。",
  },
  {
    id: "brook",
    index: 1,
    name: "萤光溪谷",
    subtitle: "第二章 · 空白的收件人",
    description: "溪水与萤灯照着回转的桥路，留心飞行团子和摇铃伙伴。",
    waves: 7,
    palette: {
      ground: "#a3d5bb",
      grass: "#7fbea4",
      path: "#e9d6ba",
      water: "#83cddd",
      sky: "#d6e8ec",
      fog: "#cce0e0",
      accent: "#edcca3",
      tree: "#86bfa5",
    },
    paths: [
      points([
        [-13, 5],
        [-8, 5],
        [-8, -4],
        [-2, -4],
        [-2, 5],
        [5, 5],
        [5, -5],
        [13, -5],
      ]),
    ],
    pads: pads([
      [-11, 1],
      [-11, -4],
      [-5, 1],
      [-5, -7],
      [-1, -7],
      [1, 0],
      [1, 8],
      [5, 8],
      [8, 2],
      [8, -2],
      [10, -8],
      [3, -8],
      [-11, 8],
      [-4, 8],
    ]),
    core: { x: 13, z: -5 },
    intro: [
      "狐狸 Pip 在溪边修灯，听见云朵纽扣响起了与水流相同的节拍。",
      "他们循着节拍向上游寻找，却发现一整队梦游团子正把萤火虫的光送进浓雾。",
    ],
    outro:
      "Pip 点亮桥头的萤灯，雾里短暂显出一张邀请函的轮廓——收件人那一栏是空的。",
  },
  {
    id: "grove",
    index: 2,
    name: "蘑菇月林",
    subtitle: "第三章 · 云上的窗",
    description: "蘑菇灯围绕漫长的林间路，范围塔可以照顾抱枕双子。",
    waves: 8,
    palette: {
      ground: "#b9c6c3",
      grass: "#93b6a8",
      path: "#decfb9",
      water: "#9ebdc9",
      sky: "#d9d7ec",
      fog: "#d0ccd9",
      accent: "#cba4db",
      tree: "#9cc9b3",
    },
    paths: [
      points([
        [-13, -7],
        [-7, -7],
        [-7, 5],
        [0, 5],
        [0, -5],
        [7, -5],
        [7, 6],
        [13, 6],
      ]),
    ],
    pads: pads([
      [-10, -3],
      [-10, 3],
      [-9, 8],
      [-4, -4],
      [-4, 1],
      [-4, 8],
      [3, 1],
      [3, -8],
      [7, -8],
      [10, -2],
      [10, 2],
      [10, 9],
      [5, 9],
      [3, 5],
      [-4, -8],
    ]),
    core: { x: 13, z: 6 },
    intro: [
      "熊猫 Bao 守着月林的小茶屋，每晚都为一位没来过的客人留一盏灯。",
      "今夜蘑菇的影子连成了路，团子们带着遗落的星光走向林心，像是在替谁筹备一场只有自己的节日。",
    ],
    outro:
      "三位伙伴在树洞里找到一张画：高高的云上有一扇窗，窗下的小云团独自看着地面的星灯。",
  },
  {
    id: "frost",
    index: 3,
    name: "霜铃雪坡",
    subtitle: "第四章 · 回家的风铃",
    description: "两支梦游队伍从雪坡汇入，守住合流路口并重新摇响风铃。",
    waves: 9,
    palette: {
      ground: "#e6e8f1",
      grass: "#cddae5",
      path: "#c7bfd9",
      water: "#99bfd8",
      sky: "#e3dfee",
      fog: "#d8d6e4",
      accent: "#b7c7e9",
      tree: "#b4ccda",
    },
    paths: [
      points([
        [-13, -7],
        [-8, -7],
        [-8, -2],
        [-2, -2],
        [-2, 2],
        [5, 2],
        [5, -4],
        [13, -4],
      ]),
      points([
        [-13, 7],
        [-8, 7],
        [-8, 2],
        [-2, 2],
        [5, 2],
        [5, -4],
        [13, -4],
      ]),
    ],
    pads: pads([
      [-11, -4],
      [-11, 4],
      [-5, -5],
      [-5, 0],
      [-5, 5],
      [-2, -5],
      [1, -1],
      [1, 5],
      [5, 5],
      [8, 0],
      [8, -7],
      [11, -1],
      [-8, -10],
      [-8, 10],
      [3, -7],
    ]),
    core: { x: 13, z: -4 },
    intro: [
      "雪坡上的旧风铃记得云层之间的归途，可结冰的星灯已经照不到那么高。",
      "Momo 把空白邀请函揣进怀里，Pip 修好引光装置，Bao 把热茶分给同伴；他们要先守住最后一段上山的路。",
    ],
    outro: "风铃重新响起，雾中的大云团终于开口：「我只是想让家里，也亮一次。」",
  },
  {
    id: "starlight",
    index: 4,
    name: "星灯广场",
    subtitle: "第五章 · 给每一个想回家的人",
    description: "两条彩灯长廊通向广场，为最后一封邀请和云上的窗守住光芒。",
    waves: 10,
    palette: {
      ground: "#cdc9df",
      grass: "#b7bfd6",
      path: "#f1d2bd",
      water: "#a1b5d2",
      sky: "#d4cbe2",
      fog: "#cdc6dc",
      accent: "#e4b3ce",
      tree: "#b8c5ce",
    },
    paths: [
      points([
        [-13, -7],
        [-7, -7],
        [-7, -1],
        [0, -1],
        [0, 5],
        [7, 5],
        [7, 0],
        [13, 0],
      ]),
      points([
        [-13, 7],
        [-10, 7],
        [-10, 1],
        [-3, 1],
        [-3, -5],
        [7, -5],
        [7, 0],
        [13, 0],
      ]),
    ],
    pads: pads([
      [-10, -4],
      [-4, -8],
      [-5, -3],
      [-6, 4],
      [-13, 3],
      [-7, 8],
      [0, 8],
      [3, 2],
      [3, -2],
      [3, -8],
      [7, -8],
      [10, -3],
      [10, 3],
      [7, 8],
      [-1, -8],
      [-13, -1],
    ]),
    core: { x: 13, z: 0 },
    intro: [
      "迷雾团长把借来的星光围在身边，却怎么也拼不出通往云上那扇窗的路。",
      "三位伙伴将邀请函写上「给每一个想回家的人」，在广场架起最后的守卫，让躁动的梦游团子安静下来，为星灯争取修复的时间。",
    ],
    outro:
      "当最后一颗星糖落进灯芯，广场与云上的窗同时亮了；迷雾散开，原来团长只是一个抱着枕头的小云团。",
  },
];
export const ENDING = [
  "星灯没有留下被借走的光，而是把一条温暖的光路送向云端。",
  "小云团回到窗边，又带着一篮云朵棉花糖赶来参加星灯节——这一次，邀请函上写着它的名字。",
  "Momo 收好邮包，Pip 擦亮灯罩，Bao 添上新茶；从此每一盏星灯，都为晚归的朋友多亮一会儿。",
];
