import {PostalGame,ROUTES,SHIFTS} from './core.mjs';
const $=id=>document.getElementById(id);let scene=null;let mode='shift';let soundEnabled=false;let audio=null;let last=performance.now();let feedbackTimer=0;let best={shift:0,endless:0,zen:0};let pausedByHelp=false;let lastWon=false;
try{best={...best,...JSON.parse(localStorage.getItem('parcel-shift-best')||'{}')};soundEnabled=localStorage.getItem('parcel-shift-sound')==='true';}catch{}
const game=new PostalGame(event=>onGameEvent(event));
function sfx(kind){if(!soundEnabled)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const melody=kind==='correct'?[523,659,784]:kind==='error'?[196,146]:kind==='start'?[392,523,659,784]:kind==='scan'?[880,1320]:[440];melody.forEach((freq,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='error'?'triangle':'sine';o.frequency.value=freq;o.connect(g);g.connect(audio.destination);const t=audio.currentTime+i*.075;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.045,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.17);o.start(t);o.stop(t+.18);});}catch{}}
function setFeedback(text,type=''){clearTimeout(feedbackTimer);$('feedback').textContent=text;$('feedback').className='feedback '+type;}
function updateSound(){$('sound').querySelector('span').textContent=soundEnabled?'音效开':'音效关';$('sound').setAttribute('aria-label',soundEnabled?'关闭音效':'开启音效');$('sound').setAttribute('aria-pressed',String(soundEnabled));}
function startGame(){closeDialog();$('start-card').hidden=true;game.start(mode);sfx('start');}
function renderParcel(){const p=game.current;if(!p)return;$('parcel-count').textContent='NO. '+String(p.id).padStart(3,'0');const hidden=p.tags.includes('blurred')&&!p.scanned;$('address-district').textContent=hidden?'地址模糊':ROUTES[p.route].name;$('address-street').textContent=hidden?'标签受潮，请扫描恢复收件地址':p.address;$('recipient').textContent='收件人：'+p.name;$('weight').textContent=p.tags.includes('heavy')&&!p.scanned?'重量待核验':p.weight+' kg';$('postcode').textContent=hidden?'1•••••':p.postcode;$('tracking').textContent='PS 2026 '+String(p.id).padStart(3,'0')+' 07';$('mail-type').textContent=p.tags.includes('express')?'优先配送':p.tags.includes('return')?'退件待处理':'标准包裹';
 const tags=p.tags.map(t=>({fragile:p.wrapped?['done','✓ 已加固']:['fragile','◇ 易碎 · 先加固'],blurred:p.scanned?['done','✓ 地址已恢复']:['scan','⌗ 地址模糊'],heavy:p.scanned?['done','✓ 称重完成']:['scan','▣ 超重 · 先称重'],express:['express','ϟ 加急件'],return:['return','↶ 退回寄件人']}[t]));$('parcel-tags').innerHTML=(tags.length?tags:[['plain','普通件']]).map(([c,t])=>`<span class="tag ${c}">${t}</span>`).join('');$('wrap').classList.toggle('done',p.wrapped);$('scan').classList.toggle('done',p.scanned);$('wrap').setAttribute('aria-pressed',String(p.wrapped));$('scan').setAttribute('aria-pressed',String(p.scanned));document.querySelectorAll('.route').forEach(b=>b.classList.toggle('hint',p.id===1&&Number(b.dataset.route)===p.route));
}
function renderStats(){const snap=game.snapshot();$('score').textContent=String(game.score).padStart(5,'0');$('combo').innerHTML=game.combo+'<span> COMBO</span>';$('lives').textContent=game.mode==='zen'?'∞':'●'.repeat(Math.max(0,game.lives))+'○'.repeat(Math.max(0,5-game.lives));$('lives').setAttribute('aria-label',game.mode==='zen'?'练习模式，无限机会':'剩余 '+game.lives+' 次机会');$('best').textContent=best[game.mode]||0;$('shift-label').textContent=game.mode==='shift'?SHIFTS[game.shift].name+' · 0'+(game.shift+1)+' / 03':game.mode==='endless'?'无尽高峰 · 持续来件':'轻松练习 · 无时间限制';
 $('mission').textContent=game.mode==='shift'?'本班目标：正确分拣 '+SHIFTS[game.shift].target+' 件':game.mode==='endless'?'分拣越多，传送带越快':'练习目标：掌握路线与特殊处理';$('progress-text').textContent=game.mode==='shift'?game.correct+' / '+SHIFTS[game.shift].target:game.totalCorrect+' 件';$('progress-fill').style.width=game.mode==='shift'?Math.min(100,game.correct/SHIFTS[game.shift].target*100)+'%':'100%';const playing=game.status==='playing';const enabled=playing&&game.transition<=0;document.querySelectorAll('[data-route],#wrap,#scan,#return').forEach(b=>b.disabled=!enabled);$('pause').disabled=!['playing','paused'].includes(game.status);$('pause').textContent=game.status==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',game.status==='paused'?'继续游戏':'暂停游戏');$('belt-label').textContent=game.status==='ready'?'设备待命':game.status==='paused'?'传送带暂停':playing?'传送带运行中':'班次已结束';
}
function renderTimers(){const sec=Math.ceil(game.time);$('clock').textContent=game.mode==='shift'?String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0'):'∞';const p=game.current;if(p){$('parcel-time').textContent=game.mode==='zen'?'不限时':p.remaining.toFixed(1)+' s';$('time-fill').style.width=(game.mode==='zen'?100:100*p.remaining/p.limit)+'%';document.body.classList.toggle('urgent',game.mode!=='zen'&&p.remaining<3);}else{document.body.classList.remove('urgent');}}
function onGameEvent(e){switch(e.type){case'parcel':scene?.setParcel(e.parcel);renderParcel();$('shipping-label').classList.remove('flash');void $('shipping-label').offsetWidth;$('shipping-label').classList.add('flash');if(e.parcel.id<=6)setFeedback(({1:'第一件：读城区名，选择闪烁的对应路线。',2:'易碎件：先按 Q 加固，再按地址分拣。',3:'标签受潮：按 E 扫描，就能恢复完整地址。',4:'加急件时限更短，直接按地址分拣。',5:'退件优先：按 R 退回，无需选择城区。',6:'超重件：按 E 扫描称重，再按地址分拣。'})[e.parcel.id]);else setFeedback('先核对处理标签，再投递到正确路线。');break;
 case'start':scene?.setShift(game.shift);$('scene-subtitle').textContent=game.mode==='zen'?'慢慢来，每一件都会找到方向':'检查标签 · 特殊处理 · 按区投递';document.querySelector('.scene-caption>span').textContent=game.mode==='shift'?SHIFTS[game.shift].subtitle:game.mode==='endless'?'高峰不停歇':'悠闲分拣日';$('event-banner').hidden=true;break;
 case'handle':scene?.handle(e.action);renderParcel();sfx(e.action==='scan'?'scan':'tap');setFeedback(e.action==='wrap'?'包装已加固，可以按地址投递。':'核验完成，请核对城区与处理标签。','success');break;
 case'result':scene?.sendParcel(e.route,e.ok);setFeedback(e.message+(e.ok?' · +'+e.points:' · -30 分'),e.ok?'success':'error');sfx(e.ok?'correct':'error');const f=$('float-score');f.textContent=(e.points>0?'+':'')+e.points;f.className='float-score'+(e.ok?'':' bad');void f.offsetWidth;f.classList.add('animate');if(!e.ok){document.querySelector('.scene-panel').classList.remove('shake');void f.offsetWidth;document.querySelector('.scene-panel').classList.add('shake');}document.querySelectorAll('.route').forEach(b=>b.classList.remove('hint'));break;
 case'rush':$('event-banner').textContent='ϟ 突发来件潮 · 新包裹时限缩短 20%';$('event-banner').hidden=false;sfx('start');break;
 case'eventEnd':$('event-banner').hidden=true;break;
 case'shiftComplete':if(!e.final)setTimeout(()=>showShiftSummary(),500);break;
 case'finish':lastWon=e.won;if(game.score>(best[game.mode]||0)){best[game.mode]=game.score;try{localStorage.setItem('parcel-shift-best',JSON.stringify(best));}catch{}}$('event-banner').hidden=true;setTimeout(()=>showFinal(e.won),500);break;
 case'upgrade':sfx('scan');showShiftSummary();break;}
 renderStats();renderTimers();}
function showDialog(html,kind){$('dialog-content').innerHTML=html;$('dialog').dataset.kind=kind;$('dialog-close').hidden=kind==='summary'||kind==='final';if(!$('dialog').open)$('dialog').showModal();}
function closeDialog(){$('dialog').close();}
function showHelp(){pausedByHelp=game.pause();showDialog(`<span class="dialog-kicker">SORTING HANDBOOK / 07</span><h2 class="dialog-title">一件包裹的正确旅程</h2><p class="dialog-intro">核对标签，完成必要处理，再把包裹送往正确城区。</p><ol class="guide-list"><li><b>1</b><span><strong>先看退件标签</strong>“退回寄件人”优先级最高。按 <kbd class="key-hint">R</kbd> 直接退回。</span></li><li><b>2</b><span><strong>检查特殊包裹</strong>易碎件按 <kbd class="key-hint">Q</kbd> 加固；地址模糊或超重件按 <kbd class="key-hint">E</kbd> 扫描核验。组合标签都需要完成。</span></li><li><b>3</b><span><strong>按地址送往四条路线</strong><kbd class="key-hint">A</kbd> 东城　<kbd class="key-hint">S</kbd> 南城　<kbd class="key-hint">D</kbd> 西城　<kbd class="key-hint">F</kbd> 北城。点击路线卡片或 3D 邮箱也可以。</span></li><li><b>4</b><span><strong>连击、升级，再挑战高峰</strong>正确分拣得分，连续正确提升奖励。错投、漏处理或超时扣信誉和 30 分。班次间用邮币升级，切换后台会自动暂停。</span></li></ol><button class="primary-button" id="help-ok">${pausedByHelp?'继续分拣':'明白，准备开工'}</button>`,'help');$('help-ok').onclick=()=>closeHelp();}
function closeHelp(){closeDialog();if(pausedByHelp){game.resume();pausedByHelp=false;}renderStats();}
function pauseGame(){if(game.status==='paused'){closeDialog();game.resume();renderStats();return;}if(!game.pause())return;showDialog(`<span class="dialog-kicker">TAKE A BREATHER</span><h2 class="dialog-title">传送带暂停了。</h2><p class="dialog-intro">包裹和计时都会等你，喝口水再继续吧。</p><div class="dialog-actions"><button class="primary-button" id="resume">继续分拣 <kbd>空格</kbd></button><button class="secondary-button" id="end-run">结束本轮</button></div>`,'pause');$('resume').onclick=pauseGame;$('end-run').onclick=()=>{closeDialog();game.finish(false);};renderStats();}
function summaryStats(){const accuracy=game.totalHandled?Math.round(game.totalCorrect/game.totalHandled*100):0;return`<div class="summary-score">${game.score.toLocaleString()}<small>总得分</small></div><div class="summary-stats"><div><small>正确送达</small><strong>${game.totalCorrect}<small> 件</small></strong></div><div><small>最高连击</small><strong>${game.maxCombo}</strong></div><div><small>准确率</small><strong>${accuracy}%</strong></div></div>`;}
function showShiftSummary(){if(game.status!=='between')return;const upgrades=[['slow','缓速传送带','每件增加 3 秒',25],['stamp','熟练印章','每件额外 25 分',35],['shield','连击保险','每班保留 1 次连击',40]];showDialog(`<span class="dialog-kicker">SHIFT ${game.shift+1} / COMPLETED</span><h2 class="dialog-title">${SHIFTS[game.shift].name}准点收工！</h2><p class="dialog-intro">本班目标已完成。整备设备，迎接下一波来件。</p>${summaryStats()}<div class="upgrade-title"><strong>分拣站升级</strong><span>邮币余额：<b>${game.coins}</b></span></div><div class="upgrades">${upgrades.map(([id,name,desc,cost])=>`<button class="upgrade ${game.upgrades[id]?'owned':''}" data-upgrade="${id}" ${game.upgrades[id]||game.coins<cost?'disabled':''}><strong>${name}</strong><small>${desc}</small><b>${game.upgrades[id]?'✓ 已升级':cost+' 邮币'}</b></button>`).join('')}</div><p class="modal-note">${game.combo>=5?'连击奖励已到账 · ':''}升级在本轮后续班次持续生效。</p><div class="dialog-actions"><button class="primary-button" id="next-shift">开始${SHIFTS[game.shift+1].name}</button><button class="secondary-button" id="finish-shift">结束本轮</button></div>`,'summary');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>game.buy(b.dataset.upgrade));$('next-shift').onclick=()=>{closeDialog();game.nextShift();sfx('start');};$('finish-shift').onclick=()=>{game.status='playing';closeDialog();game.finish(false);};}
function showFinal(won){if(game.status!=='complete')return;const practice=game.mode==='zen';const title=won?'今日准点，完美收工。':practice?'每次练习，都更熟练。':game.lives<=0?'先歇一歇，再来一班。':game.mode==='shift'&&game.time<=0?'下班铃响了。':'这班辛苦了。';const desc=won?'三个班次挑战完成，你就是今天的王牌分拣员。':game.lives<=0?'信誉已用尽。留意退件与特殊标签，下一次一定能送得更准。':game.mode==='shift'&&game.time<=0?'时间用尽。熟悉快捷键，可以让更多包裹准点送达。':'本轮成绩已保存到这台设备，随时回来挑战自己的纪录。';showDialog(`<span class="dialog-kicker">${won?'POSTMASTER ACHIEVED':'SHIFT REPORT'} / 07</span><h2 class="dialog-title">${title}</h2><p class="dialog-intro">${desc}</p>${summaryStats()}<p class="modal-note">本模式本机最佳：${best[game.mode]||0} 分${game.score>0&&game.score===best[game.mode]?' · 新纪录！':''}</p><div class="dialog-actions"><button class="primary-button" id="replay">再开一班</button><button class="secondary-button" id="back-home">切换模式</button></div>`,'final');$('replay').onclick=startGame;$('back-home').onclick=()=>{closeDialog();game.status='ready';$('start-card').hidden=false;renderStats();};}
$('start').onclick=startGame;$('help').onclick=showHelp;$('pause').onclick=pauseGame;$('sound').onclick=()=>{soundEnabled=!soundEnabled;updateSound();try{localStorage.setItem('parcel-shift-sound',String(soundEnabled));}catch{}if(soundEnabled)sfx('scan');};$('wrap').onclick=()=>game.handle('wrap');$('scan').onclick=()=>game.handle('scan');$('return').onclick=()=>game.handle('return');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>game.sort(Number(b.dataset.route)));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;game.mode=mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));$('mode-description').textContent={shift:'三个班次，逐步升级你的分拣站。',endless:'来件永不停歇，坚持越久，挑战越大。',zen:'没有倒计时，也不扣信誉，轻松熟悉路线。'}[mode];$('start').innerHTML=(mode==='shift'?'开始早班':mode==='endless'?'迎接高峰':'开始练习')+' <kbd>↵</kbd>';renderStats();});
$('dialog-close').onclick=()=>{const kind=$('dialog').dataset.kind;if(kind==='help')closeHelp();else if(kind==='pause')pauseGame();};$('dialog').addEventListener('cancel',e=>{e.preventDefault();const kind=$('dialog').dataset.kind;if(kind==='pause')pauseGame();else if(kind==='help')closeHelp();});
window.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey)return;const key=e.key.toLowerCase();if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if($('dialog').open){if($('dialog').dataset.kind==='pause'&&(key===' '||key==='escape')){e.preventDefault();pauseGame();}return;}if(key==='enter'&&game.status==='ready'){e.preventDefault();startGame();return;}if(key===' '||key==='escape'){e.preventDefault();pauseGame();return;}if(game.status!=='playing')return;if('asdf'.includes(key)&&key.length===1){e.preventDefault();game.sort('asdf'.indexOf(key));}else if(key==='q'){e.preventDefault();game.handle('wrap');}else if(key==='e'){e.preventDefault();game.handle('scan');}else if(key==='r'){e.preventDefault();game.handle('return');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.status==='playing')pauseGame();});
async function initScene(){try{const {createPostOffice}=await import('./scene.js');scene=createPostOffice($('scene'),route=>game.sort(route));scene.setParcel({id:1,tags:[]});$('loading-scene').hidden=true;}catch(error){console.error('3D 场景初始化失败',error);$('loading-scene').textContent='3D 画面不可用，请使用下方路线按钮继续分拣。';$('loading-scene').style.cssText='inset:auto 20px 20px;padding:10px;font-size:11px;background:#e5ead6;z-index:0';}}
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;game.tick(dt);scene?.update(dt,now/1000,game);renderTimers();if(game.transition>0||game.status==='playing')renderStats();requestAnimationFrame(frame);}
updateSound();renderStats();initScene();requestAnimationFrame(frame);
// Browser tools use the same game actions and state as the visible controls.
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(console.warn);}catch(e){console.warn(e);}};register({name:'read_sorting_game',description:'Read the current postal sorting game status, active parcel, score and rules.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return game.snapshot();}});register({name:'start_sorting_game',description:'Start a new postal game. Only available when the station is ready or the current game has ended.',inputSchema:{type:'object',properties:{mode:{enum:['shift','endless','zen']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['shift','endless','zen'].includes(input.mode))throw new Error('Invalid mode');if(!['ready','complete'].includes(game.status))throw new Error('A game is already in progress');mode=input.mode;startGame();return game.snapshot();}});register({name:'process_postal_parcel',description:'Apply a special handling action or deliver the current parcel to route 0 east, 1 south, 2 west, 3 north. A wrong delivery loses points and reputation.',inputSchema:{type:'object',properties:{action:{enum:['wrap','scan','return','deliver']},route:{type:'integer',minimum:0,maximum:3}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['wrap','scan','return','deliver'].includes(input.action))throw new Error('Invalid action');if(game.status!=='playing'||game.transition>0)throw new Error('No parcel is ready');if(input.action==='deliver'){if(!Number.isInteger(input.route)||input.route<0||input.route>3)throw new Error('Invalid route');game.sort(input.route);}else game.handle(input.action);return game.snapshot();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
