import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';

export class CargoScene {
 constructor(el,onAim,onPlace){this.el=el;this.onAim=onAim;this.onPlace=onPlace;this.layer=0;this.dims=[4,2,3];this.target=new THREE.Vector3();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#101827');this.camera=new THREE.PerspectiveCamera(37,1,.1,200);this.camera.position.set(7,7,9);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(el.clientWidth,el.clientHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.enablePan=false;this.controls.minDistance=5;this.controls.maxDistance=22;this.controls.minPolarAngle=.15;this.controls.maxPolarAngle=Math.PI*.49;this.controls.target.set(0,.8,0);this.controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
 this.scene.add(new THREE.AmbientLight('#a4b9e9',2.2));const sun=new THREE.DirectionalLight('#fff1d8',4);sun.position.set(-3,10,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-8,right:8,top:8,bottom:-8});sun.shadow.bias=-.001;this.scene.add(sun);const rim=new THREE.DirectionalLight('#7398ff',3);rim.position.set(5,3,-6);this.scene.add(rim);const green=new THREE.PointLight('#b8ff4f',12,15);green.position.set(-4,2,3);this.scene.add(green);
 this.board=new THREE.Group();this.cargo=new THREE.Group();this.ghost=new THREE.Group();this.scene.add(this.board,this.cargo,this.ghost);this.cubeGeo=new RoundedBoxGeometry(.93,.93,.93,2,.065);this.edgeGeo=new THREE.EdgesGeometry(new THREE.BoxGeometry(.935,.935,.935));this.down=null;this.lastPointer=null;
 const canvas=this.renderer.domElement;const pointers=new Set();
 canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1){this.down=null;return;}this.down=e.button===0&&e.isPrimary?{id:e.pointerId,x:e.clientX,y:e.clientY,dragged:false}:null;});
 canvas.addEventListener('pointermove',e=>{if(this.down&&this.down.id===e.pointerId&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>6)this.down.dragged=true;if(e.buttons===0&&e.pointerType!=='touch')this.aim(e);});
 canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const d=this.down;this.down=null;if(d&&d.id===e.pointerId&&e.button===0&&e.isPrimary&&!d.dragged&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6){if(this.aim(e))this.onPlace();}});
 canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);this.down=null;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
 this.resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);});this.resize.observe(el);this.addStars();this.loop(); }
 addStars(){const points=[];let seed=15;for(let i=0;i<140;i++){seed=(seed*16807)%2147483647;const x=(seed/2147483647-.5)*65;seed=(seed*16807)%2147483647;const y=(seed/2147483647-.5)*45;points.push(x,y,-18);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));this.scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:'#758399',size:.035,transparent:true,opacity:.6})));}
 disposeGroup(g){while(g.children.length){const o=g.children[0];g.remove(o);o.traverse(c=>{if(c.geometry&&c.geometry!==this.cubeGeo&&c.geometry!==this.edgeGeo)c.geometry.dispose();if(c.material){(Array.isArray(c.material)?c.material:[c.material]).forEach(m=>m.dispose());}});}}
 setBoard(dims){this.dims=dims;this.disposeGroup(this.board);const [W,H,D]=dims;const plate=new THREE.Mesh(new RoundedBoxGeometry(W+.6,.28,D+.6,2,.08),new THREE.MeshStandardMaterial({color:'#273b52',metalness:.72,roughness:.36}));plate.position.y=-.2;plate.receiveShadow=true;this.board.add(plate);
 for(let x=0;x<W;x++)for(let z=0;z<D;z++){const floor=new THREE.Mesh(new THREE.BoxGeometry(.96,.045,.96),new THREE.MeshStandardMaterial({color:(x+z)%2?'#263c51':'#2e465b',metalness:.55,roughness:.65}));floor.position.set(x-W/2+.5,-.03,z-D/2+.5);floor.receiveShadow=true;this.board.add(floor);}
 const line=(a,b,color,opacity=1)=>{const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}));this.board.add(l);return l;};
 for(const x of [-W/2,W/2])for(const z of [-D/2,D/2]){line([x,0,z],[x,H,z],'#628495',.48);const dot=new THREE.Mesh(new THREE.BoxGeometry(.08,.13,.08),new THREE.MeshBasicMaterial({color:'#bcfa58'}));dot.position.set(x,.015,z);this.board.add(dot);}
 for(const y of [0,H]){line([-W/2,y,-D/2],[W/2,y,-D/2],'#6c94a2',.45);line([-W/2,y,D/2],[W/2,y,D/2],'#86bdb8',y===0?.8:.25);line([-W/2,y,-D/2],[-W/2,y,D/2],'#6c94a2',.4);line([W/2,y,-D/2],[W/2,y,D/2],'#6c94a2',.4);}
 for(let x=1;x<W;x++)line([x-W/2,0,-D/2],[x-W/2,H,-D/2],'#567484',.17);for(let z=1;z<D;z++)line([-W/2,0,z-D/2],[-W/2,H,z-D/2],'#567484',.17);for(let y=1;y<H;y++){line([-W/2,y,-D/2],[W/2,y,-D/2],'#567484',.21);line([-W/2,y,-D/2],[-W/2,y,D/2],'#567484',.21);}
 const inner=new THREE.Mesh(new THREE.PlaneGeometry(W,D),new THREE.MeshBasicMaterial({color:'#b9ef5b',transparent:true,opacity:.035,side:THREE.DoubleSide,depthWrite:false}));inner.rotation.x=-Math.PI/2;inner.position.y=.012;this.layerPlane=inner;this.board.add(inner);
 // Navigation rings keep the cargo bay visually anchored in the orbital workbench.
 const ring=new THREE.Mesh(new THREE.RingGeometry(Math.max(W,D)*.77,Math.max(W,D)*.77+.009,100),new THREE.MeshBasicMaterial({color:'#3b516a',transparent:true,opacity:.4,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.4;this.board.add(ring);
 this.home();}
 home(){const scale=Math.max(this.dims[0],this.dims[2],this.dims[1]);this.camera.position.set(scale*1.28,scale*1.27,scale*1.6);this.controls.target.set(0,this.dims[1]*.4,0);this.controls.update();}
 top(){const scale=Math.max(this.dims[0],this.dims[2]);this.camera.position.set(.01,scale*2.5,.015);this.controls.target.set(0,0,0);this.controls.update();}
 zoom(delta){this.camera.position.sub(this.controls.target).multiplyScalar(delta).add(this.controls.target);this.controls.update();}
 setLayer(y){this.layer=y;if(this.layerPlane)this.layerPlane.position.y=y+.015;}
 aim(e){const r=this.el.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),-this.layer-.015);const hit=this.ray.ray.intersectPlane(plane,this.target);if(!hit)return false;const x=Math.floor(hit.x+this.dims[0]/2),z=Math.floor(hit.z+this.dims[2]/2);if(x<0||x>=this.dims[0]||z<0||z>=this.dims[2])return false;this.onAim([x,this.layer,z]);return true;}
 addPiece(group,p,ghost=false,valid=true,xray=false){const material=new THREE.MeshStandardMaterial({color:ghost?(valid?'#b5f26a':'#ff5c77'):p.color,roughness:.37,metalness:.17,transparent:ghost||xray,opacity:ghost?.37:xray?.27:1,depthWrite:!ghost&&!xray});for(const c of p.cells){const w=c.map((v,a)=>v+p.pos[a]);const cube=new THREE.Mesh(this.cubeGeo,material);cube.position.set(w[0]-this.dims[0]/2+.5,w[1]+.5,w[2]-this.dims[2]/2+.5);cube.castShadow=!ghost;cube.receiveShadow=true;group.add(cube);
 if(ghost){const edge=new THREE.LineSegments(this.edgeGeo,new THREE.LineBasicMaterial({color:valid?'#ccff78':'#ff6884',transparent:true,opacity:.9}));edge.position.copy(cube.position);group.add(edge);}else{const trim=new THREE.Mesh(new THREE.BoxGeometry(.64,.035,.015),new THREE.MeshStandardMaterial({color:p.color,roughness:.5,metalness:.4}));trim.position.copy(cube.position).add(new THREE.Vector3(0,.29,.469));group.add(trim);const label=new THREE.Mesh(new THREE.BoxGeometry(.2,.11,.014),new THREE.MeshStandardMaterial({color:'#e7efec',transparent:true,opacity:xray?.15:.62}));label.position.copy(cube.position).add(new THREE.Vector3(-.2,-.23,.47));group.add(label);const dots=new THREE.Mesh(new THREE.BoxGeometry(.055,.08,.014),new THREE.MeshStandardMaterial({color:'#293544',transparent:true,opacity:.65}));dots.position.copy(cube.position).add(new THREE.Vector3(.28,-.25,.47));group.add(dots);}}
 }
 setCargo(placements,pieces,xray){this.disposeGroup(this.cargo);for(const p of placements)this.addPiece(this.cargo,{...p,color:pieces.find(c=>c.id===p.id).color},false,true,xray);}
 setGhost(p,valid){this.disposeGroup(this.ghost);if(p)this.addPiece(this.ghost,p,true,valid);}
 celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;if(this.confetti){this.scene.remove(this.confetti);this.confetti.geometry.dispose();this.confetti.material.dispose();this.confetti=null;}this.confettiUntil=performance.now()+3500;const count=160,positions=new Float32Array(count*3);this.confettiVelocity=[];for(let i=0;i<count;i++){positions.set([(Math.random()-.5)*3,this.dims[1]+.2,(Math.random()-.5)*3],i*3);this.confettiVelocity.push([(Math.random()-.5)*.07,Math.random()*.1+.03,(Math.random()-.5)*.07]);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));this.confetti=new THREE.Points(g,new THREE.PointsMaterial({color:'#c3ff64',size:.07}));this.scene.add(this.confetti);}
 loop(){requestAnimationFrame(()=>this.loop());this.controls.update();if(this.ghost)this.ghost.children.forEach(c=>{if(c.isLineSegments)c.material.opacity=.65+Math.sin(performance.now()/350)*.25;});if(this.confetti){const a=this.confetti.geometry.attributes.position;for(let i=0;i<a.count;i++){const v=this.confettiVelocity[i];a.array[i*3]+=v[0];a.array[i*3+1]+=v[1];a.array[i*3+2]+=v[2];v[1]-=.0015;}a.needsUpdate=true;if(performance.now()>this.confettiUntil){this.scene.remove(this.confetti);this.confetti.geometry.dispose();this.confetti.material.dispose();this.confetti=null;}}this.renderer.render(this.scene,this.camera);}
}
