import * as THREE from './three.module.js';
const $=id=>document.getElementById(id), tracks=[{name:'薄荷晴空',bpm:100,sky:0xc6ebdd,fog:0xe1f3dc,notes:[72,76,79,83,79,76,74,67]},{name:'蜜桃日落',bpm:120,sky:0xf1b6a4,fog:0xffe0be,notes:[69,72,76,79,76,72,74,71]},{name:'星河漫游',bpm:140,sky:0x495b8e,fog:0x9b9ac4,notes:[69,73,76,80,76,73,71,68]}];
let chosen=0,zen=false,playing=false,paused=false,muted=false,elapsed=0,score=0,combo=0,maxCombo=0,notes=0,lives=3,lane=0,jumpY=0,velocity=0,jumps=0,dash=0,cooldown=0,invincible=0,shield=0,spawn=0,lastBeat=-1,feedbackTime=0,best=0;
try{best=Number(localStorage.getItem('cloud-bunny-best')||0)}catch{}$('best').textContent=`最高纪录 ${best}`;
const scene=new THREE.Scene();scene.background=new THREE.Color(tracks[0].sky);scene.fog=new THREE.Fog(tracks[0].fog,35,105);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,180);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x7baca0,2.7));const sunlight=new THREE.DirectionalLight(0xfff2d5,3.4);sunlight.position.set(-10,20,10);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-20;sunlight.shadow.camera.right=20;sunlight.shadow.camera.top=20;sunlight.shadow.camera.bottom=-20;sunlight.shadow.normalBias=.05;scene.add(sunlight);
const mat=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness});const cream=mat(0xfffcf1),pink=mat(0xf5b1b0),dark=mat(0x343e3b),blush=mat(0xee9e9f),green=mat(0x689f72),gold=mat(0xf2c759,.35),purple=mat(0x8993af),white=mat(0xffffff);
const sphere=new THREE.SphereGeometry(1,24,16);function ball(parent,material,pos,scale){const m=new THREE.Mesh(sphere,material);m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cloud(x,y,z,size=1,storm=false){const g=new THREE.Group();g.position.set(x,y,z);const m=storm?purple:cream;ball(g,m,[0,0,0],[2.7,.64,1.6]);ball(g,m,[-1.5,.2,0],[1.5,.87,1.32]);ball(g,m,[.35,.48,-.15],[1.65,1.07,1.55]);ball(g,m,[1.8,.15,0],[1.25,.68,1.2]);g.scale.setScalar(size);scene.add(g);return g}
const heroCloud=cloud(0,-.8,0,1.5);const bunny=new THREE.Group();scene.add(bunny);ball(bunny,cream,[0,1,0],[.65,.85,.53]);ball(bunny,cream,[0,2,.02],[.83,.74,.66]);const earL=ball(bunny,cream,[-.42,2.88,0],[.22,.88,.22]);earL.rotation.z=.16;const earR=ball(bunny,cream,[.42,2.9,0],[.22,.87,.22]);earR.rotation.z=-.15;ball(earL,pink,[0,0,.7],[.6,.75,.35]);ball(earR,pink,[0,0,.7],[.6,.75,.35]);ball(bunny,dark,[-.28,2.12,.61],[.07,.10,.04]);ball(bunny,dark,[.28,2.12,.61],[.07,.10,.04]);ball(bunny,white,[-.3,2.15,.644],[.023,.03,.013]);ball(bunny,white,[.26,2.15,.644],[.023,.03,.013]);ball(bunny,pink,[0,1.94,.68],[.09,.064,.05]);ball(bunny,blush,[-.48,1.94,.56],[.14,.08,.03]);ball(bunny,blush,[.48,1.94,.56],[.14,.08,.03]);const armL=ball(bunny,cream,[-.72,1.18,0],[.24,.5,.24]),armR=ball(bunny,cream,[.72,1.18,0],[.24,.5,.24]);const footL=ball(bunny,cream,[-.35,.28,.28],[.31,.22,.43]),footR=ball(bunny,cream,[.35,.28,.28],[.31,.22,.43]);ball(bunny,cream,[0,.8,-.57],[.31,.32,.31]);const scarf=ball(bunny,green,[0,1.48,0],[.64,.16,.52]);ball(bunny,green,[.43,1.22,.51],[.15,.37,.08]);
const shieldMesh=new THREE.Mesh(new THREE.SphereGeometry(1.4,24,16),new THREE.MeshBasicMaterial({color:0xffd26e,transparent:true,opacity:.15,wireframe:true}));shieldMesh.position.y=1.6;bunny.add(shieldMesh);shieldMesh.visible=false;
const islands=[];for(let i=0;i<30;i++){const x=(i%2?1:-1)*(9+Math.random()*25),z=-i*4+14;const c=cloud(x,-3-Math.random()*6,z,.8+Math.random()*1.5);islands.push(c)}
const path=[];for(let z=0;z<19;z++)for(let l=-1;l<=1;l++){const c=cloud(l*3.7,-.9,-z*5, .63);path.push(c)}
const arch=new THREE.Group();const archColors=[0xf4b3a3,0xf2d58e,0xb7d5a0,0x8bc7be];archColors.forEach((c,i)=>{const mesh=new THREE.Mesh(new THREE.TorusGeometry(13-i*.5,.23,8,80,Math.PI),mat(c));mesh.position.set(0,0,-50);arch.add(mesh)});scene.add(arch);
const sparkGeo=new THREE.BufferGeometry();const sparkPos=new Float32Array(180*3);for(let i=0;i<180;i++){sparkPos[i*3]=(Math.random()-.5)*100;sparkPos[i*3+1]=Math.random()*30;sparkPos[i*3+2]=-Math.random()*100}sparkGeo.setAttribute('position',new THREE.BufferAttribute(sparkPos,3));const spark=new THREE.Points(sparkGeo,new THREE.PointsMaterial({color:0xffffff,size:.16,transparent:true,opacity:.7}));scene.add(spark);
const objects=[],particles=[];
function makeNote(){const g=new THREE.Group();ball(g,gold,[0,0,0],[.25,.2,.13]);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,.8,8),gold);stem.position.set(.19,.33,0);g.add(stem);ball(g,gold,[.31,.71,0],[.23,.085,.075]);return g}
function makeCarrot(){const g=new THREE.Group();const cone=new THREE.Mesh(new THREE.ConeGeometry(.23,.8,10),mat(0xf5a35b));cone.rotation.z=Math.PI+.2;g.add(cone);for(let i=0;i<3;i++){const leaf=ball(g,green,[(i-1)*.12,.48,0],[.08,.26,.06]);leaf.rotation.z=(i-1)*-.5}return g}
function addObject(type,l,z){let g;if(type==='storm'){g=new THREE.Group();ball(g,purple,[0,.25,0],[.85,.65,.7]);ball(g,purple,[-.55,.1,0],[.5,.4,.5]);ball(g,purple,[.55,.1,0],[.5,.4,.5]);const bolt=new THREE.Mesh(new THREE.ConeGeometry(.2,.6,3),gold);bolt.rotation.z=Math.PI;bolt.position.y=-.55;g.add(bolt)}else g=type==='carrot'?makeCarrot():makeNote();g.position.set(l*3.7,type==='storm'?1:1.5,z);scene.add(g);objects.push({g,type,l,hit:false})}
function burst(x,y,z,color){for(let i=0;i<10;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.09),mat(color));m.position.set(x,y,z);scene.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.8})}}
let audio,master,nextTone=0,musicStep=0;function audioInit(){if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted?0:.36;master.connect(audio.destination)}audio.resume();nextTone=audio.currentTime;musicStep=0}
function tone(freq,time,duration,vol=.15,type='sine'){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(vol,time+.012);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(master);o.start(time);o.stop(time+duration+.03)}
function music(){if(!audio||!playing||paused)return;const t=tracks[chosen],step=60/t.bpm/2;while(nextTone<audio.currentTime+.12){const n=t.notes[musicStep%8];tone(440*2**((n-69)/12),nextTone,.28,.12,'sine');if(musicStep%2===0){tone(85,nextTone,.12,.22);tone(440*2**((t.notes[Math.floor(musicStep/8)%8]-93)/12),nextTone,.5,.13,'triangle')}if(musicStep%4===2)tone(2200,nextTone,.045,.025,'triangle');musicStep++;nextTone+=step}}
function feedback(text){$('feedback').textContent=text;$('feedback').style.opacity=1;feedbackTime=.8}
function jump(){if(!playing||paused||jumps>=2)return;const beat=60/tracks[chosen].bpm,phase=elapsed%beat,perfect=Math.min(phase,beat-phase)<.12;jumps++;velocity=jumps===1?8.6:7.8;burst(bunny.position.x,.4,0,0xffffff);if(perfect){combo++;maxCombo=Math.max(maxCombo,combo);score+=20*Math.min(5,1+Math.floor(combo/5));feedback('PERFECT ✦')}else{feedback(jumps===2?'DOUBLE HOP':'HOP!')}tone(jumps===2?880:660,audio?.currentTime||0,.12,.12)}
function action(a){if(!playing||paused)return;if(a==='left')lane=Math.max(-1,lane-1);if(a==='right')lane=Math.min(1,lane+1);if(a==='jump')jump();if(a==='dash'&&cooldown<=0){dash=2;cooldown=9;feedback('CLOUD RUSH!');burst(bunny.position.x,1,0,0xf3d569)}}
function selectTrack(i){chosen=i;document.querySelectorAll('.track').forEach((b,j)=>b.classList.toggle('selected',j===i));scene.background.set(tracks[i].sky);scene.fog.color.set(tracks[i].fog);$('bpm').textContent=tracks[i].bpm+' BPM';$('world-tag').innerHTML=`<span>☁</span><div>${tracks[i].name}<small>FLOATING ISLAND / 0${i+1}</small></div>`;document.body.classList.toggle('night',i===2)}
function start(){audioInit();objects.forEach(o=>scene.remove(o.g));objects.length=0;elapsed=score=combo=maxCombo=notes=lane=jumpY=velocity=jumps=dash=cooldown=invincible=shield=spawn=0;lives=3;lastBeat=-1;playing=true;paused=false;$('menu').hidden=true;$('world-tag').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('touch').hidden=!matchMedia('(pointer:coarse)').matches;document.body.classList.add('playing');$('modal').close();heroCloud.visible=false;feedback('LET’S HOP!');updateHUD()}
function updateHUD(){$('score').textContent=String(Math.floor(score)).padStart(5,'0');$('combo').textContent=combo>1?`${combo} 连击 · ×${Math.min(5,1+Math.floor(combo/5))}`:'跟着节拍跳跃';$('hearts').textContent=zen?'∞ 自由漫游':'♥ '.repeat(Math.max(0,lives));$('timer').textContent=zen?`${Math.floor(elapsed)} 秒`:`${Math.max(0,Math.ceil(90-elapsed))} 秒`;$('stage').textContent=`${tracks[chosen].name} · 第 ${1+Math.floor(elapsed/30)} 乐章`;$('progress').style.width=`${zen?elapsed%90/90*100:elapsed/90*100}%`;$('mission').textContent=notes<12?`任务 · 收集音符 ${notes} / 12`:maxCombo<10?`任务 · 达成连击 ${maxCombo} / 10`:'✦ 双重任务完成 · 继续创造纪录';$('power').textContent=dash>0?'✦ 冲刺中 · 无敌吸附':shield>0?'🥕 护盾已就绪':cooldown>0?`冲刺冷却 ${Math.ceil(cooldown)}s`:'冲刺就绪 · Shift'}
function finish(){playing=false;paused=false;if(score>best){best=Math.floor(score);try{localStorage.setItem('cloud-bunny-best',String(best))}catch{}}$('best').textContent=`最高纪录 ${best}`;const rank=score>4000?'S':score>2000?'A':score>800?'B':'C';$('modal-content').innerHTML=`<div class="medal">${rank} ✦</div><h2>${lives>0?'天空为你喝彩！':'休息一下，再蹦蹦'}</h2><p>${lives>0?'这一程的快乐，已收进云朵里。':'躲开雷云，或用跳跃和冲刺越过它。'}</p><div class="results"><div><strong>${Math.floor(score)}</strong><small>音符积分</small></div><div><strong>${maxCombo}</strong><small>最高连击</small></div><div><strong>${notes}</strong><small>收集音符</small></div></div><button class="primary" id="again">再跳一曲</button><button class="zen" id="back">返回天空</button>`;$('modal').showModal();$('again').onclick=start;$('back').onclick=home}
function home(){playing=false;paused=false;$('modal').close();$('menu').hidden=false;$('world-tag').hidden=false;$('hud').hidden=true;$('pause').hidden=true;$('touch').hidden=true;document.body.classList.remove('playing');heroCloud.visible=true;objects.forEach(o=>scene.remove(o.g));objects.length=0;lane=0;jumpY=0}
function pause(){if(!playing)return;paused=!paused;if(paused){$('modal-content').innerHTML='<div class="medal">☁</div><h2>在云上歇一会儿</h2><p>你的节奏还在这里，准备好了就继续。</p><button class="primary" id="resume">继续蹦蹦</button><button class="zen" id="back">结束本次漫游</button>';$('modal').showModal();$('resume').onclick=pause;$('back').onclick=home}else{$('modal').close();if(audio){nextTone=audio.currentTime;audio.resume()}}}
$('start').onclick=start;$('zen').onclick=()=>{zen=!zen;$('zen').setAttribute('aria-pressed',zen);$('zen-mark').textContent=zen?'●':'○'};document.querySelectorAll('.track').forEach(b=>b.onclick=()=>selectTrack(Number(b.dataset.track)));$('sound').onclick=()=>{muted=!muted;if(master)master.gain.value=muted?0:.36;$('sound').textContent=muted?'♩':'♫';$('sound').setAttribute('aria-label',muted?'开启音乐':'关闭音乐')};$('pause').onclick=pause;$('help').onclick=()=>{if(playing&&!paused){pause();return}$('modal-content').innerHTML='<div class="medal">♪</div><h2>让快乐踩在拍子上</h2><p>← → / A D：切换三条云朵路线。<br>空格 / W / ↑：跳跃，空中再按可二段跳。<br>Shift：2 秒无敌冲刺，自动吸附音符。<br>P / Esc：暂停或继续。</p><p>在节拍圆点亮起时跳跃，获得 Perfect 连击。收集金色音符加分，胡萝卜提供一次护盾；跳过或避开雷云。完成 90 秒挑战，或开启无限生命的自由漫游。手机可使用下方触摸按钮。</p>';$('modal').showModal()};$('close').onclick=()=>{if(playing&&paused)pause();else if(!playing&&$('menu').hidden)home();else $('modal').close()};$('modal').addEventListener('cancel',e=>{e.preventDefault();$('close').click()});document.addEventListener('keydown',e=>{if(!playing&&e.target instanceof HTMLButtonElement&&e.code==='Space')return;if(['Space','ArrowUp','ArrowLeft','ArrowRight','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;const map={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump',ShiftLeft:'dash',ShiftRight:'dash'};if(map[e.code])action(map[e.code]);if(e.code==='KeyP'||e.code==='Escape'){if(!$('modal').open)pause();else if(paused)pause()}});document.querySelectorAll('#touch button').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pause()});
let last=performance.now(),time=0;const look=new THREE.Vector3(),targetCamera=new THREE.Vector3();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;time+=dt;const bpm=tracks[chosen].bpm,beat=60/bpm,t=playing?elapsed:time;const pulse=(t%beat)/beat;document.querySelectorAll('.beat-dots i').forEach((d,i)=>d.classList.toggle('on',i===Math.floor(t/beat)%4&&pulse<.32));if(feedbackTime>0){feedbackTime-=dt;if(feedbackTime<=0)$('feedback').style.opacity=0}
if(playing&&!paused){elapsed+=dt;music();cooldown=Math.max(0,cooldown-dt);dash=Math.max(0,dash-dt);invincible=Math.max(0,invincible-dt);velocity-=23*dt;jumpY+=velocity*dt;if(jumpY<=0){jumpY=0;velocity=0;jumps=0}let speed=10+Math.min(6,elapsed/22)+(dash>0?6:0);spawn-=dt;if(spawn<=0){spawn=beat*2;const l=Math.floor(Math.random()*3)-1;addObject(Math.random()<.25&&elapsed>5?'storm':'note',l,-65);if(Math.random()<.36)addObject('note',l===1?-1:1,-68);if(Math.random()<.1)addObject('carrot',Math.floor(Math.random()*3)-1,-73)}for(const c of path){c.position.z+=speed*dt;if(c.position.z>8)c.position.z-=95}for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.g.position.z+=speed*dt;if(o.type!=='storm')o.g.rotation.y+=dt*1.8;const dx=Math.abs(o.g.position.x-bunny.position.x),dz=Math.abs(o.g.position.z);if(!o.hit&&dz<(dash>0?3:1.05)&&dx<(dash>0&&o.type!=='storm'?5:1.15)){if(o.type==='storm'){if(jumpY<1.6&&dash<=0&&invincible<=0){if(shield>0){shield=0;feedback('护盾保护 ✦')}else{if(!zen)lives--;combo=0;feedback(zen?'轻轻碰了一下':'小心雷云！')}invincible=1.8;burst(o.g.position.x,1,0,0xa1a9bc);o.hit=true;if(lives<=0){finish();break}}}else if(Math.abs((1.5+jumpY)-o.g.position.y)<2||dash>0){o.hit=true;if(o.type==='note'){notes++;score+=100*Math.min(5,1+Math.floor(combo/5));tone(1046,audio?.currentTime||0,.1,.05);if(notes===12){score+=500;feedback('音符任务完成 +500')}}else{shield=1;score+=150;feedback('胡萝卜护盾！')}burst(o.g.position.x,o.g.position.y,0,0xf2cd61)}}if(o.hit||o.g.position.z>9){if(!o.hit&&o.type==='note')combo=0;scene.remove(o.g);objects.splice(i,1)}}if(!zen&&elapsed>=90&&playing)finish();updateHUD()}
if(!paused){bunny.position.x=THREE.MathUtils.lerp(bunny.position.x,playing?lane*3.7:0,1-Math.exp(-dt*13));bunny.position.y=playing?jumpY+Math.abs(Math.sin(t/beat*Math.PI))*.1:Math.abs(Math.sin(t/beat*Math.PI))*.22;bunny.rotation.z=Math.sin(t/beat*Math.PI*2)*.055;bunny.rotation.y=playing?Math.sin(t/beat*Math.PI*2)*.06:.32+Math.sin(time*.4)*.16;armL.rotation.z=-.45-Math.sin(t/beat*Math.PI*2)*.35;armR.rotation.z=.45-Math.sin(t/beat*Math.PI*2)*.35;earL.rotation.z=.16+Math.sin(time*4)*.06;earR.rotation.z=-.15+Math.sin(time*4+.5)*.06;footL.position.y=.28+Math.max(0,Math.sin(t/beat*Math.PI*2))*.1;footR.position.y=.28+Math.max(0,-Math.sin(t/beat*Math.PI*2))*.1;bunny.visible=invincible<=0||Math.floor(time*12)%2===0;shieldMesh.visible=shield>0||dash>0;shieldMesh.rotation.y+=dt;for(let i=0;i<islands.length;i++)islands[i].position.y+=Math.sin(time*.6+i)*dt*.12;for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=7*dt;p.m.scale.setScalar(Math.max(0,p.life));if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();particles.splice(i,1)}}}
const mobile=innerWidth<760;if(playing){targetCamera.set(0,8.4,17);look.set(0,0,-9)}else{targetCamera.set(mobile?-6.5:-8,6.3,mobile?19:17);look.set(mobile?-3.3:-4.4,1.2,0)}camera.position.lerp(targetCamera,1-Math.exp(-dt*3));camera.lookAt(look);path.forEach(c=>c.visible=playing);arch.visible=playing;spark.rotation.y=time*.004;renderer.render(scene,camera)}camera.position.set(-8,6.3,17);requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});
window.cloudBunny={getState:()=>({playing,paused,score,notes,combo,maxCombo,lives,elapsed,lane,jumps,shield,zen,track:tracks[chosen].name}),action};if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'get_game_state',description:'Read the current Cloud Bunny score and game state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.cloudBunny.getState()})}catch{}}
