import {World} from './scene.js';
import {Music,TRACKS} from './audio.js';
const $=s=>document.querySelector(s),ui=$('#interface');
const icons={play:'<path d="m9 5 11 7-11 7Z" fill="currentColor" stroke="none"/>',sound:'<path d="m11 5-6 5H2v4h3l6 5zM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',mute:'<path d="m11 5-6 5H2v4h3l6 5zM16 9l6 6m0-6-6 6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="15" cy="17" r="3" fill="currentColor"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3c-1 0-1 1-1 2m0 3h.01"/>',heart:'<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>',star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',music:'<path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',carrot:'<path d="M15 6C6 0-1 18 3 21c2 2 17-6 12-15Zm-7 4 3 2m-6 3 3 1m7-10 5-4m-4 4 6 1m-7-2 1-5"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7z"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',arrow:'<path d="m14 6-6 6 6 6"/>',trophy:'<path d="M8 3h8v7a4 4 0 0 1-8 0Zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 2v5m-4 2h8"/>',moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',cloud:'<path d="M7 18a5 5 0 1 1 1-10 6 6 0 0 1 11 3 3.5 3.5 0 0 1 0 7Z"/>'};
const ic=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.star}</svg>`;
const storage={get(){try{return JSON.parse(localStorage.getItem('cloud-hop-v1')||'{}')}catch{return{}}},save(v){try{localStorage.setItem('cloud-hop-v1',JSON.stringify(v))}catch{}}};
let saved=storage.get();saved={best:{},carrots:0,plays:0,maxCombo:0,perfects:0,costume:0,owned:[0],...saved};
const music=new Music();music.volume=saved.volume??.55;
let world;try{world=new World($('#world'))}catch(e){ui.innerHTML='<div class="fatal"><h1>云朵暂时没有加载成功</h1><p>这个游戏需要支持 WebGL 的浏览器。请开启硬件加速，或使用新版 Chrome、Safari、Edge 再试。</p><button onclick="location.reload()">重新加载</button></div>';throw e;}
let state='menu',trackIndex=0,mode='relax',targets=[],score=0,combo=0,maxCombo=0,perfect=0,good=0,miss=0,carrots=0,energy=0,health=5,lane=0,totalBeats=128,boostStart=Infinity,boostEnd=-1,modal=null,lastFeedbackAt=0,feedback='',feedbackClass='',lastTap=-10,rafTime=0,starting=false,scoreBanked=false,lifecycle=0;
const costumes=[{name:'葡萄汽水',color:'#9276df',price:0},{name:'蜜桃乌龙',color:'#ed9ba7',price:30},{name:'薄荷冰沙',color:'#6cbfae',price:60}];
function applyCostume(){world.materials.purple.color.set(costumes[saved.costume]?.color||costumes[0].color)}applyCostume();
const track=()=>TRACKS[trackIndex];
function key(){return `${track().id}-${mode}`}
function makeChart(start=0,end=totalBeats){const a=[];let seed=19+trackIndex*29+start,prev=0;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const step=trackIndex===2?1:2;for(let beat=Math.max(4,start);beat<end;beat+=step){if(beat<12)prev=0;else prev=Math.max(-1,Math.min(1,prev+(rnd()>.5?1:-1)));a.push({id:`n${beat}`,beat,lane:prev,type:'note',done:false});if(beat%8===4)a.push({id:`c${beat}`,beat:beat+1,lane:prev,type:'carrot',done:false});if(beat>16&&beat%8===0)a.push({id:`s${beat}`,beat:beat+1,lane:prev===0?(rnd()>.5?1:-1):-prev,type:'storm',done:false});}return a;}
function header(){return `<header class="header"><button class="brand" data-action="home" aria-label="云端蹦迪首页"><span class="brand-mark">${ic('cloud')}</span><span>云端蹦迪<small>CLOUD HOP</small></span></button><nav><span class="tiny-tag">${ic('music')} 跟着心跳，去云端</span><button class="icon-button" data-action="help" aria-label="玩法说明">${ic('help')}</button><button class="icon-button" data-action="mute" aria-label="${music.muted?'开启声音':'静音'}">${ic(music.muted?'mute':'sound')}</button><button class="icon-button" data-action="settings" aria-label="游戏设置">${ic('settings')}</button></nav></header>`}
function render(){document.body.dataset.state=state;document.body.dataset.night=trackIndex===2;ui.innerHTML=header()+(state==='menu'?menu():hud())+(state==='paused'?pauseView():'')+(state==='result'?resultView():'')+(modal?modalView():'');bind();}
function menu(){const t=track();return `<main class="lobby"><section class="intro"><div class="eyebrow"><span></span> 云端舞池 · 现在开放</div><h1>把烦恼留在地面，<br>一起<span>蹦上云端。</span></h1><p class="intro-copy">戴上耳机，踩着节拍。<br>和小兔跳进一场轻飘飘的音乐冒险。</p><div class="mode-picker" role="group" aria-label="游戏模式">${[['relax','轻松漫游'],['challenge','节奏挑战'],['endless','无尽云海']].map(([v,n])=>`<button data-mode="${v}" class="${mode===v?'selected':''}" aria-pressed="${mode===v}">${n}</button>`).join('')}</div><p class="mode-description">${mode==='relax'?'自由享受音乐，漏拍也没关系。':mode==='challenge'?'保持节奏与连击，守护你的 5 颗爱心。':'云海没有尽头，看看你能走多远。'}</p><button class="start-button" data-action="start">${ic('play')}<span>开始云端之旅</span><kbd>SPACE</kbd></button><span class="sound-hint">${ic('sound')} 点击开始，开启音乐</span><div class="little-stats"><span>${ic('trophy')} 最高纪录 <strong>${(saved.best[key()]||0).toLocaleString()}</strong></span><span>${ic('carrot')} <strong>${saved.carrots}</strong></span></div></section><div class="scene-label"><span class="live-dot"></span> ${t.title}<small>${t.bpm} BPM · ${t.tag.split(' · ')[1]}</small></div><button class="bunny-label" data-action="wardrobe">${ic('star')} 小兔的衣橱 <span>+</span></button><div class="float-caption">每一次跳跃，都有好心情。<span>✦</span></div><section class="music-dock"><div class="dock-title"><span>选一首，出发。</span><small>THE SKY IS YOUR DANCE FLOOR</small><button data-action="achievements">${ic('trophy')} 成就</button></div><div class="tracks">${TRACKS.map((t,i)=>`<button data-track="${i}" class="track-card ${trackIndex===i?'active':''}" aria-pressed="${trackIndex===i}"><span class="track-art art-${i}">${ic(['cloud','sun','moon'][i])}<span class="vinyl-dot"></span></span><span class="track-info"><small>0${i+1} / ${t.english}</small><strong>${t.title}</strong><span>${t.tag}</span></span><span class="track-meta">${t.bpm}<small>BPM</small></span><span class="track-check">${trackIndex===i?'✓':ic('play')}</span></button>`).join('')}</div></section><footer class="lobby-footer"><span><kbd>←</kbd><kbd>→</kbd> 换道 <i></i><kbd>空格</kbd> 踩点跳跃 <i></i><kbd>Shift</kbd> 能量冲刺</span><span>放轻松，你已经在云上了 ${ic('cloud')}</span></footer></main>`}
function hud(){return `<section class="game-hud"><div class="score-panel"><small>SCORE</small><strong id="score">${score.toLocaleString()}</strong><div id="lives">${mode==='relax'?'自由漫游':Array(5).fill(0).map((_,i)=>`<span class="${i>=health?'empty':''}">♥</span>`).join('')}</div></div><div class="track-progress"><span>${track().title}<small>${mode==='endless'?'无尽云海':track().bpm+' BPM'}</small></span><div class="progress-rail"><div id="progress-fill"></div></div><div class="progress-meta"><span id="elapsed">0:00</span><span>${mode==='endless'?'∞':formatTime(totalBeats*60/track().bpm)}</span></div></div><button class="icon-button pause-button" data-action="pause" aria-label="暂停游戏">${ic('pause')}</button><div class="combo-panel"><strong id="combo">${combo}</strong><small>COMBO</small><span id="multiplier">×1 倍率</span></div><div id="feedback" aria-live="polite"></div><div id="countdown"></div><div class="energy-box"><div><span>${ic('bolt')} 彩虹能量</span><strong id="energy-label">0%</strong></div><div class="energy-rail"><div id="energy-fill"></div></div><button id="boost" data-action="boost">${ic('bolt')} 冲刺 <kbd>SHIFT</kbd></button></div><div class="rhythm-panel"><span id="rhythm-guide">看到音符靠近小兔，踩准节拍跳起来</span><div class="beat-meter"><span class="beat-note left-note">♪</span><span class="beat-note right-note">♪</span><div class="beat-target"><span></span></div></div><span class="rhythm-keys"><kbd>← →</kbd> 换道 <kbd>空格</kbd> 跳跃 <kbd>ESC</kbd> 暂停</span></div><div class="touch-controls"><button data-action="left" aria-label="向左换道">${ic('arrow')}</button><button class="touch-jump" data-action="jump">${ic('music')} 跳</button><button data-action="right" aria-label="向右换道">${ic('arrow')}</button></div></section>`}
function pauseView(){return `<div class="overlay"><section class="dialog pause-dialog" role="dialog" aria-modal="true" aria-label="暂停游戏"><div class="dialog-symbol">${ic('pause')}</div><small>TAKE A LITTLE BREATH</small><h2>在云上歇一会儿</h2><p>音乐和小兔都在这里等你。</p><button class="primary-button" data-action="resume">${ic('play')} 继续跳舞</button><button class="secondary-button" data-action="restart">重新开始</button><button class="text-button" data-action="home">返回云端</button></section></div>`}
function resultView(){const acc=perfect+good+miss?Math.round((perfect+good*.7)/(perfect+good+miss)*100):0;const grade=acc>=93?'S':acc>=80?'A':acc>=60?'B':'C';return `<div class="overlay"><section class="dialog result-dialog" role="dialog" aria-modal="true" aria-label="本次成绩"><small>A LITTLE HOP, A LOT OF JOY</small><div class="grade">${grade}<span>${health>0?'旅程完成':'下次一定跳得更远'}</span></div><h2>${health>0?'把快乐，跳进云里。':'深呼吸，再来一曲。'}</h2><div class="final-score">${score.toLocaleString()}<small>本次得分 ${score>=(saved.best[key()]||0)&&score>0?'· 新纪录 ✦':''}</small></div><div class="result-stats"><span><strong>${maxCombo}</strong>最高连击</span><span><strong>${acc}%</strong>节拍准确率</span><span><strong>+${carrots}</strong>获得胡萝卜</span></div><div class="judgements"><span>PERFECT <b>${perfect}</b></span><span>GOOD <b>${good}</b></span><span>MISS <b>${miss}</b></span></div><button class="primary-button" data-action="restart">${ic('play')} 再跳一次</button><button class="text-button" data-action="home">换首歌，继续快乐</button></section></div>`}
function modalView(){let content='';if(modal==='help')content=`<small>HOW TO HOP</small><h2>简单几步，快乐起跳。</h2><div class="help-row"><span>${ic('music')}</span><div><h3>跟着节拍，跳！</h3><p>紫色音符到达小兔脚下的光圈时，按空格。前 8 拍不用换道，先找到感觉。</p></div></div><div class="help-row"><span>${ic('arrow')}</span><div><h3>云朵之间，自由换道</h3><p>用 ← → 或 A / D 对准音符。胡萝卜经过时自动收集；灰色雷云要换道避开，或及时跳过。</p></div></div><div class="help-row"><span>${ic('bolt')}</span><div><h3>连击蓄能，彩虹冲刺</h3><p>踩准节拍会积累能量与倍率。能量满后按 Shift，下一强拍开始 8 拍自动收集并免伤。</p></div></div><p class="help-foot">手机使用底部触屏按钮。轻松模式漏拍不会结束；挑战和无尽模式有 5 颗爱心。按 P / Esc 可暂停。</p><button class="primary-button" data-action="close-modal">我准备好了</button>`;
 if(modal==='settings')content=`<small>MAKE YOURSELF AT HOME</small><h2>调到喜欢的频率</h2><label class="setting-label" for="volume">音乐音量 <span id="volume-value">${Math.round(music.volume*100)}%</span></label><input id="volume" type="range" min="0" max="100" value="${music.volume*100}"><div class="setting-row"><span>声音</span><button class="secondary-button" data-action="mute">${ic(music.muted?'mute':'sound')} ${music.muted?'已静音':'播放声音'}</button></div><p class="help-foot">原创合成音乐 · 无需下载音频<br>成绩、衣橱和偏好只保存在这台设备。</p>`;
 if(modal==='wardrobe')content=`<small>LITTLE BUNNY'S CLOSET</small><h2>今天穿什么颜色？</h2><p class="balance">${ic('carrot')} ${saved.carrots} 根胡萝卜</p><div class="costumes">${costumes.map((c,i)=>`<button data-costume="${i}" class="costume ${saved.costume===i?'active':''}" ${!saved.owned.includes(i)&&saved.carrots<c.price?'disabled':''}><span style="background:${c.color}">${ic('music')}</span><strong>${c.name}</strong><small>${saved.costume===i?'已穿戴':saved.owned.includes(i)?'点击穿戴':c.price+' 根胡萝卜解锁'}</small></button>`).join('')}</div><p class="help-foot">收集云路上的胡萝卜，为小兔换上新耳机和围巾。</p>`;
 if(modal==='achievements'){const badges=[['初次云游','完成 1 次旅程',saved.plays>=1],['节奏小天才','达到 20 连击',saved.maxCombo>=20],['完美舞步','累计 50 次 Perfect',saved.perfects>=50],['胡萝卜收藏家','解锁全部 3 套装扮',saved.owned.length>=3]];content=`<small>SMALL HOPS, BIG MOMENTS</small><h2>你的云端收藏</h2><div class="badges">${badges.map(([n,d,ok])=>`<div class="badge ${ok?'unlocked':''}"><span>${ic('trophy')}</span><div><strong>${n}</strong><small>${d}</small></div><b>${ok?'✓':'○'}</b></div>`).join('')}</div><p class="help-foot">已完成 ${saved.plays} 次旅程 · 最佳连击 ${saved.maxCombo}</p>`;}
 return `<div class="overlay modal-overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="${{help:'玩法说明',settings:'游戏设置',wardrobe:'小兔衣橱',achievements:'云端成就'}[modal]}"><button class="close-button icon-button" data-action="close-modal" aria-label="关闭">${ic('close')}</button>${content}</section></div>`;}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));document.querySelectorAll('[data-track]').forEach(b=>b.addEventListener('click',()=>{trackIndex=+b.dataset.track;world.setTrack(track());render()}));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;render()}));document.querySelectorAll('[data-costume]').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.costume;if(!saved.owned.includes(i)){if(saved.carrots<costumes[i].price)return;saved.carrots-=costumes[i].price;saved.owned.push(i)}saved.costume=i;storage.save(saved);applyCostume();render()}));$('#volume')?.addEventListener('input',e=>{music.setVolume(+e.target.value/100);saved.volume=music.volume;storage.save(saved);$('#volume-value').textContent=`${e.target.value}%`});if(modal||state==='paused'||state==='result')queueMicrotask(()=>$('.dialog button')?.focus());}
async function start(){if(starting)return;starting=true;const generation=++lifecycle;modal=null;try{await music.unlock();if(generation!==lifecycle)return;score=combo=maxCombo=perfect=good=miss=carrots=energy=0;health=5;lane=0;boostStart=Infinity;boostEnd=-1;lastTap=-10;feedback='';scoreBanked=false;totalBeats=track().bars*4;targets=makeChart();world.setTargets(targets);world.lane=0;music.play(track());state='running';render();}catch(e){feedback='音频未能启动，请再次点击开始';alert(feedback);}finally{if(generation===lifecycle)starting=false;}}
async function pause(){if(state!=='running')return;state='paused';render();await music.pause();}
function bank(){if(scoreBanked)return;scoreBanked=true;saved.carrots+=carrots;saved.plays++;saved.maxCombo=Math.max(saved.maxCombo,maxCombo);saved.perfects+=perfect;saved.best[key()]=Math.max(saved.best[key()]||0,score);storage.save(saved);}
function finish(){bank();state='result';music.stop();world.boost=false;render();}
function goHome(){lifecycle++;starting=false;if(state==='running'||state==='paused')bank();music.stop();music.ctx?.resume();state='menu';modal=null;world.boost=false;render();}
async function action(a){if(a==='start'||a==='restart')return start();if(a==='mute'){music.setMute(!music.muted);return render()}if(a==='home')return goHome();if(a==='pause')return pause();if(a==='resume'&&state==='paused'){const generation=++lifecycle;await music.resume();if(generation!==lifecycle||state!=='paused')return;music.running=true;state='running';return render()}if(['help','settings','wardrobe','achievements'].includes(a)){if(state==='running')await pause();modal=a;render();return}if(a==='close-modal'){modal=null;render();return}if(state!=='running'||modal)return;if(a==='left')move(-1);if(a==='right')move(1);if(a==='jump')jump();if(a==='boost')boost();}
function move(dir){lane=Math.max(-1,Math.min(1,lane+dir));world.lane=lane;}
function feedbackText(s,type='perfect'){feedback=s;feedbackClass=type;lastFeedbackAt=world.clock;const el=$('#feedback');if(el){el.textContent=s;el.className=type;el.style.animation='none';void el.offsetWidth;el.style.animation='';}}
function collect(n,quality='perfect',auto=false){if(n.done)return;n.done=true;if(n.type==='carrot'){carrots++;score+=100;world.burst(n.lane,'#ffcd78');music.effect('carrot');feedbackText('+1 胡萝卜','carrot');return}if(n.type==='storm')return;combo++;maxCombo=Math.max(maxCombo,combo);const multiplier=1+Math.min(3,Math.floor(combo/10));if(quality==='perfect'){perfect++;score+=300*multiplier;energy=Math.min(100,energy+11)}else{good++;score+=150*multiplier;energy=Math.min(100,energy+7)}world.burst(n.lane,auto?'#ffe0a3':'#d0aaff');music.effect('hit');feedbackText(auto?'彩虹冲刺 ✦':quality==='perfect'?'PERFECT!':'GOOD!',quality);if(combo%10===0)world.jump(true);}
function fail(n){n.done=true;if(n.type==='carrot')return;combo=0;miss++;if(mode!=='relax')health--;energy=Math.max(0,energy-5);feedbackText(n.type==='storm'?'雷云！换条路吧':'再找找节奏','miss');music.effect('miss');if(health<=0)finish();}
function jump(){const now=music.ctx.currentTime;if(now-lastTap<.12)return;lastTap=now;world.jump();const beat=music.beat;if(beat<0)return;const n=targets.filter(x=>x.type==='note'&&!x.done&&x.lane===lane).sort((a,b)=>Math.abs(a.beat-beat)-Math.abs(b.beat-beat))[0];if(!n)return;const delta=Math.abs(n.beat-beat)*60/track().bpm;const window=mode==='relax'?.19:.14;if(delta<=window)collect(n,delta<=.08?'perfect':'good');else feedbackText('跟着鼓点，再跳一下','hint');}
function boost(){if(energy<100||music.beat<boostEnd||boostStart!==Infinity)return;energy=0;boostStart=Math.ceil((music.beat+.05)/4)*4;boostEnd=boostStart+8;feedbackText('下一强拍 · 准备冲刺','carrot');music.effect('boost');}
function formatTime(s){return `${Math.floor(Math.max(0,s)/60)}:${String(Math.floor(Math.max(0,s))%60).padStart(2,'0')}`}
function updateGame(){const beat=music.beat,spb=60/track().bpm;if(beat>=boostEnd&&boostStart!==Infinity){boostStart=Infinity;world.boost=false}world.boost=beat>=boostStart&&beat<boostEnd;
 if(mode==='endless'&&beat>totalBeats-16){const more=makeChart(totalBeats,totalBeats+64);totalBeats+=64;targets=targets.filter(n=>!n.done&&n.beat>beat-3).concat(more);world.setTargets(targets);}
 for(const n of targets){if(n.done)continue;const diff=(beat-n.beat)*spb;if(world.boost&&diff>=0&&diff<.5){if(n.type==='storm')n.done=true;else collect(n,'perfect',true);continue}if(n.type==='note'&&diff>(mode==='relax'?.19:.14))fail(n);else if(n.type==='carrot'&&Math.abs(diff)<.19&&n.lane===lane)collect(n);else if(n.type==='storm'&&diff>0){n.done=true;if(n.lane===lane&&world.clock-world.jumpAt>.43)fail(n)}else if(n.type==='carrot'&&diff>.2)n.done=true;if(state!=='running')return;}
 if(mode!=='endless'&&beat>totalBeats+.4){finish();return}$('#score').textContent=score.toLocaleString();$('#combo').textContent=combo;$('#multiplier').textContent=`×${1+Math.min(3,Math.floor(combo/10))} 倍率`;$('#energy-label').textContent=world.boost?'冲刺中':energy+'%';$('#energy-fill').style.width=energy+'%';$('#boost').disabled=energy<100;$('#boost').classList.toggle('ready',energy>=100);$('#progress-fill').style.width=Math.max(0,beat/totalBeats*100)+'%';$('#elapsed').textContent=formatTime(beat*spb);if(mode!=='relax')$('#lives').innerHTML=Array(5).fill(0).map((_,i)=>`<span class="${i>=health?'empty':''}">♥</span>`).join('');const count=$('#countdown');count.textContent=beat<0?Math.ceil(-beat):beat<.7?'LET’S HOP!':'';$('#feedback').style.opacity=world.clock-lastFeedbackAt<1?1:0;
 const interval=trackIndex===2?1:2;const phase=((beat%interval)+interval)%interval;document.documentElement.style.setProperty('--beat',1-Math.abs(Math.sin(beat*Math.PI)));document.documentElement.style.setProperty('--note-travel',phase/interval);$('#rhythm-guide').textContent=world.boost?(boostEnd-beat<2?'冲刺即将结束 · 准备接拍':'彩虹冲刺！自动收集音符'):beat<12?'先在中间云道，跟着鼓点按空格':'看准音符的云道 · 靠近光圈时跳跃';}
window.addEventListener('keydown',e=>{if(e.key==='Tab'&&(modal||state==='paused'||state==='result')){const items=[...document.querySelectorAll('.overlay:last-child button:not(:disabled), .overlay:last-child input')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault()}return}if(e.repeat||e.target.matches?.('input'))return;if(e.code==='Escape'||e.code==='KeyP'){e.preventDefault();if(modal){modal=null;render()}else if(state==='running')pause();else if(state==='paused')action('resume');return}if(modal)return;if(state==='menu'&&e.code==='Space'&&!e.target.matches?.('button')){e.preventDefault();start();return}if(state!=='running')return;const actions={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ShiftLeft:'boost',ShiftRight:'boost'};if(actions[e.code]){e.preventDefault();action(actions[e.code]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause()});$('#world').addEventListener('pointerdown',()=>{if(state==='running')jump()});
render();world.setTrack(track());function tick(ms){const dt=Math.min(.05,(ms-rafTime)/1000||.016);rafTime=ms;if(state==='running'){music.update();updateGame()}world.render(state==='paused'?0:dt,state==='running'||state==='paused'?music.beat:0,state==='running'||state==='paused');requestAnimationFrame(tick)}requestAnimationFrame(tick);
const readState=()=>({state,track:track().id,mode,score,combo,maxCombo,perfect,good,miss,carrots,energy,health,lane,beat:music.beat,boost:world.boost,visibleTargets:targets.filter(n=>!n.done&&n.beat>music.beat-1&&n.beat<music.beat+8).map(n=>({type:n.type,lane:n.lane,beat:n.beat})),audioState:music.ctx?.state??'uninitialized',muted:music.muted,audioGain:music.master?.gain.value??0});
Object.defineProperty(window,'cloudHop',{value:Object.freeze({getState:readState}),writable:false});
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_cloud_hop_game',title:'查看云端蹦迪状态',description:'读取当前曲目、游戏模式、得分和节奏状态。不会开始或操作游戏。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('此工具不接受参数');return readState()}},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true});}catch{}}
