import {chromium} from '/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4868/',{waitUntil:'networkidle'});await page.locator('#loading-scene').waitFor({state:'hidden'});await page.screenshot({path:'output/playwright/desktop-start.png',fullPage:true});
await page.locator('#start').click();await page.waitForTimeout(100);const routes={'东城区':0,'南城区':1,'西城区':2,'北城区':3};let route=routes[await page.locator('#address-district').textContent()];await page.locator(`[data-route="${route}"]`).click();await page.waitForTimeout(750);assert.match(await page.locator('#parcel-tags').textContent(),/易碎/);await page.keyboard.press('q');assert.match(await page.locator('#parcel-tags').textContent(),/已加固/);route=routes[await page.locator('#address-district').textContent()];await page.keyboard.press('asdf'[route]);await page.waitForTimeout(750);assert.equal(await page.locator('#address-district').textContent(),'地址模糊');await page.keyboard.press('e');route=routes[await page.locator('#address-district').textContent()];assert.notEqual(route,undefined);await page.keyboard.press('asdf'[route]);await page.waitForTimeout(750);assert.match(await page.locator('#parcel-tags').textContent(),/加急/);route=routes[await page.locator('#address-district').textContent()];await page.keyboard.press('asdf'[route]);await page.waitForTimeout(750);assert.match(await page.locator('#parcel-tags').textContent(),/退回/);await page.keyboard.press('r');await page.waitForTimeout(750);assert.match(await page.locator('#parcel-tags').textContent(),/超重/);await page.keyboard.press('e');await page.keyboard.press('Space');const time=await page.locator('#parcel-time').textContent();await page.waitForTimeout(800);assert.equal(await page.locator('#parcel-time').textContent(),time);await page.locator('#resume').click();await page.screenshot({path:'output/playwright/desktop-playing.png',fullPage:true});
// Complete the first shift using visible package text and controls.
for(let i=0;i<7;i++){if(await page.locator('#next-shift').count())break;const tags=await page.locator('#parcel-tags').textContent();if(tags.includes('退回'))await page.locator('#return').click();else{if(tags.includes('易碎'))await page.locator('#wrap').click();if(tags.includes('模糊')||tags.includes('超重'))await page.locator('#scan').click();route=routes[await page.locator('#address-district').textContent()];await page.locator(`[data-route="${route}"]`).click();}await page.waitForTimeout(750);}
await page.locator('#next-shift').waitFor();await page.locator('[data-upgrade="slow"]').click();assert.match(await page.locator('[data-upgrade="slow"]').textContent(),/已升级/);await page.locator('#next-shift').click();assert.match(await page.locator('#shift-label').textContent(),/午班/);await page.locator('#help').click();assert.equal(await page.locator('#dialog').getAttribute('data-kind'),'help');await page.locator('#help-ok').click();await page.keyboard.press('Space');await page.locator('#end-run').click();await page.waitForTimeout(650);await page.locator('#back-home').click();await page.locator('[data-mode="zen"]').click();await page.locator('#start').click();assert.equal(await page.locator('#parcel-time').textContent(),'不限时');await page.keyboard.press('Space');
await page.setViewportSize({width:390,height:844});await page.locator('#resume').click();await page.screenshot({path:'output/playwright/mobile-playing.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(errors.length,0,errors.join('\n'));console.log('Browser checks passed: WebGL, click/keyboard, first 6 parcel types, pause, shift completion, upgrade, help, practice, mobile overflow.');await browser.close();
