import assert from 'node:assert/strict';
import {Simulation,angleTo,distance} from '../dist/simulation.js';
const tick=(s,seconds)=>{for(let i=0;i<seconds*20;i++)s.step(.05)};
const tests=[];const test=(name,fn)=>{fn();tests.push(name)};
test('北向方位与运动坐标一致',()=>{assert.equal(angleTo({x:0,z:0},{x:0,z:-10}),0);assert.equal(angleTo({x:0,z:0},{x:10,z:0}),90)});
test('暂停冻结任务时间与武器冷却',()=>{const s=new Simulation();s.start();s.ping();s.togglePause();tick(s,10);assert.equal(s.time,0);assert.equal(s.pingCooldown,12)});
test('静默模式限制航速且不能从滑杆突破',()=>{const s=new Simulation();s.setSpeed(25);s.toggleSilent();s.setSpeed(25);assert.equal(s.player.desiredSpeed,5);s.start();tick(s,1);assert(s.player.noise<15)});
test('主动声呐解算目标、增加暴露并阻止连发',()=>{const s=new Simulation();s.start();assert(s.ping().ok);assert.equal(s.player.exposure,28);assert(s.enemies.every(e=>e.known));assert(s.enemies[1].confidence>=.99);assert.equal(s.ping().ok,false)});
test('必须选择且解算目标才能发射',()=>{const s=new Simulation();s.start();assert.equal(s.fire().ok,false);s.select('S01');assert.equal(s.fire().ok,false);assert.equal(s.player.torpedoes,8)});
test('发射的制导鱼雷实际追踪、命中并推进撤离目标',()=>{const s=new Simulation();s.start();s.ping();s.select('S02');assert(s.fire().ok);assert.equal(s.player.torpedoes,7);assert.equal(s.fire().ok,false);tick(s,40);assert.equal(s.targetSunk,1);assert.equal(s.status,'playing');assert(s.logs.some(l=>l.text.includes('撤离区')));s.player.x=s.mission.extract.x;s.player.z=s.mission.extract.z;s.step(.05);assert.equal(s.status,'won')});
test('攻击潜艇任务完整通关',()=>{const s=new Simulation('hunter');s.start();s.ping();s.select('S01');s.fire();tick(s,10);s.select('S02');s.fire();tick(s,60);assert.equal(s.status,'won');assert.equal(s.targetSunk,2)});
test('全部弹药耗尽且无在航鱼雷时给出失败原因',()=>{const s=new Simulation();s.start();s.player.torpedoes=0;s.step(.05);assert.equal(s.status,'lost');assert.match(s.result.reason,/鱼雷已用尽/)});
test('最后一枚在航鱼雷不会触发提前失败',()=>{const s=new Simulation();s.start();s.player.torpedoes=1;s.ping();s.select('S02');s.fire();s.step(.05);assert.equal(s.status,'playing');tick(s,35);assert.equal(s.targetSunk,1);assert.equal(s.status,'playing')});
test('诱饵吸引来袭鱼雷并保护已离开的潜艇',()=>{const s=new Simulation();s.start();s.player.desiredSpeed=0;s.deployDecoy();s.player.x=70;s.torpedoes.push({id:100,x:0,z:-90,depth:120,heading:180,target:'player',hostile:true,life:30,trail:[]});tick(s,10);assert.equal(s.player.hull,100);assert(s.logs.some(l=>l.text.includes('成功截获')))});
test('跨越温跃层和静默使警戒下降',()=>{const s=new Simulation();s.start();s.player.depth=s.player.desiredDepth=230;s.player.exposure=70;s.toggleSilent();tick(s,30);assert(s.player.exposure<40);assert(!s.torpedoes.some(t=>t.hostile))});
test('隐蔽任务无弹药也能通过全部航路点',()=>{const s=new Simulation('passage');s.start();s.player.torpedoes=0;s.player.depth=s.player.desiredDepth=230;s.toggleSilent();for(const wp of s.mission.waypoints){s.player.x=wp.x;s.player.z=wp.z;s.step(.05)}assert.equal(s.status,'won')});
test('危险潜深造成损伤、损管消耗电量',()=>{const s=new Simulation();s.start();s.player.depth=s.player.desiredDepth=360;tick(s,20);assert(s.player.hull<100);const b=s.player.battery;assert(s.repair().ok);assert.equal(s.player.hull,100);assert.equal(s.player.battery,b-15)});
test('存档保留任务状态并以暂停方式恢复',()=>{const s=new Simulation('hunter');s.start();s.ping();s.select('S01');s.fire();tick(s,3);const restored=Simulation.restore(s.save());assert.equal(restored.status,'paused');assert.equal(restored.mission.id,'hunter');assert.equal(restored.player.torpedoes,7);assert.equal(restored.torpedoes.length,1);assert.equal(restored.time,s.time);assert.throws(()=>Simulation.restore('{}'))});
console.log(`${tests.length} 项核心玩法检查通过：\n`+tests.map(n=>'✓ '+n).join('\n'));
