import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s);
const names={iron:'铁矿',crystal:'晶体',fiber:'纤维',ice:'冰矿',alloy:'合金',food:'口粮',water:'饮用水',oxygen:'氧气罐'};
const icons={iron:'⬡',crystal:'◈',fiber:'♧',ice:'❖',alloy:'▱',food:'◉',water:'◍',oxygen:'◎'};
const recipes=[
{id:'shelter',name:'紧急避难舱',icon:'⌂',desc:'抵御沙暴，恢复体温与氧气。每一段旅程都需要归处。',cost:{iron:12,fiber:6},type:'build'},
{id:'solar',name:'太阳能阵列',icon:'▥',desc:'白昼发电，为生命维持和信标提供能源。',cost:{iron:8,crystal:4},type:'build'},
{id:'extractor',name:'冰矿提取器',icon:'♧',desc:'自动凝结水分，每 30 秒生产一份饮用水。',cost:{iron:10,crystal:3},type:'build'},
{id:'garden',name:'生态种植舱',icon:'♧',desc:'培育异星植物，每 30 秒生产一份口粮。',cost:{iron:8,fiber:10,ice:4},type:'build'},
{id:'beacon',name:'深空通讯信标',icon:'⚑',desc:'需要避难舱和太阳能阵列。连接家园，完成生存协议。',cost:{alloy:6,crystal:10,iron:12},type:'build'},
{id:'lamp',name:'勘探照明灯',icon:'☼',desc:'照亮异星长夜，为前哨站增添温暖。',cost:{iron:3,crystal:1},type:'build'},
{id:'alloy',name:'精炼合金 ×2',icon:'▱',desc:'精炼铁矿与晶体，用于高级结构。',cost:{iron:4,crystal:1},give:2,type:'craft'},
{id:'water',name:'净化饮用水',icon:'◍',desc:'融化并过滤冰矿。使用后恢复 38 点水分。',cost:{ice:3},give:1,type:'craft'},
{id:'food',name:'压缩口粮',icon:'◉',desc:'提取可食用的植物纤维。恢复 35 点饱食度。',cost:{fiber:4},give:1,type:'craft'},
{id:'oxygen',name:'应急氧气罐',icon:'◎',desc:'从冰矿中电解氧气，恢复 50 点氧气。',cost:{ice:4,crystal:1},give:1,type:'craft'},
{id:'tool',name:'等离子采集器升级',icon:'⚒',desc:'永久提高采集效率，每次采集额外获得 2 份资源。',cost:{alloy:3,crystal:5},type:'craft'}
];
let saved;try{saved=JSON.parse(localStorage.getItem('outpost-echo-v1'))}catch{}
const state=Object.assign({inv:{iron:8,crystal:2,fiber:3,ice:3,alloy:0,food:2,water:2,oxygen:1},stats:{health:100,oxygen:94,food:86,water:82},time:0,x:0,z:4,buildings:[],harvested:0,upgraded:false,won:false},saved||{});
let paused=false,drawer=null,placing=null,ghost=null,rotation=0,nearest=null,scanUntil=0,harvestCooldown=0,storm=false,dead=false,autoSave=0,produce=0;
const keys={};const scene=new THREE.Scene();scene.background=new THREE.Color('#7f9d9b');scene.fog=new THREE.FogExp2('#849d98',.008);
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,600);let yaw=.58,pitch=.68,distance=33;const cameraTarget=new THREE.Vector3(0,0,0);
const ambient=new THREE.HemisphereLight('#d6efdf','#654a43',2.4);scene.add(ambient);const sun=new THREE.DirectionalLight('#ffe3b4',3.8);sun.position.set(-25,45,-20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:140});sun.shadow.bias=-.001;scene.add(sun);
const mats={sand:mat('#b59c7c'),rock:mat('#716d60'),rock2:mat('#918475'),white:mat('#e4e4cd'),trim:mat('#536c68'),dark:mat('#253a3c'),orange:mat('#c96e40'),crystal:mat('#74d3bd',.25,.35),fiber:mat('#527767'),ice:mat('#b7dce0',.22,.2),solar:mat('#234c60',.23,.5),glow: new THREE.MeshStandardMaterial({color:'#a5f5dc',emissive:'#66d9bf',emissiveIntensity:1.7})};
function mat(color,roughness=.88,metalness=.05){return new THREE.MeshStandardMaterial({color,roughness,metalness,flatShading:true})}
function mesh(geometry,material,parent=scene,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(parent,w,h,d,material,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),material,parent,x,y,z)}
function cyl(parent,r1,r2,h,material,x=0,y=0,z=0,n=8){return mesh(new THREE.CylinderGeometry(r1,r2,h,n),material,parent,x,y,z)}
let seed=83;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
function height(x,z){return Math.sin(x*.075)*Math.cos(z*.06)*.7+Math.sin(x*.22+z*.09)*.21}
const terrainGeometry=new THREE.PlaneGeometry(340,340,140,140);terrainGeometry.rotateX(-Math.PI/2);const pos=terrainGeometry.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,height(pos.getX(i),pos.getZ(i)));terrainGeometry.computeVertexNormals();const terrain=mesh(terrainGeometry,mats.sand);terrain.castShadow=false;
// Distant sculpted ridges and layered mesas.
for(let i=0;i<62;i++){const a=i/62*Math.PI*2,r=92+random()*64,x=Math.cos(a)*r,z=Math.sin(a)*r;const h=7+random()*26;const mountain=cyl(scene,2+random()*8,9+random()*12,h,mat(i%3===0?'#7e8175':'#938777'),x,h/2-2,z,5+Math.floor(random()*3));mountain.rotation.y=random()*4;}
for(let i=0;i<220;i++){let x=(random()-.5)*150,z=(random()-.5)*150;if(Math.hypot(x,z)<8)continue;const s=.12+random()*.55;const r=mesh(new THREE.DodecahedronGeometry(s,0),i%3===0?mats.rock2:mats.rock,scene,x,height(x,z)+s*.35,z);r.scale.set(1.6,.7,1);r.rotation.set(random(),random()*5,random());}
// Landing pad and damaged descent module.
const base=new THREE.Group();base.position.set(-5,height(-5,-5),-5);scene.add(base);cyl(base,3.7,3.9,.18,mats.trim,0,.05,0,12);cyl(base,2.1,2.5,.22,mats.dark,0,.2,0,8);cyl(base,1.35,1.85,1.2,mats.white,0,.95,0,8);cyl(base,1.12,1.35,1.7,mats.white,0,2.3,0,8);cyl(base,.5,1.15,.8,mats.trim,0,3.55,0,8);box(base,1.25,.72,.11,mats.dark,0,2.6,1.25);box(base,1.32,.1,.13,mats.orange,0,2.08,1.29);for(let i=0;i<4;i++){const a=i*Math.PI/2+.75;const leg=box(base,.22,1.8,.22,mats.trim,Math.sin(a)*1.9,.9,Math.cos(a)*1.9);leg.rotation.z=Math.cos(a)*.5;leg.rotation.x=-Math.sin(a)*.5;cyl(base,.5,.5,.1,mats.dark,Math.sin(a)*2.3,.1,Math.cos(a)*2.3)}box(base,.13,2,.13,mats.dark,.6,4.1,0);mesh(new THREE.SphereGeometry(.14),mats.glow,base,.6,5.1,0);
const crates=new THREE.Group();crates.position.set(-1.6,height(-1.6,-4),-4);scene.add(crates);for(let i=0;i<3;i++){let b=box(crates,.7,.55,.6,i===1?mats.orange:mats.white,i*.83,.28,0);box(b,.74,.1,.62,mats.trim,0,.08,0)}
const resources=[];
function addResource(type,x,z,index){let g=new THREE.Group();g.position.set(x,height(x,z),z);scene.add(g);if(type==='fiber'){for(let i=0;i<5;i++){const a=random()*6.28;let stem=cyl(g,.03,.1,.8+random(),mats.fiber,Math.sin(a)*.35,.55,Math.cos(a)*.35,5);stem.rotation.z=(random()-.5)*.6;const leaf=mesh(new THREE.OctahedronGeometry(.4),mat(i%2?'#98aa79':'#648b77'),g,stem.position.x,1+random()*.3,stem.position.z);leaf.scale.set(.5,1.4,.5)}}else if(type==='crystal'||type==='ice'){for(let i=0;i<4;i++){const s=.4+random()*.6;const c=cyl(g,0,s*.45,s*2,type==='ice'?mats.ice:mats.crystal,(random()-.5),s*.85,(random()-.5),5);c.rotation.z=(random()-.5)*.55;}cyl(g,.65,.8,.18,mats.rock,0,.1,0)}else{for(let i=0;i<3;i++){const c=mesh(new THREE.DodecahedronGeometry(.55+random()*.4),mats.rock,g,(random()-.5)*.8,.35,(random()-.5)*.8);c.scale.y=.7;mesh(new THREE.OctahedronGeometry(.18),mats.orange,g,c.position.x,.8,c.position.z)}}const r={type,x,z,group:g,left:4,respawn:0,id:index};resources.push(r);}
const types=['iron','crystal','fiber','ice'];for(let i=0;i<100;i++){let a=random()*6.28,r=9+random()*62;addResource(types[i%4],Math.sin(a)*r,Math.cos(a)*r,i)}
addResource('iron',4,3,100);addResource('fiber',-3,7,101);addResource('crystal',7,-3,102);addResource('ice',-8,5,103);
// Small survey rover.
const rover=new THREE.Group();rover.position.set(5,height(5,-6),-6);rover.rotation.y=-.4;scene.add(rover);box(rover,1.7,.45,2.1,mats.white,0,.7,0);box(rover,1.2,.18,1.2,mats.solar,0,1.02,-.25);for(let x of [-1,1])for(let z of [-.7,.7]){let wheel=cyl(rover,.35,.35,.3,mats.dark,x,.35,z);wheel.rotation.z=Math.PI/2}box(rover,.07,1.4,.07,mats.trim,.4,1.3,.6);box(rover,.4,.2,.2,mats.orange,.4,2,.6);
const player=new THREE.Group();scene.add(player);player.position.set(state.x,0,state.z);const body=new THREE.Group();player.add(body);const torso=box(body,.65,.75,.4,mats.white,0,1.2,0);box(body,.46,.42,.25,mats.trim,0,1.2,-.3);box(body,.43,.18,.05,mats.orange,0,1.3,.23);const helmet=mesh(new THREE.SphereGeometry(.39,12,10),mats.white,body,0,1.88,0);const visor=mesh(new THREE.SphereGeometry(.33,12,8,0,Math.PI*2,0,Math.PI/2),mat('#162f39',.15,.6),body,0,1.9,.1);visor.rotation.x=Math.PI/2;box(body,.7,.08,.45,mats.orange,0,.93,0);const arms=[];const legs=[];for(let side of [-1,1]){let arm=box(body,.2,.7,.23,mats.white,side*.45,1.13,0);arms.push(arm);box(arm,.23,.17,.26,mats.trim,0,-.28,0);let leg=box(body,.25,.65,.28,mats.white,side*.2,.54,0);legs.push(leg);box(leg,.28,.19,.4,mats.dark,0,-.28,.06)}const tool=box(arms[1],.13,.13,.62,mats.trim,0,-.25,.22);box(tool,.25,.22,.17,mats.glow,0,0,.32);
const buildings=[];
function createBuilding(type,x,z,rot=0,preview=false){const g=new THREE.Group();g.position.set(x,height(x,z),z);g.rotation.y=rot;const lit=[];
if(type==='shelter'){box(g,4.7,.24,4.3,mats.trim,0,.18,0);for(let x of [-1.8,1.8])for(let z of [-1.6,1.6])cyl(g,.13,.2,.7,mats.dark,x,0,z);box(g,4,2.2,3.5,mats.white,0,1.35,0);for(const side of [-1,1]){const roof=box(g,4.2,.16,1.95,mats.white,0,2.58,side*.9);roof.rotation.x=side*.24;}box(g,4.1,.17,3.6,mats.orange,0,2.3,0);box(g,1.05,1.65,.08,mats.dark,.7,1.13,1.79);box(g,.07,1.65,.12,mats.glow,.13,1.13,1.86);box(g,1.2,.65,.1,mats.solar,-1,1.65,1.79);box(g,1.4,.12,.9,mats.trim,.7,.32,2.15);box(g,1.6,.15,.65,mats.white,.7,.12,2.8);cyl(g,.24,.24,2.4,mats.trim,-2.2,1.2,-.8);cyl(g,.24,.24,2.4,mats.trim,-2.2,1.2,0);}
if(type==='solar'){const panel=new THREE.Group();panel.position.y=1.65;panel.rotation.x=-.3;g.add(panel);box(panel,4.05,.13,2.65,mats.trim,0,-.08,0);box(panel,3.9,.09,2.5,mats.solar);for(let x=-1.9;x<=1.9;x+=.48)box(panel,.025,.015,2.5,mats.white,x,.052,0);for(let z=-1.2;z<=1.2;z+=.4)box(panel,3.9,.015,.02,mats.trim,0,.053,z);for(let x of [-1.3,1.3])cyl(g,.08,.13,1.6,mats.trim,x,.8,0);box(g,.6,.5,.6,mats.white,0,.3,0)}
if(type==='extractor'){cyl(g,.8,1.1,.3,mats.trim,0,.15,0);cyl(g,.65,.65,1.7,mats.white,0,1.15,0);cyl(g,.7,.7,.18,mats.orange,0,1.3,0);cyl(g,.2,.4,1.8,mats.trim,0,2.3,0);cyl(g,1.5,.2,.5,mats.white,0,3.2,0);box(g,.5,.6,.1,mats.glow,0,1.3,.66)}
if(type==='garden'){box(g,3.4,.5,2.5,mats.white,0,.3,0);box(g,3.1,.1,2.2,mats.dark,0,.58,0);for(let x=-1;x<=1;x++)for(let z of [-.6,.6]){cyl(g,.04,.07,.7,mats.fiber,x,.95,z);mesh(new THREE.OctahedronGeometry(.35),mats.fiber,g,x,1.3,z)}const glass=new THREE.MeshStandardMaterial({color:'#a3ded0',transparent:true,opacity:.22,roughness:.2,side:THREE.DoubleSide});const dome=mesh(new THREE.SphereGeometry(1.8,16,8,0,Math.PI*2,0,Math.PI/2),glass,g,0,.6,0);dome.scale.z=.75;}
if(type==='beacon'){cyl(g,1.4,1.6,.3,mats.trim,0,.15,0);cyl(g,.4,.8,2,mats.white,0,1.3,0);cyl(g,.1,.22,4,mats.trim,0,3.2,0);let dish=cyl(g,1.2,.1,.5,mats.white,0,4.4,0,16);dish.rotation.z=.5;mesh(new THREE.SphereGeometry(.17),mats.glow,g,0,5.3,0);for(let a=0;a<6.3;a+=2.1){let support=box(g,.1,3,.1,mats.orange,Math.cos(a)*.6,1.8,Math.sin(a)*.6);support.rotation.z=Math.cos(a)*.3;support.rotation.x=Math.sin(a)*.3}}
if(type==='lamp'){cyl(g,.4,.5,.15,mats.trim,0,.1,0);cyl(g,.05,.08,3,mats.trim,0,1.6,0);box(g,.8,.15,.5,mats.white,0,3.1,0);box(g,.65,.08,.4,mats.glow,0,3,0);const light=new THREE.PointLight('#c3ffdc',9,12,2);light.position.set(0,2.8,0);g.add(light)}
scene.add(g);if(preview){g.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.4;o.castShadow=false}})}else buildings.push({type,x,z,rot,group:g});return g}
for(const b of state.buildings)createBuilding(b.type,b.x,b.z,b.rot);
const dustGeometry=new THREE.BufferGeometry();const dustPositions=new Float32Array(600*3);for(let i=0;i<dustPositions.length;i+=3){dustPositions[i]=(random()-.5)*140;dustPositions[i+1]=random()*18;dustPositions[i+2]=(random()-.5)*140}dustGeometry.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({color:'#e0d4b5',size:.045,transparent:true,opacity:.5}));scene.add(dust);
const ring=mesh(new THREE.RingGeometry(.9,1,48),new THREE.MeshBasicMaterial({color:'#b4eed8',transparent:true,opacity:.8,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.visible=false;
const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();let mouseDown=null,lastPointer=null,dragging=false;
function groundAt(event){pointer.set(event.clientX/innerWidth*2-1,-event.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObject(terrain)[0]?.point}
renderer.domElement.addEventListener('pointerdown',e=>{mouseDown={x:e.clientX,y:e.clientY};lastPointer={x:e.clientX,y:e.clientY};dragging=false;renderer.domElement.setPointerCapture(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(mouseDown){const dx=e.clientX-lastPointer.x,dy=e.clientY-lastPointer.y;if(Math.hypot(e.clientX-mouseDown.x,e.clientY-mouseDown.y)>4)dragging=true;if(dragging&&!placing){yaw-=dx*.006;pitch=THREE.MathUtils.clamp(pitch+dy*.004,.3,1.2)}lastPointer={x:e.clientX,y:e.clientY}}if(placing&&ghost){const p=groundAt(e);if(p){ghost.position.copy(p);ghost.rotation.y=rotation;}}});
renderer.domElement.addEventListener('pointerup',e=>{if(!dragging&&placing){const p=groundAt(e);if(p)placeBuilding(p)}mouseDown=null;lastPointer=null});
renderer.domElement.addEventListener('wheel',e=>{distance=THREE.MathUtils.clamp(distance+e.deltaY*.018,12,58)},{passive:true});
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('#toast-stack').append(el);setTimeout(()=>el.remove(),3600)}
function canAfford(cost){return Object.entries(cost).every(([k,v])=>(state.inv[k]||0)>=v)}
function spend(cost){for(const[k,v]of Object.entries(cost))state.inv[k]-=v}
function costText(cost){return Object.entries(cost).map(([k,v])=>`${names[k]} ${state.inv[k]||0}/${v}`).join(' · ')}
function closeDrawer(){$('#drawer').classList.add('hidden');drawer=null;document.querySelectorAll('.slot').forEach(b=>b.classList.toggle('active',b.dataset.action==='tool'))}
function openDrawer(type){if(drawer===type){closeDrawer();return}cancelBuild();drawer=type;renderDrawer();$('#drawer').classList.remove('hidden');document.querySelectorAll('.slot').forEach(b=>b.classList.toggle('active',b.dataset.action===type))}
function renderDrawer(){const titles={build:['前哨站蓝图','将荒野变成家园。选择蓝图，在身边的空地放置建筑。'],craft:['便携制造终端','把发现变成可能。消耗原料，制造生存物资与装备。'],inventory:['旅行者的行囊','每一份资源，都让你离家更近一步。点击补给立即使用。']};let html=`<div class="drawer-head"><h2>${titles[drawer][0]}</h2><button class="close" aria-label="关闭">×</button></div><p class="drawer-intro">${titles[drawer][1]}</p>`;if(drawer==='inventory'){html+='<div class="inventory-grid">'+Object.entries(names).map(([k,v])=>`<div class="inventory-item"><span>${icons[k]}</span>${v}<b>${state.inv[k]||0}</b>${['food','water','oxygen'].includes(k)?`<button class="primary use" data-id="${k}" style="margin-top:14px;padding:7px 12px" ${(state.inv[k]||0)<1?'disabled':''}>使用</button>`:''}</div>`).join('')+'</div>'}else html+=recipes.filter(r=>r.type===drawer).map(r=>`<button class="recipe" data-id="${r.id}"><span class="recipe-icon">${r.icon}</span><div><span class="tag">${r.id==='tool'&&state.upgraded?'已升级':canAfford(r.cost)?'可制作':'资源不足'}</span><h3>${r.name}</h3><p>${r.desc}</p><span class="cost ${canAfford(r.cost)?'':'lack'}">${costText(r.cost)}</span></div></button>`).join('');$('#drawer').innerHTML=html;$('.close').onclick=closeDrawer;document.querySelectorAll('.recipe').forEach(b=>b.onclick=()=>selectRecipe(b.dataset.id));document.querySelectorAll('.use').forEach(b=>b.onclick=()=>useItem(b.dataset.id))}
function selectRecipe(id){const recipe=recipes.find(r=>r.id===id);if(!canAfford(recipe.cost)){toast('资源不足：'+costText(recipe.cost),true);return}if(id==='tool'&&state.upgraded){toast('采集器已经升级');return}if(id==='beacon'&&(!has('shelter')||!has('solar'))){toast('请先建造避难舱与太阳能阵列',true);return}if(recipe.type==='build'){closeDrawer();placing=recipe;ghost=createBuilding(id,player.position.x+4,player.position.z,rotation,true);$('#build-hint').classList.remove('hidden');$('#build-name').textContent=recipe.name;toast('选择附近的空地，点击放置建筑');}else{spend(recipe.cost);if(id==='tool')state.upgraded=true;else state.inv[id]=(state.inv[id]||0)+recipe.give;toast('制造完成 · '+recipe.name);updateUI();renderDrawer();save()}}
function cancelBuild(){placing=null;if(ghost){scene.remove(ghost);ghost.traverse(o=>{if(o.isMesh)o.material.dispose()});ghost=null}$('#build-hint').classList.add('hidden')}
function placeBuilding(p){if(paused||dead)return;if(Math.hypot(p.x-player.position.x,p.z-player.position.z)>14){toast('建造位置太远，请在 14 米以内放置',true);return}if(Math.hypot(p.x+5,p.z+5)<6||buildings.some(b=>Math.hypot(p.x-b.x,p.z-b.z)<4.8)||resources.some(r=>r.group.visible&&Math.hypot(p.x-r.x,p.z-r.z)<2.1)){toast('此处空间不足，请选择一片空地',true);return}if(!canAfford(placing.cost)){toast('资源不足',true);return}const recipe=placing;spend(recipe.cost);createBuilding(recipe.id,p.x,p.z,rotation);cancelBuild();toast('建造完成 · '+recipe.name);if(recipe.id==='beacon'){state.won=true;showModal('signal')}updateUI();save()}
function has(type){return buildings.some(b=>b.type===type)}
function useItem(id){if(!state.inv[id])return;const gains={food:35,water:38,oxygen:50};if(state.stats[id]>=99){toast('当前状态良好，无需补充');return}state.inv[id]--;state.stats[id]=Math.min(100,state.stats[id]+gains[id]);toast(`已使用${names[id]} · +${gains[id]}`);updateUI();if(drawer)renderDrawer();save()}
function harvest(){if(paused||dead||placing||performance.now()<harvestCooldown)return;if(!nearest){toast('靠近矿石、晶体或植物后按 E 采集');return}if(nearest.kind==='base'){state.stats.oxygen=Math.min(100,state.stats.oxygen+30);toast('着陆舱氧气补充完成');harvestCooldown=performance.now()+3000;return}const amount=(state.upgraded?5:3);state.inv[nearest.type]=(state.inv[nearest.type]||0)+amount;state.harvested+=amount;nearest.left--;nearest.group.scale.setScalar(.85);const harvestedGroup=nearest.group;setTimeout(()=>harvestedGroup.scale.setScalar(1),150);if(nearest.left<=0){nearest.group.visible=false;nearest.respawn=state.time+120}toast(`+${amount} ${names[nearest.type]} · 已存入背包`);harvestCooldown=performance.now()+650;arms[1].rotation.x=-1.1;setTimeout(()=>arms[1].rotation.x=0,250);updateUI();if(drawer)renderDrawer()}
function scan(){if(paused||dead)return;scanUntil=state.time+15;toast('扫描完成 · 附近资源已标记 15 秒')}
const objectives=[()=>[state.harvested>=12,'采集基础资源',`${Math.min(12,state.harvested)} / 12`],()=>[has('shelter'),'建造紧急避难舱',has('shelter')?'1 / 1':'0 / 1'],()=>[has('solar'),'部署太阳能阵列',has('solar')?'1 / 1':'0 / 1'],()=>[has('beacon'),'建立深空通讯',has('beacon')?'1 / 1':'0 / 1']];
function updateUI(){$('#objectives').innerHTML=objectives.map(f=>{const[done,title,count]=f();return `<div class="objective ${done?'done':''}"><span class="check">${done?'✓':''}</span><span>${title}</span><span class="count">${count}</span></div>`}).join('');$('#resource-strip').innerHTML=['iron','crystal','fiber','ice','alloy','food'].map(k=>`<div class="resource"><span>${icons[k]}</span><div><b>${state.inv[k]||0}</b><small>${names[k]}</small></div></div>`).join('');$('#level').textContent=1+Math.floor(state.harvested/40)+buildings.length;updateVitals();if(state.won){$('#mission-title').textContent='信号已抵达，旅程仍继续';$('#mission-status').textContent='救援信号已发送 · 继续扩建你的异星家园'}}
function updateVitals(){const statNames={health:'生命',oxygen:'氧气',food:'饱食',water:'水分'};$('#vital-bars').innerHTML=Object.entries(statNames).map(([k,v])=>`<div class="vital"><label>${v}</label><div class="bar"><i style="width:${state.stats[k]}%;background:${state.stats[k]<25?'#ec936e':k==='oxygen'?'#9ecbd2':k==='food'?'#c7c594':'#b4eed8'}"></i></div><b>${Math.ceil(state.stats[k])}</b></div>`).join('')}
function save(){state.x=player.position.x;state.z=player.position.z;state.buildings=buildings.map(({type,x,z,rot})=>({type,x,z,rot}));try{localStorage.setItem('outpost-echo-v1',JSON.stringify(state));$('#save-label').textContent='已保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}catch{$('#save-label').textContent='存档不可用 · 浏览器存储受限'}}
function showModal(type){paused=true;const content={help:`<span class="eyebrow">FIELD GUIDE / 生存手册</span><h2>你好，旅行者。</h2><p>你的着陆舱停在一颗无名星球。采集散落的资源，建立避难所，制造合金，最终点亮深空通讯信标。</p><div class="help-grid"><span><kbd>WASD / ↑↓←→</kbd> 移动</span><span><kbd>SHIFT</kbd> 奔跑</span><span><kbd>E</kbd> 采集 / 着陆舱补氧</span><span><kbd>B</kbd> 建造蓝图</span><span><kbd>C</kbd> 制造物资</span><span><kbd>I</kbd> 背包 / 使用补给</span><span><kbd>F</kbd> 扫描周围资源</span><span><kbd>R</kbd> 旋转建筑</span><span><kbd>ESC</kbd> 取消 / 暂停</span><span>拖动视角 · 滚轮缩放</span></div><p>靠近避难舱可持续恢复氧气与生命；太阳能增强恢复效率。沙暴时尽快回到避难舱。用冰矿制水、用纤维制造食物。进度每 15 秒自动保存。</p>`,pause:`<span class="eyebrow">MISSION ON HOLD</span><h2>宇宙可以等一会儿。</h2><p>游戏已暂停，生命维持与风暴计时已停止。你的探索进度已保存在此浏览器。</p>`,signal:`<span class="eyebrow">TRANSMISSION SUCCESSFUL</span><h2>有人听见了你的声音。</h2><p>深空信标已上线。穿过漫长的星际寂静，一条回音终于抵达：<br>「我们收到你的坐标了，旅行者。」<br>生存协议完成。你可以继续探索、制造、扩建这个属于你的前哨站。</p>`,dead:`<span class="eyebrow">EMERGENCY RECOVERY</span><h2>生命维持系统已离线。</h2><p>着陆舱已记录你最后的生命信号。启动应急复苏后，返回着陆点，保留建筑与资源。</p>`};$('#modal').innerHTML=`<div class="modal-card">${content[type]}<button class="primary" id="resume">${type==='dead'?'启动应急复苏':type==='help'?'继续探索 →':'返回星球 →'}</button>${type==='pause'?'<button class="secondary" id="manual-save">保存进度</button>':''}</div>`;$('#modal').classList.remove('hidden');$('#resume').onclick=()=>{if(dead){dead=false;state.stats={health:100,oxygen:100,food:70,water:70};player.position.set(0,0,4);save()}paused=false;$('#modal').classList.add('hidden')};if($('#manual-save'))$('#manual-save').onclick=()=>{save();toast('探索进度已保存')}}
$('#help-btn').onclick=()=>showModal('help');$('#pause-btn').onclick=()=>{save();showModal('pause')};document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='tool'){closeDrawer();cancelBuild()}else if(a==='scan')scan();else openDrawer(a)});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'){if(placing)cancelBuild();else if(drawer)closeDrawer();else if(paused&&!dead){paused=false;$('#modal').classList.add('hidden')}else showModal('pause');return}if(paused)return;const actions={KeyE:harvest,KeyB:()=>openDrawer('build'),KeyC:()=>openDrawer('craft'),KeyI:()=>openDrawer('inventory'),KeyF:scan,Digit1:()=>{cancelBuild();closeDrawer()},KeyR:()=>{rotation+=Math.PI/2;if(ghost)ghost.rotation.y=rotation}};actions[e.code]?.()});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false)});window.addEventListener('beforeunload',save);
function updateMap(){const c=$('#minimap').getContext('2d');const w=190,h=150;c.clearRect(0,0,w,h);c.save();c.translate(w/2,h/2);c.strokeStyle='#8db7a61b';c.lineWidth=1;for(let r=25;r<100;r+=25){c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.stroke()}c.beginPath();c.moveTo(-95,0);c.lineTo(95,0);c.moveTo(0,-75);c.lineTo(0,75);c.stroke();const factor=1.6;for(const r of resources){if(!r.group.visible)continue;const x=(r.x-player.position.x)*factor,z=(r.z-player.position.z)*factor;if(Math.abs(x)>90||Math.abs(z)>70)continue;c.fillStyle=r.type==='crystal'?'#a0e1d1':r.type==='ice'?'#9bbfcc':r.type==='fiber'?'#a2aa78':'#ba9982';c.fillRect(x-1.5,z-1.5,3,3)}for(const b of [...buildings,{x:-5,z:-5}]){c.strokeStyle='#dde6c6';c.strokeRect((b.x-player.position.x)*factor-3,(b.z-player.position.z)*factor-3,6,6)}c.rotate(-player.rotation.y);c.fillStyle='#c5f6de';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,5);c.lineTo(0,3);c.lineTo(4,5);c.closePath();c.fill();c.restore();c.fillStyle='#a3c1b4';c.font='8px monospace';c.fillText('N',92,11)}
function updateLabels(){const list=[];const baseP=new THREE.Vector3(-5,5.8,-5);list.push({p:baseP,text:'⌂ 着陆舱 · 氧气补给'});if(scanUntil>state.time){for(const r of resources){if(r.group.visible&&Math.hypot(r.x-player.position.x,r.z-player.position.z)<25)list.push({p:r.group.position.clone().add(new THREE.Vector3(0,2,0)),text:icons[r.type]+' '+names[r.type]})}}for(const b of buildings){if(Math.hypot(b.x-player.position.x,b.z-player.position.z)<25)list.push({p:b.group.position.clone().add(new THREE.Vector3(0,b.type==='beacon'?6:4,0)),text:recipes.find(r=>r.id===b.type).name})}$('#world-labels').innerHTML=list.map(({p,text})=>{p.project(camera);if(p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1)return'';return `<div class="world-label" style="left:${(p.x*.5+.5)*innerWidth}px;top:${(-p.y*.5+.5)*innerHeight}px">${text}</div>`}).join('')}
let last=performance.now(),uiTime=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!dead){state.time+=dt;const forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);const run=keys.ShiftLeft||keys.ShiftRight;let moving=forward||side;if(moving){const angle=Math.atan2(-side,forward);const vx=Math.sin(yaw+angle),vz=Math.cos(yaw+angle);const speed=run?6:3.4;let nx=THREE.MathUtils.clamp(player.position.x-vx*speed*dt,-78,78),nz=THREE.MathUtils.clamp(player.position.z-vz*speed*dt,-78,78);const blocked=Math.hypot(nx+5,nz+5)<2.4||buildings.some(b=>b.type==='shelter'&&Math.abs(nx-b.x)<2.1&&Math.abs(nz-b.z)<1.8);if(!blocked){player.position.x=nx;player.position.z=nz}player.rotation.y=Math.atan2(-vx,-vz);legs.forEach((l,i)=>l.rotation.x=Math.sin(now*.012*(run?1.5:1)+i*Math.PI)*.45);arms.forEach((l,i)=>l.rotation.x=Math.sin(now*.012+i*Math.PI+Math.PI)*.3);body.position.y=Math.abs(Math.sin(now*.012))*.045;}else{legs.forEach(l=>l.rotation.x=0);body.position.y=0}
player.position.y=height(player.position.x,player.position.z)+.06;const shelter=buildings.some(b=>b.type==='shelter'&&Math.hypot(player.position.x-b.x,player.position.z-b.z)<5.8);const atBase=Math.hypot(player.position.x+5,player.position.z+5)<4.8;const isStorm=state.time%300>=240;if(isStorm!==storm){storm=isStorm;toast(storm?'警告：离子风暴抵达，立即返回避难舱！':'风暴已离开 · 地表恢复安全',storm);$('#storm-overlay').style.opacity=storm?1:0}
const stats=state.stats;stats.oxygen=THREE.MathUtils.clamp(stats.oxygen+dt*(shelter?(has('solar')?3:1.6):atBase?1:-(run&&moving?.18:.09)*(storm?2.5:1)),0,100);stats.food=Math.max(0,stats.food-dt*.035);stats.water=Math.max(0,stats.water-dt*(run&&moving?.09:.05));if(storm&&!shelter)stats.health=Math.max(0,stats.health-dt*.4);if(stats.oxygen<=0||stats.food<=0||stats.water<=0)stats.health=Math.max(0,stats.health-dt*1.8);else if(shelter)stats.health=Math.min(100,stats.health+dt*.5);$('#safety').textContent=shelter?'避难舱范围 · 生命维持恢复中':storm?'离子风暴 · 请立即寻找掩护':'太空服生命维持正常';if(stats.health<=0){dead=true;showModal('dead')}
produce+=dt;if(produce>30){produce=0;const waters=buildings.filter(b=>b.type==='extractor').length;if(waters){state.inv.water+=waters;toast(`提取器生产完成 · +${waters} 饮用水`)}const foods=buildings.filter(b=>b.type==='garden').length;if(foods){state.inv.food+=foods;toast(`种植舱收获 · +${foods} 口粮`)}updateUI()}
nearest=null;let minDist=2.7;for(const r of resources){if(!r.group.visible&&state.time>r.respawn){r.left=4;r.group.visible=true;r.group.scale.setScalar(1)}if(!r.group.visible)continue;const d=Math.hypot(r.x-player.position.x,r.z-player.position.z);if(d<minDist){minDist=d;nearest=r}}if(!nearest&&atBase)nearest={kind:'base'};if(nearest&&!placing){$('#interaction').classList.remove('hidden');$('#interaction span').textContent=nearest.kind==='base'?'着陆舱 · 补充氧气':'采集'+names[nearest.type];$('#interaction small').textContent=nearest.kind==='base'?'安全补给点':state.upgraded?'等离子采集器 · +5':'地质采集器 · +3';ring.visible=nearest.kind!=='base';if(ring.visible)ring.position.set(nearest.x,height(nearest.x,nearest.z)+.05,nearest.z)}else{$('#interaction').classList.add('hidden');ring.visible=false}if(keys.KeyE)harvest();autoSave+=dt;if(autoSave>=15){save();autoSave=0}}
const phase=(state.time/600+.405)%1;const lightLevel=.25+Math.max(0,Math.sin((phase-.25)*Math.PI*2))* .75;ambient.intensity=.6+lightLevel*1.8;sun.intensity=lightLevel*3.8;scene.background.set(storm?'#8d9282':'#7f9d9b').multiplyScalar(.38+lightLevel*.62);scene.fog.color.copy(scene.background);scene.fog.density=storm?.025:.008;cameraTarget.lerp(new THREE.Vector3(player.position.x,1,player.position.z),.055);camera.position.set(cameraTarget.x+Math.sin(yaw)*Math.cos(pitch)*distance,cameraTarget.y+Math.sin(pitch)*distance,cameraTarget.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(cameraTarget);const dp=dust.geometry.attributes.position;for(let i=0;i<dp.count;i++){dp.setX(i,dp.getX(i)+dt*(storm?16:1.1));if(dp.getX(i)>70)dp.setX(i,-70)}dp.needsUpdate=true;dust.material.opacity=storm?.85:.35;dust.material.size=storm?.08:.045;renderer.render(scene,camera);uiTime+=dt;if(uiTime>.2){uiTime=0;updateVitals();updateMap();updateLabels();const day=1+Math.floor(state.time/600);const hours=Math.floor(phase*24),minutes=Math.floor(phase*24*60)%60;$('#clock').innerHTML=`SOL ${String(day).padStart(2,'0')} <small>${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}</small>`;$('#weather').textContent=storm?'离子风暴 · 危险':lightLevel<.4?'静谧夜晚 · 低温':'晴朗 · 能见度良好';$('#temp').textContent=`${Math.round(-38+lightLevel*23)}°C`;$('#day-progress').style.width=phase*100+'%';const remain=storm?300-state.time%300:240-state.time%300;$('#storm-info').textContent=storm?`风暴将在 ${Math.ceil(remain)} 秒后结束`:`下一场离子风暴预计 ${Math.floor(remain/60).toString().padStart(2,'0')}:${Math.floor(remain%60).toString().padStart(2,'0')} 后抵达`;$('#coords').textContent=`${(24.8+player.position.z*.01).toFixed(2)}° N · ${(68.2+player.position.x*.01).toFixed(2)}° E`;}}
updateUI();requestAnimationFrame(animate);setTimeout(()=>toast(saved?'欢迎回来，旅行者。已恢复上次探索进度。':'着陆成功 · WASD 移动，靠近资源按 E 采集 · 按 ? 查看手册'),1100);
// Read-only diagnostics for smoke checks.
window.__outpost={getState:()=>JSON.parse(JSON.stringify({...state,x:player.position.x,z:player.position.z,buildings:buildings.map(({type,x,z})=>({type,x,z}))})),getRenderer:()=>({triangles:renderer.info.render.triangles,calls:renderer.info.render.calls}),recipes};
