import { chromium } from '/Users/bytedance/.npm/_npx/31e32ef8478fbf80/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('output/playwright',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4267',{waitUntil:'networkidle'});await page.waitForTimeout(1500);
console.log('initial',await page.evaluate(()=>window.snowbowl?.snapshot()));console.log('ui',await page.locator('body').innerText());
await page.screenshot({path:'output/playwright/desktop.png'});
await page.keyboard.down('Space');await page.waitForTimeout(790);await page.keyboard.up('Space');await page.waitForTimeout(6900);
console.log('shot',await page.evaluate(()=>window.snowbowl?.snapshot()));await page.screenshot({path:'output/playwright/shot.png'});
await page.getByRole('button',{name:/继续投球|开始下一轮/}).click();console.log('next',await page.evaluate(()=>window.snowbowl?.snapshot()));
await page.locator('[data-mode="challenge"]').click();await page.getByRole('button',{name:'开启新比赛',exact:true}).click();await page.locator('[data-ball="burst"]').click();
console.log('challenge',await page.evaluate(()=>window.snowbowl?.snapshot()));
await page.keyboard.down('Space');await page.waitForTimeout(790);await page.keyboard.up('Space');await page.waitForTimeout(6900);
console.log('burst',await page.evaluate(()=>window.snowbowl?.snapshot()));
await page.locator('#next-shot').click();await page.locator('#help').click();console.log('help',await page.locator('#help-dialog').isVisible());await page.locator('[data-close="help-dialog"]').last().click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);await page.screenshot({path:'output/playwright/mobile.png'});
console.log('mobileOverflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));console.log('errors',errors);
await writeFile('output/playwright/qa-result.json',JSON.stringify({errors},null,2));await browser.close();
