import { createWorld, V } from './world.js';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let world;
try { world=createWorld($('#world')); } catch(error) { $('#loading').textContent='3D 画面无法启动，请启用浏览器硬件加速后重试。';$('#startBtn').disabled=true;console.error(error);throw error; }
const {whale,camera,shards,altars,foods,jellies,sonar,THREE}=world;
const SAVE='whalefall-save-v1';let saved=null;try{saved=JSON.parse(localStorage.getItem(SAVE));if(!saved||saved.version!==1||!Array.isArray(saved.shards)||!Array.isArray(saved.altars))saved=null;}catch{}
$('#continueBtn').hidden=!saved;$('#loading').textContent='海域已就绪 · 随时启航';
let state={playing:false,paused:false,health:100,energy:100,heading:0,speed:0,sonarCooldown:0,sonarAge:99,invincible:0,shards:0,altars:0,won:false,time:0,distance:0,scans:0,foods:0};
let keys={},time=0,last=performance.now(),saveClock=0,toastTimer,orbit=0,orbitPitch=0,drag=false,lastMouse={x:0,y:0},interactable=null,manualTarget=null,audio=null,soundOn=false;
let modalBeforeFocus=null;const isTouch=matchMedia('(pointer:coarse)').matches;
const stories=[['石之回声','这里曾是一座与鲸共生的城市。石柱上的涟漪纹路，记录着每一次迁徙的方向。'],['潮汐的刻度','潮汐并非日历，却替他们记住了时间。每一枚晶体都保存着一段早已失落的鲸歌。'],['最后的守望者','当城市沉入海底，守望者没有离开。他们点亮三座祭坛，等待鲸群再次归来。'],['归海之门','门的另一侧不是陆地，而是一片从未被遗忘的海。你的歌声，让它再次苏醒。']];
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function ping(freq=420,duration=.5){if(!soundOn||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,audio.currentTime+duration);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.09,audio.currentTime+.06);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function toggleSound(){soundOn=!soundOn;if(soundOn){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(!audio.bed){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=52;g.gain.value=.018;o.connect(g).connect(audio.destination);o.start();audio.bed=g;}audio.bed.gain.value=.018;ping(170,2);}catch{soundOn=false;notify('此浏览器暂不支持音效');}}else if(audio?.bed)audio.bed.gain.value=0;$('#soundBtn').style.color=soundOn?'#d7ffe0':'';$('#soundBtn').textContent=soundOn?'♫':'♪';$('#soundBtn').title=soundOn?'关闭海洋音效':'开启海洋音效';$('#soundBtn').setAttribute('aria-label',$('#soundBtn').title);}
$('#soundBtn').onclick=toggleSound;
function persist(){if(!state.playing)return;const data={version:1,shards:shards.filter(s=>s.collected).map(s=>s.id),altars:altars.filter(a=>a.active).map(a=>a.id),position:whale.position.toArray(),heading:state.heading,time:state.time,distance:state.distance,scans:state.scans,foods:state.foods,won:state.won};try{localStorage.setItem(SAVE,JSON.stringify(data));saved=data;}catch{} }
function start(resume=false){closeModal();Object.assign(state,{playing:true,paused:false,health:100,energy:100,heading:0,speed:0,sonarCooldown:0,sonarAge:99,invincible:4,shards:0,altars:0,won:false,time:0,distance:0,scans:0,foods:0});keys={};orbit=0;orbitPitch=0;manualTarget=null;whale.position.set(0,3,36);whale.rotation.set(0,0,0);
 shards.forEach(s=>{s.collected=false;s.group.visible=true;});altars.forEach(a=>activateAltar(a,false));foods.forEach(f=>{f.available=true;f.group.visible=true;});
 if(resume&&saved){shards.forEach(s=>{s.collected=saved.shards.includes(s.id);s.group.visible=!s.collected;});altars.forEach(a=>activateAltar(a,saved.altars.includes(a.id)));if(Array.isArray(saved.position)&&saved.position.length===3&&saved.position.every(Number.isFinite))whale.position.fromArray(saved.position);state.heading=Number.isFinite(saved.heading)?saved.heading:0;for(const k of ['time','distance','scans','foods'])state[k]=Number.isFinite(saved[k])?Math.max(0,saved[k]):0;state.won=!!saved.won;state.shards=shards.filter(s=>s.collected).length;state.altars=altars.filter(a=>a.active).length;}
 $('#landing').hidden=true;$('#scene-note').hidden=true;$('#landing-bottom').hidden=true;$('#hud').hidden=false;$('#mobile-controls').hidden=!isTouch;document.body.classList.add('playing');$('#pauseBtn').textContent='Ⅱ';camera.position.copy(whale.position).add(new V(0,8,24));updateQuest();persist();notify(resume?'欢迎回来，旅航者。深海仍记得你的歌声。':'用 W A S D 游动，靠近金色碎片自动收集；Q 释放鲸歌声呐。');}
$('#startBtn').onclick=()=>{if(saved)openPanel('new');else start();};$('#continueBtn').onclick=()=>start(true);
function activateAltar(a,active){a.active=active;a.crystal.material.color.set(active?'#99efc7':'#5d9ca3');a.crystal.material.emissive.set(active?'#43efbd':'#227477');a.crystal.material.emissiveIntensity=active?2:.6;a.light.intensity=active?14:0;}
function updateQuest(){const completed=state.shards===6,lit=state.altars===3;$('#chapter').textContent=state.won?'完成':lit?'03 / 03':completed?'02 / 03':'01 / 03';$('#questTitle').textContent=state.won?'海洋记得你的歌':lit?'穿越归海之门':completed?'唤醒三座祭坛':'寻找海洋的记忆';$('#questDesc').textContent=state.won?'继续漫游，聆听遗迹与生命的回响。':lit?'回到神殿，靠近光门并按 E，让鲸歌再次回响。':completed?'跟随青色信标，靠近祭坛后按 E 注入记忆。':'收集散落在遗迹周围的 6 枚记忆碎片。';$('#questProgress').textContent=lit?'◎':Array.from({length:completed?3:6},(_,i)=>i<(completed?state.altars:state.shards)?'◆':'◇').join(' ');$('#questNumber').textContent=lit?'已苏醒':`${completed?state.altars:state.shards} / ${completed?3:6}`;$('#guide').textContent=state.won?'旅程已保存 · 海洋探索无止境':'Q 声呐：定位碎片 · 驱散水母\n青色浮游生物可恢复生命与能量';$('#journalDot').classList.toggle('active',state.shards>0);}
function target(){if(manualTarget)return {position:manualTarget,name:'自定义航标'};if(state.won)return null;let list=state.shards<6?shards.filter(s=>!s.collected):state.altars<3?altars.filter(a=>!a.active):[];if(!list.length)return {position:new V(0,3,-24),name:'归海之门'};let closest=list.reduce((a,b)=>whale.position.distanceTo(a.group.position)<whale.position.distanceTo(b.group.position)?a:b);return {position:closest.group.position,name:state.shards<6?'记忆碎片':'共鸣祭坛'};}
function scan(){if(!state.playing||state.paused)return;if(state.sonarCooldown>0){notify(`鲸歌正在积蓄，${Math.ceil(state.sonarCooldown)} 秒后可再次释放`);return;}state.sonarCooldown=10;state.sonarAge=0;state.scans++;sonar.position.copy(whale.position);sonar.visible=true;$('#scan-label').style.opacity=1;jellies.forEach(j=>{if(j.group.position.distanceTo(whale.position)<55)j.stun=9;});ping(180,2.5);notify('鲸歌扩散 · 附近水母已暂时平静，航标指向最近的目标');}
$('#sonarBtn').onclick=scan;let dashTap=0;$('#dashBtn').onclick=()=>{if(!state.paused&&state.playing){if(state.energy<12)notify('能量不足，放慢速度或寻找青色浮游生物');else dashTap=1.2;}};
function interact(){if(!state.playing||state.paused)return;if(!interactable){notify('靠近祭坛或归海之门，即可产生共鸣');return;}if(interactable==='gate'){if(state.altars<3){notify('归海之门仍在沉睡，需要先唤醒三座祭坛。');return;}if(!state.won){state.won=true;ping(620,3);persist();updateQuest();openPanel('win');}return;}
 if(state.shards<6){notify('祭坛需要完整的记忆：先收集 6 枚金色碎片。');return;}if(!interactable.active){activateAltar(interactable,true);state.altars++;state.health=Math.min(100,state.health+25);state.energy=100;ping(450+state.altars*100,1.7);updateQuest();persist();notify(state.altars===3?'三座祭坛共鸣！神殿的归海之门已经开启。':`第 ${state.altars} 座祭坛苏醒 · 鲸歌正穿越古老的石壁`);}}
$('#touchInteract').onclick=interact;
function togglePause(){if(!state.playing){openPanel('help');return;}if(!$('#modal').hidden){closeModal();return;}openPanel('pause');}$('#pauseBtn').onclick=togglePause;
function closeModal(){ $('#modal').hidden=true;state.paused=false;keys={};$('#pauseBtn').textContent='Ⅱ';if(modalBeforeFocus?.isConnected)modalBeforeFocus.focus(); }
$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
function openPanel(type){modalBeforeFocus=document.activeElement;state.paused=state.playing;keys={};$('#pauseBtn').textContent='▷';$('#modal').hidden=false;const c=$('#modalContent');const eyebrow=t=>`<div class="tiny-label">${t}</div>`;
 if(type==='help')c.innerHTML=eyebrow('A GUIDE TO THE DEEP')+'<h2>让海洋带你前行</h2><p>你是一头寻找远古鲸歌的蓝鲸。收集 6 枚金色记忆碎片，唤醒 3 座共鸣祭坛，最后回到中央神殿，打开归海之门。</p><div class="help-grid"><div><kbd>W / ↑</kbd>向前游动</div><div><kbd>S / ↓</kbd>向后游动</div><div><kbd>A D / ← →</kbd>左右转向</div><div><kbd>Space / C</kbd>上浮 / 下潜</div><div><kbd>Shift</kbd>加速冲刺</div><div><kbd>Q</kbd>鲸歌声呐</div><div><kbd>E</kbd>祭坛 / 光门交互</div><div><kbd>M / J</kbd>地图 / 探索日志</div><div><kbd>鼠标拖动</kbd>环视鲸鱼</div><div><kbd>Esc</kbd>暂停 / 继续</div></div><p>金色碎片靠近后自动收集。青色浮游生物恢复生命与能量。紫色水母有毒，鲸歌可让附近水母平静 9 秒。能量会自然恢复，迷失方向时跟随屏幕航标与右下角地图。</p><p>旅程自动保存在本机浏览器。生命耗尽后返回神殿入口，已找到的记忆不会丢失。</p>';
 if(type==='journal'){let count=state.won?4:state.altars>0?3:state.shards>=3?2:state.shards>0?1:0;c.innerHTML=eyebrow('MEMORIES OF THE OCEAN')+`<h2>探索日志</h2><p>那些被大海珍藏的故事。已发现 ${count} / 4 篇。</p>`+stories.map(([title,text],i)=>`<div class="journal-item ${i<count?'':'locked'}"><h3>${i<count?'0'+(i+1)+' · '+title:'◇ 尚未听见的回声'}</h3><p>${i<count?text:['收集第一枚记忆碎片解锁','收集三枚记忆碎片解锁','唤醒第一座共鸣祭坛解锁','穿越归海之门解锁'][i]}</p></div>`).join('');$('#journalDot').classList.remove('active');}
 if(type==='map'){c.innerHTML=eyebrow('BATHYMETRIC CHART · SECTOR 01')+'<h2>遗忘之庭 · 海域图</h2><p>点击海图放置航标，追随屏幕指引自由探索。</p><canvas id="bigMap" class="big-map" width="500" height="500"></canvas><div class="map-legend"><span>▲ 蓝鲸</span><span>◆ 记忆碎片</span><span>◎ 共鸣祭坛</span></div><div class="modal-actions"><button id="clearWaypoint" class="secondary">清除航标 · 恢复任务指引</button></div>';drawMap($('#bigMap'),true);$('#bigMap').onclick=e=>{const rect=e.target.getBoundingClientRect();manualTarget=new V(((e.clientX-rect.left)/rect.width-.5)*240,3,((e.clientY-rect.top)/rect.height-.5)*240-20);closeModal();notify('已标记目的地，到达后自动恢复任务指引');};$('#clearWaypoint').onclick=()=>{manualTarget=null;closeModal();notify('已恢复任务指引');};}
 if(type==='pause'){c.innerHTML=eyebrow('A MOMENT OF STILLNESS')+'<h2>海洋，静候你的归来。</h2><p>旅程已自动保存。深呼吸，下一段回声就在前方。</p>'+statsHTML()+'<div class="modal-actions"><button class="primary" id="resumeGame">继续探索 ↗</button><button class="secondary" id="returnHome">返回主画面</button></div>';persist();$('#resumeGame').onclick=closeModal;$('#returnHome').onclick=home;}
 if(type==='new'){c.innerHTML=eyebrow('A NEW VOYAGE')+'<h2>开启新的旅程？</h2><p>新的旅程会替换这台设备上的探索存档。你也可以继续之前的航行。</p><div class="modal-actions"><button class="primary" id="resumeSaved">继续上次旅程 ↗</button><button class="secondary" id="restartGame">重新开始</button></div>';$('#resumeSaved').onclick=()=>start(true);$('#restartGame').onclick=()=>start(false);}
 if(type==='win'){c.innerHTML=eyebrow('THE OCEAN REMEMBERS')+'<h2>你让深海，再次歌唱。</h2><p>光穿过沉没千年的门扉，古老的鲸歌与潮汐一起归来。那些被遗忘的记忆，终于找到了回家的路。</p>'+statsHTML()+'<div class="journal-item"><h3>✧ 航程完成 · 深海守望者</h3><p>全部 6 枚记忆碎片已寻回，3 座共鸣祭坛已苏醒。探索日志现已完整解锁。</p></div><div class="modal-actions"><button class="primary" id="freeRoam">继续自由探索 ↗</button><button class="secondary" id="readEnding">阅读最后的回声</button></div>';$('#freeRoam').onclick=closeModal;$('#readEnding').onclick=()=>openPanel('journal');}
 $('#closeModal').focus();
}
function statsHTML(){return `<div class="stats"><div><b>${Math.floor(state.time/60)}:${String(Math.floor(state.time%60)).padStart(2,'0')}</b>航行时间</div><div><b>${Math.round(state.distance)}</b>游动距离 / m</div><div><b>${state.scans}</b>鲸歌回响</div></div>`;}
function home(){persist();state.playing=false;closeModal();$('#landing').hidden=false;$('#scene-note').hidden=false;$('#landing-bottom').hidden=false;$('#hud').hidden=true;$('#mobile-controls').hidden=true;$('#continueBtn').hidden=!saved;document.body.classList.remove('playing');sonar.visible=false;$('#scan-label').style.opacity=0;}
$('.brand').onclick=e=>{e.preventDefault();if(state.playing)openPanel('pause');};$$('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
addEventListener('keydown',e=>{if(e.code==='Tab'&&!$('#modal').hidden){const items=[...$('#modal').querySelectorAll('button,[href],[tabindex="0"]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&state.playing)e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){togglePause();return;}if(!$('#modal').hidden)return;keys[e.code]=true;if(e.code==='KeyQ')scan();if(e.code==='KeyE')interact();if(e.code==='KeyM')openPanel('map');if(e.code==='KeyJ')openPanel('journal');});
addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{keys={};if(state.playing&&!state.paused)openPanel('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};persist();if(state.playing&&!state.paused)openPanel('pause');}});addEventListener('beforeunload',persist);
world.renderer.domElement.addEventListener('pointerdown',e=>{if(!state.playing||state.paused)return;drag=true;lastMouse={x:e.clientX,y:e.clientY};world.renderer.domElement.setPointerCapture(e.pointerId);});addEventListener('pointermove',e=>{if(drag){orbit-=(e.clientX-lastMouse.x)*.006;orbitPitch=THREE.MathUtils.clamp(orbitPitch+(e.clientY-lastMouse.y)*.005,-.4,.65);lastMouse={x:e.clientX,y:e.clientY};}});addEventListener('pointerup',()=>drag=false);
$$('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;});
function drawMap(canvas,big=false){if(!canvas)return;const ctx=canvas.getContext('2d'),size=canvas.width,scale=size/240;const pos=(x,z)=>[size/2+x*scale,size/2+(z+20)*scale];ctx.clearRect(0,0,size,size);ctx.strokeStyle='#75b1a520';ctx.lineWidth=1;for(let r=1;r<5;r++){ctx.beginPath();ctx.arc(size/2,size/2,r*size/10,0,Math.PI*2);ctx.stroke();}ctx.beginPath();ctx.moveTo(size/2,0);ctx.lineTo(size/2,size);ctx.moveTo(0,size/2);ctx.lineTo(size,size/2);ctx.stroke();let [gx,gy]=pos(0,-29);ctx.strokeStyle='#a5cfc84a';ctx.strokeRect(gx-23*scale,gy-18*scale,46*scale,36*scale);ctx.beginPath();ctx.arc(gx,gy,9*scale,0,Math.PI*2);ctx.strokeStyle=state.altars===3?'#a2ffda':'#718d8a';ctx.stroke();
 shards.forEach(s=>{if(s.collected)return;let[x,y]=pos(s.group.position.x,s.group.position.z);ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillStyle='#f4d698';ctx.fillRect(-2.5,-2.5,5,5);ctx.restore();});altars.forEach(a=>{let[x,y]=pos(a.group.position.x,a.group.position.z);ctx.beginPath();ctx.arc(x,y,big?6:3,0,Math.PI*2);ctx.strokeStyle=a.active?'#ceffe6':'#62bdb5';ctx.stroke();if(a.active){ctx.fillStyle='#ceffe6';ctx.fill();}});if(big||state.sonarAge<4)jellies.forEach(j=>{let[x,y]=pos(j.group.position.x,j.group.position.z);ctx.fillStyle=j.stun>0?'#608e99':'#9569b8';ctx.beginPath();ctx.arc(x,y,big?3:1.5,0,Math.PI*2);ctx.fill();});if(manualTarget){let[x,y]=pos(manualTarget.x,manualTarget.z);ctx.strokeStyle='#fff';ctx.strokeRect(x-4,y-4,8,8);}let[x,y]=pos(whale.position.x,whale.position.z);ctx.save();ctx.translate(x,y);ctx.rotate(-state.heading);ctx.fillStyle='#c7f5df';ctx.shadowColor='#99e2bf';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,5);ctx.lineTo(0,2);ctx.lineTo(4,5);ctx.closePath();ctx.fill();ctx.restore();if(big){ctx.fillStyle='#96bab1';ctx.font='12px sans-serif';ctx.fillText('N',size/2+8,22);ctx.fillText('中央神殿',gx+17,gy+5);}}
function update(dt){state.time+=dt;saveClock+=dt;state.sonarCooldown=Math.max(0,state.sonarCooldown-dt);state.sonarAge+=dt;state.invincible=Math.max(0,state.invincible-dt);dashTap=Math.max(0,dashTap-dt);
 const forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),turn=(keys.KeyA||keys.ArrowLeft?1:0)-(keys.KeyD||keys.ArrowRight?1:0);state.heading+=turn*dt*.95;const boosting=(keys.ShiftLeft||keys.ShiftRight||dashTap>0)&&state.energy>5;const goal=forward*(boosting?22:10);state.speed=THREE.MathUtils.damp(state.speed,goal,2.4,dt);const old=whale.position.clone();whale.position.x-=Math.sin(state.heading)*state.speed*dt;whale.position.z-=Math.cos(state.heading)*state.speed*dt;
 const vertical=(keys.Space?1:0)-(keys.KeyC||keys.ControlLeft?1:0);whale.position.y=THREE.MathUtils.clamp(whale.position.y+vertical*dt*7,-6,40);whale.position.x=THREE.MathUtils.clamp(whale.position.x,-112,112);whale.position.z=THREE.MathUtils.clamp(whale.position.z,-132,92);state.distance+=whale.position.distanceTo(old);whale.rotation.y=state.heading;whale.rotation.z=THREE.MathUtils.damp(whale.rotation.z,-turn*.18,3,dt);whale.rotation.x=THREE.MathUtils.damp(whale.rotation.x,vertical*.16,3,dt);state.energy=THREE.MathUtils.clamp(state.energy+(boosting&&forward!==0?-22:10)*dt,0,100);whale.userData.tail.rotation.x=Math.sin(time*(boosting?6:3))*(Math.abs(state.speed)>2?.28:.13);
 const a=state.heading+orbit;const offset=new V(Math.sin(a)*24,8+orbitPitch*20,Math.cos(a)*24);const desired=whale.position.clone().add(offset);camera.position.lerp(desired,1-Math.exp(-2.4*dt));const look=whale.position.clone().add(new V(-Math.sin(state.heading)*6,1,-Math.cos(state.heading)*6));camera.lookAt(look);if(!drag){orbit=THREE.MathUtils.damp(orbit,0,.6,dt);orbitPitch=THREE.MathUtils.damp(orbitPitch,0,.6,dt);}
 shards.forEach(s=>{if(!s.collected&&whale.position.distanceTo(s.group.position)<5){s.collected=true;s.group.visible=false;state.shards++;state.energy=Math.min(100,state.energy+20);ping(480+state.shards*70,.8);updateQuest();persist();notify(state.shards===6?'六枚记忆已完整！前往三座青色祭坛，按 E 唤醒。':`记忆碎片 ${state.shards} / 6 · ${state.shards===1?'解锁探索日志「石之回声」':state.shards===3?'解锁探索日志「潮汐的刻度」':'你听见了远方的鲸歌'}`);}});
 foods.forEach(f=>{if(!f.available){f.timer-=dt;if(f.timer<=0){f.available=true;f.group.visible=true;}}else if(whale.position.distanceTo(f.group.position)<5&&(state.energy<90||state.health<95)){f.available=false;f.timer=35;f.group.visible=false;state.health=Math.min(100,state.health+20);state.energy=Math.min(100,state.energy+40);state.foods++;ping(750,.3);notify('浮游微光 · 生命 +20，能量 +40');}});
 jellies.forEach(j=>{if(j.stun<=0&&state.invincible<=0&&whale.position.distanceTo(j.group.position)<5){state.health=Math.max(0,state.health-18);state.invincible=2.5;ping(80,.8);notify('水母蜇伤！用 Q 鲸歌安抚它们，或冲刺离开。');}});
 if(state.health<=0){whale.position.set(0,5,36);state.health=100;state.energy=100;state.invincible=8;state.speed=0;notify('洋流将你送回了神殿入口 · 已发现的记忆保留');persist();}
 interactable=null;for(const a of altars)if(!a.active&&whale.position.distanceTo(a.group.position)<10){interactable=a;break;}if(whale.position.distanceTo(new V(0,3,-24))<12&&!state.won)interactable='gate';$('#interact').hidden=!interactable;$('#interact span').textContent=interactable==='gate'?(state.altars===3?'穿越归海之门':'聆听沉睡的光门'):state.shards<6?'聆听祭坛 · 需要 6 枚记忆':'唤醒共鸣祭坛';
 if(manualTarget&&whale.position.distanceTo(manualTarget)<8){manualTarget=null;notify('已抵达航标 · 恢复任务指引');}
 if(state.sonarAge<3){sonar.scale.setScalar(1+state.sonarAge*23);sonar.material.opacity=(1-state.sonarAge/3)*.11;}else{sonar.visible=false;$('#scan-label').style.opacity=0;}
 $('#healthText').textContent=Math.ceil(state.health);$('#energyText').textContent=Math.floor(state.energy);$('#healthBar').style.width=state.health+'%';$('#energyBar').style.width=state.energy+'%';$('#depth').textContent=Math.round(1283-whale.position.y).toLocaleString();$('#sonarTimer').textContent=state.sonarCooldown>0?`${Math.ceil(state.sonarCooldown)} 秒后就绪`:'已就绪';$('#dashTimer').textContent=boosting?'正在冲刺':state.energy<12?'能量恢复中':'消耗能量';drawMap($('#mapCanvas'));
 const dest=target();$('#target-marker').hidden=!dest;if(dest){let p=dest.position.clone().project(camera);const behind=dest.position.clone().sub(camera.position).dot(camera.getWorldDirection(new V()))<0;let x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;if(behind){x=innerWidth*.5+(p.x>0?-1:1)*innerWidth*.4;y=innerHeight*.52;}$('#target-marker').style.left=THREE.MathUtils.clamp(x,35,innerWidth-35)+'px';$('#target-marker').style.top=THREE.MathUtils.clamp(y,110,innerHeight-170)+'px';$('#targetText').textContent=dest.name;$('#targetDistance').textContent=Math.round(whale.position.distanceTo(dest.position))+' m';}
 if(saveClock>5){saveClock=0;persist();}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(state.paused)return;time+=dt;world.animate(dt,state.playing);if(state.playing)update(dt);else{whale.position.x=13;whale.position.z=21;whale.rotation.set(.03,-.78,-.08);camera.position.set(54+Math.sin(time*.08)*2,19,69);camera.lookAt(-5,2,-21);}world.render();}requestAnimationFrame(frame);
// Read-only diagnostics for browser verification and performance checks.
window.__whalefall={getState:()=>({...state,position:whale.position.toArray(),collected:shards.filter(s=>s.collected).map(s=>s.id),lit:altars.filter(a=>a.active).map(a=>a.id)}),getRenderInfo:()=>({calls:world.renderer.info.render.calls,triangles:world.renderer.info.render.triangles})};
