import {PARTS,SPECIES,TOOLS,newGame,validateSave,countFound,countClean,countPlaced,digAction,cleanAction,placeAction} from './game.js';
import {GameScene} from './scene.js';

const ICONS={
 fossil:'<path d="M4 7c0-3 4-4 5-1l7 7c3-1 5 1 4 3s-3 2-4 1l-7-7c-2 2-5 0-5-3Z"/><path d="m10 12-4 4m2-2 3 3m1-1-2 4m4-6 4-2"/>',
 pick:'<path d="m5 21 11-14M4 7c5-5 11-4 16 1M11 4l8 7M15 5l4 1"/>',
 flask:'<path d="M9 3h6M10 3v6L4 19a1 1 0 0 0 1 2h14a1 1 0 0 0 1-2L14 9V3M8 14h8m-6 3h.01m4 1h.01"/>',
 museum:'<path d="m3 8 9-5 9 5H3Zm2 3v7m5-7v7m4-7v7m5-7v7M3 21h18M3 18h18"/>',
 coin:'<circle cx="12" cy="12" r="8"/><path d="m12 7 3 5-3 5-3-5Z"/>',
 'sound-off':'<path d="M11 5 6 9H3v6h3l5 4V5Zm5 4 5 6m0-6-5 6"/>',
 sound:'<path d="M11 5 6 9H3v6h3l5 4V5Zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
 book:'<path d="M12 5v16M12 5C8 2 4 3 2 4v15c3-1 7-1 10 2 3-3 7-3 10-2V4c-3-1-7-2-10 1Z"/>',
 map:'<path d="m3 5 6-2 6 3 6-2v15l-6 2-6-3-6 2V5Zm6-2v15m6-12v15"/>',
 pin:'<path d="M19 10c0 6-7 11-7 11S5 16 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',focus:'<path d="M3 9V4h5m8 0h5v5m0 7v5h-5M8 21H3v-5"/><circle cx="12" cy="12" r="3"/>',
 camera:'<path d="m8 5 1-2h6l1 2h4a1 1 0 0 1 1 1v13H3V6a1 1 0 0 1 1-1h4Z"/><circle cx="12" cy="12" r="4"/>',
 mouse:'<rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v7M6 9h12"/>',
 compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',chevron:'<path d="m9 5 7 7-7 7"/>',
 skull:'<path d="M6 17C2 15 3 6 7 4c6-4 13 0 13 6 0 4-2 6-5 7v3H7v-3Zm3 0v3m3-3v3M6 9l3 2-2 2-2-1 1-3Zm8 0 3 1-1 3-3-1 1-3Z"/>',
 spine:'<path d="M6 3c8 3 3 7 9 10s3 5 5 8M4 6l5-2M5 9l7-3m-4 6 6-3m-2 7 6-4m-2 8 6-4"/>',
 ribs:'<path d="M12 3v18M10 5C2 5 2 12 5 12m9-7c8 0 8 7 5 7M10 9c-6 0-7 7-3 8m7-8c6 0 7 7 3 8m-7-4c-3 0-5 7-1 7m5-7c3 0 5 7 1 7"/>',
 bone:'<path d="M6 3a3 3 0 0 1 4 4l7 7a3 3 0 1 1 3 5 3 3 0 1 1-5-3L8 9a3 3 0 1 1-5-3 3 3 0 0 1 3-3Z"/>',
 tail:'<path d="M3 5c9 0 4 8 11 9s5 5 8 7M4 3 3 8m5-4L6 10m5 0-3 3m5-1-2 5m5-3-2 5m5-2-1 4"/>',
 light:'<path d="M8 17c0-4-3-4-3-8a7 7 0 0 1 14 0c0 4-3 4-3 8H8Zm1 3h6M10 23h4M9 9l3 3 3-3m-3 3v5"/>',
 chisel:'<path d="m4 20 3-5 8-11 4 3-8 11-7 2ZM13 7l4 3M5 18l3 2M15 4l1-2 5 4-2 2"/>',
 brush:'<path d="m14 3 4 2-5 10-4-2 5-10ZM9 13l-4 1-4 7h8l4-6m-9 6 4-6m0 6 3-5"/>',
 scan:'<path d="M4 8V4h4m8 0h4v4m0 8v4h-4M8 20H4v-4M2 12h20"/><circle cx="12" cy="12" r="4"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 energy:'<path d="m14 2-9 12h6l-1 8 9-12h-6l1-8Z"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',rotate:'<path d="M20 11a8 8 0 1 0-2 7M20 4v7h-7"/>',check:'<path d="m5 12 4 4L19 6"/>',trophy:'<path d="M8 3h8v7a4 4 0 0 1-8 0V3Zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 2v5m-4 2h8m-6-2h4"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 4v3"/>'
};
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[name]||ICONS.bone}</svg>`;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function decorate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
decorate();
const SAVE_KEY='deep-time-expedition-v1';let storageOK=true;let state;
try{const raw=localStorage.getItem(SAVE_KEY);state=raw?validateSave(JSON.parse(raw)):newGame();if(!state)state=newGame();}catch{state=newGame();storageOK=false;}
let scene=null,audio=null,toastTimer,feedbackTimer,exhibitPending=false;
const expedition=()=>state.expeditions[state.species];
const data=()=>SPECIES[state.species];
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('#save-label').textContent=storageOK?'进度自动保存在此设备':'当前浏览器无法存档，请保持页面打开';}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function feedback(text){$('#floating-feedback').textContent=text;$('#floating-feedback').classList.add('visible');clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('#floating-feedback').classList.remove('visible'),1800);}
function sound(type='tap'){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const gain=audio.createGain();gain.connect(audio.destination);const osc=audio.createOscillator();osc.connect(gain);const now=audio.currentTime;osc.type=type==='success'?'sine':type==='brush'?'triangle':'triangle';osc.frequency.setValueAtTime(type==='success'?660:type==='brush'?290:140,now);osc.frequency.exponentialRampToValueAtTime(type==='success'?990:80,now+.12);gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+.2);osc.start();osc.stop(now+.22);}catch{}}
function setView(view){state.view=view;if(view==='lab'){if(countFound(expedition())===0)toast('先发掘一块化石，再来修复实验室。');else if(expedition().dig[state.selected]!==100)state.selected=expedition().dig.findIndex(x=>x===100);}
 if(view==='museum'){const completed=state.expeditions.findIndex(e=>e.rewarded);if(completed!==-1&&!expedition().rewarded)state.species=completed;}
 scene?.build();render();save();}
function selectPart(index){if(!Number.isInteger(index)||index<0||index>5)return;state.selected=index;state.rotation=1;if(state.view==='lab'&&state.labMode==='clean')scene?.build();else if(state.view==='lab')scene?.build();render();save();}
function setLabMode(mode){state.labMode=mode;if(mode==='assemble'&&!expedition().clean[state.selected].every(Boolean)){const next=expedition().clean.findIndex((v,i)=>v.every(Boolean)&&!expedition().placed[i]);if(next>=0)state.selected=next;}state.rotation=1;scene?.build();render();save();}
function setTool(tool){if(!TOOLS.some(x=>x.id===tool))return;state.tool=tool;render();save();}
function dig(index=state.selected,point){state.selected=index;const result=digAction(state,index);if(result.error){toast(result.error);return result;}if(result.scan){scene?.scan();toast('发现 6 处骨骼信号。选择 A1—B3 地块继续发掘。');sound('success');}else{if(point)scene?.burst(point);sound(state.tool==='brush'?'brush':'tap');if(result.found){feedback(`${PARTS[index].name}已出土  +25 经费`);sound('success');if(countFound(expedition())===6){toast('6 件化石已全部收集！前往实验室开始修复。');}else{const next=expedition().dig.findIndex(v=>v<100);setTimeout(()=>{if(state.view==='field'&&state.selected===index){state.selected=next;render();save();}},650);}}else if(result.damaged)feedback('岩层很薄！换软毛刷保护骨骼');else if(result.progress>=60&&state.tool==='hammer')feedback('骨骼轮廓显露 · 建议换软毛刷');else feedback(`${PARTS[index].area} · 土层清除 ${result.progress}%`);}
 render();save();return result;}
function clean(spot,point){const result=cleanAction(state,state.selected,spot);if(result.error){toast(result.error);return result;}if(point)scene?.burst(point,0xb4a680);sound('brush');if(result.clean){feedback(`${PARTS[state.selected].name}修复完成`);sound('success');if(countClean(expedition())===6)toast('所有标本修复完成，切换到骨架拼装。');else toast('这件标本已清理完毕。选择下一件标本，或开始拼装。');}render();save();return result;}
function place(index,point){const result=placeAction(state,index);if(result.error){toast(result.error);return result;}sound('success');if(point)scene?.burst(point,0xedcf98);feedback(`${PARTS[state.selected].name}拼合成功`);render();save();if(result.complete){exhibitPending=true;setTimeout(()=>{exhibitPending=false;completion(result.reward);},500);}else{const next=expedition().placed.findIndex((v,i)=>!v&&expedition().clean[i].every(Boolean));if(next>=0)setTimeout(()=>{if(state.view==='lab'){selectPart(next);}},650);}return result;}
function handleScene(event){if(event.type==='dig')dig(event.index,event.point);else if(event.type==='clean')clean(event.spot,event.point);else if(event.type==='place')place(event.index,event.point);}
function primary(){const e=expedition(),i=state.selected;if(state.view==='field'){if(countFound(e)===6){setView('lab');return;}dig();}else if(state.view==='lab'){if(state.labMode==='clean'){if(e.dig[i]<100){setView('field');return;}const spot=e.clean[i].findIndex(v=>!v);if(spot>=0)clean(spot);else if(countClean(e)===6)setLabMode('assemble');else{const next=e.clean.findIndex((v,j)=>!v.every(Boolean)&&e.dig[j]===100);if(next>=0)selectPart(next);else setLabMode('assemble');}}else{if(e.rewarded){setView('museum');return;}place(i);}}else{if(e.rewarded)openLocations();else setView(countFound(e)>0?'lab':'field');}}

function render(){const e=expedition(),s=data(),found=countFound(e),cleaned=countClean(e),placed=countPlaced(e),i=state.selected,field=state.view==='field',lab=state.view==='lab',museum=state.view==='museum',assembling=lab&&state.labMode==='assemble';
 $$('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-current',b.dataset.view===state.view?'page':'false');});
 $('#credits').textContent=state.credits.toLocaleString();$('#expedition-no').textContent=String(state.species+1).padStart(3,'0');$('#period-label').textContent=s.period;
 $('#scene-title').innerHTML=`${field?s.site:lab?(assembling?'骨架拼装台':'化石修复台'):'我的博物馆'}<span class="title-tag">${field?'野外考察中':lab?(assembling?'重建远古生命':'让细节重现'):e.rewarded?'珍藏已入馆':'等待首件藏品'}</span>`;
 $('#scene-subtitle').textContent=field?'每一块化石，都是通往远古世界的线索。':lab?(assembling?'选择已修复的部件，调整方向，再与骨架轮廓拼合。':'轻轻刷去泥块，找回沉睡千万年的生命细节。'):'从一片碎骨，到一段被重新讲述的生命史。';
 $('#location-name').textContent=field?`${s.site} · A 区`:lab?(assembling?'古生物实验室 · 拼装区':'古生物实验室 · 修复区'):'深时博物馆 · 主展厅';$('#environment-info').textContent=field?s.climate:'恒温 · 21°C';$('#day-label').textContent='DAY '+String(state.day).padStart(2,'0');
 $('#scene-label').textContent=field?'发掘现场':lab?(assembling?'骨架复原':'精细修复'):'骨骼陈列';$('#scene-code').textContent=field?`SITE ${s.code}—01`:`SPECIMEN ${s.code}—0${i+1}`;
 $('#scene-hint').textContent=field?'点击土层挖掘 · 拖动旋转 · 滚轮缩放':lab?(assembling?'点击骨架轮廓拼合 · R 旋转部件 · 拖动环视':'拖动刷去五处泥块 · 或点击下方清理按钮'):'拖动欣赏骨架 · 滚轮缩放 · 相机按钮隐藏浮层';
 $('#mission-number').textContent=`0${state.species+1} / 03`;$('#species-name').textContent=s.name;$('#species-latin').textContent=s.latin;$('#species-rarity').textContent=s.difficulty;
 const progress=field?found:lab?(assembling?placed:cleaned):placed;$('#progress-label').textContent=field?'骨骼收集进度':lab?(assembling?'骨架拼合进度':'标本修复进度'):'骨架复原进度';$('#progress-count').innerHTML=`${progress} <small>/ 6</small>`;$('#progress-fill').style.width=`${progress/6*100}%`;
 const stage=e.rewarded?3:found<6?0:cleaned<6?1:2;$('#stage-steps').innerHTML=['发掘','修复','拼装'].map((n,j)=>`<div class="stage-step ${stage>j?'done':stage===j?'active':''}"><span class="step-dot">${stage>j?'✓':j+1}</span>${n}</div>`).join('');
 $('#objective-text').textContent=field?(found===6?'全部标本已经出土，前往实验室清理表面泥土。':e.dig[i]>=60?'骨骼已露出轮廓，使用软毛刷保护脆弱细节。':'选择地块，用地质锤移除表层岩土。'):lab?(assembling?(e.rewarded?'完整骨架复原成功！送入博物馆展陈。':`${PARTS[i].name}方向：${state.rotation*90}°。调至 0°，再点击对应轮廓。`):e.dig[i]<100?'这件标本尚未出土，回到遗址进行发掘。':e.clean[i].every(Boolean)?'这件标本已修复，可以继续清理其他部件或开始拼装。':`刷去${PARTS[i].name}表面的 ${5-e.clean[i].filter(Boolean).length} 处泥块。`):e.rewarded?'欣赏你的研究成果，或启程探索下一处遗址。':'发掘、修复并拼合第一具骨架，让博物馆迎来开馆。';
 $('#next-stage').innerHTML=`${field?'前往修复实验室':lab?(assembling?'查看博物馆':'前往骨架拼装'):'探索其他遗址'}${icon('chevron')}`;
 $('#inventory-title').textContent=museum?'展馆收藏':'化石标本';$('#inventory-count').textContent=museum?`${state.expeditions.filter(x=>x.rewarded).length} / 3`:`${found} / 6`;
 if(museum){$('#specimen-grid').innerHTML=SPECIES.map((s,j)=>`<button class="specimen ${state.expeditions[j].rewarded?'found complete':''} ${j===state.species?'selected':''}" data-exhibit="${j}" aria-label="查看${s.name}展品">${icon(state.expeditions[j].rewarded?'fossil':'lock')}<span>${s.name}</span></button>`).join('');$('#inventory-hint').textContent='完成完整骨架，即可解锁永久展陈';}
 else{$('#specimen-grid').innerHTML=PARTS.map((p,j)=>`<button class="specimen ${e.dig[j]===100?'found':''} ${j===i?'selected':''} ${e.placed[j]?'complete':''}" data-part="${j}" aria-label="选择${p.area} ${p.name}，${e.dig[j]<100?'已挖掘'+e.dig[j]+'%':e.placed[j]?'已拼装':e.clean[j].every(Boolean)?'已修复':'已出土'}" aria-pressed="${j===i}">${icon(p.icon)}<span>${p.name}</span><i class="part-progress" style="width:${field?e.dig[j]:e.clean[j].filter(Boolean).length*20}%"></i></button>`).join('');$('#inventory-hint').textContent=field?'点击标本，定位对应的勘探地块':assembling?'选择部件后，点击模型轮廓或下方拼合':'点击标本切换 · 每件有五处独立泥块';}
 $('#note-title').textContent=museum?'古生物档案':'考古学家的笔记';$('#note-text').textContent=museum?s.fact:assembling?PARTS[i].tip:lab?'每一处裂纹都可能藏着线索。五处泥块清理完毕，即可把这件标本送上拼装台。':'发现骨骼轮廓后，换用软毛刷。耐心，往往比力气更重要。';
 $('#target-kicker').textContent=field?'当前勘探地块':lab?(assembling?'待拼合部件':'当前修复标本'):'当前展品';$('#target-name').textContent=field?`${PARTS[i].area} · ${PARTS[i].name}区域`:lab?`${PARTS[i].name}${assembling?' · '+state.rotation*90+'°':''}`:s.name+' · '+(e.rewarded?'完整骨架':'未入馆');
 $('#target-status').textContent=field?(e.dig[i]===100?'已收集':`${e.dig[i]}% 已发掘`):lab?(assembling?`${placed}/6 已拼合`:`${e.clean[i].filter(Boolean).length*20}% 已清理`):e.rewarded?'馆藏 No. 00'+(state.species+1):'待复原';
 $('#action-label').textContent=field?(found===6?'前往实验室':state.tool==='scan'?'扫描化石信号':'继续挖掘'):lab?(assembling?(e.rewarded?'送入博物馆':'拼合选中部件'):e.dig[i]<100?'返回遗址':e.clean[i].every(Boolean)?(cleaned===6?'开始骨架拼装':'修复下一件'):'刷去一处泥块'):e.rewarded?'开启新考察':'继续我的考察';
 $('#primary-action [data-icon]').innerHTML=icon(field?'pick':lab?(assembling?'fossil':'brush'):'compass');
 if(field){$('#tool-heading').textContent='考察工具';$('#tool-caption').textContent=state.upgrade?`工具等级 ${state.upgrade+1} · 发掘效率提升`:'选择适合土层的工具';$('#tool-list').innerHTML=TOOLS.map(t=>`<button class="tool ${state.tool===t.id?'active':''}" data-tool="${t.id}" aria-pressed="${state.tool===t.id}"><span data-icon="${t.icon}">${icon(t.icon)}</span><span><span class="tool-name">${t.name}</span><span class="tool-hint">${t.caption}</span></span><kbd>${t.key}</kbd></button>`).join('');}
 else if(lab){$('#tool-heading').textContent='修复工作台';$('#tool-caption').textContent=assembling?'调整部件方向后拼合':'清理完毕的部件可以开始拼装';$('#tool-list').innerHTML=`<button class="tool ${!assembling?'active':''}" data-mode="clean"><span data-icon="brush">${icon('brush')}</span><span class="tool-name">标本清理</span></button><button class="tool ${assembling?'active':''}" data-mode="assemble"><span data-icon="fossil">${icon('fossil')}</span><span class="tool-name">骨架拼装</span></button><button class="tool" data-rotate ${!assembling?'disabled':''}><span data-icon="rotate">${icon('rotate')}</span><span class="tool-name">旋转 90°</span><kbd>R</kbd></button>`;}
 else{$('#tool-heading').textContent='馆藏研究';$('#tool-caption').textContent='珍藏每一次探索的成果';$('#tool-list').innerHTML=`<button class="tool active" data-details>${icon('book')}<span class="tool-name">藏品档案</span></button><button class="tool" data-achievements>${icon('trophy')}<span class="tool-name">研究成就</span></button><button class="tool" data-locations>${icon('map')}<span class="tool-name">新的考察</span></button>`;}
 $('#integrity-label').innerHTML=`${e.integrity}<small>%</small>`;$('#integrity-fill').style.width=e.integrity+'%';$('#integrity-fill').style.background=e.integrity>80?'#a2b790':'#d3a46f';$('#condition-tip').textContent=e.integrity===100?'精细发掘，保护每一处细节':e.integrity>=80?'轻微损伤，继续精细清理':'化石仍可复原，请改用软毛刷';$('#energy-label').textContent=state.energy;
 $('#sound').innerHTML=icon(state.sound?'sound':'sound-off');$('#sound').setAttribute('aria-label',state.sound?'关闭音效':'开启音效');$('#sound').title=state.sound?'关闭音效':'开启音效';scene?.update();
}

function modal(title,eyebrow,html){$('#modal-title').textContent=title;$('#modal-eyebrow').textContent=eyebrow;$('#modal-body').innerHTML=html;decorate($('#modal-body'));if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function help(){modal('探险手册','FIELD GUIDE / HOW TO PLAY',`<p class="modal-copy">从第一块化石开始，把一段远古生命史带回今天。游戏会自动保存在当前浏览器，每件标本都可以慢慢完成。</p><div class="guide-grid" style="margin-top:18px"><div class="guide-item"><b>${icon('scan')}01 · 勘探与发掘</b><p>选择 A1—B3 地块或点击场景。地质锤适合表层，土层清除 60% 后改用软毛刷；精细凿在 80% 后也可能伤到骨骼。</p></div><div class="guide-item"><b>${icon('brush')}02 · 精细修复</b><p>标本出土后，进入实验室。拖动刷过五处棕色泥块，也可点击“刷去一处泥块”。清理过的位置不会重复计分。</p></div><div class="guide-item"><b>${icon('fossil')}03 · 骨架拼合</b><p>切换骨架拼装，选择修复好的部件。点击“旋转 90°”调至 0°，然后点击对应轮廓，或按“拼合选中部件”。</p></div><div class="guide-item"><b>${icon('museum')}04 · 展陈与探索</b><p>拼好六个部件即可入馆，获得经费并解锁下一遗址。用经费升级工具；营地休整免费恢复体力。</p></div></div><div class="key-guide"><span><kbd>1–4</kbd>选择工具</span><span><kbd>← →</kbd>选择部件</span><span><kbd>空格</kbd>当前操作</span><span><kbd>R</kbd>旋转部件</span><span><kbd>E</kbd>修复实验室</span><span><kbd>?</kbd>帮助</span></div><div class="modal-footer"><button class="amber-button" data-close>继续考察</button></div>`);}
function openLocations(){modal('选择考察遗址','EXPEDITION MAP / 03 SITES',`<p class="modal-copy">先复原当前动物的完整骨架，即可解锁下一处遗址。你可以随时返回已经解锁的考察。</p>${SPECIES.map((s,i)=>{const unlocked=i===0||state.expeditions[i-1].rewarded;return `<button class="site-option ${i===state.species?'active':''}" data-site="${i}" ${!unlocked?'disabled':''}><span class="site-num">0${i+1}</span><span><b>${s.site}</b><small>${s.name} · ${s.period}<br>${s.coords}</small></span><span class="site-status">${state.expeditions[i].rewarded?'已完成 ✓':i===state.species?'当前考察':unlocked?'开始考察':'待解锁'}</span></button>`;}).join('')}<p class="sources">遗址为游戏虚构场景。骨架为便于交互设计的简化复原模型。</p>`);}
function camp(){const cost=(state.upgrade+1)*100;modal('回到考察营地','BASE CAMP / REST & RESEARCH',`<p class="modal-copy">一次好的考察，需要足够的耐心，也需要休息。休整会推进一天，并恢复全部体力。</p><div class="stats-grid"><div class="stat-box"><strong>${state.energy}</strong><small>当前体力 / 100</small></div><div class="stat-box"><strong>${state.credits}</strong><small>研究经费</small></div><div class="stat-box"><strong>Lv.${state.upgrade+1}</strong><small>工具等级</small></div></div><div class="upgrade"><span data-icon="pick"></span><div><b>${state.upgrade===3?'专业工具组已满级':'升级野外工具组'}</b><p>${state.upgrade===3?'每次发掘额外清除 9% 土层。':'每次操作额外清除 3% 土层，累计提升。升级不会恢复已经受损的骨骼。'}</p></div><button class="outline-button" data-upgrade ${state.upgrade===3||state.credits<cost?'disabled':''}>${state.upgrade===3?'已满级':cost+' 经费'}</button></div><div class="modal-footer"><button class="outline-button" data-close>返回现场</button><button class="amber-button" data-rest>休整一天 · 免费</button></div>`);}
function journal(){const completed=state.expeditions.filter(e=>e.rewarded).length;modal('我的考察记录','EXPEDITION JOURNAL',`<div class="stats-grid"><div class="stat-box"><strong>${state.discovered}</strong><small>累计出土标本</small></div><div class="stat-box"><strong>${completed} / 3</strong><small>复原史前动物</small></div><div class="stat-box"><strong>${state.day}</strong><small>考察日</small></div></div>${[['第一块时间碎片','首次发掘一件化石',state.discovered>0],['耐心的修复师','完整清理六个骨架部件',state.expeditions.some(e=>countClean(e)===6)],['远古生命重现','完成第一具骨架并入馆',completed>0],['完美守护者','以 100% 完整度完成一次复原',state.expeditions.some(e=>e.rewarded&&e.integrity===100)],['深时探索者','完成全部三个遗址的考察',completed===3]].map(([title,desc,earned])=>`<div class="achievement ${earned?'earned':''}"><span data-icon="${earned?'trophy':'lock'}"></span><div><b>${title}</b><p>${desc}</p></div><span>${earned?'已达成':'待探索'}</span></div>`).join('')}<div class="modal-footer"><button class="outline-button" data-help>查看操作指南</button><button class="amber-button" data-close>继续考察</button></div>`);}
function details(){const s=data(),e=expedition();modal(s.name+' · 藏品档案','PALEONTOLOGY / SPECIMEN 00'+(state.species+1),`<div class="exhibit-summary"><div class="big-icon">${icon('fossil')}</div><h3>${s.name}</h3><em>${s.latin}</em><p>${s.description}</p></div><div class="badges"><span>${s.period}</span><span>${e.rewarded?'已入馆':'尚未入馆'}</span><span>完整度 ${e.integrity}%</span></div><p class="modal-copy">${s.fact}</p><p class="sources">知识来源：<a href="${s.source}" target="_blank" rel="noopener noreferrer">伦敦自然历史博物馆</a>。模型经过简化，供游戏体验使用。</p><div class="modal-footer"><button class="amber-button" data-close>回到展厅</button></div>`);}
function completion(reward){const s=data(),e=expedition();modal('一段远古生命，重新站立','EXPEDITION COMPLETE',`<div class="exhibit-summary"><span class="big-icon" data-icon="trophy"></span><h3>${s.name}复原成功</h3><p>从岩层中的碎片，到完整的生命轮廓。<br>你的第 ${state.species+1} 次考察，值得被珍藏。</p></div><div class="stats-grid"><div class="stat-box"><strong>${e.integrity}%</strong><small>化石完整度</small></div><div class="stat-box"><strong>+${reward}</strong><small>研究奖励</small></div><div class="stat-box"><strong>6 / 6</strong><small>骨架拼合</small></div></div><p class="modal-copy">${s.fact}</p><div class="modal-footer"><button class="outline-button" data-locations>${state.species<2?'新遗址已解锁':'全部遗址已探索'}</button><button class="amber-button" data-museum>送入博物馆</button></div>`);}
function resetConfirm(){modal('重新开始考察？','NEW EXPEDITION',`<p class="modal-copy">这会清空此浏览器中的全部化石、展品、经费和升级，从红岩峡谷的第一天重新开始。此操作无法撤销。</p><div class="modal-footer"><button class="outline-button" data-close>保留进度</button><button class="amber-button" data-confirm-reset>清空并重新开始</button></div>`);}

document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.part!==undefined)selectPart(Number(b.dataset.part));if(b.dataset.tool)setTool(b.dataset.tool);if(b.dataset.mode)setLabMode(b.dataset.mode);if(b.hasAttribute('data-rotate')){state.rotation=(state.rotation+1)%4;render();save();sound('tap');}if(b.dataset.exhibit!==undefined){const i=Number(b.dataset.exhibit);if(!state.expeditions[i].rewarded){toast('完成这具骨架的复原后，它就会出现在展厅。');return;}state.species=i;scene?.build();render();save();}if(b.hasAttribute('data-site')){const i=Number(b.dataset.site);if(i>0&&!state.expeditions[i-1].rewarded)return;state.species=i;state.selected=0;state.labMode='clean';state.tool='hammer';state.view=state.expeditions[i].rewarded?'museum':'field';closeModal();scene?.build();render();save();}if(b.hasAttribute('data-close'))closeModal();if(b.hasAttribute('data-help'))help();if(b.hasAttribute('data-details'))details();if(b.hasAttribute('data-achievements'))journal();if(b.hasAttribute('data-locations'))openLocations();if(b.hasAttribute('data-museum')){closeModal();setView('museum');}if(b.hasAttribute('data-rest')){state.energy=100;state.day++;save();render();closeModal();toast('体力完全恢复，新的一天开始了。');}if(b.hasAttribute('data-upgrade')){const cost=(state.upgrade+1)*100;if(state.upgrade<3&&state.credits>=cost){state.credits-=cost;state.upgrade++;save();render();camp();toast('工具已升级，发掘效率提升。');}}if(b.hasAttribute('data-confirm-reset')){state=newGame();if(scene)scene.state=state;save();closeModal();scene?.build();render();toast('新考察开始。欢迎回到红岩峡谷。');}});
$('#primary-action').addEventListener('click',primary);$('#next-stage').addEventListener('click',()=>{if(state.view==='field')setView('lab');else if(state.view==='lab'){if(state.labMode==='clean')setLabMode('assemble');else setView('museum');}else openLocations();});
$('#help').onclick=help;$('#journal').onclick=journal;$('#locations').onclick=openLocations;$('#camp').onclick=camp;$('#reset-game').onclick=resetConfirm;$('#close-modal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('#sound').onclick=()=>{state.sound=!state.sound;render();save();sound('success');};$('#zoom-in').onclick=()=>scene?.zoom(1);$('#zoom-out').onclick=()=>scene?.zoom(-1);$('#reset-camera').onclick=()=>scene?.resetCamera();$('#photo-mode').onclick=()=>{$('.game-panel').classList.toggle('pure-mode');$('#photo-mode').setAttribute('aria-pressed',$('.game-panel').classList.contains('pure-mode'));};
window.addEventListener('keydown',e=>{if($('#modal').open||e.target.matches('input,textarea,select')||e.repeat)return;if(e.key===' '){if(e.target.closest('button,a'))return;e.preventDefault();primary();}else if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();selectPart((state.selected+(e.key==='ArrowRight'?1:5))%6);}else if(['1','2','3','4'].includes(e.key)&&state.view==='field')setTool(TOOLS[Number(e.key)-1].id);else if(e.key.toLowerCase()==='r'&&state.view==='lab'&&state.labMode==='assemble'){state.rotation=(state.rotation+1)%4;render();save();}else if(e.key.toLowerCase()==='e')setView('lab');else if(e.key==='?')help();});
try{scene=new GameScene($('#viewport'),state,handleScene);$('#loading').remove();}catch(error){$('#loading').textContent='此浏览器暂时无法启用 3D。请打开硬件加速或换用支持 WebGL 的浏览器。';console.error('3D scene initialization failed',error);}
render();save();

// Browser agents use the same validated actions as players. Unsupported browsers ignore this enhancement.
if(document.modelContext?.registerTool){
 const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}};
 register({name:'read_expedition_progress',description:'Read current species, excavation, restoration, assembly, energy, credits and collection progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {species:data().name,view:state.view,selected:PARTS[state.selected].name,energy:state.energy,credits:state.credits,excavation:[...expedition().dig],restored:expedition().clean.map(x=>x.filter(Boolean).length*20),assembled:[...expedition().placed],exhibits:state.expeditions.map((e,i)=>({species:SPECIES[i].name,complete:e.rewarded}))};}});
 register({name:'select_expedition_workspace',description:'Navigate to the excavation field, restoration laboratory, or museum without completing a game action.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['field','lab','museum']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['field','lab','museum'].includes(input.view))throw new Error('Invalid workspace');setView(input.view);return {view:state.view,species:data().name};}});
 register({name:'excavate_fossil_once',description:'Use the selected excavation tool once on one valid site cell. Costs energy and can reduce fossil integrity with coarse tools near exposed bones.',inputSchema:{type:'object',properties:{cell:{type:'integer',minimum:0,maximum:5},tool:{type:'string',enum:['hammer','chisel','brush','scan']}},required:['cell','tool'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.cell)||input.cell<0||input.cell>5||!TOOLS.some(t=>t.id===input.tool))throw new Error('Invalid cell or tool');if(state.view!=='field')throw new Error('Navigate to the excavation field first');setTool(input.tool);return dig(input.cell);}});
}
