import {T,createWorld,buildCourse,animateWorld,burst} from './scene.js';
import {COURSES} from './courses.js';
import {newBall,fireBall,stepBall,clamp} from './physics.js';
const $=id=>document.getElementById(id);
let world;try{world=createWorld($('viewport'));}catch(e){$('loading').innerHTML='<span class="loading-orbit">✦</span><h2>这趟航行需要 3D 加速</h2><p>请开启浏览器硬件加速，或使用支持 WebGL 2 的浏览器。</p>';throw e;}
const SAVE_KEY='cosmic-pup-v1';let saved={records:{},sound:false};try{saved={...saved,...JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')};}catch{}if(!saved.records||typeof saved.records!=='object')saved.records={};
let level=0,c=COURSES[0],b=newBall(c.start),strokes=0,collected=new Set(),angle=0,power=45,loft=false,time=0,won=false,swing=0,charging=false,chargeTime=0,drag=null,undo=null,undoUsed=false,collisions=0,guardianHits=0,boosted=false,portalUsed=false,lastSafe={x:0,z:8},settleTimer=null,toastTimer=null,focusedBeforeModal=null,runScores={},audio=null,muted=!saved.sound,accumulator=0;
const pointer=new T.Vector2(),ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),-.25),point=new T.Vector3();
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(saved));}catch{}}
function initAudio(){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}catch{}}
function tone(freq,duration=.1,type='sine',gain=.08,delay=0){if(muted)return;initAudio();if(!audio)return;const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(60,freq*.65),t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+duration+.015);}
function melody(){[523,659,784,1047].forEach((f,i)=>tone(f,.3,'sine',.09,i*.13));}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
function setPower(v){power=clamp(Math.round(v),5,100);$('power').value=power;$('power-value').innerHTML=power+'<span>%</span>';$('power').style.background=`linear-gradient(to right,#b9f58e ${power}%,#4d425e ${power}%)`;}
function updateHUD(){$('strokes').textContent=strokes;$('stars-count').innerHTML=collected.size+'<span>/ 3</span>';$('ready-text').textContent=won?'完美着陆！':b.moving?'小球航行中…':charging?'正在蓄力…':'准备击球';$('ready-light').style.background=b.moving?'#e9c284':'#b9f58e';$('shoot-btn').disabled=b.moving;$('shoot-btn').innerHTML=won?'查看结算':'挥杆 <span>SPACE</span>';$('power').disabled=b.moving||won;$('undo-btn').disabled=!undo||undoUsed||won;$('undo-count').textContent=undoUsed?'0':'1';$('ball-label').style.opacity=(!b.moving&&!won&&strokes===0)?'1':'0';$('putt-btn').classList.toggle('selected',!loft);$('loft-btn').classList.toggle('selected',loft);$('putt-btn').setAttribute('aria-pressed',String(!loft));$('loft-btn').setAttribute('aria-pressed',String(loft));}
function loadLevel(i){clearTimeout(settleTimer);level=i;c=COURSES[i];b=newBall(c.start);strokes=0;collected=new Set();angle=Math.atan2(c.hole[0]-b.x,b.z-c.hole[1]);power=45;loft=false;won=false;charging=false;drag=null;undo=null;undoUsed=false;collisions=0;guardianHits=0;boosted=false;portalUsed=false;lastSafe={x:b.x,z:b.z};buildCourse(world,c);world.ballMesh.visible=true;world.pup.position.set(b.x-1.4,.1,b.z-.4);$('hole-num').textContent=String(i+1).padStart(2,'0');$('planet-label').textContent=c.planet;$('course-name').textContent=c.name;$('course-description').textContent=c.description;$('mechanic-label').textContent=c.tag;$('gravity-label').textContent=`重力 ${(c.gravity/10).toFixed(1)} g`;$('par').textContent=c.par;$('level-tip').textContent=c.tip;$('wind-value').textContent=c.wind[0]===0?'平静':`${c.wind[0]>.2?'轻风':'微风'} · 向右`;$('wind-arrow').textContent=c.wind[0]===0?'·':'↗';$('progress-dots').innerHTML=COURSES.map((_,n)=>`<span class="progress-dot ${n===i?'active':saved.records[n]?'done':''}" title="第 ${n+1} 洞"></span>`).join('');const rec=saved.records[i];$('best-score').textContent=rec?`个人最佳 · ${rec.strokes} 杆 / ${rec.stars} 星`:'个人最佳 · 等待创造';$('dog-message').textContent=['今天的目标：把星星和小球都带回家。','汪！高抛可以越墙，但要小心飞出边界。','这片沙子，好像饼干碎！','虫洞里面，会有零食吗？','系好安全带，我们要起飞啦。','最后一洞！麻薯相信你的准头。'][i];setPower(power);closeModal();updateHUD();}
function shoot(){if(b.moving||won||!$('modal').hidden)return;initAudio();charging=false;undo={ball:{...b},strokes,stars:[...collected],collisions,guardianHits,boosted,portalUsed,lastSafe:{...lastSafe}};lastSafe={x:b.x,z:b.z};fireBall(b,angle,power,loft);strokes++;swing=.6;tone(240,.1,'triangle',.12);burst(world,b.x,.35,b.z,0xe4f2c2,7);updateHUD();$('dog-message').textContent=loft?'宇宙飞球！希望它记得降落。':'好球！盯住它的落点。';}
function undoShot(){if(!undo||undoUsed||won)return;b={...undo.ball};strokes=undo.strokes;collected=new Set(undo.stars);collisions=undo.collisions;guardianHits=undo.guardianHits;boosted=undo.boosted;portalUsed=undo.portalUsed;lastSafe={...undo.lastSafe};undoUsed=true;world.stars.forEach((s,i)=>s.visible=!collected.has(i));world.ballMesh.visible=true;charging=false;drag=null;updateHUD();toast('时光倒流！每洞只有这一次哦。');}
function challengeMet(){return [strokes===1,collisions===0,collected.size===3,strokes<=2,boosted&&collisions===0,guardianHits===0][level];}
function completeHole(){if(won)return;won=true;charging=false;world.ballMesh.visible=false;const challenge=challengeMet();runScores[level]={strokes,stars:collected.size,challenge};const old=saved.records[level];saved.records[level]={strokes:Math.min(strokes,old?.strokes??Infinity),stars:Math.max(collected.size,old?.stars??0),challenge:challenge||!!old?.challenge};save();melody();burst(world,c.hole[0],.5,c.hole[1],0xffde92,55);updateHUD();$('dog-message').textContent='汪汪！这一杆值得两块小饼干！';settleTimer=setTimeout(showResult,1100);}
function modal(html){focusedBeforeModal=document.activeElement;$('modal-content').innerHTML=html;$('modal').hidden=false;charging=false;drag=null;updateHUD();$('close-modal').focus();}
function closeModal(){$('modal').hidden=true;focusedBeforeModal?.focus?.();focusedBeforeModal=null;}
function showResult(){const relative=strokes-c.par,name=strokes===1?'一杆入洞！':relative<=-2?'老鹰球！':relative===-1?'小鸟球！':relative===0?'标准杆达成！':'成功着陆！';const chal=challengeMet();modal(`<div class="result-emblem">${strokes===1?'🏆':'🪐'}</div><div class="eyebrow" style="justify-content:center">任务 ${String(level+1).padStart(2,'0')} 完成</div><h2 id="modal-title" class="result-title">${name}</h2><p class="result-subtitle">${c.name} · 麻薯为你摇起了尾巴。</p><div class="result-stars">${'★'.repeat(collected.size)}<span style="color:#675474">${'☆'.repeat(3-collected.size)}</span></div><div class="result-stats"><div><b>${strokes}</b><span>本洞杆数</span></div><div><b>${relative>0?'+':''}${relative===0?'E':relative}</b><span>相对标准杆</span></div><div><b>${saved.records[level].strokes}</b><span>个人最佳</span></div></div>${chal?`<div class="achievement">✦ 挑战达成：${c.challenge}</div>`:''}<div class="modal-actions"><button class="secondary-btn" id="replay-result">再挑战一次</button><button class="primary-btn" id="next-level">${level===5?'查看银河成绩单':'前往下一颗星球'}</button></div>`);$('replay-result').onclick=()=>loadLevel(level);$('next-level').onclick=()=>level===5?showScorecard():loadLevel(level+1);}
function showMap(){modal(`<div class="eyebrow">CHOOSE YOUR ORBIT</div><h2 id="modal-title">下一站，哪颗星球？</h2><p>六座球场，六种冒险。可以自由选择，也可以依次挑战。</p><div class="course-grid">${COURSES.map((r,i)=>{let record=saved.records[i];return `<button class="course-card ${level===i?'current':''}" data-course="${i}"><span class="course-icon">${r.icon}</span><b>${String(i+1).padStart(2,'0')} · ${r.name}</b><small>PAR ${r.par} · ${r.tag.slice(2)}</small><small class="record">${record?`${record.strokes} 杆 · ${'★'.repeat(record.stars)}${'☆'.repeat(3-record.stars)}`:'尚未探索'}</small></button>`;}).join('')}</div><div class="modal-actions"><button id="scorecard-btn" class="secondary-btn">银河成绩单</button><button id="map-continue" class="primary-btn">回到球场</button></div>`);document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.course);if(i===level)closeModal();else confirmSwitch(i);});$('map-continue').onclick=closeModal;$('scorecard-btn').onclick=showScorecard;}
function confirmSwitch(i){if(strokes&&!won){modal(`<div class="eyebrow">CHANGE ORBIT</div><h2 id="modal-title">出发去新的星球？</h2><p>本洞尚未完成的杆数和星星会重置，历史最佳会保留。</p><div class="modal-actions"><button id="keep-playing" class="secondary-btn">继续本洞</button><button id="switch-confirm" class="primary-btn">前往${COURSES[i].name}</button></div>`);$('keep-playing').onclick=closeModal;$('switch-confirm').onclick=()=>loadLevel(i);}else loadLevel(i);}
function showScorecard(){const records=saved.records,done=Object.keys(records).length,total=Object.values(records).reduce((n,r)=>n+r.strokes,0),stars=Object.values(records).reduce((n,r)=>n+r.stars,0);modal(`<div class="eyebrow">YOUR GALACTIC PASSPORT</div><h2 id="modal-title">麻薯的银河成绩单</h2><p>已探索 ${done} / 6 座球场 · 共收集 ${stars} / 18 颗星星<br>成绩保存在当前浏览器，每洞分别记录最佳杆数和最多星星。</p><table class="score-table"><thead><tr><th>球场</th><th>标准杆</th><th>最佳杆数</th><th>星星</th></tr></thead><tbody>${COURSES.map((r,i)=>`<tr><td>${r.icon} ${r.name}</td><td>${r.par}</td><td>${records[i]?.strokes??'—'}</td><td>${records[i]?'★'.repeat(records[i].stars)+'☆'.repeat(3-records[i].stars):'—'}</td></tr>`).join('')}</tbody></table>${done===6?`<div class="achievement">🏆 银河巡回赛完成 · 最佳杆数合计 ${total} / 标准杆 18</div>`:''}<div class="modal-actions"><button id="score-map" class="secondary-btn">球场地图</button><button id="score-continue" class="primary-btn">${won?'再来一轮':'继续探索'}</button></div>`);$('score-map').onclick=showMap;$('score-continue').onclick=()=>won?loadLevel(0):closeModal();}
function showHelp(){modal(`<div class="eyebrow">FLIGHT MANUAL</div><h2 id="modal-title">麻薯的宇宙挥杆指南</h2><p>用尽量少的杆数把小球送进旗杆下的球洞。收集星星，寻找属于你的捷径。</p><div class="help-grid"><div><span>⌖</span><b>瞄准与挥杆</b><p>移动鼠标指向目标，再按住空格蓄力，松开击球。也可以按住球场向后拖动，松手发射。触屏轻点球场瞄准，调节力度后点击「挥杆」。</p></div><div><span>↟</span><b>推杆与高抛</b><p>推杆稳定滚动；高抛可以飞过矮墙和裂隙，但可能飞出球场。A / D 微调方向，C 切换俯视。每洞可免费撤销一次。</p></div><div><span>◎</span><b>认识外星机关</b><p>沙地减速；虫洞两两相连；青色箭头加速；紫色垫弹跳。移动守门员会把球弹开，红色裂隙会罚一杆并送回上次击球点。</p></div><div><span>✦</span><b>收集银河成就</b><p>每洞有三颗星和一个特别挑战。小球滚过星星即可收集。地图中可以自由选关，最佳成绩自动保存在当前浏览器。</p></div></div><div class="modal-actions"><button class="primary-btn" id="help-close">收到，准备挥杆！</button></div>`);$('help-close').onclick=closeModal;}
function resetPrompt(){modal(`<div class="eyebrow">ONE MORE TRY</div><h2 id="modal-title">重新挑战${c.name}？</h2><p>本洞杆数和星星将归零，历史最佳成绩会保留。</p><div class="modal-actions"><button id="reset-no" class="secondary-btn">继续本洞</button><button id="reset-yes" class="primary-btn">重新挑战</button></div>`);$('reset-no').onclick=closeModal;$('reset-yes').onclick=()=>loadLevel(level);}
function groundPoint(event){const r=world.renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,world.camera);return ray.ray.intersectPlane(plane,point)?point.clone():null;}
const canvas=world.renderer.domElement;
canvas.addEventListener('pointermove',e=>{if(b.moving||won||!$('modal').hidden||charging)return;const p=groundPoint(e);if(!p)return;if(drag){const d=Math.hypot(e.clientX-drag.screenX,e.clientY-drag.screenY);if(d>8){drag.active=true;angle=Math.atan2(drag.point.x-p.x,p.z-drag.point.z);setPower(Math.hypot(drag.point.x-p.x,drag.point.z-p.z)*15);updateHUD();}}else if(e.pointerType!=='touch')angle=Math.atan2(p.x-b.x,b.z-p.z);});
canvas.addEventListener('pointerdown',e=>{if(b.moving||won||!$('modal').hidden||e.button!==0)return;initAudio();const p=groundPoint(e);if(!p)return;drag={point:p,screenX:e.clientX,screenY:e.clientY,active:false};angle=Math.atan2(p.x-b.x,b.z-p.z);canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const active=drag.active;drag=null;if(active)shoot();else if(e.pointerType==='touch')toast('方向已设定 · 调节力度后点击挥杆');});canvas.addEventListener('pointercancel',()=>{drag=null;charging=false;updateHUD();});
$('power').addEventListener('input',e=>setPower(e.target.value));$('shoot-btn').onclick=()=>won?showResult():shoot();$('putt-btn').onclick=()=>{if(b.moving||won)return;loft=false;updateHUD();};$('loft-btn').onclick=()=>{if(b.moving||won)return;loft=true;updateHUD();};$('undo-btn').onclick=undoShot;$('courses-btn').onclick=showMap;$('help-btn').onclick=showHelp;$('restart-btn').onclick=resetPrompt;$('close-modal').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=closeModal;
$('camera-btn').onclick=()=>{world.topView=!world.topView;$('camera-btn').style.color=world.topView?'#b9f58e':'';};$('rotate-left').onclick=()=>world.desiredAngle-=Math.PI/6;$('rotate-right').onclick=()=>world.desiredAngle+=Math.PI/6;$('sound-btn').onclick=()=>{muted=!muted;saved.sound=!muted;save();updateSound();if(!muted){initAudio();tone(660,.15);toast('音效已开启 · 祝你一杆进洞！');}};
function updateSound(){$('sound-btn').innerHTML=muted?'♪<span class="slash"></span>':'♪';$('sound-btn').title=muted?'开启音效':'关闭音效';$('sound-btn').setAttribute('aria-label',muted?'开启音效':'关闭音效');}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('modal').hidden)closeModal();charging=false;drag=null;updateHUD();return;}if(!$('modal').hidden){if(e.key==='Tab'){const nodes=[...$('modal').querySelectorAll('button:not(:disabled),[tabindex="0"]')];if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus();}}return;}if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();if(!e.repeat&&!b.moving&&!won){charging=true;chargeTime=0;setPower(5);initAudio();updateHUD();}}if(e.code==='KeyA'||e.code==='ArrowLeft'){e.preventDefault();angle-=.035;}if(e.code==='KeyD'||e.code==='ArrowRight'){e.preventDefault();angle+=.035;}if(e.code==='KeyC'&&!e.repeat)$('camera-btn').click();if(e.code==='KeyR'&&!e.repeat)resetPrompt();});
document.addEventListener('keyup',e=>{if(e.code==='Space'&&charging){e.preventDefault();shoot();}});window.addEventListener('blur',()=>{charging=false;drag=null;updateHUD();});document.addEventListener('visibilitychange',()=>{if(document.hidden){charging=false;drag=null;accumulator=0;updateHUD();}});window.addEventListener('resize',world.resize);
function physics(dt){const events=stepBall(b,c,dt,time);for(const ev of events){if(ev==='hole'){completeHole();return;}if(ev==='wall'){tone(140,.055,'triangle',.025);}if(['obstacle','bumper','guardian'].includes(ev)){collisions++;if(ev==='guardian')guardianHits++;tone(200,.07,'triangle',.05);burst(world,b.x,b.y,b.z,0xdcc1ee,5);}if(ev==='portal'){portalUsed=true;tone(740,.35,'sine',.06);burst(world,b.x,.5,b.z,0xbbafff,25);toast('虫洞穿梭！欢迎来到另一边。');}if(ev==='boost'){boosted=true;tone(440,.23,'sawtooth',.035);toast('彗星加速！');}if(ev==='jump'){tone(520,.2,'sine',.05);}if(ev==='out'){b=newBall([lastSafe.x,lastSafe.z]);strokes++;world.ballMesh.visible=true;toast('飞出轨道 · 返回击球点，罚 1 杆');tone(150,.3,'triangle',.07);updateHUD();}if(ev==='stop')updateHUD();}
 if(!won&&!b.falling)world.stars.forEach((s,i)=>{if(!collected.has(i)&&Math.hypot(b.x-s.position.x,b.z-s.position.z)<.67&&b.y<1.8){collected.add(i);s.visible=false;tone(780+collected.size*140,.19,'sine',.07);burst(world,s.position.x,.9,s.position.z,0xffd66d,18);updateHUD();toast(collected.size===3?'三颗星星集齐！麻薯的口袋闪闪发光。':'收集到一颗星星 ✦');}});
}
function renderAim(){world.aim.visible=!b.moving&&!won;world.cursor.visible=!b.moving&&!won;if(!world.aim.visible)return;const length=2.4+power*.055;world.aimDots.forEach((d,i)=>{let ratio=(i+1)/world.aimDots.length,l=length*ratio;d.position.set(b.x+Math.sin(angle)*l,.23+(loft?Math.sin(ratio*Math.PI)*1.8:0),b.z-Math.cos(angle)*l);d.scale.setScalar(i%3===0?1.2:.85);});world.cursor.position.set(b.x,.16,b.z);world.cursor.scale.setScalar(1+Math.sin(time*3)*.045);}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(document.hidden)return;const active=$('modal').hidden;time+=active?dt:0;if(active){swing=Math.max(0,swing-dt);if(charging){chargeTime+=dt;setPower(5+95*(.5-.5*Math.cos(Math.min(chargeTime,1.65)/1.65*Math.PI)));}accumulator+=dt;let steps=0;while(accumulator>=1/120&&steps++<8){physics(1/120);accumulator-=1/120;}}renderAim();animateWorld(world,b,c,time,dt,{won,swing});const pos=new T.Vector3(b.x,2.9,b.z).project(world.camera);$('ball-label').style.left=(pos.x*.5+.5)*innerWidth+'px';$('ball-label').style.top=((-pos.y*.5+.5)*innerHeight-document.querySelector('.topbar').offsetHeight-5)+'px';}
loadLevel(0);updateSound();requestAnimationFrame(frame);setTimeout(()=>$('loading').classList.add('hidden'),450);
