import * as THREE from 'three';
import './style.css';
const $=s=>document.querySelector(s);
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x28574e);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x28574e,.024);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,140);
scene.add(new THREE.HemisphereLight(0xe6f5bd,0x174e48,2.6));const sun=new THREE.DirectionalLight(0xffebbc,3.5);sun.position.set(-12,25,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30});sun.shadow.bias=-.001;scene.add(sun);
const mat=(color,roughness=.7)=>new THREE.MeshStandardMaterial({color,roughness});const green=mat(0x72a833),belly=mat(0xd8e993),dark=mat(0x183526),white=mat(0xf3f4d9),stemMat=mat(0x466c35);const world=new THREE.Group();scene.add(world);
function sphere(parent,x,y,z,sx,sy,sz,material){const m=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),material);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;parent.add(m);return m;}
function line(points,color,opacity=1){return new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity}));}
const water=new THREE.Mesh(new THREE.PlaneGeometry(240,240,110,110),new THREE.MeshStandardMaterial({color:0x266b62,roughness:.29,metalness:.48,transparent:true,opacity:.94}));water.rotation.x=-Math.PI/2;water.position.y=-.12;water.receiveShadow=true;scene.add(water);
const waterBase=water.geometry.attributes.position.array.slice();
const frog=new THREE.Group();scene.add(frog);sphere(frog,0,.5,0,.56,.43,.69,green);sphere(frog,0,.38,.39,.42,.3,.26,belly);sphere(frog,0,.78,.29,.57,.36,.42,green);[-1,1].forEach(s=>{sphere(frog,s*.34,1.01,.4,.22,.25,.2,green);sphere(frog,s*.34,1.055,.535,.155,.17,.105,white);sphere(frog,s*.34,1.07,.622,.077,.1,.035,dark);sphere(frog,s*.32,1.105,.65,.022,.029,.011,white);sphere(frog,s*.49,.22,-.24,.31,.22,.39,green);sphere(frog,s*.51,.10,.1,.3,.10,.3,green);sphere(frog,s*.36,.23,.5,.105,.2,.11,green);for(let j=0;j<3;j++)sphere(frog,s*(.28+j*.1),.08,.68,.09,.055,.16,green);sphere(frog,s*.45,.74,.59,.08,.045,.025,mat(0xc4d56d));});frog.add(line([new THREE.Vector3(-.21,.67,.667),new THREE.Vector3(0,.625,.702),new THREE.Vector3(.21,.67,.667)],0x385827));
const shadow=new THREE.Mesh(new THREE.CircleGeometry(.65,40),new THREE.MeshBasicMaterial({color:0x102e20,transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
let pads=[],decor=[],drops=[],ripples=[],chapter=0,index=0,target=1,lives=3,score=0,jumps=0,elapsed=0,charging=false,power=0,flight=null,paused=false,finished=false,checkpoint=0,sink=0,started=false,sound=true,audioCtx=null;let toastUntil=8,phase=0;const chapterNames=['晨曦池塘','浮光水湾','萤火秘境'];
const route=[[-1,4,2.65],[2.2,.4,1.85],[-1.6,-3.6,1.7],[3,-7.3,1.85],[-.8,-11.1,2.3],[-4.3,-15,1.75],[.5,-18.5,1.8],[4.4,-22.6,1.65],[0,-27,2.8]];
function lily(x,z,r,type='normal',n=0){const group=new THREE.Group();group.position.set(x,.16,z);const shape=new THREE.Shape();shape.moveTo(.05,.02);for(let i=0;i<=90;i++){const a=.23+i/90*(Math.PI*2-.48);const rr=r*(1+Math.sin(a*7+n)*.018);shape.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}shape.lineTo(.05,.02);const material=mat(type==='sink'?0xa6a24c:type==='moving'?0x64a669:0x619749);const geo=new THREE.ExtrudeGeometry(shape,{depth:.13,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.07,bevelThickness:.055});geo.rotateX(-Math.PI/2);const leaf=new THREE.Mesh(geo,material);leaf.castShadow=true;leaf.receiveShadow=true;group.add(leaf);for(let k=0;k<11;k++){const a=.3+k/11*5.65;const v=[new THREE.Vector3(.1,.215,.02),new THREE.Vector3(Math.cos(a)*r*.48,.22,-Math.sin(a)*r*.48),new THREE.Vector3(Math.cos(a)*r*.92,.21,-Math.sin(a)*r*.92)];group.add(line(v,0xc1d27b,.23));}group.rotation.y=n*1.76;world.add(group);return {group,x,z,r,type,n,baseY:.16,leaf};}
function lotus(parent,scale=1){const g=new THREE.Group();g.scale.setScalar(scale);for(let k=0;k<11;k++){const a=k/11*Math.PI*2;const p=sphere(g,Math.cos(a)*.43,.32,Math.sin(a)*.43,.2,.16,.46,mat(k%2?0xeeb6b4:0xf8d4c1));p.rotation.y=-a+Math.PI/2;p.rotation.z=.25;}for(let k=0;k<7;k++){const a=k/7*Math.PI*2;const p=sphere(g,Math.cos(a)*.21,.48,Math.sin(a)*.21,.14,.3,.28,mat(0xffe6cc));p.rotation.y=-a;}sphere(g,0,.5,0,.16,.17,.16,mat(0xe7c85e));parent.add(g);return g;}
let seed=9;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function disposeWorld(){world.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});world.clear();}
function init(c=0){chapter=c;disposeWorld();pads=[];drops=[];decor=[];index=0;target=1;lives=3;score=0;jumps=0;elapsed=0;charging=false;flight=null;paused=false;finished=false;checkpoint=0;sink=0;power=0;started=false;seed=39+c*14;$('#modal').classList.add('hidden');$('#pause').textContent='Ⅱ';
route.forEach(([x,z,r],i)=>{const type=i===4||i===8?'checkpoint':i>0&&((i+c)%4===2)?'moving':i>0&&((i+c)%4===3)?'sink':'normal';const p=lily(x,z,r,type,i);pads.push(p);const halo=new THREE.Mesh(new THREE.RingGeometry(r+ .32,r+ .34,80),new THREE.MeshBasicMaterial({color:0x9bc9a5,transparent:true,opacity:.13,side:THREE.DoubleSide,depthWrite:false}));halo.rotation.x=-Math.PI/2;halo.position.set(x,-.015,z);world.add(halo);if(type==='checkpoint'){const f=lotus(p.group,i===8?1.3:.8);f.position.set(-.9,.1,.3);}if(i>0){const d=new THREE.Group();const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.22),new THREE.MeshStandardMaterial({color:0xe4fba4,emissive:0x9da847,emissiveIntensity:.8,metalness:.4,roughness:.1}));d.add(mesh);p.group.add(d);d.position.y=1.1;drops.push({g:d,p,collected:false});}});
for(let i=0;i<55;i++){const z=10-rand()*65;const x=(rand()<.5?-1:1)*(8+rand()*17);const p=lily(x,z,.5+rand()*1.4,'normal',i);decor.push(p);if(i%5===0)lotus(p.group,.7+rand()*.4);}
for(let i=0;i<90;i++){const x=(rand()<.5?-1:1)*(13+rand()*17),z=15-rand()*75,h=1+rand()*3;const g=new THREE.Group();g.position.set(x,0,z);const reed=new THREE.Mesh(new THREE.CylinderGeometry(.025,.07,h,5),stemMat);reed.position.y=h/2;g.add(reed);if(i%3===0)sphere(g,0,h,0,.12,.42,.12,mat(0x655438));else{const blade=new THREE.Mesh(new THREE.ConeGeometry(.19,h,4),mat(0x477343));blade.position.set(.2,h*.58,0);blade.rotation.z=-.2;g.add(blade);}world.add(g);}
frog.position.copy(pads[0].group.position);frog.rotation.y=Math.PI;camera.position.set(13,17,24);updateUI();setTarget(1);toast('点击前方荷叶瞄准，按住空格蓄力',7);scene.fog.color.setHex([0x28574e,0x284f58,0x173b49][c]);renderer.setClearColor(scene.fog.color);water.material.color.setHex([0x266b62,0x286478,0x214f69][c]);$('.chapter-list').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===c));}
const ring=new THREE.Mesh(new THREE.RingGeometry(1,1.025,80),new THREE.MeshBasicMaterial({color:0xe2f5a5,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;scene.add(ring);const marker=new THREE.Mesh(new THREE.RingGeometry(.18,.23,40),new THREE.MeshBasicMaterial({color:0xe5fab1,side:THREE.DoubleSide,transparent:true,opacity:.9}));marker.rotation.x=-Math.PI/2;scene.add(marker);const arc=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xd7edab,dashSize:.13,gapSize:.15,transparent:true,opacity:.5}));scene.add(arc);
const particles=new THREE.BufferGeometry();const points=[];for(let i=0;i<170;i++)points.push((Math.random()-.5)*50,Math.random()*6+.3,12-Math.random()*65);particles.setAttribute('position',new THREE.Float32BufferAttribute(points,3));const fireflies=new THREE.Points(particles,new THREE.PointsMaterial({color:0xedecad,size:.055,transparent:true,opacity:.75}));scene.add(fireflies);
const dragonflies=[];for(let i=0;i<3;i++){const g=new THREE.Group();sphere(g,0,0,0,.055,.055,.38,mat(0x79cbd1));for(let s of [-1,1])for(let a of [-1,1]){const wing=sphere(g,s*.32,.04,a*.12,.35,.015,.095,new THREE.MeshStandardMaterial({color:0xc3f5eb,transparent:true,opacity:.5,metalness:.4}));wing.rotation.y=a*s*.25;}scene.add(g);dragonflies.push(g);}
function beep(freq=440,dur=.1){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audioCtx.currentTime+dur);g.gain.setValueAtTime(.07,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
function toast(t,d=3){$('#toast').textContent=t;toastUntil=phase+d;$('#toast').style.opacity=1;}
function updateUI(){$('#chapterName').textContent=`第${['一','二','三'][chapter]}章 · ${chapterNames[chapter]}`;$('#level').textContent=`${String(index+1).padStart(2,'0')} / 09`;$('#score').textContent=String(score).padStart(2,'0');$('#lives').textContent='♥ '.repeat(lives)+'♡ '.repeat(3-lives);$('#jumpCount').textContent=`${jumps} 次跳跃`;$('#landName').innerHTML=(index===0?'启程之叶':index===8?'彼岸莲台':pads[index].type==='checkpoint'?'莲花驿站':pads[index].type==='sink'?'将沉的枯叶':pads[index].type==='moving'?'随波之叶':`第 ${index+1} 片荷叶`)+`<small>${index===0?'YOUR ADVENTURE STARTS HERE':pads[index].type==='sink'?'KEEP MOVING · 4 SECONDS':'ONE LEAP CLOSER TO THE HORIZON'}</small>`;}
function setTarget(i){if(flight||finished)return;target=THREE.MathUtils.clamp(i,Math.max(0,index-1),Math.min(8,index+2));if(target===index)target=Math.min(index+1,8);const p=pads[target];ring.scale.setScalar(p.r+ .18);toast(p.type==='moving'?'漂流荷叶会移动，留意落点':p.type==='sink'?'枯叶只能停留 4 秒，别停下！':p.type==='checkpoint'?'莲花驿站 · 抵达后恢复勇气并保存进度':'蓄力到浅色区间，轻巧落在荷叶中央',3);}
function begin(){if(paused||flight||finished||charging)return;charging=true;power=0;started=true;beep(280,.06);}
function predicted(p){const to=pads[target].group.position.clone();const delta=to.sub(frog.position);delta.y=0;return frog.position.clone().add(delta.multiplyScalar(.36+p*.98));}
function release(){if(!charging)return;charging=false;const end=predicted(power);end.y=.17;flight={from:frog.position.clone(),end,t:0,duration:.82+power*.35,height:2.4+power*2};jumps++;frog.scale.set(1,1,1);frog.rotation.y=Math.atan2(end.x-frog.position.x,end.z-frog.position.z);beep(580,.18);updateUI();}
function ripple(x,z,color=0xb8e0b7){const m=new THREE.Mesh(new THREE.RingGeometry(.3,.34,50),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.04,z);scene.add(m);ripples.push({m,age:0});}
function fail(reason){ripple(frog.position.x,frog.position.z);lives--;flight=null;charging=false;power=0;beep(120,.35);if(lives<=0){finished=true;updateUI();showModal('再试一次，风会帮你',`<p>这次收集了 <b>${score}</b> 颗露珠，跳跃 <b>${jumps}</b> 次。<br>小小失足，也是冒险的一部分。</p>`,'重新启程 ↗',()=>init(chapter));return;}index=checkpoint;sink=0;frog.position.copy(pads[index].group.position);setTarget(index+1);updateUI();toast(reason+' · 已回到莲花存档点',4);}
function land(){const pos=frog.position;const hit=pads.findIndex(p=>Math.hypot(pos.x-p.group.position.x,pos.z-p.group.position.z)<p.r*.91&&p.group.position.y>-.3);if(hit<0){fail('扑通！落入水中');return;}index=hit;frog.position.y=pads[index].group.position.y;flight=null;sink=0;ripple(pos.x,pos.z);const d=drops.find(d=>d.p===pads[index]);if(d&&!d.collected){d.collected=true;d.g.visible=false;score++;beep(850,.22);toast('露珠 +1 · 漂亮的一跃！');}if(pads[index].type==='checkpoint'){checkpoint=index;lives=3;toast('莲花存档成功 · 勇气已恢复',4);}updateUI();if(index===8){finished=true;const bestKey=`lilybound-best-${chapter}`;let best;try{best=Number(localStorage.getItem(bestKey))||Infinity;if(elapsed<best)localStorage.setItem(bestKey,String(Math.floor(elapsed)));}catch{}showModal(chapter===2?'你把整个夏天，跳成了诗':'抵达彼岸，新的风景在等你',`<p>完成「${chapterNames[chapter]}」</p><p>◆ ${score} / 8 颗露珠　·　${jumps} 次跳跃　·　${formatTime(elapsed)}</p><p>${score===8?'完美收集！荷塘里的每一滴晨光，都与你相遇。':'还有露珠藏在来时的荷叶上，随时欢迎回来探索。'}</p>`,chapter<2?'前往下一片水域 ↗':'再游一次荷塘 ↗',()=>init((chapter+1)%3));}else setTarget(Math.min(index+1,8));}
function showModal(title,html,button,action){paused=true;charging=false;frog.scale.set(1,1,1);$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;$('#modalAction').textContent=button;$('#modalAction').onclick=()=>{$('#modal').classList.add('hidden');paused=false;action?.();};$('#modal').classList.remove('hidden');}
function pause(){if(finished)return;if(paused){$('#modal').classList.add('hidden');paused=false;return;}showModal('在荷叶上，歇一会儿',`<p>风还在吹，荷塘会等你。<br>当前进度：第 ${index+1} 片荷叶 · ${score} 颗露珠</p>`,'继续冒险 ↗');}
function help(){showModal('每一跃，都有小技巧',`<p class="note"><b>01 / 瞄准</b><br>点击前方荷叶，或按 ← → / A D 切换目标。</p><p class="note"><b>02 / 起跳</b><br>按住空格，蓄力至浅色区间后松开。虚线显示真实落点；蓄力不足或过度都会影响距离。</p><p class="note"><b>03 / 探索</b><br>收集全部 8 颗露珠。漂流叶随波移动，枯叶 4 秒后下沉。莲花恢复勇气并保存进度。第二、三章小心低飞的蜻蜓！</p>`,'明白了，出发 ↗');}
$('#help').onclick=help;$('#pause').onclick=pause;$('#reset').onclick=()=>init(chapter);$('#sound').onclick=()=>{sound=!sound;$('#sound').classList.toggle('off',!sound);$('#sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');if(sound)beep();};document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>init(Number(b.dataset.chapter)));
window.addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape')pause();if(e.code==='KeyR')init(chapter);if(paused||finished)return;if(e.code==='Space')begin();if(['ArrowRight','KeyD'].includes(e.code))setTarget(target+1);if(['ArrowLeft','KeyA'].includes(e.code))setTarget(target-1);});window.addEventListener('keyup',e=>{if(e.code==='Space')release();});window.addEventListener('blur',()=>{if(!paused&&!finished)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&!finished)pause();});$('#touchJump').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);begin();});$('#touchJump').addEventListener('pointerup',release);$('#touchJump').addEventListener('pointercancel',()=>{charging=false;power=0;});
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let drag=null,orbit=0;renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,orbit};});renderer.domElement.addEventListener('pointermove',e=>{if(drag)orbit=THREE.MathUtils.clamp(drag.orbit+(e.clientX-drag.x)*.002,-.5,.5);});renderer.domElement.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<8&&!paused&&!finished){mouse.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(pads.map(p=>p.leaf));if(hits.length){const i=pads.findIndex(p=>p.leaf===hits[0].object);if(i!==index&&Math.abs(i-index)<=2)setTarget(i);else toast('请选择相邻的荷叶，最远可以跨越一片');}}drag=null;});window.addEventListener('pointerup',()=>drag=null);
function formatTime(v){return `${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}`;}window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
const clock=new THREE.Clock();let sim=0;init();
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);phase+=dt;if(!paused){sim+=dt;if(started&&!finished)elapsed+=dt;for(const p of [...pads,...decor]){p.group.position.y=.16+Math.sin(sim*1.25+p.n)*.055;if(p.type==='moving'){p.group.position.x=p.x+Math.sin(sim*(.65+chapter*.18)+p.n)*(.65+chapter*.3);p.group.position.z=p.z+Math.cos(sim*.6+p.n)*.3;}}if(!flight&&!finished){const p=pads[index];frog.position.x+= (p.group.position.x-frog.position.x)*Math.min(1,dt*5);frog.position.z+=(p.group.position.z-frog.position.z)*Math.min(1,dt*5);frog.position.y=p.group.position.y;if(p.type==='sink'){sink+=dt;p.group.position.y-=Math.max(0,sink-1.8)*.23;frog.position.y=p.group.position.y;if(sink>3)toast(`荷叶正在下沉！${Math.max(0,4-sink).toFixed(1)} 秒`,.1);if(sink>4)fail('枯叶沉入水中');}if(charging){power=Math.min(1,power+dt*.6);frog.scale.set(1+power*.16,1-power*.32,1+power*.1);$('#powerText').textContent=`${Math.round(power*100)}% ${power>.57&&power<.75?'· 就是现在！':''}`;}else{power=0;frog.scale.set(1,1+Math.sin(sim*3)*.025,1);}const end=predicted(charging?power:.653);marker.position.copy(end);marker.position.y=.4;const pts=[];for(let i=0;i<=32;i++){const t=i/32;const p=frog.position.clone().lerp(end,t);p.y+=Math.sin(t*Math.PI)*(2.4+(charging?power:.653)*2)+.25;pts.push(p);}arc.geometry.dispose();arc.geometry=new THREE.BufferGeometry().setFromPoints(pts);arc.computeLineDistances();}if(flight){flight.t+=dt/flight.duration;const t=Math.min(flight.t,1);frog.position.lerpVectors(flight.from,flight.end,t);frog.position.y+=Math.sin(Math.PI*t)*flight.height;frog.rotation.x=Math.sin(t*Math.PI*2)*.18;if(t>=1){frog.rotation.x=0;land();}}for(let i=0;i<dragonflies.length;i++){const d=dragonflies[i],z=-7-i*9;d.position.set(Math.sin(sim*(.65+i*.15)+i)*6,chapter===0?2.7:1.05+Math.sin(sim*1.4+i)*.35,z+Math.cos(sim*.8+i));d.rotation.y=Math.cos(sim*.7+i);d.children.forEach((c,j)=>{if(j>0)c.rotation.z=Math.sin(sim*55)*.17;});if(chapter>0&&started&&!finished&&frog.position.distanceTo(d.position)<.63)fail('被巡游蜻蜓撞到了');}}
for(const d of drops){d.g.position.y=1.05+Math.sin(sim*2+d.p.n)*.15;d.g.rotation.y=sim;}ring.position.copy(pads[target].group.position);ring.position.y+=.21;ring.material.opacity=.4+Math.sin(phase*3)*.15;ring.visible=!flight&&!finished;arc.visible=marker.visible=!flight&&!finished;shadow.position.set(frog.position.x,.34,frog.position.z);shadow.scale.setScalar(1+frog.position.y*.09);shadow.material.opacity=Math.max(.03,.22-frog.position.y*.027);for(let i=ripples.length-1;i>=0;i--){const r=ripples[i];r.age+=dt;r.m.scale.setScalar(1+r.age*3);r.m.material.opacity=Math.max(0,.5-r.age*.25);if(r.age>2){scene.remove(r.m);r.m.geometry.dispose();r.m.material.dispose();ripples.splice(i,1);}}const positions=water.geometry.attributes.position;for(let i=0;i<positions.count;i++)positions.array[i*3+2]=Math.sin(waterBase[i*3]*.55+sim*.55)*.035+Math.cos(waterBase[i*3+1]*.7+sim*.7)*.025;positions.needsUpdate=true;water.geometry.computeVertexNormals();fireflies.rotation.y=Math.sin(sim*.07)*.04;
const focusZ=frog.position.z-5;const narrow=innerWidth<600;const desired=new THREE.Vector3(12*Math.cos(orbit)+Math.sin(orbit)*18,narrow?21:17,focusZ+23*Math.cos(orbit));camera.position.lerp(desired,dt*1.8);camera.lookAt(narrow?-1:-2.7,0,focusZ);$('#powerFill').style.width=`${power*100}%`;if(!charging)$('#powerText').textContent=flight?'乘风而起…':'准备好了吗？';$('#timer').textContent=formatTime(elapsed);$('#toast').style.opacity=phase<toastUntil?'1':'0';renderer.render(scene,camera);}
animate();
// A read-only state snapshot is useful for automated smoke checks.
window.__lilybound={state:()=>({chapter,index,target,lives,score,jumps,elapsed,paused,finished,charging,flying:!!flight}),get renderer(){return renderer;}};
