import * as THREE from './vendor/three.module.js';
export class OceanScene{
 constructor(container){
  this.container=container;this.mode='chase';this.orbit={yaw:1.04,pitch:.19,distance:77};this.drag=false;this.shipMeshes=new Map();this.torpedoMeshes=new Map();this.effectMeshes=[];this.clock=0;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#0a272b');this.scene.fog=new THREE.FogExp2('#0a272b',.0038);
  this.camera=new THREE.PerspectiveCamera(45,1,.1,2600);
  try{this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(err){container.innerHTML='<div class="webgl-error">此设备未开启 WebGL，仍可使用「战术海图」进行作战。</div>';this.error=true;return}
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;container.appendChild(this.renderer.domElement);
  this.scene.add(new THREE.HemisphereLight(0x81c9cc,0x06131b,2.1));const sun=new THREE.DirectionalLight(0xa6e7e7,3.5);sun.position.set(-90,160,-90);this.scene.add(sun);const rim=new THREE.DirectionalLight(0x4ac6ad,2);rim.position.set(80,20,60);this.scene.add(rim);
  this.player=this.makeSub(0x314546,true);this.scene.add(this.player);
  const floorG=new THREE.PlaneGeometry(2300,2300,70,70);floorG.rotateX(-Math.PI/2);const pos=floorG.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,-155+Math.sin(x*.009)*10+Math.cos(z*.008)*11+Math.sin(x*.025+z*.021)*3)}floorG.computeVertexNormals();this.floor=new THREE.Mesh(floorG,new THREE.MeshStandardMaterial({color:0x143a3a,roughness:1,flatShading:true}));this.scene.add(this.floor);
  const grid=new THREE.GridHelper(1800,60,0x34665d,0x1c423f);grid.position.y=-143;grid.material.transparent=true;grid.material.opacity=.22;this.scene.add(grid);
  const surfaceG=new THREE.PlaneGeometry(2600,2600,55,55);surfaceG.rotateX(-Math.PI/2);this.surface=new THREE.Mesh(surfaceG,new THREE.MeshStandardMaterial({color:0x28565a,transparent:true,opacity:.30,side:THREE.DoubleSide,roughness:.25,metalness:.2}));this.surface.position.y=0;this.scene.add(this.surface);
  const layer=new THREE.Mesh(new THREE.PlaneGeometry(2000,2000),new THREE.MeshBasicMaterial({color:0x3bafa3,transparent:true,opacity:.03,side:THREE.DoubleSide,depthWrite:false}));layer.rotation.x=-Math.PI/2;layer.position.y=-54;this.scene.add(layer);
  const particleG=new THREE.BufferGeometry();const particles=new Float32Array(2100);for(let i=0;i<particles.length;i+=3){particles[i]=(Math.random()-.5)*900;particles[i+1]=Math.random()*155-150;particles[i+2]=(Math.random()-.5)*900}particleG.setAttribute('position',new THREE.BufferAttribute(particles,3));this.particles=new THREE.Points(particleG,new THREE.PointsMaterial({color:0x9dd4c8,size:.32,transparent:true,opacity:.42}));this.scene.add(this.particles);
  this.rayGroup=new THREE.Group();for(let i=0;i<9;i++){const g=new THREE.CylinderGeometry(1,7,180,5,1,true);const ray=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x82dfcb,transparent:true,opacity:.018,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));ray.position.set(-180+i*65,-60,-160);ray.rotation.z=-.35;this.rayGroup.add(ray)}this.scene.add(this.rayGroup);
  this.pingGroup=new THREE.Group();this.scene.add(this.pingGroup);this.fxGroup=new THREE.Group();this.scene.add(this.fxGroup);
  const wakeGeo=new THREE.BufferGeometry();wakeGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(240),3));this.wake=new THREE.Points(wakeGeo,new THREE.PointsMaterial({color:0xc3e9dc,size:.35,transparent:true,opacity:.26}));this.scene.add(this.wake);
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();const c=this.renderer.domElement;c.addEventListener('pointerdown',e=>{this.drag=true;this.last={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!this.drag)return;this.orbit.yaw-=(e.clientX-this.last.x)*.007;this.orbit.pitch=Math.max(-.12,Math.min(.9,this.orbit.pitch+(e.clientY-this.last.y)*.005));this.last={x:e.clientX,y:e.clientY}});c.addEventListener('pointerup',()=>this.drag=false);c.addEventListener('wheel',e=>{e.preventDefault();this.orbit.distance=Math.max(50,Math.min(230,this.orbit.distance+e.deltaY*.08))},{passive:false});
 }
 makeSub(color,detail=false){const group=new THREE.Group();const metal=new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.7});const dark=new THREE.MeshStandardMaterial({color:0x182a2e,roughness:.55,metalness:.6});const hull=new THREE.Mesh(new THREE.CapsuleGeometry(3.6,25,12,28),metal);hull.rotation.x=Math.PI/2;group.add(hull);const top=new THREE.Mesh(new THREE.CapsuleGeometry(2.6,22,8,20),dark);top.rotation.x=Math.PI/2;top.scale.y=.95;top.position.y=1.4;group.add(top);
  const tower=new THREE.Mesh(new THREE.BoxGeometry(3.4,5.3,7.5),metal);tower.position.set(0,4.2,-3);group.add(tower);const cap=new THREE.Mesh(new THREE.CylinderGeometry(1.7,1.7,7.5,14),metal);cap.rotation.x=Math.PI/2;cap.position.set(0,6.8,-3);group.add(cap);
  for(let i=0;i<3;i++){const mast=new THREE.Mesh(new THREE.CylinderGeometry(.13,.18,3.5+i*.6,8),dark);mast.position.set((i-1)*.55,9,-4+i);group.add(mast)}
  const fin=new THREE.Mesh(new THREE.BoxGeometry(12,.35,2.4),metal);fin.position.set(0,2,-1);group.add(fin);const stern=new THREE.Mesh(new THREE.BoxGeometry(10,.45,4),metal);stern.position.z=13;group.add(stern);const rudder=new THREE.Mesh(new THREE.BoxGeometry(.45,7,4),metal);rudder.position.set(0,0,13);group.add(rudder);
  const prop=new THREE.Group();for(let i=0;i<7;i++){const blade=new THREE.Mesh(new THREE.BoxGeometry(.55,3.3,1),new THREE.MeshStandardMaterial({color:0x766545,metalness:.9,roughness:.3}));blade.position.y=1.8;const pivot=new THREE.Group();pivot.rotation.z=i*Math.PI*2/7;pivot.add(blade);prop.add(pivot)}prop.position.z=18;group.add(prop);group.userData.prop=prop;
  if(detail){const seamMat=new THREE.MeshBasicMaterial({color:0x5b7774,transparent:true,opacity:.2});for(let z=-12;z<15;z+=4){const seam=new THREE.Mesh(new THREE.TorusGeometry(3.61,.02,4,36),seamMat);seam.position.z=z;group.add(seam)}const light=new THREE.Mesh(new THREE.SphereGeometry(.24,8,8),new THREE.MeshBasicMaterial({color:0x8bffc0}));light.position.set(-1.9,5.8,-5.5);group.add(light);for(let i=0;i<5;i++){const hatch=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,.08,12),dark);hatch.position.set(0,3.7,3+i*2.2);group.add(hatch)}}return group;
 }
 makeShip(type){if(type==='sub')return this.makeSub(0x3f5555);const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x465b5e,metalness:.5,roughness:.6});const hull=new THREE.Mesh(new THREE.CapsuleGeometry(4,30,4,12),mat);hull.rotation.x=Math.PI/2;hull.scale.x=.95;hull.scale.z=.7;g.add(hull);const deck=new THREE.Mesh(new THREE.BoxGeometry(7,2,26),mat);deck.position.y=2;g.add(deck);const bridge=new THREE.Mesh(new THREE.BoxGeometry(5,5,7),mat);bridge.position.set(0,5,-2);g.add(bridge);if(type==='cargo'){for(let i=0;i<4;i++){const box=new THREE.Mesh(new THREE.BoxGeometry(5.5,3,3.7),new THREE.MeshStandardMaterial({color:i%2?0x665b47:0x536c66}));box.position.set(0,5,4+i*4);g.add(box)}}else{const mast=new THREE.Mesh(new THREE.CylinderGeometry(.18,.3,10),mat);mast.position.set(0,12,-3);g.add(mast)}return g}
 resize(){if(this.error)return;const w=this.container.clientWidth,h=this.container.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 setMode(mode){this.mode=mode;this.resize()}
 clearGroup(g){while(g.children.length){const c=g.children[0];g.remove(c);c.geometry?.dispose();c.material?.dispose()}}
 update(sim,dt){if(this.error)return;this.clock+=dt;if(this.sceneMission!==sim.mission.id){for(const m of this.shipMeshes.values()){this.scene.remove(m);m.traverse(c=>{c.geometry?.dispose();c.material?.dispose()})}this.shipMeshes.clear();this.sceneMission=sim.mission.id}const p=sim.player;this.player.position.set(p.x,-p.depth*.3,p.z);this.player.rotation.y=-p.heading*Math.PI/180;this.player.rotation.z=Math.sin(this.clock*.4)*.006;this.player.userData.prop.rotation.z+=dt*p.speed;
  for(const e of sim.enemies){let mesh=this.shipMeshes.get(e.id);if(!mesh){mesh=this.makeShip(e.type);this.shipMeshes.set(e.id,mesh);this.scene.add(mesh)}mesh.visible=e.alive&&(e.revealed>0||(e.confidence>.62&&sim.time-(e.lastContact?.time||0)<10));const contact=e.lastContact||e;mesh.position.set(contact.x,-contact.depth*.3+(e.type==='sub'?0:2.5),contact.z);mesh.rotation.y=-e.heading*Math.PI/180;mesh.traverse(c=>{if(c.isMesh){c.material.transparent=true;c.material.opacity=Math.min(.65,e.confidence*.65)}})}
  const target=new THREE.Vector3(p.x,-p.depth*.3,p.z);let wanted;
  if(this.mode==='periscope'){wanted=new THREE.Vector3(p.x,2,p.z+1);if(!this.initializedCamera){this.camera.position.copy(wanted);this.initializedCamera=true}this.camera.position.lerp(wanted,.07);this.camera.lookAt(p.x+Math.sin(p.heading*Math.PI/180)*200,2,p.z-Math.cos(p.heading*Math.PI/180)*200);this.scene.fog.density=.0015;this.surface.material.opacity=.87;this.scene.background.set('#52787d');this.player.visible=false;this.camera.fov=48}
  else{this.player.visible=true;this.camera.fov=45;const yaw=this.orbit.yaw-p.heading*Math.PI/180;wanted=new THREE.Vector3(p.x+Math.sin(yaw)*this.orbit.distance,-p.depth*.3+Math.sin(this.orbit.pitch)*this.orbit.distance+13,p.z+Math.cos(yaw)*this.orbit.distance);if(!this.initializedCamera){this.camera.position.copy(wanted);this.initializedCamera=true}this.camera.position.lerp(wanted,.055);this.camera.lookAt(target);this.scene.fog.density=.0038;this.surface.material.opacity=.3;this.scene.background.set('#0a272b')}
  this.camera.updateProjectionMatrix();const pos=this.surface.geometry.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,Math.sin(pos.getX(i)*.024+this.clock*.6)*1.2+Math.cos(pos.getZ(i)*.019+this.clock*.4)*1.1);pos.needsUpdate=true;
  this.particles.position.set(p.x,0,p.z);this.particles.rotation.y=this.clock*.003;this.rayGroup.position.set(p.x,0,p.z);const wp=this.wake.geometry.attributes.position;for(let i=0;i<wp.count;i++){const t=(i/80+this.clock*.09)%1;wp.setXYZ(i,p.x-Math.sin(p.heading*Math.PI/180)*(18+t*65)+(Math.sin(i*7)*t*4),-p.depth*.3+Math.cos(i*9)*t*3,p.z+Math.cos(p.heading*Math.PI/180)*(18+t*65)+Math.cos(i*7)*t*4)}wp.needsUpdate=true;this.wake.material.opacity=p.speed*.018;
  this.clearGroup(this.pingGroup);for(const pulse of sim.pulses){const ring=new THREE.Mesh(new THREE.RingGeometry(Math.max(0,pulse.r-1),pulse.r+1,90),new THREE.MeshBasicMaterial({color:0x86f5c1,side:THREE.DoubleSide,transparent:true,opacity:pulse.life*.11,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.set(pulse.x,-p.depth*.3,pulse.z);this.pingGroup.add(ring)}
  this.clearGroup(this.fxGroup);for(const t of sim.torpedoes){const m=new THREE.Mesh(new THREE.CapsuleGeometry(.35,3.3,3,6),new THREE.MeshBasicMaterial({color:t.hostile?0xff8a5c:0x94f2d0}));m.rotation.x=Math.PI/2;m.rotation.z=-t.heading*Math.PI/180;m.position.set(t.x,-t.depth*.3,t.z);this.fxGroup.add(m);if(t.trail.length>1){const g=new THREE.BufferGeometry().setFromPoints(t.trail.map(v=>new THREE.Vector3(v.x,-v.depth*.3,v.z)));this.fxGroup.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:t.hostile?0xe6885a:0x91d2c2,transparent:true,opacity:.4})))}}
  for(const e of sim.effects){const mesh=new THREE.Mesh(new THREE.SphereGeometry((2-e.life)*10+1,16,12),new THREE.MeshBasicMaterial({color:0xffb668,transparent:true,opacity:e.life*.3,wireframe:true}));mesh.position.set(e.x,-e.depth*.3,e.z);this.fxGroup.add(mesh)}
  for(const d of sim.decoys){const mesh=new THREE.Mesh(new THREE.SphereGeometry(3,12,8),new THREE.MeshBasicMaterial({color:0x62b4ef,transparent:true,opacity:.3,wireframe:true}));mesh.position.set(d.x,-d.depth*.3,d.z);this.fxGroup.add(mesh)}
  this.renderer.render(this.scene,this.camera);
 }
}
