import * as THREE from './vendor/three.module.min.js';
import {AMMO,LEVELS,GRAVITY,launch,pointAt,flightTime,segmentBox,explosionDamage,seeded} from './physics.js';
const $=id=>document.getElementById(id), origin={x:0,y:4.1,z:27};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('loading').innerHTML='<h2>战场需要 WebGL</h2><p>请使用开启硬件加速的现代浏览器打开。</p>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('world').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#9ea9a6');scene.fog=new THREE.FogExp2('#a3ada5',.0064);
const camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.3,420);
const hemi=new THREE.HemisphereLight(0xd8e5ee,0x5b6250,2.35);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffdfae,3.35);sun.position.set(-50,65,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-80;sun.shadow.camera.right=80;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;sun.shadow.camera.far=190;sun.shadow.bias=-.0006;sun.shadow.normalBias=.05;scene.add(sun);
const rim=new THREE.DirectionalLight(0xbad9dd,1.05);rim.position.set(30,30,-60);scene.add(rim);
const materials={};function mat(color,roughness=1,metalness=0){const key=color+':'+roughness+':'+metalness;return materials[key]??=(new THREE.MeshStandardMaterial({color,roughness,metalness,flatShading:true}));}
const boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.IcosahedronGeometry(1,1);
function mesh(geo,material,x,y,z,parent=scene){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(x,y,z,w,h,d,color,parent=scene){const m=mesh(boxGeo,typeof color==='number'||typeof color==='string'?mat(color):color,x,y,z,parent);m.scale.set(w,h,d);return m;}
function beam(a,b,width,color,parent){const mid=new THREE.Vector3().addVectors(a,b).multiplyScalar(.5),m=box(mid.x,mid.y,mid.z,width,a.distanceTo(b),width,color,parent);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return m;}
let terrain=new THREE.Group(),fortress=new THREE.Group(),catapult=new THREE.Group();scene.add(terrain,fortress,catapult);
const blocks=[],debris=[],particles=[],projectiles=[],fires=[],flags=[],scorchMarks=[],rings=[];let core,coreGlow,arm,engineer,throwStone,rand=seeded(12),totalWalls=0,destroyedWalls=0,animTime=0,toastTimer=0,shake=0,shootAnim=0;
const state={level:0,core:210,health:100,maxHealth:100,ammo:[7,2,2,1],ammoType:0,yaw:0,elevation:36,power:56,shots:0,gold:0,score:0,phase:'ready',paused:false,follow:false,view:'siege',sound:false,upgrades:{power:0,armor:0,ammo:0},earned:[false,false,false,false,false],best:[0,0,0,0,0],settle:0,enemyShot:null};
try{const save=JSON.parse(localStorage.getItem('iron-siege-v1')||'null');if(save&&save.version===1){state.gold=Math.max(0,Number(save.gold)||0);for(const k of ['power','armor','ammo'])state.upgrades[k]=Math.max(0,Math.min(2,Number(save.upgrades?.[k])||0));state.earned=Array.from({length:5},(_,i)=>!!save.earned?.[i]);state.best=Array.from({length:5},(_,i)=>Math.max(0,Math.min(3,Number(save.best?.[i])||0)));state.level=Math.max(0,Math.min(4,Number(save.level)||0));}}catch{}
function save(){try{localStorage.setItem('iron-siege-v1',JSON.stringify({version:1,gold:state.gold,upgrades:state.upgrades,earned:state.earned,best:state.best,level:state.level}));}catch{}}
let audioCtx;
function sound(kind){if(!state.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),t=audioCtx.currentTime;osc.connect(gain);gain.connect(audioCtx.destination);if(kind==='fire'){osc.type='sawtooth';osc.frequency.setValueAtTime(140,t);osc.frequency.exponentialRampToValueAtTime(35,t+.28);gain.gain.setValueAtTime(.09,t);gain.gain.exponentialRampToValueAtTime(.001,t+.35);osc.start();osc.stop(t+.35);}else if(kind==='win'){osc.type='triangle';[392,493.9,587.3,784].forEach((v,i)=>osc.frequency.setValueAtTime(v,t+i*.15));gain.gain.setValueAtTime(.11,t);gain.gain.exponentialRampToValueAtTime(.001,t+.85);osc.start();osc.stop(t+.85);}else{osc.type='triangle';osc.frequency.setValueAtTime(kind==='hit'?75:240,t);osc.frequency.exponentialRampToValueAtTime(25,t+.35);gain.gain.setValueAtTime(.15,t);gain.gain.exponentialRampToValueAtTime(.001,t+.5);osc.start();osc.stop(t+.5);const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*.3,audioCtx.sampleRate),arr=buffer.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=(Math.random()*2-1)*(1-i/arr.length);const n=audioCtx.createBufferSource(),g=audioCtx.createGain();n.buffer=buffer;g.gain.value=.14;n.connect(g);g.connect(audioCtx.destination);n.start();}}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=3.2;}
function addTree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);terrain.add(g);mesh(new THREE.CylinderGeometry(.16*s,.28*s,3*s,5),mat(0x635941),0,1.5*s,0,g);for(let i=0;i<3;i++){const m=mesh(new THREE.ConeGeometry((2.2-i*.42)*s,(3.8-i*.3)*s,6),mat([0x455f56,0x506a5a,0x64765d][i]),0,(3.1+i*1.25)*s,0,g);m.rotation.y=rand()*3;}}
function addFlag(x,y,z,color=0xa85136,parent=fortress,scale=1){mesh(new THREE.CylinderGeometry(.055,.07,4.5*scale,6),mat(0x493e32),x,y+2*scale,z,parent);const geo=new THREE.PlaneGeometry(2.4*scale,1.3*scale,8,3),m=mesh(geo,new THREE.MeshStandardMaterial({color,side:THREE.DoubleSide,roughness:1,flatShading:true}),x+1.2*scale,y+3.2*scale,z,parent);flags.push({mesh:m,base:geo.attributes.position.array.slice(),phase:rand()*6});}
function tent(x,z,color,scale=1){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=-.25;terrain.add(g);const roof=mesh(new THREE.ConeGeometry(2.8*scale,3.5*scale,4),mat(color),0,1.75*scale,0,g);roof.rotation.y=Math.PI/4;beam(new THREE.Vector3(-2.5*scale,.1,1.8*scale),new THREE.Vector3(0,3.5*scale,0),.09,0x6c5b41,g);beam(new THREE.Vector3(2.5*scale,.1,1.8*scale),new THREE.Vector3(0,3.5*scale,0),.09,0x6c5b41,g);box(0,.8,2.02*scale,.55,1.5,.03,0x222e30,g);}
function buildTerrain(){const ground=mesh(new THREE.PlaneGeometry(700,700),mat(0x788575),0,-.12,0,terrain);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
const road=mesh(new THREE.PlaneGeometry(10,130,1,1),mat(0x99947b),0,-.09,-5,terrain);road.rotation.x=-Math.PI/2;road.rotation.z=.015;
for(let i=0;i<80;i++){const x=(rand()-.5)*210,z=(rand()-.5)*200;if(Math.abs(x)<17&&z<43&&z>-75)continue;const s=.35+rand()*1.4;const m=mesh(new THREE.IcosahedronGeometry(s,0),mat([0x929383,0x818c78,0x8d9684][i%3]),x,.25*s,z,terrain);m.scale.y=.5;m.rotation.set(rand(),rand(),rand());}
for(let i=0;i<36;i++){let x=(i%2===0?-1:1)*(25+rand()*65),z=-100+rand()*158;addTree(x,z,.65+rand()*.75);}
for(let i=0;i<26;i++){const a=i/26*Math.PI*2;const d=125+rand()*45,h=18+rand()*40;const m=mesh(new THREE.ConeGeometry(30+rand()*35,h,5),mat(i%3===0?0x879c91:0x768d86),Math.cos(a)*d,h*.38-4,Math.sin(a)*d-42,terrain);m.rotation.y=rand()*3;}
for(let i=0;i<240;i++){const x=(rand()-.5)*130,z=(rand()-.5)*145;if(Math.abs(x)<6)continue;const m=mesh(new THREE.ConeGeometry(.18,.7+rand()*.6,3),mat(i%3===0?0x9b9c73:0x687e63),x,.2,z,terrain);m.rotation.z=(rand()-.5)*.4;}
tent(-17,25,0x647d85,1.3);tent(-24,17,0x526b75,1);tent(20,30,0x8b836a,1);addFlag(-12,0,23,0x3e6778,terrain,1.3);for(let i=0;i<4;i++)box(-14+i%2*1.6,.55,17+Math.floor(i/2)*1.4,1.3,1.1,1.1,0x7b674c,terrain);
for(let j=0;j<2;j++){for(let i=0;i<7;i++){const x=(j?1:-1)*(14+i*1.7),z=37-i*.6;beam(new THREE.Vector3(x,.1,z-.8),new THREE.Vector3(x,1.4,z+.5),.18,0x63583e,terrain);beam(new THREE.Vector3(x,.1,z+.8),new THREE.Vector3(x,1.4,z-.5),.18,0x63583e,terrain);}}
}
function buildCatapult(){catapult.position.set(0,0,29);const wood=0x80613d,dark=0x4d4030,metal=0x454e4c;box(0,.7,0,3.8,.5,5.6,wood,catapult);for(const x of [-1.35,1.35]){box(x,1.1,0,.3,.3,5.4,dark,catapult);beam(new THREE.Vector3(x,1,-1.9),new THREE.Vector3(x,4,0),.35,wood,catapult);beam(new THREE.Vector3(x,1,1.9),new THREE.Vector3(x,4,0),.35,wood,catapult);for(const z of [-1.8,1.8]){const wheel=mesh(new THREE.CylinderGeometry(.82,.82,.34,12),mat(dark),x*1.5,.85,z,catapult);wheel.rotation.z=Math.PI/2;const rim=mesh(new THREE.TorusGeometry(.69,.07,5,12),mat(metal,.7,.3),x*1.65,.85,z,catapult);rim.rotation.y=Math.PI/2;for(let a=0;a<4;a++){const spoke=box(x*1.66,.85,z,.1,1.35,.11,wood,catapult);spoke.rotation.x=a*Math.PI/4;}}}
const ax=mesh(new THREE.CylinderGeometry(.2,.2,3.6,8),mat(metal),0,3.9,0,catapult);ax.rotation.z=Math.PI/2;arm=new THREE.Group();arm.position.set(0,3.9,0);catapult.add(arm);box(0,0,-1.1,.32,.38,5.3,wood,arm);box(0,-.65,1.45,1.2,1.25,.9,0x65665a,arm);const bowl=mesh(new THREE.CylinderGeometry(.72,.46,.35,8),mat(dark),0,.2,-3.4,arm);throwStone=mesh(sphereGeo,mat(0xb6b4a4),0,.7,-3.4,arm);throwStone.scale.setScalar(.47);arm.rotation.x=-.25;
for(let i=0;i<5;i++){const m=mesh(sphereGeo,mat(0xb3b1a2),3.4+(i%2)*.8,.35,1.1+Math.floor(i/2)*.8,catapult);m.scale.setScalar(.38);}
engineer=new THREE.Group();engineer.position.set(-3,.05,1);catapult.add(engineer);box(0,1.2,0,.65,.9,.4,0x406875,engineer);mesh(new THREE.IcosahedronGeometry(.28,1),mat(0xc2a481),0,1.98,0,engineer);const helmet=mesh(new THREE.SphereGeometry(.31,8,4,0,Math.PI*2,0,Math.PI*.55),mat(0x696c62,.7,.3),0,2.05,0,engineer);box(-.18,.42,0,.21,.8,.24,0x4e4b3d,engineer);box(.18,.42,0,.21,.8,.24,0x4e4b3d,engineer);beam(new THREE.Vector3(.35,1.55,0),new THREE.Vector3(.8,1.05,-.2),.2,0x406875,engineer);beam(new THREE.Vector3(-.35,1.55,0),new THREE.Vector3(-.48,.95,.1),.2,0x406875,engineer);
}
function block(x,y,z,w,h,d,type='wall',color){const lev=LEVELS[state.level],hp=type==='barrel'?15:type==='core'?lev.hp:type==='tower'?lev.wall*1.2:lev.wall;
const m=type==='barrel'?mesh(new THREE.CylinderGeometry(.65,.72,1.5,9),mat(0x79452e),x,y,z,fortress):box(x,y,z,w,h,d,color??[0xa7a38b,0x9a9c87,0xb3ac93,0x949985][Math.floor(rand()*4)],fortress);
const obj={mesh:m,x,y,z,w,h,d,type,hp,maxHp:hp,dead:false,min:{x:x-w/2,y:y-h/2,z:z-d/2},max:{x:x+w/2,y:y+h/2,z:z+d/2}};blocks.push(obj);if(type==='wall'||type==='tower')totalWalls++;
if(type==='barrel'){for(const off of [-.4,.4]){const band=mesh(new THREE.TorusGeometry(.7,.055,4,9),mat(0x41433b),x,y+off,z,fortress);band.rotation.x=Math.PI/2;obj.decor??=[];obj.decor.push(band);}const fuse=box(x,y+1,z,.12,.5,.12,0xc9b67d,fortress);obj.decor.push(fuse);}
return obj;}
function buildFortress(){const lev=LEVELS[state.level],z=lev.z;box(0,.12,z,33,.4,26,0x8d8f7c,fortress);box(0,.37,z,31,.25,24,0x787f6d,fortress);
const rows=5+(state.level>=2?1:0),front=z+9;for(let row=0;row<rows;row++){for(let i=-6;i<=6;i++){if(Math.abs(i)<=1&&row<3)continue;block(i*2.15,row*1.43+1.1,front,2.1,1.38,1.7);}}
for(let i=-6;i<=6;i+=2)block(i*2.15,rows*1.43+1,front,1.25,1.2,1.8);
for(let row=0;row<3;row++)for(let i=-1;i<=1;i++)block(i*1.48,1.1+row*1.4,front,1.43,1.34,1.1,'wall',0x776345);
for(const side of [-1,1]){for(let row=0;row<4;row++)for(let i=0;i<8;i++)block(side*14,1.1+row*1.43,z+7-i*2.1,1.7,1.38,2.05);for(let i=0;i<8;i+=2)block(side*14,6.85,z+7-i*2.1,1.8,1.2,1.25);
for(const dz of [9,-8]){for(let row=0;row<7+(state.level>=3?1:0);row++)for(let k=0;k<4;k++){const a=k*Math.PI/2;block(side*13+Math.cos(a)*1.3,1.1+row*1.4,z+dz+Math.sin(a)*1.3,2.25,1.35,2.25,'tower');}const ty=11+(state.level>=3?1.4:0);for(let a=0;a<4;a++){const m=block(side*13+(a%2?1.45:-1.45),ty,z+dz+(a<2?1.45:-1.45),1.2,1.3,1.2,'tower');}addFlag(side*13,ty,z+dz,0x9b4434,fortress,.8);}}
for(let row=0;row<4;row++)for(let i=-5;i<=5;i++)block(i*2.15,1.1+row*1.43,z-10,2.1,1.38,1.7);
core=block(0,4.5,z,5.8,8,5.8,'core',0x9b9682);box(0,8.75,z,6.8,.7,6.8,0xc0b397,fortress);core.decor=[fortress.children.at(-1)];for(let i=0;i<4;i++){const m=box((i%2?2.6:-2.6),9.65,z+(i<2?2.6:-2.6),1.25,1.5,1.25,0xb8ac8e,fortress);core.decor.push(m);}
const banner=box(0,5.7,z+2.96,1.65,4.5,.08,0xad533a,fortress);core.decor.push(banner);const emblem=mesh(new THREE.OctahedronGeometry(.52),mat(0xd2b673,.65,.2),0,5.9,z+3.08,fortress);emblem.scale.y=1.3;core.decor.push(emblem);for(const x of [-1.9,1.9]){const m=box(x,3.5,z+2.96,.4,1.1,.08,0x454b43,fortress);core.decor.push(m);}addFlag(0,9.8,z,0xaa5037,fortress,1.15);
coreGlow=new THREE.PointLight(0xffbe6c,6,16,2);coreGlow.position.set(0,5,z+5);fortress.add(coreGlow);
block(-4,1.3,z+5,1.4,1.5,1.4,'barrel');block(4,1.3,z+4,1.4,1.5,1.4,'barrel');if(state.level>0){block(0,1.3,z+6,1.4,1.5,1.4,'barrel');block(5.5,1.3,z,1.4,1.5,1.4,'barrel');}if(state.level>2)block(-5,1.3,z-1,1.4,1.5,1.4,'barrel');
}
const pathMaterial=new THREE.LineDashedMaterial({color:0xf5d493,dashSize:.5,gapSize:.48,transparent:true,opacity:.6});const pathLine=new THREE.Line(new THREE.BufferGeometry(),pathMaterial);scene.add(pathLine);
const dotGeo=new THREE.SphereGeometry(.085,5,4),dotGroup=new THREE.Group();scene.add(dotGroup);for(let i=0;i<46;i++)mesh(dotGeo,new THREE.MeshBasicMaterial({color:0xffdf9b,transparent:true,opacity:.75}),0,0,0,dotGroup);
const aimRing=mesh(new THREE.RingGeometry(1.25,1.38,48),new THREE.MeshBasicMaterial({color:0xf2d28e,transparent:true,opacity:.75,side:THREE.DoubleSide}),0,.06,-20);aimRing.rotation.x=-Math.PI/2;
const aimCross=new THREE.Group();scene.add(aimCross);for(let i=0;i<4;i++){const a=i*Math.PI/2;const m=box(Math.sin(a)*1.7,.07,Math.cos(a)*1.7,.12,.025,.7,new THREE.MeshBasicMaterial({color:0xf2d28e}),aimCross);m.rotation.y=a;}
function collision(a,b){let nearest=null,at=2;for(const o of blocks){if(o.dead)continue;const t=segmentBox(a,b,o.min,o.max,.35);if(t!==null&&t<at){at=t;nearest=o;}}if(nearest)return{object:nearest,point:new THREE.Vector3().copy(a).lerp(b,at)};if(b.y<=.4){const t=Math.max(0,Math.min(1,(a.y-.4)/(a.y-b.y)));return{object:null,point:new THREE.Vector3().copy(a).lerp(b,t)};}return null;}
function updatePrediction(){const v=launch(state.yaw,state.elevation,state.power),time=flightTime(origin,v),points=[];let prev=new THREE.Vector3(origin.x,origin.y,origin.z),end=prev.clone();const dt=.065;for(let t=0;t<=time+dt;t+=dt){const p=new THREE.Vector3().copy(pointAt(origin,v,t,LEVELS[state.level].wind));if(t>0){const hit=collision(prev,p);if(hit){points.push(hit.point);end.copy(hit.point);break;}}points.push(p);prev=p;end=p;}pathLine.geometry.dispose();pathLine.geometry=new THREE.BufferGeometry().setFromPoints(points);pathLine.computeLineDistances();dotGroup.children.forEach((dot,i)=>{const index=Math.min(points.length-1,Math.floor(i/(dotGroup.children.length-1)*(points.length-1)));dot.position.copy(points[index]);dot.visible=i%2===0||points.length>50;});aimRing.position.set(end.x,.07,end.z);aimCross.position.set(end.x,0,end.z);$('range').textContent=Math.round(Math.hypot(v.x*time+.5*LEVELS[state.level].wind*time*time,v.z*time))+' m';catapult.rotation.y=-state.yaw*Math.PI/180;}
function floatText(text,pos,enemy=false){const p=pos.clone().project(camera),el=document.createElement('div');el.className='damage-number'+(enemy?' enemy':'');el.textContent=text;el.style.left=(p.x*.5+.5)*innerWidth+'px';el.style.top=(-p.y*.5+.5)*innerHeight+'px';$('damage-numbers').appendChild(el);setTimeout(()=>el.remove(),1600);}
function spawnParticles(pos,color,count=20,power=1){for(let i=0;i<count;i++){if(particles.length>150){const old=particles.shift();scene.remove(old.mesh);}const m=mesh(sphereGeo,mat(color),pos.x,pos.y,pos.z);const s=.12+Math.random()*.38;m.scale.setScalar(s);m.castShadow=false;particles.push({mesh:m,velocity:new THREE.Vector3((Math.random()-.5)*8,Math.random()*7,(Math.random()-.5)*8).multiplyScalar(power),life:.45+Math.random()*1.2,max:1.7,scale:s});}}
function blastRing(pos,color=0xf1af64){const m=mesh(new THREE.RingGeometry(.85,1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,side:THREE.DoubleSide}),pos.x,.12,pos.z);m.rotation.x=-Math.PI/2;rings.push({mesh:m,life:.65});}
function disposeMesh(m){scene.remove(m);if(m.geometry&&m.geometry!==boxGeo&&m.geometry!==sphereGeo)m.geometry.dispose();if(m.material&&!Object.values(materials).includes(m.material))m.material.dispose();}
function removeObject(o,impact,collapse=false){if(o.dead)return;o.dead=true;fortress.remove(o.mesh);if(o.type==='wall'||o.type==='tower'){destroyedWalls++;state.score+=collapse?12:20;}if(o.type==='core')state.core=0;
if(o.type==='barrel'){o.decor?.forEach(m=>fortress.remove(m));state.score+=75;toast('火药桶连爆！');explode(new THREE.Vector3(o.x,o.y,o.z),9.5,175,0xefad52,'barrel');return;}
const models=[o.mesh,...(o.decor??[])];for(const m of models){fortress.remove(m);scene.add(m);const direction=m.position.clone().sub(impact);if(direction.lengthSq()<.1)direction.set(Math.random()-.5,1,Math.random()-.5);direction.normalize();debris.push({mesh:m,velocity:direction.multiplyScalar(collapse?2:4+Math.random()*4).add(new THREE.Vector3(0,collapse?.5:3+Math.random()*3,0)),angular:new THREE.Vector3(Math.random()-.5,Math.random()-.5,Math.random()-.5).multiplyScalar(2),life:9,bounced:0});}if(debris.length>180){const dead=debris.splice(0,debris.length-180);dead.forEach(d=>disposeMesh(d.mesh));}}
function damageObject(o,damage,pos){if(o.dead||damage<=0)return;o.hp-=damage;if(o.type==='core'){state.core=Math.max(0,o.hp);state.score+=Math.round(damage*.8);floatText('−'+Math.round(damage),new THREE.Vector3(o.x,o.y+5,o.z));}if(o.hp<=0)removeObject(o,pos);else if(o.type!=='barrel'){if(!o.tint){o.mesh.material=o.mesh.material.clone();o.tint=true;}o.mesh.material.color.lerp(new THREE.Color(0x544a3c),.11);}}
function collapseUnsupported(impact){for(let pass=0;pass<3;pass++){for(const o of blocks){if(o.dead||!['wall','tower'].includes(o.type)||o.min.y<1)continue;const support=blocks.some(b=>!b.dead&&b!==o&&b.max.y<=o.min.y+.1&&b.max.y>o.min.y-.55&&b.max.x>o.min.x+.15&&b.min.x<o.max.x-.15&&b.max.z>o.min.z+.15&&b.min.z<o.max.z-.15);if(!support)removeObject(o,impact,true);}}}
function distanceToBox(p,o){return Math.hypot(Math.max(o.min.x-p.x,0,p.x-o.max.x),Math.max(o.min.y-p.y,0,p.y-o.max.y),Math.max(o.min.z-p.z,0,p.z-o.max.z));}
function explode(pos,radius,damage,color,type,direct){shake=Math.max(shake,type==='barrel'?.4:.22);sound('hit');spawnParticles(pos,color,type==='barrel'?32:24,1.1);spawnParticles(pos,0xaaa48b,14,.65);blastRing(pos,color);const before=destroyedWalls;for(const o of blocks){if(o.dead)continue;const d=distanceToBox(pos,o);if(d<radius){let hit=explosionDamage(d,radius,damage);if(o===direct)hit+=damage*.2;damageObject(o,hit,pos);}}collapseUnsupported(pos);if(destroyedWalls-before>=8){state.score+=(destroyedWalls-before)*5;toast('城防崩塌 · 连锁破坏 +'+(destroyedWalls-before)*5);}
if(type===2){fires.push({pos:pos.clone(),radius:6.8,remaining:3.6,tick:0,visual:0});toast('燃烧区域已形成 · 持续灼烧');}if(type!=='barrel'){const m=mesh(new THREE.CircleGeometry(radius*.55,20),new THREE.MeshBasicMaterial({color:0x3c3d32,transparent:true,opacity:.3,depthWrite:false}),pos.x,.015,pos.z);m.rotation.x=-Math.PI/2;scorchMarks.push(m);}updateHUD();}
function addProjectile(pos,velocity,type,mini=false){const m=mesh(sphereGeo,mat(AMMO[type].color,.85,.05),pos.x,pos.y,pos.z);m.scale.setScalar(mini?.3:.52);const p={mesh:m,origin:{...pos},velocity:{...velocity},time:0,type,mini,trail:0,split:false};projectiles.push(p);return p;}
function fire(){if(state.phase!=='ready'||state.paused)return;if(state.ammo[state.ammoType]<=0){toast('该弹种已用尽，请切换弹药');return;}state.phase='flying';state.ammo[state.ammoType]--;state.shots++;shootAnim=.72;throwStone.visible=false;state.settle=0;sound('fire');addProjectile(origin,launch(state.yaw,state.elevation,state.power),state.ammoType);pathLine.visible=false;dotGroup.visible=false;aimRing.visible=false;aimCross.visible=false;updateHUD();}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i],prev=p.mesh.position.clone();p.time+=dt;const current=new THREE.Vector3().copy(pointAt(p.origin,p.velocity,p.time,LEVELS[state.level].wind));p.mesh.position.copy(current);p.mesh.rotation.x+=dt*3;p.mesh.rotation.z+=dt*2;p.trail+=dt;if(p.trail>.06){p.trail=0;spawnParticles(current,p.type===2?0xe5a360:0xc5bca1,1,.07);}if(p.type===3&&!p.mini&&p.velocity.y-GRAVITY*p.time<-.1&&!p.split){p.split=true;const v={x:p.velocity.x+LEVELS[state.level].wind*p.time,y:p.velocity.y-GRAVITY*p.time,z:p.velocity.z};for(let j=0;j<5;j++){addProjectile(current,{x:v.x+(j-2)*1.6,y:v.y+Math.abs(j-2)*.45,z:v.z+(j%2?1.4:-1.4)},3,true);}scene.remove(p.mesh);projectiles.splice(i,1);spawnParticles(current,0xd4b9cf,16,.3);continue;}
const hit=collision(prev,current);if(hit||p.time>12||Math.abs(current.x)>130||current.z<-160){scene.remove(p.mesh);projectiles.splice(i,1);const point=hit?.point??current;const ammo=AMMO[p.type];explode(point,ammo.radius*(p.mini?.8:1),ammo.damage*(1+state.upgrades.power*.18)*(p.mini?.68:1),p.type===0?0xbbb59d:ammo.color,p.type,hit?.object);state.settle=.9;}}
if(!projectiles.length&&state.phase==='flying')state.phase='settling';}
function fireEnemy(){state.phase='enemy';const z=LEVELS[state.level].z+8;const alive=blocks.filter(b=>!b.dead&&b.type==='tower').length,all=blocks.filter(b=>b.type==='tower').length;const factor=Math.max(.3,alive/all);const damage=Math.max(4,Math.round(LEVELS[state.level].damage*factor));const start={x:11,y:11,z},end={x:0,y:1,z:29},duration=2;const velocity={x:(end.x-start.x)/duration,y:(end.y-start.y+.5*GRAVITY*duration*duration)/duration,z:(end.z-start.z)/duration};const m=mesh(sphereGeo,mat(0xe29c62),start.x,start.y,start.z);m.scale.setScalar(.35);state.enemyShot={mesh:m,start,velocity,t:0,duration,damage};toast('敌方回击！摧毁炮塔可降低伤害');updateHUD();}
function finishShot(){if(state.core<=0){victory();return;}if(state.health<=0){defeat('投石机已被摧毁');return;}if(state.ammo.every(n=>n<=0)){defeat('弹药耗尽，堡垒仍在坚守');return;}if(state.shots%LEVELS[state.level].retaliate===0&&state.phase!=='enemy'){fireEnemy();return;}state.phase='ready';throwStone.visible=true;if(state.ammo[state.ammoType]===0)state.ammoType=state.ammo.findIndex(n=>n>0);pathLine.visible=dotGroup.visible=aimRing.visible=aimCross.visible=true;updatePrediction();updateHUD();}
function updateEnemy(dt){const e=state.enemyShot;if(!e)return;e.t+=dt;e.mesh.position.copy(pointAt(e.start,e.velocity,e.t,0));if(Math.random()<.3)spawnParticles(e.mesh.position,0xd79762,1,.1);if(e.t>=e.duration){scene.remove(e.mesh);state.enemyShot=null;state.health=Math.max(0,state.health-e.damage);shake=.45;sound('hit');spawnParticles(new THREE.Vector3(0,2,29),0xd9ae72,26,1);floatText('−'+e.damage,new THREE.Vector3(0,5,29),true);updateHUD();finishShot();}}
function updateEffects(dt){for(let i=debris.length-1;i>=0;i--){const d=debris[i];d.life-=dt;if(d.life<=0){disposeMesh(d.mesh);debris.splice(i,1);continue;}if(d.bounced<3){d.velocity.y-=GRAVITY*dt;d.mesh.position.addScaledVector(d.velocity,dt);d.mesh.rotation.x+=d.angular.x*dt;d.mesh.rotation.y+=d.angular.y*dt;d.mesh.rotation.z+=d.angular.z*dt;if(d.mesh.position.y<.4){d.mesh.position.y=.4;d.velocity.y=Math.abs(d.velocity.y)*.24;d.velocity.x*=.55;d.velocity.z*=.55;d.bounced++;}}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);continue;}p.velocity.y-=3*dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.scale.setScalar(p.scale*Math.max(.05,p.life/p.max));}
for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.life-=dt;r.mesh.scale.setScalar((.65-r.life)*17+.5);r.mesh.material.opacity=Math.max(0,r.life/.65)*.6;if(r.life<=0){scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();rings.splice(i,1);}}
for(let i=fires.length-1;i>=0;i--){const f=fires[i];f.remaining-=dt;f.tick+=dt;f.visual+=dt;if(f.visual>.075){f.visual=0;const p=f.pos.clone().add(new THREE.Vector3((Math.random()-.5)*4,Math.random()*1.5,(Math.random()-.5)*4));spawnParticles(p,Math.random()>.5?0xe5ab53:0xe67843,2,.18);}if(f.tick>=.4){const elapsed=f.tick;f.tick=0;for(const o of blocks){if(o.dead)continue;const d=distanceToBox(f.pos,o);if(d<f.radius)damageObject(o,26*elapsed*(1-d/f.radius)*(1+state.upgrades.power*.18),f.pos);}updateHUD();}if(f.remaining<=0)fires.splice(i,1);}
}
function resetScene(){for(const p of [...projectiles,...particles,...debris,...rings])disposeMesh(p.mesh);for(const m of scorchMarks)disposeMesh(m);if(state.enemyShot)scene.remove(state.enemyShot.mesh);projectiles.length=particles.length=debris.length=rings.length=fires.length=scorchMarks.length=0;state.enemyShot=null;fortress.traverse(o=>{if(o.geometry&&o.geometry!==boxGeo&&o.geometry!==sphereGeo)o.geometry.dispose();if(o.isMesh&&o.material&&!Object.values(materials).includes(o.material))o.material.dispose();});fortress.clear();blocks.length=0;for(let i=flags.length-1;i>=0;i--){if(flags[i].mesh.parent!==terrain)flags.splice(i,1);}totalWalls=destroyedWalls=0;$('damage-numbers').replaceChildren();}
function startLevel(index){state.level=index;resetScene();rand=seeded(LEVELS[index].seed);state.core=LEVELS[index].hp;state.maxHealth=100+state.upgrades.armor*30;state.health=state.maxHealth;state.ammo=LEVELS[index].ammo.map((n,i)=>n+(i===0?state.upgrades.ammo*2:i===1?state.upgrades.ammo:0));state.ammoType=0;state.shots=0;state.score=0;state.phase='ready';state.paused=false;state.settle=0;state.yaw=0;state.elevation=36;state.power=50+index*3;state.view='siege';orbitAngle=.49;orbitElevation=.47;orbitDistance=102;shootAnim=0;arm.rotation.x=-.25;throwStone.visible=true;buildFortress();$('modal').hidden=true;pathLine.visible=dotGroup.visible=aimRing.visible=aimCross.visible=true;setView('siege');syncInputs();updateHUD();updatePrediction();save();}
function updateHUD(){const lev=LEVELS[state.level],percent=Math.max(0,Math.ceil(state.core/lev.hp*100));$('chapter').textContent=lev.chapter+' · '+lev.name;$('level-name').textContent=lev.name;$('level-desc').textContent=lev.desc;$('level-count').textContent='0'+(state.level+1)+' / 05';$('core-percent').textContent=percent+'%';$('core-bar').style.width=percent+'%';$('destruction').textContent=Math.round(destroyedWalls/Math.max(1,totalWalls)*100)+'%';$('shots').textContent=state.ammo.reduce((a,b)=>a+b,0);$('gold').textContent=state.gold;$('health-text').textContent=state.health+' / '+state.maxHealth;$('health-bar').style.width=(state.health/state.maxHealth*100)+'%';$('wind').textContent=(Math.abs(lev.wind)*6).toFixed(1);$('wind-arrow').textContent=lev.wind>=0?'↗':'↖';$('wind-desc').textContent=(Math.abs(lev.wind)<.3?'轻微侧风':'强劲侧风')+' · 向'+(lev.wind>=0?'右':'左');$('counter-label').textContent='敌方将在 '+(lev.retaliate-state.shots%lev.retaliate)+' 次发射后反击';$('score-text').innerHTML='战场得分 <b>'+String(state.score).padStart(4,'0')+'</b>';$('ammo-hint').textContent=AMMO[state.ammoType].hint.split(' · ')[0];$('chapter-dots').innerHTML=LEVELS.map((l,i)=>'<span class="'+(i===state.level?'active':state.earned[i]?'complete':'')+'" title="'+l.name+'"></span>').join('');$('ammo-picker').innerHTML=AMMO.map((a,i)=>'<button class="ammo-btn '+(i===state.ammoType?'selected':'')+'" data-ammo="'+i+'" title="'+a.hint+'" aria-label="'+a.name+'，剩余 '+state.ammo[i]+' 发" aria-pressed="'+(i===state.ammoType)+'"><span class="ammo-key">'+(i+1)+'</span><span class="ammo-count">'+state.ammo[i]+'</span><span class="ammo-icon">'+a.icon+'</span><span class="ammo-name">'+a.name+'</span></button>').join('');$('fire').disabled=state.phase!=='ready'||state.paused||state.ammo[state.ammoType]<=0;$('fire-text').textContent=state.phase==='flying'?'飞行中':state.phase==='enemy'?'敌方回击':state.phase==='settling'?'结算中':state.phase==='won'?'已攻克':state.phase==='lost'?'已结束':'发 射';$('status').textContent=state.phase==='ready'?(state.ammo[state.ammoType]>0?'投石机已就绪':'该弹种已用尽'):state.phase==='enemy'?'敌方炮塔正在反击':state.phase==='flying'?'弹丸飞行中':'等待战场结算';$('target-label').style.display=state.core<=0?'none':'';}
function syncInputs(){for(const key of ['yaw','elevation','power']){$(key).value=state[key];$(key+'-value').textContent=state[key]+(key==='power'?'':'°');$(key).style.setProperty('--fill',((state[key]-Number($(key).min))/(Number($(key).max)-Number($(key).min))*100)+'%');}}
function setAmmo(i){if(state.phase!=='ready'||state.paused)return;state.ammoType=i;updatePrediction();updateHUD();toast(AMMO[i].hint);}
function modal(html){$('modal-card').innerHTML=html;$('modal').hidden=false;requestAnimationFrame(()=>$('modal-card').querySelector('button:not(:disabled)')?.focus());}
const upgradeDefs=[{key:'power',name:'配重强化',desc:'弹丸与燃烧伤害 +18%',icon:'⚒'},{key:'armor',name:'加固机架',desc:'投石机最大耐久 +30',icon:'♜'},{key:'ammo',name:'扩充弹仓',desc:'每关石弹 +2，爆裂弹 +1',icon:'▥'}];
function upgradeHTML(){return '<div class="upgrades">'+upgradeDefs.map(u=>{const lv=state.upgrades[u.key],cost=120+lv*80;return '<button class="upgrade" data-upgrade="'+u.key+'" '+(lv>=2||state.gold<cost?'disabled':'')+'><span>'+u.icon+'</span><span><b>'+u.name+' <span style="color:#83917f">'+lv+'/2</span></b><small>'+u.desc+'</small></span><span class="price">'+(lv>=2?'已满级':'◈ '+cost)+'</span></button>';}).join('')+'</div>';}
let resultStars=0,resultReward=0;
function showVictory(){const last=state.level===4;modal('<div class="eyebrow">'+(last?'THE NORTH IS YOURS':'FORTRESS CONQUERED')+'</div><h2>'+(last?'北境已被征服':'堡垒已攻克')+'</h2><p>'+LEVELS[state.level].name+'的旗帜落下了。整备投石机，继续前进。</p><div class="stars">'+Array.from({length:3},(_,i)=>'<span class="'+(i<resultStars?'':'dim')+'">★</span>').join('')+'</div><div class="modal-score"><div><b>'+state.score+'</b><span>战场得分</span></div><div><b>'+state.shots+'</b><span>发射次数</span></div><div><b>+'+resultReward+'</b><span>首次攻克金币</span></div></div>'+upgradeHTML()+'<div class="modal-actions"><button class="secondary" data-action="replay">再次挑战</button><button class="primary" data-action="next">'+(last?'重启北境战役':'进军下一座堡垒')+'</button></div><p style="font-size:10px;margin:15px 0 0">金币余额 ◈ '+state.gold+' · 升级与战役进度保存在当前浏览器</p>');}
function victory(){if(state.phase==='won')return;state.phase='won';resultStars=state.shots<=5?3:state.shots<=9?2:1;state.best[state.level]=Math.max(state.best[state.level],resultStars);resultReward=state.earned[state.level]?0:180+state.level*40;state.earned[state.level]=true;state.gold+=resultReward;state.score+=Math.round(state.health*3)+state.ammo.reduce((a,b)=>a+b,0)*50;save();sound('win');updateHUD();showVictory();}
function defeat(reason){state.phase='lost';updateHUD();modal('<div class="eyebrow">REGROUP & RETURN</div><h2>暂且撤退</h2><p>'+reason+'。试试提高抛射角越过城墙，或用爆裂弹引爆城门后的火药桶。</p><div class="modal-score"><div><b>'+Math.round((1-state.core/LEVELS[state.level].hp)*100)+'%</b><span>核心受损</span></div><div><b>'+state.score+'</b><span>战场得分</span></div></div><div class="modal-actions"><button class="secondary" data-action="help">查看攻城手册</button><button class="primary" data-action="replay">重新集结</button></div>');}
function help(){state.paused=true;modal('<div class="eyebrow">ENGINEER’S FIELD MANUAL</div><h2>攻城工程师手册</h2><p>调整方向、抛射角与力度，观察金色弹道，<br>击碎城墙或越过它，摧毁悬挂红旗的中央核心。</p><div class="help-grid"><div><b>瞄准与发射</b><span>A / D 调整方向，W / S 调整抛射角；↑ / ↓ 调整力度，空格发射。触屏可直接拖动滑块。</span></div><div><b>四种弹药</b><span>1 石弹破墙；2 爆裂弹范围爆破；3 燃烧弹持续灼烧；4 散射弹在空中分裂。</span></div><div><b>把城防变成武器</b><span>摧毁底层石块会使上层崩塌。击中红色火药桶引发连爆，击毁侧翼炮塔减弱回击。</span></div><div><b>观察战場</b><span>拖动环视、滚轮缩放；C 切换战术视角；可开启跟随弹丸。金色落点已包含风偏。</span></div><div><b>战役与整备</b><span>攻克五座堡垒。首次通关奖励金币，可升级伤害、耐久和弹仓。重试恢复本关弹药。</span></div><div><b>休整与进度</b><span>Esc 暂停。切换窗口自动暂停。升级与关卡进度保存在当前浏览器；单次射击不存档。</span></div></div><div class="modal-actions"><button class="primary" data-action="close-help">返回战场</button></div>');updateHUD();}
function pause(){if(['won','lost'].includes(state.phase))return;state.paused=true;modal('<div class="eyebrow">HOLD YOUR FIRE</div><h2>战场已暂停</h2><p>风也在等你。准备好后继续攻城。</p><div class="modal-actions"><button class="secondary" data-action="replay">重试本关</button><button class="primary" data-action="resume">继续作战</button></div><div class="modal-actions"><button class="secondary" data-action="help">攻城手册</button><button class="secondary" data-action="campaign">战役地图</button></div>');updateHUD();}
function campaignMap(){state.paused=true;modal('<div class="eyebrow">NORTHERN CAMPAIGN</div><h2>北境战役</h2><p>已攻克的堡垒可以随时重新挑战。</p><div class="upgrades">'+LEVELS.map((l,i)=>'<button class="upgrade" data-level="'+i+'" '+(i>0&&!state.earned[i-1]?'disabled':'')+'><span>0'+(i+1)+'</span><span><b>'+l.name+'</b><small>'+l.desc+'</small></span><span class="price">'+(state.best[i]?'★'.repeat(state.best[i]):'◇')+'</span></button>').join('')+'</div><div class="modal-actions"><button class="primary" data-action="resume">返回战场</button></div>');}
let orbitAngle=.49,orbitElevation=.47,orbitDistance=102,drag=null;
const cameraTarget=new THREE.Vector3(0,3,-7),desiredCamera=new THREE.Vector3(),lookTarget=new THREE.Vector3(0,3,-7);
function setView(view){state.view=view;$('view-siege').classList.toggle('active',view==='siege');$('view-tactical').classList.toggle('active',view==='tactical');if(view==='siege'){orbitAngle=.49;orbitElevation=.47;orbitDistance=102;}else{orbitAngle=.05;orbitElevation=1.13;orbitDistance=108;}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
addEventListener('resize',resize);
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{if(state.paused||e.button!==0)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;orbitAngle-=(e.clientX-drag.x)*.006;orbitElevation=Math.max(.18,Math.min(1.35,orbitElevation+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();if(state.paused)return;orbitDistance=Math.max(58,Math.min(155,orbitDistance+e.deltaY*.06));},{passive:false});
$('fire').addEventListener('click',fire);$('ammo-picker').addEventListener('click',e=>{const b=e.target.closest('[data-ammo]');if(b)setAmmo(Number(b.dataset.ammo));});
for(const key of ['yaw','elevation','power'])$(key).addEventListener('input',()=>{state[key]=Number($(key).value);syncInputs();if(state.phase==='ready')updatePrediction();});
$('reset-aim').addEventListener('click',()=>{state.yaw=0;state.elevation=36;state.power=50+state.level*3;syncInputs();updatePrediction();});$('view-siege').addEventListener('click',()=>setView('siege'));$('view-tactical').addEventListener('click',()=>setView('tactical'));$('follow').addEventListener('click',()=>{state.follow=!state.follow;$('follow').classList.toggle('active',state.follow);$('follow').setAttribute('aria-pressed',String(state.follow));$('follow').innerHTML='跟随弹丸 <span>'+(state.follow?'●':'○')+'</span>';});$('sound').addEventListener('click',()=>{state.sound=!state.sound;$('sound').style.color=state.sound?'var(--gold)':'';$('sound').textContent=state.sound?'♫':'♪';$('sound').setAttribute('aria-label',state.sound?'关闭音效':'开启音效');toast(state.sound?'战场音效已开启':'战场音效已关闭');if(state.sound)sound('fire');});$('help').addEventListener('click',()=>{if(state.phase==='won')return;help();});$('pause').addEventListener('click',pause);
$('modal-card').addEventListener('click',e=>{const u=e.target.closest('[data-upgrade]');if(u){const key=u.dataset.upgrade,lv=state.upgrades[key],cost=120+lv*80;if(lv>=2||state.gold<cost)return;state.gold-=cost;state.upgrades[key]++;save();updateHUD();showVictory();return;}const l=e.target.closest('[data-level]');if(l){const i=Number(l.dataset.level);if(i===0||state.earned[i-1])startLevel(i);return;}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='resume'||a==='close-help'){state.paused=false;$('modal').hidden=true;if(state.phase==='lost')defeat('调整战术，再次进攻');else if(state.phase==='won')showVictory();updateHUD();}if(a==='replay')startLevel(state.level);if(a==='next')startLevel(state.level===4?0:state.level+1);if(a==='help')help();if(a==='campaign')campaignMap();});
addEventListener('keydown',e=>{const tag=e.target.tagName;if(e.key==='Tab'&&!$('modal').hidden){const focusable=[...$('modal-card').querySelectorAll('button:not(:disabled)')];if(focusable.length){const first=focusable[0],last=focusable.at(-1);if(!focusable.includes(document.activeElement)){e.preventDefault();first.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.key==='Escape'){e.preventDefault();if(!$('modal').hidden&&state.paused){state.paused=false;$('modal').hidden=true;if(state.phase==='lost')defeat('调整战术，再次进攻');else if(state.phase==='won')showVictory();updateHUD();}else pause();return;}if(state.paused||['won','lost'].includes(state.phase)||['INPUT','BUTTON','A','SELECT','TEXTAREA'].includes(tag)||e.target.isContentEditable)return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();if(!e.repeat)fire();return;}if('1234'.includes(k)&&k.length===1){setAmmo(Number(k)-1);return;}if(k==='c'){setView(state.view==='siege'?'tactical':'siege');return;}const move={a:['yaw',-.5],d:['yaw',.5],w:['elevation',1],s:['elevation',-1],arrowup:['power',1],arrowdown:['power',-1]}[k];if(move){e.preventDefault();if(state.phase!=='ready')return;const [id,step]=move;state[id]=Math.max(Number($(id).min),Math.min(Number($(id).max),state[id]+step));syncInputs();updatePrediction();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!state.paused&&!['won','lost'].includes(state.phase))pause();});
let last=performance.now(),fpsCounter=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.035);last=now;
if(!state.paused){animTime+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('visible');}flags.forEach(f=>{const a=f.mesh.geometry.attributes.position;for(let i=0;i<a.count;i++){const x=f.base[i*3];a.setZ(i,Math.sin(animTime*3+x*2+f.phase)*.18*(x/2+.7));}a.needsUpdate=true;});if(shootAnim>0){shootAnim-=dt;const progress=1-shootAnim/.72;arm.rotation.x=-.25+Math.sin(progress*Math.PI)*1.65;}else arm.rotation.x=-.25;
if(state.phase==='flying')updateProjectiles(dt);updateEffects(dt);if(state.phase==='settling'){state.settle-=dt;if(state.settle<=0&&fires.length===0)finishShot();}if(state.phase==='enemy')updateEnemy(dt);coreGlow.intensity=core.dead?0:5.5+Math.sin(animTime*2)*.6;engineer.rotation.y=Math.sin(animTime*.7)*.08;shake=Math.max(0,shake-dt);}
const mobile=innerWidth<700,aspectScale=mobile?1.38:1;cameraTarget.set(0,2,LEVELS[state.level].z*.27+1);if(state.follow&&projectiles.length&&state.phase==='flying'){const pos=projectiles[0].mesh.position;desiredCamera.copy(pos).add(new THREE.Vector3(13,8,20));lookTarget.copy(pos).add(new THREE.Vector3(0,0,-8));}else{const dist=orbitDistance*aspectScale,angle=orbitAngle*(mobile?.3:1);desiredCamera.set(Math.sin(angle)*Math.cos(orbitElevation)*dist,Math.sin(orbitElevation)*dist,Math.cos(angle)*Math.cos(orbitElevation)*dist).add(cameraTarget);lookTarget.copy(cameraTarget);if(mobile)lookTarget.z=-4;}
camera.position.lerp(desiredCamera,1-Math.exp(-dt*4));const look=lookTarget.clone();if(shake>0&&!reduced)look.add(new THREE.Vector3((Math.random()-.5)*shake*1.5,(Math.random()-.5)*shake,0));camera.lookAt(look);const cp=new THREE.Vector3(0,14,LEVELS[state.level].z).project(camera);$('target-label').style.left=(cp.x*.5+.5)*innerWidth+'px';$('target-label').style.top=(-cp.y*.5+.5)*innerHeight+'px';if(state.phase==='ready')aimRing.material.opacity=.5+Math.sin(animTime*2)*.2;renderer.render(scene,camera);}
buildTerrain();buildCatapult();startLevel(state.level);camera.position.set(46,49,77);$('loading').remove();requestAnimationFrame(animate);toast(state.level===0?'工程师就位 · 调整金色弹道，空格发射':'已恢复战役进度 · '+LEVELS[state.level].name);
// Module exports allow deterministic verification of the same live gameplay rules.
export {state,startLevel,fire,finishShot,updateProjectiles,updateEffects,updateEnemy,collision,blocks,explode,syncInputs,updatePrediction,updateHUD,origin};
