export const GOODS=[
{id:'salt',name:'岩盐',en:'SALT',base:18,color:'#efe4ce',icon:'salt'},
{id:'dates',name:'椰枣',en:'DATES',base:26,color:'#ae654c',icon:'dates'},
{id:'copper',name:'铜器',en:'COPPER',base:48,color:'#b9804a',icon:'copper'},
{id:'silk',name:'丝绸',en:'SILK',base:76,color:'#728f8d',icon:'silk'},
{id:'spice',name:'香料',en:'SPICES',base:64,color:'#bf623b',icon:'spice'},
{id:'gems',name:'宝石',en:'GEMS',base:145,color:'#789581',icon:'gems'}];
export const CITIES=[
{id:'dawn',name:'曙光绿洲',en:'DAWN OASIS',x:-25,z:17,special:'dates',demand:'silk',color:'#708d75',desc:'棕榈树下的泉水从不干涸，商旅们在这里交换故事，也交换第一袋椰枣。',type:'绿洲集市'},
{id:'salt',name:'白盐古城',en:'SALT CITADEL',x:-29,z:-11,special:'salt',demand:'dates',color:'#bba78b',desc:'纯白盐田环绕古城。干燥的风里，来自南方的甜美椰枣格外珍贵。',type:'盐田城邦'},
{id:'copper',name:'赤岩要塞',en:'RED ROCK FORT',x:-3,z:-21,special:'copper',demand:'salt',color:'#af614b',desc:'峡谷深处的矿火昼夜不息。铜器从这里流向沙海的每一座城市。',type:'矿业要塞'},
{id:'silk',name:'月牙港',en:'CRESCENT HARBOR',x:24,z:-14,special:'silk',demand:'spice',color:'#6b9196',desc:'月牙形的湖泊旁，织匠将星光织进绸缎，远方的香料最受欢迎。',type:'织造之都'},
{id:'spice',name:'琥珀集市',en:'AMBER BAZAAR',x:27,z:14,special:'spice',demand:'gems',color:'#c18c4b',desc:'空气中漂浮着肉桂与胡椒的气息。富有的香料商人钟爱罕见宝石。',type:'香料之城'},
{id:'gems',name:'星陨遗城',en:'STARFALL RUINS',x:0,z:25,special:'gems',demand:'copper',color:'#8c7c99',desc:'古老的石门守护着陨星传说。寻宝者带来宝石，也需要耐用的铜器。',type:'宝石古城'}];
export const UPGRADES=[{id:'camels',name:'添置骆驼',desc:'货舱容量 +30，每日补给消耗 +1',base:360,max:4,icon:'camel'},{id:'guards',name:'雇佣护卫',desc:'降低途中风险，武装护送商队',base:280,max:3,icon:'shield'},{id:'canteen',name:'旅行水囊',desc:'每段行程用水减少 25%',base:260,max:2,icon:'water'},{id:'navigator',name:'沙漠向导',desc:'缩短行程，减少补给消耗',base:420,max:2,icon:'compass'}];
export const CONTRACTS=[{id:'sweet',name:'北方的甜蜜',city:'salt',good:'dates',qty:12,reward:360,rep:8,days:14,desc:'白盐古城的节庆需要一批新鲜椰枣。'},{id:'thread',name:'绿洲的新衣',city:'dawn',good:'silk',qty:8,reward:1000,rep:12,days:24,desc:'曙光绿洲的裁缝正等待月牙港的丝绸。'},{id:'metal',name:'遗迹勘探队',city:'gems',good:'copper',qty:10,reward:800,rep:10,days:18,desc:'星陨遗城的勘探队需要结实的铜器。'},{id:'royal',name:'王室珍藏',city:'spice',good:'gems',qty:6,reward:1500,rep:15,days:28,desc:'琥珀集市的大商人悬赏收购优质宝石。'}];
export function freshState(){return {version:1,coins:1250,day:1,location:'dawn',water:60,food:45,morale:92,cargo:{dates:8},upgrades:{camels:0,guards:0,canteen:0,navigator:0},rep:0,profit:0,visits:['dawn'],completed:[],contracts:[],route:[],trip:null,event:null,log:[{day:1,text:'你抵达曙光绿洲。一条新的商路，正等待被书写。',type:'info'}],market:{},trades:0,legs:0,achievements:[],weather:'晴朗',speed:1,muted:true,paused:false};}
export const cityBy=id=>CITIES.find(c=>c.id===id);
export const goodBy=id=>GOODS.find(g=>g.id===id);
export function capacity(s){return 60+s.upgrades.camels*30;}
export function cargoCount(s){return Object.values(s.cargo).reduce((a,b)=>a+b,0);}
export function quote(s,cid,gid){const c=cityBy(cid),g=goodBy(gid);const factor=c.special===gid?.67:c.demand===gid?1.51:1.06;const wave=1+Math.sin(s.day*.41+CITIES.indexOf(c)*1.7+GOODS.indexOf(g))*.09;const pressure=Math.max(-.045,Math.min(.045,(s.market[cid+gid]||0)*.003));return Math.max(1,Math.round(g.base*factor*wave*(1+pressure)));}
export function sellQuote(s,cid,gid){return Math.floor(quote(s,cid,gid)*.9);}
export function stock(s,cid,gid){return Math.max(0,Math.floor((cityBy(cid).special===gid?90:40)-(s.market[cid+gid]||0)));}
export function legInfo(s,from,to){const a=cityBy(from),b=cityBy(to);const distance=Math.hypot(a.x-b.x,a.z-b.z);const days=Math.max(1,Math.ceil(distance/17-s.upgrades.navigator*.65+(s.morale<45?.8:0)+(s.weather==='沙尘'?.6:0)));const water=Math.max(1,Math.ceil(days*(4+s.upgrades.camels)*(1-s.upgrades.canteen*.25)));const food=days*(3+s.upgrades.camels);const risk=Math.max(5,Math.round(distance*.52-s.upgrades.guards*12));return {days,water,food,risk,distance};}
export function routeInfo(s){let from=s.location;return s.route.reduce((a,to)=>{const l=legInfo(s,from,to);from=to;return {days:a.days+l.days,water:a.water+l.water,food:a.food+l.food,risk:Math.max(a.risk,l.risk)};},{days:0,water:0,food:0,risk:0});}
export function netWorth(s){return s.coins+GOODS.reduce((v,g)=>v+(s.cargo[g.id]||0)*sellQuote(s,s.location,g.id),0)+UPGRADES.reduce((v,u)=>v+s.upgrades[u.id]*u.base,0);}
export function addLog(s,text,type='info'){s.log.unshift({day:s.day,text,type});s.log=s.log.slice(0,60);}
export function buy(s,gid,qty){if(s.trip)return '旅途中无法交易';qty=Math.floor(qty);const p=quote(s,s.location,gid);if(!Number.isFinite(qty)||qty<1)return '请选择购买数量';if(s.coins<p*qty)return '金币不足';if(cargoCount(s)+qty>capacity(s))return '货舱空间不足';if(qty>stock(s,s.location,gid))return '市场库存不足';s.coins-=p*qty;s.cargo[gid]=(s.cargo[gid]||0)+qty;s.market[s.location+gid]=(s.market[s.location+gid]||0)+qty;s.trades++;addLog(s,`买入 ${qty} 箱${goodBy(gid).name}，支出 ${p*qty} 金币。`);return null;}
export function sell(s,gid,qty){if(s.trip)return '旅途中无法交易';qty=Math.floor(qty);if(!Number.isFinite(qty)||qty<1||qty>(s.cargo[gid]||0))return '没有足够的货物';const total=sellQuote(s,s.location,gid)*qty;s.coins+=total;s.profit+=total-goodBy(gid).base*.67*qty;s.cargo[gid]-=qty;s.market[s.location+gid]=Math.max(-20,(s.market[s.location+gid]||0)-qty);s.trades++;addLog(s,`售出 ${qty} 箱${goodBy(gid).name}，收入 ${total} 金币。`,'good');return null;}
export function resupply(s){if(s.trip)return '抵达城镇后可补给';const cost=Math.ceil((80-s.water)*1.2+(60-s.food)*1.5);if(cost<=0)return '补给已经充足';if(s.coins<cost)return `补满需要 ${cost} 金币，可单独购买小份补给`;s.coins-=cost;s.water=80;s.food=60;addLog(s,`补给充足，花费 ${cost} 金币。`);return null;}
export function supply(s,kind){if(s.trip)return '抵达城镇后可补给';const cap=kind==='water'?80:60;const n=Math.min(10,cap-s[kind]);const cost=Math.ceil(n*(kind==='water'?1.2:1.5));if(!n)return '已装满';if(s.coins<cost)return '金币不足';s.coins-=cost;s[kind]+=n;return null;}
export function nextDay(s,n){s.day+=n;s.weather=['晴朗','晴朗','热风','晴朗','沙尘'][Math.floor(s.day/3)%5];Object.keys(s.market).forEach(k=>s.market[k]*=.86);s.contracts=s.contracts.filter(t=>{if(s.day>t.deadline){addLog(s,`委托「${CONTRACTS.find(c=>c.id===t.id).name}」已逾期。`,'warn');return false;}return true;});}
export function rest(s){if(s.trip)return '旅途中无法休息';if(s.coins<35)return '休整需要 35 金币';s.coins-=35;s.morale=Math.min(100,s.morale+24);nextDay(s,1);addLog(s,'在商队驿站休整一日，士气恢复。','good');return null;}
export function upgrade(s,id){if(s.trip)return '抵达城镇后可升级';const u=UPGRADES.find(u=>u.id===id),lv=s.upgrades[id],cost=u.base*(lv+1);if(lv>=u.max)return '已达到最高等级';if(s.coins<cost)return '金币不足';s.coins-=cost;s.upgrades[id]++;addLog(s,`${u.name}升级至 ${lv+1} 级。`,'good');return null;}
export function depart(s){if(s.trip)return '商队正在行进';if(!s.route.length)return '先在地图上选择目的地';const dest=s.route[0];if(dest===s.location){s.route.shift();return depart(s);}const info=legInfo(s,s.location,dest);if(s.water<info.water||s.food<info.food)return '本段补给不足，请先补充水与口粮';s.water-=info.water;s.food-=info.food;s.trip={from:s.location,to:dest,progress:0,info,eventDone:s.legs===0};s.route.shift();s.paused=false;addLog(s,`启程前往${cityBy(dest).name}，预计 ${info.days} 天。`);return null;}
export function arrive(s){const t=s.trip;if(!t)return;s.location=t.to;nextDay(s,t.info.days);s.legs++;s.morale=Math.max(20,s.morale-5);if(!s.visits.includes(s.location)){s.visits.push(s.location);s.rep+=3;}s.trip=null;s.event=null;addLog(s,`抵达${cityBy(s.location).name}。当地商人已经备好货物。`,'good');}
export function makeEvent(s){const events=[{id:'traveler',tag:'沙海邂逅',title:'风沙中的旅人',text:'一位迷路的制图师向商队求助。他愿意用金币与一份新地图，换取一小袋饮水。',choices:[{label:'分给他 6 份水',detail:'饮水 −6 · 金币 +65 · 声望 +3',kind:'help'},{label:'指明最近的绿洲',detail:'不消耗资源，继续前进',kind:'skip'}]},{id:'ruins',tag:'意外发现',title:'沙丘之下的回响',text:'风吹开了古老遗迹的入口。向导发现一只完好的陶罐，但探索需要时间和饮水。',choices:[{label:'探索遗迹',detail:'饮水 −4 · 获得 1 箱宝石',kind:'explore'},{label:'标记位置，继续赶路',detail:'声望 +1',kind:'skip'}]},{id:'storm',tag:'旅途挑战',title:'地平线上的沙暴',text:'远处的天空染成了深铜色。你可以雇佣当地向导穿过峡谷，也可以搭起营地等待风停。',choices:[{label:'请向导带路',detail:'金币 −45 · 安全通过',kind:'guide'},{label:'扎营避风',detail:'行程 +1 天 · 士气 −8',kind:'camp'}]},{id:'merchant',tag:'流动商人',title:'驼铃声中的交易',text:'迎面而来的小商队急需周转资金，愿意把两箱香料以优惠价格转让给你。',choices:[{label:'买下两箱香料',detail:'金币 −55 · 香料 +2',kind:'bargain'},{label:'互道平安',detail:'继续前进',kind:'skip'}]}];return events[(s.legs+s.day)%events.length];}
export function resolveEvent(s,kind){if(kind==='help'){if(s.water<6)return '饮水不足';s.water-=6;s.coins+=65;s.rep+=3;}if(kind==='explore'){if(s.water<4||cargoCount(s)>=capacity(s))return '需要 4 份饮水和 1 格空货舱';s.water-=4;s.cargo.gems=(s.cargo.gems||0)+1;}if(kind==='guide'){if(s.coins<45)return '金币不足';s.coins-=45;}if(kind==='camp'){s.trip.info.days++;s.morale=Math.max(20,s.morale-8);}if(kind==='bargain'){if(s.coins<55||cargoCount(s)+2>capacity(s))return '金币或货舱空间不足';s.coins-=55;s.cargo.spice=(s.cargo.spice||0)+2;}if(kind==='skip'&&s.event?.id==='ruins')s.rep++;addLog(s,`旅途记事：${s.event.title}。`);s.event=null;return null;}
export function tick(s,dt){if(!s.trip||s.paused||s.event)return false;s.trip.progress+=dt*s.speed/13;if(s.trip.progress>.47&&!s.trip.eventDone){s.trip.eventDone=true;if((s.legs+s.day)%3!==0&&s.trip.info.risk>8){s.event=makeEvent(s);return true;}}if(s.trip.progress>=1){arrive(s);return true;}return false;}
export function acceptContract(s,id){if(s.contracts.some(t=>t.id===id)||s.completed.includes(id))return '已经接受或完成此委托';if(s.contracts.length>=3)return '最多同时接受 3 个委托';const c=CONTRACTS.find(t=>t.id===id);s.contracts.push({id,deadline:s.day+c.days});addLog(s,`接受委托「${c.name}」，第 ${s.day+c.days} 天前交付。`);return null;}
export function deliverContract(s,id){if(s.trip)return '抵达目的地后交付';const c=CONTRACTS.find(t=>t.id===id);if(s.location!==c.city)return `需要前往${cityBy(c.city).name}`;if((s.cargo[c.good]||0)<c.qty)return `需要 ${c.qty} 箱${goodBy(c.good).name}`;if(!s.contracts.some(t=>t.id===id))return '请先接受委托';s.cargo[c.good]-=c.qty;s.coins+=c.reward;s.rep+=c.rep;s.completed.push(id);s.contracts=s.contracts.filter(t=>t.id!==id);addLog(s,`完成「${c.name}」，获得 ${c.reward} 金币。`,'good');return null;}
export function rescue(s){if(s.trip)return '旅途中不能领取救济';if(s.coins>=30)return '救济仅提供给金币少于 30 的商队';const nearest=CITIES.filter(c=>c.id!==s.location).map(c=>legInfo(s,s.location,c.id)).sort((a,b)=>a.days-b.days)[0];s.water=Math.max(25,nearest.water,s.water);s.food=Math.max(25,nearest.food,s.food);if(cargoCount(s)===0)s.cargo.dates=5;s.morale=Math.max(70,s.morale);addLog(s,'商会提供了应急补给。每一位行商都值得再次出发。','good');return null;}
export function checkAchievements(s){const defs=[['first','第一次远行',s.legs>=1,80],['trader','熟练行商',s.trades>=10,150],['explorer','沙海足迹',s.visits.length>=6,400],['rich','富甲一方',netWorth(s)>=10000,800],['guild','商会之友',s.completed.length>=3,350]];const unlocked=[];for(const [id,name,yes,reward] of defs){if(yes&&!s.achievements.includes(id)){s.achievements.push(id);s.coins+=reward;addLog(s,`达成「${name}」，奖励 ${reward} 金币。`,'good');unlocked.push(name);}}return unlocked;}
