import * as THREE from 'three';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const COLORS=[0xff8867,0xc9ed89,0xafafff,0x77d9e2], HEX=COLORS.map(c=>'#'+c.toString(16));
const songs=[{name:'Neon Circuit',bpm:120,root:110},{name:'Chrome Afterglow',bpm:105,root:98},{name:'System Override',bpm:140,root:123.47}];
let song=0,level=1,auto=false,playing=false,started=false,elapsed=0,last=performance.now(),notes=[],score=0,combo=0,maxCombo=0,hits=0,misses=0,quality=0,energy=0,overUntil=0,judgmentUntil=0,beatIndex=-1,duration=64,muted=false,orbit=false;
const pulses=[0,0,0,0],buttons=$$('[data-lane]');let audio,master;
function initAudio(){if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=Number($('#volume').value)*.5;master.connect(audio.destination);}if(audio.state==='suspended')audio.resume();}
function tone(freq,when,len,type='sine',vol=.2){if(!audio)return;const osc=audio.createOscillator(),g=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,when);g.gain.setValueAtTime(.001,when);g.gain.exponentialRampToValueAtTime(vol,when+.008);g.gain.exponentialRampToValueAtTime(.001,when+len);osc.connect(g);g.connect(master);osc.start(when);osc.stop(when+len+.03);}
function drum(t,kick=true){if(kick){const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(145,t);o.frequency.exponentialRampToValueAtTime(42,t+.17);g.gain.setValueAtTime(.65,t);g.gain.exponentialRampToValueAtTime(.001,t+.23);o.connect(g);g.connect(master);o.start(t);o.stop(t+.25);}else{const buffer=audio.createBuffer(1,audio.sampleRate*.12,audio.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.exp(-i/(audio.sampleRate*.025));const source=audio.createBufferSource(),g=audio.createGain(),filter=audio.createBiquadFilter();filter.type='highpass';filter.frequency.value=2200;source.buffer=buffer;g.gain.value=.28;source.connect(filter);filter.connect(g);g.connect(master);source.start(t);}}
function instrument(lane,n=0){initAudio();const t=audio.currentTime,r=songs[song].root,scale=[0,3,7,10,12,10,7,3],f=r*2**(scale[n%8]/12);if(lane===0)drum(t,n%2===0);if(lane===1)tone(f,t,.27,'triangle',.45);if(lane===2){tone(f*2,t,.35,'sine',.19);tone(f*3,t,.35,'triangle',.09);}if(lane===3)tone(f*4,t,.18,'triangle',.22);pulses[lane]=1;}
function backing(b){const t=audio.currentTime,r=songs[song].root,ch=[0,0,3,7][Math.floor(b/8)%4];drum(t,b%2===0);tone(r*2**(ch/12)/2,t,.35,'sine',.15);if(b%4===0){tone(r*2**(ch/12)*2,t,1.1,'triangle',.05);tone(r*2**((ch+7)/12)*2,t,1.1,'sine',.05);}if(b%2===1)tone(r*8,t,.035,'square',.025);}
function readBest(){try{return localStorage.getItem(`botbeat-${song}-${level}`)||'0'}catch{return'0'}}
function updateBest(){$('#best').textContent=readBest().padStart(6,'0');$('.personal small').textContent=songs[song].name.toUpperCase()+' / '+['CHILL','GROOVE','CHAOS'][level];}
function chart(){const beat=60/songs[song].bpm;duration=beat*128;notes=[];for(let b=4;b<124;b++){const lane=(b*7+Math.floor(b/8)+song)%4;if(level===0&&b%2)continue;notes.push({t:b*beat,lane,done:false});if(level===2&&b%3===0)notes.push({t:(b+.5)*beat,lane:(lane+2)%4,done:false});if(level>0&&b%8===7)notes.push({t:b*beat,lane:(lane+1)%4,done:false});}notes.sort((a,b)=>a.t-b.t);}
function reset(){playing=false;started=false;elapsed=0;score=combo=maxCombo=hits=misses=quality=energy=overUntil=0;beatIndex=-1;chart();$('#idlePrompt').style.display='flex';$('#play').innerHTML="▶ <span>LET'S PLAY</span>";$('#stageStatus').textContent='READY WHEN YOU ARE';document.body.classList.remove('overdrive');updateHUD();}
function togglePlay(){initAudio();if(!started){started=true;$('#idlePrompt').style.display='none';}playing=!playing;$('#play').innerHTML=playing?'Ⅱ <span>PAUSE</span>':'▶ <span>RESUME</span>';$('#stageStatus').textContent=playing?(auto?'AUTO PLAY • ENJOY THE SHOW':'LIVE • FIND YOUR GROOVE'):'PAUSED • TAKE A BREATHER';}
function judge(text,color){$('#judgment').textContent=text;$('#judgment').style.color=color;$('#judgment').style.opacity=1;judgmentUntil=performance.now()+550;}
function hit(lane){instrument(lane,Math.max(0,Math.floor(elapsed/(60/songs[song].bpm))));pulses[lane]=1;buttons[lane].classList.add('pressed');setTimeout(()=>buttons[lane].classList.remove('pressed'),130);if(!playing||auto)return;const candidates=notes.filter(n=>n.lane===lane&&!n.done&&Math.abs(n.t-elapsed)<.19);const n=candidates.sort((a,b)=>Math.abs(a.t-elapsed)-Math.abs(b.t-elapsed))[0];if(n)collect(n,Math.abs(n.t-elapsed)<.085);else{combo=0;energy=0;judge('OFF BEAT','#ff8867');}updateHUD();}
function collect(n,perfect=true){n.done=true;hits++;combo++;maxCombo=Math.max(combo,maxCombo);quality+=perfect?1:.6;const multiplier=Math.min(4,1+Math.floor(combo/10));score+=(perfect?100:60)*multiplier*(elapsed<overUntil?2:1);energy++;if(energy>=20){energy=0;overUntil=elapsed+8;judge('OVERDRIVE!','#e3ff9f');}else judge(perfect?'PERFECT':'GOOD',perfect?'#d5f5a2':'#83dce7');pulses[n.lane]=1;}
function updateHUD(){$('#score').textContent=String(score).padStart(6,'0');$('#combo').innerHTML=combo+'<span>×</span>';$('#accuracy').innerHTML=(hits+misses?Math.round(quality/(hits+misses)*100):'—')+'<span>%</span>';$('#energyFill').style.width=(elapsed<overUntil?100:energy*5)+'%';$('#energyText').textContent=elapsed<overUntil?'2× POINTS • '+Math.ceil(overUntil-elapsed)+'s':'BUILD YOUR GROOVE';$('#time').innerHTML=format(elapsed)+' <i>/ '+format(duration)+'</i>';$('#progressFill').style.width=elapsed/duration*100+'%';document.body.classList.toggle('overdrive',elapsed<overUntil);}
function format(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');}
function finish(){playing=false;$('#play').innerHTML='▶ <span>PLAY AGAIN</span>';$('#stageStatus').textContent='SET COMPLETE • ENCORE?';const best=Number(readBest());if(!auto&&score>best){try{localStorage.setItem(`botbeat-${song}-${level}`,score)}catch{}}updateBest();$('#resultTitle').textContent=auto?'The bots know their groove.':score>best?'A new personal best.':'You brought the groove.';$('#resultScore').textContent=score.toLocaleString();$('#resultStats').textContent=`${auto?'AUTO PERFORMANCE · ':''}${Math.round(quality/Math.max(1,hits+misses)*100)}% accuracy · ${maxCombo} best combo · ${misses} missed notes`;$('#results').showModal();started=false;}
$('#play').onclick=()=>{if(elapsed>=duration)reset();togglePlay()};$('#restart').onclick=()=>{reset();togglePlay()};$('#guide').onclick=()=>$('#help').showModal();$('#closeHelp').onclick=()=>$('#help').close();$('#gotIt').onclick=()=>$('#help').close();$('#again').onclick=()=>{$('#results').close();reset();togglePlay()};$('#dismiss').onclick=()=>{$('#results').close();reset()};
$$('[data-song]').forEach(b=>b.onclick=()=>{song=Number(b.dataset.song);$$('[data-song]').forEach(e=>e.classList.toggle('selected',e===b));reset();updateBest()});$$('[data-level]').forEach(b=>b.onclick=()=>{level=Number(b.dataset.level);$$('[data-level]').forEach(e=>e.classList.toggle('selected',e===b));$('#difficultyCaption').textContent=['EASE INTO THE GROOVE','A LITTLE CHALLENGE','ALL SYSTEMS GO'][level];reset();updateBest()});$('#auto').onclick=()=>{auto=!auto;$('#auto').classList.toggle('on',auto);$('#auto').setAttribute('aria-checked',auto);$('#autoState').textContent=auto?'ON':'OFF';reset();};$('#volume').oninput=()=>{if(master)master.gain.value=muted?0:Number($('#volume').value)*.5};$('#mute').onclick=()=>{initAudio();muted=!muted;master.gain.value=muted?0:Number($('#volume').value)*.5;$('#mute').textContent=muted?'♩':'♫';$('#mute').title=muted?'Unmute audio':'Mute audio';};buttons.forEach(b=>b.onpointerdown=()=>hit(Number(b.dataset.lane)));
window.addEventListener('keydown',e=>{if(e.repeat||$('dialog[open]')||e.target.matches('input'))return;const lane=['d','f','j','k'].indexOf(e.key.toLowerCase());if(lane>=0){e.preventDefault();hit(lane);}if(e.code==='Space'){e.preventDefault();if(elapsed>=duration)reset();togglePlay()}if(e.key.toLowerCase()==='r'){reset();togglePlay()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)togglePlay()});
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x171e20);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x171e20,.042);const camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(0,5.3,14.5);camera.lookAt(0,1,0);
scene.add(new THREE.HemisphereLight(0xc6e0db,0x252b29,2));const mainLight=new THREE.DirectionalLight(0xe3f1d5,3);mainLight.position.set(-3,8,5);mainLight.castShadow=true;mainLight.shadow.mapSize.set(2048,2048);scene.add(mainLight);
const mat=(color,metal=.25,rough=.48)=>new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough});const dark=mat(0x242d2e,.55),black=mat(0x101c20,.4),metal=mat(0x667772,.7),white=mat(0xe6e9d1,.3);
function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,m,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p)}
function cylinder(r,h,m,x,y,z,p,r2=r){return mesh(new THREE.CylinderGeometry(r,r2,h,32),m,x,y,z,p)}
function ball(r,m,x,y,z,p){return mesh(new THREE.SphereGeometry(r,20,16),m,x,y,z,p)}
function rod(a,b,r,m,p){const v1=new THREE.Vector3(...a),v2=new THREE.Vector3(...b),d=v2.clone().sub(v1);const o=cylinder(r,d.length(),m,...v1.clone().add(v2).multiplyScalar(.5).toArray(),p);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return o;}
function glow(c){return new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:2.2})}
box(30,.2,23,mat(0x1c2525),0,-.22,0);box(13,.38,4.8,mat(0x303d3c,.5),0,0,0);box(13,.05,.06,glow(0x8cae87),0,.18,2.42);box(13,7,.2,mat(0x182022),0,3,-3.3);
for(let i=-8;i<=8;i++){box(.018,.008,18,mat(0x34423f),i*1.1,-.11,4);box(25,.008,.018,mat(0x34423f),0,-.1,i*1.1)}for(let x=-6;x<=6;x+=.65)box(.025,4,.08,mat(0x303e3b),x,2.3,-3.12);
for(const x of [-6,6]){box(.14,5,.16,metal,x,2.5,-2.6);for(let y=.6;y<5;y+=.6)rod([x-.2,y,-2.6],[x+.2,y+.4,-2.6],.028,metal);}box(12.4,.15,.18,metal,0,4.9,-2.6);
for(let i=0;i<8;i++){const x=-5.3+i*1.5;const fixture=cylinder(.16,.27,dark,x,4.65,-2.5);fixture.rotation.x=.45;ball(.09,glow(COLORS[i%4]),x,4.48,-2.4);const spot=new THREE.SpotLight(COLORS[i%4],25,13,.37,.8,1);spot.position.set(x,4.45,-2.3);spot.target.position.set(x*.8,.1,.7);scene.add(spot,spot.target);const cone=mesh(new THREE.ConeGeometry(.85,4,32,1,true),new THREE.MeshBasicMaterial({color:COLORS[i%4],transparent:true,opacity:.027,depthWrite:false,side:THREE.DoubleSide}),x,2.5,-2);cone.rotation.z=(i%2?1:-1)*.13;}
for(const x of [-5.5,5.5]){box(.95,1.9,.8,dark,x,1.2,-.1);for(let y of [.65,1.5]){const speaker=cylinder(.32,.05,black,x,y,.34);speaker.rotation.x=Math.PI/2;const ring=new THREE.Mesh(new THREE.TorusGeometry(.28,.025,10,32),metal);ring.position.set(x,y,.38);scene.add(ring);ball(.09,dark,x,y,.4);}box(1.1,.14,1,black,x,.24,0);}
const robots=[],positions=[-3.8,-1.25,1.25,3.8];
function robot(i){const group=new THREE.Group();group.position.set(positions[i],.3,0);scene.add(group);const suit=mat(COLORS[i],.38,.35),light=glow(COLORS[i]);const body=new THREE.Group();group.add(body);for(const x of [-.25,.25]){box(.32,.16,.58,dark,x,.13,.12,body);rod([x,.2,0],[x,.7,0],.105,metal,body);ball(.13,dark,x,.56,0,body);}box(.83,.68,.48,suit,0,1,0,body);box(.61,.28,.06,dark,0,1.03,.27,body);for(let j=0;j<4;j++)box(.065,.09+(j%3)*.035,.02,light,-.18+j*.12,1.03,.31,body);cylinder(.13,.15,metal,0,1.41,0,body);const head=new THREE.Group();head.position.y=1.83;body.add(head);box(1,.67,.64,suit,0,0,0,head);box(.83,.34,.08,black,0,.03,.34,head);for(const x of [-.23,.23]){box(.15,.07,.025,light,x,.04,.39,head);cylinder(.14,.1,dark,x<0?-.55:.55,0,0,head).rotation.z=Math.PI/2;}box(.22,.035,.02,dark,0,-.22,.34,head);rod([.3,.34,0],[.36,.62,0],.024,metal,head);ball(.055,light,.36,.64,0,head);const arms=[];for(const s of [-1,1]){const arm=new THREE.Group();arm.position.set(s*.52,1.22,0);body.add(arm);ball(.14,metal,0,0,0,arm);rod([0,0,0],[s*.1,-.35,.18],.09,suit,arm);ball(.1,dark,s*.1,-.35,.18,arm);rod([s*.1,-.35,.18],[s*.03,-.5,.43],.075,metal,arm);ball(.13,suit,s*.03,-.5,.43,arm);arms.push(arm);}cylinder(.98,.09,mat(0x364340),positions[i],.27,0);const ring=new THREE.Mesh(new THREE.TorusGeometry(.95,.018,8,80),light);ring.rotation.x=-Math.PI/2;ring.position.set(positions[i],.325,0);scene.add(ring);robots.push({group,body,head,arms,ring});}
for(let i=0;i<4;i++)robot(i);
const drumMat=mat(0xd7795c,.45),kit=new THREE.Group();kit.position.set(-3.8,.25,.8);scene.add(kit);const bass=cylinder(.48,.45,drumMat,0,.51,.25,kit);bass.rotation.x=Math.PI/2;const face=cylinder(.42,.025,mat(0xe1d7bb),0,.51,.49,kit);face.rotation.x=Math.PI/2;box(.14,.14,.03,black,0,.51,.51,kit).rotation.z=Math.PI/4;for(let x of [-.48,.43]){cylinder(.24,.23,drumMat,x,.97,.15,kit);cylinder(.23,.02,white,x,1.1,.15,kit);}for(let x of [-.85,.8]){rod([x,0,.1],[x,1.35,.1],.025,metal,kit);cylinder(.37,.026,mat(0xdac391,.7),x,1.35,.1,kit).rotation.z=x*.13;rod([x-.22,.05,.1],[x+.22,.05,.1],.025,metal,kit);}for(let s of [-1,1])rod([s*.55,1.1,.4],[s*.42,1.4,.8],.018,white,robots[0].body);
function guitar(i,color){const p=new THREE.Group();p.position.set(.1,.82,.55);p.rotation.z=-.48;robots[i].body.add(p);ball(.28,mat(color),0,0,0,p).scale.set(1,1.3,.33);ball(.22,mat(color),0,.26,0,p).scale.set(1,1,.4);box(.12,.85,.08,metal,0,.69,0,p);box(.18,.2,.09,mat(color),0,1.2,0,p);box(.15,.1,.02,black,0,.08,.1,p);for(let s=-1;s<=1;s++)box(.008,1.25,.008,white,s*.026,.48,.1,p);for(let y=.38;y<1.12;y+=.1)box(.13,.012,.008,white,0,y,.06,p);}
guitar(1,0xccdf95);guitar(3,0x6db5bb);
const keys=new THREE.Group();keys.position.set(1.25,1.05,.7);scene.add(keys);box(1.45,.15,.47,dark,0,0,0,keys);for(let i=0;i<15;i++){box(.081,.045,.3,white,-.65+i*.091,.1,.07,keys);if(i%7!==2&&i%7!==6)box(.042,.04,.16,black,-.61+i*.091,.137,-.01,keys);}rod([-.5,-.8,0],[.5,0,0],.035,metal,keys);rod([.5,-.8,0],[-.5,0,0],.035,metal,keys);
const particles=new THREE.BufferGeometry(),pts=new Float32Array(180*3);for(let i=0;i<pts.length;i+=3){pts[i]=(Math.random()-.5)*15;pts[i+1]=Math.random()*6;pts[i+2]=(Math.random()-.5)*7;}particles.setAttribute('position',new THREE.BufferAttribute(pts,3));const dust=new THREE.Points(particles,new THREE.PointsMaterial({color:0xd7e6b1,size:.025,transparent:true,opacity:.38}));scene.add(dust);
function resize(){const el=$('.stage');renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();const tr=$('.track-wrap');$('#track').width=tr.clientWidth*devicePixelRatio;$('#track').height=tr.clientHeight*devicePixelRatio;}
new ResizeObserver(resize).observe($('.game'));$('#cameraBtn').onclick=()=>{orbit=!orbit;$('#cameraBtn span').textContent=orbit?'FRONT VIEW':'ORBIT VIEW'};$('#cameraBtn').onkeydown=e=>{if(e.key==='Enter')$('#cameraBtn').click()};const ctx=$('#track').getContext('2d');
function drawTrack(){const c=$('#track'),w=c.width/devicePixelRatio,h=c.height/devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);const top=w*.27,bottom=w*.13,topWidth=w*.46,bottomWidth=w*.74,lineY=h-52;function xAt(l,y){return top+(bottom-top)*(y/lineY)+(topWidth+(bottomWidth-topWidth)*(y/lineY))*l/4}for(let lane=0;lane<4;lane++){ctx.beginPath();ctx.moveTo(xAt(lane,0),0);ctx.lineTo(xAt(lane+1,0),0);ctx.lineTo(xAt(lane+1,lineY),lineY);ctx.lineTo(xAt(lane,lineY),lineY);ctx.closePath();ctx.fillStyle=pulses[lane]>.3?HEX[lane]+'15':lane%2?'#182122':'#141c1e';ctx.fill();ctx.strokeStyle='#35443d';ctx.lineWidth=.7;ctx.stroke();}for(let j=0;j<5;j++){const y=((j/5+elapsed*.18)%1)*lineY;ctx.beginPath();ctx.moveTo(xAt(0,y),y);ctx.lineTo(xAt(4,y),y);ctx.strokeStyle='#33433a55';ctx.stroke();}const lookAhead=level===2?1.65:2.2;for(const n of notes){if(n.done)continue;const dy=n.t-elapsed;if(dy<-.2||dy>lookAhead)continue;const y=(1-dy/lookAhead)*lineY,x=xAt(n.lane,y),nw=xAt(n.lane+1,y)-x;ctx.fillStyle=HEX[n.lane];ctx.shadowColor=HEX[n.lane];ctx.shadowBlur=12;ctx.fillRect(x+nw*.18,y-4,nw*.64,7);ctx.shadowBlur=0;ctx.fillStyle='#fff8';ctx.fillRect(x+nw*.18,y-4,nw*.64,1);}for(let lane=0;lane<4;lane++){const x=xAt(lane,lineY),nw=xAt(lane+1,lineY)-x;ctx.fillStyle=HEX[lane];ctx.shadowBlur=pulses[lane]*25+4;ctx.shadowColor=HEX[lane];ctx.fillRect(x+3,lineY,nw-6,2);ctx.shadowBlur=0;if(pulses[lane]>.2){const g=ctx.createLinearGradient(0,lineY-65,0,lineY);g.addColorStop(0,HEX[lane]+'00');g.addColorStop(1,HEX[lane]+'40');ctx.fillStyle=g;ctx.fillRect(x+3,lineY-65,nw-6,65)}}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.06);last=now;const t=now/1000;if(playing){elapsed+=dt;const b=Math.floor(elapsed/(60/songs[song].bpm));if(b!==beatIndex){beatIndex=b;backing(b);}for(const n of notes){if(n.done)continue;if(auto&&elapsed>=n.t){collect(n);instrument(n.lane,Math.floor(n.t/(60/songs[song].bpm)));}else if(elapsed-n.t>.19){n.done=true;misses++;combo=0;energy=0;judge('MISS','#d88e7b');}}updateHUD();if(elapsed>=duration)finish();}if(now>judgmentUntil)$('#judgment').style.opacity=0;for(let i=0;i<4;i++){pulses[i]=Math.max(0,pulses[i]-dt*3.5);const r=robots[i],groove=playing?Math.sin(t*songs[song].bpm/60*Math.PI*2+i)*.045:Math.sin(t*1.4+i)*.015;r.body.position.y=groove+pulses[i]*.075;r.body.rotation.z=groove*.5;r.head.rotation.y=Math.sin(t*.8+i)*.11;r.head.rotation.z=groove;r.arms[0].rotation.x=-pulses[i]*.5+groove;r.arms[1].rotation.x=pulses[i]*.6-groove;r.ring.material.emissiveIntensity=1.5+pulses[i]*3;}dust.rotation.y=t*.008;if(orbit){camera.position.x=Math.sin(t*.23)*3.8;camera.lookAt(0,1,0);}else{camera.position.x*=.95;camera.lookAt(0,1,0);}renderer.render(scene,camera);drawTrack();}
reset();updateBest();resize();requestAnimationFrame(frame);
